### ISSUE TITLE
Temperatursensoren fehlen

### ISSUE THREAD

**Issue by Apollon77** [thkl/homebridge-homematic#1]
Hi,

ich hab die fehlenden Sachen die ich im Forum geschrieben hab mal hier frech als Issue angelegt:

HM-WDS40-TH-I (Temperatursensor innen)
HM-WDS10-TH-O (Temperatursensor aussen)

Diese hier:
HM-WS550STH-I (Temperaturinnensensor pot. ohne Humidity von CuXd)
findet er zu beginn, aber dann wenn er die Werte hat sind die nicht dabei.

**Comment by thkl** [comment]
Ja, das ist ein kniffligeres Problem. Das ganze System baut auf Channeltypen auf. Jetzt haben die Sensoren den Typ WEATHER. Leider haben die neueren Thermostate auch einen WEATHER Kanal, welcher zusätzlich zum Control Kanal noch mal die Temperaturen führt. Das würde heissen wer ein Thermostat besitzt bekommt das Gerät doppelt in Homekit angelegt.

Hier muss ich mir mal was cleveres einfallen lassen

**Comment by Apollon77** [comment]
In der Konfig ne unterscheidung einbauen wie bei "Outlets" und "doors"?

**Comment by thkl** [comment]
genau das war der plan. sollte jetzt gehen ...  (die filterung wird in internalconfig.json gemacht)

**Comment by Apollon77** [comment]
cool ... sobald es per "npm update" verfügbar ist teste ich es ... oder wie am besten?!

**Comment by thkl** [comment]
sollte als Version 0.0.6 verfügbar sein

**Comment by Apollon77** [comment]
cool, worx!!

**Comment by thkl** [comment]
;o)

**Comment by Apollon77** [comment]
Ääähm ... Die Luftfeuchtigheitswerte fehlen noch, korrekt ?!

**Comment by thkl** [comment]
Ja, hier muss ich mir was einfallen lassen um die Geräte die keine Luftfeuchtigkeit messen können, wegzulassen. Weil der Kanaltyp WEATHER ist nicht eindeutig.

**Comment by Apollon77** [comment]
Ich glaube eher das es eine Ausnahme ist wenn ein Gerät nur Temperatur misst, oder ?!
Die neue Version läuft doch so dfas CCU die Daten pusht oder ?! Damit weisst Du doch ob so ein gerät nur "TEMPERATURE" oder auch "HUMIDITY" gepusht hat ... und danach dann entscheiden ...

Oder halt wieder ein "temp_only_device"-Setting in der Konfig wo man diese Geräte angibt die nur Temperatur haben

**Comment by thkl** [comment]
Ja die CCU pusht. Aber ich lese am Anfang per Rega alle Kanäle ein. Und aus dessen Typ leite ich die HomeKit Geräte ab. Und die gepushten Daten der CCU kommen später. 
Ich denke mal ich nehm die Interneconfig Datei wo ich auch schon die Filter habe da zu Hilfe.

**Comment by Apollon77** [comment]
interne Filterdatei ist ggf schwierig. Bei CUxD kann man pro Gerät entscheidn ob es beides hat oder nicht ... damit gehts kaputt :-( Mindestens für CUxD bräuchte man eine "pro Device-SN"-Möglichkeit

**Comment by thkl** [comment]
Ich kenne das CuxD Problem von meiner IOS App da musste ich auch Köpfstände machen. Der nächste Weg wäre es nicht nur Gerät und Kanäle zu lesen sondern auch Datenpunkte. Aber das geht zu weit.  Ich werde den Feuchtigkeitspunkt für "die 3" Geräte einfach intern festlegen und ausblenden.

**Comment by Apollon77** [comment]
welche 3 sind das in deinen augen?
Oder halt sagen das CUXd Nur mit Humidity supportet ist ... im Notfall kann man es ja in der App ausblenden :-)

**Comment by thkl** [comment]
Ne 3 steht für * ... Ich gugg mir das mal in der Doku an. Man muss ja auch nicht jede ausgefallene Kombination unterstützen.  Ist ja hier auch alles freiwillig.
