### ISSUE TITLE
Thermostat aktualisiert nicht

### ISSUE THREAD

**Issue by timokli** [thkl/homebridge-homematic#101]
Ich habe per

"services": [
    { "type": "HM-WDS10-TH-O:WEATHER",
          "service": "HomeMaticHomeKitCuxDThermostatService"
    }]

ein in CuxD kreiertes Thermostat hinzugefügt welches auch wunderbar angezeigt wird. Leider aktualisiert sich der Temperatur-Wert in Apple Home nicht, obwohl der Wert des Cuxd Devices in der CCU2 korrekt alle paar Minuten aktulaisiert wird.

Was kann ich tun? :)

**Comment by thkl** [comment]
Nichts :) Da ich keinen Notification Service für CuxD implementiert habe wird das so nicht funktionieren.

**Comment by timokli** [comment]
Oh schade, gibts denn alternative Lösungen? Ich nutze ein CuxD Wrapper Thermostat und schriebe dort die Aussentemperatur per CCU Script rein. Das Wrapper Device ist in der CCU ein HM-WDS30-T-O. Wenn ich das Device ganz ohne "service" definition nutze scheint es ebenfalls nicht zu funktionieren.

Wäre sowas denkbar?

 { "type": "HM-WDS30-T-O:WEATHER",
          "service": "HomeMaticHomeKitThermostatService"
    	}

**Comment by timokli** [comment]
habe es hinbekommen, so funktioniert es inkl. humidity:

{ "type": "HM-WDS30-T-O:WEATHER",
"service": "HomeMaticHomeKitThermostatWeatherService"
}

**Comment by timokli** [comment]
es funktioniert leider doch nicht zuverlässig... der Status aktualisiert sich nur dann, wenn man manuell eine Aktion in der Home App macht. Diese Aktion kann das drücken eines Buttons sein, oder auch das Neustarten der App.

Bei welchen Devices gibt es denn einen zuverlässigen Notification Service? Bzw. wie funktioniert dieser denn genau?

**Comment by thkl** [comment]
Siehe oben .. Geräte auf dem CuxD Layer senden keinen Event an das homebridge Modul, wenn sich deren Parameter ändern. Oder besser gesagt, ich abonniere die Events auf dem CuxD Layer nicht.

Daher werden die Werte nur gepullt, wenn HomeKit selber sie abfragt. Und das passiert eben nur wenn man zb einen Raum aufmacht in dem ein Gerät ist....

**Comment by timokli** [comment]
Hi, wie ich bereits geschrieben habe nutze ich zwar ein durch Cuxd erstelltes Gerät, aber kein CuxD Device mehr. Ich nutze nun ein ordinäres HM-WDS30-T-O, also ein Aussenthermometer. Homebridge sollte hiervon nichts mitbekommen, das stellt sich in Homeatic als ganz normales HM Gerät dar.

**Comment by thkl** [comment]
achso .. hmm ich schau mir das mal an .. das könnte man sicher auch in einem normalen eventbehaftetem Service abwickeln ...

**Comment by timokli** [comment]
Da ich jetzt eine HM Wetterstation habe kann ich auf eine Umsetzung/Prüfung nun verzichten ;) Trotzdem danke.
