### ISSUE TITLE
Fenster Anzeige seltsam

### ISSUE THREAD

**Issue by timokli** [thkl/homebridge-homematic#102]
Hallo,
ich habe alle Fenster und Tür-Sensoren laut Anleitung als "windows" bzw. "doors" definiert, jeweils den kanal :1.

Wenn nun ein Fenster/Tür geöffnet wird, dann sieht man in Apple Home den Status "schliessen" und ein sich drehendes Icon oben links. Egal wie lange man wartet, es geschieht nichts weiteres. Erst wenn manuell auf das Fenster-Icon in Home gedrückt wird dann wird auch der korrekte Status "geöffnet" angezeigt.

Beim schliessen eines Fensters wird "wird geöffnet"'angezeigt, ebenfalls mit dem Apple-Rädchen. Auch hier passiert solange nichts bis man den Sensor in Home drückt, erst dann ist "Geschlossen" als Status zu sehen.

Was mir als erstes auffällt ist der verdrehte Status: Beim Schliessen eines Fensters -> "wird geöffnet", beim öffnen eines Fensters -> "schliessen". Kann man hier was invertieren oder ist das ein Bug?

Zudem ist natürlich das viel grösser Problem das die Sensoren nicht automatisch auf den endgültigen Status springen, also "Geschlossen" bzw. Geöffnet".

Ich vermute das hat etwas damit zu tun, dass Homebridge bzw. Appel lediglich motorisierte Fenstersensoren unterstützt. Kann man hier trotzdem irgend etwas machen dass z.b. nach einem Timeout während des "Motor-macht-was-Status" automatisch der endgültige Ziel-Status "Geöffnet" bzw. Geschlossen" angezeigt wird? Anders erkenne ich keinerlei Sinn darin überhaupt nichtmotorisierte Kontaktsensoren in Homebridge zu nutzen, oder?

**Comment by sblogoshs** [comment]
Hallo.

Das Problem habe ich auch und bei mir funktioniert es wenn ich nach einem Start der Homebridge in der eve-app die Fenster einmalig in den bearbeiten Zustand bringe bis zum nächsten Neustart ohne Probleme. Dann wird sowohl in der eve-app als auch in der home-app geschlossen bzw. offen angezeigt.
Aber eben leider nur bis zu einem Neustart der Homebridge!

Gruß sblogoshs

**Comment by bprskalo** [comment]
hallo zusammen

ich würde euch empfehlen die fenster als normale kontaktesensor zu verwenden. in der tat ist es so, dass apple offiziell nur motorisierte fenster als "fenster" untetstützt .. alles andere sind kontaktsensoren.

in der home app könnt ihr dann festlege das der kontaktsensor ein fenster ist und ihr könnt auch bei den benachrichtigungen in der app einstellen das ihr jedes mal eine meldung bekommet wenn das fenster geöffnet oder geschlossen wird. 

es gibt also nur zwei zustände die angezeigt werden können offen oder geschlossen. ein schräggestelltes fenster wird also als offen erkannt.

gruss

bosi

**Comment by sblogoshs** [comment]
Hallo.

Damit geht die Frage an Siri nach geöffneten Fenster/Türen natürlich nicht mehr und das war meines Wissens der Grund für die "doors" bzw. ""windows"  Kennzeichnung.

Gruß sblogoshs

**Comment by bprskalo** [comment]
falsch .. das geht immer noch weil du den Siri namen "fenster" vergibst und den raum festlegst

dann lautet die frage "ist das fenster im schlafzimmer offen" und siri antwortet brav mit "ja" oder "nein" je nach zustand.

ich habe das so bei mir eingestellt und es funktioniert auch :-)

**Comment by sblogoshs** [comment]
...man lernt nie aus, wieder etwas dazugelernt.

Vielen Dank!

Gruß sblogoshs

**Comment by bprskalo** [comment]
gern :-)

**Comment by sblogoshs** [comment]
Hallo.

Ich habs gerade geändert und denke das hatte ich vor einiger Zeit schon einmal (hatte es nur vergessen) und weiß nun warum mir das nicht gefallen hat, da ich hauptsächlich die eve-app verwende und dort dann "ja" für geschlossen  bzw. "nein" für offen steht.

Nur so zur Info.

Gruß sblogoshs

**Comment by bprskalo** [comment]
hast du den sensor typ in der home app auf "fenster" gestellt in den eigenschaften ?

**Comment by sblogoshs** [comment]
Ja das habe ich und alle anderen Möglichkeiten ergeben dasselbe. Ja/Nein

**Comment by bprskalo** [comment]
dann wird es so sein, dass eve den "mehrwert" nicht erkennt und es einfach als sensor gehalten wird .. daher ja/nein ..

ich habe das eve nicht mehr im einsatz, weil die neue home app (und in 10.3 noch besser) mittlerweile alls kann was ich brauche, aber das ist halt immer geschmacksache :-)

**Comment by sblogoshs** [comment]
...ich nutze die eve weil es da bei den Automationen mehr Möglichkeiten gibt, so habe ich bei der home keine Bedingungen und bei eve geht z. B. Temperatur kleiner/gleich/größer. 
Ich habe auch 10.3 und die einzigen  Bedingungen die ich nutzen kann sind Sonnenaufgang/Sonnenuntergang.

Gruß sblogoshs

**Comment by bprskalo** [comment]
eben :-) .. für meinen einsatz genügend .. und ja das ist ein manko mit den regeln :-)

**Comment by timokli** [comment]
ich nutze aus dem grund ja auch alle türen/fenster als kontaktsensor.
ein problem gibt es allerdings bei der umstellung des kontaktsensortyps auf fenster/tür: statusmeldungen werden nicht angezeigt, also "im status anzeigen" hat keine funktion mehr. sobald der typ kontaktsensor benutzt wird funktioniert die statusanzeige wieder.
ist das ein bug?

**Comment by bprskalo** [comment]
meines wissens nach wird die statusmeldung aktuell nur für sensoren unterstützt.

**Comment by thkl** [comment]
Kann das zu gemacht werden ?

**Comment by timokli** [comment]
wenn es keine lösung gibt ja, ist zwar schade aber dann kannman das ja nur so akzeptieren ;)

**Comment by dkrizic** [comment]
Die Lösung ist ganz einfach, die Einträge aus "windows" und "doors" entfernen, so dass alle Fenster und Türen Kontakte sind, diese kann man dann in der Home App als Türen, Fenster (oder wie in meinem Fall auch Garagentor) einstellen. Ab iOS > 10.2 kann man für diese Geräte AUCH Benachrichtigung einschalten, daher ist das ein vollwertiger Ersatz.

**Comment by timokli** [comment]
@dkrizic wie oben schon geschrieben gibt es da noch ein Problem bei Nutzung des Typs Tür/Fenster: statusmeldungen werden nicht angezeigt, also "im status anzeigen" hat keine funktion mehr. sobald der typ "kontaktsensor" benutzt wird funktioniert die statusanzeige wieder. 

Damit kann ich aber leben, auch wenn die Icons von Tür und Fenster schöner wären ;)

**Comment by dkrizic** [comment]
Ok, aber das Problem habe ich hier nicht, schau mal:

![img_8608](https://cloud.githubusercontent.com/assets/1181349/25901386/8c8e207c-358e-11e7-9ffb-cb8193d76a9c.jpg)
![img_8609](https://cloud.githubusercontent.com/assets/1181349/25901385/8c317cdc-358e-11e7-87c3-434f84ebbc69.jpg)

**Comment by timokli** [comment]
Ich glaube wir reden aneinander vorbei :) Ich meine die Einstellung "Im Status anzeigen"
![img_4702](https://cloud.githubusercontent.com/assets/25152397/25901885/5933733a-3598-11e7-8c84-49f62fde5556.PNG)

Wenn die aktiv ist, dann werden offene Kontaktsensoren als Text auf der Übersichtsseite angezeigt:
![img_4703](https://cloud.githubusercontent.com/assets/25152397/25901923/713e3b9a-3598-11e7-82c4-0b28b0b1f9dd.png)

Sobald der Typ nicht "Kontaktsensor" ist, funktioniert diese Text-Statusanzeige nicht mehr. In den Details sehe ich die offenen Sensoren trotzdem, aber da muss ich ja extra manuell draufklicken, was ich nicht möchte ;)

**Comment by dkrizic** [comment]
Ah, ok, stimmt... Gut, damit kann ich leben, wenn ich das Haus verlasse und sehen will, ob alles zu ist, gehe ich auf die "Status Details" Seite und sehe es dort. Der Punkt war mir garnicht aufgefallen. Danke, dass wir das geklärt haben.

**Comment by timokli** [comment]
Bei mir hängt ein iPad an der Wand und beim Verlassen des Hauses ist die Anzeige für den flüchtigen Blick super :)
