### ISSUE TITLE
HM-WDS100-C6-O-2 fehlende Sensoren

### ISSUE THREAD

**Issue by timokli** [thkl/homebridge-homematic#103]
Ich habe eine Wetterstation HM-WDS100-C6-O-2 integriert, allerdings fehlen mir in der Home App einige Sensoren (Regen ja/nein, Windrichtung, Windgeschwindigkeit). Es sind nur die Sensoren für Temperatur, Luftfeuchte und Helligkeit vorhanden. Seltsamerweise sind in der Eve App alle diese Sensoren zu sehen, nur in der Home App nicht. Woran könnte das liegen?

**Comment by timokli** [comment]
Hast du dir das mal ansehen können? Oder kann ich noch etwas tun?

**Comment by thkl** [comment]
Das liegt daran, das die in HomeKit (noch) nicht unterstützt werden. Eve bringt einige eigene Datentypen mit ..

**Comment by timokli** [comment]
hi, any news to this with ios11?
