### ISSUE TITLE
Homekit Homepilot

### ISSUE THREAD

**Issue by Tarsonion** [thkl/homebridge-homematic#104]
Hallo zusammen,

ich habe ein Problem mit der Homebridge für den Rademacher Homepilot.

Ich habe es geschafft, daß Homebridge auf dem RPi läuft und auch den Homepilot erkennt.
Derzeit habe ich am Homepilot 3 Geräte. 1 Gurtwickler und 2 Rollladenmotoraktoren.
Die Homebridge erkennt allerdings nur den Gurtwickler, den ich auch im Homekit steuern kann. Die Aktoren werden hingegen nicht erkannt.
Eingebunden haben ich das ganze über die Rademacher-Blinds.....

Kann mir da jemand weiterhelfen?

gruss
Tarsonion

**Comment by dkrizic** [comment]
Sind das HomeMatic-Komponenten, ich kenne sie nicht...

**Comment by thkl** [comment]
Wenn dann bräuchte ich die HM-.... Typenbezeichnungen
