### ISSUE TITLE
Disable Switch Function in Homematic Powermeter Plug

### ISSUE THREAD

**Issue by drschnalli** [thkl/homebridge-homematic#105]
Hello, is there any way to disable the switch fuction for the powermeter plug? My computer is plugged into it and i dont want to accidentally turn it off... the outlet option is no option for me (which is a very good option by the way... using it for sound devices) because i can still turn it on and off. I even found no way to disable it on my ccu2..

**Comment by thkl** [comment]
i have to build in this ...

**Comment by thkl** [comment]
ok i implemented that in 0.0.75. if you set the channel to read only (CCU device settings) all switch events will be ignored. Currently the indicator at the HomeApp will do the switch (i can not change the permissions at runtime) but will be ignored. (i will try to change this in a later update)

**Comment by XerXes777** [comment]
Please the same for variables.
A sample:
"variables": ["Variable1"],
"variables_disable_switch_function": ["Variable2"],
The Variable1 is a normal switch.
The Variable2 is a switch too, but it is not possible to switch on/off. Only to show the state.

**Comment by thkl** [comment]
oh i think this is to much ... you may solve this via CCU by yourself:

1. copy the variable to a 'shadow'
2. create a program which acts on a change of the original variable and copies the value 
3. import the shadow to homebridge ...
