### ISSUE TITLE
Türklingelsensor 

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#106]
Ich habe den Türklingelsensor HM-Sen-DB-PCB. Der wird von HBHM unterstützt. Allerdings funktioniert er nicht, er meldet nichts. Er hatte mal funktioniert. Liegt das an:

- HomeKit 
- HomeBridge
- HomeBridge-HomeMatic

Was kann man tun?

Zweite Frage: Kann man einen "normalen" Sensor (z.B. HM-PBI-4-FM) als Türklingelkontakt konfigurieren?

**Comment by Samfox2** [comment]
Doorbell funktioniert nicht mehr als "Einzelservice". Homekit verlangt nun, dass der doorbellservice mit etwas kombiniert wird, z.B. Eine Kamera oder einen Motionsensor. Hier ein Bsp.: https://github.com/Maxmudjon/HAP-NodeJS-accessories/blob/master/Video_Doorbell_accessory.js

**Comment by dkrizic** [comment]
Also ein Feature von iOS 10.3?

**Comment by Samfox2** [comment]
Naja, "feature" ist das wohl nicht gerade... Eine Umsetzung sollte aber wohl machbar sein, das device muss halt einfach auf Motionsensor geändert werden und dann noch als Zusatz eine doorbell anhängen.

**Comment by dkrizic** [comment]
Ich hätte im Raum einen Motion Sensor, vielleicht wäre es cool, wenn man in der config.json solche Dinge kombinieren könnte, d.h. den Motion Sensor als Accessory und den Türklingelsensor (oder andere Contacts) als Doorbell Service. 

Macht das Sinn?

**Comment by Samfox2** [comment]
Ja, macht Sinn. Über eine extra Option könnte man an den Motionsensor den Doorbell-Service mit ranhängen. Der muss dann im Falle eines Auslösens ein "Programmableswitch"-Event mit Wert 0 setzen. Das sollte funktionieren. Falls im gleichen Raum noch eine Kamera vorhanden ist, sollte dann auch ein Bild mitkommen.

**Comment by thkl** [comment]
hmmm ich könnte das DoorBell Device gleich als Motion Sensor implementieren. Dann ist zwar die Meldung bissel komisch, die beim Klingeln kommt aber hey es würde funktionieren ...

**Comment by Samfox2** [comment]
Jup, vielleicht einfach mal ausprobieren wie das ausschaut.

**Comment by Vaniffew** [comment]
Hallo zusammen, ich schließe mich der Runde einmal an.
Eine ähnliche Konstellation läuft bei mir.

- HM Funk-Klingelsignalsensor (HM-Sen-DB-PCB)
- HM Funk-Tür-/Fensterkontakt, optisch (HM-Sec-SCo)

Ab morgen hätte ich ein ein HM Bewegungsmelder.

Der Klingelsignalsensor wird von der home.app als KEY DEVICE erkannt. Ist das so korrekt, dass ich nachher Benachrichtigung erhalte und eventuell mit integrierter Kamera ein Bild? Erstmal geht es um die Benachrichtigung selbst. Kann mir jemand auf die Sprünge helfen, was genau ich anpassen muss? 
Des Weiteren: Kann mir jemand verraten, wo ich auf dem Raspberry Pi die channel_config.json finde?

Danke im voraus.

**Comment by Samfox2** [comment]
Hi, Benachrichtigungen durch den Klingelsensor sollten erst wieder nach den angesprochenen Änderungen funktionieren, dann auch ggf. mit Bild.

**Comment by thkl** [comment]
OK im aktuellen Commit ist diese Funktion drin.
Es gibt einen neuen Service HomeMaticHomeKitDoorBellMotionService dafür. Man muss in der Datei ChannelServices\channel_config.json für den Eintrag HM-Sen-DB-PCB:KEY den Service anpassen.

Ich überlege noch wie ich das Userfreundlicher machen kann.

**Comment by thkl** [comment]
Ist die GitHub Version nicht so gut? Soll ich ein npm draus machen ?

**Comment by dkrizic** [comment]
Hi, npm-Version ist immer gut. Normalerweise teste ich solche Dinge sofort, das werde ich jetzt auch tun. Ich kämpfe momentan mit drei Problemen:

- Aus irgendwelchen komischen Gründen kann ich die CCU Web UI nicht mit dem Safari/Mac öffnen, während es auf dem iPhone ohne Probleme klappt
- Ich hatte gestern mit der 0.0.71 einen Crash (siehe unten)
- HomeBridge lauft auf meinem Debian nur IPv6, announced aber IPv6 und IPv4, daher habe ich öfter mal "No Response"...

**Comment by dkrizic** [comment]
Interessant ist, dass HBHM ca. eine Minute braucht, um die Liste der Geräte zu ziehen:

```
May  7 11:37:30 supermicro homebridge[453]: [5/7/2017, 11:37:30 AM] [HomeMatic CCU] NPM 0.0.71 vs Local 0.0.71
May  7 11:38:23 supermicro homebridge[453]: [5/7/2017, 11:38:23 AM] [HomeMatic CCU] Fetch Response
```

**Comment by thkl** [comment]
So ich hab 0.0.72 gebaut. Wichtig ist, ich habe noch keinen Config Switch dafür. Deswegen muss in der channel_config.json für  HM-Sen-DB-PCB:KEY die Serviceklasse getauscht werden. Sieht man aber schon.

Die Fehlermeldung könnte daher kommen, das 2 Geräte den selben Namen haben

**Comment by dkrizic** [comment]
Den gleichen Namen: In HomeMatic oder HomeKit?

Die GitHub-Version läuft jetzt, es erscheint ein Motion Sensor. Wenn ich jetzt klingel, müsste eine "Motion" gemeldet werden?

**Comment by thkl** [comment]
richtig dann wird für 1sek der Bewegungsmelder ausgelöst

**Comment by dkrizic** [comment]
Es funktioniert. Die Lösung ist nicht perfekt, aber sie tut es erstmal, mal sehen, was HomeKit in iOS > 10.3 bietet.

**Comment by Samfox2** [comment]
Ja, funkioniert auch mit der npm version. Versuch doch mal noch einen doorbell service an den Motionsensor dranzuhängen und diesen auszulösen, dann sollte die Meldung etwas eindeutiger sein.
