### ISSUE TITLE
Status von Variablen

### ISSUE THREAD

**Issue by timokli** [thkl/homebridge-homematic#107]
Hallo, leider werden eingebundene Variablen in der Home App wohl nicht regelmässig aktualisiert, ausser man startet die Home App neu. Andere Devices funktionieren. Kann man hier irgendetwas machen? Ich nutze die Variablen z.b.für die Anwesenheitsanzeige, da bin ich auf eine automatische Aktualisierung der Anzeige angewiesen.

**Comment by thkl** [comment]
Das Problem ist, das die CCU keine Events sendet, wenn sich eine Variable ändert, aber da gibt es eine Lösung über einen Virtuellen Key .. dessen Kanaladresse in der config.json unter dem Key variable_update_trigger_channel eintragen. Immer wenn sich eine Variable ändert muss die CCU diesen Key "drücken" (zb durch ein Programm auslösen). Immer wenn jetzt dieser Virtuelle Key Event ausgelöst wird, lädt das homematic Plugin alle Variablenwerte neu aus der CCU

**Comment by timokli** [comment]
hi, habe es eben versucht:

das programm in der ccu eingerichtet: funktioniert, es wird ein langer tastendruck ausgeführt.

in der config.json habe ich den parameter 
"variable_update_trigger_channel":["BidCos-RF.BidCoS-RF:1"],
eingefügt.

das virtuelle,device habe ich in das gewerk "homekit" aufgenommen. in der home app sehe ich jetzt auch ein neues device, allerdings erkannt als "virtual_key".

allerdings aktualisieren sich die variablen nach wie vor nicht. hab ich noch einen denkfehler?

**Comment by thkl** [comment]
Der Trigger reagiert auf Kurzen Tastendruck ;)

**Comment by timokli** [comment]
leider hilft das auch nicht. in der home app wird der virtual key kurz grösser, d.h. der tastendruck wird offensichtlich ausgeführt. am variablenstatus öndert sich aber leider nichts.

**Comment by thkl** [comment]
oops Tschuldigung. Nicht die Channeladresse kommt dort rein, sondern der Name der Taste.

**Comment by timokli** [comment]
leider funktioniert es auch nicht mit
      "variable_update_trigger_channel":["HM-RCV-50 BidCoS-RF:1"],

**Comment by thkl** [comment]
ok ich werd mir das bei Gelegenheit mal genauer anschauen

**Comment by timokli** [comment]
super, wenn ich was tun kann gib bescheid. danke schon mal.

**Comment by timokli** [comment]
ich glaube ich habe es hinbekommen: Es wird wirklich der Name der Taste genutzt, allerdings muss im Config File der Name wohl ohne die eckigen Klammern angegeben werden:

"variable_update_trigger_channel": "Hombridge_Trigger",

**Comment by timokli** [comment]
Eben nochmals komplett durchgespielt: Funktioniert!

**Comment by Sillium** [comment]
Hmm, funktioniert bei mir leider noch nicht.

config.json: `"variable_update_trigger_channel": "Homebridge_Trigger"` und `"subsection": "HomeKit"`

Homematic CCU2: Virtuellen Taster umbenannt in "Homematic_Trigger", zu Gewerk "HomeKit" hinzugefügt.

Homebridge neu gestartet, HomeKit-Home komplett entfernt und Homebridge neu hinzugefügt. Leider tauchen alle Geräte auf, nur der Homematic_Trigger nicht. Habe ich noch etwas offensichtliches übersehen?

**Comment by JensBonse** [comment]
Hallo zusammen,
ich habe das gleiche Problem wie @Sillium .
Habe in der config.json "variable_update_trigger_channel": "Trigger" eingefügt.
Habe in der CCU den Virtuellen Key (HM-RCV-50 BidCoS-RF:1) in Trigger umbenannt.
Habe auf der CCU ein Program erstellt, welches auf Aktualisierung der Variable Trigger_Test (ein boolean) jeweils bei True und False den Virtuellen Key 'Kurz' auslöst.

In der Home App (oder auch EVE) sehe ich jedoch keine Aktualisierung.
Ich hoffe irgendwer kann mir da helfen.

**Comment by nicoh88** [comment]
![homebridge-homematic_variablen](https://user-images.githubusercontent.com/264264/42757786-87047576-8901-11e8-86bc-f9cf7d4557d5.png)

https://github.com/thkl/homebridge-homematic/wiki/Variablen
