### ISSUE TITLE
update 0.0.71

### ISSUE THREAD

**Issue by noereg** [thkl/homebridge-homematic#109]
hello everybody 

everything was running well until i updated

after updating to version 0.0.71 it shows the following errors

> /usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/protocol.js:28
>        var content = Buffer.alloc(0);
>                             ^
>
>TypeError: Buffer.alloc is not a function
>    at Object.Protocol.encodeRequest (/usr/local/lib/node_modules/homebridge->homematic/node_modules/binrpc/lib/protocol.js:28:30)
>    at methodCall (/usr/local/lib/node_modules/homebridge->homematic/node_modules/binrpc/lib/client.js:168:35)
>    at HomeMaticRPC.connect (/usr/local/lib/node_modules/homebridge->homematic/HomeMaticRPC.js:226:17)
 >   at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:147:10
 >   at Server.<anonymous> (/usr/local/lib/node_modules/homebridge->homematic/HomeMaticRPC.js:277:39)
 >   at Server.g (events.js:260:16)
 >   at emitNone (events.js:67:13)
 >   at Server.emit (events.js:166:7)
  >  at emitCloseNT (net.js:1523:8)
  >  at nextTickCallbackWith1Arg (node.js:426:9)

is there a possibility to downgrade to Version 0.0.70 

thanks

**Comment by thkl** [comment]
Please update your node.js . that will fix this issue...

**Comment by noereg** [comment]
thank you now it works
