### ISSUE TITLE
Switch wie Variablen einbinden

### ISSUE THREAD

**Issue by Omega236** [thkl/homebridge-homematic#110]
Hallo,

bei Variablen kann man im Homekit den Typ (Licht, Lüfter, Schalter) auswählen. So kann man z.B. Beamer, Waschmaschine .. super steuern ohne dass wenn man sagt Alle lichter aus dass dann die Waschmaschine ausgehen.

Wenn man nun in CuxD ein Virtuellen Switch erstellt, wird dieser immer als Licht eingebunden.

Eine Variable zu erstellen und in Homebridge einzubinden ist aber weit aufwendiger als ein Virtuelles Device. 

Kann man irgendwo einstellen dass ein CuxD Switch wie eine Variable im Homekit eingebunden wird?

Danke schonmal

**Comment by Omega236** [comment]
Ich habe nun in der HomeMaticHomeKitSwitchService.js 
lightbulb = new Service["Lightbulb"](this.name);
Durch 
lightbulb = new Service["Switch"](this.name); 
ersetzt. Jetzt macht es genau was ich will.
Leider wird dies ja bei der nächsten Version überschrieben. Aber eine Anpassung an der HomeMaticHomeKitSwitchService in der nächsten Version ist auch nicht Gut da sonst jeder alle Switche neu benennen und auf Licht umstellen müsste.

Irgend ne Idee wie ich das dauerhaft so hinbekomme?

**Comment by thkl** [comment]
Aktuell kannst Du (siehe Readme) eine eigene ServiceClass anlegen und die in der config.json angeben. Also einfach das File HomeMaticHomeKitSwitchService.js kopieren umbauen und wie in der Readme angegeben einbinden.

**Comment by Omega236** [comment]
Hallo,

ich habe unter /usr/lib/node_modules/homebridge-homematic/ChannelServices meine Neue Datei HomeMaticHomeKitSwitchServiceAsSwitch.js erstellt (hier meinen Speziellen code angepasst und in die Config-Datei `"services": [
        {
 "type": "SWITCH",
"service": "HomeMaticHomeKitSwitchServiceAsSwitch"
}
        ]
` . Das hat auch alles Wunderbar funktioniert.

Leider wurde /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSwitchServiceAsSwitch.js beim Update gelöscht :(

Wo kann ich meine eigene Datei ablegen ohne dass sie mir wieder gelöscht wird?

**Comment by thkl** [comment]
ab der aktuellen Version 0.0.76 können die custom Serviceclasses im config Verzeichnis abgelegt werden. Bitte beachten, das diese beim Laden die ParentClass HomeKitGenericService benötigen. Ich hab das mal im HomeMaticHomeKitSwitchService.js so umgebaut, das es funktioniert.
Die Definition welcher HM Typ welche Klasse lädt kann in der config.json erfolgen. Siehe Readme

**Comment by Omega236** [comment]
Hallo 

Danke schonmal. Aber ich versteh es jetzt nicht ganz. Ich habe nun meine Custom class und die HomeKitGenericService in des config.json abgelegt. Das funktioniert ist aber wohl nicht so gedacht. 

Ich kann leider nicht erkennen was bzw wie du das meinst dass du die Homematichomekitswitchservice.js umgebaut hast.

**Comment by thkl** [comment]
Ich meine den Teil hier : 

`// Attention : If you move the clazz outside the buildin channelservice you have to make sure the superclass HomeKitGenericService
// is reachable 

var parentPath = path.dirname(module.parent.filename);
var rootClazzPath = path.join(parentPath,'ChannelServices','HomeKitGenericService.js');
var rootClazz = require(rootClazzPath).HomeKitGenericService

util.inherits(HomeMaticHomeKitSwitchService, rootClazz);

`

**Comment by Omega236** [comment]
Komisch. Warum find ich das nirgends im Code? Den letzten Commit den ich sehe ist vom 25.05.2017. ist das so?

**Comment by thkl** [comment]
weil der Trollel (thats me :o) ) vergessen hat es einzuchecken ...

**Comment by Omega236** [comment]
Hallo,

ja es funktioniert.

Danke :)

Aber ist es Absicht dass am Ende der Datei ein ; fehlt?

**Comment by roe1974** [comment]
Hallo
Beschäftige mich erst seit kurzem mit Homematic/Homebridge ...
Wie kann ich jetzt richtig die Lampen als Schalter darstellen ... was wäre der richtige weg in der aktuellen Version  0.0.76 ?
danke !
lg
