### ISSUE TITLE
Siri keine Prozent Werte

### ISSUE THREAD

**Issue by hans-peter123** [thkl/homebridge-homematic#113]
Hallo,

habe schon erfolgreich die Bridge ne weile am laufen.

Mir ist nun aufgefallen dass seit einiger Zeit (Kann leider nichts genaueres sagen) Siri keine Prozentwerte mehr sagt. 
Das Läuft dann so: "Rolladen 50%"
"OK, ich habe Jalousien auf"

Un 'mitten im Satz' ist dann Ende :(

Ich habe auch schon mal "mein Haus gelöscht" und den Accessoires und persist Ordner + ccu.json. Danach aber immer noch der selbe Fehler.

Mein ihr das Liegt an der Bridge? Oder an irgendwas anderem.
Meine CCU ist diese hier (Aktuellste Version): https://github.com/jens-maus/RaspberryMatic

Hat damit auf jeden fall mal funktioniert, kann es sein dass sich da mal was geändert hat. Oder ich was freigeben muss...

Hat jemand eine Idee? Danke schön :)

Übrigens in der Home App ist alles ok, und da kommen auch die Werte...

**Comment by thkl** [comment]
Hmm das wird wohl an Siri liegen.  Wenn die Werte in der Home App stimmen werden die korrekt zu HomeKit geliefert.

**Comment by hans-peter123** [comment]
Müssten die Werte auch bei anderweitig Veränderung nachträglich in der App verändert werden? Also wenn ich meinen Rolladen über die Weboberfläche verändere...
Weil das funktioniert nicht.

**Comment by Omega236** [comment]
Bei mir werden die Prozentwerte auch nicht mehr gesagt :( liegt aber meiner Meinung nach an Siri
