### ISSUE TITLE
HmIP-BSM (Schalt-MessAktor) funktioniert nicht mehr

### ISSUE THREAD

**Issue by Omega236** [thkl/homebridge-homematic#114]
Der LichtSchalter hatte bisher immer funktioniert.

Ich vermute sei 0.7x funktioniert er nicht mehr.

Laut Home App wird es geschalten aber es passiert nichts. Aktualisierungen bekommt er auch nicht mit (wenn über WebUI geschalten).
[StartLog.txt](https://github.com/thkl/homebridge-homematic/files/1005745/StartLog.txt)
[Config.txt](https://github.com/thkl/homebridge-homematic/files/1005746/Config.txt)

**Comment by thkl** [comment]
Ja ich weiss, es gehen gerade keine HMIP Geräte. Ich habe die Kommunikation auf binrpc umgestellt, aber das HMIP Interface kann das dummerweise nicht. Ich seh zu das ich das schnell fixe

**Comment by thkl** [comment]
in 0.0.73 gefixt
