### ISSUE TITLE
HM-LC-Ja1PBU-FM:JALOUSIE

### ISSUE THREAD

**Issue by pacco81** [thkl/homebridge-homematic#116]
Folgendes Gerät wird leider noch nicht unterstützt:

There is no service for HM-LC-Ja1PBU-FM:JALOUSIE

HM-LC-Ja1PBU-FM:JALOUSIE
https://www.elv.de/homematic-jalousiesteuerung.html
ELV Homematic Jalousiesteuerung, Komplettbausatz
Artikel-Nr.: 68-15 00 93

<img width="618" alt="bildschirmfoto 2017-06-01 um 22 28 10" src="https://cloud.githubusercontent.com/assets/29131107/26699313/a7a462e4-4719-11e7-9f33-121a18c08a11.png">

devconfig.cgi
Channel configuration for JALOUSIE OEQ0xxxxxxxxx:1
Device firmware version 2.11
Device Parameters
INTERNAL_KEYS_VISIBLE		
LOCAL_RESET_DISABLE		
Firmware Update
Restore Config
Channel Parameters
AES_ACTIVE		
CHANGE_OVER_DELAY		s (0.500000-25.500000)
POSITION_SAVE_TIME		s (0.100000-25.500000)
REFERENCE_RUNNING_TIME_BOTTOM_TOP		s (0.100000-6000.000000)
REFERENCE_RUNNING_TIME_SLATS		s (0.000000-10.000000)
REFERENCE_RUNNING_TIME_TOP_BOTTOM		s (0.100000-6000.000000)
REFERENCE_RUN_COUNTER		(0-255)
STATUSINFO_MINDELAY	
	s (0.500000-15.500000)
STATUSINFO_RANDOM		s (0.000000-7.000000)
TRANSMIT_TRY_MAX		(0-10)
Values
DIRECTION	NONE 		
DIRECTION_SLATS	NONE 		
INHIBIT			
INSTALL_TEST			
LEVEL	 100% (0.000000-1.000000)	
LEVEL_COMBINED			
LEVEL_SLATS	 100% (0.000000-1.000000)	
STOP			
WORKING			
WORKING_SLATS

**Comment by thkl** [comment]
Welches Homekit Gerät wäre denn hier passend ?

**Comment by pacco81** [comment]
Für den Anfang würde mit eine Ansteuerung wie bei den normalen Homematic-Rolloaktoren reichen.

Ich habe kein Homekit Device gefunden, welches neben der Jalousiehöhe auch die Eigenschaft wie Level_Slats also Lamellenposition besitzt.

**Comment by Omega236** [comment]
Zur Info, so muss die Services Sektion in der config.json aussehen:

`"services": [
{
"type":"HM-LC-Ja1PBU-FM:JALOUSIE",
"service": "HomeMaticHomeKitBlindService"
}
  ]
`

Aber wäre schön wenn das fest eingebaut wird.

**Comment by thkl** [comment]
BTW es gibt eine GitHub App für iOS (CodeHub) ..

**Comment by xxxchris** [comment]
Hallo Zusammen,
ich hab mir den Code in der channel-config.json eingebaut und mir ist aufgefallen, dass kurz nach Start der Homebridge in der CCU2 alle Geräte nacheinander auf "Kommunikationsstörung" gehen. Nachdem ich die Jalousie aus dem HomeKit Gewerk genommen habe, war alles wieder in Ordnung.
Stört sich da der Service und es werden Daten übermittelt, dass in der CCU2 etwas abstürzt?
