### ISSUE TITLE
Virtueller Taster

### ISSUE THREAD

**Issue by timokli** [thkl/homebridge-homematic#117]
Ich habe einen Virtuellen Taster der CCU über das Gewerk eingebunden, nun wird dieser in Homebridge bzw. der Home App als "Virtual_Key" angezeigt, für welchen in der Home App Aktionen konfiguriert werden können.

Ich möchte aber keine Aktion hinterlegen, sondern die in der CCU hinterlegte Aktion für den virtuellen Taster triggern.

Wie kann ich in der Home App einen Taster bereitstellen ohne diesen dort konfigurieren zu müssen? Gibt es da eine andere Geräteklasse?

**Comment by thkl** [comment]
soweit ich weiss, kennt HomeKit keine Taster ....

**Comment by timokli** [comment]
ok, gäbs dann irgend eine idee für einen workaround? eventuell ein programm dass einfach nur den ccu taster betätigt? oder eine variable?

**Comment by thkl** [comment]
du kannst ccu programm aus homekit bedienen
