### ISSUE TITLE
Rolladenaktor als Garagentor ausgeben?

### ISSUE THREAD

**Issue by Calprainn** [thkl/homebridge-homematic#118]
Hallo,

ich verwende einen Funk-Rollladenaktor (HM-LC-Bl1-FM) um damit mein Garagentor zu bedienen. Softwareseitig ist der Aktor mit RaspMatic verbunden, was wiederum mit der Homebridge auf meinem Ubuntu Server verbunden ist. Soweit funktioniert das ganze auch problemlos mit Homekit. Nur eine Kleinigkeit stört mich: Homekit erkennt den Rollladenaktor natürlich als Jalousie (Blind) und nicht als Garagentor. 

Gibt es eine Möglichkeit der Homebridge vorzugaugeln, dass mein Aktor ein Garagentor oder eine Tür ist, damit Homekit diesen als solche erkennt?

**Comment by Omega236** [comment]
In CuxD virtuelles device erstellen und mit Programm "verknüpfen". 
Oder rolladenaktoren  über die Config.json als anderen Service einbinden. Das wirkt sich aber auf alle rolladenaktoren aus.

**Comment by Calprainn** [comment]
Ich wüsste jetzt nicht wie ich CUxD unter Raspmatic installieren soll.

Wie binde ich denn den Rolladenaktor als bspw. Door Service ein? Da ich nur diesen einen Aktor habe, wäre die Vorgehensweise nicht schlimm.

Aktuell sieht meine config so aus:
```
{
	"platform": "HomeMatic",
	"name": "HomeMatic CCU2",
	"ccu_ip": "192.168.124.62",
	"filter_device": [],
	"filter_channel": [],
	"outlets": [],
	"doors": [],
	"programs": [],
	"accessories": [],
	"subsection": "Homekit"
   },
```

Mein Rolladenaktor: BidCos.RF.NEQ1536944:1

Danke!!

**Comment by thkl** [comment]
Es gibt in HomeKit einen Garagentor Öffner .. da könnte man quasi eine eigene Serviceklasse für bauen. Das Ding verhält sich ähnlich einem Motorisieren Fenster .. Es kennt also als Zustände zu und offen.

Würde es funktionieren, wenn Dein Rolloaktor von Homekit auch nur 0% und 100% bekommt ?

**Comment by Calprainn** [comment]
Im Grunde besteht mein Garagentor aus einer großen Jalousie, die über einen Zugmotor und dem o.g. Homematic-Funkschalter geschaltet wird. Genaugenommen erkennt ja auch dein Plugin den Schalter richtig und in der Eve App kann ich auch "die Jalousie" mit 0% und 100% schalten. Wenn jetzt in Homekit aus der Jalousie ein Garagentor werden würde, das ich auf und zu (0% und 100%) schalten könnte, wäre das super. ;-)

**Comment by thkl** [comment]
ja, das ginge über eine eigene Serviceclass die halt auf der einen Seite den Rolloaktor anspricht und auf der anderen Seite als Garagentoröffner erscheint. Man kann das in der config.json für jedes Gerät festlegen wenn man möchte

**Comment by Calprainn** [comment]
Leider reichen meine Programmierkenntnisse für solch ein Vorhaben nicht aus.

**Comment by mach1009** [comment]
Ist es möglich, dass mal jemand ein Beispiel dafür nennt, wie man ein bestimmtes HM-Gerät (Name oder Seriennummer) mit einer anderen Geräteklasse versehen kann?

**Comment by thkl** [comment]
hier sind die passenden Klassen : https://github.com/thkl/homebridge-homematic/tree/master/ChannelServices

**Comment by mach1009** [comment]
Ja, das habe ich verstanden. Wie ich eine Geräteklasse mit einem anderen Service verbinden kann ist ja in der Readme beschrieben. 
Allerdings fehlt mir der entscheidende Hinweis wie ich nur ein einziges HM Gerät ändern kann.

**Comment by thkl** [comment]
Es geht momentan nur für einen Gerätetypen aber nicht für eine spezielle Geräteadresse

**Comment by mach1009** [comment]
Schade. Genau so hätte ich es gebraucht. Danke

**Comment by thkl** [comment]
ja ggf bau ich das irgendwann mal ein

**Comment by mach1009** [comment]
Das wäre cool. Da ja mit iOS 11 weitere Typen kommen sollen, wäre das sicher sinnvoll.

**Comment by Calprainn** [comment]
Ich habe jetzt mal selber mein Glück probiert, aber wie vermutet, es scheitert an meinen Kenntnissen. So ganz verstehe ich das mit dem Servicesclass und den entsprechenden Änderungen in der config.json nicht.

Wäre denn jemand bitte bereit, mir bei einer Lösung zu helfen?
Ich möchte gerne das mein Funk-Rollladenaktor (Bezeichnung: HM-LC-Bl1-FM, S/N: NEQ1536944:1) statt als Jalousie (BLIND) in Homekit als Garagentor (ich schätze mal DOOR wäre der entsprechende Service?) erkannt wird. Was müsste ich in welcher Datei ändern/hinzufügen damit das funktioniert? Meine derzeitige Config steht weiter oben.

Vielen Dank!

**Comment by thkl** [comment]
Ich muss den Core erweitern damit man einzelnen Geräten eigene Serviceklassen verpassen kann.

**Comment by Calprainn** [comment]
Also geht das, was ich da vor habe, in der aktuellen Konstellation noch nicht so einfach zu bewerkstelligen?

**Comment by thkl** [comment]
Nein
