### ISSUE TITLE
Kein Update von 0.0.69 auf 0.0.76 ?

### ISSUE THREAD

**Issue by Robiv8** [thkl/homebridge-homematic#119]
sudo npm -g update homebridge-homematic
kommt das:
[..................] - : info using node@v6.11.0
das rädchen dreht sich kurz!
Und alles bleibt beim alten? Kein Update wird durchgeführt.

[2017-06-22 22:46:41] [HomeMatic CCU] NPM 0.0.76 vs Local 0.0.69
[2017-06-22 22:46:41] [HomeMatic CCU] There is a new Version available. Please update with sudo npm -g update homebridge-homematic

**Comment by bprskalo** [comment]
hallo

versuche es mal so

sudo npm install -g --unsafe-perm homebridge-homematic

**Comment by Robiv8** [comment]
Mach ich Heute Abend! Danke schon mal.

**Comment by bprskalo** [comment]
ok, versuche doch mal das file direkt anzusprechen 

sudo npm install -g --unsafe-perm https://github.com/thkl/homebridge-homematic.git

**Comment by Robiv8** [comment]
Super
Das hat geklappt.
