### ISSUE TITLE
HMIP-SRH

### ISSUE THREAD

**Issue by VKTML** [thkl/homebridge-homematic#120]
Währe es möglich den neuen HMIP Fenstergriffsensor einzufügen?
Ich bin neu hier, und finde den Pfad von channel_config.json auf meinem Raspberry nirgends.
Leider habe ich nirgends eine Anleitung gefunden, und meine Fähigkeiten sind nicht ganz so ausgeprägt.
Würde mich freuen, wenn mir jemand etwas unter die Arme greifen könnte.

**Comment by thkl** [comment]
die Channel Config ist in /usr/local/lib/node_modules/homebridge-homematic/ChannelServices
Sie heisst channel_config.json

So wie es in der Doku ausschaut verhält sich das Ding wie der alte Fenstergriffsensor.
Deswegen mal unterhalb von 

```
{
	   "type": "ROTARY_HANDLE_SENSOR",
	   "service": "HomeMaticHomeKitRotaryHandleService"
	},

```
folgendes einfügen und homebridge neu starten.

```
	{
	   "type": "ROTARY_HANDLE_TRANSCEIVER",
	   "service": "HomeMaticHomeKitRotaryHandleService"
	},
```

Wenn es geht bitte mal Rückinfo.

**Comment by VKTML** [comment]
sorry für die späte Rückmeldung, war im Urlaub.
vielen Dank für die Hilfe, funktioniert nun einwandfrei.
