### ISSUE TITLE
Wrong status of Homematic IP switch with measurement function

### ISSUE THREAD

**Issue by tegti** [thkl/homebridge-homematic#122]
Currently I am using a Homematic IP switch with measurement function with a CCU2. There was no problem to configure it with Homebridge and to see it in the Apple HomeKit app. There is also no problem to turn the switch on or off via HomeKit. But after doing that and reopen the app again, the status is not synchronized. I have launched Homebridge in debug mode and recognized, that Homebridge sends to status 0 (=off) to HomeKit, although the switch is turned on (checked in CCU2 WebUI).

I am using Homebridge version 0.0.76 and CCU2 version 2.27.8.

**Comment by MarkusBe** [comment]
Hi there, I am having the same problem here, any suggestions? The switch is always shown as "on", although it is OFF. 

Thank you for any help...

**Comment by thkl** [comment]
please use only the channel with number 6 (metering channel) for homekit ... the service will automatically query the correct switch channel...
