### ISSUE TITLE
Homebridge wird von Eve nicht gefunden

### ISSUE THREAD

**Issue by sickboy2711** [thkl/homebridge-homematic#123]
Leider findet die Elgato-EVE App die Homenrigde nicht.
Hat jemand evtl. einen Rat?

**Comment by bprskalo** [comment]
wenn Dir geholfen werden soll, brauchen wir einiges mehr an Information., so wie zum Beispiel allfällige Fehlermeldungen , config,json usw ..

**Comment by sickboy2711** [comment]
habe es irgendwie hinbekommen mit einer anderen config. 
Aber Homebrigde wurde direkt in Homekit intigriert ohne Umweg über Eve
