### ISSUE TITLE
Combine channels to custom services

### ISSUE THREAD

**Issue by RealDeemer** [thkl/homebridge-homematic#125]
I am using a HM-LC-Sw4-PCB to toggle my garage door. A key press either closes or opens the garage door. The garage door itself knows 4 states, in where it cycles: (1) Motor Upwards -> (2) Stop -> (3) Motor Downwards -> (4) Stop -> (1) ...

I that channel is exposed to homebridge-homematic as a switch, it is displayed as light bulb. 

I am using HM-Sec-SC to detect if the garage door is closed. This is exposed to homebridge-homematic as blind service, at least it displays when the door is opened.

I now want to combine these two channels into a single HomeKit device. I am thinking a scenario where a press to the icon in HomeKit would trigger the motor across the states and the icon displays if the door is opened or closed. I was wondering if "Custom Service Class" would be an approach to get this solved. If not, is there any other way to get these combined?

**Comment by dkrizic** [comment]
I solved the program using two devices:

* A port on HM-LC-Sw4-DR (I had one left, because I use the other 3 for my irrigation)
* HM-Sec-TiS This device is a contact that can be made to look like a garage door

Not perfect, but ok for me. I agree that it would be much nicer if it would be the original HomeKit GarageDoor switch.

**Comment by RealDeemer** [comment]
Somyou have two devices formjust a door, right? It seemst that your config is similar to mine, where I have a switch that triggers the mechanism, and a sensor that indicates if the door is opened. 

And yes, having the ability to combine the channels from the devices in a single device, the device could be remapped to a Homekit Door.

**Comment by mach1009** [comment]
I have now implemented my garage door and wrote a HowTo:
[Homebridge-http-garagedoor](https://github.com/mach1009/homebridge-http-garagedoor/wiki/How-to-setup-a-garage-door-opener-in-Homekit-with-Homematic-CCU2-or-RaspberryMatic)
