### ISSUE TITLE
All Homekit CCU devices show "no response" when Issues with some Homematic devices?

### ISSUE THREAD

**Issue by timokli** [thkl/homebridge-homematic#126]
I frequently loose *all* Homematic devices after some days with a new setup of homebridge with homebridge-homematic plugin as single plugin running. The only way to get it working again is to completly reconfigure Homebridge from scratch with a new username (MAC-Address).

When I use other plugins with homebridge, its working without this problem, so this should not be a problem with homebridge itself. When I add homebridge-homematic, the "no response" error comes up after a few days.

The same problem is mentioned here: https://github.com/nfarina/homebridge/issues/1390

Any hint how to get the reason for this? Maybe its only one device which causes the hole homematic plugin to stop work?

**Comment by timokli** [comment]
In addition: could this "sanitization" be a possible solution?
https://github.com/nfarina/homebridge/issues/1367#issuecomment-315382467

**Comment by NebzHB** [comment]
he's already doing something like that :
https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeKitGenericService.js#L132

**Comment by timokli** [comment]
Ok, so the reason for our problem should be find anywhere else in the plugin... :)

**Comment by NebzHB** [comment]
Or maybe the min max ... he doesn't test that

Envoyé de mon iPhone

**Comment by timokli** [comment]
Yesterday I had the problem again after adding some new devices to the "Homekit-Gewerk" and restarting Homebridge.

Is ther any maximum limit how many devices can user with homebridge-homeatic before this bug happens?

any other news to this problem? is anybody working on it?

**Comment by nicoh88** [comment]
Same here, second time - 7 days everything was okay, since yesterday all homebridge-devices have had "no response" error - only the original philips hue bridge is working. :-(

![bildschirmfoto 2017-08-11 um 13 09 05](https://user-images.githubusercontent.com/264264/29210908-4fc8060c-7e96-11e7-885e-6aae76f0ac71.png)

The "no response" problem is defintly a homematic plugin problem. I've been using it for 20 days -
 before that, about 6 months, i had no problems.

I have only three devices in the "Homekit-Gewerk".
- _HmIP-SMI_
- _HMIP-SWDO_
- _HM-LC-Sw1-Pl-CT-R1_

Cheers Nico

**Comment by nicoh88** [comment]
**A few questions about the cause of the "no response" problem:**
1. Which plugins are configured in your config.json (`npm -g list | grep -i homebridge`)?
2. Do you have an original [Philips Hue Bridge](https://www.howtogeek.com/wp-content/uploads/2015/10/ximg_561e966beee38.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.O2B_X_9wwF.png) on HomeKit in use?
3. Do you have an [HA-Bridge](https://github.com/bwssytems/ha-bridge) in use?
4. Do you have a [Devolo HomeControl](http://www.devolo.de/home-control/)?
5. Do you have an AppleTV or iPad as a HomeKit Home Hub in use? If so, which device and which iOS version?
6. What HomeMatic device types do you have in the HomeKit group?

**My answer:** 
1. homebridge-cmdswitch2, homebridge-devolo, homebridge-fritz, homebridge-harmonyhub, homebridge-homematic, homebridge-neato, homebridge-netatmo, homebridge-samsungtv-control, homebridge-sonos, homebridge-sonybraviatv, homebridge-vorwerk
2. Yes, v2.
3. [Yes, for my logitech harmony hub](https://www.loggn.de/logitech-harmony-companion-haussteuerungstasten-fremd-belegen-ha-bridge/).
4. Yes.
5. Yes. 
5.1. Home Hub: iPad mini 3 with iOS 10.3.3.
5.2. Client Devices: iPhone 7 with iOS 11b5 and iPad Air 2 with iOS 11b5.
6. one HmIP-SMI, one HMIP-SWDO, one HM-LC-Sw1-Pl-CT-R1

**Comment by nicoh88** [comment]
Problem was solved by @pdlove - [here](https://github.com/nfarina/homebridge/issues/1418#issuecomment-322669553).

**Update homebridge**
`npm -g update homebridge`
