### ISSUE TITLE
Update des Status in der Home.app geht nicht mehr, auch notifications klappen nicht mehr. 

### ISSUE THREAD

**Issue by udochrist** [thkl/homebridge-homematic#127]
Ich betreibe HomeKit-homematic schon seit einiger Zeit. Bisher Problemlos. 
Die versionen sind die jeweils aktuellen, das ganze läuft im docker von marcoraddatz. 
Wenn ich in der Home.app beispielsweise ein Licht einschalte geht das Licht an und der Status des Buttons ändert sich. Schalte ich das Licht am Taster an passiert in der app gar nichts. Analog bei den türkontakten. Wenn ich das docker Image starte, dann wird der aktuelle Status der Kontakte korrekt übernommen in die Home app. Öffnet oder schließt man danach eine Türe/Fenster gibt's kein Update in der app und auch keine notification. In der ccu und anderen homematic Apps passt alles, da die Status zum Start auch stimmen und früher alles funktioniert hat schließe ich konfig-probleme aus. 

Gefühlt würde ich sagen passiert das seit dem letzten Update der ccu Firmware 2.27.8. 

Falls jemand Ideen hat / logfiles braucht, dann gerne.

**Comment by thkl** [comment]
Klingt so als ob keine Events von der CCU beim homematic Plugin ankommen.
Bitte mal prüfen ob das homematic plugin auf port 9090 (wired 9091 ; ip 9092) von der CCU erreichbar ist. Ggf im Debug Modus (homebridge -D) schauen, ob irgendwelche diesbezüglichen Fehler auftauchen ...

**Comment by udochrist** [comment]
Bei mir ist weder auf der CCU, noch auf dem Rechner der die Homebridge ausführt irgendwas unter TCP Port 909[012] erreichbar. ich erhalte da grundsätzlich "connection refused".

Nach langem Kampf mit Docker und Logfiles kann ich den Fehler jetzt verstehen:

die Maschine auf der der docker container für homematic läuft hat mehrere Netzwerk ips. das xmlrpc Modul schnappt sich anscheinend das erste gefundene interface und versucht den listener zu starten.
Das IF das er bei mir geschnappt hat war natürlich das falsche (aktuell nicht gesteckt und daher eine auto-ip Adresse). Bevor ich den ganzen Krempel hier wieder umkonfiguriere: besteht die change in der config die "local-ip" so wie den "local-port" anzugeben und xmlrpc dazuzubringen sich daran zu halten?

**Comment by thkl** [comment]
Aktualisiere mal das File HomeMaticRPC.js auf die aktuelle GitHub Version hier ... 
Und dann versuche mal in der config die Keys : local_ip und local_port

**Comment by udochrist** [comment]
ja. das ists....
issue kann damit geschlossen werden!
Danke für den schnellen fix!
