### ISSUE TITLE
Schalter nicht als Licht sondern als Schalter in HomeKit darstelllen

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#128]
Hallo
Beschäftige mich erst seit kurzem mit Homematic/Homebridge ...
Wie kann ich jetzt richtig einige Lampen als Schalter darstellen (Nicht alle Schalter HM-LC..... sind Lichtschalter) ... was wäre der richtige weg in der aktuellen Version 0.0.76 ?
danke !
lg

**Comment by dkrizic** [comment]
Dann wäre es cool, Schalter auch als Sprinkler abzubilden

**Comment by roe1974** [comment]
Ahhh. herausgefunden.....
Unter "Outlet" den entsprechenden Schalter + Kanal definiert...schon ist es eine Steckdose (dh. Lüfter, Steckdose oder Licht ) ;)
