### ISSUE TITLE
Support of the HM-Sen-Wa-Od filling level sensor

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#129]
Is there a way to show the filling level by the HM-Sen-Wa-Od sensor in HomeKit ?

**Comment by iuliusmaximilian** [comment]
Anyone out there?

**Comment by thkl** [comment]
sorry, as i know,  there is currently no homekit device available to map that HM device. May be with ios 11 ....

**Comment by iuliusmaximilian** [comment]
Wäre es nicht möglich es auf "Battery Level" percentage o.ä. zu mappen ?
