### ISSUE TITLE
Es werden nicht alle HM Geräte angezeigt

### ISSUE THREAD

**Issue by dr-apple** [thkl/homebridge-homematic#13]
Ich habe beim ersten einrichten der HB alle HM Geräte in der HB gesehen, aber nach kurzer Zeit verschwanden ca 60% alle HM Geräte ??? Warum...

Egal was ich mache Sie kommen nicht wieder, aber Sie werden erfasst, das sieht man im LOh der HB.

Die HB habe ich noch mal neu aufgesetzt und jetzt habe ich von anfang an nur 40% mein HM Geräte....

Hat einer eine Idee woran das liegen könnte ?

Hat einer eine Liste mit allen Sprachbefehlen für die HB ? Ich habe noch nicht rausgefunden, wie ich den Status abfragen kann, ob ein Fenster offen ist usw....

**Comment by thkl** [comment]
Kann es sein, das mehr als 100 Geräte übermittelt werden sollen ? Hinter einer Homekit Bridge sind max. 100 Geräte zulässig.

**Comment by hammond23** [comment]
Gibt es eine Möglichkeit, über die Grenze von 100 Geräten zu gehen? Wenn ich mein Audio-Equipment steuern will (es gibt dafür keine plugins), dann ist die Grenze schnell überschritten.

**Comment by JensBonse** [comment]
Einfach mehrere Bridges verwenden.
100 ist das HomeKit Limit. Da kann die HomeBridge nichts dran ändern.

**Comment by hammond23** [comment]
Sorry, ich habe gerade mal 4 Tage mit der HomeBridge gearbeitet. Wie mehrere Bridges verwenden?
Ich habe das Ganze auf dem Pi2 laufen.

**Comment by hammond23** [comment]
Also mehrere Pi's verwenden? Keine andere Möglichkeit?

**Comment by JensBonse** [comment]
Korrekt. Mehrere Pi's verwenden.
Wie gesagt, ist keine Limitation der HomeBridge selber, sondern HomeKit von Apple setzt das Limit.

**Comment by thkl** [comment]
Jap so ist es. 
Oder via lxc mehrere virtuelle Maschinen auf einem Pi laufen lassen.  Die Bridge kann immer nur in einer Instanz laufen.

**Comment by leonsio** [comment]
und wie soll das einen weiter bringen? oder meinst du man würde dann durch Filter die Abgrenzung vornehmen?

**Comment by thkl** [comment]
Oder durch zwei Gewerke
