### ISSUE TITLE
Virtuelle Taster der CCU2 verwenden

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#130]
Hallo
Gibt es eine Möglichkeit einen virtuellen Taster der CCU2 so einzubinden, um ihn als Schalter zu verwenden (soll in einem programm abgefragt werden).
Hintergrund: scharf/unscharf schalten der Alarmanlage mittels iPhone
Weiters würde ich gerne eine eingebundene Variable nur Anzeigen in Homekit (wird Standardmässig als Schalter eingebunden, mit dem ich den Wert der Variable ändern kann)

Ich hoffe auf Tips
DANKE, lg Richard

**Comment by mach1009** [comment]
Hi,
am besten lässt sich eine Systemvariable dafür verwenden. Die lässt sich direkt in der App schalten und due siehst den Status.  Die Änderung kann in Programmen ausgewertet werden.

**Comment by roe1974** [comment]
Hi, danke, werde ich so machen. Mit einer Variable die ich als Schalter verwende und einem Programm dass den Schalter gleich wieder ausschaltet bei einer Bedingung. Damit habe ich quasi "einen taster"
Gibt es jetzt noch die Möglichkeit so eine Variable "nur" anzeigen zu lassen in Homekit ?

lg Richard

**Comment by JensBonse** [comment]
Kannst auch direkt ein Programm als HomeKit Device registrieren. Ein Programm wird als An-Aus Schalter dargestellt und wird auch sofort wieder auf Aus gesetzt.

**Comment by roe1974** [comment]
OK, probiere ich ;-)
DANKE !
Jetzt wäre noch toll, wenn man die Variable (scharf/unscharf) nur Anzeigen lassen könnte (also ohne Schalterfunktion) ;-)
lg Richard

**Comment by Vaitage** [comment]
Hi, wie ist es möglich Programme direkt von Homematic ins HomeKit einzufügen? bei mir kommt der Fehler, wenn ich "Virtuelle Schalter" nutzen will, das ich eine Steuerzentrale einrichten soll.

bitte um Hilfe

**Comment by thkl** [comment]
https://github.com/thkl/homebridge-homematic#programs

**Comment by Vaitage** [comment]
Das bringt mir nix.
Selbst wenn ich die variablen in die config Eintrage startet er mir die Homebridge nicht mehr, da kommt im SSH eine rote Fehlermeldung, die ist aber zu schnell weg als das ich diese lesen kann.

Deswegen wäre es mal schön zu wissen wie roe das realisiert hat.
