### ISSUE TITLE
HM-SEC-SIR-WM zeigt in Home falschen zustand bzw. ändert ihn bei "aktualisierung"

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#132]
Ich setzte per CCU Programm die Sirene auf "abwesend" (entspricht: Alle Sensoren scharf) ..... nach einiger Zeit setzt Home am iPhone (bei aktualisierung )den Status auf "nacht" (entspricht: Aussensensoren scharf) ... obwohl der Status auf der CCU noch immer "Alle Sensoren scharf" ist .....
Es gab (in Foren nachlesbar) am Anfang dieses Produktes ein Problem mit diesen zwei Zuständen (waren in der WebUi der CCU vertauscht)......wurde aber durch Update in der CCU behoben.
Wurde hier im Code dieser "Fehler" korrigiert und wird deshalb bei Aktualisierung in der Home App der Status falsch angezeigt ?

Wenn ich die beiden Werte in der CCU setzte, wird es in Home im ersten Moment richtig angezeigt. Bei schliessen der Home App und neu aufrufen, werden diese beiden Zustände vertauscht ?!?

PS: Bin jetzt kein programmierer, der code sieht aber so aus als würden diese beiden Zustände vertauscht werden...Ich setzte in der CCU richtig...im ersten moment wird richtig angezeigt...beim aktualisieren in Home entspricht der Wert aber einen anderen Zustand...den er dann auch anzeigt 
PSS: Bei jem Home öffnen und aktualisieren kommt von der Sirene "Die Alarmsieren wurde aktiviert"

lg Richard

**Comment by thkl** [comment]
Momentan ist das Mapping der Zustände wie folgt : 

CCU   -- Homekit
0 = DISARMED  --> Characteristic.SecuritySystemCurrentState.STAY_ARM = 0;
2 = ALLSENS_ARMED -- Characteristic.SecuritySystemCurrentState.AWAY_ARM = 1;
1 = EXTSENS_ARMED -- Characteristic.SecuritySystemCurrentState.NIGHT_ARM = 2;
3 = ALARM_BLOCKED -- Characteristic.SecuritySystemCurrentState.DISARMED = 3;


Soll das geändert werden ? Wenn ja was wäre denn besser ?

**Comment by roe1974** [comment]
warum wird 1 mit 2 und 2 mit 1 vertauscht 
das ist aus meiner sicht nicht richtig
das war ein bug in der sirene ... der behoben wurde
richtig ist 1-1 2-2
lg

**Comment by thkl** [comment]
Naja externe Sensoren heisst ja Außenhaut .. und die wäre ja Nachtalarm also intern scharf.
Die Zustandsdaten habe ich aus der aktuellen Doku ...http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/hm_devices_Endkunden.pdf Seite 271

**Comment by roe1974** [comment]
wie gesagt ... wird bei aktivieren kurz richtig angezeigt 
dann springt er auf den jeweils anderen zustand in der anzeige um....

**Comment by roe1974** [comment]
ich ändere die zustände mit einem schalter der die entsprende kanäle (1-3) triggert
kanal 4 sind ja die geschalteten zustände 
lg

**Comment by thkl** [comment]
Ich habe das Ding hier nur auf dem Schreibtisch an einem Testsystem und ändere das über das WebGUI der CCU:

"Alarm Aus" Knopf CCU ergibt "Zuhause" in Homekit
"Alle Sensorenscharf(extern scharf)" Knopf CCU ergibt "Abwesend" in HomeKit
"Außensensoren scharf (intern scharf)" Knopf der CCU wird zu "Nacht" in HomeKit


Auslösung eines der 3 Alarme über das WebGUI bringt Homekit in den Zustand -"Ausgelöst"

Für mich sieht das ok aus ??

**Comment by roe1974** [comment]
und wenn du den zustand in der home app änderst ....
auf nacht und abwesend ... stimmt es dann auch ?

**Comment by thkl** [comment]
Zuhause wird zu Alarm aus
Abwensen zu extern scharf
Nacht zu intern scharf
Aus zu Alarm blockiert

🤔

**Comment by roe1974** [comment]
mom checke noch mal ....und melde mich
danke vorerst

**Comment by roe1974** [comment]
also ich kann sie in der home app schalten ...
wenn du aber aus dem screen wo du den zustand ändern kannst dann wieder rausgehst
zum icon ... ändert er kurz darauf den zustand jeweils zum anderen ... (anwesend/nacht)

der teil vom code kommt mir komisch vor

(value==1){currentState.setValue(Characteristic.SecuritySystemCurrentState.DISARMED,null);}
			        if (value==1){currentState.setValue(Characteristic.SecuritySystemCurrentState.NIGHT_ARM,null);}
			        if (value==2){currentState.setValue(Characteristic.SecuritySystemCurrentState.AWAY_ARM,null);}
			        if (value==0){currentState.setValue(Characteristic.SecuritySystemCurrentState.STAY_ARM,null);}
		       });

wieso kommt zweimal „1“ bei der abfrage ?

lg richard

**Comment by roe1974** [comment]
PS: Spende ist raus ;-)

**Comment by thkl** [comment]
Vielen Dank 😊

**Comment by roe1974** [comment]
konntest du dir den code ansehen (post davor) ... sieht irgendiw seltsam aus .. oder ?

**Comment by thkl** [comment]
Ja.  Aber das ist nur der Code der ausgeführt wird wenn nach dem setzen des Status dieser wieder abgefragt wird.  

Ich weiß jetzt auch nicht warum :)
Ich muss mal probieren was passiert wenn ich das ändere.

**Comment by roe1974** [comment]
OK...musste ja gestern persist+accessories löschen und alles neu anlegen (wegen iOS 11)
Habe danach den code geändert (wie ich es schon unter iOS 10 hatte)
Habe jetzt wieder den original code von Dir....und jetzt geht es ....
komisch ;-) ... vielleicht lag es daran, dass ich ursprünglich alle vier kanäle im "homekit gewerk" hatte und nicht nur den 4ten kanal (so wie jetzt) ;-)
DANKE jedenfalls für Deine Bemühungen !!!!
lg Richard

**Comment by roe1974** [comment]
Kommando zurück..... im ersten Step sieht es gut aus.....
nur mach die Home App zu ... warte kurz ... und öffne sie wieder.. plötzlich ändert sich der Zustand von ursprünglich abwesend auf nacht (oder umgekehrt) ... hmmmmmmm

**Comment by thkl** [comment]
Na ich Probier das nachher mal aus

**Comment by roe1974** [comment]
Aja...wenn Du dir das ansiehst...kannst du gleich den Batterie Status mit reinpacken ;-)
DANKE :-)
lg Richard

**Comment by roe1974** [comment]
Hi @thkl ..... konntest Du schon testen ;-)
lg Richard

**Comment by thkl** [comment]
Nope bin gestern nicht dazu gekommen. Hab nur gesehen das das HomeKit Gerät einen Batterie Datenpunkte hat.  Also das kann ich erweitern.

**Comment by roe1974** [comment]
Ok...kein stress... wichtiger wäre mir den "fehler" zu analysieren....
Hoffe er tritt bei Dir auch auf ;-)
lg Richard

**Comment by thkl** [comment]
OK ich hab es glaube ich ... HomeKit sendet einen SecuritySystemCurrentState Set Event wenn die App aufgerufen wird. Den habe ich bisher nirgendwo implementiert, denn es macht auch keinen Sinn den CurrentState setzen zu wollen. Denn normal wird der TargetState gesetzt .. das löst einen Call zur CCU aus und das Gerät bekommt den neuen Zustand. Eine Zustandsänderung löst dann eine Änderung im SecuritySystemCurrentState aus ... also quasi die Bestätigung.

Ich hab da File HomeMaticHomeKitSecuritySystem.js hier schon mal geändert rein gestellt.
Du kannst das mal zum Test tauschen .. es sollte auf dem Pi unter /usr/local/lib/node_modules/homebridge-homematic/ChannelService (wenn mit npm install -g installiert wurde)  liegen.
Da ist auch schon der Batterie Indikator mit drin.


Zur Bonus Frage: local_ip bringt von der Performance nichts. Aber es gibt auf PI's mit 2 aktiven Netzwerkinterfaces (zb YAHM Installationen) gelegentlich das Problem das die automatische Erkennung der eigenen IP Adresse, genau die falsche ermittelt und als Empfänger der Events zur CCU sendet. Das kann man damit umgehen.

**Comment by roe1974** [comment]
super ! werde testen und berichten :)

**Comment by thkl** [comment]
BTW: im nächsten Update (muss allerdings auch was an einem core file gemacht werden -  deswegen als npm ) gibt es dann auch Support für den Sabo (Sirene / Magnetkontakte / IRDs)  .. 

Leider zeigt die HomeApp das nur in den Details an und erzeugt keine Notification (was ich ja persönlich schwach finde - denn wenn jemand meine Sirene abreisst würde ich das schon gern wissen wollen)

**Comment by roe1974** [comment]
ja schade :( ... mit iOS 12 dann *lol*

**Comment by roe1974** [comment]
Status: Betterie geht
Der Fehler ist immer noch da zwischen "abwesend" und "Nacht" :-(

**Comment by thkl** [comment]
Aber das „Aktivieren“ beim neu öffnen der HomeApp sollte weg sein. 

Und jetzt die Zustände Nacht und Abwesend tauschen ???

**Comment by roe1974** [comment]
naja...ich setzte den status zB auf "Nacht" -> CCU (intern scharf)
schliesse die App
Starte sie neu ... dann kommt "aktivieren" und er ändert auf "abwesend" -> CCU bleibt (intern)
.... aber dann ist ruhe
JEIN .... weil beim wechseln solange die App offen ist stimmen die Stati
erst wenn du die App schliesst und wieder öffnest wird einmalig vertauscht ?!?!?!? hmmmmmmmm

**Comment by thkl** [comment]
Hmm das ist mir gestern nicht aufgefallen. Aber ich schau mir das noch mal an.

**Comment by roe1974** [comment]
Verwende deinen Code schon länger "verändert"
so funktioniert es perfekt .... aber hier ist Nacht/abwesend konsequent vertauscht.
Habe es nicht geschafft das umzudrehen

'use strict';

var HomeKitGenericService = require('./HomeKitGenericService.js').HomeKitGenericService;
var util = require("util");


function HomeMaticHomeKitSecuritySystem(log,platform, id ,name, type ,adress,special, cfg, Service, Characteristic) {
    HomeMaticHomeKitSecuritySystem.super_.apply(this, arguments);
}

util.inherits(HomeMaticHomeKitSecuritySystem, HomeKitGenericService);

HomeMaticHomeKitSecuritySystem.prototype.propagateServices = function(homebridge, Service, Characteristic) {
    
  // Register new Characteristic or Services here
  
}



HomeMaticHomeKitSecuritySystem.prototype.createDeviceService = function(Service, Characteristic) {

	var that = this;
    // Fill Servicelogic here
    var secsys = new Service["SecuritySystem"](this.name);
    this.services.push(secsys);
    this.internalsirupdate = false
    
    // Characteristic.SecuritySystemCurrentState and Characteristic.SecuritySystemTargetState 
    
    var currentState = secsys.getCharacteristic(Characteristic.SecuritySystemCurrentState)

	.on('set', function(value,callback) {
		// nothing to do
	   if (callback) {callback();}
	}.bind(this))

    .on('get', function(callback) {
      that.query("4:ARMSTATE",function(value){
		  var hkValue = 0
		  // have to set target state also
		  that.internalsirupdate = true;
		  var ts = that.currentStateCharacteristic["TARGET"];
		  
		  switch (value) {
			
			case 0: 
				currentState.setValue(0,null);
				ts.updateValue(0,null);
				hkValue = 0
				break;
			case 1:
				currentState.setValue(1,null);
				ts.updateValue(1,null);
				hkValue = 1
				break;
			case 2:
				currentState.setValue(2,null);
				ts.updateValue(2,null);
				hkValue = 2
				break;
			case 3:
				currentState.setValue(3,null);
				ts.updateValue(3,null);
				hkValue = 3
				break;
			}
		  
		  that.internalsirupdate = false;
		  if (callback) {
			  callback(null,hkValue);
		  }
      });
    }.bind(this));

	that.currentStateCharacteristic["4:ARMSTATE"] = currentState;
    
	var ts = secsys.getCharacteristic(Characteristic.SecuritySystemTargetState)

	.on('get',function(callback){
	   if (callback) {callback();}
	}.bind(this))

    .on('set', function(value,callback) {
       if (that.internalsirupdate==false) {
	       
       var hmvalue = -1;
       if (value==3) {hmvalue = 3;}
       if (value==2) {hmvalue = 2;}
       if (value==1) {hmvalue = 1;}
       if (value==0) {hmvalue = 0;}
    
       if (hmvalue != -1) {
	       that.log.info("Set %s",hmvalue)
	       that.command("set","4:ARMSTATE" , hmvalue,function() {
		       that.remoteGetValue("4:ARMSTATE",function(value) {
			        if (value==3){currentState.setValue(Characteristic.SecuritySystemCurrentState.DISARMED,null);}
			        if (value==2){currentState.setValue(Characteristic.SecuritySystemCurrentState.NIGHT_ARM,null);}
			        if (value==1){currentState.setValue(Characteristic.SecuritySystemCurrentState.AWAY_ARM,null);}
			        if (value==0){currentState.setValue(Characteristic.SecuritySystemCurrentState.STAY_ARM,null);}
		       });
	       });
       }
       }
       
       if (callback) callback();
    }.bind(this));

	this.currentStateCharacteristic["TARGET"] = ts;


	this.remoteGetValue("4:ARMSTATE");

	this.addValueMapping("4:ARMSTATE",0,0);
    this.addValueMapping("4:ARMSTATE",1,1);
    this.addValueMapping("4:ARMSTATE",2,2);
    this.addValueMapping("4:ARMSTATE",3,3);
	
	this.addLowBatCharacteristic(secsys,Characteristic);

	this.deviceAdress = this.adress.slice(0, this.adress.indexOf(":"));
}

HomeMaticHomeKitSecuritySystem.prototype.endWorking=function()  {
   this.remoteGetValue("4:ARMSTATE");
}


HomeMaticHomeKitSecuritySystem.prototype.datapointEvent= function(dp,newValue) {
	if ((dp=='1:STATE') || (dp=='2:STATE') || (dp=='3:STATE')) {
	   if (newValue==true) {
		   var cs = this.currentStateCharacteristic["4:ARMSTATE"];
		   this.log.info("set alarm %s",cs);
		   cs.setValue(4, null);
	   } 
	}
	
	if (dp=="4:ARMSTATE") {
		this.log.debug("Send Armstate %s",newValue)
		var ts = this.currentStateCharacteristic["TARGET"];
		var cs = this.currentStateCharacteristic["4:ARMSTATE"];
		this.internalsirupdate = true;

		switch (newValue) {
			
			case 0: 
				cs.updateValue(0,null);
				ts.updateValue(0,null);
				break;
			case 1:
				cs.updateValue(1,null);
				ts.updateValue(1,null);
				break;
			case 2:
				cs.updateValue(2,null);
				ts.updateValue(2,null);
				break;
			case 3:
				cs.updateValue(3,null);
				ts.updateValue(3,null);
				break;
			
			
		}
		this.internalsirupdate = false
	}
	
 }

module.exports = HomeMaticHomeKitSecuritySystem;

**Comment by roe1974** [comment]
btw: nutze node 8.4.0 .... kann ich auf 8.5.0/8.6.0 gehen... ?
lg

**Comment by thkl** [comment]
ok, ich hab alles weggeworfen und noch mal neu gemacht. Das File mal tauschen dann sollte es gehen.

**Comment by roe1974** [comment]
homebridge startet nicht mehr.

/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSecuritySystem.js:123
   var this = that;
       ^^^^

SyntaxError: Unexpected token this
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at HomeMaticChannelLoader.loadClass (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:83:13)

**Comment by thkl** [comment]
Dreh das mal um in var that=this ....

**Comment by roe1974** [comment]
das kömmt öfter vor ..... überall ändern ?

**Comment by thkl** [comment]
Nein nur in Zeile 123 ist der Fehler

**Comment by roe1974** [comment]
OK .. es startet...
jetzt ist das permanente "aktivieren" problem da....
Bei jedem App schliessen (abschiessen) und neu starten kommt eine push nachricht (jeweils der andere Wert) und es bleibt ständig ... "aktivieren" :-(

**Comment by roe1974** [comment]
PS: Meine Code Önderung von oben funktioniert perfekt...nur gehört abwesend/nacht vertauscht ... irgendwie ;-)

**Comment by thkl** [comment]
Die pushnachricht kommt ja. Aber spätestens nach einmal zustandswechsel sollte „aktivieren“ weg sein

**Comment by roe1974** [comment]
ne :-( 
jedesmal app abschiessen und neue starten kommt eine push nachricht ... und "aktivieren"....
... habe jetzt meinen code (also deinen bissi verändert) wieder rein ... da funktioniert es absolut sauber....
Eine push bei veränderung ... dann ist ruhe
schönheitsfehler: nacht = extern und abwesend = intern (home/CCU)

**Comment by thkl** [comment]
ich hab noch mal was geändert. Ich bekomme von HomeKit jedesmal wenn die App aktiviert wird eine Anfrage nach Current und Target State. Die muss ich beantworten. Daraufhin kommt der Push. Auch wenn sich der Rückgabewert nicht verändert hat.

Ich hab jetzt noch mal was eingebaut, das ein Event aus der CCU keine Änderung an Homekit sendet wenn der Zustand der gleiche ist wie der zuletzt zu HK gesendete.

**Comment by roe1974** [comment]
werde testen ...
bei meiner änderungen kommen aber keine push nachrichten beim schließen / öffnen von Home

**Comment by roe1974** [comment]
Leider immer noch nicht :-(
Wenn Du einen Zustand einstellst (abwesen oder nacht)....und du die Home App danach öfter abschiesst und wieder öffnest kommt jedesmal eine push Nachricht (obwohl der Zustand gleich geblieben ist) und beim zweiten mal zeigt er kurz den falschen Zustand...dann konstant den richtigen....
btw: aus und zuhause funktioniert ohne probleme...
Ich will dich aber nicht überstrpazieren... mein geänderter code funktioniert perfekt (bis auf den Schönheitsfehler in der CCU - Zustände vertauscht) .. aber das lass ich halt so ;-)
Aber...könntest Du dir das mit den Jalousien ansehen (#151) ... das stört mich mehr ;-)
lg RIchard

**Comment by thkl** [comment]
Das hier sollte aber jetzt durch sein oder ?

**Comment by roe1974** [comment]
yes
