### ISSUE TITLE
Integration in ioBroker

### ISSUE THREAD

**Issue by thoduh** [thkl/homebridge-homematic#133]
Hallo,
erstmal vielen Dank für dieses Tool !
Benutze es schon seit Ewigkeiten und bin aus sehr zufrieden damit.
Aber:
Ließe sich das ganze nicht in ioBroker integrieren?
Ich bin auf yahka.0 umgestiegen weil es mit ioBroker läuft, allerdings läuft es extrem schlecht im vergleich zu deinem Tool.
Wäre wirklich eine Super Sache, denn dein Tool ist um WELTEN besser und einfacher zu konfigurieren.
-> Noch dazu ist dein Support super!
Ich selber kenne mich damit zu wenig aus, kann deshalb auch nicht abschätzen ob es überhaupt möglich wäre...

**Comment by thkl** [comment]
ioBroker hat meines Wissens eine eigene HomeKit Integration

**Comment by Apollon77** [comment]
Naja, eine die alles manuell konfigurieren muss ... Dein Projekt hat ein Super Mapping geschaffen und die Frage wäre ob man das nich verheiraten könnte (Dein Mapping als "Library" in ioBroker nutzen sodass biele HM-Komponenten automatisch konfiguriert werden könnten oder so) :-)
