### ISSUE TITLE
BidCos-RF doesn’t get filtered out

### ISSUE THREAD

**Issue by dehsgr** [thkl/homebridge-homematic#134]
Hi!

At Neighbours Home appear around 50 HM-RCV-BidCos-RF devices. They don‘t disappear regardles of filtering it in Config, as you described. How do I geht the Filter working? CuX-Devices were filtered correctly.

Thank you,

dehsgr

**Comment by thkl** [comment]
You should add all devices , you want to use with homekit to a dedicated subsection (eg. HomeKit) and then put the name of that subsection in your config file as described here : https://github.com/thkl/homebridge-homematic#configuration

**Comment by dehsgr** [comment]
Yes, of Course. I've already done this. The same way I did at my Installation. This didn't prevent devices appearing in HomeKit. :-(

**Comment by dehsgr** [comment]
Ok. I triple-checked config again and found a typing error. Issue is solved.

Thank you!
