### ISSUE TITLE
HM-Sec-SCo Türkontakt aktualisiert nicht mehr

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#135]
Nach Update der Homebridge auf 0.4.27 aktualisiert der Türkontakt HM-Sec-SCo nicht mehr.
Der Status wird nach jedem Neustart richtig angezeigt. Dann nicht mehr.
Hat wer eine Idee ?

lg Richard

**Comment by roe1974** [comment]
zurück zu homebridge 0.4.22.....alles geht wieder

lg richard

**Comment by candlestorm** [comment]
wie kann man denn das Downgrade durchführen?
ich habe derzeit exakt dasselbe Problem.

**Comment by roe1974** [comment]
sudo npm install -g homebridge@0.4.22

lg Richard

**Comment by candlestorm** [comment]
danke...läuft nun auch wieder  :-)

**Comment by roe1974** [comment]
läuft nur bedingt bei mir....... :(
nach neustart der homebridge werden die status änderungen der kontakte "life" in Home angezeigt.....nach einer gewissen Zeit nur wenn ich Home am Iphone neu starte .... bei dir auch so ?
lg Richard

**Comment by candlestorm** [comment]
Bei mir läuft es seit stunden fehlerfrei.
Sonst plane per cron alle paar Stunden einen Neustart...würdest du im laufenden Betrieb nicht merken

**Comment by roe1974** [comment]
ok :-)

**Comment by roe1974** [comment]
wenn du die home app öffnest......und im hitergrund offen lässt (also nicht "abschiesst") ... zeigt er immer noch live die änderungen der kontakte nach zB 30min?
