### ISSUE TITLE
Push Mitteilungen

### ISSUE THREAD

**Issue by Tobi563** [thkl/homebridge-homematic#136]
Gibt es eine Möglichkeit über Homekit oder auch andere Programme, Push-Mitteilungen zu bekommen wenn die Temperatur unter oder über einem bestimmten Punkt liegt?

**Comment by thkl** [comment]
Nein, soweit ich weiss geht das nicht.

**Comment by Omega236** [comment]
Hallo,
du kannst ein CuxD Alarm Gerät erstellen, dieses über ein Programm auf auslösen oder nicht stellen und dieses Gerät in die Homebridge-Gruppe aufnehmen.

Es gibt auch Fertige CuxD Geräte die sich um so sachen wie Temperatur-Schwellen kümmern, aber ob genau das geht weiß ich nicht, einfach probieren bzw doku von CuxD lesen.
