### ISSUE TITLE
Status von Geräten invertieren

### ISSUE THREAD

**Issue by timokli** [thkl/homebridge-homematic#138]
Ich würde gerne in der Home-App den Status zweier Rolladenaktoren HM-LC-Bl1PBU-FM invertiert/verdreht zum echten Homematic Zustand anzeigen lassen. Also in HM ist Status "geschlossen" in der Home App soll "offen" angezeigt werden. Hintergrund: Die über diese Aktoren angesteuerten Markisen zeigen eingefahren "geöffnet" an, was natürlich verwirrend ist, wenn auch im Sinne des Aktors durchaus korrekt.

Ist es möglich eine Option einzuführen in der ich die Aktoren channels hinterlegen kann welche dann von homebridge-homematic schlicht invertiert werden?

**Comment by thkl** [comment]
Hmm das würde schon gehen, aber es wäre ein erheblicher Umbau

**Comment by mach1009** [comment]
Hast du einfach mal überlegt die Drähte für auf und ab am Aktor zu tauschen?

**Comment by thkl** [comment]
Nein ich behandle derzeit alle Kanaltypen gleich. Ich müsste eine Logic einbauen das für ein Gerät (oder mehrere) umzustellen.
