### ISSUE TITLE
No service for HM-TC-IT-WM-W-EU:SWITCH_TRANSMIT

### ISSUE THREAD

**Issue by Sonsi79** [thkl/homebridge-homematic#139]
Hi.
Ich habe das Wandthermostat "HM-TC-IT-WM-W-EU".
Im Terminal sehe ich beim Starten der Homebridge die folgende Meldung:

"[HomeMatic CCU2] There is no service for HM-TC-IT-WM-W-EU:SWITCH_TRANSMIT"

Wird das Thermostat von Homebridge-Homematic nicht unterstützt?

**Comment by thkl** [comment]
Wirf mal den Channel 7 des Geräte aus dem Homekit Gewerk und nimm stattdessen Channel 1 (WEATHER_TRANSMIT) ... Channel 7 liefert nur die Info ob die ggf angelerten Magnetkontakte offene Fenster dedektieren
