### ISSUE TITLE
Homegear Support

### ISSUE THREAD

**Issue by Marioheld** [thkl/homebridge-homematic#14]
Das homebridge-homematic Plugin aktzeptiert kein Homgear als CCU ersatz, da das Plugin RegaHSS Aufrufe verwendet, welche von Homegear nicht aktzeptiert werden. Würden diese durch RPC Aufrufe ersetzt werden wäre es so möglich Homematic Geräte ganz ohne CCU über den HM-CFG-USB mit Homegear fernzusteuern. 

Weiterführender Forum Eintrag: https://forum.homegear.eu/viewtopic.php?t=417

**Comment by thkl** [comment]
Ja, aber für einige Funktionen ist Rega notwendig.  zb. für Variablen , Programme oder auch Virtuelle Gruppen von Aktoren(zB Heizungsgruppen)

**Comment by Marioheld** [comment]
Homegear bietet hier leicht andere Ansätze wodurch bei Homegear kein Rega notwendig ist (Beispiel: [Variabeln](https://forum.homegear.eu/viewtopic.php?t=245), [Programme](https://www.homegear.eu/index.php/Homegear_Reference#Homegear_Scripts), [Virtuelle Geräte](https://forum.homegear.eu/viewtopic.php?t=21)). Natürlich ist es ein mehraufwand diese speziellen unterschiede, zwischen Homegear und CCU, zu programmieren, dennoch wäre es eine tolle Erweiterung für dieses Plugin.

**Comment by thkl** [comment]
Ja, in Ermangelung von Hardware und Testmöglichkeiten würde ich das von meiner Seite aus nicht einbauen. Kann aber gern jemand machen ....
