### ISSUE TITLE
ios11 keine Geräte mehr verfügbar

### ISSUE THREAD

**Issue by Fritzo81** [thkl/homebridge-homematic#143]
Nach dem Update auf ios11 sind keine Geräte mehr verfügbar bzw. es wird die hombridge nicht mehr gefunden.

**Comment by dkrizic** [comment]
Dann schau mal direkt bei Homebridge vorbei, scheint ein allgemeines Problem zu sein.

**Comment by thkl** [comment]
Also zumindest mit dem IOS11 GM Build funktioniert noch alles problemlos hier ...

**Comment by dkrizic** [comment]
Die GM ist mit der finalen Version identisch. Ich hatte kein Update nach der GM.

**Comment by Samfox2** [comment]
Ich hatte vorher keine GM installiert, hab also auf das finale iOS11 geupdated. Ebenfalls keine Probleme:
iPhone 6s / iPad Pro 12 / ATV 4 alle auf iOS11

**Comment by Sonsi79** [comment]
Ich denke das wird das gleiche Problem sein wie bei meiner Meldung. 
iOS 11, Homematic 2.29.22 führt bei mir auch zu einem Timeout wodurch die Homebridge-Homematic die Homebridge lahmlegt.
Thomas (thkl) hatte mir gestern Abend einen Weg aufgezeigt zumindst die Homebridge wieder zum laufen zu bekommen indem der Timeaut von 120 auf 360 hochgesetzt wird, jedoch sind die Homematic Geräte weiterhin nicht aktualisierbar :-(

Siehe meine Meldungen unter #137

**Comment by Fritzo81** [comment]
Bei mir hat das geholfen:

Delete homebridge from home app
Kill homebridge
Remove cachedaccessories
Change Mac address of homebridge with new one
Remove temp folder
Start homebridge
Read homebridge to home app on iOS 11

Seit dem läuft alles wieder normal
