### ISSUE TITLE
Feature request: Sprinkler und Faucet support

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#144]
Seit iOS gibt es eine neue Schalterart Sprinkler. Ich lade gerade mal Xcode 9 beta runter, da scheint der Simulator für HomeKit mittlerweile direkt enthalten zu sein und wollte mal schauen, ob es einfach "nur" eine andere Art von Schaltern ist. 

Wenn ja, dann könnte man sie als "sprinklers : [ "bla", "bla" ]" konfigurieren.

**Comment by thkl** [comment]
Ähm nein ? 
<img width="256" alt="bildschirmfoto 2017-09-20 um 09 55 48" src="https://user-images.githubusercontent.com/884355/30632936-1b38c5d4-9dea-11e7-8113-917768d2a1e9.png">

**Comment by thkl** [comment]
Doch doch .. er ist aus dem XCode 9 Additional Tools Paket und Version 3.0 .. der aus XCode 8 ist Version 2.0 und schaut bissel anders aus....

**Comment by dkrizic** [comment]
Also, in den "Xcode 9 Additional Tools" befindet sich ein HomeKit Accessory Simulator in der Version 3.0 (123.1) und der kennt weder Sprinkler noch Faucet, das meinte ich, dass sie den Simulator noch nicht auf den neusten Stand gebracht haben. Auch in der Dokumentation finde ich die Konstanten für die Accessories und Services nicht und auch in den Characteristics habe ich nichts diesbezüglich gefunden.

**Comment by thkl** [comment]
Ja ja .. nur wo hast Du die Info her, das es die beiden Services geben soll ?

**Comment by dkrizic** [comment]
Von der WWDC, siehe

https://devstreaming-cdn.apple.com/videos/wwdc/2017/705d3czqkho1a6u/705/705_whats_new_in_homekit.pdf

![screen shot 2017-09-20 at 10 36 00](https://user-images.githubusercontent.com/1181349/30634498-9570d030-9def-11e7-867e-0bda99d1af89.png)

**Comment by thkl** [comment]
Aha .. na dann warten wir mal ab bis die Doku mehr sagt. Aber auf HM Seite kann man da ja nur einen Schaltaktor mit Magnetventil entsprechend abbilden ... das wird wieder ein wildes config.json gebastel ..

**Comment by dkrizic** [comment]
Aktuell sind es ganz normale Switches, die bei mir den Sprinkler steuern:

![img_3719](https://user-images.githubusercontent.com/1181349/30634901-f1ae43ea-9df0-11e7-98c4-e9bb418318ac.jpg)
![img_3753](https://user-images.githubusercontent.com/1181349/30634902-f1cf489c-9df0-11e7-92ab-18badfda2d9e.JPG)
![img_9410](https://user-images.githubusercontent.com/1181349/30634950-1d378094-9df1-11e7-8bcc-08fb281bdcfa.PNG)

Mich interessiert primär, ob ein Sprinkler ein ganz normaler Switch (mit einem anderen Icon ist), oder ob da etwas mehr Logik drin ist (z.B. immer nur einer, Zeit, die er anbleibt)... Daher bin ich so neugierig.

**Comment by thkl** [comment]
Na es bleibt Spannend ....

**Comment by dkrizic** [comment]
Die aktuelle Version von iOS 11.2 kennt jetzt Sprinkler und Faucet. Ich habe das mal bei https://github.com/KhaosT/HAP-NodeJS/issues/504 eingetütet, aber die UUIDs sind noch unbekannt, da es keinen neuen HomeKit Simulator gibt.
