### ISSUE TITLE
Seit heute alle Geräte nur noch auf "Aktualisieren......"

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#145]
Seit heute in der Früh stehen alle Geräte der Homebridge in der Home App nur mehr auf "Aktualisieren" .....
Es kommen keine aktuellen Stati und es kommt nach sehr langer Zeit "Keine Antwort".
In der Console (.err und .log) sieht alles normal aus. ... Liegt das an Apple ????

lg Richard

PS: Auch die "original Homekit" Geräte (EVE etc...) kommen nicht mit Status !??!?!?!...oder nur seeeeehr langsam

Und wie ist eiegntlich die Kommunikation..... CCU2 <-> raspberry <-> ATV <-> iPhone ????

**Comment by thkl** [comment]
Note: Aktuell habe ich das auch .. wenn man das Gerät aber in der HomeApp auf macht (Force Touch) wird es richtig aktualisiert und ab dann werden die richtigen Werte angezeigt.  (bzw natürlich auch wenn ein Event der CCU einen neuen Wert schickt. Bis dahin stehen die Geräte auf Update bzw No Response ...
