### ISSUE TITLE
Bewegungsmelder Gerät nicht ereichbar

### ISSUE THREAD

**Issue by XerXes777** [thkl/homebridge-homematic#146]
Der Kanel für die Helligkeit bei den Bewegunsmelder HM-Sec-MDIR-2 wird nicht erkannt.
Neuste nodejy version node-v8.5.0
Neuste homebridge version  homebridge@0.4.28
Neuste homebridge-homematic version NPM 0.0.80
Frische neue Installation.

Und spammt den syslog voll:

Sep 23 19:06:03 ole homebridge[1173]: [2017-9-23 19:06:03] [eva] Brightness 4.86
Sep 23 19:06:05 ole homebridge[1173]: [2017-9-23 19:06:05] [eva] Brightness 5.82
Sep 23 19:06:05 ole homebridge[1173]: [2017-9-23 19:06:05] [eva] Brightness 5.82
Sep 23 19:06:07 ole homebridge[1173]: [2017-9-23 19:06:07] [eva] Brightness 4.86
Sep 23 19:06:07 ole homebridge[1173]: [2017-9-23 19:06:07] [eva] Brightness 4.86
Sep 23 19:06:07 ole homebridge[1173]: [2017-9-23 19:06:07] [eva] Brightness 5.82
Sep 23 19:06:07 ole homebridge[1173]: [2017-9-23 19:06:07] [eva] Brightness 5.82
Sep 23 19:06:08 ole homebridge[1173]: [2017-9-23 19:06:08] [eva] Brightness 5.82
Sep 23 19:06:08 ole homebridge[1173]: [2017-9-23 19:06:08] [eva] Brightness 5.82
Sep 23 19:06:09 ole homebridge[1173]: [2017-9-23 19:06:09] [eva] Brightness 4.86
Sep 23 19:06:09 ole homebridge[1173]: [2017-9-23 19:06:09] [eva] Brightness 4.86
Sep 23 19:06:09 ole homebridge[1173]: [2017-9-23 19:06:09] [eva] Brightness 5.82
Sep 23 19:06:09 ole homebridge[1173]: [2017-9-23 19:06:09] [eva] Brightness 5.82
Sep 23 19:06:15 ole homebridge[1173]: [2017-9-23 19:06:15] [eva] Brightness 4.86
Sep 23 19:06:15 ole homebridge[1173]: [2017-9-23 19:06:15] [eva] Brightness 4.86
Sep 23 19:06:16 ole homebridge[1173]: [2017-9-23 19:06:16] [eva] Brightness 4.86
Sep 23 19:06:16 ole homebridge[1173]: [2017-9-23 19:06:16] [eva] Brightness 4.86
Sep 23 19:06:16 ole homebridge[1173]: [2017-9-23 19:06:16] [eva] Brightness 5.82
Sep 23 19:06:16 ole homebridge[1173]: [2017-9-23 19:06:16] [eva] Brightness 5.82
Sep 23 19:06:16 ole homebridge[1173]: [2017-9-23 19:06:16] [eva] Brightness 4.86
Sep 23 19:06:16 ole homebridge[1173]: [2017-9-23 19:06:16] [eva] Brightness 4.86
Sep 23 19:06:16 ole homebridge[1173]: [2017-9-23 19:06:16] [eva] Brightness 4.86
Sep 23 19:06:16 ole homebridge[1173]: [2017-9-23 19:06:16] [eva] Brightness 4.86
Sep 23 19:06:17 ole homebridge[1173]: [2017-9-23 19:06:17] [eva] Brightness 4.86
Sep 23 19:06:17 ole homebridge[1173]: [2017-9-23 19:06:17] [eva] Brightness 4.86
Sep 23 19:06:17 ole homebridge[1173]: [2017-9-23 19:06:17] [eva] Brightness 5.82
Sep 23 19:06:17 ole homebridge[1173]: [2017-9-23 19:06:17] [eva] Brightness 5.82
Sep 23 19:06:17 ole homebridge[1173]: [2017-9-23 19:06:17] [eva] Brightness 5.82
Sep 23 19:06:17 ole homebridge[1173]: [2017-9-23 19:06:17] [eva] Brightness 5.82
Sep 23 19:06:17 ole homebridge[1173]: [2017-9-23 19:06:17] [eva] Brightness 5.82
Sep 23 19:06:17 ole homebridge[1173]: [2017-9-23 19:06:17] [eva] Brightness 5.82
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 5.82
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 5.82
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 5.82
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 5.82
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 4.86
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 4.86
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 5.82
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 5.82
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 4.86
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 4.86
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 5.82
Sep 23 19:06:18 ole homebridge[1173]: [2017-9-23 19:06:18] [eva] Brightness 5.82
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 4.86
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 4.86
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 5.82
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 5.82
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 4.86
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 4.86
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 5.82
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 5.82
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 4.86
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 4.86
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 5.82
Sep 23 19:06:19 ole homebridge[1173]: [2017-9-23 19:06:19] [eva] Brightness 5.82
Sep 23 19:06:20 ole homebridge[1173]: [2017-9-23 19:06:20] [eva] Brightness 4.86
Sep 23 19:06:20 ole homebridge[1173]: [2017-9-23 19:06:20] [eva] Brightness 4.86
Sep 23 19:06:55 ole homebridge[1173]: [2017-9-23 19:06:55] [eva] Brightness 4.86

**Comment by thkl** [comment]
ist in 0.0.81 gefixt

**Comment by bprskalo** [comment]
da läuft mit der 81 was nicht so wie es sollte ..

[9/24/2017, 2:39:07 PM] ====================
[9/24/2017, 2:39:07 PM] ERROR LOADING PLUGIN homebridge-homematic:
[9/24/2017, 2:39:07 PM] /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:447
};
 ^
SyntaxError: Unexpected token ;
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:5:29)
    at Module._compile (module.js:556:32)
[9/24/2017, 2:39:07 PM] ====================
[9/24/2017, 2:39:07 PM] No plugins found. See the README for information on installing plugins.
[9/24/2017, 2:39:07 PM] Loaded config.json with 0 accessories and 1 platforms.
[9/24/2017, 2:39:07 PM] ---
[9/24/2017, 2:39:07 PM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'HomeMatic' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by XerXes777** [comment]
ja kann ich bestätigen.
wollte die version auch gerade testen und konnte sie gar nicht starten.

**Comment by thkl** [comment]
🙀 https://github.com/thkl/homebridge-homematic/commit/dee543ff5724c48ae42bae89ebe494f594129bf2

**Comment by XerXes777** [comment]
okay läuft
danke
