### ISSUE TITLE
Neues Gerät taucht nicht in Home.app oder eve auf

### ISSUE THREAD

**Issue by udochrist** [thkl/homebridge-homematic#147]
Ich habe zwei weitere Lichtschalter angeschlossen und in der ccu konfiguriert. Soweit sogut.
Beide Schalter sind ebenfalls in der Sektion für die Homebridge drin und werden beim Neustart der Bridge auch mit gelistet. Die Schalter werden aber nicht in der Home app oder in eve hinzugefügt.
Alle Versionen sind aktuell. Ios11, 0.80 homematic Plugin und neueste ccu fw.

**Comment by thkl** [comment]
Nabend, 
ich habe das eben mal mit einer Sirene probiert weil ich die für ein anderes Thema hier am Wickel habe.
Löschen der Sirene aus der CCU und Neustart homebride -> Gerät verschwindet aus der Home App
Anlernen der Sirene; Einfügen in Homekit Gewerk; Neustart Bridge -> Gerät erscheint automatisch wieder in der Home App....

Schwer nachzuvollziehen, da ja bei Dir das Gerät augenscheinlich auch mit im Log als erkannt angezeigt wird. (es steht aber dann sowas hier im Log für das Gerät ?

`
[9/24/2017, 9:10:53 PM] [HomeMatic CCU] Load BuildIn Service Class HomeMaticHomeKitSecuritySystem

[9/24/2017, 9:10:53 PM] [HomeMatic CCU] service for HM-Sec-Sir-WM:ARMING is HomeMaticHomeKitSecuritySystem
`

Also das die richtige Serviceclass gefunden wird ?

**Comment by udochrist** [comment]
Hallo, Viel dank fürs testen. der Issue kann weg.
Das Problem hat sich in der Zwischenzeit erledigt. Die Geräte sind jetzt aufgetaucht. eventuell hing die Verzögerung mit dem umstellen auf ios11 auf einer handvoll apple-geräte und apple tv zusammen.
