### ISSUE TITLE
Alarmsirene aktualisierung Homebridge 0.4.28 (HomeMaticHomeKitSecuritySystem.js)

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#148]
Hallo
Kann sein, dass durch die neue Homebridge Version die Alarmsirene nicht mehr richtig aktualisiert wird ?
Nach jedem Start der Home App stimmt der Status der Sirene. Sonst wird er nicht aktualisiert.
Ist das auch ein "true/false" "0/1" Problem der neuen Homebridge Version ?

lg Richard
PS: Wo ist Deine "Wunschliste" ... würde Dir gerne etwas zukommen lassen für den Support hier ;-)

**Comment by thkl** [comment]
geht es um HM-Sec-Sir-WM ? 
Bei mir funktioniert die ... Zumal diese ja nicht ja nein kennt sondern div. Arming Zustände.
Auch wird eine Auslösung in der Home App richtig erkannt und dargestellt.

**Comment by roe1974** [comment]
homebridge neu gestartet ... jetzt geht es ... komisch
aber die schaltzustände ccu2/homekit stimmen nicht überein ... habe ich schon mal gepostet ( #132)
konntest du dir schon ansehen ?
lg richard 
PS: wunschliste ?

**Comment by thkl** [comment]
Ich habe das mit den Zuständen mal in #132 beschrieben. Wunschliste gibt es aktuell nicht (die HM Produkte sind ja jetzt nicht gerade was für den Spendenbutten hier) .. letzterer ist allerdings auf der Hauptseite hier vorhanden
