### ISSUE TITLE
Raspberry Pi A -- >BidCos Service unter Windows über "alten" runden LAN Adapter

### ISSUE THREAD

**Issue by thezepter** [thkl/homebridge-homematic#15]
Hallo,

danke erstmal für die tolle Arbeit !
Ich betreibe das Plugin auf meinem Pi A und habe einen laufenden BidCos Service auf einem Windows Server und einen alten HomeMatic LAN Adapter (der runde). In Zukunft baue ich mir eine CCU auf Pi B Basis, aber bis dahin würde ich gerne meinen BidCos Service über Windows einbinden. Ist das mit dem Plugin überhaupt möglich ?
Bekomme keine Devices integriert.

So schauts aus.

![hb](https://cloud.githubusercontent.com/assets/2700279/13315679/8535029c-dbac-11e5-988a-2de4aeb25290.PNG)
 
Danke schonmal !

**Comment by thkl** [comment]
Nabend, 

nein, so geht das nicht. Das Initiale Auslesen der Geräte passiert über die Rega Schnittstelle.
Die Zustandsabfrage und Änderung läuft dann über die RPC Schnittstelle.
Deine obige Config schaut nicht so aus, als ob  Rega vorhanden ist.

Man könnte das ganze so anpassen,das die Geräte über den BidCos RPC Dienst gelesen werden, aber dann kommen, soweit ich weiss keine Gerätenamen sondern nur Adressen zurück.

**Comment by thezepter** [comment]
Ah ok, gut zu wissen. Dann warte ich einfach noch ne Woche bis mein RaspiMatic fertig ist.

**Comment by bprskalo** [comment]
Hallo in die Runde

auch von meiner Seite ein grosses Lob und ein Dankeschön für die Arbeit !!


Frage : Ich möchte einen ROTARY_HANDLE_SENSOR via hombridge anzeigen . Von Haus aus geht das ja als Kontakt und wenn man im config,json den Sensor als "door" einträgt .. erscheint es als Türe (was von den Statusmeldungen her ja logischer wäre (geöffnet und so.. ) 

sind das die beiden einzigen Möglichkeiten ?

Danke schonmal im voraus !

**Comment by thkl** [comment]
Ja, da es meines Wissens keinen direkten Fensterkontakt in HomeKit gibt.

**Comment by bprskalo** [comment]
Danke für die Antwort, was ja noch nicht ist , kann noch werden :-) ..

und wie ist es mit dem VALVE_STATE ?

**Comment by thkl** [comment]
Hi,

das ist genau das gleiche.  
Das Thermostat Control in HomeKit kennt Soll, Ist Temperatur und einen Modus (Heizen/Kühlen etc)

**Comment by bprskalo** [comment]
Danke :-), ja das mit dem heizen und kühlen ist auch so ein Thema , da HM ja auch noch andere Modus kennt .. eine weitere Baustelle, fragt sich ob HM je mal sich lizenzieren lässt um das ganze dann direkt anzubieten als Elgato .. 


DANKE nochmals für die Antworten !

**Comment by thkl** [comment]
Die offizielle Implementation des HomeKit Protokolls in die CCU sollte für HM kein großes Thema sein. Das es geht sieht man ja hier.  Im Gegenteil könnten sie den gleichen Bold Move wie Philips machen und eine neue CCU verkaufen.

**Comment by bprskalo** [comment]
das stimmt und das mit der neuen CCU .. wäre mir ehrlich gesagt egal .. im sinne von Out of the Box, auch wenn ich das alles hier sehr spannend finde und auch einiges lernen durfte :-) .. ich habe mal gelesen, dass Apple horrende Lizenzgebühren verlangt wobei sich EQ3 das bestimmt leisten könnte und zudem einen riesigen Markt abgreifen könnte :-)
