### ISSUE TITLE
Homematic IP Gerät an Homematic CCU

### ISSUE THREAD

**Issue by sohnkarlsruhe** [thkl/homebridge-homematic#150]
Habe ein Homematic IP Türsensor an meine CCU angelernt, alles Prima. Funktioniert auch und ändert seinen Status. Aber in der HomeAPP und Homebridge sehe ich keine Zustandsänderung. Wenn die Tür beim starten von Homebridge offen ist, bleibt sie offen, zu bleibt zu.

**Comment by DeLocke** [comment]
some problem with "HMIP-SWDO"

**Comment by DeLocke** [comment]
"enable_hmip":"true"
 muss in die config.json

**Comment by sohnkarlsruhe** [comment]
Danke
