### ISSUE TITLE
CUXD FS20 Jalousieaktor einbinden

### ISSUE THREAD

**Issue by Rilly1601** [thkl/homebridge-homematic#155]
Hallo, gibt es eine Möglichkeit das der per CUXD eingebundene Jalousieaktor nicht als Lampe, sondern als Rolladen angezeigt wird? Falls ja gibt es hierfür eine Anleitung, die ich irgendwo nachlesen kann?

Danke und viele Grüße
Rilly

**Comment by thkl** [comment]
Als was für ein Gerät kommt der denn in der CCU an ? Klingt nach einem Dimmer ...

**Comment by Rilly1601** [comment]
Nein, eigentlich ist er in der CCU meiner Meinung nach korrekt als Funk-Rollladenaktor 1-fach für Markenschalter, Unterputz eingebunden.  (Typbezeichnung HM-LC-Bl1PBU-FM)

**Comment by thkl** [comment]
Wenn es als BLIND als Kanaltype nach HomeKit kommt dann wird daraus ein WindowCovering Device. Sollte es als zb. Dimmer in der CCU versorgt sein, dann ist es eine Lampe in HomeKit.

**Comment by Rilly1601** [comment]
Ah super, vielen Dank, ich hab grad im CUxD nach einem Kanaltyp BLIND gesucht, aber nichts gefunden. Wie stelle ich das denn ein?

**Comment by thkl** [comment]
Das geht glaube ich nicht. Schau Dir mal das Log an wenn homebridge startet.
Dann sollte sowas hier auftauchen : 

[10/4/2017, 9:34:33 PM] [HomeMatic CCU] Load BuildIn Service Class HomeMaticHomeKitBlindService
[10/4/2017, 9:34:33 PM] [HomeMatic CCU] service for BLIND:BLIND is HomeMaticHomeKitBlindService
