### ISSUE TITLE
HM-PBI-4-FM Taster reagiert nicht

### ISSUE THREAD

**Issue by FA-Tech** [thkl/homebridge-homematic#156]
Hallo zusammen,
ich habe gerade eben die ersten zwei Kanäle des 4er Tasters HM-PBI-4-FM eingefügt.
HomKit erkennnt diese und ich kann sie auch konfigurieren... aber passieren tut beim betätigen des Tasters nichts :( 

Hoffe jemand kann mir weiter helfen 
Danke schon mal im voraus!

**Comment by Traxios** [comment]
Gibt es hier noch Erkenntnisse? Ich habe die gleiche Erfahrung gemacht. Da das Modul eines der wenigen Module ist, mit dem man Unterputz bestehende Taster weiterverwenden kann, wäre es toll, wenn die Homebridge HomeKit Integration funktioniert.

Vielen Dank für weitere Unterstützung. :-)
