### ISSUE TITLE
Wechsel iOS Gerät ... irgendwas zu beachten ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#157]
Da ich bei Apple keine Infos finde, stelle ich die Frage hier rein...
Bei mir steht ein iPhone Wechsel an...muss ich bei Homekit/Homebridge irgend etwas beachten ?
Oder einfach backup -> backup zurückspielen -> altes Gerät läschen ... und alles passt wieder ??

DANKE für eure Infos
lg Richard

**Comment by Vaitage** [comment]
Hallo,

Ich habe das auch schon gemacht, Backup reicht aus. 
Falls das nicht ausreicht einfach die homebridge löschen und neu eingeben.

Nochwas: ich könnt deine Hilfe wegen den Virtuellen Tasten brauchen. Können wir uns auf ein anderen weg evtl mal unterhalten?

**Comment by roe1974** [comment]
danke
ja klar...
kontaktdaten per mail austauschen: roe@live.at
lg richard
