### ISSUE TITLE
Homematic Push's kommen nicht immer an

### ISSUE THREAD

**Issue by DeLocke** [thkl/homebridge-homematic#158]
Ich hab das Problem das sporadisch einer meiner HmIP-RF zwar seinen Status auf der CCU2 aktualisiert, aber dieses Event nicht gepusht wird via HomeKit aufs Handy.

Hat da jemand eine Idee dazu?

Kann ich irgendwo ein Debug anschalten um denn zu sehen das homebridge diese Information über das Plugin erhalten hat?

**Comment by JensBonse** [comment]
Aktualisiert sich der Status denn in der Home APP?
