### ISSUE TITLE
Keine HomeMatic Geräte gefunden ?!?

### ISSUE THREAD

**Issue by kohlsalem** [thkl/homebridge-homematic#16]
Hallo, 

ich habe eine HM CCU2 mit ein paar Geräten erfolgreich am Laufen, und eine Homebridge mit milights, weiner wemo und netatmo gekoppelt. Funktioniert soweit alles. 

Ausser halt die HM :-)

```
[HomeMatic CCU] Initializing HomeMatic platform...
[HomeMatic CCU] Homematic Plugin Version 0.0.25
[HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[HomeMatic CCU] init RPC
[HomeMatic CCU] Local IP: 192.168.178.95
[HomeMatic CCU] XML-RPC server for interface BidCos-RF.is listening on port 9090
[HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[HomeMatic CCU] CCU RPC Init Call on port 2001 for interface BidCos-RF.
[HomeMatic CCU] Fetching Homematic devices...
```
Und dann wird nix gefunden?!?

Die Config ist:
```
    "platforms": [
        {
            "platform": "HomeMatic",
            "name": "HomeMatic CCU",
            "ccu_ip": "192.168.178.98",
            "filter_device":[],
            "filter_channel":[ ],
            "outlets":[ ],
            "doors":[],
            "programs":[],
            "subsection":""
        },
```
Hab ich was generelles übersehen?

Gruß
Michael

**Comment by kohlsalem** [comment]
Nachdem ich http://homematic-forum.de/forum/viewtopic.php?t=27465 nochmal nachgelesen hab, kam ich auf die Idee die "subsection" rauszunehmen. Das hat's gelöst.

Ist in der Instalationsbeschreibung nicht sehr eindeutig beschrieben.

**Comment by thkl** [comment]
Ok, das stimmt. Ist nicht ganz eindeutig. Ich ändere das mal noch.
Danke für den Hinweis.
