### ISSUE TITLE
 HM-Sec-RHS (Fenster-Drehgriffkontakt).....

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#160]
Zeigt der Fenster-Drehgriffkontakt HM-Sec-RHS in Homekit genauso nur offen/geschlossen ... oder sieht man auch "gekippt" ?

lg Richard

**Comment by dkrizic** [comment]
Gekippt wird auch als offen gezeigt. Ich glaube HomeKit kennt gekippt nicht.

**Comment by dkrizic** [comment]
Ich sehe gerade, dass Fenster in HomeKit 0 bis 100% offen sein können. Evtl. macht es Sinn ein gekipptes Fenster mit 50% anzugeben. Ich der Home app wird dann "50% Open" statt "Open" angezeigt. Wäre vielleicht eine Idee.

**Comment by thkl** [comment]
kann man machen ... macht das Sinn ? Für mich ist gekippt generell offen. Ich mein das sieht doch die Heizungssteuerung in der CCU auch so ?

**Comment by dkrizic** [comment]
Ich finde es macht Sinn, weil es ist schon ein Unterschied ob gekippt oder offen.

**Comment by thkl** [comment]
ist das noch relevant ?

**Comment by dkrizic** [comment]
Fände ich cool
