### ISSUE TITLE
Variablenzustand wird falsch angezeigt

### ISSUE THREAD

**Issue by Sillium** [thkl/homebridge-homematic#163]
Ich habe zwei "Logikwert"-Variablen über das "variables" in der config.json eingebunden. Sie werden in HomeKit als Switches angezeigt. Jedoch wird eine der beiden immer als off (false) angezeigt, auch wenn sich ihr Status auf der Homematic CCU2 ändert. Die andere Variable ändert zwar ihren Status, zeigt aber immer das Gegenteil an. Müssen sie evtl. bestimmte Wertebezeichnungen für "wahr" und "falsch" haben, damit es funktioniert? Bei der ersten Variable ist es "wahr = an" und "falsch = aus". Bei der zweiten "wahr = ist wahr" und "falsch = ist falsch".

**Comment by thkl** [comment]
Variablen werden nicht automatisch aktualisiert wenn sie sich in der CCU ändern.
Die CCU sendet keine Events in so einem Fall ... Und ich werte nur den value Status aus. Das heisst, wenn die Varnames vertauscht sind , ist es auch in Home vertauscht ...

Für den Aktualisierung der Variablen kann man sich eines Tricks bedienen.
Man nehme einen Virtuellen Taster der CCU und lasse den auf die Änderung einer (oder aller) der gewünschten Variablen per CCU Programm einen kurzen Tastendruck ausführen. In der config.json muss dieser Kanal als Parameter "variable_update_trigger_channel" eingetragen werden.
Damit löst die CCU auf diesem Kanal einen Event aus wenn sich eine Variable ändert .. und Homebridge reagiert auf diesen Event

**Comment by Sillium** [comment]
Alles klar, vielen Dank. Werde ich bei Gelegenheit so einrichten.
