### ISSUE TITLE
CUxD Motion Sensor (Type (40)) aktualisiert nicht...

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#164]
Ich habe einen virtuellen Motion Sensor eingebunden (Type 40 in CUxD) damit ich den Sensor meines Türspions in Homekit bekomme.
Es wird alles richtig dargestellt, nur wird der Status in Home nur aktualisiert wenn ich den Raum wechsel oder Home schliesse / neu starte.....
Liegt das am channel Service oder muss ich noch was einstellen ?

lg Richard

PS: Und bekomme ich den Helligkeitssensor irgenwie in Home weg, der ja falsche werte anzeigt da der Motionsensor über HTTP getriggert wird ? (eigenes channel service?)

**Comment by roe1974** [comment]
@thkl ... ist wie #101 .....
habe ich eine chance ? ;-) ;-)

lg Richard

**Comment by thkl** [comment]
Da das CuxD Interface nicht unterstützt wird, muss ich die Werte via Rega abfragen. Das heisst ich bekomme keine Events von der CCU wenn sich der Status ändert. Die Rega Abfrage passiert nur, wenn HomeKit nach dem Status fragt, und das macht es nur wenn man die Seite mit dem Gerät refresht.

**Comment by roe1974** [comment]
alles klar :-)
