### ISSUE TITLE
KeyMatic: Tür öffnen

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#167]
Hi,

wenn ich das richtig verstehe, kann man die KeyMatic zwar auf und zuschliessen, nicht aber öffnen, was ja eine ganz nette Funktion ist. Ich habe ein Programm geschrieben "OpenKeyMatic" und eine boolsche Variable "KeyMaticMaster".

Die Variable habe ich als

`            "variables" : [
                "KeyMaticMaster"
            ],
`

und das Programm als

`            "programs":[
                "OpenKeyMaticDoor"
            ],
`

eingebunden. "KeyMaticMaster" dient als Schutz, damit ich es nicht ausversehen auslöse und wird von einem Programm nach 30s auf false gesetzt, funktioniert. Ich will nun, dass "OpenKeyMaticDoor" nur dann ausgeführt wird, wenn "KeyMaticMater==true":

Aber sobald ich "OpenKeyMaticDoor" auslöse, wird die Tür *immer* geöffnet. Hat jemand eine Idee?

<img width="696" alt="screen shot 2017-10-26 at 20 16 07" src="https://user-images.githubusercontent.com/1181349/32069834-a29038c0-ba8a-11e7-8048-7a0cc4247d58.png">

**Comment by thkl** [comment]
Programme werden mit obj.ProgramExecute() ausgeführt. Dabei sind dem RegaHSS die Conditions Wurst. Gleiches sollte passieren wenn Du das Programm über das WebUI manuell startest.

**Comment by dkrizic** [comment]
Ok, hast Du eine Idee, wie ich das realisieren kann?

**Comment by thkl** [comment]
Kannst Du das Programm über einen Virtuellen Taster auslösen lassen ? Virtual Keys sollten doch gehen oder ?

**Comment by dkrizic** [comment]
Ich sehe gerade, dass Virtual Keys als "Programmable Switches" abgebildet sind, d.h. ich müsste in der Home-App festlegen, was dann passiert. Habe ich was falsch verstanden?

**Comment by thkl** [comment]
Naja du triggerst das Programm (inkl. der Sicherung über die Variable) von einem virtuellen Key aus.
Der Key kommt als Programmable Switch in Home an. Den kannst Du entweder manuell auslösen in dem Du den Switch betätigst, oder über eine Szene in Home von Siri auslösen lassen.

**Comment by dkrizic** [comment]
Verstehe ich nicht, der Programmable Key macht ja nichts, ich kann ihm nur Ding innerhalb von Home zuweisen.

**Comment by thkl** [comment]
Ach stimmt der geht ja nur andersrum ... hmm ok streich die Idee ....

**Comment by dkrizic** [comment]
Funktioniert Programm1 -> Programm2 und in Programm2 wird die Variable ausgewertet?

**Comment by thkl** [comment]
2. Variable durch HomeKit von false auf true und die als Auslöser des Programmes ?

**Comment by dkrizic** [comment]
Ok, so klappt es, aber jetzt kommt das Problem, dass die Variablen sich nicht aktualisieren. Aber in einem anderen Issue hast Du ja beschrieben, wie das geht.

**Comment by dkrizic** [comment]
Eleganteste Lösung bis jetzt:

- Variable 1 "Sperre" als Switch in Home sichtbar
- Programm 1 "Öffnen" als Switch in Home sichtbar
- Programm 1 setzt Variable "Action" = true
- Programm 2 reagiert auf "Action" = true und macht die Tür auf, wenn "Sperre" = true...

Funktioniert, einziger Schönheitsfehler ist, dass "Sperre" nicht aktualisiert wird

**Comment by roe1974** [comment]
@dkrizic ..... ich habe mich für Nuki entschlossen (kann ich sehr empfehlen!)
Lässt sicher perfekt in Homekit intergrieren und ist auch über CCU steuerbar (was ich nicht verwende)
lg Richard
