### ISSUE TITLE
json korrekt anpassen...Datei ungültig

### ISSUE THREAD

**Issue by Seehofweg** [thkl/homebridge-homematic#168]
Ich muss von dem Port 9090 weg und egal wie ich den Wert in die json.config eintrage, es kommt immer  "There was a problem reading your config.json file." und Homebridge startet nicht.

Das ist meine aktuelle Fassung:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:25",
        "port": 51826,
        "pin": "210-72-009"
        "local_port": 8080,

},

    "platforms": [
        {
            "platform": "HomeMatic",
            "name": "homematic-ccu2",
            "ccu_ip": "192.168.178.16",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "programs": [],
            "accessories": [],
            "subsection": "Homebridge"
        }
     ]
}

**Comment by dkrizic** [comment]
Nach dem "pin": "210-72-009" fehlt ein Komma. Bitte selbst in jsonlint testen.
