### ISSUE TITLE
ChannelServices/HomeMaticHomeKitVariableService.js

### ISSUE THREAD

**Issue by sweidinger** [thkl/homebridge-homematic#169]
Hallo,
wie schwierig wäre ein Änderung der HomeMaticHomeKitVariableService von einem "Switch" auf einem "MotionSensor"? In meiner HomaticZentrale läuft ein Script, dass mir in Variablen ausgibt, wenn bestimmte Müllarten abgeholt werden. Diese Variablen sollen dann nur im HomeKit angezeigt werden und nicht "Schaltbar" sein. Klasse wäre ein "MotionSensor", bei dem ich die Mitteilung aktivieren könnte. Mir persönlich würde auch eine modifizierte HomeMaticHomeKitVariableService.js reichen. ;-)

**Comment by roe1974** [comment]
Hi

Habe ich mit dem gelöst:

https://www.npmjs.com/package/homebridge-http-motion-sensor

Du musst nur via script einen "curl http://xxx.xxx.xxx.xxx:Port" absetzten und schon gibt der "virtuelle" Motion sensor in HK für 11 sekunden Signel

lg Richard

**Comment by sweidinger** [comment]
Hi, irgendwie stehe ich mit deinem Tipp auf dem Schlauch. Ich lese die Variable via HomeBridge von meiner Homematic Zentrale aus. Wie komme ich den mit dem Plugin "https://www.npmjs.com/package/homebridge-http-motion-sensor" auf meine Homematic Zentrale?

**Comment by dkrizic** [comment]
homebridge-http-motion-sensor stellt einen Bewegungsmelder in HomeKit dar, der durch eine URL getriggert werden kann, der hat also erstmal nichts mit der HomeMatic zu tun. Wenn Du jetzt (z.B. von der CCU) einen HTTP-Zugriff auf die URL machst, löst Du eine "Bewegung" auf dem virtuellen Bewegungssensor aus, der wiederum eine Benachrichtigung zur Folge hat.

Ich nutze das für einen anderen Fall: Ich habe Kameras, die an meiner Synology Surveillance Station angeschlossen sind. Die Kameras sind intelligent und Lösen einen "Motion Alert". Bei einem "Motion Alert" wird die URL des homebridge-http-motion-sensor ausgelöst, HomeKit sieht eine Bewegung und sendet automatisch Banachrichtigung mit Bildern aller Kameras im gleichen Raum auf das Handy (rich notifications).

**Comment by sweidinger** [comment]
Ahhhhh, jetzt wird ein Schuh draus. ;-) Danke. ;-) Werde es gleich mal testen. ;-)

**Comment by roe1974** [comment]
besser hätte ich es nicht erklären können :-)
konkret (bei mir mit CUxD)

Programm mit.
Variable "Eingang" bei aktualisierung auslösen.....
dann Script:
string url= "http://xxx.xxx.xxx.xxx:port";
if ( (dom.GetObject(ID_DATAPOINTS)).Get("CUxD.CUX2801001:1.CMD_EXEC")) { (dom.GetObject(ID_DATAPOINTS)).Get("CUxD.CUX2801001:1.CMD_EXEC").State("extra/curl -s -k "#url);
} else {}

lg

**Comment by roe1974** [comment]
@dkrizic .....
...wie hast du das mit den rich notifications gelöst.... direkt in HK ?

**Comment by dkrizic** [comment]
Das ist ein Automatismus von HomeKit: Wenn Du eine HomeKit-Kamera und einen HomeKit-Bewegungsmelder hast und der BW eine Bewegung feststellt, dann passiert das automatisch!

HomeKit-Kameras kann man z.B. mit homebridge-camera-ffmpeg erzeugen und BM wie oben beschrieben. Ich glaube man braucht aber einen Apple TV 4 (oder iPad) dafür.

**Comment by roe1974** [comment]
ok habe ich alles genau so ... nur mit homebridge-camera-ffmpeg-omx....
wie und wo bekomme ich ein bild ????
muss ich eine automation anlegen ... wenn bewegung dann kamera ???

**Comment by dkrizic** [comment]
Konfiguriere (in der Home-App), dass die Kamera und der BW im selben Raum sind und lös mal eine Bewegung mit "curl http://x.x.x.x:yyyy/" aus, dann müsste die rich notification schon kommen.

**Comment by roe1974** [comment]
sind im gleichen raum ... die einzigen zwei geräte (BW und KAMERA) ... kommt nur normale Push Nachricht

**Comment by dkrizic** [comment]
Hast Du in der Kamera eine stillImageSource eingetragen? Wird die Kamera normal angezeigt, wenn Du sie in Home anschaust?

**Comment by roe1974** [comment]
ja.....
"stillImageSource": "-i http://xxx.xxx.xxx.xxx/snapshot.jpg",
und ja wird normal angezeigt ......
hmmmmmmmm

**Comment by dkrizic** [comment]
Dann schau mal hier: https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/117

Die Ursache ist noch unklar, ich vermute mal, dass die Bilder zu gross sind oder die Kameras zu lange brauchen.

**Comment by roe1974** [comment]
OK..geht aber auch nicht während ich ein "live" bild in Home habe und dann den BW auslöse ...
kommt trotzdem nur eine normale noti
liegt es an:
       "maxWidth": 1280,
        "maxHeight": 720,
??????
Die Kamera liefert nur 640x480 .... ist eine Türspion Kamera ;-)

**Comment by dkrizic** [comment]
Ist mir bis jetzt auch noch nicht klar. Ich werde auch mal mit den Auflösungen experimentieren. Ich habe drei sehr ähnliche 4MP-Kameras. Bei einer geht das mit den Notifications, bei zwei nicht. Aber die genauen Details sind mir auch noch unklar. Falls ich news habe, schreibe es hier rein.

Welche Türspion-Kamera hast Du?

**Comment by sweidinger** [comment]
Hi Leute, nochmal vielen Dank für die sehr schnelle und freundliche Hilfestellung.
Hab jetzt alles integriert und meine LaMetric-Time meldet mir nun auch wenn eine bestimmte Müllabholung ansteht. ;-) Falls jemand dazu Hilfe braucht, kann ich gerne meine Homebridge-IFTTT-LaMetric Skripte zur Verfügung stellen. ;-)

**Comment by roe1974** [comment]
@dkrizic 

Die einzige WLAN Türspion Kamera die ich gefunden habe.

edimax ic-6220dc

http://www.edimax-de.eu/edimax/merchandise/merchandise_detail/data/edimax/de/home_network_cameras_indoor_fixed/ic-6220dc/

bin sehr zufrieden.... das mit "bis zu 55mm Türstärke" stimmt nicht ... sind alle Adapter dabei bis 110mm

lg Richard

**Comment by dkrizic** [comment]
Ich bin zwar ein Freund von cooler Technologie, aber bei mir läuft as so: Ich gehe auf die Seite meines Müllentsorgers (FES in Frankfurt), gebe dort meine Strasse und Hausnummer ein und lade mir einen iCal-Kalender für das gesamte Jahr herunter mit Alerts für 18:00 Uhr am Vortag. "Low-Tech" und funktioniert super.

Die Türspion-Kamera kenne ich, wobei ich keine Türspion habe, sondern ein Glas und tendiere daher eher zu so etas wie einer Circle 2, die mittlerweile offensichtlich aus HomeKit kann.

**Comment by roe1974** [comment]
ja cool ......
btw... suche eine http alarmsirene .... wie der motion sensor..... der über curl http..... auslösbar ist....
kennst Du da etwsa ?
lg

**Comment by sweidinger** [comment]
Nen iCal, Kalender gibts von unserem Müllentsorger leider nicht, wär jetzt nicht das Problem, aber ich wollte die Erinnerung nicht auf dem Handy-Kalender, da ich nicht sicherstellen kann, dass wenn die Erinnerung kommt ich auch tatsächlich zuhause bin, bzw. am Kalender kann ich die Erinnerung auch lessen, und es dann später trotzdem vergessen....

Deswegen eine Zentrale Uhr in der Küche (LaMetric-Time) die mir am Vortag mich drauf hinweist, dass ich den Müll rausstellen muss (Restmüll,Bio,Papier und gelber Sack) Die Meldung kommt dank HomeKit auch nur wenn jemand zuhause ist, und bleibt solange, bis diese (per Taster an der Uhr) quittiert wird. ;-)

**Comment by jannnfe** [comment]
Hallo @dkrizic. Ich will auch so gerne das mit den Bewegungssensoren hinbekommen wie du. Ich habe eine Foscam und eine Wanscam Kamera. Kennst du dich vielleicht aus, wie ich dessen Bewegungsalarm bekomme und wie muss ich genau das Plugin homebridge-http-motion-sensor konfigurieren. Kennst du dich mit Zoneminder aus? Habe beide Kameras damit verbunden und greife mit dem homebridge-camera-ffmpeg plugin darauf zu. In Zoneminder werden auch die Motion getriggert. Konnte nach ein paar Stunden googeln und ausprobieren nichts finden.

**Comment by dkrizic** [comment]
Also, Du legst mit homebridge-http-motion-sensor für jede Kamera einen Eintrag an

```
    "accessories": [
        {
            "accessory": "http-motion-sensor",
            "name": "Diele Bewegungsmelder Vorderhaus",
            "port": 18089,
            "serial" : "E642011E3ECB"
        },
        {
            "accessory": "http-motion-sensor",
            "name": "Garage Bewegungsmelder Stellplatz",
            "port": 18090,
            "serial" : "E642011E3ECF"
        }
    ]
```

d.h. bei einem http://<homebridge-server>:18090/ müsste der Bewegungsmelder reagieren. Bei mir sind die Kameras in der Synology Surveillance Station registriert, wo sie 24h aufnehmen. Meine Kameras sind intelligent und melden Bewegungen. Notfalls kann die Surveillance Station das Bild selbst auswerten, allerdings erhöht das die CPU-Last enorm. Ich kann dort einstellen, dass bei einer Bewegung eine URL aufgerufen wird:

<img width="733" alt="screen shot 2017-11-14 at 07 19 48" src="https://user-images.githubusercontent.com/1181349/32765781-649ae700-c90c-11e7-8e81-35acd10b1698.png">
<img width="730" alt="screen shot 2017-11-14 at 07 19 38" src="https://user-images.githubusercontent.com/1181349/32765786-67e7b712-c90c-11e7-9d92-7bcae97c3b7c.png">
![Uploading Screen Shot 2017-11-14 at 07.19.27.png…]()
<img width="732" alt="screen shot 2017-11-14 at 07 19 16" src="https://user-images.githubusercontent.com/1181349/32765788-6834186e-c90c-11e7-84d5-db2c4d1cb29d.png">
<img width="802" alt="screen shot 2017-11-14 at 07 18 57" src="https://user-images.githubusercontent.com/1181349/32765789-684ddd26-c90c-11e7-979f-82415b64031b.png">
<img width="808" alt="screen shot 2017-11-14 at 07 18 41" src="https://user-images.githubusercontent.com/1181349/32765790-686c87e4-c90c-11e7-8920-7de8841ce8aa.png">

d.h. es passiert folgendes:

- Die Kamera bemerkt eine Bewegung
- die Action Rule ruft die URL für den Bewegungsmelder in homebridge-http-motion-sensor
- HomeKit bemerkt eine Bewegung und schickt für jede Kamera im gleichen Raum eine Meldung mit Snapshot der Kamera

Wenn Du keine Synology Surveillance Station (oder ähnliches Produkt) hast, kann ich Dir sowas nur ans Herz legen, da diese Systeme die Kamera aufzeichnen, in meinem Fall 90 Tage. So kann man - nachdem was passiert ist - die Aufnahmen sichern und der (dankbaren!) Polizei geben.

**Comment by jannnfe** [comment]
@dkrizic Danke für deine ausführliche Antwort.
Wenn ich die URL des Homebridge Sensors im Browser öffne schlägt er auch aus.
Bis jetzt habe ich noch nichts gefunden, den URL Request durch das Programm Zoneminder zu starten. Ich möchte, dass sobald Zoneminder ein neues Event erstellt der Sensor reagiert.

**Comment by dkrizic** [comment]
@jannnfe Ich kenne Zoneminder nicht, das mit den URLs ist tatsächlich ein Feature der Synology Surveillance Station. Ich hatte vorher auch mal geschaut, ob es einen Linux-Client für die ONVIF-Kameras gibt, die ich habe, aber ich habe nichts brauchbares gefunden.

**Comment by nicoh88** [comment]
@sweidinger Ich denke dein "Problem" / "Feature" wurde auf anderen Wege gelöst. Ich kann hier zu machen oder?

**Comment by martinzuern** [comment]
Wer hier nach all der Zeit noch eine Lösung sucht: Ich habe die "Virtual Buttons" der Fernbedienung umkonfiguriert zu Motion Sensors. Wenn man dann auf einer der Tasten (z.B. in einem Programm) den `SHORT_PRESS` auslöst, dann triggert der Motion Sensor für eine Sekunde. Einzige Anpassung dafür in der `homematic_config.json`:

```json5
{
  # weitere Konfiguration
  "services": [
    {
      "type": "HM-RCV-50:VIRTUAL_KEY",
      "service": "HomeMaticHomeKitDoorBellMotionService"
    }
  ]
}
```
