### ISSUE TITLE
Homematic HM-CC.TC Aktor wird nicht erkannt

### ISSUE THREAD

**Issue by Wolf6660** [thkl/homebridge-homematic#17]
Hallo,

ich habe auf meinem RPI Homebridge mit dem Homematic Plugin installiert. Er hat auch alle Rolladenaktoren und Licht bzw. Schaltaktoren erkannt. Nur die Heizungssteuerung mit den Aktoren HM-CC-TC werden nicht erkannt. Werden diese nicht unterstützt oder mache ich etwas falsch? Gibt es eine Möglichkeit diese manuell einzubinden?

Einen neueren Heizungsakter (HM-TC-IT-WM-EU) wird erkannt.

Für eine Rückmeldung wäre ich sehr dankbar.

 
Gruß

Daniel

**Comment by thkl** [comment]
Ich mach schon mal zu, geht ja im nächsten release
