### ISSUE TITLE
Keine Aktualisierung wenn Homematic beim Start HB noch nicht bereit

### ISSUE THREAD

**Issue by Sonsi79** [thkl/homebridge-homematic#170]
Hi Thomas,
ich habe einen kleinen Fehler gefunden. 
Wenn ich die Homebridge starte, aber die Homematic noch nicht fertig hochgefahren ist (Stromausfall), werden die Werte und Status nachdem die Homematic hochgefahren ist nicht mehr aktualisiert.
Ich muss erst die Homebridge neu starten damit es wieder geht.

Nehme an das HB-HM versucht Werte zu erhalten aber die HM keine Liefert da noch im Boot Vorgang und dann irgendwie aufgibt :-)

Kann man das irgendwie fixen oder umgehen?
Eine Art Retry nach 120 Sekunden oder so...

lieben Gruß Christoph

**Comment by thkl** [comment]
Jain ... wenn die Homematic nicht da ist können keine Geräte gelesen werden. Das muss aber zum Start erfolgen. 

Man könnte das ggf abfangen indem man wartet bis die ccu reagiert. Aber solange fährt Homebridge auch nicht hoch.

**Comment by Sonsi79** [comment]
Das klingt nach eine Lösung.
Kann mr vorstellen dass viele die ihre Homematic als YAHM Container starten das gleiche Problem haben.
Bein Bootvorgang des Pi startet ja alles zugleich und die Homematic braucht ca 60 Sekunden länger als die Homebridge.

Denke es könnte schon reichen, dass HB-HM wenn keine CCU2 gefunden wird oder antwortet einfach im 60 Sekunden Takt einen retry durchführt.

Bin aber für jede Idee oder Lösung dankbar :-)

**Comment by thkl** [comment]
Das hier als Startscript in /etc/init.d/homebridge wartet auf einem YAHM auf den Start von rega.

```
#!/bin/sh
### BEGIN INIT INFO
# Provides:	homebridge
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


dir="/home/pi"
cmd="homebridge"
user="pi"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Wait for Rega ... zzzZZZ"
        until pids=$(pidof ReGaHss)
        do   
          sleep 1
        done

        echo "Rega is Alive"
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
```

**Comment by dehsgr** [comment]
Ich trage es mal hier ein, da sehr ähnlich gelagert:
Wenn ich die CCU neustarte, dann werden die Werte (ohne Neustart von homebridge) auch nicht mehr auf dem Phone aktualisiert. Erst der Neustart von homebridge schafft hier abhilfe. Ohne diesen, scheinen irgendwie nur gecachte Werte herangezogen zu werden.

**Comment by thkl** [comment]
Das ist so.

**Comment by mach1009** [comment]
Ich habe dieses Problem gelöst, indem ich mir homebridge Server installiert habe und darüber mit einem Script per URL nach dem Neustart der CCU einen Neustart der Homebridge aufrufe.

**Comment by dehsgr** [comment]
@mach1009: Danke für den Tipp! Das werde ich mal ausprobieren...

**Comment by mach1009** [comment]
Sag Bescheid, wenn ich dir die Scripte schicken soll. Grüße

**Comment by krobipd** [comment]
@thkl I did everything you mention but homebridge won't start at boot. do I have to do something different? do I need to do something else? I created the file in the folder you mention with your content, is that everything?

**Comment by mach1009** [comment]
@chip131001 
Sorry für die lange Wartezeit.

Ich habe mir praktisch nur 'homebridge Server' installiert und rufe über ein Script nach dem Neustart der CCU den "Restart" Link auf.

Also CCU Programm anlegen --> 'Wenn' bleib leer.
Script anlegen --> Verzögert um 90s
Script: 
`string url = "http://raspberrypi:8765/restart";
dom.GetObject("CUxD.CUX2801001:1.CMD_EXEC").State("wget -q -O - "#url);`

Da die CCU bei Start immer alle Programme abarbeitet, wird das Script aufgerufen.

**Comment by mach1009** [comment]
@chip131001 
Sorry. Da bin ich raus. Ich habe bei mir keine Passworteingabe eingerichtet.
