### ISSUE TITLE
homebridge-homematic und historian am gleichen raspi ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#171]
@thkl ... hallo Thomas
Kurze Frage.... kann ich historian und homebridge-homematic am gleichen raspi laufen lassen ??
historian nutzt laut doku auch Port 9090/9091

Danke für eine kurze Info

lg Richard

**Comment by thkl** [comment]
Das geht du kannst über einen Config Eintrag den Port ändern.

**Comment by thkl** [comment]
Achso der Parameter heißt local_port

**Comment by roe1974** [comment]
ok.... aber sowohl dein plugin also auch historian reden mit der CCU
trotzdem dürfen die posts nicht die gleichen sein ?

**Comment by thkl** [comment]
Nein weil auf einen Port kann immer nur ein Prozess lauschen.

**Comment by dkrizic** [comment]
Klugscheisser: Pro Interface

eth0: Port X != eth1: Port X

wobei 0.0.0.0 auf allen Interfaces lauscht.

**Comment by roe1974** [comment]
ok danke :):):)

**Comment by thkl** [comment]
Badummmmm tsssss

**Comment by roe1974** [comment]
@thkl 
@dkrizic 
... wenn aber historian auf einer synolgy rennt brauche ich keine rücksicht auf die ports nehmen....oder ?

lg Richard

**Comment by roe1974** [comment]
@dkrizic 
also damit ich es verstehe:
ich nutze am raspi (homebridge) port 9090/9091/9092 /default)
wenn jetzt historian auf der synolgy läuft ... können dort nicht die standard ports 9090 und 8080 verwendet werden ????
Steh grad am schlauch ;-)

**Comment by dkrizic** [comment]
Die Synology belegt auch irgendwelche Ports, bei mir sind das z.B. 

`PORT      STATE SERVICE
21/tcp    open  ftp
22/tcp    open  ssh
80/tcp    open  http
81/tcp    open  hosts2-ns
83/tcp    open  mit-ml-dev
84/tcp    open  ctf
85/tcp    open  mit-ml-dev
111/tcp   open  rpcbind
139/tcp   open  netbios-ssn
161/tcp   open  snmp
443/tcp   open  https
445/tcp   open  microsoft-ds
548/tcp   open  afp
554/tcp   open  rtsp
2049/tcp  open  nfs
3306/tcp  open  mysql
5000/tcp  open  upnp
5001/tcp  open  commplex-link
49160/tcp open  unknown
50001/tcp open  unknown
50002/tcp open  iiimsf
`

In meinem Beispiel sind 9090 und 8080 frei, würden also laufen.

**Comment by roe1974** [comment]
Habe sonst nix laufen auf der synology......

**Comment by dkrizic** [comment]
Mach doch einfach, es kommt eine klare Fehlermeldung, wenn der Port schon belegt ist. Ich kenne Historian jetzt nicht.

**Comment by roe1974** [comment]
ok...so mache ich es ;-)
DANKE jedenfalls
