### ISSUE TITLE
There is no service for HmIP-FROLL:SHUTTER_VIRTUAL_RECEIVER

### ISSUE THREAD

**Issue by nicoh88** [thkl/homebridge-homematic#174]
Hi,

ich habe 4 Homematic IP Rollladenaktor HmIP-FROLL Unterputz (HM-TC-IT-WM-W-EU) im Einsatz.
Im Terminal sehe ich beim Starten der Homebridge folgende Meldungen:

```
[HomeMatic CCU] There is no service for HmIP-FROLL:SHUTTER_VIRTUAL_RECEIVER
[HomeMatic CCU] There is no service for HmIP-FROLL:SHUTTER_VIRTUAL_RECEIVER
[HomeMatic CCU] There is no service for HmIP-FROLL:SHUTTER_VIRTUAL_RECEIVER
[HomeMatic CCU] There is no service for HmIP-FROLL:SHUTTER_VIRTUAL_RECEIVER
```

Ich habe den Kanal 4 dem HomeKit-Gewerk zugeordnet, mit diesem Kanal kann ich auf der CCU2 Startseite den Aktor bedienen - daher sollte der Fehler eigentlich nicht bei mir liegen.

![bildschirmfoto 2017-11-04 um 14 41 09](https://user-images.githubusercontent.com/264264/32405902-7fa601d8-c16e-11e7-86b4-a8ad51dae511.png)
![bildschirmfoto 2017-11-04 um 14 41 57](https://user-images.githubusercontent.com/264264/32405903-7fbfa124-c16e-11e7-9649-3e065b3c919d.png)

Werden die HmIP Rollladenaktor noch nicht von homebridge-homematic unterstützt?

Gruß Nico

**Comment by thkl** [comment]
mal bitte zum test die neue channelconfig https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/channel_config.json tauschen .. damit sollte es gehen.

**Comment by nicoh88** [comment]
**Funktioniert! Vielen Dank für die schnelle Hilfe!**

```
[HomeMatic CCU] Initializing platform accessory 'Rollladen Fenster Küche'...
[HomeMatic CCU] Initializing platform accessory 'Rollladen Fenster WZ'...
[HomeMatic CCU] Initializing platform accessory 'Rollladen Oberlicht WZ'...
[HomeMatic CCU] Initializing platform accessory 'Rollladen Terrassentür WZ'...
```

![img_6515](https://user-images.githubusercontent.com/264264/32408279-b3acea4c-c195-11e7-9b84-c7adb525c5d2.jpg)

**Comment by thkl** [comment]
Super dann npm‘e ich das mal für den Rest der Welt

**Comment by maweiler** [comment]
Hi,

Ich musste meinen Rasp neu aufsetzen, aber Dank der bekannten Anleitungen war das kein Problem. Nur leider läuft nicht alles rund. 

Beim Start der homebridge kommt jetzt folgende Fehlermeldung

[20/11/2020, 19:39:18] [HomeMatic CCU2] [ServiceClassLoader] There is no service for HM-RC-19:BLIND
[20/11/2020, 19:39:18] [HomeMatic CCU2] [ServiceClassLoader] There is no service for HM-RC-19:BLIND
[20/11/2020, 19:39:18] [HomeMatic CCU2] [ServiceClassLoader] There is no service for HM-RC-19:BLIND
[20/11/2020, 19:39:18] [HomeMatic CCU2] [ServiceClassLoader] There is no service for HM-RC-19:BLIND
[20/11/2020, 19:39:18] Initializing platform accessory ‘HM Sec SCo OEQ0493118 1’…
[20/11/2020, 19:39:18] Initializing platform accessory ‘Heizung Wohnzimmer INT0000001 1’…

Ich habe auf meiner CCU2 HM-RC-19 als Rollladensteuerung eingebunden. Auf der CCU2 läuft alles perfekt und bis zum neu aufsetzen war das alles kein Problem. Nur jetzt kommt diese Fehlermeldung und ich kann die Rolladen über homebridge nicht mehr steuern. Hast du eine Idee??

Gruß
Martin

**Comment by dirk777** [comment]
@thkl: I experience the same issue with HmIP-BROLL-2:SHUTTER_VIRTUAL_RECEIVER.

I'm just adding 
```
{
    "type": "HmIP-BROLL-2:SHUTTER_VIRTUAL_RECEIVER",
    "service": "HomeMaticHomeKitBlindServiceIP"
}
```

This works fine for me.
