### ISSUE TITLE
RaspberryMatic CCU - Plugin findet keine Devices

### ISSUE THREAD

**Issue by thezepter** [thkl/homebridge-homematic#18]
Hallo,

ich bin nun endlich von meinem alten LAN Adapter weg um auch in den Genuss von diesem Plugin zu kommen und habe einen Raspberry Pi 2 mit der originalen HomeMatic Software laufen (RaspBerryMatic). Identisch zur CCU2.

Ich bekomme aber keine Devices hinzugefügt.

Siehe Initialisierung:
![homebridge_homematic](https://cloud.githubusercontent.com/assets/2700279/14314735/55d1fe16-fbf9-11e5-9f71-9c02901be34b.PNG)
![homebridge_homematic_2](https://cloud.githubusercontent.com/assets/2700279/14314831/fec226cc-fbf9-11e5-9022-c93a0c5b0d41.PNG)

Kenn hier jemand helfen ? Oder kann ich helfen, falls das Plugin hiefür irgendwie angepasst werden müsste ?!

**Comment by JensBonse** [comment]
Generell funktioniert die RaspberryMatic problemlos mit der HomeBridge. Habe es so im Einsatz.

Wie schaut denn deine Konfiguration aus? Hast du ggf. auf ein Gewerk gefiltert das es nicht gibt?

**Comment by thezepter** [comment]
So sieht bei mir der Configabschnitt aus. Absolut nichts drin.

		{
			"platform": "HomeMatic",
			"name": "HomeMatic CCU",
			"ccu_ip": "192.168.2.85",
			"filter_device":[],
			"filter_channel":[],
			"outlets":[],
			"doors":[],
			"programs":[],
			"subsection":""
  	}

**Comment by JensBonse** [comment]
Lass 'subsection' mal ganz weg.
Also so:

    {
        "platform": "HomeMatic",
        "name": "HomeMatic CCU",
        "ccu_ip": "192.168.2.85",
        "filter_device":[],
        "filter_channel":[],
        "outlets":[],
        "doors":[],
        "programs":[]
}

**Comment by thezepter** [comment]
:-) Sauber ! Danke
![geht](https://cloud.githubusercontent.com/assets/2700279/14315409/454a5ca6-fbfd-11e5-987f-15af15791b96.PNG)
