### ISSUE TITLE
Homebridge-Homematic "Keine Antwort"

### ISSUE THREAD

**Issue by sascha080290** [thkl/homebridge-homematic#180]
Hallo zusammen,

vllt. kann mir hier jemand helfen. Ich habe in letzter Zeit öfter Probleme mit HomeKit und meinen Homemati-Geräten gehabt.

Ich habe am Montag meinen RPi3 neu aufgesetzt und es hat auch alles PERFEKT funktioniert. Meine Homematic-Geräte sind am iPhone alle ersichtlich und konnten gesteuert werden. Aber seit heute morgen bekomme ich, wie vor Montag vor dem Aufsetzen, wieder von allen Geräten "keine Antwort". Meine Geräte, welche direkt in HomeKit eingebunden sind (z. B. elgato eve energy) funktionieren weiterhin und können auch gesteuert werden - nur die Homematic-Geräte nicht mehr.

An der CCU2 kann es aber auch nicht liegen, da über meine EASY-App alles funktioniert und gesteuert werden kann.

Die Homebridge selbst läuft auch korrekt und nach meinem Test "sudo systemctl status homebridge -l" werden auch alle Geräte aus Homematic korrekt angezeigt. 

Ich verstehe deshalb auch nicht, weshalb ich in HomeKit schon wieder "keine Antwort" habe?!

**Comment by nicoh88** [comment]
Hi sascha080290,

ich hatte vor ein paar Monaten ähnliche Probleme, diese wurden aber durch ein [HomeBridge Core](https://github.com/nfarina/homebridge) Update langfristig gelöst - es lag nicht am [homebridge-homematic](https://github.com/thkl/homebridge-homematic/) Plugin. Bei mir half auch nur eine Neuinstallation, bzw. das Ändern der MAC-Adresse (_username in config.json_) in der HomeBridge Konfiguration, damit die Geräte wieder verfügbar waren. Dadurch musste aber auch die Apple Home App komplett neu eingerichtet werden - Zuordnungen, Szenen, Benachrichtigungen, Automationen, etc.

**Folgende Fragen ergeben sich erstmal:**
**1.:** Hast du nur HomeMatic Geräte im HomeBridge oder auch andere? (nicht Elgato, weil nicht über HomeBridge)
**1.1.:** Werden diese auch als "keine Antwort" / "nicht verfügbar" angezeigt?
**1.2.:** Welche HomeBridge Plugins hast du noch in der config.json?
**2.:** Was bekommst du für einen Output, wenn du folgenden Befehl auf dem Terminal ausführst ...
**2.1.:** ... `npm -g outdated --long`
**2.2.:** ... `npm list -g --depth=0`

Gruß Nico

**Comment by sascha080290** [comment]
hey zusammen,
es funktioniert wieder, Neustart Apple TV... Was für mich trotzdem keinen Sinn macht, weil angelegte Automationen trotzdem verschwunden sind - jedes Mal die letzten Wochen.

zu den Fragen
1 Ich habe noch ein weiteres plugin (rcswitch-gpiomem).
1.1 Die Geräte waren ebenfalls nicht mehr erreichbar.
1.2 nur rcswitch-gpiomem (3 Geräte/Switch)
2.1 nichts - alles aktuell
2.2 /usr/local/lib
├── homebridge@0.4.33
├── homebridge-homematic@0.0.96
├── homebridge-rcswitch-gpiomem@1.1.4
└── npm@5.5.1

**Comment by nicoh88** [comment]
@sascha080290 Das Problem ist sicher nicht mehr aufgetreten, oder? Mache hier zu.
