### ISSUE TITLE
HM-LC-Sw1-FM wird als Licht erkannt

### ISSUE THREAD

**Issue by krobipd** [thkl/homebridge-homematic#183]
Hallo

dein Plugin funktioniert echt super aber für mich gibs hier einen kleinen Schönheitsfehler.

Ich habe den Homematic HM-LC-Sw1-FM verbaut um eine Steckdose zu schalten.
Mein Problem damit ist jetzt dass dieser Switch in der Home App als Licht behandelt wird.

Es wäre toll wenn das ein normaler Switch wäre und kein Licht.

Gibt es irgendwas was Ich tun kann um das zu ändern?
![fullsizeoutput_b71](https://user-images.githubusercontent.com/27220902/33221554-a49597aa-d150-11e7-98cf-e16321545ebb.jpeg)

**Comment by thkl** [comment]
Steht in der Readme Stichwort Outlets

**Comment by krobipd** [comment]
könntest du mir bitte sagen was ich da wo eintragen soll? ich verstehe nicht welchen wert du da drin stehen haben magst. Seriennummer? Typenbezeichnung? Was? ist für mich nicht verständlich was du da haben willst.

**Comment by krobipd** [comment]
ok so habs selbst herausgefunden, wäre schön wenn du das etwas genauer erklären würden in der readme. daraus wird nämlich niemand schlau :-(

so jedenfalls der string lautet
`"outlets":["BidCos-RF.OEQxxxxxx:1", "BidCos-RF.OEQxxxxx:1"],`

die xxx stehen für die Seriennummer.

**Comment by bprskalo** [comment]
nun, wenn man sich etwas intensiver mit der ganzen Thematik befasst, ist die Anleitung verständlich :-)

wichtig ist, dass falls du die Zeile zwischen andere Zeilen einfügst ein Komma (,) am Schluss rein schreibst, ansonsten wird Deine Konfiguration nicht starten

Wenn Du nur ein Gerät (also einen HM-LC-Sw1-FM) verbaut hast würde Dein Eintrag so aussehen : 

"outlets":[ "BidCos-RF.KEQXXXXXXX:4"],

und ja in diesem Beispiel musst Du "KEQXXXXXXX" mit der Serienummer Deines HM-LC-Sw1-FM ersetzen
