### ISSUE TITLE
HM-LC-Sw4-WM lässt sich nicht per Homekit schalten

### ISSUE THREAD

**Issue by Baenker** [thkl/homebridge-homematic#184]
Ich hab da mal ein Problem  :mrgreen: 

Ich habe in der Garage den Schaltaktor, 4-fach (HM-LC-Sw4-WM). Auf den 3 Kanal habe ich das Licht vom Hörman-Tor angeschlossen.

Diesen Kanal habe ich ganz noraml über das Gewerk in Homekit aufgenommen. Es wird mir in meinen Fall richtigerweise als Licht angezeigt.

Das Licht wird mir ganz normal angezeigt und auch mit dem richtigen Status. Wenn ich es z. B. über Pocket Control, ein Programm oder pe Webui schalte wird mir der Status ebenfalls richtig in Homekit aktualisiert.

Nur selber schalten funktioniert nicht? Siri meldet mir zwar das er den Befehl abgesetzt hat aber es passiert nichts. Auch per Button in der Homekit-App passiert nichts?

Schalten kann ich ganz normal mittels:

dom.GetObject("BidCos-RF.NEQ1459610:3.STATE").State(true);

Habe nur ich das Problem oder ist es vielleicht noch ein kleiner Fehler?

**Comment by pbksol** [comment]
Ich kann zumindest für den HM-LC-Sw4-Ba-PCB von dem hier einige arbeiten sagen, dass es tadellos funktioniert. Technisch sind die beiden Geräte ja prinzipiell identisch.

**Comment by Baenker** [comment]
Vielleicht verhält sich der HM-LC-Sw4-Ba-PCB anders oder ist im Code speziel deklariert?

Was mich halt wundert ist das Homekit Statusänderungen die ich mittels HM-App oder per Webui tätige richtig angezeigt werden.
