### ISSUE TITLE
HmIP-STH als "dummen" Temp-/Feuchte-Sensor auswerten?

### ISSUE THREAD

**Issue by pbksol** [thkl/homebridge-homematic#185]
Nehmen wir an, man hätte in Räumen ohne Heizungen die Temperatur/Feuchtesensoren HmIP-STH verteilt und möchte diese eigentlich nur als "dumme" Sensoren für Temperatur und Feuchtigkeit benutzen.

Leider ist es weder möglich wie bei den echten HM-Wandthermostaten den Kanal für HB zu aktivieren, der nur diese beiden Werte ausgibt, noch lässt sich der HmIP-STH in eine Heizungsgruppe packen um dann darüber an die Werte zu kommen. Anderes Thema, aber die Anbindung von HmIP an die CCU ist ganz nett, aber schön ist echt anders.

Hat jemand eine Idee wie man dieses Problem lösen könnte? Ich habe schon mit den Services gespielt, aber so wirklich erfolgreich war da bisher keiner der Versuche. Vielleicht hat das ja schon mal jemand gelöst…? Prinzipiell ist der HmIP-STH nichts anderes als ein HmIP-Wandthermostat ohne Display und Knöpfchen und verhält sich auch so.

**Comment by nicoh88** [comment]
@pbksol: Ist das hier noch relevant? 

Was möchtest du genau haben? So wie ich dich verstanden habe, möchtest du für einen HmIP-STH, zwei Kacheln (Temp & Feuchte) in HomeKit haben?

So wird es aktuell angezeigt:
![img_8605](https://user-images.githubusercontent.com/264264/37491182-43d2f62a-289d-11e8-8819-6c06b33be404.png)
![img_8606](https://user-images.githubusercontent.com/264264/37491184-45a63624-289d-11e8-965d-916652fb648b.png)

Reicht das dir nicht?

Gruß Nico

**Comment by pbksol** [comment]
Ich hatte ein bisschen die Hoffnung, dass man die beiden Werte für Temperatur und Feuchtigkeit über eine selbstdefinierbare Vorlage so extrahieren könnte, dass man sie angezeigt bekommt wie ein Thermometer und einen Feuchtigkeitsmesser -- also ohne die Thermostatfunktion.

**Comment by nicoh88** [comment]
Ehrlich gesagt, würde ich mir das so auch wüschen. 
Da ich meine zwei HmIP-STH, genau wie du, nur dafür benutze.

Die Thermostatfunktion bräuchte man nur, wenn man in Homematic eine Verknüpfung hat ggf. zu einem HmIP-FAL230-C6 oder HMIP-eTRV/2.

@thkl 
Könnten wir hier irgendetwas bauen, dass unter bestimmten Voraussetzungen (config.json) das "Thermostat" in HomeKit nicht als Thermostat angezeigt wird, sondern einfach nur zwei "dumme" Kacheln für Temperatur und Luftfeuchtigkeit bekommt?
Ich stelle es mir vor wie bei "Doors and Windows"...

**Comment by thkl** [comment]
Siehe letzten commit für #215  demnächst können für jeden Gerätetyp in der config.json Einstellungen mitgeliefert werden.  Da kann man sowas auch unterbringen.

**Comment by qwikser** [comment]
Das wäre wirklich eine Tolle Sache!  Habe nämlich eben gesehen das bei mir gar keine "Feuchte" mehr ankommt da ich mit der neuen Funktion "Virtuelle Gruppen" arbeite. Siehe:
![img_1764](https://user-images.githubusercontent.com/24945399/37588379-57de2f82-2b62-11e8-86e8-f80d270554c4.PNG)
![img_1765](https://user-images.githubusercontent.com/24945399/37588381-5aa9ef94-2b62-11e8-93f1-b73a640b0710.PNG)

**Comment by thkl** [comment]
Virtuell Gruppen haben aber, so weit ich weiss keinen Datenpunkt für Feuchtigkeit.

**Comment by qwikser** [comment]
..deswegen würde ich diese ja mit Trick 17 von hinten durch die Brust rein zaubern... 😛

**Comment by tkoenig** [comment]
Also ich hab das kurz mal getestet den `HomeMaticHomeKitThermostatWeatherService` für den HmIP-STH zu benutzen. 
Das geht prinzipiell wenn man statt `TEMPERATURE`  `ACTUAL_TEMPERATURE` abfragt und den Gerätetyp dann über die `services` zuweist..

Im grossen und ganzen sieht das so aus:
```
this.hmTemperatureVariable = (this.deviceType == "HmIP-STH" ? 'ACTUAL_TEMPERATURE' : 'TEMPERATURE');
```

und in der config fügt man unter services folgendes hinzu:

```
{ "type": "HmIP-STH:HEATING_CLIMATECONTROL_TRANSCEIVER",
   "service": "HomeMaticHomeKitThermostatWeatherService"}
```

@thkl wenn das Sinn macht mache ich gerne einen pull-request oder willst du das wie erwähnt anders lösen?

**Comment by thkl** [comment]
@tkoenig oh gerne. Die beste Lösung wäre sicher eine eigene Serviceklasse dafür. Ich möchte die einzelnen Klassen so generisch wie möglich halten.

**Comment by qwikser** [comment]
Huhu - und wie mach ich das jetzt mit den Virtuellen Gruppen und des fehlenden Feuchtigkeitswertes? Neues Ticket?

**Comment by nicoh88** [comment]
@qwikser: Ja, bitte ein neues Issue und genau erklären. Danke 

@thkl @tkoenig:
Danke, läuft.

```
"services": [
  { "type": "HmIP-STH:HEATING_CLIMATECONTROL_TRANSCEIVER",
    "service": "HomeMaticHomeKitThermostatWeatherServiceIP" }
]
```

<img src="https://user-images.githubusercontent.com/264264/38054050-149a6fb2-32d6-11e8-9eac-23eaed7df81e.jpeg" width="400"/>

**Comment by DatTobi** [comment]
@thkl @qwikser 

Hallo,

verzeiht bitte meine Unwissenheit, aber ich versuche verzweifelt meinen HmIP-STH über den WheatherService einzubinden. Beim Start von Homebridge bekomme ich aber immer folgende Fehlermeldung:

module.js:549
    throw err;
    ^

Error: Cannot find module 'fakegato-history'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at HomeMaticHomeKitThermostatWeatherService.enableLoggingService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:218:36)
    at HomeMaticHomeKitThermostatWeatherService.createDeviceService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermostatWeatherService.js:18:8)
    at HomeMaticHomeKitThermostatWeatherService.HomeKitGenericService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:105:8)
    at new HomeMaticHomeKitThermostatWeatherService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermostatWeatherService.js:7:51)
    at HomeMaticChannelLoader.loadChannelService (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:95:19)
    at device.channels.map.ch (/usr/local/lib/node_modules/homebridge-homematic/index.js:340:22)
    at Array.map (<anonymous>)
    at json.devices.map.device (/usr/local/lib/node_modules/homebridge-homematic/index.js:300:21)
    at Array.map (<anonymous>)
    at HomeMaticPlatform.buildaccesories (/usr/local/lib/node_modules/homebridge-homematic/index.js:288:16)
    at regarequest.script.data (/usr/local/lib/node_modules/homebridge-homematic/index.js:234:9)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:43:9)


Irgendwie scheint bei mir was zu fehlen. Könnt ihr mir sagen, was ich da noch ergänzen muss?
Dazu sei gesagt, dass ich kompletter Anfänger bin. Ich würde mich über eine kleine Anleitung freuen.

Vielen Dank vorab und schöne Grüße
Tobi
