### ISSUE TITLE
thermostat - home app zeigt immer an "wird geheizt"

### ISSUE THREAD

**Issue by krobipd** [thkl/homebridge-homematic#186]
mir ist aufgefallen das die home app immer anzeigt das meine Thermostate heizen würden.

zB festgestellte Temperatur 23 grad, am thermostat eingestellt sind 17 grad.

trotzdem schreibt die home app ständig das auf 17 grad geheizt wird.

es wäre schön wenn das geschlossene Thermostat als AUS gekennzeichnet wäre.
somit wären die Status Infos der Home App richtig.

**Comment by pbksol** [comment]
Die Home-App zeigt immer an, wenn auf einen bestimmten Wert geheizt werden soll. Was bei den Homematic-Thermostaten nicht passiert ist die Übermittlung des aktuellen Ventilstatus. Die Home-App unterscheidet zwischen einem Orangen Hintergrund für die Temperatur für "es wird geheizt" und einem Grünen Hintergrund für "Temperatur erreicht". Es fehlt im Prinzip nur die Auswertung der Ventilstellung so das alles >0% orange angezeigt wird und 0% grün.
Für die Homematic-IP-Thermostate gibt es diese Funktionalität bereits. Ohne mir den Code detailliert angeschaut zu haben könnte ich mir vorstellen, dass es damit zusammenhängen könnte, dass HmIP alle Statusdaten in einem Kanal schickt, Homematic diese über mehrere Kanäle verteilt und daher kein Zugriff darauf möglich ist.

**Comment by krobipd** [comment]
danke für die ausführlich Antwort. ja das wäre klasse wenn man das Modul um diese Funktion für die homematic heizkörperthermostate erweitern könnte.

**Comment by Baenker** [comment]
Homematic Gruppen sollte man aber eher nicht nutzen, denn dort stimmt die Ist-Temperatur nicht. Diese wird nur einmalg beim Start von Homebridge gezogen und dann nicht aktualisiert.

Wenn ich mich nicht täusche wird heizen nicht angezeigt wenn man die Heizung ausstellt. Ansonsten ist die Information ja grundsätzlich nicht ganz falsch. Es wird ja lediglich der Modus angezeigt und nicht ob ein Heizventil offen steht....

**Comment by pbksol** [comment]
@Baenker ohne jetzt ein Gscheidhaferl sein zu wollen… Die Gruppen enthalten sehr wohl die Ist-Temperatur. Sie wird von dem Homebridge-Homematic-Plugin lediglich einmalig ausgewertet.

**Comment by thkl** [comment]
Ja, das ist so. Da die Gruppen keine Events senden, wird die Temperatur nur abgefragt, wenn HomeKit eine get Event sendet.

**Comment by Baenker** [comment]
@thkl am 21.10. hattest Du ins Homematic Forum geschrieben: Ich habe es gerade mal getestet. Das IF sendet Events. Aber ich höre nicht drauf. :lol: Sondern nur auf BidCos-RF ; HmIP und Wired.

@pbksol Hatte ich doch genau so geschrieben??

**Comment by pbksol** [comment]
@Baenker uups… Hast Recht… Zu viel "Home" auf einmal xD

**Comment by thkl** [comment]
Ok dann so rum.  Also die Events werden ignoriert. Wenn man das Gerät im Home öffnet wird es dann nicht aktualisiert ?

**Comment by alexduerl** [comment]
Hallo Zusammen,
Ich kann das hier beschriebene bestätigen:
- Soll-Temperatur auf 21%
- Ist-Temperatur auf 17%
—> Temperatur-Symbol in der HomeApp orange, Anzeige „wird geheizt auf 17%“

Die HomeApp versteht also nicht dass der Sollwert erreicht ist ...

**Comment by pbksol** [comment]
Ja, weil die Homematic-Komponenten nicht alle wissen wie die aktuelle Ventilstellung ist. Das kann man bei einigen Geräten zwar auswerten, aber es ist halt keine allgemein gültige Lösung. Aktuell wird diese Information nach meinem Kenntnisstand von dem Plugin gar nicht ausgewertet.

**Comment by alexduerl** [comment]
Auf Kanal 8 kommen 4 Werte mit:

[HomeMatic CCU2] RPC event for HmIP-RF.000C9709AC8D68:8 EMERGENCY_OPERATION with value false
[HomeMatic CCU2] RPC event for HmIP-RF.000C9709AC8D68:8 FROST_PROTECTION with value false
[HomeMatic CCU2] RPC event for HmIP-RF.000C9709AC8D68:8 STATE with value false
[HomeMatic CCU2] RPC event for HmIP-RF.000C9709AC8D68:8 HUMIDITY_ALARM with value false

Der STATE ist der Schaltzustand, der auch in der CCU2 angezeigt wird:

true = es wird geheizt
false = es wird nicht geheizt

Gibt es eine Möglichkeit den auszuwerten und damit die Anzeige in der HomeApp zu beeinflussen?

LG

**Comment by alexduerl** [comment]
... vielleicht werde ich hier aber jetzt auch gerade die "Homematic Heizkörperthermostate" und die "Homematic Wandthermostate für Fussbodenheizung" durcheinander. Wenn das so sein sollte, bitte ich um Verzeihung ...

Ich spreche von einem "Homematic IP Wandthermostat mit Schaltausgang für die Fussbodenheizung".

Hier wird der Schaltzustand wie zuvor beschrieben übermittelt.

Bei den Heizkörperthermstaten ist wahrscheinlich wie hier richtig geschrieben die Ventilstellung wichtig ...

**Comment by pbksol** [comment]
Guck mal ein bisschen weiter oben. Vor einem Monat habe ich mal aufgeschrieben welche Geräte was können hier in diesem Thread und auch was die konkreten Probleme sind.

**Comment by alexduerl** [comment]
stimmt, hast recht ... sorry.

Aber käme man dann nicht bei den IP-Geräten über den Schaltzustand an die notwendige Information?
Leider weiß ich nicht wie sich die Geräte im Kühl-Modus verhalten ...

**Comment by thkl** [comment]
Also mal zur Klarstellung wie die Klasse funktioniert:

HomeKit Geräte kennen den Zustand: Heizen/Kühlen/Aus 

Die aktuelle Implementation setzt diesen Zustand wie folgt:

Solltemp ist 4,5 Grad (6 bei alten Thermostaten) = HomeKit Gerät geht auf „Aus“ (das entspricht der Thermostateinstellung „Off“)

sonst geht das HomeKit Gerät auf Heizen. 

Es ist dabei Wurst (🌭), ob die Soll > IstTemp ist. 


Hintergrund ist, das die Klasse für alle Thermostate (egal ob mit Ventilantrieb oder ohne) benutzt wird.  
Einen Ventilzustand kann ja bei einem Thermostat nicht abgelesen werden.
