### ISSUE TITLE
HmIP–FBL

### ISSUE THREAD

**Issue by Marcolist** [thkl/homebridge-homematic#188]
Bekomme immer die Meldung „no Service for HmIP–FBL....“
Werden diese aktuell nicht unterstützt?

**Comment by bprskalo** [comment]
ein hallo erst mal :-) 

grundsätzlich sind das BLINDS, die IP sind "noch" nicht in der aktuellen Version integriert , Du kannst diese aber relativ einfach selber einbauen .. oder ganz lieb Fragen ob es denn in der nächsten Version Fix eingebaut wird

Wie das geht steht im README.md ganz unten 

[https://github.com/thkl/homebridge-homematic#custom-serviceclasses](url)

**Comment by Hifclif** [comment]
Hallo bprskalo,
dies würde ich auch brauchen. Der Link geht leider nicht. Kannst du mir bitte weiterhelfen?
sg

**Comment by grinselwald** [comment]
Ich habe leider so gut wie keine Ahnung von der Programmierung... Also bleibt für mich nur abzuwarten, dass sie hoffentlich bald integriert werden!

**Comment by thkl** [comment]
Mahlzeit, sind das Rollo Aktoren mit Lamellenverstellung oder ohne ?

**Comment by legerp** [comment]
Moin, würde mich freuen wie ein schnitzel  - wenn es in der nächsten Version drin ist. Habe es über eine CustomServiceClass versucht, aber irgendwie kommt der Status der Jalousie nicht immer am iPhone an, bin aber neu im Thema -  Die Bedienung funkt.
