### ISSUE TITLE
Humidity Werte

### ISSUE THREAD

**Issue by bprskalo** [thkl/homebridge-homematic#19]
Hallo Thomas

ist es richtig, das die "humidity" werte gemäss "pull request" nicht in der Version 26 sind :-) ?

wenn ja, würdest du diese noch mit einbauen .. ?

Danke !

Gruss

**Comment by thkl** [comment]
jetzt schon ;)

**Comment by bprskalo** [comment]
perfekt, danke !! und funktioniert auch :-)
