### ISSUE TITLE
Ansteuerung Heizung via Homebridge

### ISSUE THREAD

**Issue by moellerherm** [thkl/homebridge-homematic#190]
Hallo,

nachdem die Thermostate dem Gewerk "Homekit" zugeordnet wurden, bekomme ich beim starten der Homebridge folgenden Fehler: "there is no service for HM-CC-RT-DN: Climate Control receiver homebridge" Was mache ich ggfs. falsch....?
VG
Chris

**Comment by pbksol** [comment]
Welchen Kanal hast Du dem Gewerk zugeordnet?
