### ISSUE TITLE
Status der Geräte nicht korrekt

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#191]
Hallo zusammen, ich habe öfter (fast andauernd) das Problem, dass der Status der Geräte in der Home App. nicht richtig angezeigt wird. Bspw. für HM-LC-Dim1TPBU-FM oder HM-LC-Dim1T-DR. CCU2 und Rasp. ist für Homebridge und Homebridge-Homematic auf neusten Stand... Steuern der Geräte funktioniert weitestgehend problemlos, ausser dass die Home App. öfter mal "Aktualisieren..." anzeigt.

**Comment by pbksol** [comment]
Hast Du mehr als ein iOS-Gerät? Wenn auf einem dieses "Aktualisieren" angezeigt wird, mit dem zweiten Gerät einmal den gleichen Raum aufrufen. Wird der Status da dann sofort und korrekt angezeigt?

**Comment by iuliusmaximilian** [comment]
Ja, wir haben zwei iPhone und zwei iPads sowie zwei Apple Watches und ein ATV (4). Ja, der Status wird dann sofort und korrekt angezeigt. Bzgl. des falschen Status kann ich definitiv sagen, dass wenn ein Neustart des Rasp. dafür sorgt dass dann sofort alle Status korrekt angezeigt werden.

**Comment by pbksol** [comment]
Zu der Problematik mit der Anzeige "Aktualisieren" und der sofortigen Anzeigen auf einem anderen Gerät: die Ursache dafür würde ich nicht in der Homebridge suchen. Das passiert auch immer wieder mit Geräten, die für HomeKit zertifiziert sind. Bei Homebridge ist wichtig zu wissen, dass die Statusmeldungen der Reihe nach abgefragt werden. Ist also ein Gerät darunter, das länger für eine Antwort benötigt und/oder der Timeout im HB-Plugin zu lange gesetzt ist, dann dauert es bisweilen sehr lange bis zu einer Aktualisierung. Ruft dann ein zweites Gerät den Status ab, kann die Antwort schneller erfolgen und während das erste Gerät noch auf einen Status wartet ist die zweite Anfrage schon beantwortet. Ich hoffe man kann das irgendwie verstehen xD.

Zu den Sensoren und den Werten…
Zu den konkreten Dimmern kann ich nichts sagen, aber ich habe mit den LED-Dimmern für die Montage in der Zuleitung keinerlei solche Effekte beobachten können. Prinzipiell ist die Funktionsweise aber gleich.
Zu dem Fenstersensor… Das ist keine generelle Problematik der Homematic-Schnittstelle für Homebridge. Die zeigen in allen Installationen die korrekten Werte an und aktualisieren diese auch in Echtzeit wenn sich ein Status ändert.

Wie viele Geräte werden von der Homebridge an HomeKit übergeben? Sind noch andere Plugins in Homebridge installiert neben dem Homematic-Plugin? Das wären jetzt die Punkte an denen ich eine Ursache vermuten wollen würde. Das gesamte System läuft normalerweise sehr stabil und braucht keine Neustarts oder dergleichen.

**Comment by CyberChris79** [comment]
Hallo liebe Community,

leider habe ich das gleiche Problem.

Ich habe 2x HmIP-BROLL in Benutzung. Diese werden über eine CCU2 angesprochen.
Für die Homekit Ünterstützung nutze ich eine Raspberry Pi 3 mit einer Homebridge. Dort habe ich auch andere Plugins wie z.B. Fritz!, knx, IFTTT, Roomba und Homematic.

Ich habe alles über die Home App (iOS 11)mit Szenen eingerichtet das sich z.B. die Rollos bei Sonnenuntergang schließen und bei Sonnenaufgang öffnen. Die Automatik funktioniert auch einwandfrei, sobald ich aber die Home App öffne steht da leider noch ein alter Status drin. Erst wenn ich die Homebridge auf der Raspi neu starte, habe ich den aktuellen Status. 
Auch "enable hmip" steht auf true.

Dieses Problem tritt bei mir aber nur bei dem Homematic Plugin auf. Fritz! funktioniert seit Anfang an problemlos. Die anderen habe ich nicht so oft in Benutzung, sodass ich da noch keine Erfahrungen sammeln konnte. Ich habe dort festgstestellt, das das Fritz Plugin auch ständig den Status auf der Homebridge aktualisiert. 

Kann mir da jemand weiter helfen?

Grüße
CyberChris79

**Comment by CyberChris79** [comment]
Hallo liebe Community,

leider habe ich das gleiche Problem.

Ich habe 2x HmIP-BROLL in Benutzung. Diese werden über eine CCU2 angesprochen.
Für die Homekit Ünterstützung nutze ich eine Raspberry Pi 3 mit einer Homebridge. Dort habe ich auch andere Plugins wie z.B. Fritz!, knx, IFTTT, Roomba und Homematic.

Ich habe alles über die Home App (iOS 11)mit Szenen eingerichtet das sich z.B. die Rollos bei Sonnenuntergang schließen und bei Sonnenaufgang öffnen. Die Automatik funktioniert auch einwandfrei, sobald ich aber die Home App öffne steht da leider noch ein alter Status drin. Erst wenn ich die Homebridge auf der Raspi neu starte, habe ich den aktuellen Status.
Auch "enable hmip" steht auf true.

Dieses Problem tritt bei mir aber nur bei dem Homematic Plugin auf. Fritz! funktioniert seit Anfang an problemlos. Die anderen habe ich nicht so oft in Benutzung, sodass ich da noch keine Erfahrungen sammeln konnte. Ich habe dort festgstestellt, das das Fritz Plugin auch ständig den Status auf der Homebridge aktualisiert.

Kann mir da jemand weiter helfen?

Grüße
CyberChris79

> 

Hallo liebe Community,

ich glaube das ich das Problem gelöst habe, indem ich zur "enable hmip" zusätzlich noch die "local_ip" : "raspberry pi 3 ip adresse" eingetragen habe.
Zumindest ist es seitdem nicht mehr aufgetreten.

Grüße
CyberChris79

**Comment by iuliusmaximilian** [comment]
Hallo zusammen, die obige Info von @pbksol, dass Gerätestatus sequentiell abgearbeitet werden hat mich stutzig gemacht, da ich mind. zwei HM Autoren habe, die relativ weit weg von der CCU2 sind und manchmal den Kontakt verlieren. Mittlerweile habe ich hier einen Homematic 103755 Wired RS485 LAN Gateway installiert. Zusätzlich habe ich eine Wartungsroutine die einmal die Nacht sowohl die CCU2 als auch Homebridge auf dem Rasp3 inkl. Updates neu startet. Im Ergebnis tauchen die falschen Gerätestatus nicht mehr auf. @CyberChris79 local IP Hinweis habe ich gerade erst nachgeholt, mein Eindruck ist, dass das "Aktualisieren" jetzt beim Öffnen der Home App. schneller ist. Vielen Dank!
