### ISSUE TITLE
Dimmerstatus wird nicht aktualisiert

### ISSUE THREAD

**Issue by alexduerl** [thkl/homebridge-homematic#192]
Hallo Zusammen, Ich habe den Dimmer „HmIP-BDT“ (Dimmaktor für Markenschalter - Phasenabschnitt). Die Bedienung des Dimmers funktioniert soweit schon per Home App. Allerdings wir der Status des Dimmers in der Home App nicht korrekt angezeigt. Um das zu verdeutlichen hier mal ein Szenario:
* Homebridge ist gestoppt
* ich schalte den Dimmer mit einem Wert von 25% per Taster ein
* ich starte Homebridge im Debug Modus
* der Status wird korrekt ausgelesen (log: RPC getValue (0008D709ABFF36:4 LEVEL) Response 0.25 Errors: null)
* ich starte die home App auf dem iPad. Der Status wird mit 25% korrekt angezeigt. Soweit gut!
* nun ändere ich den Wert z.b per Home App auf 20%. Die Lampe wird auf 20% gedämmt und im log erscheinen entsprechende Meldungen:

RPC event for HmIP-RF.0008D709ABFF36:4 LEVEL with value 0.2 [1/2/2018, 8:08:46 PM] 
[HomeMatic CCU2] Accessory Licht Wohnzimmer found -> Send Event [1/2/2018, 8:08:46 PM] [HomeMatic CCU2] Skip update because of working flag (true) or IsNull(20)

* Nun kommt der Fehler:
* ich schließe die Home App und öffne sie wieder. Danach wird wieder der Initialwert 25% angezeigt.
* nun kann ich z.b per Home App auch das Licht komplett ausschalten. Das Licht schaltet aus. Öffne ich die App erneut, wird wieder 25% und die Lampe als „an“ angezeigt.

Ich glaube das Problem ist, dass der Status des Dimmers nur beim Start der Homebridge an Homekit durchgereicht wird. Denn egal was ich danach mit dem Dimmer tue, erscheint im log immer folgende Zeile:

Skip update because of working flag (true) or IsNull(20)

Denke also nicht, dass der Homematic Ip Dimmer das Problem ist, sondern dass hier das Workingflag irgendwie nicht korrekt gesetzt/ausgewertet wird.
Leider bin ich nicht fit genug um das selbständig anzupassen. Aber ich denke ich bin auf der richtigen Spur ...

LG

**Comment by alexduerl** [comment]
So, habe jetzt mal in der "HomeKitGenericService.js" den Parameter "ignoreWorking" auf "true" gesetzt. Dann wird der Status des Dimmers immer korrekt angezeigt und aktualisiert.
Das bestätigt schon Mal meine Annahme, dass in der "HomeMaticHomeKitDimmerService.js" noch irgendwie das "WorkingFlag" anders gesetzt werden muss ... 
Ich versuche das mal zu debuggen ...

**Comment by thkl** [comment]
Bitte nicht in der Generic Klasse ... das würde sich auf alle Geräte auswirken. Das sollte in der jeweilig abgeleiteten Klasse gemacht werden. 

Working wird verwendet um Daten nur zu HomeKit zu sende , damit länger laufende Gerätezustandsänderungen (Dimmer / Blinds) nicht permanent Änderungsrequests an HomeKit sendet. 

Es gibt Eventcall (endWorking) der aufgerufen wird, wenn working durch die CCU wieder auf False gesetzt wird. Dieser Call könnte zum Update der HomeKitdatwn benutzt werden. Zb mache ich das in HomeMaticHomeKitBlindServiceIP

**Comment by alexduerl** [comment]
Hallo,
Ja, das war mir schon klar. Habe ich auch direkt wieder rückgängig gemacht. War für mich nur der Weg mich dem Ganzen mal langsam zu nähern. Bin grade erst seit kurzen dabei Homematic Komponenten und die homebridge zu nutzen. Finde das ein geniales Projekt und super was hier auf die Beine gestellt wurde .... aber das mit dem Dimmerstatus hat mich gefuchst, da der Dimmer mein erstes Homematic Gerät war ... und deshalb hab ich mal versucht mich da mal reinzudenken ...

**Comment by alexduerl** [comment]
Hallo,
ein 

this.usecache = false; 

in der HomeKitHomeMaticDimmerService.js

führt auch zum gewünschten Ergebnis. Die Werte werden dann im HomeKit immer korrekt angezeigt.

**Comment by padman74** [comment]
Ich habe dasselbe Problem, kann aber keine Besserung mit dem ausgeschaltetem Cache feststellen. Beim  Dimmer HM-LC-Dim1TPBU-FM tritt dieses Problem nicht auf.

**Comment by alexduerl** [comment]
Bei mir wird der Status des Dimmers seit dem Ausschalten des Caches immer korrekt angezeigt.

Das Problem ist, dass der Status meines Erachtens nur einmal beim starten des homebridge Services abgefragt und danach nicht mehr aktualisiert, also gecached  wird.

Das Ausschalten des Caches ist sicherlich nicht die saubere Lösung, ich persönlich bin damit aber jetzt erstmal zufrieden, da es für mich damit korrekt arbeitet.

**Comment by padman74** [comment]
Hi Alex,  wahrscheinlich an der Falschen. Wo muss das Kommando stehen?
Danke schon einmal im Voraus.

**Comment by padman74** [comment]
Update. Ich habe festgestellt, dass bei meinen IP Dimmern die Event-Methoden nicht durchlaufen werden. Kann es sein, dass die CCU keine Events sendet wenn der Dimmer manuell geschaltet wird?

**Comment by padman74** [comment]
Update. Hab den Schalter enable_hmip in der config.json vergessen. Sorry. Läuft jetzt.

**Comment by CyberChris79** [comment]
Hallo Leute,

leider habe ich das bei mir auch erst jetzt fest gestellt, das der ein/aus Status bzw. Dimm Status in der App nicht aktualisiert wird. Ich kann die Deckenlampe manuell schalten oder per App. Wenn ich sie per app schalte wird der Status sofort aktualisiert, sobald ich die Lampe manuell schalte, geht diese zwar an, jedoch sehe ich noch den alten aus Zustand inder App. Dies passiert nur bei der HmIP-BDT. Ich habe das mit den HmIP-BSM getestet und da ist alles so wie es sein soll.
enable_hmip ist bei mir auf true, sowohl auch local_ip=ip der Homebridge und ios10=true

Vielen Dank im Voraus.
Christian
