### ISSUE TITLE
Division by 10 for sensor value?

### ISSUE THREAD

**Issue by jhk3** [thkl/homebridge-homematic#195]
Hi,

Thank you for homebridge-homematic. In homekit apps (Eve, Home), my HmIP SMI reports an illumination that is only 1/10th of the value reported in the CCU2 (raspberrymatic). If I change line 34 of  homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorServiceIP.js, which is callback(null,value/10), removing the division by 10, homekit displays the correct illumination in lux. Why the division by 10 then? A bug?

Regards,

    Jörg

**Comment by pbksol** [comment]
There is no real conversion possible between HM values which range from 0 to 255 and a Lux value. Some HM sensors have significant differences in how they report these values.

![hmbrightness](https://user-images.githubusercontent.com/8238713/34738235-b1e84b5e-f578-11e7-93c8-a1dd665b1f7b.png)

There are some examples. It's the same for the "-2" sensors.

**Comment by jhk3** [comment]
It is just that I find the values reported by the CCU2 (58 or 0-1 Lux, depending on whether I switch light on or not) more consistent with the value reported by a Philips Hue motion/light/temperature sensor in the neighbour room (similar values for light vs. light off, with value reported the same in all Apps, Eve, Apple Home, Philips Hue). The values I get through the Eve and Apple home apps via Homebridge are between 0.0 - 0.6 Lux which is only about 1/10th. I am convinced that the division by 10 cannot be correct for HmIP-SMI.

**Comment by pbksol** [comment]
Uuups… HmIP-SMI… That's the device that is only reporting illumination if a motion was detected. And they do report values in Lux. This device behaves (to my knowledge) completely different and reports Lux (like the non IP HM-Sen-LI-O) but other devices do not.

I think thkl will jump in here – I'm not sure if it's possible to handle these special devices without leaving the "keep it as generic as possible" idea behind this plugin.

**Comment by thkl** [comment]
It is possible to generate a special service class for this device. But i need some help with this cause I do not own that device.

**Comment by jhk3** [comment]
I would help to the best of my ability. I have the HmIP-SMI  in my house administered by a raspberry running the latest CCU2 software, but I am not working in IT/software development and therefore my knowledge of programming is only very basic. Just let me know what you need.

Best regards, 

    Jörg

**Comment by jhk3** [comment]
Auf 

[https://homematic-forum.de/forum/viewtopic.php?t=32412](https://homematic-forum.de/forum/viewtopic.php?t=32412)

gibt es ein Script zum Auslesen der Datenpunkte Lichtstärke (in Lux) und Bewegung (true/false)  dieses Bewegungsmelders. Ich habe es bei mir getestet und es funktioniert:

var myChannel = dom.GetObject("HmIP-SMI 000XXXXXXXXXXX:1");
var dp = myChannel.DPByHssDP("ILLUMINATION");
WriteLine(dp.Value());

var myChannel = dom.GetObject("HmIP-SMI 000XXXXXXXXXXX:1");
var dp = myChannel.DPByHssDP("MOTION");
WriteLine(dp.Value());

Ausgabe bei mir:
44.6
false

**Comment by thkl** [comment]
Sind das jetzt Lux oder ist das ein "HomematicWirNennenEsLichtEinfallWert" ?

**Comment by jhk3** [comment]
Lux

**Comment by jhk3** [comment]
Mit der aktuellen Homematic Plugin Version 0.0.104 ist der Wert unmittelbar nach dem Start der Apple Home-App 1/10 des Lux Wertes, aber sobald der Bewegungssensor des HmIP-SMI einmal ausgelöst hat, stimmt der Lux Wert. Bei Beenden und Neustart von "Home" ist die Anzeige zurück auf 1/10 des tatsächlichen Lux Wertes, bis erneut durch Bewegung ausgelöst wird, dann stimmt es wieder (reproduzierbar).

**Comment by thkl** [comment]
ok kick die /10 mal raus

**Comment by jhk3** [comment]
keine Änderung im Verhalten mit "Home"
