### ISSUE TITLE
HAP Warning

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#196]
Mir ist letztens im log....

Jan 18 15:51:54 raspberrypi homebridge[511]: HAP Warning: Characteristic 00000079-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000007....

aufgefallen ..... hat das eine bedeutung ?

lg RIchard

**Comment by thkl** [comment]
irgend ein Gerät erzeugt eine Characteristic die nicht in der normalen Konfig drin ist. Ist nicht weiter schlimm
