### ISSUE TITLE
HmIP-BBL - [HomeMatic CCU2] There is no service

### ISSUE THREAD

**Issue by Hifclif** [thkl/homebridge-homematic#197]
Hallo Zusammen,
ich wollte die Aktoren einbinden und nun:
[HomeMatic CCU2] There is no service for HmIP-BBL:BLIND_VIRTUAL_RECEIVER
Werden die nicht unterstützt oder liegt der Fehler noch bei einem meiner Settings?
Schöne Grüße

**Comment by Hifclif** [comment]
Alle auf Urlaub?

**Comment by thkl** [comment]
Was ist das denn für ein Gerät ?

**Comment by Hifclif** [comment]
Hi, das ist ein HmIP-BBL (Jalousienaktor) https://www.elv.at/homematic-ip-jalousieaktor-fuer-markenschalter.html

**Comment by Hifclif** [comment]
Hat niemand Jalousien?

**Comment by jhk3** [comment]
Habe auch zwei solche HmIP-BBL, selbe Fehlermeldung. Sollten im Prinzip so funktionieren wie HmIP-BROLL, aber es gibt zusätzlich noch die Einstellung für die Lamellen-Position.

**Comment by Hifclif** [comment]
Ja wäre schön wenn das integriert würde.

**Comment by grinselwald** [comment]
Fände ich auch!

**Comment by jhk3** [comment]
Wenn man in die config.json die Zeilen

"enable_hmip":"true",
      "services": [
        { "type": "HmIP-BBL:BLIND_VIRTUAL_RECEIVER",
         "service": "HomeMaticHomeKitBlindServiceIP"
        }]
einträgt, dann erscheinen die entsprechenden Knöpfe in der Home-App auf dem iOS Device (vorausgesetzt man hat die Jalousien auch im HomeMatic WebUI im Gewerk für die Homebridge verfügbar gemacht).
Damit lassen sich die Jalousien hoch und runterfahren, allerdings kann man keine Einstellung des Lamellenwinkels vornehmen. Beides erfolgt in der HomeMatic WebUI unter Status und Bedienung Geräte über den Kanal 4 des HmIP-BBL.

**Comment by Hifclif** [comment]
Hey cool, das geht. Problem das ich habe ist das sie immer nur auf 96% öffnet. Also sie fährt hoch und dann wieder ein wenig runter. Aber die Fuktion geht schon mal! TOP von dir

**Comment by jhk3** [comment]
Evtl. gibt die Liste der BBL-Kanäle und Einstellung noch Informationen, wie man die Lamellen im Neigungswinkel per homebridge/homekit ändern kann:

![bbl-kanale](https://user-images.githubusercontent.com/35252324/36946434-55279130-1fbd-11e8-9582-6b18cb193066.jpg)

**Comment by Hifclif** [comment]
Guten Morgen, was ich noch festgestellt habe ist das nach einigen Stunden kein Status mehr zurückgegeben wird und die CCU extrem Langsam geworden ist. Heißt alles ist 3-4 Sekunden verzögert und kein Status der Geräte kommen mehr (zb Fensterkontakte, Rollopositionen) . Werde die Konfig zum test mal zurückstellen. sg

**Comment by jhk3** [comment]
Das Problem mit der Statusrückgabe zeigen meine Jalousien bislang nicht. Der Status wird auch korrekt in „Home“ aktualisiert, wenn ich die App „@Home“ (für Homematic ohne Homekit) benutze. Ich hatte aber gestern die Ordner persist und accessoires sowie ccu.json gelöscht und alles neu aufgesetzt, da ich von den Ordnern keine Backups gemacht hatte.
Die beiden Jalousien, die ich an Homekit angebunden habe, fahren über Homekit nur im Bereich zwischen 5 und 95 % offen, wobei die Lamellenwinkel anschließend völlig willkürlich eingestellt sind. Sauber ist die bisherige Anbindung keinesfalls.

**Comment by jhk3** [comment]
Für mich sieht es so aus als gäbe es in Homekit gar keinen Support für Jalousien / Blinds / Shades, der neben der Höhe der Jalousien auch eine Veränderung der Lamellenwinkel zuließe ? Jedenfalls sind die Ergebnisse der Suchmaschinen ernüchternd.

**Comment by Stefan774** [comment]
Hallo zusammen,

einen Service gibt es meiner Meinung nach auf HomeKit-Seite. Das müsst der Service "Slat" sein und hier würde es dann auch die Möglichkeit geben den TiltAngel anzugeben.

/**
 * Service "Slat"
 */

Service.Slat = function(displayName, subtype) {
  Service.call(this, displayName, '000000B9-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.SlatType);
  this.addCharacteristic(Characteristic.CurrentSlatState);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Name);
  this.addOptionalCharacteristic(Characteristic.CurrentTiltAngle);
  this.addOptionalCharacteristic(Characteristic.TargetTiltAngle);
  this.addOptionalCharacteristic(Characteristic.SwingMode);
};

**Comment by thkl** [comment]
Ok, ich hab die Dinger nicht also bin ich bissel auf Input angewiesen:

Das ist in erster Linie ein normaler Rollo Aktor nur das er noch einen zusätzlichen Datenpunkt für die Jalousieverstellung hat ... Also müsste ich den normalen HomeMaticHomeKitBlindServiceIP Service nur noch mit dem Slat Service erweitern. Der Channel wo die Daten ausgetauscht werden ist dann sicher Kanal 4 ... Datenpunkt LEVEL ist für die Einstellung der Jalousie zuständig. Aber welcher Datenpunkt ist die Lamellen ? Laut Doku gibt es da nur einen LEVEL_2 ... ist der das ?

**Comment by Hifclif** [comment]
![grafik](https://user-images.githubusercontent.com/35782387/36989754-ee97f8f6-20a2-11e8-85df-84ad2a99bcae.png)

**Comment by jhk3** [comment]
LEVEL_2: ja, sieht so aus als ist es das. Ich habe mal die Suchmaschine angeworfen und das hier gefunden: 

[https://homematic-forum.de/forum/viewtopic.php?t=38094](url)

Wenn ich das Script dieser Seite als Testscript im WEBUI teste, dann scheint es zu stimmen (bin Script-Anfänger):

var o=dom.GetObject("HmIP-RF.00135709960C68:4.LEVEL_2");
  WriteLine(o.Value());
  o.State(0.8);

liefert in der WebUI tatsächlich die Position 80% (0.8), unter Status und Bedienung, Geräte.

**Comment by jhk3** [comment]
LEVEL_2: ja, sieht so aus als ist es das. Ich habe mal die Suchmaschine angeworfen und das hier gefunden: 

[https://homematic-forum.de/forum/viewtopic.php?t=38094](https://homematic-forum.de/forum/viewtopic.php?t=38094))

Wenn ich das Script dieser Seite als Testscript im WEBUI teste, dann scheint es zu stimmen (bin Script-Anfänger):

var o=dom.GetObject("HmIP-RF.00135709960C68:4.LEVEL_2");
  WriteLine(o.Value());
  o.State(0.8);

liefert in der WebUI tatsächlich die Position 80% (0.8) .

**Comment by thkl** [comment]
Letzte Frage .. die Lamellenposition geht von bis ? .. HomeKit kennt von -90° bis +90° ...

**Comment by thkl** [comment]
könnte mit https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitBlindSlatServiceIP.js funktionieren

Ich kann es nur nicht testen

**Comment by jhk3** [comment]
ich probiere es aus ...

**Comment by thkl** [comment]
oops und jetzt

**Comment by Hifclif** [comment]
habs gefunden. teste mal rum

**Comment by jhk3** [comment]
Der Status der Jalousien wird in der „Home“ App korrekt angezeigt (auch dann, wenn man „@Home“ zum Einstellen nimmt, was ohne Homekit ansteuert). Es klappt auch, per kurzer Berührung der Schaltflächen in der Apple Home-App die Jalousien vollständig hoch oder runter zu fahren. Inkonsistent ist bei mir nur die Reaktion auf eine Höheneinstellung, die in Apples „Home“ angezeigt wird, wenn man die Knöpfe länger berührt.

**Comment by Hifclif** [comment]
Bei mir ist das Problem das die Aktoren angezeigt werden aber keine reaktion wenn ich sie betätige. Stelle ich zurück kann ich öffnen und schließen. Es kommt am Aktor aber schon nichts an.

**Comment by thkl** [comment]
Kopier Dir mal bitte https://raw.githubusercontent.com/thkl/homebridge-homematic/master/ChannelServices/HomeMaticHomeKitBlindSlatServiceIP.js nach ./homebridge und ändere den Servicetyp in der config auf 

```
"services": [{
"type": "HmIP-BBL:BLIND_VIRTUAL_RECEIVER",
"service": "HomeMaticHomeKitBlindSlatServiceIP"
}]
```

Dann sollten auch die Lamellen funktionieren ... 
Ich kanns nicht testen ...

**Comment by thkl** [comment]
@Hifclif .. zeigt nach oben ...

**Comment by thkl** [comment]
sollte in der aktuellen version gehen wenn nicht bitte neuen issue aufmachen
