### ISSUE TITLE
Support for Eve fake History (fakegato)

### ISSUE THREAD

**Issue by to0b** [thkl/homebridge-homematic#198]
Is it possible to implement the fakegato history service? (https://github.com/simont77/fakegato-history)

**Comment by thkl** [comment]
this looks not like a homematic device so it will not make it into this plugin ...

**Comment by thkl** [comment]
Uhh I totally misinterpreted that thing. 
Working on that to implement.

**Comment by to0b** [comment]
Thank you!

**Comment by thkl** [comment]
Seems to work ...

![Image](https://i.imgur.com/7uKCNO6.jpg)

**Comment by Samfox2** [comment]
Cool

**Comment by thkl** [comment]
Thank you.  There is still some stuff to do before i am able to release that version. 

Currently supported are thermostats, virtual heating groups, and motion sensors ...

Eve is able to show power measurement devices also. I’ve implemented the service also on them but it didn’t work so far.  🤔🙈

**Comment by Samfox2** [comment]
Doors and windows should also work, they have a characteristic that counts „times opened“

**Comment by thkl** [comment]
yeah but one step after another ... :)

**Comment by Samfox2** [comment]
Does history log for thermostats (HM-CC-RT-DN) already work? Your last commit shows only an empty graph and no messurements.

**Comment by thkl** [comment]
Due the fact that i have no access to these old thermostates i was not able to implement the history. If you are able to add this, please do ...

**Comment by Samfox2** [comment]
No prob, I see what I can do.

**Comment by Samfox2** [comment]
Ok, I think the problem is in function `HomeMaticHomeKitThermalControlService.prototype.queryData`.
Logging is done in the humidity request. If the device has no humidity sensor nothing is logged.

**Comment by thkl** [comment]
Ahh ok that’s a good point 😜. Ich will change that soon.

**Comment by thkl** [comment]
should work with https://github.com/thkl/homebridge-homematic/commit/8fff1e9916ed9276ec427d7061a423b8eeac7cf5

**Comment by Samfox2** [comment]
Works 👍

**Comment by thkl** [comment]
Nice ... so i will close this

**Comment by JensBonse** [comment]
@thkl Hallo Thomas, ich habe die .104 installiert und habe bemerkt, dass die History Einträge irgendwie nicht permanent gesichert werden. Kann es sein, wenn man es als Service laufen lässt und nicht als User pi mit homebridge -D das dann die History nicht geschrieben werden kann? Hatte es heute um 15h mit Homebridge -D kurz laufen. Danach dann als Service und um 18h sah ich dann in der History, dass seit 3h keine Daten mehr geschrieben worden sind.
Dann habe ich es um 18h nochmal als User pi mit homebridge -D laufen lassen und dann kam direkt ein Wert hinzu. Oder ist das ein OSI Layer 8 Problem?

**Comment by thkl** [comment]
die Einträge werden im .homebridge Verzeichnis gespeichert. Also da, wo auch die Config steht. Da braucht der User, unter dem homebridge liegt Schreibrechte.

**Comment by JensBonse** [comment]
Hmm die scheint er zu haben. Last Entry ist auf 50. Also sollte er generell 50 Eintrage aufgezeichnet haben. Komischerweise zeigt mir EVE das so nicht an. Ich werde das mal beobachten.

Könntest du noch einbauen, dass die RotaryHandle und wenn die als Window deklariert sind dann nicht auf 'Schließend' stehen, sondern auf 'Geschlossen' bzw. auf 'Geöffnet' stehen?
Erst wenn ich den Status eines Fensters ändere wird er korrekt in HomeKit dargestellt.

**Comment by thkl** [comment]
Also bei mir sind die Einträge seit ca 3 Wochen da. Und auch die nach dem Update heute auf latest. 
Gerade noch mal neu gestartet die Files (heißen hostname_seriennummer.json) haben ein aktuelles Datum+Zeit. Da wird also reingeschrieben. Das siehst Du auch in -D

Für den Fenstergriff bitte neuen Issue. Sonst komme ich durcheinander. 

Den habe ich aber soweit ich mich erinnere, vor ein paar Tagen gefixt.

**Comment by nicoh88** [comment]
@JensBonse 

Ich habe da eine Idee. Ich brauche noch ein paar Infos von dir. 😄 

1. Wenn du im Debug-Mode startest, startest du Homebridge als welcher User?
2. Wenn Homebridge normal läuft, läuft es unter welchen User? `service homebridge start`?

Ich denke, dass entweder der User, unter dem normalerweise, Homebridge läuft, entweder kein Homeverzeichnis hat, der Ordner `.homebridge` nicht existiert, es nicht ausreichend Berechtigungen gibt oder die User-Zeile in dem `homebridge.service` File fehlt. 

Wenn ich die Infos habe, baue ich dir ein paar Befehle, mit welchen wir deinem Problem auf den Grund gehen können. 👍 

[Ich hatte mal mit dem Xiaomi-Plugin ein ähnliches Problem](https://www.loggn.de/homebridge-xiaomi-mi-robot-vacuum-saugroboter-fehlermeldungen/).

**Comment by JensBonse** [comment]
Danke, hat sich komischerweise erledigt. Die 3 Stunden gestern hatte er nichts aufgezeichnet. Als ich dann heute Morgen geschaut habe, waren alle Daten da.

**Comment by box99h** [comment]
Ich musste meine Homebridge neu aufsetzen und habe nun das Problem, dass meine WDS100 die Temperatur und die Luftfeuchtigkeit nicht mehr aufzeichnet. 
Für alle anderen Sensoren (WDS40 und WDS10) werden die Daten aufgezeichnet. 

Vor der Neuinstallation hat aber auch die WDS 100 funktioniert. Wäre super, wenn mir jemand helfen könnte, da ich derzeit keine Idee habe wo der Fehler liegen könnte.
