### ISSUE TITLE
Keine Status Aktualisierung für HMW-Sen-SC-12-DR

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#199]
Hallo,

ich habe einen HMW-Sen-SC-12-DR und an diesem fest eingebaute Fensteröffnungskontakte.

Die Homematic und PocketControl erkennen den Status der Fenster und Türen korrekt und aktualisieren diesen auch. Die Homebridge allerdings nicht. Wenn ich Homebridge neu starte wird der korrekte Status übernommen, allerdings findet keine laufende Status Aktualisierung statt.

Ich habe den HMW-Sen-SC-12-DR auf folgende HomeMaticHomeKitWiredSensorService.js konfiguriert.

```
'use strict';

var HomeKitGenericService = require('./HomeKitGenericService.js').HomeKitGenericService;
var util = require("util");


function HomeMaticHomeKitWiredSensorService(log,platform, id ,name, type ,adress,special, cfg, Service, Characteristic) {
    HomeMaticHomeKitWiredSensorService.super_.apply(this, arguments);
}

util.inherits(HomeMaticHomeKitWiredSensorService, HomeKitGenericService);


HomeMaticHomeKitWiredSensorService.prototype.createDeviceService = function(Service, Characteristic) {

    var that = this;
    var sensor = new Service["ContactSensor"](this.name);
    var state = sensor.getCharacteristic(Characteristic.ContactSensorState)
	.on('get', function(callback) {
      that.query("SENSOR",function(value){
       if (callback) callback(null,value);
      });
    }.bind(this));

    that.currentStateCharacteristic["SENSOR"] = state;
    state.eventEnabled = true;
	
    this.services.push(sensor);
    this.remoteGetValue("SENSOR");

}


module.exports = HomeMaticHomeKitWiredSensorService;
```

**Comment by iuliusmaximilian** [comment]
Kann mich hier Jemand unterstützen ?

**Comment by iuliusmaximilian** [comment]
@thkl Kannst Du hierauf mal einen Blick werfen, ich komme selbst hier nicht weiter. Danke!

**Comment by thkl** [comment]
Die neue Core Version kann einzelne Events für Datenpunkte noch mal zum jeweiligen Homekit Service schicken.  Ich bau das hier mal noch ein ...

**Comment by iuliusmaximilian** [comment]
Problem still exists in 106.

**Comment by iuliusmaximilian** [comment]
`"enable_wired": true,`

ist des Rätsels Lösung - funktioniert! :-)

**Comment by thkl** [comment]
Ja, mit aktivem Interface werden auch alle Events übertragen \o/

**Comment by iuliusmaximilian** [comment]
Sehr sehr geil, nur nähere ich mich nun leider der magischen 100er Grenze \o/

**Comment by thkl** [comment]
https://github.com/thkl/homebridge-homematic/wiki/Anbindung-an-die-CCU

**Comment by nicoh88** [comment]
@iuliusmaximilian: Mach dir keine Sorgen wegen deiner 100 Geräte. 😉 

_**F:** Wieviele HomeMatic Geräte kann ich aufnehmen.
**A:** Hinter einer sog. Bridge in HomeKit können aktuell maximal 100 Geräte verwaltet werden. Das heisst maximal 100 Geräte (bei Geräten mit mehreren Kanälen zb 2fach Schaltaktoren natürlich dann entsprechend weniger) können verwendet werden._

Ich habe zwar keine 100 Geräte, aber auf einem RPi bereits 2 Homebridge's laufen. Da es die Last der Abfragen besser verteilt und ich eine Trennung zwischen LAN-Geräten und WAN-Geräten habe. Somit reißt es nicht das gesamte HomeKit in den Abgrund, wenn das Internet mal nicht funktioniert oder ein Clouddienst aktuell überlastet ist.

Rein theoretisch, richtest du mit den 101sten Gerät dann einfach eine zweite Homebridge ein und ein neues Gewerk "HomeKit2" und fügst diese zusätzliche dann einfach hinzu. 👍 

Gruß

**Comment by iuliusmaximilian** [comment]
@nicoh88 Danke!
