### ISSUE TITLE
Support for HM-IP Taster WRC2

### ISSUE THREAD

**Issue by martinB65** [thkl/homebridge-homematic#200]
Hallo,
HM-IP Taster werden offenbar nicht unterstützt. Dem Taster den "normalen" KeyService zuzuweisen bringt leider nichts bzw. ergibt beim Tastendruck folgendes Resultat.

`[2018-2-2 16:52:34] [HomeMatic CCU2] RPC event for HmIP-RF.00019709AC85B7:0 UNREACH with value false
[2018-2-2 16:52:34] [HomeMatic CCU2] RPC event for HmIP-RF.00019709AC85B7:0 RSSI_DEVICE with value -49
`

Danke für Unterstützung.

**Comment by thkl** [comment]
Moin, wie heisst das Geräte als Typenbezeichnung HmIP-..... ?

**Comment by martinB65** [comment]
Hallo,
das Gerät heißt HMIP-WRC2.

Gruß
Martin Binder

**Comment by mach1009** [comment]
Kannst du kurz erklären, was du damit erreichen möchtest?
Meiner Meinung nach macht es ja keinen Sinn einen Taster per HomeKit zu bedienen. Geht ja auch über Homematic nicht. Ein Taster hat ja nichts, was sich auslösen lässt. 

Grüße

**Comment by martinB65** [comment]
Aber ein Taster löst etwas aus.... darum geht es mir. 
In Homematic geht das selbstverständlich und auch in HomeKit mit den „alten“ (nicht HMIP-) Tastern. In HomeKit brauche ich das, um damit Aktoren zu schalten, die es nicht in Homematic gibt (z.B. Fritzbox DECT200 Schaltsteckdosen), oder eine HomeKit-Szene zu schalten.

Ich könnte mir natürlich auch irgendwelche Taster kaufen, die schon HomeKit enabled sind, aber ich möchte keinen Wildwuchs und daher soviel wie möglich mit Homematic-Komponenten umsetzen.

Schönen Gruß

**Comment by mach1009** [comment]
Ah verstehe. Das macht Sinn
Grüße

**Comment by fabiancamps** [comment]
Es gibt auch noch einen anderen Wandtaster, den HM-PB-2-WM55:
http://www.eq-3.de/produkte/homematic/licht/hm-pb-2-wm55.html

Sollte eigentlich fast gleich sein, support für beide Tasten wäre super um genau wie angebeben, außerhalb der Homematic Zentrale andere geräte ansteuren zu können.

**Comment by martinB65** [comment]
Hallo fabiancamps, die Taster aus der "normalen" (ohne IP) HM-Reihe (ich habe: HM-PB-2-WM55-2)  funktionieren bei mir auch mit homebridge-homematic. Es wird allerdings nur der einfache Tastendruck gesendet (Doppelklick und langer Tastendruck sind nicht unterstützt, obwohl man in der Home-App alle Ereignisse zuweisen kann).

**Comment by thkl** [comment]
@martinB65  leider finde ich keine Doku bei EQ3 dazu. Kannst Du den Taster mal bitte ins Homekit Gewerk aufnehmen und Homebridge neu starten. Dann sollte eine Warnung kommen There is no service for : .....  diese Zeile brauch ich mal ... da steht der Channelname drin.

**Comment by martinB65** [comment]
[HomeMatic CCU2] There is no service for HMIP-WRC2:KEY_TRANSCEIVER

**Comment by fstehle** [comment]
Hey @martinB65, 

habe in PR https://github.com/thkl/homebridge-homematic/pull/340 HMIP-WRC2 Support eingebaut, da ich genau vor dem gleichen Problem stehe.

In der Zwischenzeit kann aber auch ganz einfach Support dafür aktivieren, in dem man die Config wie folgt erweitert:

```
{
  ...
  "platforms" : [
    {
      "platform": "HomeMatic",
      "name": "HomeMatic CCU",
      ...
      "services": [
        { "type": "KEY_TRANSCEIVER",
          "service": "HomeMaticHomeKitKeyService"
        }]
    }
  ]
}
```

**Comment by snookerap** [comment]
@thkl erstmal vielen Dank für das super Plugin!!!

In Homekit ist der Taster drin, aber ich bekomme damit keine Homekit-Geräte geschaltet.

**Comment by lobocobra** [comment]
I have the same problem, the switch does not work with homematic.
=> Can anyone guide me, how to make it work? Above it seems that there is a way , but I do not understand what to do where
