### ISSUE TITLE
Unterstützung für HmIP-BWTH (Feature Request)

### ISSUE THREAD

**Issue by Stefan774** [thkl/homebridge-homematic#203]
Hallo zusammen,

wäre es möglich den Wandthermostat mit Schaltausgang HmIP-BWTH mit zu unterstützen?
Wäre es vielleicht schon ausreichend wenn man in der channel_config.json den Aktor mit aufnimmt wie folgt?
<code>
"services": [
	{ "type": "HmIP-BWTH",
          "service": "HomeMaticHomeKitThermostatService"
	}]
</code>
Bin leider noch nicht ganz so tief In der Thematik drin und meine Wandthermostate kommen auch erst in KW11 an. Aber HomeKit wäre halt echt klasse ;) 

Grüße

**Comment by dkrizic** [comment]
Ich habe hier 8 HmIP-BWTH im Einsatz und sie funktionieren prächtig auch bereits mit der aktuellen Version.

**Comment by Stefan774** [comment]
Ah ok danke. 

Dann scheine ich die channel_config.json bzw. das Plug-In noch nicht richtig zu verstehen. Ich finden nämlich nirgens eine Referenz auf den Aktor. Hattest du etwas anpassen müssen oder wurden die Aktoren einfach direkt unterstützt?

Ich schließe dann mal den "Issue" wäre aber super wenn mir jemand einen Tipp geben könnte warum der Aktor funktioniert wenn er nirgends (also innerhalb der channel_config.json) definiert wurde.
