### ISSUE TITLE
Systemvariable als Gerät bereitstellen (Garagentor, Alarmsystem)

### ISSUE THREAD

**Issue by mach1009** [thkl/homebridge-homematic#204]
Ich habe mir über die CCU eine Alarmanlage realisiert. Da ich diese auch gerne in Homekit sehen und bedienen wollte, habe ich mir mit der XML-Api und diesem Plugin beholfen: [https://github.com/codetwice/homebridge-http-securitysystem](url)
Dazu habe ich die Systemvariable (die ich eh brauchte) gleich so angelegt, dass sie gleich zu dem Plugin passt. Praktisch handelt es sich hier um eine Kombination von Sensor und Aktor, die ein Gerät im Homekit abbilden. 

Neben Alarmanlage wäre das auch ein Anwendungsfall für elektrische Fenster und Garagentore. Ich könnte mir vorstellen, dass man in der Config bspw. GarageDoor definiert und eine Systemvariable zuweist. Diese muss dann die Status des Services abbilden. Alles andere macht ein Programm in der CCU. Damit ist man völlig losgelöst von definierten Sensoren oder Aktoren.

Wäre das nicht auch direkt im Homematic Plugin denkbar?

**Comment by thkl** [comment]
https://github.com/thkl/homebridge-homematic#variables

**Comment by mach1009** [comment]
Ja, soweit bin ich auch schon gekommen. 
Es geht darum eine Variable als Gerät zu deklarieren. Auch mit einer Werteliste und nicht nur true und false.

Habe mir das oben genannte Plugin kopiert und soweit als Garagentor angepasst. Fange jetzt an das mit meinen Variablen in der CCU über die XML API zu testen. 

Aus Sicht Homematic wäre es cool, wenn man sich den Weg über die XML API sparen könnte. Dann kann man sich Polling sparen. 

Meinst du es wäre denkbar das über das Homematic-Plugin zu realisieren?

**Comment by mach1009** [comment]
Ich habe mein Garagentor nun so umgesetzt und ein kleines HowTo geschrieben:
[Homebridge-http-garagedoor](https://github.com/mach1009/homebridge-http-garagedoor/wiki/How-to-setup-a-garage-door-opener-in-Homekit-with-Homematic-CCU2-or-RaspberryMatic)
