### ISSUE TITLE
HmIP-FDT

### ISSUE THREAD

**Issue by Hifclif** [thkl/homebridge-homematic#205]
Hallo Zusammen, wird der Aktor (Dimmer) aus der IP Linie unterstützt?
Schöne Grüße

**Comment by thkl** [comment]
Aktuell nicht, da ich das Ding noch nicht kenne. Ist das ein "normaler" Dimmer ?

**Comment by Hifclif** [comment]
Hi, ist ein normaler Unterputz dimmer.

**Comment by thkl** [comment]
den hier muss ich mal "on Hold" stellen denn in der EQ3 Doku http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf ist noch keine Info dazu

**Comment by krobipd** [comment]
Dieser Unterputz Dimmer sollte ja an sich das selbe Tun wie der Dimm-Schalter (HmIP-BDT).

http://www.eq-3.de/produkte/homematic-ip/homematic-ip-dimmaktor-unterputz-phasenabschnitt.html

http://www.eq-3.de/produkte/homematic-ip/homematic-ip-dimmaktor-fuer-markenschalter.html#bestell_info
