### ISSUE TITLE
HomeMaticHomeKitBlindService - Level für geschlossen einstellen

### ISSUE THREAD

**Issue by rhammeran** [thkl/homebridge-homematic#208]
Hallo,

ich schließe meine Rollos abends nicht ganz, damit bei geöffnetem Fenster noch ein bisschen Luft rein kommt. Im Homekit werden diese Rollos dann aber immer noch als geöffnet angezeigt. Kann man das irgendwo einbauen, dass z.B. 20% geöffnet noch als geschlossen interpretiert werden?

mfg

Ralf

**Comment by thkl** [comment]
Es soll also, wenn Du Siri sagst „schließe die Jalousie“ diese zb nur auf 10% fahren ?

Würde gehen, das Problem ist aber dann: die Jalousien gehen dann *immer* nur noch auf 10% egal was du machst.

Vielleicht ist der Ansatz hier über ein CCU Programm, in welchem Du die Jalousien auf den gewünschten Wert fahren lässt, besser. 
Dieses kannst Du auch aus HomeKit steuern. Und über eine HomeKit Szene kann dann auch Siri das Programm triggern.

**Comment by thkl** [comment]
Oh ich sehe gerade, ich hab das Thema verfehlt. 

Also Du willst das <20% für HomeKit als geschlossen zählt.  Würde gehen, wenn gilt das aber für alle Jalousie Aktoren, die Du in HomeKit hast.

**Comment by rhammeran** [comment]
Genau "<20%" soll für HomeKit als geschlossen zählen. Das wäre auch ok, wenn das für alle Aktoren einheitlich gelten würde.

**Comment by thkl** [comment]
Ok ich werde das so nicht einbauen, denn das gilt dann für alle User. 

Aber Du kannst bei Dir ja das Servicefile für die Rollos ändern.  Ich such das mal raus ....

**Comment by rhammeran** [comment]
oh ja, wäre super ... in Anpassung des Files bekomme ich dann schon hin.

**Comment by thkl** [comment]
mit https://github.com/thkl/homebridge-homematic/commit/87b2ed9fa5cf34f0474ad5991d1ecfd7ce835c43  sollte das jetzt funktionieren.

Es muss in der config.json eine Einstellung für das minimale und/oder maximale Level angegeben werden , welche als zu oder offen interpretiert werden.

Hier als Beispiel werden alle BROLL Devices so eingestellt, das < 20% als ZU und > 80% als offen gelten.
```
"HmIP-BROLL:SHUTTER_VIRTUAL_RECEIVER": {
		"minValueForClose" : 20,
		"maxValueForOpen" : 80
	    }
```

**Comment by rhammeran** [comment]
Vielen Dank für die Änderung!

Wenn  ich die Werte direkt in der "HomeMaticHomeKitBlindService.js" eintrage, dann funktioniert es wie beschrieben. Ich habe es allerdings nicht geschafft, die Wert so in der config.json aufzunehmen, dass sie auch angenommen werden - meine Aktoren sind allerdings alle BidCos, nicht HmIP.

btw.  bei

`  if (this.maxValueForOpen > 0) {
      this.log.info("there is a custom open level of %s",this.maxValueForOpen)
  }`

​müsste es  m.E. < 100​ lauten

**Comment by iuliusmaximilian** [comment]
Ich habe das mal für den HM-LC-Bl1PBU-FM ausprobiert, funktioniert aber nicht, was mache ich falsch?

                "special": [{
                        "HM-LC-Bl1PBU-FM:LEVEL": {
                                "minValueForClose" : 5,
                                "maxValueForOpen" : 95
                                }
                }],
                "services": []

**Comment by legerp** [comment]
das hat bei mir für HmIP-FROLL funktioniert. unter plattforms eintragen

            "special": [
                {
                    "HmIP-FROLL:SHUTTER_VIRTUAL_RECEIVER": {
                        "minValueForClose": 20,
                        "maxValueForOpen": 90
                    }
                }
            ],
