### ISSUE TITLE
Nach update auf 0.0.27 werden keine Geräte mehr angezeigt..

### ISSUE THREAD

**Issue by Dieter52** [thkl/homebridge-homematic#21]
Hallo,
nach dem Update wird die Homematic Homebridge zwar am iPhone gefunden, aber es sind keine Geräte mehr vorhanden.
Ich habe verschiedene Sachen versucht:
 - Neustart homebridge 
- löschen der HomeKit im iPhone
- HomeKit neu Initialisiert

Er findet die Homebridge, lädt sie aber es befinden sich keine Geräte mehr in der Anzeige.

Hier noch ein paar Infos:
Loaded plugin: homebridge-homematic
Registering platform 'homebridge-homematic.HomeMatic'
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
[HomeMatic CCU] Initializing HomeMatic platform...
[HomeMatic CCU] Homematic Plugin Version 0.0.27
[HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[HomeMatic CCU] init RPC
[HomeMatic CCU] Local IP: 192.168.178.38
[HomeMatic CCU] XML-RPC server for interface BidCos-RF.is listening on port 9090
[HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[HomeMatic CCU] CCU RPC Init Call on port 2001 for interface BidCos-RF.
[HomeMatic CCU] Fetching Homematic devices...
[HomeMatic CCU] Method call params for 'system.listMethods': homebridge
[HomeMatic CCU] Initializing platform accessory 'Bad Licht'...
[HomeMatic CCU] Initializing platform accessory 'Fenstersensor Küche'...
[HomeMatic CCU] Initializing platform accessory 'Gästeraum Lichtschalter'...
[HomeMatic CCU] Initializing platform accessory 'Heizung an aus'...
[HomeMatic CCU] Initializing platform accessory 'Heizung Gaestezimmer'...
[HomeMatic CCU] Initializing platform accessory 'Heizung Schlafzimmer'...
[HomeMatic CCU] Initializing platform accessory 'Heizung Wohnzimmer'...
[HomeMatic CCU] Initializing platform accessory 'Heizung Bad'...
[HomeMatic CCU] Initializing platform accessory 'HeizungenEsszimmer'...
[HomeMatic CCU] Initializing platform accessory 'Heizungssteuerung:2'...
[HomeMatic CCU] Initializing platform accessory 'Kueche Lichtschalter'...
[HomeMatic CCU] Initializing platform accessory 'Lischtschalter Flur'...
[HomeMatic CCU] Initializing platform accessory 'Schlafzimmer Ein Aus'...
[HomeMatic CCU] Initializing platform accessory 'Schlafzimmerlichtschalter'...
[HomeMatic CCU] Initializing platform accessory 'HM-Sec-SCo MEQ0724093:1'...
[HomeMatic CCU] Initializing platform accessory 'SensorOptisch_1'...
[HomeMatic CCU] Initializing platform accessory 'SensorOptisch_2'...
[HomeMatic CCU] Initializing platform accessory 'Temperaturfühler Aussen'...
[HomeMatic CCU] Initializing platform accessory 'Wohnzimmer Lichtschalter'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Homebridge is running on port 51826.
[HomeMatic CCU] NPM 0.0.27 vs Local 0.0.27

und die config.json:

{
	"bridge": {
		"name": "Homebridge",
		"username": "C9:26:3D:E3:CF:A8",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"platforms": [{
		"platform": "HomeMatic",
		"name": "HomeMatic CCU",
		"ccu_ip": "192.168.178.26",
		"filter_device": [],
		"filter_channel": [],
		"outlets": [],
		"doors": [],
		"programs": [],
		"subsection": "AppleHome"

	}]
}

Vielleicht weis ja jemand woran das liegen kann ....

Gruss
Dieter

**Comment by thkl** [comment]
Ich befürchte hier hilft nur ein Reset der HomeKit Konfiguration im IOS unter Datenschutz/HomeKit

**Comment by Dieter52** [comment]
Das Problem war nicht homebridge-homematic sondern homegridge selber.
nach npm -g install homebridge läuft nun alles wieder.

Danke für die Hilfe...
