### ISSUE TITLE
Support HM-CC-SCD (Luftgütesensor / CO2)

### ISSUE THREAD

**Issue by nicoh88** [thkl/homebridge-homematic#210]
- Characteristic.AirQuality
- Characteristic.CarbonDioxideDetected
- Characteristic.CurrentTemperature

[Beispiel im Netatmo-Plugin](https://github.com/planetk/homebridge-netatmo/tree/master/service).

![85976_f01_gesensor](https://user-images.githubusercontent.com/264264/37026982-5743567e-2130-11e8-958e-a6149de446d1.jpg)

**Comment by thkl** [comment]
Wenn ich mir das Config File anschaue, dann liefert das Gerät nur einen State : 0,1,2 -> ["LEVEL_NORMAL", "LEVEL_ADDED", "LEVEL_ADDED_STRONG"]

Damit kann ich nur Characteristic.CarbonDioxideDetected füllen ....

**Comment by thkl** [comment]
siehe https://github.com/thkl/homebridge-homematic/commit/6c07e09b78a6663a67af680d70dfda22bc15211c  da ist jetzt auch schon der Eve History Kram für Thermostate und IRDs drin

**Comment by nicoh88** [comment]
@thkl Ok, danke! 👍 

Der "**Characteristic.CarbonDioxideDetected**" ist dann wie ein Bewegungsmelder dargestellt und zeigt auch die **PPM** an? 
![img_8458](https://user-images.githubusercontent.com/264264/37060914-072ff770-2192-11e8-8c58-ddf9f0fef293.PNG)

Es wäre perfekt, wenn du auch noch zusätzlich den "Characteristic.AirQuality" hinzufügen würdest, hier gibt es in HomeKit, soweit ich weiß, "Gut", "Schlecht" und "Sehr Schlecht":
- LEVEL_NORMAL = GOOD
- LEVEL_ADDED = BAD
- LEVEL_ADDED_STRONG = VERY BAD
![img_8457](https://user-images.githubusercontent.com/264264/37060948-1b31997c-2192-11e8-8e63-b7dc17e75e9e.PNG)

(Screenshots Netatmo)
Gruß Nico

**Comment by thkl** [comment]
Ich kann nur die AirQuality 1:1 zum CO2 Wert abbilden, das geht aber keine ppm Werte, die liefert der Sensor nicht ...

**Comment by nicoh88** [comment]
Hmm, du könntest es aber "hart" mappen oder? Bedeutet wenn Homematic sagt:

"Normale CO2-Konzentation" = 0-999ppm = Gut
"erhöhte CO2-Konzentation" + "deutlich erhöhte CO2-Konzentation" = 1000-1999ppm = Schlecht
"stark erhöhte CO2-Konzentation" = 2000-9999ppm = Sehr Schlecht

[Link](https://www.elv.de/faq/co2-ppm-werte.html) zur ELV FAQ.

**Comment by thkl** [comment]
so ich hab mal geschaut, Service.CarbonDioxideSensor man an der Stelle nur Sinn für die eingebaute Characteristic.CarbonDioxideDetected ... alles andere sind immer falsche Werte ;) Und Wenn ich AirQuality hinzufüge weiss ich nicht wie das die Apps so auswerten .. das ist aber im Prinzip auch gleich dem CO2 Detected ...

**Comment by nicoh88** [comment]
Alles klar. 👍 
Dennoch danke.

Kann es leider noch nicht testen, möchte mir den nächsten auf eBay schießen.
Wird sicher laufen. :sweat_smile:

**Comment by thkl** [comment]
Echt ? Die ollen Dinger willst du kaufen ? Da würde ich eher noch ein Netatmo Innenmodul reinstellen. Das ist hübscher und kann mehr als das olle HM Ding

**Comment by nicoh88** [comment]
Du hast natürlich Recht! Aber, eine Netatmo habe ich schon, möchte ich aktuell verkaufen, da ich im letzten Jahr vielleicht 10x in die Netatmo geschaut habe und ich grundsätzlich versuche Systeme zusammenzuführen, um so wenig unterschiedliche Systeme wie möglich zu haben - deshalb fliegt jetzt Netatmo raus.

Was für uns mittlerweile ein Trigger ist, ist wenn die Netatmo / Home App eine Pushmitteilung sendet, dass die Luftqulität über 1000ppm ist. Darauf möchten wir ungern verzichten, daher der CO2-Sensor von HomeMatic. **Ich finde leider keinen anderen für HomeMatic oder Devolo (Z-Wave).** 👎 

Die Erkenntnis das ich den aktuellen PPM-Wert nicht aus HomeMatic rausbekomme, ist ziemlich schade und zwingt mich aktuell zum erneuten Hinterfragen...

Ich werde unsere Wetterdaten vom HomeMatic Wettersensor, einem CO2-Melder und zwei Temperatur- und Luftfeuchtigkeitssensoren (zwei unterschiedliche Räume) und die 3 Tages-Vorhersagen durch eine Wetter-API auf einem Kindle KT3 (8. Generation, neueste, kein Paperwhite) darstellen. Akkulaufzeit, mit ca. 57 Aktualisierungen am Tag, ca. 25-35 Tage - hochgerechnet, konnte ich noch nicht validieren. 
Dieser PPM-Wert ist für mich da schon sehr wichtig und nett... das geht ja dann nicht. :cry:

FUCK!

![img_8463](https://user-images.githubusercontent.com/264264/37327072-2067ad8e-2695-11e8-960f-ca76089d9176.jpg)
