### ISSUE TITLE
Support HmIP-SWO-[B|PL|PR] (Wettersensor)

### ISSUE THREAD

**Issue by nicoh88** [thkl/homebridge-homematic#211]
Ähnlich [HomeMaticHomeKitWeatherStationService.js](https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitWeatherStationService.js).

![152056_f01_gewettersens](https://user-images.githubusercontent.com/264264/37027138-cc2938b4-2130-11e8-9770-b0495859d7dd.jpg)
![homematic-ip-funk-wetter-kombisensor-hmip-swo-pl](https://user-images.githubusercontent.com/264264/37027141-cc60911a-2130-11e8-9b1f-1d6c527fc8b5.jpg)
![hmip_swo-pr_01](https://user-images.githubusercontent.com/264264/37027139-cc4317ca-2130-11e8-88d6-6b0be6f5462b.jpg)

**Comment by tkoenig** [comment]
Es gibt bereits initialen Support für die Basic Variante, siehe #207 
Eventuell fehlen noch Anpassungen für Sonnenscheindauer, etc aber ich habe die Basic Variante in Einsatz mit Windgeschwindigkeit/Helligkeit und Temperatur.

**Comment by nicoh88** [comment]
@tkoenig 

Ah cool! 👍 

Dann fehlt aber noch der PL und PR in der `channel_config.json` oder?
Laut der [HomeMaticHomeKitIPWeatherStationService.js](https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitIPWeatherStationService.js) sollte ja sogar schon Regen ([Characteristic.IsRainingCharacteristic](url)) und Helligkeit ([Characteristic.CurrentAmbientLightLevel](url)) funktionieren.

Kannst du mal ein Screenshot der Apple Home App posten, wie die Services angezeigt werden? Würde mich aktuell interessieren. 🥇 

Ich werde in den nächsten 10 Tagen, meinen HmIP-SWO-PR von der HmIP-Zentrale ablernen und dann an meiner [piVCCU](https://github.com/alexreinert/piVCCU) anlernen und dann berichten.

Gruß Nico

**Comment by thkl** [comment]
Ich habe das mal gemergt ... Bitte mal Rückinfo ob es problemlos läuft. Dann schiebe ich das mal zusammen mit dem Eve Statistik Feature aus #198  in eine neue npm Version

**Comment by tkoenig** [comment]
Wie man sieht zeigt die Home app nur Temperatur, Luftfeuchte & Helligkeit an.

In z.b. Eve sieht man dann alles.

Was noch fehlt ist eine Unterscheidung zwischen den verschiedenen Wetterstationen. z.b wird zur Zeit auch der Status für Windrichtung & Regen übermittelt, den die Basic version gar nicht hat.

Wenn ich mal dazu komme kann ich mir das gerne anschauen, und auch die zusätzlichen Charakteristiken (Sonnenscheindauer) einbauen.

![img_0849](https://user-images.githubusercontent.com/63860/37078766-ca9a8d9e-21e0-11e8-8af3-d2ee820402b7.PNG)
![img_0850](https://user-images.githubusercontent.com/63860/37078767-cab405b2-21e0-11e8-86a4-20fed0ec5396.PNG)

**Comment by nicoh88** [comment]
@tkoenig Das wäre prima - dann könnten wir hier zu machen. 

Gruß & Danke
Nico

**Comment by nicoh88** [comment]
Hier ist zwar zu. Aber @tkoenig müsste noch zwei Anpassung machen.

- Unterscheidung zwischen den verschiedenen Wetterstationen (z.b wird zur Zeit auch der Status für Windrichtung & Regen übermittelt, den die Basic Version gar nicht hat)
- die zusätzlichen Charakteristiken für Sonnenscheindauer

**Comment by nicoh88** [comment]
@thkl Machst du hier bitte wieder auf? Danke

Ich habe meinen **HmIP-SWO-PR** nun an meiner CCU2 angelernt.

![img_8584](https://user-images.githubusercontent.com/264264/37393103-6fffaa28-2770-11e8-8239-aa841ff712ff.PNG)
![img_8585](https://user-images.githubusercontent.com/264264/37393104-7027c88c-2770-11e8-9534-01b8b68b147b.PNG)

Aufgefallen ist mir folgendes @tkoenig:

- Regen (Ja/Nein)
- Wind Geschwindigkeit
- Wind Richtung
- Wind Schwankungsbreite 

werden nur in EVE angezeigt, dafür gibt es ja _noch_ keinen "offiziellen" Home-App support. Man könnte aber aus "Regen" (Ja/Nein) einen Bewegungsmelder machen, der Auslöst, wenn es regnet. Sonnenscheindauer fehlt. Wind Richtung und Wind Schwankungsbreite werden zwar angezeigt bleiben aber immer bei 0 Grad.

```
<device name="Wettersensor" ise_id="2541" unreach="false" config_pending="false">
<channel name="Wettersensor:0" ise_id="2542" visible="true" operate="true">
<datapoint name="HmIP-RF.012345789:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="2543" value="false" valuetype="2" valueunit="" timestamp="1521008495" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.DUTY_CYCLE" type="DUTY_CYCLE" ise_id="2547" value="false" valuetype="2" valueunit="" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.ERROR_CODE" type="ERROR_CODE" ise_id="2548" value="0" valuetype="8" valueunit="" timestamp="1521018035" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.ERROR_WIND_COMMUNICATION" type="ERROR_WIND_COMMUNICATION" ise_id="2549" value="false" valuetype="2" valueunit="" timestamp="1521018035" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.ERROR_WIND_NORTH" type="ERROR_WIND_NORTH" ise_id="2550" value="false" valuetype="2" valueunit="" timestamp="1521018035" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.LOW_BAT" type="LOW_BAT" ise_id="2551" value="false" valuetype="2" valueunit="" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.OPERATING_VOLTAGE" type="OPERATING_VOLTAGE" ise_id="2555" value="0.000000" valuetype="4" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="2556" value="197" valuetype="8" valueunit="" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.RSSI_PEER" type="RSSI_PEER" ise_id="2557" value="0" valuetype="8" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.TEMPERATURE_OUT_OF_RANGE" type="TEMPERATURE_OUT_OF_RANGE" ise_id="2558" value="false" valuetype="2" valueunit="" timestamp="1521018035" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.UNREACH" type="UNREACH" ise_id="2559" value="false" valuetype="2" valueunit="" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="2563" value="false" valuetype="2" valueunit="" timestamp="1521014918" operations="5"/>
</channel>
<channel name="Wettersensor" ise_id="2567" visible="true" operate="true">
<datapoint name="HmIP-RF.012345789:1.ACTUAL_TEMPERATURE" type="ACTUAL_TEMPERATURE" ise_id="2568" value="2.100000" valuetype="4" valueunit="°C" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.HUMIDITY" type="HUMIDITY" ise_id="2569" value="96" valuetype="16" valueunit="% rF" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.ILLUMINATION" type="ILLUMINATION" ise_id="2570" value="2677.000000" valuetype="4" valueunit="" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.RAINING" type="RAINING" ise_id="2571" value="false" valuetype="2" valueunit="" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.RAIN_COUNTER" type="RAIN_COUNTER" ise_id="2572" value="0.300000" valuetype="4" valueunit="mm" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.RAIN_COUNTER_OVERFLOW" type="RAIN_COUNTER_OVERFLOW" ise_id="2573" value="false" valuetype="2" valueunit="" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.SUNSHINEDURATION" type="SUNSHINEDURATION" ise_id="2574" value="5" valuetype="16" valueunit="min" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.SUNSHINEDURATION_OVERFLOW" type="SUNSHINEDURATION_OVERFLOW" ise_id="2575" value="false" valuetype="2" valueunit="" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.SUNSHINE_THRESHOLD_OVERRUN" type="SUNSHINE_THRESHOLD_OVERRUN" ise_id="2576" value="false" valuetype="2" valueunit="" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.WIND_DIR" type="WIND_DIR" ise_id="2577" value="87.500000" valuetype="4" valueunit="°" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.WIND_DIR_RANGE" type="WIND_DIR_RANGE" ise_id="2578" value="90.000000" valuetype="4" valueunit="°" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.WIND_SPEED" type="WIND_SPEED" ise_id="2579" value="4.000000" valuetype="4" valueunit="km/h" timestamp="1521019233" operations="5"/>
<datapoint name="HmIP-RF.012345789:1.WIND_THRESHOLD_OVERRUN" type="WIND_THRESHOLD_OVERRUN" ise_id="2580" value="false" valuetype="2" valueunit="" timestamp="1521019233" operations="5"/>
</channel>
<channel name="HmIP-SWO-PR 012345789:2" ise_id="2581" visible="true" operate="true"/>
<channel name="HmIP-SWO-PR 012345789:3" ise_id="2582" visible="true" operate="true"/>
<channel name="HmIP-SWO-PR 012345789:4" ise_id="2583" visible="true" operate="true"/>
<channel name="HmIP-SWO-PR 012345789:5" ise_id="2584" visible="true" operate="true"/>
<channel name="HmIP-SWO-PR 012345789:6" ise_id="2585" visible="true" operate="true"/>
<channel name="HmIP-SWO-PR 012345789:7" ise_id="2586" visible="true" operate="true"/>
<channel name="HmIP-SWO-PR 012345789:8" ise_id="2587" visible="true" operate="true"/>
</device>
```

**Es ergeben sich also noch folgende offene ToDos:**

- [ ] - Unterscheidung zwischen den verschiedenen Wetterstationen (z.b wird zur Zeit auch der Status für Windrichtung & Regen übermittelt, den die Basic Version gar nicht hat)
- [ ] - die zusätzlichen Charakteristiken für Sonnenscheindauer
- [ ] - BWM für Regen (Ja/Nein) in der HomeApp
- [ ] - Fix für Wind Richtung und Wind Schwankungsbreite

DANKE

**Comment by nicoh88** [comment]
**Es ergeben sich also noch folgende offene ToDos:**

- [x] - Fix für Wind Richtung und Wind Schwankungsbreite
- [x] - die zusätzlichen Charakteristiken für Sonnenscheindauer
- [x] - Regenmenge abbildbar (RAIN_COUNTER)
- [x] - BWM für Regen (Ja/Nein) in der HomeApp
- [x] - Unterscheidung zwischen den verschiedenen Wetterstationen (z.b wird zur Zeit auch der Status für Windrichtung & Regen übermittelt, den die Basic Version gar nicht hat)
- [x] - Protokollierung für Temperatur und Luftfeuchte (fakegato-history)

**UPDATE:**
Bei [fakegato-history](https://github.com/simont77/fakegato-history) funktioniert nur ein `accessoryType` pro Geräte (Wettersensor). Also musste ich entscheiden ob "weather" (Temperatur & Helligkeit) oder "motion" (Regenerkennung) protokolliert werden soll.
Ich habe mich für "weather" (Temperatur & Helligkeit) entschieden. Sollte sich dem "**Problem**" mal ein richtiger Programmierer widmen, bekommt man das sicher irgendwie hin - aber fürs erste so in Ordnung.

**Comment by thkl** [comment]
Nö, man kann mehrere Characteristics loggen. Mach ich ja beim Thermostat: Temp & Feuchtigkeit.

**Comment by nicoh88** [comment]
Done & Close.
https://github.com/thkl/homebridge-homematic/commit/557628cb6644cb3c0535e914e5fa9fe103cc2a27

**Comment by nicoh88** [comment]
@thkl 

Korrekt, Temperatur & Feuchtigkeit (weather) geht, aber zusätzlich Bewegungserkennung (motion), in dem Fall bei [RAINING](url), geht nicht.

Wenn doch, kannst du ja die Anpassung machen. 👍 
Ich bin mit meinen Commit fertig.
