### ISSUE TITLE
HmIP-PDT Wird nicht angezeigt

### ISSUE THREAD

**Issue by djgreenfire** [thkl/homebridge-homematic#213]
Hallo, und zwar habe ich einen Pi3,eine laufende Homebridge und eine CCU2.
ich habe an der CCU2 schon einen HmIP-SMI(Bewegungsmelder) & einen
HMIP-SWDO(Fensterkontakt) beide werden super in meiner Apple Home App
angezeigt und funktionieren Tadellos nun habe ich eine HmIP-PDT steckdose
und bekomme diese einfach nicht in der Home app zu gesicht. über das
Webinterface der CCU2 kann ich die Steckdose sehen und auch steuern aber
auf meinem Telefon nicht.
Denn als nächstes möchte ich
gern einen Unterputz-Taster mit Dimmer installieren um so per Taster und
per smartphone meine Deckenbeleuchtung zu steuern.

Wäre dir sehr dankbar für deine Hilfe.

Installiert habe ich die Homebridge per App und die Plugins genauso.

**Comment by thkl** [comment]
Ich hab mal geschaut, das könnte durchaus schon mit einer kleinen Änderung in der config.json Datei auf dem Pi funktionieren.
Probier mal bitte folgendes in die Parameter des homematic-plugins einzufügen:

```
"services": [{	 
  "type": "DIMMER_TRANSMITTER",
	   "service": "HomeMaticHomeKitDimmerService"
}]
```

**Comment by djgreenfire** [comment]
Ich habe die Zeile eingefügt aber es hat trotzdem nicht geklappt

**Comment by djgreenfire** [comment]
{
  "accessories" : [

  ],
  "bridge" : {
    "username" : "CD:22:3D:E3:CE:07",
    "name" : "Homebridge",
    "pin" : "031-45-031",
    "port" : 51826
  },
  "platforms" : [
    {
      "ccu_ip" : "192.168.178.92",
      "subsection" : "Homekit",
      "doors" : [

      ],
      "enable_hmip" : true,
      "services" : [
        {
          "type" : "DIMMER_TRANSMITTER",
          "service" : "HomeMaticHomeKitDimmerService"
        }
      ],
      "platform" : "HomeMatic",
      "windows" : [

      ],
      "outlets" : [
        "HmIP-RF.000DD7098B9176:3",
        "HmIP-PDT.000DD7098B9176:3"
      ],
      "name" : "HomeMatic",
      "programs" : [
        "Steckdose50",
        "SteckdoseAus",
        "Steckdose10"
      ]
    },

**Comment by djgreenfire** [comment]
Wahrscheinlich meintest du es so:

    "services" : [
        {
          "type" : "HmIP-PDT",
          "service" : "HomeMaticHomeKitDimmerService"
        }
      ],

Es hat funktioniert!!! Vielen Dank für die hilfe

**Comment by thkl** [comment]
ok dann geht der normale Dimmer Service dafür ...

**Comment by nicoh88** [comment]
@thkl Soll ich es direkt in der `channel_config.json` für ALLE hinterlegen? 
Wenn nein, kurze Info an mich, warum nicht. Damit ich in Zukunft weiß, wie ich mich verhalten soll.

Gruß Nico

**Comment by djgreenfire** [comment]
Ich denke das es Sinn macht, Wenn diese Funktion direkt integriert ist.
Auf jeden Fall nochmals vielen Dank vor allem für die schnelle Hilfe. Man darf ja nicht vergessen das die ganzen Entwickler hier ja auch noch ein privat- und Berufsleben haben.

Mit freundlichen Grüßen
