### ISSUE TITLE
HomeMaticHomeKitGarageDoorService.js

### ISSUE THREAD

**Issue by qwikser** [thkl/homebridge-homematic#214]
Huhu - jetzt haut es auch bei mir hin. 😄  Was ich aber eben noch loswerden wollte. Kann man noch quasi eine Art "Sperre" einbauen? ..falls das Tor offen ist und man zu Siri sagt: "Öffne das Tor" ..dann wird dort der Befehl gesendet, was das Tor quasi schließt. Da ich ja nur den einen Kontakt habe für auf/stop/zu. In der Home APP wird dann der Zustand nicht mehr korrekt angezeigt.

**Comment by nicoh88** [comment]
Hi @qwikser,

damit hast du leider absolut Recht - habe es gerade getestet. 👎 

@thkl 
Ich dachte die Logik übernimmt nun HomeKit / Apple selbst, da ja eigentlich klar ist, dass das Garagentor geschlossen ist und somit nicht "nochmal" geschlossen werden kann. Selbst mit einem Sensor, sollte es eigentlich nur ein Problem im Zeitfenster (bei 16 Sekunden) zwischen "Öffnen" und "komplett Offen" geben. Liegt das am `HomeMaticHomeKitGarageDoorService.js` oder an HomeKit selbst?

**Comment by thkl** [comment]
Ja ich prüfe nicht ob das Tor Offen ist, ich bin davon ausgegangen das HomeKit das verhindert. 

Scheinbar also nicht.  Mit nur einem Sensor für geschlossen wird das aber schwer. Ich könnte zwar an der Stelle schauen das der Auf Befehl nur gesendet wird wenn der geschlossen Sensor das Tor als Zu an sieht. Aber man könnte ein zu fahrendes Tor dann nicht mit dem AufButton unterbrechen.  

Mit zwei Sensoren kein Ding, dann geht auf nur wenn der Auf Sensor negativ ist und Zu nur wenn der Zu Sensor nicht zu meldet.

**Comment by qwikser** [comment]
Mist - dann hätte ich aber besser mal 2 MKs geholt anstatt dem hier:[http://www.eq-3.de/produkte/homematic/sicherheit-und-ueberwachung/hm-sec-tis.html](url) 😝

**Comment by thkl** [comment]
Aber spätestens wenn der Sensor das nächste mal einen Status sendet, sollte das Tor in der Home App wieder richtig angezeigt werden. Denn ich setze den Status immer unabhängig von der Bedienung, damit auch eine direkte Bedienung am Tor in der App richtig angezeigt wird.  

Ich könnte aber an jeden Bedienbefehl eine zeitversetzte Statusabfrage hängen. Dann sollte das auch wieder passen. 

Wie lange braucht so ein Tor für einmal auf oder zu in der Regel ?

**Comment by qwikser** [comment]
Bei mir öffnen:
`
[2018-03-14 20:51:34] [HomeMatic CCU Bridge] RPC event for BidCos-RF.LEQ1318725:2 STATE with value true
[2018-03-14 20:51:34] [HomeMatic CCU Bridge] RPC event for BidCos-RF.LEQ1318725:2 WORKING with value false
[2018-03-14 20:51:34] [HomeMatic CCU Bridge] RPC event for BidCos-RF.LEQ1318725:2 STATE with value false

[2018-03-14 20:51:40] [HomeMatic CCU Bridge] RPC event for BidCos-RF.OEQ1018668:1 STATE with value true
[2018-03-14 20:51:40] [HomeMatic CCU Bridge] garage event BidCos-RF.OEQ1018668:1,STATE,true
`
Und schließen:
`
schließen

[2018-03-14 20:47:38] [HomeMatic CCU Bridge] RPC event for BidCos-RF.LEQ1318725:2 STATE with value true
[2018-03-14 20:47:38] [HomeMatic CCU Bridge] RPC event for BidCos-RF.LEQ1318725:2 WORKING with value false
[2018-03-14 20:47:39] [HomeMatic CCU Bridge] RPC event for BidCos-RF.LEQ1318725:2 STATE with value false

[2018-03-14 20:48:04] [HomeMatic CCU Bridge] RPC event for BidCos-RF.OEQ1018668:1 STATE with value false
[2018-03-14 20:48:04] [HomeMatic CCU Bridge] garage event BidCos-RF.OEQ1018668:1,STATE,false
`

**Comment by nicoh88** [comment]
Bei mir 16 Sekunden pro Vorgang, das ist aber im Vergleich zu vielen älteren Garagentormotoren schon schnell.

---

Dann hole ich mir auf jedenfall noch einen HmIP-SWDO (Tür-/Fensterkontakt) für den "Geschlossen" Zustand.

**THKL schrieb:** _Mit zwei Sensoren kein Ding, dann geht auf nur wenn der Auf Sensor negativ ist und Zu nur wenn der Zu Sensor nicht zu meldet._
@thkl: So ist jetzt bereits schon umgesetzt?

Gruß Nico

**Comment by thkl** [comment]
Also umgesetzt ist das noch nicht. Frage : Ist das irgendwie für das Tor schädlich wenn es auf ist und noch mal auf gemacht wird ? (nur dann würde ich versuchen das zu verhindern) ansonsten würde ich einfach eine Variable "rescan_delay" einbauen. Nach der angegebenen Zeit, würde ich aus dem Service einfach noch mal die Kontakte abfragen und den Homekit Zustand entsprechend nachziehen ...

**Comment by nicoh88** [comment]
@qwikser: Mit den Nachbarn geht mir ähnlich. Push-Mitteilungen habe ich für das Gerät deaktiviert. 😃

@thkl: Nein, es ist nicht schädlich für das Garagentor, wenn es auf ist und nochmal aufgemacht wird. Es geht in diesem Fall dann halt nur nicht nochmal auf oder weiter auf oder (im besten Fall) macht gar nichts - sondern geht halt zu, obwohl man gesagt hat "Öffnen".

Gruß Nico

**Comment by thkl** [comment]
ok der Einfachheit halber werde ich diese Rescan Sache einbauen. Damit ist im Prinzip auch alles erschlagen.

**Comment by nicoh88** [comment]
@thkl 
Habe die aktuelle Master drauf, aber beim Neustart von Homebridge wird weiterhin "**Wird geöffnet**" angezeigt, erst wenn ich dann händisch das Garagentor einmal hin und wieder zurückschalte, wird der Status richtig angezeigt. Oder, so scheint es, wenn der Sensor seinen Wert mal wieder an die CCU schickt.

**Deine ToDos:**
- `rescan_delay` einbauen
- bei zwei Sensoren, kein "Öffnen" erlauben, wenn schon "Geöffnet"
- Statusabfrage beim Start von Homebridge

**Comment by thkl** [comment]
die initiale Statusabfrage sollte eigentlich laufen.
Mal bitte homebridge mit -D als Parameter starten. Vor dem Barcode noch müsste sowas hier kommen:


````
.... inital query ...
.... result for close sensor ...
.... Close sensor set new target state....
.... Close sensor set new current state ....

**Comment by qwikser** [comment]
..ist die Version von gestern noch die selbe wie jetzt? ..dann guckt ich mal.

**Comment by nicoh88** [comment]
```
[3/15/2018, 3:51:49 PM] [HomeMatic CCU] result for close sensor 0
[3/15/2018, 3:51:49 PM] [HomeMatic CCU] garage event 0000D569951B4A:1,STATE,0
```

Aktuell geht es, versteh ich nicht.

**Comment by thkl** [comment]
Könnte ein Timing Problem sein. Da das beim Init der Accessoires läuft, könnte es sein, das diese noch nicht komplett eingelesen und an den homebridge Kernel gesendet wurden. Ich bau da mal eine Verzögerung ein.

**Comment by thkl** [comment]
Also das initiale Query der Sensoren erfolgt 60Sekunden nach Start der homebridge. Damit sollte alles in homekit hochgelaufen sein (famous last words)

30 Sekunden nach einer Betätigung des Tores werden die Sensoren gefragt, und entsprechend deren Status wird Homekit aktualisiert.
Wenn die 30 Sekunden nicht reichen können sie mit dem config Parameter sensor_requery_time eingestellt werden.
