### ISSUE TITLE
HMIP-SWSD: IP Rauchmelder

### ISSUE THREAD

**Issue by alexduerl** [thkl/homebridge-homematic#215]
Hallo,

ich habe 3 der Homematic IP Rauchmelder gekauft und diese gestern an der CCU angemeldet.
Die Geräte werden auch korrekt an HomeKit übergeben.

Nun hätte ich aber ggf. noch einen Verbesserungsvorschlag, dazu muss ich aber kurz ausholen:

Wenn man die Dinger an die CCU anmeldet, werden diese automatisch untereinander verknüpft, so dass der Alarm eines Melders an die anderen Melder weitergereicht wird, und diese ebenfalls Alarm schlagen: eine praktische Funktion, die im Ernstfall sicherlich sehr wertvoll ist.

Das Ganze führt aber auch dazu, dass in der HomeKit der Alarm für ALLE Melder angezeigt wird, folglich kann man nicht nachvollziehen, welcher Melder jetzt die "Ursache" für den Alarm war. Wenn man im gesamten Haus von Keller bis Dachboden Melder verteilt hat, wäre es im Ernstfall auch sehr hilfreich wenn man erkennen würde, WELCHER Melder nun ursächlich Alarm geschlagen hat, damit man der Sache etwas gezielter nachgehen kann.

Ich habe mal geschaut: die Dinger unterscheiden folgende Stati für den Parameter "SMOKE_DETEKTOR_ALARM_STATUS":

0 = Kein Alarm steht an
1 = Brandalarm an diesem Melder erkannt
2 = Der Melder signalisiert einen Einbruchalarm 
3 = Ein anderer Melder hat einen Brandalarm erkannt, dieser wurde auch an diesem Melder signalisiert

Mein Vorschlag wäre also, dass man NUR Alarme mit Status 1 an die Home-App weitergibt. Dann schlagen zwar alle Melder an, aber NUR der ursächliche Melder wird in der Home-App angezeigt und nur für diesen Melder wird eine Push-Nachricht gesendet. Dann sieht man sofort wo man im Ernstfall nachsehen muss.

Was meint Ihr dazu?

LG

**Comment by alexduerl** [comment]
Da man die Rauchmelder auch für einen Einbruchalarm nutzen kann (Status 2), wäre hier ggf. zu überlegen wie man dieses Szenario in HomeKit darstellen könnte, so dass man auch erkennt, dass der Einbruchalarm ausgelöst hat.

**Comment by thkl** [comment]
also sollte der HomeKit Alarm nur auf dem Melder angezeigt werden wenn SMOKE_DETEKTOR_ALARM_STATUS == 1 

Wenn dann müsste das aber in der config variabel sein, denn ggf will ein anderer User ja das Verhalten anders haben ...

Das mit dem Einbruch geht nicht, es sei denn ich kann das irgendwo vor einem Alarm auslesen. Beim Start von HB werden die Geräte aus der CCU gelesen und aus deren Typen die jeweiligen HomeKit Geräte gebildet. An der Stelle muss klar sein, was der Rauchmelder für ein Gerät ist.

**Comment by alexduerl** [comment]
Ja, denke der Alarm sollte nur angezeigt werden, wenn der Status = 1 ist.
Wenn das konfigurierbar wäre, wäre natürlich top, dann kann jeder das Verhalten nach seinem Belieben einstellen (wobei ich denke dass es Sinn macht im Stnadard tatsächlich nur den Melder alarm schlagen zu lassen der ursächlich ausgelöst hat).

Wegen dem Einbruchalarm war nur so ein Gedanke. Ich denke hier macht es Sinn wenn das auslösende Gerät in HomeKit entsprechend Meldung macht (z.B. Der Fensterkontakt oder der BWM). Die Rauchmelder werden ja nur zur Signalgebung missbraucht. Daher brauchen die nicht zwangsläufig in HomeKit einen Einbruchalarm anzuzeigen ...

**Comment by thkl** [comment]
siehe https://github.com/thkl/homebridge-homematic/wiki/Rauchmeldergruppen

**Comment by alexduerl** [comment]
... ein Traum! Vielen Dank!

**Comment by superbraz** [comment]
ich habe mir nun auch die SWSD zugelegt und diese ins HK eingebunden,
aber an welcher Stelle muss denn

"HmIP-SWSD:SMOKE_DETECTOR": {
  "single_alarm":true
}

in die Config?
