### ISSUE TITLE
IP Präsenzmelder HmIP-SPI Fehlermeldung

### ISSUE THREAD

**Issue by AbdulAlBane** [thkl/homebridge-homematic#217]
Hi,

wird der Homematik-IP-Präsenzmelder innen (batteriebetrieben) noch nicht unterstützt? Aktuell bekomme ich immer noch die Fehlermeldung  "There is no service for HmIP-SPI:PRESENCEDETECTOR_TRANSCEIVER".

Gruß
Alex

**Comment by thkl** [comment]
Nein wird er nicht ... Wie äußert sich dessen Zustand ? Da sollte es nur wahr und falsch geben ?

**Comment by AbdulAlBane** [comment]
Ja, er gibt nur an, ob er eine Präsenz erkennt, oder nicht. Als Auslöser sollte das für Homekit reichen, analog zu jedem anderen Standardbewegungsmelder [Präsenz erkannt; Erkennen von Präsenz beendet/keine Präsenz mehr erkannt].
![image](https://user-images.githubusercontent.com/37419381/37488972-755c3fbe-2896-11e8-8b16-7718f8955a1a.png)

**Comment by thkl** [comment]
Also könnte man das Ding wie einen normalen IR Sensor abfackeln ?

**Comment by AbdulAlBane** [comment]
Denke ich doch. Erkennt nur feinere Bewegungsmuster und man muss im Bad nicht wild rumfuchteln, damit das Licht wieder angeht ;)
