### ISSUE TITLE
HM-Sec-Key-S

### ISSUE THREAD

**Issue by arndtk** [thkl/homebridge-homematic#218]
Hallo thkl,

wäre es möglich, das genannte Türschloss ebenso komfortabel wie die GaragentorFunktion in Homekit zu integrieren? 

Also auch nur eine Kachel zum Öffnen/Schließen inkl. Anzeige geöffnet/geschlossen.

Was müsste ich dafür vorbereiten?

Grüße
Arndt

**Comment by nicoh88** [comment]
Ich habe bisher, eine solche Funktionalität in HomeKit noch nie gesehen. Ich vermute fast, dass seitens Apple bisher nur ein Garagentor mit dieser Funktionalität ausgestattet ist. Kann es aber nicht belegen...

Hier würde man ja sogar keinen extra Sensor für den Zustand benötigen oder?
Wenn man ein "HM-Sec-Key-S" und einen "Türkontakt" hat, hatte man ja immer zwei Kacheln einmal für die Haustür, einmal für das Schloss - nur weil das Schloss geöffnet ist, muss die Tür ja nicht geöffnet sein.

Wie wird das "HM-Sec-Key-S" momentan in HomeKit angezeigt? Als Schalter/Steckdose?

**Comment by arndtk** [comment]
Also es wird in HK als Schloss angezeigt. Bei Tip auf die Kachel fährt das Schloss auch in die korrekte Position.

Aber: Beim Sperren läuft und läuft die Anzeige obwohl das Schloss bereits erfolgreich zugefahren ist.

Grüße
Arndt

**Comment by thkl** [comment]
so, das Thema sollte erledigt sein .. ich hab das Servicefile bissel umgebaut ...

**Comment by arndtk** [comment]
Wie jetzt, Problem schon behoben? *staun*

Sorry, aber kannst Du mir kurz sagen, was ich nun machen muss?

Grüße
Arndt

**Comment by thkl** [comment]
:)

Du musst nur aufs nächste npm Release warten. 
Ich denke das schaffe ich morgen.

**Comment by thkl** [comment]
kann das mal jemand im 0.0.98 testen ... danke

**Comment by arndtk** [comment]
Hi.

Also die neue Version "drüber" installieren? Muss ich meine CONFIG vorher sichern?

Sorry, aber ich bin echt noch neu in diesem Thema. ;-)

Grüße
Arndt

**Comment by nicoh88** [comment]
Kurze Info für die, die mit ...

`npm install thkl/homebridge-homematic#master -g --unsafe-perm`

... auf die unstabile, inoffizielle **GitHub-#Master** aktualisiert haben, können nun mit ...

`npm install homebridge-homematic -g --unsafe-perm`

... auf das aktuelle, stabile NPM-Release aktualisieren und zukünftig, wie sonst auch, mit ...

`npm update homebridge-homematic -g`

... updaten. Somit wird dann nicht mehr auf die GitHub-Master-Version geupdatet, sondern auf die von @thkl publizierten NPM-Versionen.

@arndtk: Deine Konfiguration musst du nicht sichern. Je nachdem, welche Garagentor Testversion du installiert hattest, kann es sein, dass sich die Einträge in der config.json geändert haben. 👍 Wirst du aber sehen, kein großes Thema. 

Viel Spaß!

**Comment by arndtk** [comment]
Also ich bekomme keine Kachel in HomeKit angezeigt.

**Comment by arndtk** [comment]
Also ich bekomme keine Kachel in HomeKit angezeigt.

**Comment by arndtk** [comment]
@nicoh88 , klappt bei Dir nach dem Update weiterhin alles ohne Probleme?

Grüße
Arndt

**Comment by nicoh88** [comment]
@arndtk Poste doch mal deine` config.json`, sicher nur eine Kleinigkeit. 👍

**Comment by arndtk** [comment]
@nicoh88

Ich muss mich verbessern. Hatte das Türschloss nicht korrekt unter Gewerke einsortiert. Es ist nun sichtbar und funktioniert auch einwandfrei. *puh*

Was noch toll wäre: Das Schloss bietet noch eine dritte Funktion (neben ver- und entriegeln). Man kann es auch als Türöffner nutzen. Dazu wird der Schnapper kurz eingezogen und die Tür geht auf. 
Könnte man das auch noch als eigenständige Kachel hinbekommen?

Das Garagentor klappt leider weiterhin nicht. Hier meine config:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "platforms": [{
        "platform": "HomeMatic",
        "name": "HomeMatic CCU2",
        "ccu_ip": "192.168.2.105",
        "filter_device": [],
        "filter_channel": [],
        "outlets": [],
        "doors": [],
        "programs": [],
        "accessories": [],
        "subsection": "Homekit",
        "variables": ["Anwesenheit", "Automatikfunktionen"],
        "special": [{
            "name": "Garage",
            "type": "HM-THKL-GARAGEDOOR",
            "parameter": {
                "address_sensor_close": "BidCos-RF.MEQ0475367:1.STATE",
                "state_sensor_close": false,
                "address_actor_open": "BidCos-RF.MEQ1843772:1.STATE",
                "message_actor_open": {
                    "on": 1,
                    "off": 0
                }
            }
        }],
        "services": [{
            "type": "HM-THKL-GARAGEDOOR",
            "service": "HomeMaticHomeKitGarageDoorService"
        }]
    }]
}

```

**Comment by nicoh88** [comment]
Hi @arndtk,

ich denke, du hast das gleiche Problem wie ich hatte. 
Schaust du hier: #227

**Comment by arndtk** [comment]
Perfekt, hat geklappt!

Danke!

Sollte ich hierfür ein neues ISSUE aufmachen?
_Was noch toll wäre: Das Schloss bietet noch eine dritte Funktion (neben ver- und entriegeln). Man kann es auch als Türöffner nutzen. Dazu wird der Schnapper kurz eingezogen und die Tür geht auf.
Könnte man das auch noch als eigenständige Kachel hinbekommen?_

**Comment by dkrizic** [comment]
Zum Öffnen der Tür habe ich mir ein kleines Programm in der CCU geschrieben, welches das Türschloss öffnet und dann als Schalter (programs) eingebunden.

**Comment by arndtk** [comment]
@dkrizic danke für den Tip! Manchmal können Lösungen so einfach sein. ;-)
