### ISSUE TITLE
Garagentor -> Virtueller Taster

### ISSUE THREAD

**Issue by thoduh** [thkl/homebridge-homematic#219]
Was muss ich bei "address_actor_open" eintragen wenn ich einen virtuellen Taster verwenden will?

Bekomme folgenden Fehler:
BidCoS-RF:1 is invalid not 3 parts
cannot initialize garage device adress for open actor is invalid

**Comment by thoduh** [comment]
Bei "BidCos-RF.BidCoS-RF:1.PRESS_SHORT" kommt keine Fehlermeldung mehr, aber der Taster wird nicht betätigt...

**Comment by thkl** [comment]
Ähm BlindService kennt keine Taster. Meinst Du das Garagentor ?

**Comment by thoduh** [comment]
Stimmt natürlich, Sorry, war gestern schon spät ;-)

**Comment by thkl** [comment]
Ok ich schau mir das nachher mal an. Eigentlich sollt der Taster auslösen wenn man dem Datenpunkt ein true sendet.

**Comment by thkl** [comment]
Ok ich hab es gefunden. Aufgrund eines routing bugs wurden alle Calls der Garage nicht via rpc gesendet sondern sind zurück auf Rega gefallen. Nur sind die Virtuellen Tasten nicht via dom.GetObject(...) ansprechbar .. deswegen nix ..

Änderungen sind mehreren Files ...

**Comment by thoduh** [comment]
Kann es leider nicht testen, da ich es nicht mehr zum laufen bekomme :-(
Weiß nicht mehr wie ich es gestern geschafft hatte.

Ich kenn mich nicht besonders gut aus, deshalb muss ich wohl warten bis die Finale Version zum Download bereitsteht...

**Comment by thkl** [comment]
0.0.98 release eingetütet sollte da jetzt gehen
