### ISSUE TITLE
Feature Request: Sprinkler

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#220]
Hi,

ich habe gesehen, dass die aktuelle Homebridge/HAP-NodeJS-Version auch Sprinkler kennt. Wäre es möglich, dass man Schalter (ähnlich wie outlet) als Sprinkler abbildet?

Gruß,

Darko

**Comment by thkl** [comment]
Was meinst Du mit Schalter ? Einen Switchaktor oder einen Kontaktsensor ?

Gehen würde das sicher.

Langsam wird die Config echt wild 😜

**Comment by dkrizic** [comment]
Hi,

einen Switchaktor. 

Gruß,

Darko

**Comment by thkl** [comment]
Ähm Sprinkler ? Meinst Du damit Service.Faucet ... das wird als Wasserhahn angesehen ..also ich würde es eher in die Richtung Magnetventil schieben ...

**Comment by dkrizic** [comment]
es gibt Faucet und es gibt Sprinkler. Bei mir sind es in der Tat Magnetventile. Sprinkler haben in der Home-App irgendwelche Timing-Funktionen, die mich interessieren.

**Comment by thkl** [comment]
Ui juijui das Ding ist nicht trivial.

**Comment by dkrizic** [comment]
Ist es mehr als eine Geschmacksrichtung für Aktoren?

**Comment by thkl** [comment]
bisher 124 Zeilen extra Code ... and counting ...

**Comment by thkl** [comment]
Jap ... es gibt einen Valve Service .. dieser hat verschiedene Geschmacksrichtungen ... unteranderem Irrigation (also Sprinkler) ... den hab ich jetzt implementiert .. Mit Timer und allem ...

**Comment by thkl** [comment]
Siehe https://github.com/thkl/homebridge-homematic/wiki/Sprinkler-(Gartenbewässerung)

**Comment by dkrizic** [comment]
Leg Dir mal was in die Amazon-Wunschliste, ich schätze Deinen Aufwand!

**Comment by dkrizic** [comment]
Sieht bei mir jetzt so aus: 

![img_0332](https://user-images.githubusercontent.com/1181349/37565777-ead09306-2aaf-11e8-8c4e-9cf1f8ad1338.png)

Interessanterweise kann ich diese nicht per Schedule aktivieren, irgendwie blicke ich es noch nicht, aber das ist jetzt ein HomeKit-Problem.

**Comment by thkl** [comment]
Ja, so ist es gedacht.  Es wird sich die Einstellung der Laufzeit gemerkt. Die Abschaltung funktioniert auf 2 Wegen. Einmal über den OnTime Parameter und dann noch mal als Zähler innerhalb von Homebridge. Den brauch ich sowieso damit das in Home schön mitzählt.

**Comment by iuliusmaximilian** [comment]
Gibt es die Möglichkeit diese auch als "Wasserhahn" darzustellen, ich habe eine Zikulatiosnpumpe und eine Frischwasserzufuhr die würde ich gerne mit einem anderen Icon darstellen ?

**Comment by thkl** [comment]
Dafür müsstest du im Switch Service den Valve Type ändern.

**Comment by iuliusmaximilian** [comment]
Funktioniert, ist aber eher unschön dort den Standard zu ändern, noch dazu wo ich auch Sprinkler habe müsste ich das unterschiedlich über mehrere Instanzen machen. Ich habe dazu mal einen Feature Request aufgemacht.
