### ISSUE TITLE
0.0.98 Respektive 0.0.99

### ISSUE THREAD

**Issue by bprskalo** [thkl/homebridge-homematic#221]
Lieber Thomas

Hier ein Feedback zu der aktuellen Version 👍 

Ich habe mir gerade die aktuelle NPM Version gezogen. angezeigt wird mit dann die 0.0.99 

beim starten dann folgende Fehlermeldung

/usr/local/lib/node_modules/homebridge-homematic/index.js:656
		throw err
		^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/homebridge-homematic/internalconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at HomeMaticPlatform.internalConfig (/usr/local/lib/node_modules/homebridge-homematic/index.js:653:32)
    at HomeMaticPlatform.accessories (/usr/local/lib/node_modules/homebridge-homematic/index.js:160:30)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

bis und mit 0.0.97 keine Probleme gehabt 

Grüsse

Bosi

**Comment by thkl** [comment]
Da hat doch jemand tatsächlich in den 10 Minuten wo es kaputt war upgedatet.
101 geht wieder siehe https://github.com/thkl/homebridge-homematic/commit/83958fc3f6c7d35fedaa818be14e9071dc01f5bf

**Comment by bprskalo** [comment]
Danke !

also di 0.0.101 lässt sich installieren .. aber .. die RF Geräte lassen sich mit der 101 nicht ansprechen .. IP Geräte gehen ..

Gruss

**Comment by thkl** [comment]
Whooot ? ( schaltet zwischendurch wild das Licht an und aus )
Schau mal bitte in /var/log/homebridge.log ob da irgenwas ungewöhnliches auftaucht

**Comment by bprskalo** [comment]
nach jedem update teste ich alle Geräte :-) .. und darum auch gleich die Rückmeldung .. 

ehm .. ich hab kein log

**Comment by thkl** [comment]
also Schaltaktoren gehen .. Dimmer zicken ... (schau ich mir an)

**Comment by thkl** [comment]
so, 102 sollte alle Dimmer (und Jalosien) wieder heile machen ... Problem ist bei den Tests durchgefallen, weil die an der Stelle aufhören, wo Daten zur CCU gehen. (Travis hat ja keine CCU ;) )
Das XMLRPC Modul versendet bei ganzen Zahlen ein Integer aber die Schnittstelle erwartet ein double .... nun ja

**Comment by bprskalo** [comment]
läuft für mich so :-) , DANKE ! 

frage .. "Set Brightness" Level werden (wieder) angezeigt .. ist das bewusst so ? nicht dass es mich stört :-)

**Comment by thkl** [comment]
im Log ? Ja ... hab ich vergessen vor dem npm publish wieder rauszuwerfen ...

**Comment by bprskalo** [comment]
also auf der Raspberry ,

**Comment by thkl** [comment]
jap statt log.debug steht da log.info .. ich mach gleich ein 103, was solls bits sind billig

**Comment by bprskalo** [comment]
danke für die 103 :-) !! läuft !

**Comment by thkl** [comment]
Notiz an mich : Build System verbessern ...
