### ISSUE TITLE
Homebridge startet nicht mehr

### ISSUE THREAD

**Issue by Omega236** [thkl/homebridge-homematic#222]
Hallo,

nach einem Update (war davor glaub auf um die .7x)
bin jetzt auf @0.4.38 und  @0.0.103

und bekomme diesen fehler:

[2018-3-18 14:00:12] [HomeMatic CCU] if PONG is PONG CCU is alive
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.join (path.js:1217:7)
    at FakeGatoStorage.read (/usr/lib/node_modules/homebridge-homematic/ChannelServices/fakegato-storage.js:108:61)
    at FakeGatoHistory.load (/usr/lib/node_modules/homebridge-homematic/ChannelServices/fakegato-history.js:609:37)
    at FakeGatoHistory.<anonymous> (/usr/lib/node_modules/homebridge-homematic/ChannelServices/fakegato-history.js:192:12)
    at FakeGatoStorage.addWriter (/usr/lib/node_modules/homebridge-homematic/ChannelServices/fakegato-storage.js:54:6)
    at new FakeGatoHistory (/usr/lib/node_modules/homebridge-homematic/ChannelServices/fakegato-history.js:185:38)
    at HomeMaticHomeKitMotionDetectorService.createDeviceService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorService.js:19:24)
    at HomeMaticHomeKitMotionDetectorService.HomeKitGenericService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:69:8)
    at new HomeMaticHomeKitMotionDetectorService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorService.js:8:50)
pi@homebridge:~ $

Konfig habe ich schon alles nicht lebenswichtige rausgegnommen:
{
                "platform": "HomeMatic",
                "name": "HomeMatic CCU",
                "ccu_ip": "192.168.000.109",
                "subsection":"Siri",
                "filter_device":[],
                "filter_channel":[],
                "outlets":[],
                "variables":[                       ],
                "ios10":true,
                "lcache":true,
                "enable_hmip":"true",
                "local_port":10580,
                "services": [
        ]
        }

**Comment by Omega236** [comment]
Ok habe gefunden dass ich die true in " setzen muss, dann geht meine standard-konfig.

mit meiner Orginal konfig  bekomme ich den Fehler:
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1217:7)
    at HomeMaticChannelLoader.loadClass (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:111:25)
    at HomeMaticChannelLoader.loadChannelService (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:65:22)
    at device.channels.map.ch (/usr/lib/node_modules/homebridge-homematic/index.js:338:22)
    at Array.map (native)
    at json.devices.map.device (/usr/lib/node_modules/homebridge-homematic/index.js:294:21)
    at Array.map (native)
    at HomeMaticPlatform.buildaccesories (/usr/lib/node_modules/homebridge-homematic/index.js:282:16)
    at regarequest.script.e (/usr/lib/node_modules/homebridge-homematic/index.js:228:9)


Konfig:
        {
                "platform": "HomeMatic",
                "name": "HomeMatic CCU",
                "ccu_ip": "192.168.000.109",
                "subsection":"Siri",
                "filter_device":[],
                "filter_channel":[],
                "outlets":[],
                "variables":[
                        "Anwesenheit"
                            ],
                "ios10":"true",
                "lcache":"true",
                "enable_hmip":"true",
                "local_port":10580,
                "services": [
                        {
                                "type": "VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH",
                                "service": "HomeMaticHomeKitRGBWService"
                        },
                        {
                                "type": "SWITCH",
                                "service": "HomeMaticHomeKitSwitchServiceAsSwitch"
                        },
                        {
                                "type":"HM-LC-Ja1PBU-FM:JALOUSIE",
                                "service": "HomeMaticHomeKitBlindService"
                        }
                           ]
        }

**Comment by nicoh88** [comment]
Also läuft wieder?

**Comment by Omega236** [comment]
mein selbst implementiertes leider nicht.
scheinbar macht meine Klasse HomeMaticHomeKitSwitchServiceAsSwitch probleme, ich verstehe nur noch nicht warum.

**Comment by Omega236** [comment]
ja, bisher lief sie gut:

'use strict';
const path = require('path');
const util = require("util");
const fs = require('fs');
function HomeMaticHomeKitSwitchServiceAsSwitch(log,platform, id ,name, type ,adress,special, cfg, Service, Characteristic) {

HomeMaticHomeKitSwitchServiceAsSwitch.super_.apply(this, arguments);
}

// Attention : If you move the clazz outside the buildin channelservice you have to make sure the superclass HomeKitGenericService
// is reachable

var parentPath = path.dirname(module.parent.filename);
var rootClazzPath = path.join(parentPath,'ChannelServices','HomeKitGenericService.js');
var rootClazz = require(rootClazzPath).HomeKitGenericService

util.inherits(HomeMaticHomeKitSwitchServiceAsSwitch, rootClazz);

HomeMaticHomeKitSwitchServiceAsSwitch.prototype.createDeviceService = function(Service, Characteristic) {

    var that = this;
        var lightbulb = null;
        this.ignoreWorking = true;

    if (this.special=="PROGRAM") {

      lightbulb = new Service["Outlet"](this.name);
      lightbulb.getCharacteristic(Characteristic.OutletInUse)
                .on('get', function(callback) {
                if (callback) callback(null,1);
        }.bind(this));



    this.services.push(lightbulb);
    var cc = lightbulb.getCharacteristic(Characteristic.On)

    .on('get', function(callback) {
      if (callback) callback(null,0);
     }.bind(this))

    .on('set', function(value, callback) {
      if (value==1) {

        that.log("Launch Program " + that.adress);
        that.command("sendregacommand","","var x=dom.GetObject(\""+that.adress+"\");if (x) {x.ProgramExecute();}",function() {

        });

        setTimeout(function() {
                cc.setValue(0, null);

        },1000);

      }
      callback(0);

    }.bind(this));



    } else {

    if (this.special=="OUTLET") {

      lightbulb = new Service["Outlet"](this.name);
      lightbulb.getCharacteristic(Characteristic.OutletInUse)
      .on('get', function(callback) {
        if (callback) callback(null,1);
      }.bind(this));

    } else {
        lightbulb = new Service["Switch"](this.name);
    }

    this.services.push(lightbulb);

    var cc = lightbulb.getCharacteristic(Characteristic.On)

    .on('get', function(callback) {
      that.query("STATE",function(value){
               if (callback) callback(null,value);
      });
    }.bind(this))

    .on('set', function(value, callback) {
if (that.readOnly==false) {
      var onTime = that.state['ON_TIME'];
          if ((onTime!=undefined) && (onTime>0) && (value==1)) {
                  that.command("set","ON_TIME" , onTime)
          }
          if (value==0) {
                  that.delayed("set","STATE" , false)
          } else {
                  that.delayed("set","STATE" , true)
          }
}
      callback();
    }.bind(this));


    var onTimeProperties = {
           format: Characteristic.Formats.FLOAT,
           unit: Characteristic.Units.SECONDS,
           minValue: 0,
           maxValue: 3600.0, // normally defined as 85825945.6 but that`s in Hesperus inconvenient and unusable
           minStep: 1,
           perms: [Characteristic.Perms.WRITE]
         };

       var on_time = new Characteristic("OnTime","CEA288AC-EAC5-447A-A2DD-D684E4517440", onTimeProperties)
           .on('set', function(value, callback) {
             that.state['ON_TIME']=value;
             callback();
           }.bind(this));

         on_time.eventEnabled = true;

         lightbulb.addCharacteristic(on_time);

        this.remoteGetValue("STATE");

    }

    that.currentStateCharacteristic["STATE"] = cc;
 cc.eventEnabled = true;

}



module.exports = HomeMaticHomeKitSwitchServiceAsSwitch;

**Comment by Omega236** [comment]
Naja da muss ich wohl wenn ich zeit habe mir die mit der änderungen mit #220 anschauen und verstehen was sich verändert hat :(

**Comment by thkl** [comment]
*zeigt auf 0.0.104

**Comment by Omega236** [comment]
@thkl 
Super Danke hat funktioniert. 0.0.104 läuft wieder und die Einstellungen in Home sind auch nicht verloren. Danke
