### ISSUE TITLE
HmIP-BBL Positionierung funktioniert nicht

### ISSUE THREAD

**Issue by jhk3** [thkl/homebridge-homematic#225]
Die Höhe der Jalousien (bei mir Raffstore-Außenjalousien) lässt sich nicht einstellen (Homematic Plugin Version 0.0.104 ), weder per Siri mit "Setze Jalousie auf 30%", noch über die Slider in der Home-App (diese erscheinen, wenn man die Berührung der Schaltfläche in "Home" aufrecht erhält). Das war mit Version 0.98 des Plugins besser, obgleich es auch da (zumindest über die Slider) nicht immer richtig funktioniert hat. Aktuell führt der Befehl "auf 50%" zum Schließen, wenn die Jalousie offen war. Wenn sie geschlossen war, passiert nichts.

**Comment by thkl** [comment]
ist das besser in 0.0.106 ?

**Comment by jhk3** [comment]
Ja, deutlich besser. Die Positionierung der Jalusienhöhe funktioniert mit Siri jetzt sehr gut. Öffnen und Schließen per Berührung der Schaltfläche in "Home" funktioniert auch wieder, wobei ich bei aufeinanderfolgenden Berührungen keine Verzögerungen mehr sehe. 

Verstellen der Lamellenwinkel der Jalousien funktioniert noch nicht.

**Comment by nicoh88** [comment]
@thkl Die Änderung ist dann nur für `HomeMaticHomeKitBlindSlatServiceIP.js`? Weil es wäre cool, wenn "Setze Jalousie auf 30%" / "Setze Rollladen auf 30%" auch für meine HmIP-FROLL funktionieren würde. Wäre dann `HomeMaticHomeKitBlindServiceIP.js` oder?

DANKE

**Comment by jhk3** [comment]
Für meine Rollläden mit HmIP-BROLL hat das schon immer sehr gut funktioniert.

**Comment by nicoh88** [comment]
@jhk3: **Was echt?** Sagst du richtig "_Setze Rollo Terassentür auf 30%_" und das funktioniert oder Funktioniert nur _Rollladen_? Funktioniert bei dir auch "_Setze alle Rollläden auf 80%_"? Mit "_hochfahren_" und "_runterfahren_" ging es glaube ich nicht oder? Ich hatte da immer so meine Probleme, deswegen überrascht mich das jetzt sehr.

**Comment by jhk3** [comment]
Ja. Öffne (oder schließe) Rolladen nnnnn im Schlafzimmer. Öffne alle Rollläden im Schlafzimmer.  Setze alle Rollläden auf 35%. Funktioniert alles. Vorraussetzung ist, dass die Namen "Rolladen nnnn" in der Home-App oder in einer anderen App (z.B. Elgato Eve) die Homekit nutzt, richtig zugeordnet werden, d.h. man muss eindeutige Namen einmal für die Nutzung mit Siri in den Homekit-basierten Apps auf den iOS Geräten einrichten.

**Comment by thkl** [comment]
Muss ich hier noch irgend etwas tun, oder kann ich das muten ? Ich bekomm zu viele eMails ;)

**Comment by jhk3** [comment]
Verstellen der Lamellenwinkel der Jalousien funktioniert noch nicht.

Per Slider in der Home-App gibt es manchmal keine Reaktion und die Home-App geht in den "aktualisieren" Modus (so lange, bis man den Sprachbefehl absendet). Es ist nicht 100% konsistent, aber für meine Ansprüche und da es per Siri funktioniert ganz ok. Der Lamellenwinkel ist das offensichtlichere verbleibende Problem.
