### ISSUE TITLE
Dimmerstatus

### ISSUE THREAD

**Issue by bprskalo** [thkl/homebridge-homematic#231]
ein immer wieder diskutiertes Thema, ist aber leider aktuell wieder instabil, 

mit anderen Worten wird der Staus der Dimmer nicht richtig angezeigt ..

Das einzige was nutzt ist im HomeKitGenericService.js den this.usecache auf false zu stellen.

Irgendwie bin ich der Meinung, dass dies mal ohne Probleme lief :-) ..

**Comment by thkl** [comment]
Welches Device ? Die HmTypenbezeichnung bitte

**Comment by bprskalo** [comment]
HM-LC-Dim1T-FM und HM-LC-Dim1PWM-CV

Wenn ich einen der Dimmer via Home App einschalte ist der Staus richtig, also auf 100 %

Dann Home APP schliessen, via Taster ausschalten, Home APP öffnen - Status immer noch auf 100 %

**Comment by thkl** [comment]
ich hab mal ChannelServices/HomeMaticHomeKitDimmerService.js überarbeitet.
Das geht jetzt besser ...

**Comment by bprskalo** [comment]
bleibt es bei der 107 ;-) ?

**Comment by thkl** [comment]
ja es gibt noch kein neues npm ...

das könnte Travis eigentlich automatisch machen .. ich muss mal schauen wie ich das gescheit einstellen kann

**Comment by bprskalo** [comment]
habs nochmals geladen .. aber .. der effekt ist der gleiche .. sprich .. eine änderung bei beinem Setup .. und der besteht .. fas nur aus dimmern :-) ..

**Comment by thkl** [comment]
also ich  das live an einem dimmer getestet. Wenn die HomeApp offen ist, dann wird der der Status live aktualisiert wenn man die Lampe dimmt .. und wenn die App zu ist dann wenn man sie öffnet....

**Comment by bprskalo** [comment]
also ..

- ich öffne die home app
- Licht im Büro ist aus
- schalte den Dimmer im Büro via Home APP ein (=Stauts auf 100 %)
- schliesse die Home APP (auch aus dem Speicher entfernt)
- öffne die Home APP - Licht im Büro Status auf 0 obwohl es immer noch an ist ..

hab aber auch eben alles neu durchgestartet inkl RasberryMatic


Wie Eingangs beschrieben .. wenn ich den cache auf false stellt stimmt alles in jedem Zustand :-)

**Comment by thkl** [comment]
ok das kann ich nachvollziehen. Hab den Fehler auch gefunden. Hab mir da selber ein Bein gestellt

**Comment by bprskalo** [comment]
ja dann ich ich mal gespannt .. was dich ins stolpern gebracht hat ;-)

**Comment by thkl** [comment]
... Vererbung ....  🙀

**Comment by bprskalo** [comment]
hab mir mal die github version gezogen :-) ... mit der läufts so wie es sollte ;-) !!

**Comment by bprskalo** [comment]
aber so was von und verdient 😉!!

**Comment by bprskalo** [comment]
also .. hab grad intensiv getestet .. läuft prima .. kann in die NPM :-) 

bist mein Held !! DANKE !!!
