### ISSUE TITLE
wenn CCU nicht ready, keine Cache

### ISSUE THREAD

**Issue by krobipd** [thkl/homebridge-homematic#233]
Serwus

hab mit der aktuellen Version (108) festgestellt das wenn beim Booten die CCU noch nicht ready ist das kein Cache mehr genommen wird sondern einfach keinerlei Geräte vorhanden sind - somit wir alles aus HomeKit gelöst (homematic geräte) :-(

wenn die CCU dann läuft und man Homebridge Neustarten wird alles gefunden und funktioniert - man muss aber alles quasi neu einrichten in HomeKit.

> Mär 19 23:57:17 krobis-pi homebridge[532]: [2018-3-19 23:57:17] [HomeMatic CCU] Unable to parse live ccu data. Will try cache if there is one. If you want to know what, start homebridge in debug mode -> DEBUG=* homebridge -D
Mär 19 23:57:17 krobis-pi homebridge[532]: [2018-3-19 23:57:17] [HomeMatic CCU] JSON Error SyntaxError: Unexpected end of JSON input for Data
Mär 19 23:57:17 krobis-pi homebridge[532]: [2018-3-19 23:57:17] [HomeMatic CCU] Number of mapped devices : 0

**Comment by iuliusmaximilian** [comment]
Das Problem kann ich bestätigen, ich musste gestern 91 Geräte neu einrichten, umbenennen, Szenen neu hinzufügen usw. :-( Was die Ursache ist war mir nicht klar, aber es könnte durchaus damit zu tun haben, weil ich meinen Rasp gestern mehrmals neu gestartet habe und die CCU2 auch.

**Comment by iuliusmaximilian** [comment]
Schon wieder alles auf Standard :-(( Kann man das wieder herstellen ??

**Comment by thkl** [comment]
Schaut so aus, als ob der Cache nicht geladen werden konnte:
```

JSON Error SyntaxError: Unexpected end of JSON input for Data
```

Das File liegt in .homebridge/ccu.json ...
