### ISSUE TITLE
Unterscheidung der Icons für Switche in HomeKit möglich ?

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#236]
Hallo, ich habe an mehreren HM-LC-Sw4-DR teilweise Steckdosen, teilweise verschieden Typen von Lampen, teilweise Lüfter. Ich würde in HomeKit gerne das passende Icon je Schaltkanal angezeigt bekommen. Beim HM-LC-Sw4-DR Schaltkanälen kann ich aber keinen Typ wählen sondern für "SWITCH" nur die Lampen-Icons wählen. Bei einem Programm das ebenfalls als "SWITCH" gezeigt wird, kann ich aber den Typ wählen. Woran liegt das und kann man das ändern ?

**Comment by pbksol** [comment]
Guck Dir bitte den "OUTLET"-Bereich in der json.config an, damit kannst Du den Typ konfigurieren.

**Comment by iuliusmaximilian** [comment]
Es kann so einfach sein, funktioniert, Danke!
