### ISSUE TITLE
Feature request: Sperrung beachten

### ISSUE THREAD

**Issue by tkoenig** [thkl/homebridge-homematic#237]
Man kann ja in Homematic über Programme eine Sperrung  für Geräte aktivieren, sodass diese zumindest nicht mehr per Taster gesteuert werden können:
`dom.GetObject("BidCos-RF.XXXX:1.INHIBIT").Value()`

Gibt es eine Möglichkeit diese Sperrung für HomeKit Integration zu beachten?
Ich denke das würde durchaus Sinn machen:
Es gibt ja leider keine Unterscheidung zwischen Raffstore/Jalousien und Markisen.
Wenn ich jetzt Siri sage: "Mach die Jalousien zu/auf" steuert er mir deswegen natürlich auch die Markise, was ich natürlich nicht will - und schon gar nicht wenn es regnet oder stürmt.

Hier würde es Sinn machen, wenn man über ein Programm  bei Regen/Sturm die Sperrung aktiviert, dass diese Geräte dann nicht mehr über HomeKit steuerbar sind.

Gäbe es prinzipiell die Möglichkeit den INHIBIT Wert beim Senden einer Anfrage an die homematic Schnittstelle zu prüfen?

**Comment by pbksol** [comment]
HomeKit kennt keine Sperrung für Geräte, wenn ich das richtig erinnere. Das wäre die Voraussetzung um eine solche Funktion zu realisieren. Bei einer Sperre den Befehl einfach gar nicht zu senden halte ich darüber hinaus für einen Fehler, weil es keine Information an den Anwender gibt, dass sein Befehl nicht ausgeführt wurde.
Ja, man könnte jetzt die Aktoren "abklemmen" und solche Geräte mit "keine Antwort" anzeigen, aber das ist noch abwegiger…

Aber… Die Markise befindet sich gewöhnlich nicht im gleichen Raum wie die Jalousien. Erstere befinden sich außen im Garten, der Terrasse oder dem Balkon, letztere in Wohnzimmer, etc.
Zum einen versteht Siri das Kommando "Jalousien im Obergerschoss auf 0%" oder "Jalousien im Wohnzimmer auf 20%" und zum anderen ist neben einer Sperrung auch die Möglichkeit vorhanden, die ungewünschten Schaltvorgänge mit einem Programm abzufangen. Im Falle der Markise wäre es also einfach möglich den Aktor sofort wieder abzuschalten wenn außerhalb einer erlaubten Kondition eine Bewegung erfolgen soll (bspw. ausgelöster Regensensor und dergleichen). Im optimalen Fall kommt es zu gar keiner Bewegung des Motors, im nicht so optimalen Fall fährt er ein paar Millimeter und dann wieder zurück. Ja, das ist nicht super-schön, aber praktikabel. Der Anwender erhält aber ein Feedback, denn das Gerät beginnt etwas zu tun und wird wieder zurückgesetzt.

Diese ganze Intelligenz zum abfangen von speziellen Zuständen, Verriegelungen etc. zwischen einzelnen Aktoren und dergleichen sind systembedingt in der CCU und deren Programmen besser aufgehoben als in HomeKit. Da stehen auch sehr viel mehr Möglichkeiten zur Verfügung.

Und es gibt sicher noch ein gefühltes Dutzend weiterer Lösungsansätze…

**Comment by thkl** [comment]
Ich sehe das genau so.
Es gibt in Homekit nichts , mit dem ich ein Accessory temporär sperren könnte. Und an dieser Stelle müsste diese Funktion ansetzen. Siri müsste das auch mitbekommen und dann idealerweise so in der Art: "Tut mir leid, ich kann die Rollos nicht schließen, diese sind gesperrt" antworten.

In Homekit gibt es für Geräte meistens 2 Characteristiken : Current(State) und Target(State). Wenn ich jetzt einfach einen von Homekit kommenden Befehl ignoriere dann fehlen ja auch die Events von den Geräten, die States passen sich nicht an, und in HomeKit läuft ewig der Spinner.

Einzig, man könnte natürlich den TargetState im Fall einer Sperrung wieder zurücksetzen und den Befehl einfach ignorieren. Aber dann ist das Siri Feedback wieder falsch ...

**Comment by mach1009** [comment]
Das ist schade. Ich habe just dasselbe Problem. Habe meine Markise (Rolladenaktor) per Programm gesperrt, damit man sie bei Minustemperaturen nicht bedienen kann. Ganz erhlich wäre mir die Antwort von Siri egal, hauptsache meine Markise bleibt dort wo sie ist, wenn sie es soll. "Antwortet nicht" also so tun als ob das Geär tot ist, wäre vielleicht etwas näher an der Wahrheit dran.

**Comment by thkl** [comment]
Nunja, wie gesagt ich kann natürlich da Versenden von Kommandos an die CCU einfach unterdrücken, wenn INHIBIT gesetzt ist.  Daher die Frage: Was soll an dieser Stelle passieren. Event unterdrücken, Accessory antwortet nicht ? .....

**Comment by thkl** [comment]
Genau deswegen stelle ich das ja erstmal zur Diskussion.
Für die Rolladen Aktoren könnte man allerdings wenn der Inhibit gesetzt ist dieses nach Characteristic.ObstructionDetected weiterreichen ... man müsste mal testen wie sich HomeKit dann verhält. Das wäre ja dann sogar (im Falle des vereist / verschneiten Rollos) der richtige Datenpunkt

**Comment by tkoenig** [comment]
Finde den Ansatz mit ObstructionDetected eine gute Idee, und würde das auch testen!

Ich denke bei Tastern macht es durch aus Sinn die Aktoren sperren zu können (meine Kinder lieben es die Raffstore auf und zu zu machen....). Dort bekommt man auch kein Feedback und weiss im ersten Moment nicht warum es nicht geht - aber es zwingt einen ja niemand die Aktoren zu sperren? 
Wieso sollte sich das bei Homekit anders verhalten, ist ja im Prinzip diesbezüglich auch nur eine Fernbedienung. 

Aber wenn das mit dem ObstructionDetected funktioniert, wäre das natürlich super!
Ist es kompliziert den INHIBIT state abzufragen? Ich würde das gerne mal testen...

**Comment by thkl** [comment]
Naja dieser State sollte wie andere Datenpunkt events auch über die xmlrpc Schnittstelle ankommen. Die Klasse muss sich nur für diesen Event am Core registrieren und drauf reagieren.

**Comment by thkl** [comment]
@tkoenig  ich hab das mal in https://github.com/thkl/homebridge-homematic/blob/develop/ChannelServices/HomeMaticHomeKitBlindService.js versucht umzusetzen.

**Comment by mach1009** [comment]
Hey, das ging ja fix. 👍🏻
 Hatte noch nicht mal Zeit zu antworten. Werde das Morgen abend testen.

**Comment by tkoenig** [comment]
@thkl danke! 

Geht leider anscheinend noch nicht ganz...

Gerät erscheint in HomeKit mit "Antwortet nicht".

Unter Details steht: Blockade entdeckt: nein.

Im log bekomme ich folgendes mehrmals:

```
 Accessory [Homebridge] Got Characteristic "Obstruction Detected" value: undefined +1ms
  Accessory [Homebridge] Error getting value for Characteristic "Obstruction Detected": undefined +0ms

```

Das `undefined` erscheint mir komisch, sollte doch entweder true oder false sein, oder?

**Comment by thkl** [comment]
hmm ich setze das initial auf false ... kannst Du mal bitte mit -D schauen was für Events in Homebridge ankommen wenn Du den Inhibit Parameter des Gerätes setzt ..  das wird im Log angezeigt

**Comment by tkoenig** [comment]
@thkl kann sein, dass der Obstruktion event 0 oder 1 erwartet anstatt true und false?

Also wenn HomeKit läuft und ich die Sperrung einschalte und ausschalte scheint das mit diesem code zu funktionieren:

```
  if (dp == "1:INHIBIT") {
      this.inhibit = newValue;
      this.obstruction.updateValue(newValue ? 1 : 0,null);
  }

```

Aber beim initialisieren hat er noch etwas Probleme, da komm ich noch nicht drauf....

**Comment by tkoenig** [comment]
Beim callback hätte ich den gleichen code, aber da bekomme ich dann folgendes:  

```
  this.obstruction = blind.getCharacteristic(Characteristic.ObstructionDetected)
    .on('get', function(callback) {
        that.log.debug('INHIBIT!!!', that.inhibit);
        callback(that.inhibit ? 1 : 0);
    }.bind(this))
    this.obstruction.eventEnabled = true;
```

```

 Accessory [Homebridge] Getting value for Characteristic "Obstruction Detected" +1ms
[3/23/2018, 9:04:16 AM] [HomeMatic CCU] INHIBIT!!! true
  Accessory [Homebridge] Got Characteristic "Obstruction Detected" value: undefined +2ms
  Accessory [Homebridge] Error getting value for Characteristic "Obstruction Detected": undefined +1ms
```

**Comment by thkl** [comment]
ja das kann sein, ich wusste bisher nicht was die CCU liefert ...deswegen die Frage oben nach dem Lo ... 

callback bei gettern ist nicht wie bei updateValue .... sondern callback(null,value) ...

**Comment by tkoenig** [comment]
genau so hab ichs gemacht, siehe #239. 
Jetzt geht das mal ganz gut soweit, werde noch weiter testen!

**Comment by tkoenig** [comment]
@thkl danke fürs update, sehe das geht mit true, false auch!

**Comment by thkl** [comment]
gut, ich mach das dann optional mit einem Parameter in der config.json .. , wenn gilt das dann für alle Geräte des Services oder für keins ... (wenn man es nicht explizit aktiviert, verhält sich der Service wie vorher)

**Comment by tkoenig** [comment]
@thkl perfekt! Danke

**Comment by thkl** [comment]
Die aktuelle Version benötigt wie oben beschrieben einen Eintrag in der Config.json damit das Feature eingeschalten wird:

```
"HM-LC-Bl1-SM:BLIND":{"observeInhibit":true}
```

Wobei der Teil vor dem : der Typenbezeichnung des Rollandeaktors entspricht.
Für diesen wird das dann aktiviert.

Die IP Geräte haben soweit ich jetzt die Doku gelesen habe keinen INHIBIT Datenpunkt

**Comment by tkoenig** [comment]
IP Geräte habe ich leider auch keine zum testen...

Habe jedenfalls gerade master ausgechecked und es funktionier soweit alles (aktiv/inaktiv setzen) - auch ohne config! 👍 
Ein und ausfahren habe ich mit master noch nicht getestet (es regnet und ist dunkel), 
aber im develop branch hat das funktioniert.

**Comment by tkoenig** [comment]
Oh - hab nicht gesehen, dass im develop branch noch neuer code ist... 
Im master ist jetzt jedenfalls der code der ohne config funktioniert...
Soll ich das auch noch testen oder kommt das sowieso in master?

**Comment by thkl** [comment]
Der Master hat noch nicht die Version wo es die Config Einstellungen braucht.

**Comment by mach1009** [comment]
Bei mir funktioniert es auch soweit (master). Sperre wir korrekt geholt und beim Bedienen wird der Status immer wieder zurückgesetzt. Hab vielen Dank!
