### ISSUE TITLE
Syntax Error beim homebridge start seit Version 0.0.98

### ISSUE THREAD

**Issue by Seb0815** [thkl/homebridge-homematic#238]
Ich habe mein Homebridge-homematic plugin auf die neuste Version geupdatet und seit dem bekomme ich beim Start mit dem Modul einen Syntax Error "missing ) after argument list" in HomeMaticHomeKitThermometerService.js Line 47 (siehe Anhang). Für mich sieht der Code erst mal gut aus, aber trotzdem will keine Version >0.0.97 mehr laufen. Jemand eine Idee womit das zusammen hängt?

Ich nutzte homebridge im Docker auf einem Synology NAS. 
- Homebridge version is v0.4.38
- Node.js is version 9.8
![syntax error](https://user-images.githubusercontent.com/16491023/37780252-a6a52862-2dee-11e8-9595-8e5a2dd5419d.JPG)

**Comment by thkl** [comment]
Wenn Du das File in Deiner Fehlermeldung gegen https://raw.githubusercontent.com/thkl/homebridge-homematic/master/ChannelServices/HomeMaticHomeKitThermometerService.js austauschst, geht es wieder.
