### ISSUE TITLE
KeyMatic lässt sich nicht "öffen" , nur Speeren und entspeeren.

### ISSUE THREAD

**Issue by Bettarg** [thkl/homebridge-homematic#24]
Hallo, 

Ich habe ein Problem mit der Einbindung der KeyMatic. Die taucht zwar ohne Probleme in Apple Home auf, ich kann auch zu und aufschließen. 
Aber ich kann keine Öffnen Befehl geben. 

Wenn ich also draußen stehe, die Türe abgeschlossen ist, kann sie zwar aufschließen, aber auf geht sie nicht. 

Ist das Problem verständlich ? :-)

**Comment by JensBonse** [comment]
Ja, ist verständlich ;)

Du kannst per Siri die Türe nur aufschließen oder abschließen. Öffnen kannst du die Türe nicht direkt mit Siri. Dazu musst du dir eine Szene anlegen die das übernimmt.
Mit den HomeKit Apps wie z.B. EVE kannst du die Türe auch öffnen. Da ist unter 'Ungesichert / Gesichert' eine Zeile wo 'Tür' steht und 'Geschlossen'. Wenn du auf das geschlossen klickst kann du 'Geöffnet' auswählen und die Türe öffnet sich.

**Comment by leonsio** [comment]
Hmm habe zwar grad nicht laufen aber bei mir gings
du musst in EVE Keymatic als "Tür" (Typ Tür muss extra aktiviert werden) definieren, dann kannst du die mit "Wohnungstür öffnen" aufmachen
werde es bei Gelegenheit nochmal reaktivieren und testen

**Comment by Bettarg** [comment]
Hallo, 

Ah ok, i see. Mit EVE geht es, mit der Home App (aktuell) nicht. Danke.

**Comment by thkl** [comment]
i will close this issue now
