### ISSUE TITLE
Fakegato-History für HM-CC-TC

### ISSUE THREAD

**Issue by DSchumacher2104** [thkl/homebridge-homematic#240]
Hallo Thomas!

Für das alte Thermostat HM-CC-TC werden nur Messwerte für die Temperatur angelegt, für die Luftfeuchtigkeit nicht. Dies müsste doch auch eigentlich möglich sein, oder? Zudem werden im Temperaturverlauf keine "richtigen" Messwerte eingetragen, sondern alle 10 Minuten 0,0 Grad.

Bei meinem neuen Thermostat HM-TC-IT-WM-W-EU werden Messwerte für Temperatur und Luftfeuchtigkeit und bei den Heizkörperreglern HM-CC-RT-DN werden Messwerte für die Temperatur alle 2 Minuten angelegt, funktioniert super!

Für die Kontaktsensoren HM-Sec-SCo und HM-Sec-SC-2 und den Drehgriffsensor HM-Sec-RHS werden überhaupt gar keine History-Anzeigen angelegt, vermutlich werden sie noch gar nicht unterstützt.

Soviel zu meinen bisherigen Erfahrungen, ich benutze die NPM-Version 0.109.

Vielen Dank für deine tolle Arbeit!

**Comment by nicoh88** [comment]
Funktioniert bei mir für:
`HomeMaticHomeKitMotionDetectorServiceIP.js`

Funktioniert bei mir nicht für:
```
HomeMaticHomeKitThermostatServiceIP.js
HomeMaticHomeKitWeatherStationServiceIP.js
```

**Comment by tkoenig** [comment]
Bei der WeatherStation werden auch extrem viele entries gespeichert, da der `datapointEvent` mehrmals (5?) aufgerufen wird und da jedesmal gespeichert wird?

Ausserdem kommt mit der Pfad komisch vor:

 `/var/lib/homebridge/ccu.json/rpi-smarthome_HmIP-RF.00185709ACB15D:1_persist.json`?
Diese Files kann ja gar nicht geben, da ccu.json ein file ist?

Bin gerade noch beim debuggen..., vielleicht komm ich ja noch auf etwas drauf.

**Comment by thkl** [comment]
Ich weiss  ( https://github.com/thkl/homebridge-homematic/commit/57b02f93bc2a57ed3a8e0d53301e2f6e7434b9e1 )  ist mir beim Testlauf aufgefallen ...

**Comment by tkoenig** [comment]
@thkl Gibt es einen Grund warum du den Timer von fakegato nicht benutzt? `disableTimer:true`

Der würde sich sonst anscheinend darum kümmern die Werte zu Mitteln, und man bräuchte sich nicht darum kümmern das so oft aufzurufen:
`Entries are internally averaged and sent every 10 minutes using the global fakegato timer.`

**Comment by thkl** [comment]
ich hatte glaube ich einen, aber den weiss ich nicht mehr 🤦🏻‍♀️

**Comment by Samfox2** [comment]
Funktioniert das eigentlich auch bei den Kontaktsensoren? Bei mir zumindest wird da keine Historie angezeigt.

**Comment by nicoh88** [comment]
https://github.com/thkl/homebridge-homematic/pull/250

**Comment by nicoh88** [comment]
@Samfox2 Welches Gerät ist bei dir ein "Kontaktsensor" / "Belegsensor"? Ein Tür-/Fensterkontakt?

**Comment by Samfox2** [comment]
Ich benutze HM-Sec-SCo

**Comment by nicoh88** [comment]
@Samfox2 Das geht in FakeGato (door), habe ich hinzugefügt und einen pull request bei @thkl ausgelöst, wenn er es merged. Dann sollte es mit der 0.0.110 gehen - bei mir lokal geht es schon. 👍

**Comment by Samfox2** [comment]
Ah, cool!

**Comment by Samfox2** [comment]
@nicoh88 grad mal getrstet, also der loggingservice scheint da zu sein, da nun in eve das Diagramm erscheint. Leider ist es leer, d.h. es sind keinerlei „Messwerte“ zu sehen. Zur Info: ich verwende einen Kontaktsensor, jedoch in der Home-App als „door“ konfiguriert. Kann es sein, dass es da einen Unterschied gibt?
