### ISSUE TITLE
Homematic run with Docker on Synology till Version @106

### ISSUE THREAD

**Issue by franzel61** [thkl/homebridge-homematic#247]
in my environment run the homematic plug-in under Docker on my Synology. After update from, 0.0.98 to the lastest version 0.0.109  the initialization failed after the message "PONG is PONG CCU alive". what can I try to update to the latest version.... any setup change?

**Comment by thkl** [comment]
are there any other log messages , like errors or so ...

**Comment by franzel61** [comment]
Hallo Thomas,

Ich habe folgendes fotografiert





Mit freundlichen Gruessen / Best regards 

Franzel

**Comment by thkl** [comment]
Ähm ?

**Comment by franzel61** [comment]
Ich kann den Fehler reproduzieren, wo finde ich anschliessend die Logdateien?

Mit freundlichen Gruessen / Best regards

**Comment by thkl** [comment]
also normal in /var/log

**Comment by franzel61** [comment]
Hier das Log file nach dem Update von 106 (ok) nach 109 (Fehler)
[Homebridge-homematic 109.pdf](https://github.com/thkl/homebridge-homematic/files/1864779/Homebridge-homematic.109.pdf)

**Comment by thkl** [comment]
mal bitte das file HomeMaticHomeKitThermometerService.js  in /homebridge/node_modules/homebridge-homematic/ChannelServices/ gegen das hier https://raw.githubusercontent.com/thkl/homebridge-homematic/master/ChannelServices/HomeMaticHomeKitThermometerService.js tauschen.

**Comment by franzel61** [comment]
Sieht gut aus... Initialisierung läuft durch 

Super Dank für die schnelle Hilfe & ein gutes Osterfest
Franzel

Mit freundlichen Gruessen / Best regards 
Franzel Rudison
