### ISSUE TITLE
Fehler beim autostart von Homebridge (systemd)

### ISSUE THREAD

**Issue by setje** [thkl/homebridge-homematic#25]
Hallo zusammen,
ich habe den Autostart der Homebdirge am Raspberry Pi 2 gemäß Anleitung gemacht. Wenn ich den Start mitlogge, sehe ich beim Start, dass das homebridge-homematic Plugin einen Fehler produziert und homebridge somit nicht startet.

Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] Loaded plugin: homebridge-homematic
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] Registering platform 'homebridge-homematic.HomeMatic'
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] ---
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] Loaded config.json with 0 accessories and 1 platforms.
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] ---
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] Loading 1 platforms...
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] [HomeMatic CCU] Initializing HomeMatic platform...
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] [HomeMatic CCU] Homematic Plugin Version 0.0.31
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
Aug 16 20:01:35 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
Aug 16 20:01:36 raspberrypi homebridge[2997]: [8/16/2016, 8:01:35 PM] [HomeMatic CCU] init RPC
Aug 16 20:01:36 raspberrypi homebridge[2997]: [8/16/2016, 8:01:36 PM] [HomeMatic CCU] Local IP: 192.168.1.76
Aug 16 20:01:36 raspberrypi homebridge[2997]: [8/16/2016, 8:01:36 PM] [HomeMatic CCU] XML-RPC server for interface BidCos-RF.is listening on port 9090
Aug 16 20:01:36 raspberrypi homebridge[2997]: [8/16/2016, 8:01:36 PM] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
Aug 16 20:01:36 raspberrypi homebridge[2997]: [8/16/2016, 8:01:36 PM] [HomeMatic CCU] CCU RPC Init Call on port 2001 for interface BidCos-RF.
Aug 16 20:01:36 raspberrypi homebridge[2997]: [8/16/2016, 8:01:36 PM] [HomeMatic CCU] Fetching Homematic devices...
Aug 16 20:01:40 raspberrypi homebridge[2997]: [8/16/2016, 8:01:40 PM] [HomeMatic CCU] NPM 0.0.31 vs Local 0.0.31
Aug 16 20:02:36 raspberrypi homebridge[2997]: [8/16/2016, 8:02:36 PM] [HomeMatic CCU] timeout while executing rega script
Aug 16 20:02:36 raspberrypi homebridge[2997]: fs.js:549
Aug 16 20:02:36 raspberrypi homebridge[2997]: return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
Aug 16 20:02:36 raspberrypi homebridge[2997]: ^
Aug 16 20:02:36 raspberrypi homebridge[2997]: Error: ENOENT: no such file or directory, open './.homebridge/ccu.json'
Aug 16 20:02:36 raspberrypi homebridge[2997]: at Error (native)
Aug 16 20:02:36 raspberrypi homebridge[2997]: at Object.fs.openSync (fs.js:549:18)
Aug 16 20:02:36 raspberrypi homebridge[2997]: at Object.fs.readFileSync (fs.js:397:15)
Aug 16 20:02:36 raspberrypi homebridge[2997]: at /usr/local/lib/node_modules/homebridge-homematic/index.js:172:17
Aug 16 20:02:36 raspberrypi homebridge[2997]: at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:55:9)
Aug 16 20:02:36 raspberrypi homebridge[2997]: at emitNone (events.js:67:13)
Aug 16 20:02:36 raspberrypi homebridge[2997]: at ClientRequest.emit (events.js:166:7)
Aug 16 20:02:36 raspberrypi homebridge[2997]: at Socket.emitTimeout (_http_client.js:534:10)
Aug 16 20:02:36 raspberrypi homebridge[2997]: at Socket.g (events.js:260:16)
Aug 16 20:02:36 raspberrypi homebridge[2997]: at emitNone (events.js:67:13)
Aug 16 20:02:36 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Aug 16 20:02:36 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

Wo liegt hier der Fehler? Scheinbar gibt es die Datei ccu.json im Ordner /home/pi/.homebridge nicht. Aber auch wenn ich die Datei per Hand erstelle (ohne Inhalt), ändert sich der Fehler nicht.

**Comment by thkl** [comment]
Oops ok Fehler liegt an einem 'neuen Feature'. Das Plugin lädt wenn es keine Daten von der CCU bekommt zwischengespeicherte Daten . Wenn das File aber noch nie existiert Crash es.

Ich habe das in der index.js gefixt ...sollte jetzt gehen ..

**Comment by setje** [comment]
Probiere ich gleich aus. Muss ich das plugin nochmal installieren per `npm install -g homebridge-homematic`, oder kann ich die index.js irgendwo austauschen? Wenn ja, wo liegt die Datei?

**Comment by thkl** [comment]
nein das npm ist noch nicht aktualisiert. Die Datei index.js muss getauscht werden. sie liegt hier /usr/local/lib/node_modules/homebridge-homematic/

**Comment by setje** [comment]
Der Fehler taucht nun nicht mehr auf, dafür kommt etwas anderes:

Aug 17 06:27:58 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:58 AM] [HomeMatic CCU] Homematic Plugin Version 0.0.31
Aug 17 06:27:58 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:58 AM] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
Aug 17 06:27:58 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:58 AM] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
Aug 17 06:27:58 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:58 AM] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
Aug 17 06:27:58 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:58 AM] [HomeMatic CCU] init RPC
Aug 17 06:27:58 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:58 AM] [HomeMatic CCU] Local IP: 192.168.1.76
Aug 17 06:27:58 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:58 AM] [HomeMatic CCU] XML-RPC server for interface BidCos-RF.is listening on port 9090
Aug 17 06:27:58 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:58 AM] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
Aug 17 06:27:58 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:58 AM] [HomeMatic CCU] CCU RPC Init Call on port 2001 for interface BidCos-RF.
Aug 17 06:27:59 rpi2_homematic homebridge[1341]: [8/17/2016, 6:27:59 AM] [HomeMatic CCU] Fetching Homematic devices...
Aug 17 06:28:03 rpi2_homematic homebridge[1341]: [8/17/2016, 6:28:03 AM] [HomeMatic CCU] NPM 0.0.31 vs Local 0.0.31
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: [8/17/2016, 6:28:59 AM] [HomeMatic CCU] timeout while executing rega script
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: /usr/local/lib/node_modules/homebridge-homematic/index.js:172
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: if (path.existsSync(localcache)) {
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: ^
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: TypeError: path.existsSync is not a function
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at /usr/local/lib/node_modules/homebridge-homematic/index.js:172:16
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:55:9)
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at emitNone (events.js:67:13)
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at ClientRequest.emit (events.js:166:7)
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at Socket.emitTimeout (_http_client.js:534:10)
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at Socket.g (events.js:260:16)
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at emitNone (events.js:67:13)
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at Socket.emit (events.js:166:7)
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at Socket._onTimeout (net.js:318:8)
Aug 17 06:28:59 rpi2_homematic homebridge[1341]: at _runOnTimeout (timers.js:512:11)
Aug 17 06:28:59 rpi2_homematic systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Aug 17 06:28:59 rpi2_homematic systemd[1]: Unit homebridge.service entered failed state.

**Comment by thkl** [comment]
Es ist noch zu früh ;)
Jetzt aber.... Sorry !

**Comment by setje** [comment]
Kein Problem, ich bin ja froh, dass es so ein Plugin überhaupt gibt.
Jetzt kommt der Fehler nicht mehr und homebridge startet, jedoch bleibt der Fehler:
`rpi2_homematic homebridge[1520]: [8/17/2016, 6:40:26 AM] [HomeMatic CCU] timeout while executing rega script`

**Comment by thkl** [comment]
Dann stimmt die IP der CCU nicht bzw die CCU ist unter dieser IP nicht erreichbar

**Comment by setje** [comment]
Du hast vollkommen recht! Scheint auch für mich zu früh :-) Den Fehler hätte ich hinter der Fehlermeldung aber auch im Wachzustand nicht interpretiert. Danke dir!

**Comment by setje** [comment]
Jetzt habe ich nur noch das Problem, dass homebridge offenbar nicht sauber beim booten startet. Ich finde die Geräte  unter der Home App in der iOS 10 beta erst, nachdem ich nochmal homebridge neu starte mit `sudo systemctl restart homebridge`.

**Comment by thkl** [comment]
Ist das ne richtige CCU oder eine Virtuelle auf dem gleichen PI ?

**Comment by setje** [comment]
Eine virtuelle (YAHM) auf dem gleichen Pi.

**Comment by thkl** [comment]
Ah, da liegt der Hase im Pfeffer. Rega der virtuellen CCU ist in dem Falle noch nicht gestartet aber die Bridge schon.
Bitte mal in /etc/init.d/ den Inhalt von homebridge   durch das hier ersetzen : https://github.com/thkl/homebridge/blob/xmlrpc/homebridge_local

Da ist eine Abfrage drin ob Rega schon lebt und erst dann startet die Bridge

**Comment by setje** [comment]
Okay, das klingt nach einer Ursache, allerdings habe ich den autostart per systemd (Raspbian Jessie) gelöst anstelle per init.d , daher gibt es zu homebridge nichts in dem Verzeichnis.

**Comment by thkl** [comment]
Dann müsstest Du das so anpassen das vorher auf den Prozess ReGaHss gewartet wird.

ich lös das so : 

until pids=$(pidof ReGaHss)
        do   
          sleep 1
        done


Wenn der da ist, dann antwortet die CCU auch auf die Abfrage der Geräte ...

**Comment by setje** [comment]
sorry dass ich fragen muss, aber in der Datei "homebridge.service" ? Die liegt in /etc/systemd/system und hat folgenden Inhalt:

`
[Unit]
Description=Node.js HomeKit Server
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge_user
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target`

**Comment by thkl** [comment]
naja dann musst du das sicher ExecStart entsprechend umbiegen auf ein Script was vorher wartet

**Comment by setje** [comment]
Das ExecStart verweist ja auf eine Datei, wo angegeben ist, wo sich homebridge befindet.
Ich habe das nun entsprechend mit deinen Angaben ergänzt. 

`# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)

until pids=$(pidof ReGaHss)
do

HOMEBRIDGE_OPTS=-U /var/homebridge

sleep 1
done

# If you uncomment the following line, homebridge will log more
# You can display this via systemd's journalctl: journalctl -f -u homebridge
# DEBUG=*`

... scheint aber nicht richtig zu sein. Leider übersteigt das aber meine Kenntnisse, wie ich das richtig anstellen kann.

**Comment by setje** [comment]
Danke dir! Bis später dann

**Comment by thkl** [comment]
So  folgende Vorgehensweise .. 
Anlegen des systemd Services wie hier ( https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a ) beschrieben.

In der Datei /etc/systemd/system/homebridge.service die Zeile 

ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS anpassen:

ExecStart=/usr/local/bin/homebridge_yahm $HOMEBRIDGE_OPTS


Dann nach /usr/local/bin wechseln und eine Datei namens homebridge_yahm anlegen (touch homebridge_yahm )
Diese ausführbar machen (chmod +x homebridge_yahm)

Folgender Inhalt:

#!/bin/sh
### WAIT FOR REGA AND THEN LAUNCH HB
echo "Wait for Rega ... zzzZZZ"
until pids=$(pidof ReGaHss)
do   
  sleep 1
done
echo "Rega is here ok for launch"
homebridge $1

Dann sollte es gehen ....

**Comment by setje** [comment]
Danke, scheinbar gibt es dann aber ein Problem bzgl. der Benutzerrechte.

> Aug 18 06:28:43 rpi2_homematic homebridge_yahm[2292]: throw err0;
Aug 18 06:28:43 rpi2_homematic homebridge_yahm[2292]: ^
Aug 18 06:28:43 rpi2_homematic homebridge_yahm[2292]: Error: EACCES: permission denied, mkdir '/home/homebridge_user'
Aug 18 06:28:43 rpi2_homematic homebridge_yahm[2292]: at Error (native)
Aug 18 06:28:43 rpi2_homematic homebridge_yahm[2292]: at Object.fs.mkdirSync (fs.js:799:18)

Ich versuche die Abläufe gerade selber nachzuvollziehen. Die Originaldatei "homebridge" unter /usr/local/bin/ sieht im Übrigen so aus:

> 
#!/usr/bin/env node

//
// This executable sets up the environment and runs the HomeBridge CLI.
//

'use strict';

process.title = 'homebridge';

// Find the HomeBridge lib
var path = require('path');
var fs = require('fs');
var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');

// Run HomeBridge
require(lib + '/cli')();
