### ISSUE TITLE
HM-Sec-SCo fakegato history “leer“

### ISSUE THREAD

**Issue by Samfox2** [thkl/homebridge-homematic#252]
Ich benutze Kontaktsensoren (Typ HM-Sec-SCo) zur Tür/Fensterüberwachung. Mit commit #250 wird bei mir nun das Diagramm in der Eve App angezeigt, jedoch werden keine Werte geloggt. Kann das jemand nachstellen?

**Comment by nicoh88** [comment]
Hi @Samfox2,

hast du den Kontaktsensor in der config.json als „door“ / „window“ konfiguriert?

Gruß Nico

**Comment by Samfox2** [comment]
Nein, das hab ich nur in der Home-App auf door gestellt.

**Comment by nicoh88** [comment]
Hi, ich habe gerade für **ContactService** / **SensorService** noch [ein DatapointEvent hinzugefügt](https://github.com/thkl/homebridge-homematic/commit/f0191633339b727a8faad0139a93c6a7f8e364b7), damit wird eine Statusänderung sofort in die `..._persist.json`gespeichert. 👍 

Löst leider nicht @Samfox2 sein Problem, ich habe auch dieses Problem! Das Diagramm in Eve ist einfach leer. Die Daten bzw. Änderungen des Status sind aber in dem JSON-File gespeichert und erfolgreich mitprotokolliert worden. 

Eigenartig. Ich glaube nicht, dass es am Homebridge-Plugin liegt. Vermutlich ehr an der [Eve-App](https://itunes.apple.com/de/app/elgato-eve/id917695792?mt=8) oder ein Problem in [FakeGato](https://github.com/simont77/fakegato-history).

@thkl: Siehst du noch einen Fehler?

Gruß Nico

**Comment by Samfox2** [comment]
Liegt anscheinend wirklich an den 2 zusätzlichen Characteristics

https://github.com/simont77/fakegato-history/issues/29

**Comment by thkl** [comment]
Oh , ok probier ich mal aus

**Comment by thkl** [comment]
Wir kommen der Sache näher:
![Image](https://i.imgur.com/uohTcVY.jpg)

**Comment by Samfox2** [comment]
Yeah!

**Comment by thkl** [comment]
Ist leider nicht so einfach. Aktuell wird zwar die TimeOpened fleissig aktualisiert, aber der Graph unten nicht ... #sad

**Comment by Samfox2** [comment]
Wie alt sind denn die fakegato Quellen? Du hast die doch direkt reinkopiert, die waren anfangs noch buggy.

**Comment by thkl** [comment]
Ich muss mal sehen was ich da drin geändert habe. Dann referenziere ich das Original npm

**Comment by Samfox2** [comment]
Ok, die zusätzlichen Eve-Characteristics müssen dem History-Service hinzugefügt werden, nicht dem Contact-Service. Dann (könnte) es funktionieren :-)

**Comment by thkl** [comment]
Ja, ich bau sowieso gerade wieder alles um 🤦🏻‍♀️

**Comment by Samfox2** [comment]
Ich glaub die 118 und 119 müssen an den History Service, dass hatte ich mal irgendwo gelesen (vielleicht passt es ja auch nicht, kannst es ja trotzdem mal versuchen, wenn du nicht weiter kommst).

**Comment by thkl** [comment]
Hab ich gerade ausprobiert, bringt keine Änderung .. Die History für TimesOpened wird brav aktualisiert ... kann aber auch sein, das der diese Infos aus der FakeGato State History nimmt . Nur was wird da oben wo gerade No Data steht angezeigt .... hmm ...

**Comment by Samfox2** [comment]
Da oben wird in horizontalen Balken angezeigt, wie lange der Kontakt offen/geschlossen war. Da das bei hue funktioniert, muss das hier eigentlich auch gehen. Da muss irgendwo noch ein kleiner Unterschied sein

**Comment by thkl** [comment]
Hmmm die Zeiten speichere ich auch noch und sende sie an HomeKit wenn der Kontakt sich bewegt. Allerdings wird nur status ins Log geschrieben. Und daraus können ja auch die Zeiten ermittelt werden. 🤔

**Comment by Samfox2** [comment]
Für die Anzeige ganz oben stehen ja die Characteristicen 118 und 119, da wird wohl das Problem liegen. Du kannst das ja nochmal einchecken, dann schau ich auch noch mal

**Comment by thkl** [comment]
Der ganze Kram liegt hier https://github.com/thkl/homebridge-homematic/tree/contact-service

Wichtig : Keinesfalls als produktive Version nutzen, da ich einiges umgebaut habe und noch nicht alle Services angepasst habe. Die nötigen Characteristicen werden im File HomeMaticHomeKitContactService.js erzeugt und dem History Service ( this.addLoggingCharacteristic ) bzw dem Contact Service ( this.contact.addOptionalCharacteristic ) zugeordnet

**Comment by thkl** [comment]
Ich hab mal das Originale Fakegato Modul eingebunden. Ich weiss jetzt was damals nicht ging. Der Filename hatte Leerzeichen. Aber aktuell kann man den dem Service mitgeben. ... dann muss ich nix mehr an dem Modul umbauen ...

Geht trotzdem noch nicht richtig ;-/

**Comment by thkl** [comment]
Naja eigentlich kann das alles aus der State History gelesen werden. Da gibt es ja einen Timestamp wann der Kontakt auf und wann zu geht ..

**Comment by Samfox2** [comment]
@thkl Erfolg! Ich hab meine Änderung aus Zeitmangel ganz hart eingegcheckt, bitte mach das mal sauber - sorry.
Im Großen und Ganzen hab ich die Reset-Characteristic an den Logging Service gehangen und die zusätzl. Characteristics (tampered und battery) entfernt, k.A. ob letzteres notwendig war. Dann funktioniert es :-)

**Comment by thkl** [comment]
Ach ja. Eve wertet Batterie und Sabo natürlich aus und zeigt das auch an. 🤔

**Comment by Samfox2** [comment]
👍

**Comment by thkl** [comment]
Ich lass das jetzt so , oder ?

**Comment by Samfox2** [comment]
Ja super. Das mit der LastActivationTime schau ich mir irgendwann nochmal an

**Comment by thkl** [comment]
ich hab schon mal soviel rausbekommen, das irgend eine Zeit in der Vergangenheit als Referenz genommen wird. Es ist aber weder der Zeitpunkt des letzen Öffnens noch der des letzten Resets ...

**Comment by Samfox2** [comment]
Komisch, müsste eigentlich _seconds since last reset_ sein

**Comment by Samfox2** [comment]
Mal so ein Zwischenstand, das scheint sich wohl auf die _Initialtime_ zu beziehen. Die wird beim Hinzufügen des 1. Eintrags in die History gesetzt. Auslesbar über getInitialTime() des History-Services. Man müsste also z.B. _now-getInitialTime setzen_ (so die Theorie :-) ). Das klappt auch, nur wird das irgendwie nach dem Aktualisieren der Daten in der App umgesetzt.

**Comment by thkl** [comment]
Aha !

Na das Probier ich aus. Btw: für den Kontakt habe ich den FakeGato Timer aktiv.

**Comment by Samfox2** [comment]
Komisch, bei mir tauchen da teilwiese Lücken auf. Ich glaube ich werde die ganzen persistenten History-Sachen und die App nochmal runterschmeißen.

**Comment by thkl** [comment]
Whoop Whooop ! sehr gut .. LastOpen geht auch

**Comment by Samfox2** [comment]
👍

**Comment by Samfox2** [comment]
Dann mach ich hier mal zu und erwähne noch etwas Unangenehmes: die ganze Geschichte gibt es auch für den MotionSensor 😃

**Comment by thkl** [comment]
Ja, aber wo ich jetzt weiß wie der 🐰läuft ist das kein Problem.
