### ISSUE TITLE
Variable aktualisert spät bis gar nicht

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#253]
Ich habe ein Test-Programm das nichts anderes macht, als eine Systemvariable in der CCU2 von false auf true zu setzen. Nun dauert mitunter mehr als 20 Sekunden, bis diese in HomeKit aktualisiert wird. Manchmal aktualisiert sie auch gar nicht. Kann das Jemand nachvollziehen und hat das Problem Problem ?

**Comment by thkl** [comment]
Variablenänderungen werden nicht via Event von der CCU an eine externe Logicschicht gesendet.
Workaround ist die Nutzung eines Triggers. Auf der CCU muss ein Programm laufen, was beim Ändern der gewünschten Variable eine virtuelle Taste triggert. Diese muss in variable_update_trigger_channel in der config.json stehen.

Dann bekommt Homekit das zeitnah mit.

**Comment by iuliusmaximilian** [comment]
Danke, funktioniert!
