### ISSUE TITLE
HM - Heizungsmodule sind irgendwie unresponsive in der 0.1.0.9 Version

### ISSUE THREAD

**Issue by xxxchris** [thkl/homebridge-homematic#254]
Hi,
komme von 0.0.97 und hatte auf die aktuellste mit fakegato aktualisiert.
Seitdem wurde das Verschieben des Reglers zum Temperatur verändern teilweise immer zurückgesetzt bzw. nicht übernommen beim hoch oder runterrregeln. Außerdem springt der Regler wenn ich z.B. auf 22 Grad gehe wieder zurück auf 16 oder andere Werte. Ich muss den Regler dann mehrmals an die richtige Stelle ziehen, damit er dort bleibt. Wobei das auch nicht unbedingt Erfolg verspricht, denn wenn ich dann auf den Wert beim Gerät gucke, kann es sein, dass ein anderer Wert übertragen wurde, als der den ich eingestellt habe.
Ich hatte zuletzt immer die Wandthermostate ins HomeKit Gewerk genommen und bei den Räumen wo es keine gibt direkt den Stellantrieb.
Bin jetzt erstmal wieder zurück auf der 0.0.97

Mich würde auch noch interessieren, wie andere die Heizungen einbinden, es gibt ja auch die Möglichkeit eine Gruppe zu definieren und ins HomeKit Gewerk einzufügen (INTxxxx), allerdings hatte ich das mal gemacht und kann mich erinnern, dass zwar die Temperatureinstellung für die Gruppe übernommen wurde, die aktuelle Raumtemperatur aber nie aktualisiert wurde. Die Gruppe anzusprechen würde ich natürlich vorziehen.

Sind das noch aktuelle Bugs oder hab ich hier was falsch konfiguriert.

Schöne Grüße
und tolle Arbeit, die ihr hier macht!!!

**Comment by thkl** [comment]
https://github.com/thkl/homebridge-homematic/commit/3b31bc53244e90fcc864961f3de355b610468033

**Comment by xxxchris** [comment]
Hoffe... :-) 
Du willst bestimmt, dass ich das teste oder hat schon jemand?

**Comment by thkl** [comment]
Ich hatte das Verhalten bei einem Wand Thermostat auch ... jetzt nicht mehr ...

**Comment by xxxchris** [comment]
Ich weiß, wie ich ein Update auf ne bestimmte Version (npm update xy@1.0.0.0)  mache, aber wie krieg ich Änderungen, die noch keine Version haben?
Oder soll ich einfach die Änderungen bei mir lokal in der Datei machen?

**Comment by xxxchris** [comment]
Ich hab jetzt wieder die 1.0.9 installiert mit wie im Wiki beschrieben: "npm install homebridge-homematic@latest -g --unsafe-perm".
Allerdings sind da deine letzten Änderungen nicht drin. Im ChannelServices Verzeichnis bei mir fehlen auch einige Dateien. Ist mir aufgefallen als ich gerade versucht habe den HomeMaticHomeKitDoorBellVideoService einzurichten und im Debug sagt der Log, dass die Klasse nicht gefunden wurde. Ich wunder mich, warum ich die Dateien nicht ziehen kann.

**Comment by nicoh88** [comment]
Hi @xxxchris, es ist normal das diese Änderungen nicht im "latest" sind - da @thkl noch keine neue stabile Version auf NPM veröffentlich hat.

Mit `npm install homebridge-homematic@latest -g --unsafe-perm` holst du dir die letzte offizielle und stabile Version [per NPM](https://www.npmjs.com/package/homebridge-homematic) - aktuell 0.0.109, vom 20.03.2018.

Die Änderungen, die du testen möchtest (https://github.com/thkl/homebridge-homematic/commit/3b31bc53244e90fcc864961f3de355b610468033) sind aktuell nur im sehr experimentellen "develop" Branch vorhanden. Um diesen über NPM zu installieren, musst du `npm install homebridge-homematic#develop -g --unsafe-perm` ausführen.

Keine Garantie, dass dir nicht deine gesamte Homebridge-Installation um die Ohren fliegt. :wink:

**Comment by xxxchris** [comment]
Hab mir das schon gedacht und eben schon die ZIP downgeloadet und die Dateien rüberkopiert. Das schlimmste was passieren kann, ist das mir mal die ganzen Accessorys rausfliegen und ich mal wieder alles neu in HomeKit konfigurieren muss.
Auf deinen Tipp mit dem Befehl bekomme ich das:
`npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "homebridge-homematic#develop": Tags may not have any characters that encodeURIComponent encodes.
`

**Comment by nicoh88** [comment]
Mein Fehler:
`npm install thkl/homebridge-homematic#develop -g --unsafe-perm`

**Comment by xxxchris** [comment]
Danke.
Ohne sudo bekomme ich:
`Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-homematic'`

Mit sudo bekomme ich:
` Command failed: /usr/bin/git clone --depth=1 -q -b develop git://github.com/thkl/homebridge-homematic.git /root/.npm/_cacache/tmp/git-clone-7b8a50a8
npm ERR! /root/.npm/_cacache/tmp/git-clone-7b8a50a8/.git: Permission denied
`

**Comment by xxxchris** [comment]
@thkl Kann aber schon berichten, dass damit der Unresponsive-Bug gefixt zu sein scheint. Hoffe soweit war die Teststellung in Ordnung mit den manuell rübergeholten Dateien.

**Comment by thkl** [comment]
Dann mach ich das hier mal zu
