### ISSUE TITLE
Feature Request: Security device

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#255]
Hi, Glaube es ist eine Kleinigkeit, aber wäre es möglich ein Security device zu implementieren welches sich bspw. aus einer Variablen heraus den "Security" Status von der CCU2 holt. Man sieht das [hier](https://www.apple.com/de/ios/home/) auf einem der unteren Screenshots als Alarmlampe bzw. in der HomeKit Accessory Protocol Specification in "Chapter 9.11 Security System".

**Comment by thkl** [comment]
Das Security Device arbeitet mit mehreren Statis bzw auch als Schaltdevice.

<img width="766" alt="bildschirmfoto 2018-04-03 um 21 27 52" src="https://user-images.githubusercontent.com/884355/38271173-fdc0527a-3785-11e8-9982-96d277c6d7dd.png">

Die Variable müsste dazu aber einen Trigger auslösen, da Variablenänderungen in der CCU nicht als Event auf den Interface Schnittstellen ankommen.

**Comment by iuliusmaximilian** [comment]
Mh, ja das wäre sogar noch besser, aktuell habe ich Programme die zwei "Security" Variablen schalten, eine ob Überwachung scharf / deaktiviert ist und eine ob Alarm ausgelöst wurde oder nicht. In die Programme kann ich natürlich die Trigger rein hängen. Wie würde die config dazu aussehen hast du ein Beispiel ?

**Comment by thkl** [comment]
Der Trigger müsste eine Virtuelle Taste sein. Diese schickt übers Interface eine Notification.
Wenn ichs einbaue (wird noch dauern, aktuells Thema ist ContactSensor History), dann sicher so in der Art wie der Türgong oder das Garagentor ....

**Comment by thkl** [comment]
So geht ... siehe https://github.com/thkl/homebridge-homematic/wiki/Variable-basierendes-Security-System

Das Hilfsprogramm auf der CCU ist wichtig, aber das steht im Wiki ...

<img width="903" alt="bildschirmfoto 2018-04-08 um 20 29 46" src="https://user-images.githubusercontent.com/884355/38471093-a10920a8-3b6c-11e8-9f8b-4ef0025bdf3c.png">

**Comment by iuliusmaximilian** [comment]
Habs getestet, sieht super aus und funktioniert, sehr nett ist nebenbei dann auch die Push-Funktion wenn ein Alarm ausgelöst wurde. Kleine Anmerkung zur Dokumentation, da fehlt der Wert 3. Nochmals vielen Dank!

**Comment by iuliusmaximilian** [comment]
Vielleicht noch eine Anmerkung, schöner wäre den virtuellen Kanal für den Trigger auch per Name zu referenzieren.

**Comment by thkl** [comment]
Ja aber da wäre ein Roundtrip über Rega nötig. Das ist ja nur eine einmalige Einstellung.  Daher spare ich mir das.
