### ISSUE TITLE
HomeMaticHomeKitDoorBellVideoService flexible ffmpeg commandline

### ISSUE THREAD

**Issue by thkl** [thkl/homebridge-homematic#260]
customize ffmpg command line see #https://github.com/thkl/homebridge-homematic/issues/234#issuecomment-379007438

**Comment by xxxchris** [comment]
Ja, gute Idee. Hab die Änderung mal gemacht an der Datei hier. Bin vorher auf developer branch gegangen. Weiß jetzt nicht genau wo das entstanden ist, gibt jetzt plötzlich noch einen patch-1 branch unter meinem usernames.
Bin ehemaliger Rational Clear Case user. deswegen seht's mir nach, wenn ich hier vielleicht noch das falsche vorgehen im GitHub an den Tag lege.

**Comment by thkl** [comment]
ähm bei näherem hinsehen ist das doch alles schon custom ...

Beispiel wäre:

```
"parameter" : {
		"camera" : {
	        "name": "Front Door",
    			"videoConfig": {
				"source": "-re -i rtsp://url_to_rtsp_of_your_camera/livestream2",
    				"stillImageSource": "-i http://url_of_a_jpg_snapshot_from_ur_camera",
		    		"maxStreams": 2,
		    		"maxWidth": 640,
		    		"maxHeight": 480,
		    		"maxFPS": 30,
		    		"vcodec":"h264_omx",
		    		"packetsize":"1308"
				}
			.....

```

**Comment by xxxchris** [comment]
ohje, ich hab den Parameter mit bei der stillImagesource übergeben. und das führte dazu, dass gar kein livestream mehr kam. auf die einfache Idee, einfach die Parameter so wie die anderen zu übergeben bin ich nicht gekommen.. sorry. Brett vorm kopf. Probiere ich gleich aus.
Lehn meine Änderung an der ffmpeg.js einfach ab, wenn das geht.

**Comment by thkl** [comment]
Und ja , wenn Du einen Fork des Projektes machst, und was änderst erzeugt github dir einen Patch, den du dann optional als Pullrequest fürs originale Repo einwerfen kannst.
Automatisch wird aber hier nix geändert, wenn Du bei Dir was umbaust ...  ;o)

**Comment by xxxchris** [comment]
Danke fürs erklären. Habs ausprobiert wie du geschrieben hast. Funktioniert. Issue kann dann wohl wieder zu ... 😉

**Comment by thkl** [comment]
Ich hab mal die [WikiPage ](https://github.com/thkl/homebridge-homematic/wiki/Video-DoorBell) bezüglich der Parameter ergänzt
