### ISSUE TITLE
Keine Status-Aktualisierung mehr für HmIP-SMO bei mehreren Homebridge Instanzen

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#261]
Hallo, ich habe meine Homebridge von einer auf 5 Instanzen umgebaut. Funktioniert soweit alles gut. Allerdings aktualisieren seitdem meine 6 PIR den Status nicht mehr. In der CCU2 wird eine Bewegung erkannt, in HomeKit kommt das aber nicht an. Meine Konfiguration ist sehr einfach denn die PIR sind alle (nur) einem Gewerk "Homebridge4" zugeordnet. Name, Username, Port, PIN und local_port sind alle unterschiedlich je Homebridge Instanz. Im Debug Log kommt gar nichts an wenn der PIR auslöst. Woran kann das liegen?

```
{
        "bridge": {
                "name": "Homebridge4",
                "username": "XXX",
                "port": 51824,
                "pin": "YYY"
        },
        "description": "",
        "platforms": [{
                "platform": "HomeMatic",
                "name": "HomeMatic CCU2",
                "ccu_ip": "10.0.1.10",
                "local_ip": "10.0.1.99",
                "local_port": 9494,
                "filter_device": [],
                "filter_channel": [],
                "outlets": [],
                "valves": [],
                "doors": [],
                "windows": [],
                "programs": [],
                "variables": [],
                "variable_update_trigger_channel": "",
                "ios10": true,
                "enable_hmip": true,
                "enable_wired": true,
                "accessories": [],
                "subsection": "Homebridge4",
                "special": [],
                "services": []
        }]
}
```

**Comment by thkl** [comment]
Schau mal im Debug Modus ob folgende Log Einträge erscheinen:

```
[2018-4-7 12:00:27] [HomeMatic CCU] CCU Response for init at HmIP-RF. with http://192.168.178.30:9092...Value ("") Error : (null)
[2018-4-7 12:00:27] [HomeMatic CCU] CCU Response for init at BidCos-RF. with xmlrpc_bin://192.168.178.30:9090...Value ("") Error : (null)

```

Das ist das Ankoppeln an die Interfaces auf der CCU.  Value ("") und Error (null) sind normal.

**Comment by iuliusmaximilian** [comment]
Was ich gerade noch einmal verifiziert habe: Llasse ich nur die Homebridge4 Instanz laufen, ob im Debug oder nicht, funktioniert das Event Handling und der Status wird richtig aktualisiert. Starte ich danach aber eine weitere Homebridge Instanz funktioniert es nicht mehr.

**Comment by iuliusmaximilian** [comment]
Es hat irgendwie mit der Start-Reihenfolge zu tun. Ich habe mal mit einer weiteren Instanz probiert erst die 4er zu starten und dann die 2er Instanz. dann geht es nicht. Starte ich erst die 2er und dann die 4er, bekommt und verarbeitet die 4er das Event korrekt.

**Comment by iuliusmaximilian** [comment]
Temporär hat ein 
`ExecStartPre=/bin/sleep 60`
im "Homebridge4" Instanz Service ist ein workaround...

**Comment by thkl** [comment]
Angesichts der Tatsache das ein verzögerter Start der einzelnen Instanzen das Problem löst, gehe ich mal davon aus, das die CCU es nicht so toll findet, wenn 5 Inits auf einen Haufen kommen. 

Ich schließe das mal ...
