### ISSUE TITLE
Errors in CCU Systemlog

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#264]
Musste heute nach einen RASPI neustart folgendes im log feststellen..... woher kommt das ?

Apr  8 18:22:01 homematic-ccu2 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ1673xxx:2","ACTUAL_TEMPERATURE",22.500000}]}) on binary://192.168.0.18:9090/RPC2:
Apr  8 18:22:01 homematic-ccu2 user.err rfd: XmlRpc transport error
Apr  8 18:22:01 homematic-ccu2 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ1673xxx:2","ACTUAL_HUMIDITY",47.000000}]}) on binary://192.168.0.xx:9090/RPC2:
Apr  8 18:22:01 homematic-ccu2 user.err rfd: XmlRpc transport error
Apr  8 18:22:01 homematic-ccu2 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ1673xxx:2","SET_TEMPERATURE",4.500000}]}) on binary://192.168.0.xx:9090/RPC2:
Apr  8 18:22:01 homematic-ccu2 user.err rfd: XmlRpc transport error
Apr  8 18:22:21 homematic-ccu2 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ1673xxx:1","TEMPERATURE",22.600000}],[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ1673xxx:1","HUMIDITY",47}]}) on binary://192.16
Apr  8 18:22:21 homematic-ccu2 user.err rfd: XmlRpc transport error
Apr  8 18:23:00 homematic-ccu2 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ1671xxx:2","ACTUAL_TEMPERATURE",22.700000}],[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ1671xxx:2","ACTUAL_HUMIDITY",57.000000}]
Apr  8 18:23:00 homematic-ccu2 user.err rfd: XmlRpc transport error
Apr  8 18:23:13 homematic-ccu2 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ0425xxx:1","STATE",false}],[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ0425xxx:1","ERROR",0}],[methodName:"event",params:{"homeb
Apr  8 18:23:13 homematic-ccu2 user.err rfd: XmlRpc transport error
Apr  8 18:23:20 homematic-ccu2 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"homebridge_BidCos-RF.","OEQ1671xxx:1","TEMPERATURE",22.700000}]}) on binary://192.168.0.xx:9090/RPC2:
Apr  8 18:23:20 homematic-ccu2 user.err rfd: XmlRpc transport error

etc.....

lg richard

**Comment by thkl** [comment]
Wenn der CCU Rasp neu startet geht die Verbindung zur HB verloren.  Eigentlich sollte der Internet Watchdog das selber mitbekommen.  Ansonsten HB neu starten.

**Comment by roe1974** [comment]
habe homebridge neu gestartet .... nicht die CCU (die rennt siet 90 Tagen)

**Comment by thkl** [comment]
Achso. Das ist ähnlich. Ich bekomme nicht mit, wenn homebridg beendet wird. Daher kann ich die Logicschicht auch nicht an der CCU abmelden. 

Dasher gehen einige Events ins Nichts.  Die CCU killt aber nach einer Weile das Abo und sendet nix mehr an die tote Logicschicht.

**Comment by roe1974** [comment]
okeeeee :-)
