### ISSUE TITLE
Systemvariable Wert anzeugen

### ISSUE THREAD

**Issue by criticallimit** [thkl/homebridge-homematic#265]
Systematischen werden in der Homebridge als Schalter angezeigt. Gibt es eine Möglichkeit den Wert einer Systemvariablen anzeigen zu lassen? 
Also eine System variable nur als Anzeige zu benutzen? Du wie ein Temp oder Feuchtigkeit Sensor? Würde gerne Füllstandsanzeigen darstellen, habe aber keine Idee wie das mit Homebridge gehen kann. Benutze dazu einen umgebauten Temp Sensor, der nun aber Werte liefert, die ich umrechnen muss und in einer Systemvariablen in homematic darstelle. Dürre bekomm ich aber nicht in die Home App.

**Comment by thkl** [comment]
Ähm das wäre ein extrem hoher Aufwand, da für jede Variable ja unterschiedliche Geräte irgendwie in der Config eingestellt werden müssten.

**Comment by criticallimit** [comment]
Es wurde ja schon ein Gerät reichen welches nur den Wert anzeigt ;-)

**Comment by thkl** [comment]
Ja, aber es gibt kein HomeKit Device welches einfach nur einen Text anzeigt .. Das ist das Problem

**Comment by Samfox2** [comment]
Man könnte z.B. an ein _IrrigationSystem_ die _Characteristic.WaterLevel_ anhängen, dann hätte man den Wasserstand prozentual, wenn man draufklickt.

**Comment by thkl** [comment]
Ja natürlich , aber daher ja auch meine Anfangsantwort. Es müsste ja irgendwie generisch einzustellen sein.

**Comment by Samfox2** [comment]
Das würde das homematic plugin wahrscheinlich etwas überfrachten, aber @criticallimit den Wert/Text per Script abgreifen und per http plugin oder etwas Ähnlichem darstellen sollte funktionieren.

**Comment by jhk3** [comment]
Werden nicht auf manchen Kanälen Zahlenwerte übertragen (°C, Lux usw)? Man kann einer Variablen in der CCU einen Kanal zuweisen. Evtl. ist das ein Weg, Variablenwerte aus der CCU an Homekit zu senden.

**Comment by thkl** [comment]
Ja, aber diese Werte werden über Rega im WebUi angezeigt. Diese Daten laufen nicht über das Geräteinterface und erzeugen damit auch keine Events

**Comment by thkl** [comment]
@jhk3 @criticallimit man könnte einen eigenen Service für das Thema bauen ähnlich wie :  https://github.com/thkl/homebridge-homematic/blob/develop/ChannelServices/HomeMaticHomeKitAlarmSystemService.js  ( https://github.com/thkl/homebridge-homematic/wiki/Variable-basierendes-Security-System ) 

Allerdings gibt es soweit ich weiss, kein HomeKit Device was einen Füllstand abbildet .. Die Idee von @Samfox2 mit dem Waterlevel am Beregnungssystem würde gehen, schaut natürlich bissel blöd aus ...

**Comment by thkl** [comment]
siehe #267
