### ISSUE TITLE
Bibt es eine Möglichkeit den Baterie Zustand mit anzuzeigen?

### ISSUE THREAD

**Issue by MaxMan23** [thkl/homebridge-homematic#267]
Hallo Thomas,

danke erstmal für das tolle Addon, Funzt bei mir super :-).
Ich habe einen Roboter Mäher , wo ich in Homematic den Baterie Zustand sehen kann. Ich würde das gerne in Homebridge auch mit anzeigen. Es gibt ja in Homekit HMCharacteristicTypeBatteryLevel. Kann ich das irgendwie butzen?

**Comment by thkl** [comment]
Es gibt einen Batterie Service als HomeKit Gerät. Den könnte man, ähnlich wie das Variablen basierende Security System dafür verwenden. Der aktuelle Ladestand müsste in einer Variable gespeichert werden.

**Comment by iuliusmaximilian** [comment]
Das wäre genial, dann könnte man sogar #129 darüber abbilden.

**Comment by thkl** [comment]
siehe https://github.com/thkl/homebridge-homematic/wiki/Variablen-basierende-Batterie-Anzeige

iOS Home.app scheitert, Eve kann es anzeigen und gibt sogar bei niedrigem Akku eine Meldung aus.

**Comment by MaxMan23** [comment]
Müsstest du da was programmieren oder wäre das jetzt schon so möglich? (irgendein special oder custom serviceclasses)

**Comment by MaxMan23** [comment]
Super, vielen Dank. Werde es gleich mal ausprobieren :-)

**Comment by thkl** [comment]
Edit : In der Home App wird zwar die Variable als nicht unterstützt angezeigt. Aber wenn man auf Details tippt, zeigt er den % Wert an.

**Comment by iuliusmaximilian** [comment]
Anscheinend kann die HomeKit App. keine Battery Services visualisieren :-( in den Details wird aber immerhin wie o.g. dann die Variable angezeigt und per Programm bei mir aktualisiert ...

![screen](https://user-images.githubusercontent.com/28545473/38849606-2e20a654-420d-11e8-97df-f1ace3e5295f.png)

**Comment by thkl** [comment]
Siehe oben ...
Dieser Service scheint für das HomeKit Gerät an sich gedacht zu sein.
