### ISSUE TITLE
Feature Request: Faucets

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#268]
In #220 wurde bereits das IrrigationSystem Type für Sprinkler umgesetzt, toll wäre das gleiche für Faucets zu haben bzw. dass man der heutigen Config mitgeben könnte, um was es sich handelt. Ich habe eine Zikulatiosnpumpe und eine Frischwasserzufuhr die würde ich gerne als "Wasserhahn" darstellen würden anstelle der "Sprinkler" Icons.

**Comment by thkl** [comment]
In die config.json muss neben dem Valve Eintrag:

```
"HM_GERÄTETYPE:SWITCH": {
		    "types":{
			"BidCos-RF.balbalbalb:1":type
		    }
	    }
```

HM_GERÄTETYPE = bsp HM-LC-Sw2-FM 
BidCos-RF.balbalbalb:1 = Adresse des Kanals
Type = Icon Type: 

Characteristic.ValveType.GENERIC_VALVE = 0;
Characteristic.ValveType.IRRIGATION = 1;
Characteristic.ValveType.SHOWER_HEAD = 2;
Characteristic.ValveType.WATER_FAUCET = 3;

**Comment by iuliusmaximilian** [comment]
Super, funktioniert !!!

**Comment by iuliusmaximilian** [comment]
Nach intensivieren Konfiguration kleine Einschränkung, folgende Konfiguration 

```
...
                }],
                "HMW-IO-12-Sw14-DR:DIGITAL_OUTPUT": {
                        "types": { "BidCos-Wired.OEQ0129171:4": 3 }
                },
                "HM-LC-Sw4-DR-2:SWITCH": {
                        "types": { "BidCos-RF.OEQ0216786:4": 3 }
                }
        }]
...
```

Beide Valves werden korrekt registriert und sind im HomeKit verfügbar. Der IO-12-Sw14 hat allerdings einen falschen Anfangsstatus (aktiv) wenn die Homebridge neu gestartet wird. Dies ist aber nur so, wenn dieser hier mit Type registriert wird. Wird er "nur" als Valve konfiguriert ohne Type ist der Anfangsstatus korrekt. Bei dem Sw4-DR-2 ist alles korrekt.

**Comment by pat4020** [comment]
Hallo.

Ich schaffe es einfach nicht, dass ein HM-LC-Sw2-FM Kanal als "faucet" ausgegeben wird.
Wäre eventuell jemand bereit eine gesamte config.json zu posten ... ich habe den oben gegebenen Eintrag schon an diversten Stellen in der config versucht, jedoch wird das Gerät immer als Sprinkler ausgegeben.

Vielen Dank!

**Comment by roe1974** [comment]
Kann mir bitte wer den Teil der config.json genau posten ?
Kommt das hier geschreibene nach dem "valves" eintrag ?

lg Richard

**Comment by roe1974** [comment]
...und habe ich dann beim "GENERIC_VALVE" auch einen Timer ?
Wenn ja , wie kann man den deaktivieren ?

lg Richard
