### ISSUE TITLE
Duty Cycle

### ISSUE THREAD

**Issue by Stefan774** [thkl/homebridge-homematic#269]
Hallo zusammen,

ich habe folgendes Phänomen bei mir bei folgenden Set-Up:

15x HMIP-Broll (Rollladen)
3x HMIP (Rauchmelder)
10x HMIP-BWTH (230 V Thermostate)

zuerst CCU2 und jetzt auf Raspberry Matic:

Nach einer Weile manchmal 1 Tag manchmal 2 Tage können die Geräte nicht mehr angesprochen werden. Weder per HomeApp noch per WebUI. Bei den Rollladen Aktoren geht es sogar soweit, dass man die Rollläden auch nicht mehr richtig am Schalter Bedienen kann.

Nach einem Neustart der Zentrale (Raspberry) funktioniert dann alles wieder.

So warum poste ich das hier bzw. öffne ein Issue:

Einfacher Grund weil ich in den Logs immer wieder etwas von Duty Cycle lese (Anfragen kommen via xml-RPC) und ich befürchte bzw. das wäre jezt meine Vermutung, dass hier homebridge irgendetwas damit zu tun hat. Vielleicht ein Abfrage-Intervall das zu kurz ist bzw. hohl dreht usw.

Hat vielleicht jemand das gleiche Problem in Verbindung mit HomeMatic und Homebridge-Homematic?

Falls nicht muss ich an anderer Stelle weiter suchen. Werde jetzt auch mal die Homebridge ausgeschalten lassen und mal sehen wie und ob sich das auswirkt.

Viele Grüße,
Stefan

**Comment by xxxchris** [comment]
Hatte ähnliche Probleme. Geräte nicht erreichbar. Hab dann das Homematic Plugin nochmal neu gezogen. (1.0.9)Danach trat es nicht mehr auf. Ursache war aber so dann nicht mehr nachzuvollziehen.

**Comment by Stefan774** [comment]
Also kurzes Update hierzu:
Ich habe seit kurzen einen Aktor HM-LC-Sw4-DR (Hutschiene im Schaltschrank) 
Siehe auch https://www.elv.de/homematic-hm-lc-sw4-dr-funk-schaltaktor4fach-hutschiene-fuer-smart-home-hausautomation.html?refid=SEM_30003&gclid=EAIaIQobChMI-visnrLa2gIVAmUZCh2hagP5EAQYAyABEgKdifD_BwE

Seit dem ich diesen wieder aus dem Homekit Gewerk genommen habe scheint es wieder ohne Duty Cycle Probleme zu laufen. Werde das aber weiter beobachten.

**Comment by Stefan774** [comment]
Okay danke für die Erklärung.
Bis dato läuft auch wieder alles ohne Probleme. Wie gesagt nur mit dem HM-LC-Sw4 gab es Probleme anscheinend in Verbindung mit HomeKit. 

Hab auch relativ oft die App geöffnet weil halt neues Spielzeug ;)

Naja aber ich schließ jetzt mal den Thread da es anscheinend irgend ein lokales Problem bei mir war /ist mal sehen.

Grüße, Wäre super wenn du dir das mit den BROLL's und der %Anzeige bei Schalterbedienung ansehen könntest ;)

**Comment by bpohvoodoo** [comment]
Ich habe nun auch das DutyCycle Problem und et hat definitv was mit homebride zu tun. Was natürlich nicht an deinem Plugin liegen muss. Es scheint eher etwas mit ios12 zu tun zu haben. Vorher hatte ich keine Probleme
