### ISSUE TITLE
CCU Cache fehlermeldung

### ISSUE THREAD

**Issue by MCGregorUK** [thkl/homebridge-homematic#27]
Hallo! Zuerst mal danke für das tolle Plugin!

Bei der neusten Version erhalte ich folgenden fehler:
Cannot cache ccu data  { [Error: ENOENT: no such file or directory, open './.homebridge/ccu.json']
path: './.homebridge/ccu.json' }
syscall: 'open',
code: 'ENOENT',
errno: -2,

meine HomeBridge-Config ist unter /root/.homebridge

Was muss ich denn machen damit es gecached wird? Bzw. alternativ, kann ich das deaktivieren?

**Comment by MCGregorUK** [comment]
Habe meinen Pfad in der index.js angepasst.
jetzt läuft es wieder :)

**Comment by dirk777** [comment]
Auch bei mir funktioniert der Cache nur mit absoluter Pfad-Angabe. Der Config-Wert "lcache" wird anscheinend ignoriert. Erst die Anpassung in der index.js brachte Erfolg.
PS: homebridge-homematic ist einfach klasse!

**Comment by Apollon77** [comment]
Ich glaube das "lcache" als true/false Parameter gedacht ist und am Ende die Speicherung immer am von der Applikation gedachten Pfad stattfindet.

Man muss homebridge am Ende in "/root" starten dann passt das auch ... also wenn man es manuell macht. Ansonsten vor dem start Befehl ein "cd /root/"
