### ISSUE TITLE
Jalousienschalter Lamellenposition in % fahren

### ISSUE THREAD

**Issue by YuriBiemanov** [thkl/homebridge-homematic#272]
Hallo,

ich lese schon eine ganze Weile mit und versuche viele Dinge selbst zu lösen bzw. mir Anregungen von hier und da zu holen.
Eines habe ich bisher aber nicht im Ansatz geschafft. 
Ich habe die Jalousienschalter HM-LC-Ja1PBU-FM im Einsatz und binde sie zur Zeit über "services":[{"type": "HM-LC-Ja1PBU-FM:JALOUSIE", "service": "HomeMaticHomeKitBlindService"}] in der config.json in Homekit ein. 
Eine ganze Weile habe ich über kleine einfache Programme, die ebenfalls in der config.json eingetragen waren, die Jalousien hoch/mittig/runter und die Lamellen auf 45° bzw. 90° gefahren. Für jeden Befehl gab es einen zusätzlichen separaten Schalter in Homekit. Das funktionierte ganz gut, aber ich frage mich, ob es auch die Möglichkeit gibt, anstelle der einzelnen Schaltern, einen zweiten, "virtuellen" Schieberegler im Homekit einzufügen, der die Lamellenwinkel in Prozent, so wie die Behanghöhe, widerspiegelt, mit Verweis auf die Lamellenposition.

Gruß,
Yuri

**Comment by xxxchris** [comment]
ja, im Grunde müssen es zwei Prozentregler sein.
Vielleicht für 1 x Jalousie -> 2x Rolladen. Der eine geht auf die Höhe, der andere auf den Winkel.

**Comment by xxxchris** [comment]
+1

**Comment by iuliusmaximilian** [comment]
+1

**Comment by thkl** [comment]
...

**Comment by spiu16** [comment]
+
