### ISSUE TITLE
raspberrymatic & homebridge-homematic & Duty Cycle

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#274]
Hi

Seite der Umstellung auf die Raspberymatic habe ich ein komisches Verhalten beim Duty Cycle.
Der DC der normal so zwischen 5-8% liegt, schiesst sobald ich im WLAN die Home App öffne (Favoriten Seite) in die Höhe. Alle Geräte in der Favoritenseite werden als "nicht erreichbar" angezeigt. Gehe ich jetzt durch die einzelnen Räume, funktionieren alle Geräte und werden normal angezeigt. Gehe ich dann zurück auf die Favoritenseite, werden nun auch hier alle Geräte richtig und funktionell angezeigt und funktionieren auch. Das treibt den DC auf 20%. Schliesse ich die Home App und probiere das noch einmal....passiert das gleich wieder ... der DC steigt dann auf zB 38% .... usw.....
Lustigerweise wenn ich über LTE auf meinHome gehe steigert das zwar auch den DC....aber nicht so extrem und vor allem dieses Phänomen mit der Favoritenseite (Geräte beim ersten Mal nicht erreichbar) habe ich auch nicht .....

Hast Du irgendweine Idee dazu ?

Raspberrymatic, Homebridge, Homebridge-homematic .... alles aktuelle Version
Node Version 8.11.1 LTS
Apple TVOS 11.3
iOS 11.3.1

lg RIchard

**Comment by thkl** [comment]
Ich habe in der letzten Version etwas dahingehend geändert, das die Daten der Geräte, wenn Homekit anfragt, nicht mehr von Rega geladen werden. Sondern, abhängig vom Gerät, von der jeweiligen Schnittstelle. Dummerweise scheit diese die Daten nicht zwischenzuspeichern sondern fragt jedesmal das Gerät selber. 

Ich hab das mal mit https://github.com/thkl/homebridge-homematic/commit/381f063030b8a93b840a9df98d15ede5881ff95a  wieder geändert.

Jetzt wird bei Abfragen von Datenpunkten wieder Rega gefragt. Das sollte sich positiv auf den DC auswirken.

**Comment by roe1974** [comment]
machst du eine NPM Version daraus ... oder soll ich das index.js tauschen ?
lg

**Comment by roe1974** [comment]
mit der änderung startet HB nicht mehr:

May 02 17:06:08 homebridge-raspi homebridge[9029]: /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:100
May 02 17:06:08 homebridge-raspi homebridge[9029]: that.server = that.rpc.createServer({
May 02 17:06:08 homebridge-raspi homebridge[9029]: ^
May 02 17:06:08 homebridge-raspi homebridge[9029]: TypeError: Cannot read property 'createServer' of undefined
May 02 17:06:08 homebridge-raspi homebridge[9029]: at /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:100:30
May 02 17:06:08 homebridge-raspi homebridge[9029]: at Server.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:338:39)
May 02 17:06:08 homebridge-raspi homebridge[9029]: at Object.onceWrapper (events.js:313:30)
May 02 17:06:08 homebridge-raspi homebridge[9029]: at emitNone (events.js:106:13)
May 02 17:06:08 homebridge-raspi homebridge[9029]: at Server.emit (events.js:208:7)
May 02 17:06:08 homebridge-raspi homebridge[9029]: at emitCloseNT (net.js:1671:8)
May 02 17:06:08 homebridge-raspi homebridge[9029]: at _combinedTickCallback (internal/process/next_tick.js:135:11)
May 02 17:06:08 homebridge-raspi homebridge[9029]: at process._tickCallback (internal/process/next_tick.js:180:9)
May 02 17:06:08 homebridge-raspi homebridge[9029]: at Function.Module.runMain (module.js:695:11)
May 02 17:06:08 homebridge-raspi homebridge[9029]: at startup (bootstrap_node.js:188:16)
May 02 17:06:08 homebridge-raspi homebridge[9029]: at bootstrap_node.js:609:3
May 02 17:06:08 homebridge-raspi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
May 02 17:06:08 homebridge-raspi systemd[1]: Unit homebridge.service entered failed state.


lg Richard

**Comment by roe1974** [comment]
soll ich zurück auf 0.0.95 ?
lg Richard

**Comment by roe1974** [comment]
@thkl .... konntest du dir das schon ansehen ?
die änderung oben geht nicht :(
lg richard

**Comment by YuriBiemanov** [comment]
Hallo,

ich habe zur Zeit große Schwierigkeiten mit der Homematic Homebridge wegen des Duty Cycle Problem. Im Prinzip liegt der Duty Cycle ständig bei 100%. Auch mit 0.0.95 keine Besserung.

LG Yuri

**Comment by thkl** [comment]
ich habe mal die Dev Version als Beta npm gepackt ... Update : 

```
npm cache clean
sudo npm install -g  homebridge-homematic@beta
```

Die Version läuft bei mir auf dem Produktivsystem seit 1 Woche ohne Probleme

**Comment by YuriBiemanov** [comment]
Hallo,

ich habe nun auch die Dev-Version getestet. Scheint das gleiche Problem zu sein. Was mir nun aber auffiel, die Jalousienschalter wurden als einzigste Geräte als "aktualisieren" angezeigt. Ich habe sie mal aus dem Gewerk "Homekit" entfernt um zu testen ob es eventuell an ihnen bzw. dem blind-services liegt.

LG

**Comment by roe1974** [comment]
Ähnliches hier .... Auf die Idee mit dem Jalousie Aktor bin ich noch nicht gekommen...
habe auch 5 Stk. von denen ... leider gibt es keine dedizierte Class dazu sondern nur die normalen "blinds"
werde auch mal testen....
lg

**Comment by YuriBiemanov** [comment]
Ich weiß es jetzt mit Sicherheit, es liegt am Raffstorenschalter BlindsService. Ohne läuft HM astrein. Ich habe mir jetzt ein walkaround mit Programmen für Behanghöhe und separat Lamellenwinkel erstellt, der für mich gut funktioniert.

**Comment by roe1974** [comment]
Dh was genau ? ... die jalousien schalter sind nicht mehr mit blindservice in HK eingebunden ? sondern werden nur über programme gesteuert?

**Comment by roe1974** [comment]
Ich verwende (glaube ich) eine noch ältere Version der HomeMaticHomeKitBlindService.js als die von 0.0.95

Kannst die mal probieren ?

'use strict';

var HomeKitGenericService = require('./HomeKitGenericService.js').HomeKitGenericService;
var util = require("util");


function HomeMaticHomeKitBlindService(log,platform, id ,name, type ,adress,special, cfg, Service, Characteristic) {
    HomeMaticHomeKitBlindService.super_.apply(this, arguments);
}

util.inherits(HomeMaticHomeKitBlindService, HomeKitGenericService);


HomeMaticHomeKitBlindService.prototype.createDeviceService = function(Service, Characteristic) {

    var that = this;
    var blind = new Service["WindowCovering"](this.name);
    this.services.push(blind);

    var cpos = blind.getCharacteristic(Characteristic.CurrentPosition)

    .on('get', function(callback) {
      that.query("LEVEL",function(value){
       if (callback) callback(null,value);
      });
    }.bind(this));

    this.currentStateCharacteristic["LEVEL"] = cpos;
    cpos.eventEnabled = true;


    var tpos = blind.getCharacteristic(Characteristic.TargetPosition)

    .on('get', function(callback) {
        if (that.state["LEVEL"] != undefined ) {
                callback(null,that.state["LEVEL"]);
        } else {
                that.query("LEVEL",function(value){
                        if (callback) {
                                callback(null,value);
                        }
                });
        }
    }.bind(this))

    .on('set', function(value, callback) {
      that.delayed("set", "LEVEL", value, 750);
      callback();
    }.bind(this));

    var pstate = blind.getCharacteristic(Characteristic.PositionState)

        .on('get', function(callback) {
      that.query("DIRECTION",function(value){
       if (callback) {
          if (value!=undefined) {
            callback(null,value);
          } else {
            callback(null,"0");
          }

       }
      });
    }.bind(this));

    this.currentStateCharacteristic["DIRECTION"] = pstate;
    pstate.eventEnabled = true;

    this.addValueMapping("DIRECTION",0,2);
    this.addValueMapping("DIRECTION",1,1);
    this.addValueMapping("DIRECTION",2,0);
    this.addValueMapping("DIRECTION",3,2);

    this.remoteGetValue("LEVEL");
    this.remoteGetValue("DIRECTION");



}

HomeMaticHomeKitBlindService.prototype.endWorking=function()  {
 this.remoteGetValue("LEVEL");
}


module.exports = HomeMaticHomeKitBlindService;


lg Richard

**Comment by YuriBiemanov** [comment]
Hallo,

genau, ich habe Programme für die "Standard-Stellungen" Raffstoren Auf/Zu/Halbauf - Lamellen 45/90Grad. War viel Arbeit, aber in diesen Schritten stellen wir sie eh nur ein. Kann ich diese Zustände eigentlich in einem "Multiswitch" als eine Art Drop-Down-Auswahl einrichten?

@roe1974: Deine Version habe ich auch getestet, allerdings startet die Homebridge nicht.

@thkl: Einen kleinen Fehler habe ich in der Beta gefunden. Zum einen kommt trotz Deinstallation der Version 0.0.109 die Fehlermeldung

May 14 16:28:24 hbridge2 homebridge[10364]: [2018-5-14 16:28:24] [HomeMatic CCU2] NPM 0.0.109 vs Local 0.0.110

und zum Anderen wird beim Schalten eines Ausgangs vom HM Gerät HM-LC-Sw4-DR-2 (4 Schaltausgänge) alle Ausgänge nach kurzer Zeit als eingeschaltet in Homekit angezeigt.
Das war mit der vorherigen Version nicht der Fall.

**Comment by roe1974** [comment]
versuch mal das file .... (.zip vorher in .js umbenennen)

lg

[HomeMaticHomeKitBlindService.zip](https://github.com/thkl/homebridge-homematic/files/2001322/HomeMaticHomeKitBlindService.zip)

**Comment by YuriBiemanov** [comment]
ich habe es nun ausprobier, verhält sich aber genauso wie die "Standard" Version. Es wird ständig aktualisiert und der DutyCycle  geht hoch.

**Comment by roe1974** [comment]
hmmmmm ... das ist bei mir nicht so ....

**Comment by YuriBiermanov** [comment]
Kommando zurück! Ich habe deine Version nochmals länger laufen lassen, inlusive vollem Reboot aller ios Geräte und der homebridge. Nach wenigen Minuten pendelte sich der DutyCycle bei ca. 10% (anstelle 6% davor) ein. 
Das Einzige was mir auffiel, nach dem Betätigen über Homekit wird der Status von zB. "schließen" sehr spät, nachdem die Jalousie längst geschlossen ist,  auf "geschlossen" aktualsiert.

**Comment by roe1974** [comment]
Dh. wenn du nichts machst pendelt sich der DC bei 10% statt 6% ein ... habe ich das richtige verstanden ?
Oder während Du mit der HomeApp "herumspielst" ?
Wie sind die RSSi Werte der Jalousie Aktoren ?
lg Richard

**Comment by YuriBiermanov** [comment]
Was ich nun nach längerer Testzeit sagen kann:

Im Normalbetrieb von Homematic ohne viele Homekit Spielereien pendelt der DC sich auf die gewohnten 6% ein.
Wird Homekit verwendet steigt der DC auf besagte 10-17%, was aber ok ist, denn in der Standardversion des Blindservice (Version 0.0.109 und 0.0.110) steigt der DC auf undbedienbare 100% an.
Fehlerhaft ist weiterhin der Working State, aber das ist ein anderes Thema.
Die RSSi Werte sind alle in Ordnung (von 45-60 Dbm) - ich habe keine Kommunikationsstörungen im Normalbetrieb.

LG Yuri

**Comment by roe1974** [comment]
ok das passt so...wenn ich HK bediene habe ich auch so 10-19% DC (bei 63 Geräten) ....  pendelt sich dann auch wieder ein bei 3-5%
Was aber bei mir interessant ist, wenn ich die Home App nutze über LTE (Also ausserhalb des WLANs) steigt er nicht so hoch bis gar nicht.... (iPhone X, iOS 11.3.1, AT iOS 11.3) .... ist das bei Dir ähnlich ?

lg Richard

**Comment by YuriBiemanov** [comment]
Ja genau so wie Du es beschreibst! Nur ist mir das im lte Netz nie aufgefallen.
Ich habe 76 Geräte und genau die gleiche Apple Ausstattung ;-).

**Comment by roe1974** [comment]
So...jetzt wird es interessant ..... wo ist der Unterschied zwischen lokalem WLAN/BT und LTE (also von aussen) .... ?!?!?!? Vielleicht hat @thkl ein Idee dazu ?

lg

**Comment by thkl** [comment]
Nein, soweit ich das sehe ist es völlig wurschd, über was das Phone mit Homebridge spricht. Homebridge an sich redet immer via LAN/WLAN mit der CCU. Der höhere DC bei einer kompletten Abfrage der Zustände kommt halt daher, das einmal alle Geräte gefragt werden.

Ich schau mir das noch mal an. Ggf kann ich da noch optimieren
