### ISSUE TITLE
Falsche Status bei manchen Geräten

### ISSUE THREAD

**Issue by xxxchris** [thkl/homebridge-homematic#276]
Hi,
die Türen werden wenn sie in der config.json als DOORS definiert sind, grundsätzlich als offen dargestellt obwohl geschlossen.

**Comment by thkl** [comment]
Ist da nur Offen und geschlossen vertauscht oder sind die immer offen ?

**Comment by xxxchris** [comment]
Irgendwie stelle ich komische Effekte in der DEV-Version fest. Manchmal sind Schalter nicht mehr Synchron und zeigen was anderes an. Wurde was generelles umgestellt?
Bin erstmal wieder auf Master.

**Comment by xxxchris** [comment]
Hi Thomas,

hab auf den aktuellen Master aktualisiert. Der HM-LC-Sw4-SM (4 Fach Schaltaktor) scheint auch nicht ganz richtig die Werte anzuzeigen. Teilweise wird mir ein Kanal als aktiv angezeigt, obwohl er nicht aktiviert ist. Das passiert auch nach einem Neustart, dass der Wert nicht korrekt ist. Schalten per Home App ist aber kein Problem. Manchmal ist es auch genau umgekehrt und er wird als eingeschaltet gezeigt obwohl der Kanal aus ist.
Sehr mysteriös...
Das mit den DOORS werde ich mit dem aktuellen Master nochmal testen.

**Comment by xxxchris** [comment]
Ich kann den Fehler jetzt näher eingrenzen. Sobald einer der 4 Kanäle eingeschaltet ist, werden die anderen Schalter in der Home App auch als eingeschaltet dargestellt.

**Comment by criticallimit** [comment]
Ist bei mir auch so am HM-LC-Sw4-SM (4 Fach Schaltaktor). Sobald ich ihn nicht über home app schalte, werden alle Kanäle in der home app als geschaltet angezeigt. Verändere ich allerdings in der home app einen Kanal, funktioniert alles.

**Comment by xxxchris** [comment]
Muss ja irgendwas sein, was aus der DEV Branch in den Master gepusht wurde. Vorher hatte ich das Verhalten nicht.

**Comment by criticallimit** [comment]
Gibt's schon was neues zum SW4? Ist übrigens in EVE auch so. Schaltet man einen, macht die App zu und wieder auf werden alle Kanäle als geschaltet angezeigt.

**Comment by bwejs** [comment]
Habe beim SW4 ein ähnliches Verhalten festgestellt.
In HomeKitGenericService.js wird die Event Funktion für alle 4 Datenpunkte aufgerufen die im Gleichen Gerät enthalten sind.
Option hier wäre es den übergebenen channel mit der adress im object zu vergleichen. Ich bin mir aber nicht sicher was für Seiteneffekte dies haben könnte! 
Habe dies Testweise in meiner Installation so umgesetzt und bisher keine Probleme gehabt.
[https://github.com/bwejs/homebridge-homematic/blob/bwe/ChannelServices/HomeKitGenericService.js](url)

**Comment by xxxchris** [comment]
Hi! wollte dein File mal ausprobieren. Aber irgendwie funzt der Link nicht.

**Comment by xxxchris** [comment]
Hi, hab die beiden Dateien mal gegen die beiden Genannten ausgetauscht, aber es verhält sich noch genauso wie davor.

**Comment by bwejs** [comment]
Ich habe die Überprüfung nur für Schalter eingebaut um Seiteneffekte zu vermeiden. Eventuell im ersten File
`+  this.strictAdress = false;`

ersetzen durch

`+  this.strictAdress = true;`

**Comment by xxxchris** [comment]
hab die Änderung basierend auf dem master gemacht. 
ausprobiert. ne. irgendwie auch nicht. 
mach dir keinen kopf.. 😃 bei dir gehts also so?

**Comment by bwejs** [comment]
Tut mir leid, konnte nicht funktionieren.
Mein Fehler war, dass bei einem 4-Fach Schalter alle auf einmal auslösen wie bei criticallimit 

Bisher hatte ich die Überprüfung auf den Channel nur bei Tastendruck events eingebaut.

hier jetzt die version für alle:
hoffe das hat die erhoffte Wirkung:
https://github.com/bwejs/homebridge-homematic/tree/bwe

**Comment by xxxchris** [comment]
Werde ich heute Abend ausprobieren. Da ich viele verschiedene Geräte habe, sollte es auch kein Problem sein Seiteneffekte festzustellen, wenn Sie auftreten.

**Comment by xxxchris** [comment]
Klasse. Läuft und der Rest sieht bisher auch gut aus. Werde ich mal paar Tage beobachten und Rückmeldung geben.

**Comment by xxxchris** [comment]
Bislang keine Fehler entdeckt. @criticallimit Teste doch auch mal ob dein Problem behoben ist.

**Comment by criticallimit** [comment]
@xxxchris: Kenner mich leider nicht gut genug aus um zu verstehen was ich wie und wo ändern müsste

**Comment by xxxchris** [comment]
@bwejs 
Hab keine Probleme/Seiteneffekte mehr entdeckt.
Test abgeschlossen, erteile hiermit die Abnahme 😃

Könnt ihr dann rüberbringen.

**Comment by xxxchris** [comment]
#292 
Das scheint ein Seiteneffekt zu sein.... hab gerade auf den Master zurückgestellt und jetzt geht #292 wieder.

**Comment by thkl** [comment]
..
