### ISSUE TITLE
Falschmeldung von Garagentor

### ISSUE THREAD

**Issue by thoduh** [thkl/homebridge-homematic#278]
Wenn das Garagentor über mehrere Tage nicht benutzt wird (Urlaub), kommt täglich (mal Morgens, mal Abends) eine Meldung "Garagentor wurde geschlossen", obwohl niemand Zuhause war und niemand das Tor bedient hat.

Lässt sich das irgendwo abstellen?
Eine Meldung beim Öffnen und Schließen soll ja schon kommen, aber eben keine "Falschmeldung" nur weil vermutlich die CCU den Status abgefragt hat...

**Comment by thkl** [comment]
Die Meldung wird nur erzeugt, wenn die CCU eine Änderung des Zustandes des Magnetkontaktes sendet. Ich prüfe allerdings nicht, ob sich der Zustand wirklich geändert hat sondern schiebe die Daten weiter nach Homekit.

**Comment by thoduh** [comment]
Bevor du das mit Homebridge möglich gemacht hast, hatte ich eine Systemvariable in der CCU die den Zustand angezeigt hatte. Bei Änderung dieser Systemvariable hatte ich mir eine Push-Nachricht senden lassen. Dort kam aber nie eine „Falschmeldung“.

Der Fehler kommt übrigens nicht sofort am ersten Tag, sondern erst am 2. oder 3.
Ist das bei dir nicht so?

**Comment by thkl** [comment]
Auf der CCU gibt es ja im Programm zwei Trigger : bei Aktualisierung und bei Änderung.  Ersterer wird ausgelöst wenn die Schnittstelle einen Wert sendet. Der andere wenn sich dabei der Wert im Vergleich zum vorher bekannten Wert ändert. Wenn Dein Push bei Änderung erfolgt dann kann passt das so wie von Dir beschrieben. 


Ich müsste jetzt generell dieses Verhalten in den Core implementieren und die Events entsprechend filtern.

**Comment by thoduh** [comment]
Wäre natürlich super wenn du mal Zeit hast und das implementieren könntest.
Ist sonst nämlich ganz schön unheimlich im Urlaub wenn plötzlich solch eine Meldung kommt...

**Comment by nicoh88** [comment]
@thoduh:

Diese Meldungen kann man deaktivieren, dann bekommt man aber garkeine Meldungen mehr vom Garagentor. (Home > Geräte auswählen > Details > Status und Mitteilungen > Mitteilungen erlauben ausschalten)

Ich möchte Benachrichtigungen bekommen und bekomme die Meldungen jeden Tag um 5 Uhr, da ich zu diesem Zeitpunkt Homebridge über die `/etc/crontab` neustarte. Da erst nachdem Start von `homebridge-homematic` der Status des Garagentors herausgefunden wird. @thkl vielleicht kannst du hier optimieren!

Daher gehe ich bei dir @thoduh davon aus, dass immer wenn du die Meldung bekommst, aber keiner das Garagentor betätigt hat, dass Homebridge abgestürzt ist und automatisch neugestartet wurde. Kannst du ja mal über die Logdateien oder `journalctl` prüfen. 😄

**Comment by thkl** [comment]
@nicoh88  ???  Ich steh auf dem Schlauch, was ist hier mein Part ?

**Comment by thoduh** [comment]
Bei mir ist es noch immer so, dass wenn die Homebridge neu gestartet wurde, steht bei Garagentor immer „Wird geöffnet“. Auch manuelles öffnen und schließen ändert nichts.
Erst wenn ich in der Home-App das Tor einmal auf und einmal zu gemacht habe, stimmt der Status. Bis zum nächsten Neustart der Homebridge...

**Comment by thkl** [comment]
ok ich schau mal , das ich das Tor abfrage, wenn die Bridge startet.

**Comment by thoduh** [comment]
Heute folgendes beobachtet:
Das Tor ist geschlossen (auch in der Home-App). Ich öffne das Tor per Home-App, schließe die Home-App und schließe das Tor wenig später per Taster am Tor. Öffne kurz darauf die Home-App und sehe, dort steht „wird geöffnet“. Dieser Status bleibt auch so, obwohl in der CCU das Tor als geschlossen angezeigt wird.
Seltsam, oder?

**Comment by Duude4711** [comment]
Hallo zusammen,
ich wollte jetzt keinen Extra Thread aufmachen, der Titel ist bei mir halt änhlich. D.h., nach Start der Homebridge wird bei mir die Garage immer als "wird geöffnet..." angezeigt, obwohl sie geschlossen ist und die Sensoren das auch anzeigen.
Ich hab schon viel rumprobiert, aber bekomme es leider nicht hin. Anbei auch den Part meiner Config.
Zu erwähnen ist noch, dass ich zwei Sensoren nutze. 
"address_sensor_close" sagt geschlossen, wenn der Kontakt tatsächlich geschlossen ist, also value=false.
"address_sensor_open" sagt geöffnet, wenn der Kontakt geschlossen ist (in den Homematic Einstellungen zu diesem Gerät habe ich die Meldung "in Position geschlossen" auf "offen" gesetzt), also value=true.
D.h., in HomeKit wird mir der Status dieser Sensoren immer korrekt angezeigt. 
Ich hoffe, das kommt verständlich rüber... Wo könnte das Brett vorm Kopf sein?

```
        "platforms": [{
                        "platform": "HomeMatic",
                        "name": "HomeMatic CCU2",
                        "ccu_ip": "192.168.178.54",
                        "filter_device": [],
                        "filter_channel": [],
                        "outlets": [],
                        "doors": [],
                        "ios10": true,
                        "programs": ["Status Rolladen", "Status Heizungen", "Status Garten_Temp"],
                        "variables": ["roll_AutoManuell", "sys_garten_lampen"],
                        "subsection": "Homekit",
                        "special": [ {
                                "name" : "Garage",
                                "type" : "HM-THKL-GARAGEDOOR",
                                "parameter" : {
                                "address_sensor_close": "BidCos-RF.OEQ0926152:1.STATE",
                                "address_sensor_open": "BidCos-RF.NEQ1833364:1.STATE",
                                "state_sensor_close": false,
                                "state_sensor_open": true,
                                "address_actor_open": "BidCos-RF.NEQ1263356:1.STATE",
                                "message_actor_open": {"on":true,"off":false},
                                "sensor_requery_time": 20
                                      } } ],
                        "services": [ {
                                "type": "HM-THKL-GARAGEDOOR", "service": "HomeMaticHomeKitGarageDoorService"
                } ]
                }
```

**Comment by Duude4711** [comment]
Bilder sagen mehr als Worte, daher noch nen Screen dazu. Wäre mega, wenn ihr ne Lösung habt, denn der Schalter Garage wird halt leider als Lampe definiert und bei der Aktion "Schalte alle Lampen ein" geht die Garage auf 👎 
![duude4711_homekit_garage](https://user-images.githubusercontent.com/43464478/45892264-e69d2500-bdc7-11e8-952c-4291e9f04e63.png)

**Comment by Duude4711** [comment]
Hi,
mein Problem ist gelöst, Hilfe dazu von hier: https://forum.smartapfel.de/forum/thread/2039-homematic-plugin-in-homebridge-per-homebridge-app/?postID=40623

Ich habe nur noch einen Sensor genutzt, damit klappt es dann.

**Comment by thoduh** [comment]
Naja, einfach einen Sensor weglassen löst das Problem nicht wirklich.
Es sollte ja auch mit zwei Sensoren funktionieren.

Ich hatte die letzten Tag im Urlaub täglich eine Pushnachricht bekommen "Garage wurde geschlossen", obwohl niemand das Tor bedient hat, die Homebridge nicht neu gestartet wurde und auch die Sensoren keinen anderen Zustand an die CCU übermittelt hatten.
Seltsamerweise habe ich noch nie die Falschmeldung bekommen "Garage wurde geöffnet", es kommt immer nur "Garage wurde geschlossen"?
Vermute dass die Homebridge, wenn die Sensoren von der CCU abgefragt werden, das falsch interpretiert.

**Comment by Duude4711** [comment]
Ich stimm Dir zu, dass es auch mit 2 Sensoren klappen sollte; jedoch konnte ich "mein" Problem lösen, indem ich eben einen Sensor aus der Config genommen habe. 

Wusste nicht, dass man Sensoren auch zu Schaltern machen kann ^^ Wahrscheinlich meinst Du die Aktoren; ja so einen habe ich da auch drin stehen... Zur Sicherheit, wenn dieses Plugin hier mal streikt etc.
