### ISSUE TITLE
HM IP Sensors (HMIP-SWDO) - identified, but no reading

### ISSUE THREAD

**Issue by daNick73** [thkl/homebridge-homematic#28]
Hi

I use a couple of HMIP-SWDO.

They work fine in CCU2, reads go.

Homebridge identifies these, but status is not read. Even if qualified as "door" in config, they are shown as a different type of sensor, but no readings.

Any recommendations? THX!

Best regards

Nico

**Comment by Samfox2** [comment]
Same with me. Did you make any progress on that?

**Comment by thkl** [comment]
Currently there is no hmip support.

**Comment by daNick73** [comment]
Any chance that will change?
Maybe if those interested in the feature donate you a HMIP SWDO for free to test ? :)

Or just to difficult, so wont happen?

(THX btw for the plug in.. the rest works great, thats why it got me greedy) ;)

**Comment by thkl** [comment]
It's not about the Hardware :) it's about the time it takes to implement all the stuff. The HMiP is an new interface Layer.

**Comment by fabz5** [comment]
Are you actually planning to implement HMIP support? Or is this out of scope at the moment? The plugin is really great by the way, THX! :-)

**Comment by thkl** [comment]
i am currently working on that.

**Comment by thkl** [comment]
Ok here comes the HMIP-PSM (atm only the Switch Channel)

**Comment by daNick73** [comment]
Great start, thx so much! Looking forward to using my window/door sensors
(HMIP-SWDO) in homebridge/ HomeKit!
Thomas Kluge <notifications@github.com> schrieb am Do. 6. Okt. 2016 um
21:08:

**Comment by thkl** [comment]
i do not own an swdo to test, but the latest github may work ...

**Comment by daNick73** [comment]
trying to test now (see it is updated), but still says

[10/6/2016, 8:21:14 PM] [HomeMaticCCU] NPM 0.0.37 vs Local 0.0.37
 
after

sudo npm update -g homebridge-homematic

RPI has internet access.

Any recommendation what I may miss here?

Best Nico

**Comment by thkl** [comment]
Nope, you have to update from github.   Npm is still at 0.0.37. 

Replace the files at /usr/local/lib/node_modules/homebridge-homematic

**Comment by janforth** [comment]
Thanks for implementing support for HMIP. How to replace the files at /usr/local/lib/node_modules/homebridge-homematic? Thanks, Jan

**Comment by daNick73** [comment]
1. for me, HMIP-SWDOs are unchanged in 0.39: devices show up, but status is
always "closed" (sensors are read correctly in CCU2).
2. To copy the files, the following worked for me:

telnet into the rpi
sudo chmod -R 0777 usr/local/lib/node_modules/homebridge-homematic
(This allows you to overwrite files in the step below)
Use an ftp client to copy all files from the homebridge-homematic
repository to the above directory on the rpi
janforth <notifications@github.com> schrieb am Fr. 7. Okt. 2016 um 06:05:

**Comment by thkl** [comment]
Ok. will check this.  HMiP doesn't have an event system so HomeKit has always pull states.

**Comment by daNick73** [comment]
Thanks for investing your time for us. Let me know if you need support on
beta testing/ want me to check anything!
Thomas Kluge <notifications@github.com> schrieb am Fr. 7. Okt. 2016 um
07:00:

**Comment by thkl** [comment]
if you are able to make an rpc call then please:

URL http://ipccu:2010/
Methode : POST
HTTP Body:

<?xml version="1.0"?>
<methodCall>
    <methodName>getValue</methodName>
    <params>
        <param><value><string>CHANNELID</string></value></param>
        <param><value><string>STATE</string></value></param>
    </params>
</methodCall>


ChannelID is Device Serial:1

**Comment by thkl** [comment]
@daNick73 

And please make sure that you have enabled hmip in the config.json

"enable_hmip":"true"

the following startup entries should appear

```
[HomeMatic CCU] XML-RPC server for interface HmIP-RF.is listening on port 9093
[HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[HomeMatic CCU] CCU RPC Init Call on port 2010 for interface HmIP-RF.
```

**Comment by thkl** [comment]
@daNick73 

Ok i've added some logging to the current version. Please update from github and start the bridge in debug mode:

`DEBUG=* homebridge -D`

After initializing perform a state change of one of your swdo's and watch out for some logging like this

` HomeMaticRPC RPC event for HmIP-RF.blabla:1 STATE with value true +174ms`

i will need theese logging infos to dig into the issue ....

**Comment by janforth** [comment]
HMIP support works perfectly well here. All devices are found and status (on/off for the switchable I have) can be changed via Apple HomeKit! Thank you so much! Great work and exactly what I needed!

**Comment by thkl** [comment]
;o) i love to hear that. May you me please tell which devices are working well for you ...  cause i do not own any of the hmip's this is all done from paperwork ...

**Comment by janforth** [comment]
I only have several devices of "Schaltsteckdose, Pluggable Switch", Homematic IP, eQ-3, 141836A0A HMIP-PS

**Comment by daNick73** [comment]
Still struggeling, some info to check.

updated via gitgub

json for homematic

      "platform": "HomeMatic",
                                        "name": "HomeMaticCCU",
                                        "enable_hmip": "true",
                                        "ccu_ip": "192.168.178.5",
                                        "filter_device": [],
                                        "filter_channel": [],
                                        "outlets": [],
                                        "doors": [],
                                        "programs": [],
                                        "subsection": "siri"

homebridge start

[10/7/2016, 7:46:19 PM] [HomeMaticCCU] Initializing HomeMatic platform...
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] Homematic Plugin Version 0.0.37
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] Plugin by thkl  https://github.com/thkl
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] Homematic is a registered trademark of the EQ-3 AG
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] init RPC
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] Local IP: 192.168.178.3
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] XML-RPC server for interface BidCos-RF.is listening on port 9090
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] Creating Local HTTP Client for CCU RPC Events
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] CCU RPC Init Call on port 2001 for interface BidCos-RF.
[10/7/2016, 7:46:19 PM] [HomeMaticCCU] Fetching Homematic devices...



DEBUG=* homebridge -D  results in a lot of output, I identified only these lines with string "hmIP-rf"

[10/7/2016, 7:38:05 PM] [HomeMaticCCU] Error while executing rega script var d = dom.GetObject("HmIP-RF.0000D3C9xxxxEC:1");if (d){Write(d.State());}
[10/7/2016, 7:38:05 PM] [HomeMaticCCU] Error while executing rega script var d = dom.GetObject("HmIP-RF.0000D3C9xxxxxB4:1");if (d){Write(d.State());}
[10/7/2016, 7:38:05 PM] [HomeMaticCCU] Error while executing rega script var d = dom.GetObject("HmIP-RF.0000D3C9xxxxx1E:1");if (d){Write(d.State());}
[10/7/2016, 7:38:05 PM] [HomeMaticCCU] Error while executing rega script var d = dom.GetObject("HmIP-RF.0000D3C9xxxxx47:1");if (d){Write(d.State());}
[10/7/2016, 7:38:05 PM] [HomeMaticCCU] Error while executing rega script var d = dom.GetObject("HmIP-RF.0000D3C9xxxxx309:1");if (d){Write(d.State());}
[10/7/2016, 7:38:05 PM] [HomeMaticCCU] Error while executing rega script var d = dom.GetObject("HmIP-RF.0000D3C9xxxxx4A:1");if (d){Write(d.State());}

(xxx added to mask ID).

Does that help?

**Comment by thkl** [comment]
hmm some lines are missing ... 

```
[Fri Oct 07 2016 22:03:42 GMT+0200 (CEST)] [HomeMatic CCU] XML-RPC server for interface HmIP-RF.is listening on port 9093
[Fri Oct 07 2016 22:03:42 GMT+0200 (CEST)] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[Fri Oct 07 2016 22:03:42 GMT+0200 (CEST)] [HomeMatic CCU] CCU RPC Init Call on port 2010 for interface HmIP-RF.
[Fri Oct 07 2016 22:03:42 GMT+0200 (CEST)] [HomeMatic CCU] Fetching Homematic devices...
[Fri Oct 07 2016 22:03:42 GMT+0200 (CEST)] Loading 0 accessories...
[Fri Oct 07 2016 22:03:44 GMT+0200 (CEST)] [HomeMatic CCU] Initializing platform accessory 'HMIP-PSM 0001D3C98DD5B6:3'...
```

**Comment by daNick73** [comment]
I have iobroker.io running on the same RPI (installed, but not really using it). nothing else on the RPI ... could that be the cause?

**Comment by daNick73** [comment]
addition: if there is no easy fix: thx for investing time on MY request here.

Maybe you should wait whether others respond here that they would appreciate this... potentially, I am the only one using HMIP-SWDO with homebridge... and maybe I should have simply bought "normal" Homematic sensors, not HmIP :)

thx again!

**Comment by thkl** [comment]
your logfile says that the hmip rpc service is not running. i am not sure why ...

**Comment by daNick73** [comment]
update ... almost there (I guess) :)

sudo npm -g update homebridge-homematic now got me to 0.40

which added the HmIP layer to the logfile :)

[10/8/2016, 11:52:49 AM] [HomeMaticCCU] Local IP: 192.168.178.3
[10/8/2016, 11:52:49 AM] [HomeMaticCCU] XML-RPC server for interface HmIP-RF.is listening on port 9092
[10/8/2016, 11:52:49 AM] [HomeMaticCCU] Creating Local HTTP Client for CCU RPC Events
[10/8/2016, 11:52:49 AM] [HomeMaticCCU] CCU RPC Init Call on port 2010 for interface HmIP-RF.
[10/8/2016, 11:52:50 AM] [HomeMaticCCU] Fetching Homematic devices...

Now, the initial reading of my HMIP-SWDO is correct, meaning: when I start homebridge and the window is open .... it shows open! :) :)

just that state does not change, so when the window closes, that is not detected.

Anything needed from me to investigate that?

THX!

**Comment by thkl** [comment]
Ah ok ... it seems that HMIP Events are not allways multicalls .. So i have to implement the rpc event method ...

**Comment by thkl** [comment]
@daNick73 would you please replace the HomeMaticRPC.js with the actual github version and test that ... 
thank you

**Comment by daNick73** [comment]
changing state now crashes homebridge entirely :)

TypeError: Cannot read property 'setValue' of undefined
    at HomeMaticHomeKitContactService.HomeKitGenericService.event (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:220:13)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:94:20
    at Array.map (native)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:92:38)
    at emitThree (events.js:97:13)
    at Server.emit (events.js:175:7)
    at /usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/server.js:42:14
    at callback (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:65:7)
    at Deserializer.onDone (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
    at emitNone (events.js:67:13)
    at SAXStream.emit (events.js:166:7)
    at Object.SAXStream._parser.onend (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:325:33)
    at end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:363:3)
    at Object.SAXParser.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib

**Comment by thkl** [comment]
fck... sorry ... will check that asap'st

**Comment by Samfox2** [comment]
For me, HMIP-SWDOs are working as "windows" - thx for your update! "doors" are still appearing as "unsupported" in the ios app.

**Comment by daNick73** [comment]
@samfox2 the SWDOs are also updated, I.e you start homebridge and
open/close change the reading?
Samfox2 <notifications@github.com> schrieb am Sa. 8. Okt. 2016 um 18:07:

**Comment by Samfox2** [comment]
Ah, sorry. Thought it would be working as state is now open instead of closed like before. But still, no changes are recognized by the app 😔

**Comment by thkl** [comment]
Can anybody with SwDo please start the Bridge in debug mode (DEBUG=* homebridge -D) , and post the rpc event log entries while opening and closing windows.  So I am able to fix this.  

Thank you.

**Comment by daNick73** [comment]
Will do tomorrow, Sunday. Thomas, your support is fabulous! Thx so much!
Thomas Kluge <notifications@github.com> schrieb am Sa. 8. Okt. 2016 um
18:38:

**Comment by daNick73** [comment]
I updated to 0.0.41

I am pleased to confirm that homebridge now reports my SWDOs correctly (instant feedback on close and open)!

This case is SOLVED for now as far as I am concerned

Thomas: if you provide me a private email, I would be pleased to donate EUR 5 via amazon or paypal. Maybe, if others join, you will get your own SWDO :)

THX again for the worldclass support!

**Comment by Samfox2** [comment]
Nope, it's just not recognized and there is no log message in homebridge debug mode while state changes., the only message I get is  [HomeMatic CCU]There is no service for HMIP-SWDO:MAINTENANCE

**Comment by thkl** [comment]
Please make sure that you have added the channel with number 1 to your homekit subsection.

**Comment by Samfox2** [comment]
This is what it looks like


  {
           "platform": "HomeMatic",
           "name": "HomeMatic CCU",
           "ccu_ip": "192.168.2.xxx",
           "local_port": "7xx77",
           "ios10":"true",
           "enable_hmip": "true",
           "filter_device":[],
           "filter_channel":[],
           "outlets":[],
           "doors":[],
           "windows":["BidCos-RF.LEQxxxxx:1","BidCos-RF.MEQxxxxx:1","BidCos-RF.MEQxxxxx:1","BidCos-RF.MEQxxxxx:1","HmIP-RF.0000D3Xxxxxxx:1"]
        }

**Comment by thkl** [comment]
ah thats it, please read https://github.com/thkl/homebridge-homematic#configuration 
I just updated the readme, to be more specific

**Comment by Samfox2** [comment]
Hmm, so what's the problem?

**Comment by thkl** [comment]
there is no subsection key, so currently all channels are will mapped into homekit. depending on the number of devices, they go over 100, which is the limit of homekit devices behind a bridge.

In other cases, i do no have any glue whats going wrong with your installation

**Comment by Samfox2** [comment]
I changed that but it's still not recognized 😞

**Comment by daNick73** [comment]
So, using only "subsection", deleting all "windows" section content won't
do?
Samfox2 <notifications@github.com> schrieb am So. 9. Okt. 2016 um 11:33:

**Comment by Samfox2** [comment]
No. Last thing to try would be to delete the persist folder and set the whole thing up again...

**Comment by thkl** [comment]
first check, if the accessory init is correct : 

`
[HomeMatic CCU] Initializing platform accessory 'mySWDOChannel_1_Name'...
`

**Comment by Samfox2** [comment]
Got it! I changed the port and now it is working! I saw in the protocol that for hmip a "2" is added to the port and this one was already assigned at my host. Now it is working 😄 Thx 2 all.

**Comment by thkl** [comment]
Aaaah ok ... will close that issue now
