### ISSUE TITLE
Jalousien und Rolladenaktor Working State

### ISSUE THREAD

**Issue by xxxchris** [thkl/homebridge-homematic#284]
Hi, mit dem neusten Master sind die Aktoren auf "Working" obwohl sie sich nicht bewegen.

**Comment by xxxchris** [comment]
Automationen werden auf den Jalousien auch nur noch sporadisch ausgeführt. Habe einen Kontaktsensor mit der Jalousie per Home App gekoppelt, so dass wenn ich die Balkontür öffne auch die Jalousie hochgefahren wird, damit ich raus kann. Kann ich natürlich auch in der CCU umsetzen. Ist mir aber aufgefallen, dass das jetzt auch nicht mehr geht. (Aktueller Master Branch)

**Comment by xxxchris** [comment]
Momentan hat das Working wieder gestoppt. Hier kann ich nicht nachvollziehen, wann sich das dann wieder normalisiert. Werde nochmal beobachten ob sich da irgendeine Reproduzierbarkeit ergibt.

**Comment by xxxchris** [comment]
gibts hier auch schon was neues? Zuletzt funktionierte das ja noch besser vor dem letzten Merge. Habe oft den working State der ewig dreht und die eingeschalteten Nachrichten geben oft doppelt ne Meldung wenn der Rolläden hochgefahren wird. Erst der eine Status, dann der andere Status wenn sie in endstellung angekommen sind. 
Hat sonst noch jemand das Problem oder wundere ich mich alleine ?

**Comment by xxxchris** [comment]
Der Commit aus #274 hat ne Verbesserung gebracht.

**Comment by xxxchris** [comment]
... irgendwie rotieren mal wieder die Kreise und es steht "wird geöffnet", aber die Jalousien sind eigentlich unten.
Also doch noch nicht gelöst.

**Comment by xxxchris** [comment]
So sieht das übrigens die ganze Zeit aus, wenn die Jalousien geschlossen sind. Wenn sie geöffnet sind, rotiert der Kreis nicht.
![acbeb1ca-c1bc-408a-bfaa-16fa7280d183](https://user-images.githubusercontent.com/38039494/41057964-ce4ba858-69c8-11e8-9289-98f3c2ffce31.png)

**Comment by xxxchris** [comment]
Nutze jetzt für die Jalousien die Implementierung für die Homebridge in IP-Symcon. Damit tritt das Problem nicht auf.

**Comment by udochrist** [comment]
Das Problem taucht erst mit der aktuellsten Version bei mir auf. Mit der (alten) release Version ist der Status - inkl öffnen und schließen - immer korrekt gewesen.
