### ISSUE TITLE
Homematic Funk-Controller für Dual-White-LEDs (HM-LC-DW-WM)

### ISSUE THREAD

**Issue by vowchr** [thkl/homebridge-homematic#286]
Hallo zusammen
Erstmal vielen Dank für die tolle Möglichkeit, Homematic mit iOS und Siri zu steuern!

Ich habe seit kurzem zwei Dual-White LED-Bänder installiert, die ich mit dem [HM-LC-DW-WM](https://www.elv.de/elv-homematic-funk-controller-fuerdual-white-leds-hm-lc-dw-wm-bausatz.html) entsprechend steuern kann. 
Leider kann ich diese Aktoren nicht via homebridge ansprechen. Wenn ich sie in mein homekit-Gewerk aufnehme, erhalte ich im Log die folgenden Meldungen:
`[HomeMatic CCU] There is no service for HM-LC-DW-WM:DUAL_WHITE_BRIGHTNESS`
`[HomeMatic CCU] There is no service for HM-LC-DW-WM:DUAL_WHITE_COLOR`

Kann mir jemand einen Tipp geben, wie ich dies zum laufen bringen könnte? 
Wäre super wenn ihr das Device in einer späteren Version mit aufnehmen könntet.

Vielen Dank und Gruss
vowchr

**Comment by thkl** [comment]
Ja ja .. das sind am Ende pro Kanal ein Dimmer. Ok das kann man als Dimmer einzeln abbilden. 
Aaaaber ! Wie läuft das es gibt 

DUAL_WHITE_BRIGHTNESS :1 
DUAL_WHITE_COLOR :2
VIRTUAL_DUAL_WHITE_BRIGHTNESS :3
VIRTUAL_DUAL_WHITE_COLOR :4
VIRTUAL_DUAL_WHITE_BRIGHTNESS :5
VIRTUAL_DUAL_WHITE_COLOR :6

Jeder Kanal hier hat einen LEVEL Datenpunkt. Der wechselt von 0 bis 1 (also 0-100%) ..
DUAL_WHITE_BRIGHTNESS verstehe ich noch, das ist die Helligkeit. Was macht der LEVEL in DUAL_WHITE_COLOR ? Die Farbthemperatur ? Also 0 = kaltes weiß - 1 = warmes weiß ???

**Comment by thkl** [comment]
ok die virtuellen werden sicher analog der PWM Dimmer funktionieren.

Mach mal folgendes:
Nimm Dir einen Editor und bearbeite mal die config.json in /home/pi/.homebridge
Dort den Abschnitt wo das Homematic Plugin konfiguriert wird.
Da fügst Du jetzt folgendes ein: 

`
"services": [
  { "type": "DUAL_WHITE_BRIGHTNESS",
    "service": "HomeMaticHomeKitDimmerService" }
]
`

Bitte drauf achten das es ein valides JSON bleibt also Beispiel:

```
{"platform": "HomeMatic",
"name": "HomeMatic CCU",
"ccu_ip": "blabla",
"subsection":"Homekit",
"services": [
  { "type": "DUAL_WHITE_BRIGHTNESS",
    "service": "HomeMaticHomeKitDimmerService" }
]
}

Dann sollte zumindest der Dimmer Teil schon mal funktionieren.
Für den Rest muss ich einen extra Service bauen

**Comment by vowchr** [comment]
Hallo Thomas
DUAL_WHITE_BRIGHTNESS funktioniert mit deinem Tipp schonmal wunderbar. Die Helligkeit kann ich nun via Homekit steuern.

Viele Grüsse
Christian
