### ISSUE TITLE
Alternative behaviour for DimmerService On/Off switch

### ISSUE THREAD

**Issue by martinzuern** [thkl/homebridge-homematic#289]
At the moment, whenever you switch on a dimmer using HomeKit, it will set the brightness to 100%, as defined here:

https://github.com/thkl/homebridge-homematic/blob/c6dbf386e78b0fb90c6ce560a8c8835758c142c3/ChannelServices/HomeMaticHomeKitDimmerService.js#L40-L43

However, I would very much prefer the behaviour that turning the light on would set it to the _last brightness_ value. 

**Current behaviour:** 
Lamp On, 50 % brightness -> Lamp Off (will set it to 0% brightness) -> Lamp On (will set it to 100% brightness)
**Proposed behaviour:** 
Lamp On, 50 % brightness -> Lamp Off (will set it to 0% brightness) -> Lamp On (will set it to 50% brightness again)

Is there anything holding us back from implementing this (probably in a backwards-compatible manner)?

**Comment by xxxchris** [comment]
Would be nice to have a parameter for every device

**Comment by martinzuern** [comment]
@xxxchris not sure if/how this would work, as you normally specify each device. 

I thought of something like a `DimmerMinValueOn` config, which could be set to 0 for my proposed behaviour, and default to 100 to achieve the current behaviour.

**Comment by thkl** [comment]
The default behavior for the isOn Characteristic is to set the level to the last known level. If there is non such a level stored the level will be 100%. 

I can change the 100% for all Dimmers using that service to a custom value. But not for individual devices.

**Comment by martinzuern** [comment]
From my understanding, the problem here is that `HomeMaticHomeKitDimmerService` isn't storing the last value of power _and_ brightness, but only the last value sent to the CCU. 

What I feel to be necessary is to store brightness and power as variables, and to use the stored brightness value (instead of 100) when switching the light on. 

However this would require to hook in additional logic in here: https://github.com/thkl/homebridge-homematic/blob/c6dbf386e78b0fb90c6ce560a8c8835758c142c3/ChannelServices/HomeMaticHomeKitDimmerService.js#L61
as we cannot read the current value from the CCU when it's switched off (CCU will return 0, but we want to display the stored value then).

In case you don't have the time to work on this @thkl, would you accept a PR?

**Comment by martinzuern** [comment]
Especially when using Voice Commands ("Alexa/Siri, turn on the lights") it would be quite important for the lights to be aware of their set brightness.

I also have some Philips Hue, which e.g. are aware of their brightness when turning them on and off – so I think it would be helpful if homematic would adapt the same behaviour.

**Comment by thkl** [comment]
Ok thats a good point. Copying the HUE behavior may be a problem: currently homebridge is monitoring  the current LEVEL events of each dimmer. So i will be able to memorize the new level of each dimmer while its increasing. thats not a big deal. But the opposite way, thats the real problem, because depending on the level events i am not able to decide if the user is changing the level from 75% to 50% or down to zero. Especially when you are using a large ramp time. then they will be multiple LEVEL events on the way down.

**Comment by martinzuern** [comment]
I did another dig in the HomeMatic documentation, and stumbled across this:

Every dimmer seems to have the `OLD_LEVEL` action:
![image](https://user-images.githubusercontent.com/9105774/40999119-3ef7817c-690a-11e8-8375-ad39ac414acf.png)

When fired, it sets the dimmer to the last non-zero value (which is used e.g. in the Web UI when toggling on/off). 
A quick test confirmed it:
```
dom.GetObject("BidCos-RF.MEQ1116469:1.LEVEL").State(1); // Dimmer on, 100%
dom.GetObject("BidCos-RF.MEQ1116469:1.LEVEL").State(0.5); // Dimmer on, 50%
dom.GetObject("BidCos-RF.MEQ1116469:1.LEVEL").State(0); // Dimmer off

dom.GetObject("BidCos-RF.MEQ1116469:1.OLD_LEVEL").State(true); // Dimmer on, back to 50%
```

Using this instead of setting the dimmer to 100 would be at least a quick fix. Any thoughts on that?

**Comment by martinzuern** [comment]
It wouldn't be as good as a mimic of Hue's behavior, e.g. when the light is turned off and I change the brightness, I wouldn't expect the lights to turn on. But at least toggling the lights using voice commands would work perfectly fine. /cc @thkl

**Comment by thkl** [comment]
ok a isOn = true Event form homekit should set OLD_LEVEL to true ... a false Event should set LEVEL to 0 ... is this correct ?

**Comment by martinzuern** [comment]
The only dimmer that don't seem to support `OLD_LEVEL` is _HMW-LC-Dim1L-DR_, a HomeMatic Wired device. Not sure if Homebridge-Homematic supports this device anyway. 
I tested sending `OLD_LEVEL: true` instead of `LEVEL: 100` and it works perfectly fine. I'll file a PR.
