### ISSUE TITLE
Variable basierendes Security System keine Aktualisierung aus CCU

### ISSUE THREAD

**Issue by xxxchris** [thkl/homebridge-homematic#292]
zu #255 

"Wird jetzt die Variable in der CCU geändert, dann wird durch das Programm die virtuelle Taste betätigt, was den Service zu einer Abfrage des aktuellen Variablenstatus triggert. Dieser wird dann an HomeKit gemeldet.", lautet die Beschreibung im Wiki.

Wenn die Variable des Security Systems direkt in der CCU geändert wird, erfolgt keine Aktualisierung der Variable in HomeKit.
Die virtuelle Taste die durch die Aktualisierung gedrückt wird, wird im Log der Homebridge angezeigt. Allerdings wird die Variable nicht neu gezogen daraufhin.

**Comment by iuliusmaximilian** [comment]
Ich habe verschiedene Programme in der CCU2, die die Variable des Security Systems ändern und anschließend die virtuelle Taste triggern und so HomeKit aktualisieren. Bspw. nutze eine weitere Variable die mir grundsätzlich sagt, ob es einen Alarm gibt und synchronisiere diesen in beide Richtungen mit dem Security System. Funktioniert gut. Ein Beispiel mit anbei.

![screen](https://user-images.githubusercontent.com/28545473/41378297-f7593a80-6f5e-11e8-974c-abc8cf170e16.png)

**Comment by xxxchris** [comment]
Werde ich mir morgen nochmal anschauen und mich melden.

**Comment by xxxchris** [comment]
Hi, gerade ausprobiert nachdem ich auf den aktuellen Master zurück bin. Ich vermute es war ein Seiteneffekt aus der Lösung zu #276 
Damit mache ich hier mal wieder zu. Danke für deine Unterstützung
