### ISSUE TITLE
Türstatus wird invertiert angezeigt

### ISSUE THREAD

**Issue by jp112sdl** [thkl/homebridge-homematic#293]
Moin!
Bin von der 0.0.97 (da war es richtig) zur 0.0.109 (Git-Stand) gewechselt.
Seitdem wird der geschlossene Zustand als "geöffnet" angezeigt und umgekehrt.

Es handelt sich physisch um das 3fach Kontaktinterface, dessen Kanal 1 als Tür hinterlegt ist
`"doors": ["BidCos-RF.NEQ0529746:1"]`

**Comment by xxxchris** [comment]
Siehe auch #276

**Comment by jp112sdl** [comment]
@xxxchris Danke für den Hinweis!

Also ich habe in der WebUI den Status tatsächlich invertiert.
- Meldung in Position geschlossen: offen
- Meldung in Position offen: geschlossen
Der Status wird damit auch korrekt in der WebUI angezeigt.
Bisher (also mit der 0.0.97) war das auch in HomeKit der Fall.

Seit 0.0.109 (Git-Stand) nicht mehr.

Nun habe ich im Code der [HomeMaticHomeKitDoorService.js](https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitDoorService.js) gesehen, dass dort die Variable 
`reverse` hinzugekommen ist, die auch default mit false initialisiert wird.
https://github.com/thkl/homebridge-homematic/blob/7a42f7bf13910bbde8e58b4a21e937f497b091d5/ChannelServices/HomeMaticHomeKitDoorService.js#L29

Bei Erfüllen der Bedingung wird sie dann true:
https://github.com/thkl/homebridge-homematic/blob/7a42f7bf13910bbde8e58b4a21e937f497b091d5/ChannelServices/HomeMaticHomeKitDoorService.js#L31

Wie man ab [Zeile 53](https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitDoorService.js#L53) sehen kann, wird hier der Status invertiert - oder auch nicht: 
```
      if (reverse == true) {
	     this.addValueMapping("STATE",1,1);
   		 this.addValueMapping("STATE",0,100);
   	  	 this.addValueMapping("STATE",true,1);
     	 this.addValueMapping("STATE",false,100);
      } else {
	     this.addValueMapping("STATE",0,1);
   		 this.addValueMapping("STATE",1,100);
   	  	 this.addValueMapping("STATE",false,0);
     	 this.addValueMapping("STATE",true,100);
      }
```

Wenn ich die Tage mal Zeit und Lust habe, werd ich dort ansetzen.

Bin derzeit wieder zurück auf 0.0.97. Die für mich bisher stabilste/"funktionierendste" Version.

**Comment by jp112sdl** [comment]
Okay... Falsche Fährte mit HomeMaticHomeKitDoorService.js 😄

**Comment by jp112sdl** [comment]
Wegen Wechsel zu einer anderen Lösung kann hier zu.
