### ISSUE TITLE
symbole in Home App

### ISSUE THREAD

**Issue by criticallimit** [thkl/homebridge-homematic#297]
Ich habe zwei Kanäle eines HM-LC-Sw4-DR , denen ich gerne andere Symbole in der home app zuordnen würde. Für die anderen beiden benutze ich in der config.json das "outlets". Da gibt es aber nur Licht, Lüfter, Steckdose als Symbol. Gibt es eine Übersicht der Symbole die in der home app angezeigt werden können? Und wie würde ich die dann den zwei Kanälen des HM-LC-Sw4-DR zuordnen? Gibt es noch mehr als Outlets?

**Comment by pbksol** [comment]
Die Symbole sind in der Home-App fest hinterlegt. Solange Apple diese nicht um weitere Symbole erweitert müssen die vorhanden ausreichen – ein HomeKit-Gerät kann keine Symbole hinzufügen.

Alle Symbole, die für einen bestimmten Gerätetyp verfügbar sind kannst Du einfach sehen, indem Du links auf das Symbol neben dem Namen in den Details tippst. Das geht immer dann, wenn das Symbol einen orangen Rahmen hat. Alle anderen Symbole werden vom System automatisch und fix vergeben.
