### ISSUE TITLE
Kommandos von Virtuellen Tastern/Keys der CCU2 gehen verloren

### ISSUE THREAD

**Issue by padman74** [thkl/homebridge-homematic#298]
Ich habe ein kleines Problem mit virtuellen Tastern/Keys in CCU2 in Kombination mit Homebridge/Homekit. Die Kommandos von der CCU2 gehen manchmal verloren.

Ich habe HM-PBI-4-FM Taster in meiner Wohnung verbaut, die beim Schalten über die CCU2 eine Szene in Homekit aktivieren sollen. Nach Freigabe der Schalter im Gewerk tauchen die Keys in Homekit auf, auf deren Aktion "Einmal drücken" ich die Szenen konfiguriert hab. Es funktioniert alles wunderbar wenn ich direkt mittels Homekit App teste und somit die Werte frisch aus der CCU2 gelesen wurden.

Wenn sich die Systeme allerdings nach einer gewissen Zeit schlafen gelegt haben und ich zum Beispiel morgens eine Taste drücke geht das Kommando auf dem Weg von der CCU2 an die Homebridge leider häufig verloren. Manchmal führt ein mehrmaliges Drücken der Taste zum Ziel, manchmal muss ich auch ein Weilchen warten. Woran kann das liegen und was kann ich tun?

**Comment by thkl** [comment]
Frage: Werden die Zustände der  restlichen CCU Geräte in der Home App aktualisiert, oder bleibt das auch hängen ?

**Comment by padman74** [comment]
Ich habe das Problem eingrenzen können. Die Signale werden von HomeKit nicht abgeholt und verteilt. Als Zentrale hatte ich ein iPad eingerichtet. Dieses scheint sich in der Tat schlafen zu legen. Nun habe ich als Zentrale ein HomePod. Das funktioniert ohne Probleme.
