### ISSUE TITLE
Dimmer starten auf 100% in Szenen

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#299]
Wenn man eine Szenen aufruft in der HM-LC-Dim1T-DR Dimmer eingestellt sind, starten diese auf 100% und dimmen erst ein zwei Sekunden später auf den Wert der in der Szene eingestellt wurde runter.

**Comment by criticallimit** [comment]
Ja, ist bei mir auch so. Wäre toll wenn das abzustellen wäre. Komischer Weise ist das aber nicht immer der Fall, aber eine Regel hab ich bisher nicht entdecken können

**Comment by thkl** [comment]
Das könnte daran liegen, das die Szene zuerst ein EIN Kommando an die Dimmer sendet. Wenn das der Fall ist könnte https://github.com/thkl/homebridge-homematic/issues/289 die Erklärung für dieses Verhalten sein. Bei EIN wird der letzte Level des Dimmers wiederhergestellt.
