### ISSUE TITLE
homematic-xmlrpc

### ISSUE THREAD

**Issue by hobbyquaker** [thkl/homebridge-homematic#3]
Hallo Thomas,

habe gesehn dass Du das homematic-xmlrpc modul nutzt, dazu zwei Anmerkungen:
* Das Modul ist auf npmjs.org veröffentlicht, sprich Du musst in Deiner package.json nicht auf Github verweisen, kannst ganz normal mit semver dependency eintragen.
* Ich empfehle immer [binrpc](https://github.com/hobbyquaker/binrpc) statt xmlrpc zu nutzen, die Module sollten fast 1:1 austauschbar sein, musst eigentlich nur die url beim init auf xmlrpc_bin:// ändern, iirc war der einzige sonstige Unterschied dass binrpc ein connect und disconnect Event emitted und xmlrpc nicht. Binrpc belastet die CCU-Firmware (bzw die Schnittstellenprozesse rfd und hs485d) wesentlich weniger als xmlrpc und das Modul ist auch häufiger im Einsatz und wesentlich intensiver getestet worden als das homematic-xmlrpc Modul. Und wenn ich mich recht erinnere spricht der CUxD nur binrpc und kein xmlrpc.

Viele Grüße,
Sebastian

**Comment by thkl** [comment]
Hallo Sebastian,

ok danke für die Anmerkung. Ich schaue mir das mal an. Ich hab gesehen binrpc ist auch auf npmjs ....

**Comment by thkl** [comment]
Hallo Sebastian,

kann es sein, das ich bei der Nutzung von binrpc auf einen Connect Event des Clients warten muss bevor ich den Server an die CCU veröffentliche....

Ansonsten erhalte ich von der CCU beim Init einen "mit connected" Error. 

Gruß Thomas.

**Comment by hobbyquaker** [comment]
Oh - ja, exakt.

Grüße
