### ISSUE TITLE
Unterscheidung von Kanälen gleichen Namens

### ISSUE THREAD

**Issue by bpohvoodoo** [thkl/homebridge-homematic#30]
Hallo,

Es gibt ein Problem bei Kanalnamen, die bei verschiedenen Aktoren zwar gleich sind, aber u.U.
völlig andere Datenpunkte bereitstellen.
Bitte schau dir mal meinen Lösungsansatz an.

https://github.com/bpohvoodoo/homebridge-homematic/commit/f5c2c70b8d759304a1726d3e6ed1480562d9c456

**Comment by bpohvoodoo** [comment]
BTW: Dann kann man ggf. auch gleich anhand des Device-HSS-Types entscheiden, od es eine Steckdose ist.
Wobei ich mir nicht sicher bin, ob man nicht generell Switches der Aktoren als Steckdose importieren sollte, denn die kann man nachträglich ja zum Lichtschalter umdeklarieren (Licht, Steckdose, Venti). Umgekehrt geht es ja nicht.

**Comment by thkl** [comment]
Ja, ich habe das auch schon festgestellt.  
Wahrscheinlich muss ich aus dem Channel zurück über das Device den Devicetypen ermitteln und daraus dann das Mapping auf das passende HomeKit Device machen. 


Aktuell mache ich das als bloody Workaround schon beim Rinem Weather Channel.  

Das müsste nur noch mal richtig gemacht werden. 

Ich würde den Ansatz weg von Kanaltyp -> HomeKit Type hin zu einem Mapping  über die internalconfig.json machen. Wo dann für jeden HM Devicetypen drin steht wie er in HomeKit behandelt wird.  

Gleichzeitig könnte man damit dann mal die riesige Switch Verzweigung in einzelne Files aufdröseln.  



So viel Arbeit, so wenig Zeit 🤓

**Comment by thkl** [comment]
Aktuelle Version unterstützt das jetzt.
