### ISSUE TITLE
Falscher immer identischer Status bei allen Rolladenaktoren

### ISSUE THREAD

**Issue by rpdever** [thkl/homebridge-homematic#300]
Hallo,

erstmal vorweg, bei mir läuft Homematic und Homebridge auf einem Pi und ich habe 4 Rolladenaktoren von Homematic (nicht IP). 

Gesteuert wird eigentlich ausschließlich über HomeKit. Die hinterlegten Automationen werden korrekt ausgeführt und es wird immer auf Befehle gehört. Allerdings spring der Status nach jedem Befehl immer wieder auf "offen". Ich habe schon alles neu gestartet, sogar den Strom ausgeschaltet. Ich meine den Fehler nicht gehabt zu haben, bevor ich auf einer der letzten Versionen geupdated habe. 

Ich hoffe mir kann jemand helfen, bzw den Fehler beseitigen.

Ich wollte eigentlich noch 4-5 Fenster mehr integrieren. Wenn die Logs benötigt werden, einfach bescheid sagen!

Gruß Ron

**Comment by JensBonse** [comment]
Ich habe im Moment auch die aktuellste Version drauf und habe dieses Problem.
Habe leider im Moment aber keine Ahnung, in welcher Version es noch 1A ging. Bzw. warum da was geändert worden ist. Da müsste man mal die letzten commits durchgehen.

**Comment by rpdever** [comment]
Sehr gut! Also eigentlich nicht, aber immerhin bin ich nicht der einzige! Ich habe mal meine Amazon Bestellungen durchgesehen und weis jetzt eine gewissen Zeitspanne, in der das Plugin perfekt funktionierte. Ich habe den ersten Aktor am 5.8 erhalten. Installiert habe ich das ganze aber ein paar Tage später. Wenn man sich die Plugin Änderungen anschaut, sieht man eine Änderung am 1.5 und am 12.5. Einer dieser Versionen war die Richtige. Ich werde mal etwas rum probieren, da ich sowieso mehrere Homebridge Instanzen habe und somit nicht alles ausfällt.

**Comment by thkl** [comment]
Ist das Problem noch da ?

**Comment by rhammeran** [comment]
Bei mir besteht das Problem ähnlich- hatte bisher nie Zeit, es zu melden. Abweichend zu der o.g. Beschreibung stehen meine Rollos (HM-LC-Bl1PBU-FM) allerdings immer auf "Geschlossen". Zusätzlich habe ich einen "HM-LC-Ja1PBU-FM" - dieser funktioniert korrekt.

Wenn ich ein Rolle direkt am Schalter öffne, wird der Status im Homekit kurz korrekt angezeigt, nach ca. 30 Sekunden springt er dann wieder auf "geschlossen".

**Comment by rpdever** [comment]
Version 0.0.96 löst mein Problem, danach ist wohl was saftig schief gelaufen. Meine ausführliche Antwort ist im Post #311

**Comment by rpdever** [comment]
#311 Ich habe ein Update für alle mit diesem Problem.
