### ISSUE TITLE
DutyCycle immer wieder bei 99%

### ISSUE THREAD

**Issue by sblogoshs** [thkl/homebridge-homematic#301]
Hallo zusammen.

Ohne Homematic in der Homebridge bin ich bei 2-10% DutyCycle und mit, auch wenn ich nur 1 HM-Gerät über HomeKit betreibe in kürzester Zeit bei 99%. Ich habe bei allen Komponenten die aktuelle Version installiert und Raspimatic auf Raspberry Pi 3 läuft auch ohne Probleme. Bei mir kam das aber erst vor kurzem denn bisher hatte ich maximal 60% DutyCycle, wobei 60% auch schon hoch ist im Vergleich zu ohne.

Auch wenn ich Homematic als einziges Plugin verwende ist das so, entweder kam das Problem mit einem Update der Homebride oder mit der letzte Version des Plugins was aber schon etwas länger her ist und ich denke das es erst später zu Problemen kam.

Gruß sblogoshs 

Nachtrag: So. 01.07. 
Hallo zusammen.

Nun ist es als wäre nichts gewesen, schon den ganzen Tag unter 10% DutyCycle, ich kenne zwar gerne den Grund für etwas aber im Moment ist mir das nicht so wichtig, hauptsächlich die Funktion ist gegeben.

Gruß Stefan

**Comment by JensBonse** [comment]
Ich hatte das gleiche Problem. Damals hatte ich von der LXCCU auf die piVCCU geupdated. Dann hatte ich auf einmal einen Duty Cycle von über 60%. Konnte mir den Effekt auch nicht erklären. Dann habe ich auf RaspberryMatic umgestellt und der Duty Cycle ging auf einmal wieder runter auf 2%. 

An der HomeBridge hatte ich jedoch nichts verändert. Also gleiche Konfiguration der HomeBridge mit piVCCU und RaspberryMatic.

Somit würde ich darauf schließen, dass es irgendetwas an der CCU ist. Also kein Problem von  HomeBridge-Homematic.

**Comment by AdlerCentauri** [comment]
Hallo, ich habe seit ein paar Tagen auch die Homebridge installiert und auch bei mir schießt der DutyCycle seitdem in die Höhe.

**Comment by TheRealTremes** [comment]
Hallo, ich habe seit ein paar Tagen auch die Homebridge installiert und auch bei mir schießt der DutyCycle seitdem in die Höhe.

**Comment by sblogoshs** [comment]
Hallo.
Ich hatte Entwarnung gegeben weil es wieder normal schien, doch zu früh gefreut, inzwischen habe ich einen ständigen Wechsel, mal sind es keine 10% und kurz darauf kommen bei jeder Aktualisierung des Wertes 10% dazu. Während der ganzen Zeit werden nur die Daten der Energiezähler und des KeyMatic Schlosses empfangen, was natürlich auch so ist wenn ich die Homebridge aus dem System nehme, mit dem Unterschied das ich dabei nie über 10% komme.

Gruß Stefan
