### ISSUE TITLE
Seit Einsatz der Homebridge hoher DutyCycle

### ISSUE THREAD

**Issue by TheRealTremes** [thkl/homebridge-homematic#303]
Hallo, ich habe seit ein paar Tagen auch die Homebridge installiert und auch bei mir schießt der DutyCycle seitdem in die Höhe.

**Comment by Baenker** [comment]
Was heißt denn auch? Mein DC ist i. d. R. bei 0 oder 1. Abends beim Fernsehen bis zu 10. Meine Homebridge Installation beeinflusst meinen DC definitv nicht. Bei mir läuft die Homebridge aber auch schon sehr sehr lange...

**Comment by thkl** [comment]
Ja, das kommt daher das in der aktuellen npm Version versucht wird nicht alles via rega zu lösen sondern Zustände vom Interface direkt abgefragt werden, dieses hat eine Kommunikation zum Gerät zur Folge. Blöde Idee von mir ;o)

In der Github Version ist das glaube ich schon wieder gefixt, das npm dazu muss ich noch bauen ...
