### ISSUE TITLE
HM-ES-PMSw1-DR Anzeige Leistungsdaten

### ISSUE THREAD

**Issue by criticallimit** [thkl/homebridge-homematic#306]
Hallo alle! 
Kann mir jemand sagen ob der HM-ES-PMSw1-DR auch unterstützt wird? 
Wenn ja, wird er nur als Schalter angezeigt, oder gibt es auch Anzeige von Leistung, Spannung, Strom etc....
Danke!

**Comment by sebastianhegge** [comment]
Ich kann nur vom HM-ES-PMSw1-Pl berichten. [https://files.elv.com/Assets/Produkte/13/1302/130248/Downloads/130248_data.pdf](url) Wird als Modell POWERMETER angezeigt, zeigt aber keine Verbrauchsdaten an.
Ich habe dazu noch das hier gelesen [https://github.com/thkl/homebridge-homematic/issues/70](url), das ist aber ein anderes Gerät.

@thkl ist da mehr möglich? Wäre wirklich toll!

**Comment by sebastianhegge** [comment]
`<channel name="Waschmaschine" ise_id="1333" index="2" visible="true" operate="true">
  <datapoint name="BidCos-RF.OEQ0XXXXXX:2.ENERGY_COUNTER" type="ENERGY_COUNTER" ise_id="1336" value="3.600000" valuetype="4" valueunit="Wh" timestamp="1536700806" operations="5"/>
  <datapoint name="BidCos-RF.OEQ0XXXXXX:2.POWER" type="POWER" ise_id="1338" value="2.950000" valuetype="4" valueunit="W" timestamp="1536700854" operations="5"/>
  <datapoint name="BidCos-RF.OEQ0XXXXXX:2.CURRENT" type="CURRENT" ise_id="1335" value="31.000000" valuetype="4" valueunit="mA" timestamp="1536700854" operations="5"/>
  <datapoint name="BidCos-RF.OEQ0XXXXXX:2.VOLTAGE" type="VOLTAGE" ise_id="1339" value="234.000000" valuetype="4" valueunit="V" timestamp="1536700854" operations="5"/>
  <datapoint name="BidCos-RF.OEQ0XXXXXX:2.FREQUENCY" type="FREQUENCY" ise_id="1337" value="49.990000" valuetype="4" valueunit="Hz" timestamp="1536700854" operations="5"/>
</channel>`
Habe mal das dazugehörige XML kopiert ...
