### ISSUE TITLE
HMIP-Geräte werden sind nicht erreichbar - in Developer-Stand

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#308]
Nach Update von 109 auf die letzte Developer sind alle HMIP-Geräte nicht mehr erreichbar. Starte ich die Homebridge Instanz unter 109 sind sie wieder erreichbar. Im Debug-Modus kann ich erstmal keine Exceptions erkennen.

**Comment by thkl** [comment]
Hmm ich hab das aktuell auf dem Produktivsystem laufen. Da hängt zb eine HMIP-PSM Steckdose drin. Die liefert fleissig Daten und lässt sich schalten. Der HMIP Parameter in der Config ist gesetzt ?

Beim Start müsste dieses hier im Log auftauchen:

`
[7/16/2018, 6:53:35 PM] [HomeMatic CCU] CCU RPC Init Call on port 2010 for interface HmIP-RF.

...

[7/16/2018, 6:53:35 PM] [HomeMatic CCU] CCU Response for init at HmIP-RF. with http://192.168.178.20:9092...Value ("") Error : (null)
`

Dann hängt er auf der IP Schnittstelle und sollte von dort auch Daten bekommen
