### ISSUE TITLE
SW in Developer-Stand schalten nicht

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#309]
Im aktuellen Developer-Stand schalten HM-LC-Sw4-DR-2 nicht. Mit der 109 funktioniert es ohne Probleme. Gleiche config einfach nur die Instanz als pi statt mit homebridge -P /home/pi/node_modules/homebridge-homematic -U /home/pi/homebridge1 mit homebridge -U /home/pi/homebridge1 gestartet. Dimmer funktionieren allerdings scheint es auch Probleme mit den Switches über HMW-IO-12-Sw14 zu geben.

**Comment by thkl** [comment]
Sicher das es in der aktuellen GitHub Version auch so ist.  Dort hatte ich die Switches korrigiert.
