### ISSUE TITLE
Doors und Windows nicht unterstützt

### ISSUE THREAD

**Issue by jplck** [thkl/homebridge-homematic#31]
Hallo,

Kontaktsensoren die unter doors/windows eingetragen werden, werden als "nicht unterstützt" angezeigt. 

Die Kontaktsensoren werden angezeigt, wenn sie nicht unter eine der genannten optionalen Gruppen eingetragen werden. Sobald man sie allerdings einer der Gruppen hinzufügt, werden sie scheinbar nicht mehr unterstützt.

Getestet unter iOS 10 in der home App. Die homebridge + homematic Plugin läuft auf einem RPi3 in der aktuellsten Version.

Vielen Dank!

**Comment by Samfox2** [comment]
"windows" funktioniert bei mir sogar mit Benachrichtigung auf den Startbildschirm, "doors" leider ebenfalls nicht 😔

**Comment by thoduh** [comment]
"windows" funktioniert zum Teil. Siri antwortet noch etwas falsch "Nur ein motorisierte Fenster ist offen..."
"doors" funktioniert leider nicht

**Comment by thkl** [comment]
Mal bitte mit 0.0.44 testen.  
Um mit der HomeApp kompatibel zu sein kann ich keine eigenen Gerätetypen nutzen. Deswegen werden Türen als sog. motorisierte Türen (nur diese haben einen Zustand offen und geschlossen) und Fenster als motorisierte Fenster abgebildet. 

Es gibt zwar auch ein Türschloss Gerät aber das ist eher für eine Keymatic geeignet.

**Comment by Samfox2** [comment]
Immer noch "nicht unterstützt"

**Comment by Samfox2** [comment]
Kannst du dir das bitte nochmal anschauen? Ich hab grad mal testweise ein paar Sachen bei "Doors" in Richtung "Window" geändert, bringt aber alles irgendwie nichts...

**Comment by thkl** [comment]
So die Türen/Fenster sollten jetzt gehen
