### ISSUE TITLE
Homematic HMIP-RF 55 Taster

### ISSUE THREAD

**Issue by BerkTam** [thkl/homebridge-homematic#310]
Könnte man diese HMiP-RF Taster noch bitte aufnehmen?

Ich habe die zwar schon in Homebridge Homematic integriert, allerdings schießt danach
der DutyCycle extrem in die Höhe. 

Schaue ich mir in der Eve-App die Zustände eines dieser HMiP Bewegungsmelder an, so sieht 
man dort dass er sämtliche Bewegungen im tracked, was die erhöhte Abfrage bzw. Traffic wohl erklären könnte und evtl. auch den erhöhten DutyCycle. 

Danke

**Comment by thkl** [comment]
Nabend, 
meinst Du zufällig den hier: HMIP-WRC2?
Versuch mal bitte folgendes. Editier mal die config.json in .homebridge und dort im Bereich des Homematic Plugins folgendes hinzufügen:

```
"services": [
	{ "type": "KEY_TRANSCEIVER",
          "service": "HomeMaticHomeKitKeyService"
	}]
```

Wichtig, das ist ein JSON File also das , am Ende des letzten Eintrages vor dem was Du hinzufügst nicht vergessen. Validität das JSON Files kann zb unter jsonlint.com getestet werden.
