### ISSUE TITLE
Motorleinwand offen/geschlossen

### ISSUE THREAD

**Issue by udochrist** [thkl/homebridge-homematic#313]
Hallo, ich nutze einen Jalousie Aktor um eine Motorleinwand anzusteuern. Funktioniert auch bestens. Was mich etwas „stört“ ist die Benamung von offen /geschlossen.  Hier ist’s ja genau umgedreht wie bei einer Jalousie. Wennn die Leinwand eingefahren ist wäre sie geschlossen und bei ausgefahren eben geöffnet. Die Bewegung selbst stimmt, deswegen sollte ein umklammern am Aktor auch nicht das korrekte Verhalten zeigen. 

Absolut nicht das wichtige Thema, aber ich dachte ich frage mal nach ob sich was tricksen lässt. 

Danke
Udo

**Comment by thkl** [comment]
Hallo,

Was ist denn jetzt das Problem ?

**Comment by tkoenig** [comment]
Hallo, 

ich glaube nicht das Problem lösbar ist, solange es für homekit nicht spezielle accessories gibt.

Ich habe das selbe Problem mit meiner 
Wenn ich via Siri sage "Mach die Markise zu", wird sie ausgefahren da sie wie eine Jalousie behandelt wird.
Wenn man es theoretisch umkehren/am Aktor umstecken  würde, macht es wiederum bei der grafischen Anzeige keinen Sinn.

**Comment by thkl** [comment]
Ach jetzt kapier ich das Problem. Ja das kann ich so nicht lösen. Das Problem liegt daran, das viele Geräte, die es nicht in HomeKit gibt, durch ähnliche Geräte ersetzt werden. Damit muss man natürlich mit den Unzulänglichkeiten leben, die sich daraus ergeben.

**Comment by udochrist** [comment]
Na die Markise kann man einfach in Beschattung umbenennen und schon klingts logischer :-)
