### ISSUE TITLE
HmIP-SRH Position

### ISSUE THREAD

**Issue by tiirex9** [thkl/homebridge-homematic#314]
Kann man in der Home-App ablesen in welchem Zustand das Fenster ist?
Geöffnet, Gekippt, Geschlossen? Oder wird hier nur Offen (für die ersten beiden) und Geschlossen für letzteres angezeigt?

Könnte man den Zustand nicht theoretisch mithilfe der "Current Position"-Characteristric darstellen? Ich vermute fast, dass dann in der Home-App aber auch nur der Prozentwert abzulesen wäre.
Hat hier jemand mal ein wenig experimentiert?

**Comment by tiirex9** [comment]
Nevermind. *facepalm*
Ich hätt ja auch gleich nachschauen können.

Aus dem Code wird ersichtlich, dass genau das bereits gemacht wird.
```javascript
    this.cwindow = window.getCharacteristic(Characteristic.CurrentPosition);
    this.cwindow.on('get', function(callback) {
      that.query("STATE",function(value){
        if (callback) {
          switch (value) {
            case 0:
            callback(null,0)
            break;
            case 1:
            callback(null,50)
            break
            case 2:
            callback(null,100)
            break
            default:
            callback(null,0)
          }
```

**Comment by tiirex9** [comment]
Jetzt muss ich das doch nochmal aufmachen. Ich hab mir jetzt die entsprechenden HmIP-SRH Teile gekauft und eingerichtet, aber es ist leider keine Position ersichtlich. Nur "offen" für offen und gekippt und ansonsten "geschlossen". Muss ich dafür irgendwas ändern?

**Comment by thkl** [comment]
Kann sein, das dieser Aktor nicht als Fenster sondern nur als Kontakt gemappt wird. Muss ich mir anschauen

**Comment by tiirex9** [comment]
Kann man das nicht irgendwie mit den doors und windows Konfigurationsoptionen "erzwingen"?
Was geb ich da genau an, wenn es sich um einen HmIP Gerät handelt? Ist das auch hier eine Kombination aus Typenbezeichnung + "." + Seriennummer + ":" + Kanal?
Also z. B. HmIP-SRH.0007D70XXXXXXX:1 ? Das funktioniert bei mir nämlich nicht. Oder zumindest hat es keine Auswirkung auf die Accessories in der Home App. 
Habe sowohl den persist als auch den accessories Ordner gelöscht und die Bridge neu hinzugefügt. Trotzdem alles unverändert.

**Comment by justroot1337** [comment]
Bei mir geht es leider nicht. Die Änderung aus https://github.com/thkl/homebridge-homematic/issues/120
ist bereits drin. Meine Konfiguration sieht so aus:
`          "windows": [
                "HmIP-SRH.000XXXXXXXX:1"
            ],
`
Ich bekomme die 505 leider nicht angezeigt. Irgendeine Idee?

**Comment by Black-Shadowcat** [comment]
Moin, gibts eine Lösung? 
Bei mir wird nach einer 90° Drehung (weit offen) nur offen angezeigt und wenn ich den Drehgriff um 180° drehe (Kippstellung) wieder geschlossen. In der CCU wird es richtig dargestellt.

Zitat thkl: Kann sein, das dieser Aktor nicht als Fenster sondern nur als Kontakt gemappt wird. Muss ich mir anschauen

wird bei mir als Kontakt gemappt, wie alle Fenster ...
