### ISSUE TITLE
Homematic Variable wird immer wieder in der Home App zurückgesetzt

### ISSUE THREAD

**Issue by AbdulAlBane** [thkl/homebridge-homematic#315]
Guten Morgen,

ich möchte die "Anwesenheit" Variable aus Homematic innerhalb der Home App setzen. Dazu habe ich sie über die Homebridge entsprechend sichtbar gemacht. Das klappt auch alles.
Wenn ich allerdings versuche, die Variable in der Home App manuell oder per Automation zu setzen, setzt sich die Variable wieder automatisch zurück, ohne dass in Homematic eine Variablenänderung ausgelöst wird, auf die ich reagieren könnte. Den "Umweg" über den Trigger (virtueller Taster wird aktiviert, wenn sich die Variable ändert) habe ich versucht, allerdings erfolglos (Variablenänderung wird gar nicht registriert).

Gruß
Alex

**Comment by hoermiller** [comment]
Hatte das selbe Problem. Die Variable „Anwesenheit“ ist anscheinend nicht unbedingt für die Anwesenheit im Haus gedacht sondern vielmehr eine systemvariable die gesetzt wird wenn das System neu gestartet wird. Dadurch verändert sich der Wert und gibt an ob die ccu neu gestartet wurde oder nicht. Ich habe das Problem folgendermaßen gelöst. Die Variable „Anwesenheit“ ist die einzige Variable die nicht gelöscht werden kann. Ich habe sie daher in „ccu_status“ umbenannt und eine neue Variable „Anwesenheit“ erstellt. Diese Variable habe ich dann in der Homebridge config angegeben. Funktioniert seitdem wunderbar. Wichtig ist natürlich noch anzumerken, dass Variablen direkt als Schalter bedient werden. Es ist kein zusätzliches Programm in der ccu notwendig um den Wert zu ändern.

**Comment by AbdulAlBane** [comment]
Perfekt, danke. So klappt es jetzt 👍
