### ISSUE TITLE
Homematic IP Wassersensor HmIP-SWD wird nicht unterstützt

### ISSUE THREAD

**Issue by AbdulAlBane** [thkl/homebridge-homematic#317]
Guten Abend, 

aktuell scheint der Homematic IP Wassersensor noch nicht unterstützt zu werden, kann das sein? Wäre toll, wenn sich der Sensor noch integrieren ließe. Ggf. kann die non-IP Variante entsprechend abgewandelt werden. 

Parameterliste habe ich angehängt: 
![image](https://user-images.githubusercontent.com/37419381/43848724-e58533e4-9b33-11e8-936e-b83f6c8c9ef4.png)

Beste Grüße
Alex

**Comment by xerabo** [comment]
Das wäre mir auch wichtig.

**Comment by adrianoje** [comment]
Ist es irgend wie mögliche die HMIP Geräte wie den Wassersensor manuell einzufügen? Habe das gleiche Probelm mit meine er HMIP ASIR Sirene - diese lässt sich nciht zu Homekit hinzufügen...

**Comment by t-rex-2000** [comment]
man könnte diesen doch über die services integrieren?

**Comment by adrianoje** [comment]
> man könnte diesen doch über die services integrieren?

Hallo T-Rex!
Danke für die Rückmeldung! Haste hierzu eventuell passende Anleitungen wie man das macht? Eventuell den Verweis auf irgend ein existierenden Thread? Ich denke das würde sehr vielen Leuten die Möglichkeit geben selbst Ihre Gerätschaften hinzuzufügen - ohne auf ein Update vom Plugin zu warten.

Danke und Grüße!

**Comment by t-rex-2000** [comment]
ich habs bis jetzt auch nur theoretisch gelesen, noch nicht zum probieren gekommen. habe folgendes gefunden:

You own a device that is not currently working with the default implementation here? No problem. You can create custom service classes. With a little bit of knowledge from the existing classes in the ChannelServices folder, this should not be a big deal. Copy the HomeMaticHomeKitDummyService and create your own Serviceclass.

All definitions for the existing classes are located in ChannelServices/channel_config.json. There is a key for each Homematic channeltype and the corresponding name of the service class as value. Be Aware: your personal changes in that file will be overridden by the next update. So you have to set them up in your config.json:

As a sample: the device with the channel WEATHER of the device with type HM-WDS10-TH-O will use the service HomeMaticHomeKitCuxDThermostatService

"services": [
	{ "type": "HM-WDS10-TH-O:WEATHER",
          "service": "HomeMaticHomeKitCuxDThermostatService"
	}]

**Comment by CNpunkt** [comment]
Ich habe heute mal versucht den HmIP-SWD Wassersensor ans laufen zu bekommen.

Über nachfolgenden Eintrag in der config.json taucht der Wassersensor anschließend in der Home App auf:
`"services": [
            { "type":"HmIP-SWD:WATER_DETECTION_TRANSMITTER",
              "service":"HomeMaticHomeKitLeakSensorService"
            }],
`

Allerdings reagiert der Sensor in der Home App noch nicht auf einen Alarm/Ereignis. Ich glaube, dass die Ereignisse in der Serviceklasse "HomeMaticHomeKitLeakSensorService.js" nicht zu den ausgelösten Ereignissen des HmIP-SWD passen.
Debug log der ausgelösten Ereignisse:
![image](https://user-images.githubusercontent.com/16060613/48313221-6f129780-e5b9-11e8-80f9-3e63d99c5836.png)

Ich vermute mal, dass in der "HomeMaticHomeKitLeakSensorService.js" das Mapping angepasst werden muss, allerdings reicht dafür mein Verständnis der Channels nicht aus um dies durchzuführen:
![image](https://user-images.githubusercontent.com/16060613/48313249-d2042e80-e5b9-11e8-9aaa-e10431b3f20a.png)

Vielleicht kann uns ja hier noch jemand unter die Arme greifen der sich besser mit den Services und den Channels auskennt.

**Comment by t-rex-2000** [comment]
wo hast du den eintrag denn reingesetzt, kannst du den teil der config.json bitte posten

**Comment by CNpunkt** [comment]
> wo hast du den eintrag denn reingesetzt, kannst du den teil der config.json bitte posten

![image](https://user-images.githubusercontent.com/16060613/48313351-64590200-e5bb-11e8-97aa-45d9da3a5fc3.png)

**Comment by t-rex-2000** [comment]
super danke, werde ich auch mal testen. sind die variables auch angepasst?

**Comment by CNpunkt** [comment]
> super danke, werde ich auch mal testen. sind die variables auch angepasst?

> Allerdings reagiert der Sensor in der Home App noch nicht auf einen Alarm/Ereignis. Ich glaube, dass die Ereignisse in der Serviceklasse "HomeMaticHomeKitLeakSensorService.js" nicht zu den ausgelösten Ereignissen des HmIP-SWD passen.

Du hast aber schon gelesen, dass dadurch zwar der Sensor in der App auftaucht aber noch nicht funktioniert oder?
Ja, ich habe eine Systemvariable aufgenommen aber die Lösung gefällt mir nicht so gut.

Ich hoffe, dass uns noch jemand bei der Anpassung der Klasse "HomeMaticHomeKitLeakSensorService.js" helfen kann: [post](https://github.com/thkl/homebridge-homematic/issues/317#issuecomment-437668269)

**Comment by t-rex-2000** [comment]
ja habe ich gelesen, ist der eintrag in variables eventuell dafür verantwortlich?

**Comment by CNpunkt** [comment]
> ja habe ich gelesen, ist der eintrag in variables eventuell dafür verantwortlich?

Nein, da bin ich mir sehr sicher.

**Comment by adrianoje** [comment]
Versuche ich heute Abend auch mal mit der 1.10 plugin version.
Habt Ihr denn generell Push hinbekommen?
Ich finde es bei Rauchmelder und Wassersensoren sehr wichtig dass ich eine HomeKit push Mitteilung bei einem ausgelösten Alarm erhalte (bei einem Wasserbruch z.B)

Ich teste mal heute Abend :-)

**Comment by t-rex-2000** [comment]
schau mal hier vorbei:  https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitLeakSensorService.js

**Comment by AWeidenbacher** [comment]
Hallo,

ich hab jetzt heute auch mein neues HmIP-SWD Gerät via Homebridge in HOMEKIT eingebunden - hat super funktioniert!
Aber was mir nicht klar ist - brauche ich Variablen und wenn ja für was?

Gibt es zudem schon eine Lösung für die Übertragunf der Alarmmeldung in Richtung HOMEKIT?

THX für eure Unterstützung
Andreas

**Comment by mdietrich** [comment]
Hallo zusammen,

ich hatte das gleiche Problem und habe mir dafür eine Erweiterung geschrieben, die nun auch bei Feuchtigkeit oder Nässe in Homekit Alarm schlägt.

Gruß,
Mario

**Comment by AWeidenbacher** [comment]
Hallo Mario,
das klingt interessant - würde mich freuen, wenn du deine Erweiterung mit Guideline hier publizieren könntest....

Danke und Gruß
Andreas

**Comment by mdietrich** [comment]
Hallo Andreas,

die Änderungen sind in obigem Pull-Request enthalten. Wenn du jetzt schon testen magst, kopierst du dir:

- die neue HomeMaticHomeKitWaterSensorService.js
- die erweiterte channel_config.json

in Ordner ChannelServices. Alternativ zur Erweiterung der channel_config.json kannst du auch wie oben beschrieben eine Anpassung der config.json vornehmen. Als Service dann halt auch "HomeMaticHomeKitWaterSensorService" einsetzen:

```
"services": [
  { "type":"HmIP-SWD:WATER_DETECTION_TRANSMITTER", 
  "service":"HomeMaticHomeKitWaterSensorService" }
],
```

Das HmIP-SWD Gerät sollte nach einem Neustart anschließend in Homekit auftauchen und nach der Aktivierung der Mitteilungen in der App auch Push-Nachrichten verschicken, wenn Feuchtigkeit oder Nässe festgestellt wird.

Da ich das Projekt Code-technisch nicht so gut kenne wollte ich nicht den bestehenden LeakService anpassen, sondern habe einen neuen erstellt. Ich hoffe das passt soweit.

Viele Grüße,
Mario

**Comment by hillinator** [comment]
Hallo @thkl, wann wird die Version mit HmIP-SWD support released? Ich sehe, dass vor 12 Tagen bereits  der Code angepasst wurden.
