### ISSUE TITLE
Konfiguration

### ISSUE THREAD

**Issue by offle** [thkl/homebridge-homematic#32]
Hallo zusammen,

Evtl. Bin ich nur zu blöd, das zu finden. Gibt es eine Übersicht, welche Arten von Geräten in der Konfiguration unterstützt werden? Im Beispiel ist z.B. Nur "doors" erwähnt. In einem anderen Issue habe ich aber gelesen, dass es auch "windows" gibt. Was gibt es noch alles?

Vielen Dank schonmal im Voraus und sorry, wenn ich mich zu blöd anstelle ;)

Ole

**Comment by thkl** [comment]
Folgende Kanaltypen werden unterstützt:

"SENSOR","DIGITAL_OUTPUT","SWITCH","DIMMER","BLIND","CLIMATECONTROL_RT_TRANSCEIVER",
    	"THERMALCONTROL_TRANSMIT","SHUTTER_CONTACT","ROTARY_HANDLE_SENSOR","MOTION_DETECTOR",
    	"KEYMATIC","SMOKE_DETECTOR","SMOKE_DETECTOR_TEAM","SMOKE_DETECTOR_TEAM_V2",
		"WEATHER_TRANSMIT","WEATHER","LUXMETER","RAINDETECTOR","RAINDETECTOR_HEAT","PROGRAM_LAUNCHER","VARIABLE",
    	"RGBW_COLOR","TILT_SENSOR","CLIMATECONTROL_REGULATOR","KEY","VIRTUAL_KEY"

**Comment by offle** [comment]
Danke
