### ISSUE TITLE
Umzug in einen neuen Docker container?

### ISSUE THREAD

**Issue by udochrist** [thkl/homebridge-homematic#321]
Ich wollte die Homebridge (mit homematic Plugin) komplett in einen neuen Container (anderes Docker Image) umziehen.

Ich habe die Plugins passend installiert, die config.json und die Dateien aus persistence und accessories in den neuen Container umkopiert. Nach stop des alten Containers und hochfahren des neuen erhalte ich in der home.app lediglich dass keine der Komponenten aktualisiert werden kann. Laut logfile des Containers wurden alle Geräte aus der ccu aber erkannt.

Kann es sein dass das Plugin noch irgendwo sonst einen key/Status/Token angelegt hat den Apple benötigt oder lesen will? Starte ich den alten Container wieder, dann ist sofort alles da. Beide Container laufen übrigens auf demselben Rechner, allerdings natütlich nicht gleichzeitig.

**Comment by thkl** [comment]
Schaut so aus als ob HomeKit den Status der Homebridge nicht mehr updaten will. Irgendwo hab ich schon mal davon gelesen. Das ist allerdings kein HomematicPlugin Problem. 

Ggf könnte es helfen, den usernamen in der config zu ändern. Dadurch ist die Homebridge für HomeKit komplett neu.  (Evtl. verpufft dadurch aber die Geräte/Raum Zuordnung)

**Comment by udochrist** [comment]
Gefunden. Der zweite docker Container hat sich - obwohl der erste nicht aktiv war - auf ein falsches Interface für Bonjour/Avahi gebunden. Damit war er für HomeKit wohl nicht mehr auffindbar. 
Hab ich leider erst nach dem löschen meiner Home config mit knapp 100 devices festgestellt. Na ja. Ist wenigstens mal wieder alles sauber eingerichtet....

Doku hier der Vollständigkeit halber
