### ISSUE TITLE
Unterstützung für HmIP-SLO

### ISSUE THREAD

**Issue by xerabo** [thkl/homebridge-homematic#322]
Ist es möglich obigen Sensor einzubinden? Das wäre wirklich klasse.

**Comment by thkl** [comment]
Was macht der denn ?

**Comment by rpdever** [comment]
Any updates?

**Comment by MarcusFriedl** [comment]
Hi @thkl ,
gibts was neues? Hast du vielleicht einen Tip, wie man die channel_config.json anpassen kann, sowie eine dazugehörige .js?
