### ISSUE TITLE
HM-PBI-4-FM - Kein Event

### ISSUE THREAD

**Issue by SpeedmaxX** [thkl/homebridge-homematic#326]
Hallo,

habe den 4-Fach Taster HM-PBI-4-FM in Homebridge eingebunden. 

In Homekit habe ich dann "1xDrücken" mit dem Schalten einer Szene verbunden, leider ohne Erfolg. Hat jemand da Erfahrungen mit?

VG - Markus

**Comment by thkl** [comment]
Versuch mal diese Taste einem Dummy Programm auf der CCU zuzuordnen. Das muss nichts machen, außer durch den Key getriggert werden. 
Mit der Aktion wird dem Taster überhaupt erst mitgeteilt, das er seine Key Events bitte der CCU mitzuteilen hat.

**Comment by SpeedmaxX** [comment]
hm, hat leider nicht geklappt. Hab ein Programm angelegt und unter "wenn" den einfachen Tastendruck hinterlegt. Leider noch ohne Erfolg.

**Comment by SpeedmaxX** [comment]
Hi, hat noch jemand eine Idee?

**Comment by Traxios** [comment]
Und hier noch eins:

[2018-11-17 21:39:38] [HomeMatic CCU] rpc <- system.multicall on BidCos-RF.
[2018-11-17 21:39:38] [HomeMatic CCU] RPC event for BidCos-RF.OEQ0614087:1 PRESS_SHORT with value true
[2018-11-17 21:39:38] [HomeMatic CCU] Accessory WZ Glastür Doppeltaster links found -> Send Event

**Comment by Traxios** [comment]
Versionen:

/usr/lib
├── homebridge@0.4.45
├── homebridge-homematic@0.0.109
└── npm@6.4.1

**Comment by Sheldor81** [comment]
Hallo,

ich habe das gleiche Problem mit dem Homematic IP SMI Bewegungsmelder/Taster der Bewegungsmelder funktioniert aber die Tasten leider nicht. Gibt es schon eine Lösung für das Problem.
