### ISSUE TITLE
Variablen basierendes Security System

### ISSUE THREAD

**Issue by dhuuk** [thkl/homebridge-homematic#328]
Hallo,

wenn ich HomeBridge Start kommt folgende Fehlermeldung:

`No Class found in /usr/lib/node_module/homebridge-homematic/ChannelServices/HomeMaticHomeKitAlarmSystemService.js or /root/.homebridge/HomeMaticHOmeKitAlarmSystemService.js
`

meine Config.Json schaut so aus:

```
{
 "bridge": {
 "name": "Homebridge",
 "username": "CC:22:3D:E3:CE:30",
 "port": 51826,
 "pin": "031-45-154"
 },

 "platforms": [{
 "platform": "HomeMatic",
 "name": "HomeMatic CCU2",
 "ccu_ip": "192.168.2.253",
 "filter_device": [],
 "filter_channel": [],
 "outlets": [],
 "doors": [],
 "programs": ["Test_Telegram"],
 "accessories": [],
 "subsection": "AppleHomekit",
 "variables": ["Anwesenheit", "Vollschutz"],
 "enable_hmip":"true",
 "variable_update_trigger_channel":["HomeBridge Trigger"],
 "special":[
		{
		"name" : "AlarmSystem",
		"type" : "HM-THKL-VARSEC",
		"parameter" :	{
				"trigger" : "BidCos-RF.BidCos-RF:20.PRESS_SHORT",
				"variable" : "SecTest"
				}
		}
],
 "services": [
		{
		"type" : "HM-THKL-VARSEC",
		"service" : "HomeMaticHomeKitAlarmSystemService"
		}
]
 }
]
}
```

**Comment by Duude4711** [comment]
Das wiki scheint da einen Fehler drin zu haben, nimm beim "trigger" mal das erste " BidCos-RF. " raus.

**Comment by royalflashii** [comment]
der channelservice wird nicht gefunden. war bei mir auch ein Problem worauf ic noch keine lösung gefunden habe. aber werde heute nachmittag mal testen die js datei manuell zum ordner hinzuzufügen. die richtige js datei findest du auf der satrseite vom homebirdge-homamatic forum

**Comment by iuliusmaximilian** [comment]
Die ist im Release m.E. noch nicht enthalten, lasst eine zweite Instanz mit dem Developer laufen ...

https://github.com/thkl/homebridge-homematic/wiki/Update
