### ISSUE TITLE
Abwesenheit und Thermostate

### ISSUE THREAD

**Issue by thorque** [thkl/homebridge-homematic#329]
Hallo,

ich versuche herauszufinden, wie man eine Szene definiert, für eine Abwesenheitsszenario. In ioBroker habe ich dafür den MANU_MODE auf 17° gestellt. Damit war Control_Mode des Thermostat auf Manuell und der wurde solange beibehalten, bis ich den wieder deaktiviert habe (über eine Regel, die gefeuert wurde, sobald ich wieder zu hause war).

Mit HomeKit kann ich nur das Thermostat auf An oder Aus stellen (Aus ist im Winter etwas zu kalt) oder die Temperatur auf 17°. Da der AUTO_MODE allerdings aktiv bleibt, wird die Temperatur beim nächsten Schaltzyklus (z.B. 18:00 Uhr) auf 22° gesetzt. 

Wie kann man diese Herausforderung mit Homebridge und HomeKit realisieren?

**Comment by t-rex-2000** [comment]
hallo,

ich habe dies mit der anwesenheitssteuerung realisiert. dazu benötigt man allerdings eine steuerzentrale wie ipad,  tv oder homepod. bei mir funktioniert das sehr zuverlässig.

**Comment by pbksol** [comment]
Möglichkeit a)
Du lässt die Heizung dauerhaft auf Manuell und nimmst die Steuerung für die einzelnen Zeitabschnitte über HomeKit vor. Das dürfte die einfachste Variante sein.

Möglichkeit b)
Du legst eine Variable in der Homematic an, die in HomeKit geschaltet werden kann und diese setzt dann den Modus auf Manuell oder Automatisch. Und wenn man es dann ganz wild treiben will baut man das ganze dann noch so, dass die Temperaturen per Skript übernommen werden – aber das hat dann mit diesem Plugin nichts mehr zu tun.
