### ISSUE TITLE
Luftfeuchtigkeit 0%

### ISSUE THREAD

**Issue by gernot1972** [thkl/homebridge-homematic#33]
Ich habe mehrere Temperatursensoren und auch Differenztemperatursensoren im System, die keinen Datenpunkt Luftfeuchtigkeit haben.
Leider werden nur diese in der Übersicht herangezogen für die durchschnittliche Luftfeuchtigkeit in der Home App :-(
Kann man da etwas dagegen machen?

**Comment by thkl** [comment]
In Kürze wird das gehen.

**Comment by thkl** [comment]
Die aktuelle GitHub Version kann das jetzt. Hier kann in ChannelServices/channel_config.json eingestellt werden, welcher HomeKit Service für welches HM Gerät benutzt werden soll.
Ich bin noch nicht dazu gekommen eine Doku zu bauen.

**Comment by gernot1972** [comment]
wie kommt man zur aktuellen Version?
Mit sudo npm update -g homebridge-homematic
bekommt man ja noch nichts...

lg, Gernot

**Comment by thkl** [comment]
Version von hier https://github.com/thkl/homebridge-homematic/archive/master.zip  nehmen und nach /usr/local/lib/node_modules/homebridge-homematic kopieren

**Comment by gernot1972** [comment]
Sehe ich das richtig, dass ich jetzt nur noch meine Temperatursensoren (ohne Humidity Kanal) in der config Datei aufnehmen muss:

das sind HM-WDS30-T-O und HM-WDS30-OT2-SM
z.B. so:


{
			  "type" : "HM-WDS30-T-O",
			  "filter": [
				"TEMPERATUR"
			]
                       
		},

{
			  "type" : "HM-WDS30-OT2-SM",
			  "filter": [
				"TEMPERATUR"
			]
                       
		},

im channelconfig eine neue Type (z.B. Temperatur) mache mit einem neuen Service (z.B. „HomeMaticHomeKitThermostatTemperaturService") als eine Kopie von „HomeMaticHomeKitThermostatWeatherService“ Ohne Humidity???
z.B. so:

{
	   "type": „TEMPERATUR",
	   "service": "HomeMaticHomeKitThermostatTemperaturService"
	},


und alles in der json Datei einstelle?

oder muss da zusätzlich etwas angepasst werden???



lg, Gernot

**Comment by thkl** [comment]
Jain. Es müsste ein Eintrag in der channel_config gemacht werden und eine neue .js Datei erzeugt die nur noch den Temperatur Datenpunkt abfragt. Ich klöppel das mal im Laufe des Tages  zusammen

**Comment by thkl** [comment]
So ich hab das mal eingebaut. Ich kann es nicht testen, mangels Geräten. Das neue Servicefile heisst HomeMaticHomeKitThermometerService.js

**Comment by gernot1972** [comment]
Ich werde es gerne am Abend mal Testen😄 und gebe dann Rückmeldung!

Sent from a mobile device. I appologize for the brevity and typos.

**Comment by gernot1972** [comment]
JA - funktioniert - die Luftfeuchtigkeit 0% wird jetzt nicht mehr angezeigt.
Allerdings gibt es noch immer einen einstellbaren Zielwert - den bekommt man nicht weg, oder?

Zur Luftfeuchtigkeit noch: Ich habe einige HM-TC-IT-WM-W-EU Thermostate, die Luftfeuchtigkeit anzeigen.
Wieso werden diese Werte eigentlich nicht in der Übersicht angezeigt in der Home App?

Noch eine weitere Frage:
Ich habe gesehen, dass jetzt motorisierte Fenster in HomeKit sein sollen.
Wäre das nicht eine Gelegenheit den motorisierten Fensterantrieb der Homematic zu unterstützen?

Ich habe den HM-Sec-Win Kanal1 einmal in mein HomeKit Gewerk gegeben - er taucht aber leider noch nicht auf.
Könnte jedenfalls helfen bei der Implementierung, falls gewünscht.

lg, Gernot

**Comment by thkl** [comment]
Stimmt das Thermometer könnte man readonly machen. 
Und ja die anderen Thermostate könnten Luftfeuchtigkeit anzeigen. Das geht in der neuen Verdion recht ez. einzubauen. 

Motorfenster "missbrauche" ich aktuell schon als Fensterkontakte damit Siri die Frage nach offenen Fenstern beantworten kann.  Ich schaue mal in die Doku wie ich das umsetzten kann.

**Comment by thkl** [comment]
Ich hab das mit dem Thermometer mal geändert. Mal bitte auf dem PI das File HomeMaticHomeKitThermometerService.js unter /usr/local/lib/node_modules/homebridge-homematic/ChannelServices gegen die GitHub Version tauschen. Dann sollte es gehen.

**Comment by thkl** [comment]
OK winmatic kann mal probiert werden ich hoffe es funktioniert einigermassen.
es muss in /usr/local/lib/node_modules/homebridge-homematic/ChannelServices die Datei channel_config.json getauscht und HomeMaticHomeKitWinMaticService.js hinzugefügt werden.

**Comment by gernot1972** [comment]
geht das mit dem Tauschen der Dateien eigentlich auch ohne Restart?

**Comment by thkl** [comment]
Nein, da die Geräte nur beim Start der Bridge von der CCU gelesen werden.
BTW Bitte mal hier https://github.com/thkl/homebridge-homematic/issues/37 weiter machen. Ich habe einen eigenen Issue für WinMatic aufgemacht

**Comment by gernot1972** [comment]
Könnte man die Actual_Temperature von den Thermostaten auch unter der Type Temperatur anzeigen lassen analog zur Luftfeuchtigkeit?
Momentan habe ich sie ja nur unter Temp. Zielwert und dann sehe ich sie leider erst bei der Bedienung eines Thermostat.

**Comment by MrKraecker** [comment]
Das Thema ist ja mittlerweile sehr alt, daher mal nochmal die Frage ist es möglich die Luftfeuchte auch unter der aktuellen Temperatur anzuzeigen? :)
