### ISSUE TITLE
Dimmer und Heizungssteuerung

### ISSUE THREAD

**Issue by SnFei** [thkl/homebridge-homematic#332]
Moin miteinander,

erstmal dickes Lob zu diesem Plugin. Jetzt zu meinen zwei Problemen. Das ganze wurde hier irgendwie schon behandelt, jedoch fehlt es mir an Verständnis/ Informationen die Fehler zu beseitigen oder vielleicht geht es einfach nicht. Zu meinem Setup. CCU2, Heizkörperthermostate HM-CC-RT-DN direkt verknüpft mit Wandthermostaten HM-TC-IT-WM-W-EU. Das ganze in 5 Räumen. Dazu noch 7 HM-LC-Dim1PWM-CV. 
Problem 1: Wenn ich in HomeKit die Temperatur ändere, egal ob beim Wandthermostat oder beim Heizungsthermostat, springt die Temperatur immer zurück auf den manuell eingestellten Wert vom Wandthermostat. Wie wäre da Abhilfe zu schaffen?

Problem 2: Die Dimmer werden immer beim anschalten auf 100% gefahren, egal welcher Wert vorher benutzt wurde. 

Da ich eher Anfänger bin, bitte ich euch mich nicht auseinander zu nehmen und vielleicht in „einfachen“ Worten mir Abhilfe zu schaffen

**Comment by roe1974** [comment]
Problem mit den Dimmer bei mir seit iOS 12

Wenn ich den Dimmer einschalte (also 100%) ... zeigt er in Home kurz 100% ... dann 0% (Lampe leuchtet aber) ... wechsel ich dann den raum einmal und wieder zurück steht dort dann "100%" ....

noch wer das problem ?

lg Richard

**Comment by iuliusmaximilian** [comment]
Bei mir verhält es sich etwas anders, wenn ich einen Dimmer einschalte 100% dann wird kurzzeitig der letzte Dimmwert angezeigt, bspw. 14% und nach ca. einer Sekunde aktualisiert er dann auf 100%. Ein Wechsel des Raumes ist aber nicht notwendig das passiert so automatisch bei mir.

**Comment by roe1974** [comment]
Bin jetzt auf eine ältere Version von "HomeMaticHomeKitDimmerService.js" umgestiegen..... die geht besser, hat diersen Fehelr nicht. Nur beim ausschalten wird kurz der letzte Dimmwert angezeigt....

`
'use strict';

var HomeKitGenericService = require('./HomeKitGenericService.js').HomeKitGenericService;
var util = require("util");
var curLevel=0;
var lastLevel=0;
var onc;

function HomeMaticHomeKitDimmerService(log,platform, id ,name, type ,adress,special, cfg, Service, Characteristic) {
    HomeMaticHomeKitDimmerService.super_.apply(this, arguments);
}

util.inherits(HomeMaticHomeKitDimmerService, HomeKitGenericService);


HomeMaticHomeKitDimmerService.prototype.createDeviceService = function(Service, Characteristic) {

    var that = this;
    var lightbulb = new Service["Lightbulb"](this.name);
    this.services.push(lightbulb);

    this.onc = lightbulb.getCharacteristic(Characteristic.On)

    .on('get', function(callback) {
     // that.log("Get On command.");
      that.query("LEVEL",function(value) {
       
       if (value==undefined) {
        value = 0;
       }

       that.state["LAST"] = value;
       // that.log("Ret On command. "+ value );
       if (callback) callback(null,value>0);

      });
    }.bind(this))

    .on('set', function(value, callback) {

     // that.log("Set On to " + value + " command.");


       var lastLevel = that.state["LAST"];
       if (lastLevel == undefined) {
        lastLevel = -1;
       }
	
	   if (((value==true) || ((value==1))) && ((lastLevel<1))) {
          //that.log("On Command send 100 to Level");
          that.state["LAST"]=100;
	      that.command("set","LEVEL" , 100);
       } else 
   
       if ((value==0) || (value==false)) {
          //that.log("Off Command send 0 to Level");
          that.state["LAST"]=0;
	      that.command("set","LEVEL" , 0);
       } else 
       
       if (((value==true) || ((value==1))) && ((lastLevel>0))) {
         // that.log("Do Nothing on is on");
         // Do Nothing just skip the ON Command cause the Dimmer is on
       }
       
       else {
          // that.log("Fallback set Lastlevel", lastLevel);
          that.delayed("set","LEVEL" , lastLevel,2);
       }


      callback();
    }.bind(this));


    var brightness = lightbulb.getCharacteristic(Characteristic.Brightness)

    .on('get', function(callback) {
      that.query("LEVEL",function(value){
       that.state["LAST"] = (value*100);
       if (callback) callback(null,value);
      });
      
    }.bind(this))

    .on('set', function(value, callback) {
      var lastLevel = that.state["LAST"];
      if (value!=lastLevel) {
      
        if (value==0){
       	  // set On State 
	      if ((that.onc!=undefined) && (that.onc.updateValue!=undefined)) {that.onc.updateValue(false,null);}
	    } else {
	      if ((that.onc!=undefined) && (that.onc.updateValue!=undefined)) {that.onc.updateValue(true,null);}
	    }
       
	    //that.log("Set Brightness of " + that.adress + " to " + value + " command. LastLevel is "+  lastLevel);
    	that.state["LAST"] = value;
        that.isWorking = true;
     	that.delayed("set","LEVEL" , value,5);
	  }
      if (callback)  callback();
    }.bind(this));

    that.currentStateCharacteristic["LEVEL"] = brightness;
    brightness.eventEnabled = true;

    this.remoteGetValue("LEVEL");

}


HomeMaticHomeKitDimmerService.prototype.endWorking=function()  {
 this.remoteGetValue("LEVEL");
}


module.exports = HomeMaticHomeKitDimmerService; 
`

**Comment by DSchumacher2104** [comment]
Ich vermute, dass ein downgarde auf v0.0.97 helfen wird. Ich hatte ähnliche Probleme, die nach dem downgrade verschwunden sind. Solange Thomas uns nicht weiterhilft, scheint das die beste Lösung zu sein.

**Comment by DSchumacher2104** [comment]
Auch dies sollte in der aktuellen Beta auf NPM gefixed sein, siehe hier:
#254
