### ISSUE TITLE
iOS 12 Homematic Programme nicht unterstützt

### ISSUE THREAD

**Issue by kwass59** [thkl/homebridge-homematic#333]
Die Programme erscheinen in der Home App, aber mit dem Tag "not supported".

Klaus

**Comment by iuliusmaximilian** [comment]
Kleiner Tipp und vielleicht ein Workaround: Ich verwende Programme aus Home über eine boolean Hilfsvariable die als Schalter angezeigt wird und das Programm triggert. Im Programm setze ich den Wert der Hilfsvariable wieder vor Ende des Programmes. Das hat den schönen Effekt, dass das Programm als Schalter angezeigt wird und man sieht wenn das Programm läuft.

**Comment by kwass59** [comment]
Herzlichen Dank,

für die schnelle Antwort. Werde ich morgen mal ausprobieren, bin noch unterwegs. Kümmert sich denn schon jemand grundsätzlich um das Problem ?

Mit freundlichen Grüßen 
Klaus

**Comment by kwass59** [comment]
Herzlichen Dank,für die schnelle Antwort. Werde ich morgen mal ausprobieren, bin noch unterwegs. Kümmert sich denn schon jemand grundsätzlich um das Problem ?Mit freundlichen Grüßen KlausOn 2 Oct 2018, at 11:38, iuliusmaximilian <notifications@github.com> wrote:Kleiner Tipp und vielleicht ein Workaround: Ich verwende Programme aus Home über eine boolean Hilfsvariable die als Schalter angezeigt wird und das Programm triggert. Im Programm setze ich den Wert der Hilfsvariable wieder vor Ende des Programmes. Das hat den schönen Effekt, dass das Programm als Schalter angezeigt wird und man sieht wenn das Programm läuft.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by roe1974** [comment]
Also bei mir funktionieren alle Programme unter iOS 12 ?!?!?!?!?

den Eintrag

"ios10" : true

hast Du in der config.json ?

lg Richard

**Comment by kwass59** [comment]
Hallo,
habe es dann doch mit der Systemvariablen realisiert und es funktioniert ohne Probleme. Ob es mit dem Eintrag iOS10=True geht werde ich aber auch noch testen. 
Nochmals schönen Dank für eure Hilfe. 

Grüsse
Klaus

**Comment by kwass59** [comment]
Nochmals schönen Dank für eure Hilfe.

Grüsse
Klaus
