### ISSUE TITLE
Upgrade auf CCU3 möglich ?

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#334]
Hallo, hat schon Jemand Erfahrung mit Homebridge und einem Upgrade auf die neue CCU3? Meine Frage ist, ob Homebridge die Geräte dann alle neu erkennt oder ob schlichtweg nur die CCU3 anstelle der CCU2 läuft aber dies für Homebridge keinen Unterschied macht. Bei über 120 Devices ist das für mich schon entscheidend für ein eventuelles Upgrade. Vielen Dank für eine Info.

**Comment by roe1974** [comment]
Ich bin von CCU2 -> Raspberrymatic ..... kein Problem.... also muss das mit der CCU3 auch gehen.
Backup eingespielt, darauf geachtet dass der raspi nachher die gleiche IP hat wie vorher die CCU2 ... und los geht es ;-)

lg Richard

**Comment by iuliusmaximilian** [comment]
siehe #345

**Comment by iuliusmaximilian** [comment]
Hat (fast) Problemlos geklappt: Ich habe den Rasp. mit Homebridge solange komplett vom Strom getrennt bis die CCU3 unter IP der CCU2 wieder vollständig lief.

**Comment by iuliusmaximilian** [comment]
Closed
