### ISSUE TITLE
HmIP-ASIR Sirene - Homebridge und Alarm Push Mitteilungen

### ISSUE THREAD

**Issue by adrianoje** [thkl/homebridge-homematic#337]
Hallo Leute,

bastle nun schon seit paar Tagen mit meiner CCU3, HomematicIP Geräten, Rasperry Pi 3x und Homebridge herum und habe schon viel erreicht! Eure Anleitungen sind super!

Was mir noch fehlt: Kann ich irgend wie manuell die HmIP-ASIR Sirene in die config.json eintragen? Ich würde die Sirene gerne in Homekit sehen mit der Funktion dass mir diese eine Push-Mitteilung schickt sobald Sie einen Alarm abgibt. :/

Die Alarmanlage scharf zu schalten habe ich durch eine verknüpfte variable "Alarmanlage" bewerkstelligt, das funktioniert recht gut :-)
Ein Programm "programs": hinzuzufügen habe ich auch hinbekommen - allerdings werden diese in Homekit nur als Schalter angezeigt - PushMitteilungen lassen sich hier nicht einstellen X/

Hier meine config - Vielen Dank :thumbup:

"name": "HomeMatic CCU",
"ccu_ip": "192.168.178.xxx",
"enable_hmip":"true",
"filter_device": [],
"filter_channel": [],
"outlets": [],
"doors": [],
"windows": [],
"programs": [],
"accessories": [],
"subsection": "Homekit",
"variables": ["Anwesenheit", "Automatikfunktionen", "Alarmanlage"]
}]

**Comment by iuliusmaximilian** [comment]
Hi, ich benutze zwar nicht die HmIP-ASIR sondern eine Drittanbietersirene an einem HMW-IO-12-Sw14-DR aber ich habe diese sehr gut über verschiedene Programme und Variablen in Home eingebunden. Schau dir mal https://github.com/thkl/homebridge-homematic/wiki/Variable-basierendes-Security-System an!

**Comment by adrianoje** [comment]
> Hi, ich benutze zwar nicht die HmIP-ASIR sondern eine Drittanbietersirene an einem HMW-IO-12-Sw14-DR aber ich habe diese sehr gut über verschiedene Programme und Variablen in Home eingebunden. Schau dir mal https://github.com/thkl/homebridge-homematic/wiki/Variable-basierendes-Security-System an!

Danke! Die Anleitung bin ich durch allerdings klappt es bei mir nicht: musstest Du "HomeMaticHomeKitAlarmSystemService" als neuen service im channels ordner hinzufügen? Bei mir gibts im channels ordner nur "HomeMaticHomeKitSecuritySystem" Und wenn ich das in der config.jaon angebe vekommenich die sirene in homekit - allerdings ohne funktionen :-(

List/Zeit mir bei meiner Konfig damit ich die Alarmsirene in Homekit bekomme zu helfen ? Kann mich gerne per Paypal oder ggfls HMIP Sirene erkenntlich zeigen. Komme leider nicht mehr weiter :-(
