### ISSUE TITLE
Expose system variables via homebridge

### ISSUE THREAD

**Issue by gubraun** [thkl/homebridge-homematic#34]
Hi,

is it possible to expose homematic system variables via homebridge, so I can see their status in the homekit app? E.g. to monitor the status of a homematic based alarm system.

Thanks,
Gunnar

**Comment by thkl** [comment]
Currently there is a way to map Boolean Variables to HomeKit Outlets.
You have to add the name of the variable to the config.json s variables key : 

"variables":["Name1","Name2"] ....
