### ISSUE TITLE
Homematic Installation

### ISSUE THREAD

**Issue by gold2605** [thkl/homebridge-homematic#341]
Hallo, ich komme echt nicht weiter. Ich bekomme das Homematic Plugin nicht mehr zum laufen.
Das mit der Datei ändert (:47) klappt nicht. Ich habe auch mal die Version 1.0.1 installiert, dort kann ich aber die Geräte nicht schalten (Temperaturen und Status werde übertragen. Jetzt habe ich wieder 0.9.0 installiert und die Datei geändert und bekomme folgende Meldung und die Homebridge stürzt sofort ab. 
`Okt 14 15:39:20 hbridge2 homebridge[11483]: [2018-10-14 15:39:20] [Nuki] Request to Nuki bridge 'http://192.168.0.13:8080' finished with status code '200' and body '{"callbacks": [{"id": 1, "url": "http://192.168.0.113:51826/"},{"id": 2, "url": "http://192.168.0.113:51827/"}]}'. null
Okt 14 15:39:20 hbridge2 homebridge[11483]: [2018-10-14 15:39:20] [Nuki] Webhook for plugin already exists.
Okt 14 15:39:22 hbridge2 homebridge[11483]: /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:34
Okt 14 15:39:22 hbridge2 homebridge[11483]:   this.setCurrentStateCharacteristic(this.channelnumber + ":TEMPERATURE",this.cctemp);
Okt 14 15:39:22 hbridge2 homebridge[11483]:        ^
Okt 14 15:39:22 hbridge2 homebridge[11483]: TypeError: this.setCurrentStateCharacteristic is not a function
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at HomeMaticHomeKitThermometerService.createDeviceService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:34:8)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at HomeMaticHomeKitThermometerService.HomeKitGenericService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:69:8)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at new HomeMaticHomeKitThermometerService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:9:45)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at HomeMaticChannelLoader.loadChannelService (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:95:19)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at device.channels.map.ch (/usr/local/lib/node_modules/homebridge-homematic/index.js:340:22)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at Array.map (<anonymous>)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at json.devices.map.device (/usr/local/lib/node_modules/homebridge-homematic/index.js:300:21)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at Array.map (<anonymous>)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at HomeMaticPlatform.buildaccesories (/usr/local/lib/node_modules/homebridge-homematic/index.js:288:16)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at regarequest.script.data (/usr/local/lib/node_modules/homebridge-homematic/index.js:234:9)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:43:9)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at emitNone (events.js:111:20)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at IncomingMessage.emit (events.js:208:7)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at endReadableNT (_stream_readable.js:1056:12)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Okt 14 15:39:22 hbridge2 homebridge[11483]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Okt 14 15:39:22 hbridge2 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Okt 14 15:39:22 hbridge2 systemd[1]: homebridge.service: Unit entered failed state.
Okt 14 15:39:22 hbridge2 systemd[1]: homebridge.service: Failed with result 'exit-code'.

Was mache ich den falsch? Gibt es keinen Installationsweg ohne anschließend eine Datei zu ändern?
Würde mich riesig über Hilfe freuen, die letzte Nacht musste schon daran glauben :-(....

**Comment by t-rex-2000** [comment]
versuch mal folgendes: npm install thkl/homebridge-homematic#master -g --unsafe-perm . hat bei mir  geholfen

**Comment by gold2605** [comment]
Hallo, okay,
