### ISSUE TITLE
Geräte antworten nicht!

### ISSUE THREAD

**Issue by Tom1802** [thkl/homebridge-homematic#343]
Hallo,

ich habe öfter das Problem, dass ich über den Fernzugriff (iPad als Schaltzentrale) den Hinweis bekomme, dass die Geräte nicht antworten. Ich habe in der config.json bereits die local_ip des Raspi angegeben..

Gibt es noch eine andere Möglichkeit?

**Comment by JensBonse** [comment]
Sind nur HomeBridge Geräte betroffen, oder auch offizielle HomeKit Geräte wie z.B. eine Philips Hue Bridge?

**Comment by JensBonse** [comment]
Was meinst du mit "öfter"? Kommst du nie per Fernzugriff drauf, oder nur manchmal nicht?

**Comment by Tom1802** [comment]
Sind nur HomeBridge Geräte angemeldet/betroffen.

Hm öfter, also fast immer dann wenn ich der Fernzugriff zugreifen möchte. Habe überlegt, ob ich in dem Router eine feste IP zuweise. Bringt das was ?

**Comment by Luftloch80** [comment]
Habe auch das Problem mit dem Fernzugriff. Tado läuft einwandfrei. Und in der HomeKit App wird auch verbunden gezeigt. Die Elgato Eve App sagt als Fehler das Homkit einen ungültigen Parameter liefert

**Comment by JensBonse** [comment]
Früher hatten wir mal das Problem, wenn ein HomeMatic Gerät einen für HomeKit ungültigen Wert liefert, dass auf HomeKit Seite z.B. keine Antwort etc. kam.

Ich würde mal alle HomeMatic Geräte rauswerfen und dann Eins nach dem Anderen hinzufügen. so könnte man dann eingrenzen an welchem Gerät es liegt.

**Comment by Tom1802** [comment]
Danke für die Antwort! 
Meinst du die HomeMatic Geräte aus dem Gewerk entfernen und dann wieder hinzufügen oder in der HomeKit-App direkt?

Mittlerweile habe ich von extern gar keine Aktualisierungen mehr.. Nur falls der Sensor auslöst, bekomme ich eine Nachricht, aber die Heizung von unterwegs steuern geht nicht  mehr.
