### ISSUE TITLE
Türschloss einbinden

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#346]
Hallo, ich habe einen HMW-IO-12-Sw14 an dem ich bspw. Magnetventile schalte. Jetzt möchte ich darüber auch ein elektrischen Türschloss ansteuern und dieses als Schloss in Homebridge einbinden. Das ganze liegt auch Kanal 6 und ich habe folgendes versucht, was aber nur dazu führt, dass das Device als Licht angezeigt wird. Was müsste ich tun um es als Schluss ähnlich der VideoDoorBell einzubinden ?

```
              "services": [{
                        "type": "BidCos-Wired.OEQ12345678:6:DIGITAL_OUTPUT",
                        "service": "HomeMaticHomeKitKeyService"
                }],
```

**Comment by royalflashii** [comment]
versuch mal das gerät innerhalb deiner Homematic an einen virtuellen Schalter per Programm anzubinden und diesen virtuellen Schalter in das Gewerke der Homebridge zu ziehen. Sollte das nicht funktionieren kannst du auch über den Reiter Variable in der Config.json dir die Variable in der Homeapp anziegen lassen die als Schalter fungiert. vl Klappt es ja bei dir. stehe vor einem Ähnlichen Problem mit dem HmIP PCBS den ich als türöffner verwenden will und welcher nur 1 sec eingeschaltet werden darf.

**Comment by iuliusmaximilian** [comment]
Vielen Dank! Der VideoDoorBellService generiert neben der Kamera ein Device mit einem Schlosssymbol für das Türschloss. Weiss jemand was das für ein Service ist wenn ich nur das Türschloss als Device haben möchte ?

**Comment by royalflashii** [comment]
Einfach die Kamera nicht hinzufügen. Die muss in die Homebridge ja seperat aufgenommen werden. Wenn du einfach die up Kamera nicht hinzufügst sollte nur das türschloss da sein. Oder irre ich mich da ?

**Comment by iuliusmaximilian** [comment]
Ohne Kamera und ohne Klingel Adresse scheint der VideoDoorBellService nicht zu starten.

**Comment by royalflashii** [comment]
Kannst du denn zumindest bei der Klingel nicht ein virtuellen Schalter eingeben, ich mein du musst ihn ja nicht benutzten, den rstp Stream den kannst du ja auch ins leere laufen lassen wenn da was stehen muss.

**Comment by royalflashii** [comment]
Das stimmt aber hab da leider zu wenig Erfahrung. Bei mir funktioniert das mit eingebundener Kamera und klingelsensor einwandfrei. Hast du schon mal überlegt anstatt das über den Service laufen zu lassen eine systemvariable zu ändern per Programm die nach einer gewissen Zeit wieder ausgeschaltet wird oder einfach mithilfe eines Programms ?

**Comment by iuliusmaximilian** [comment]
Es kann so einfach sein, der HomeMaticHomeKitKeymaticService macht ja genau das...
