### ISSUE TITLE
HMIP STHD - wird der unterstützt?

### ISSUE THREAD

**Issue by xerabo** [thkl/homebridge-homematic#349]
HmIP-STHD: Homematic IP Temperatur- und Luftfeuchtigkeitssensor mit Display Innen

Die displaylose Variante STH wird laut Liste unterstützt. Weiß jemand ob STHD auf funktioniert?

Danke
Chris

**Comment by t-rex-2000** [comment]
hallo,

ja wird unterstützt, habe ich selbst verbaut.

**Comment by xerabo** [comment]
Super, danke!

**Comment by ballchemist** [comment]
Hey ... mal wieder hochziehen hier... mit welchem ServiceClassLoader binde ich die HMIP-STHD denn ein in Homebridge? Folgendes funzt bei mir nicht -> 

`  {
            "type": "HmIP-STHD:HEATING_CLIMATECONTROL_TRANSCEIVER",
            "service": "HomeMaticHomeKitThermostatWeatherServiceIP"
        }`
        
        Liefert nur: [ServiceClassLoader] There is no service for HmIP-STHD:HEATING_CLIMATECONTROL_CL_TRANSMITTER
