### ISSUE TITLE
Kein Zugriff mehr auf CCU3 mit FW 3.41.7 

### ISSUE THREAD

**Issue by drtp** [thkl/homebridge-homematic#351]
Hallo,

seit der FW 3.41.7 ist der Zugriff der homebridge auf die CCU3 nicht mehr möglich, auch wenn die Ports 9090-9092 in den Firewall-Einstellungen freigegeben wurden. Vermutlich liegt es daran, dass die CCU3 kein BIN-RPC mehr, sondern nur noch XML-RPC, unterstützt.

Hoffentlich lässt sich das Problem zeitnah lösen.

**Comment by thkl** [comment]
Ist seit 2 Tagen im Develop Branch gefixt. 
Npm steht noch aus

**Comment by drtp** [comment]
Sorry, dass ich hier noch mal nachhake, aber leider ist mir nicht ganz klar, was ich jetzt genau machen muss, um es mit der FW 3.41.7 zum Laufen zu bringen.

Ich hatte von [hier](https://github.com/thkl/homebridge-homematic/tree/develop) mal die Datei "HomeMaticRPC.js" in das homebridge-homematic-Verzeichnis unter node-modules meines Raspi kopiert und gehofft, dass es nach einem Neustart der HomeBridge dann funktionieren würde. Dann kam aber eine Fehlermeldung. Muss ich da noch andere Schritte unternehmen?
