### ISSUE TITLE
Problem mit Präsenzmelder HmIP-SPI

### ISSUE THREAD

**Issue by t-rex-2000** [thkl/homebridge-homematic#353]
Hallo,

habe jetzt die 0.0.109 master des homematic plugins installiert. diese version unterstützt auch den oben angegebenen präsenzmelder.

dieser wird zwarangezeigt und ich kann automationen erstellen, regieren tut er aber nicht oder manchal zeitverzögert (einige stunden). wenn er auslöst, dann schaltet er nicht wieder aus.

das er generell ordnungsgemäß funktioniert, habe ich dies mit der webui von raspberrymatic getestet.

hat jemand den präsenzmelder erfolgreich ans laufen bekommen?

**Comment by royalflashii** [comment]
gleiche problem beim hmip bewegungsmelder für den Außenbereich

**Comment by saschawerner** [comment]
Damit die Werte gelesen werden, muss der HMIP Bus auch abgefragt werden:
"enable_hmip" : true

also zum Beispiel:

{
"platform": "HomeMatic",
"name": "HomeMatic CCU2",
"ccu_ip": "192.168.1.3",
"filter_device": [],
"filter_channel": [],
"outlets": [],
"doors": [],
"programs": ["Alarmanlage unscharf"],
"accessories": [],
"subsection": "Homekit",
"variables": ["Anwesenheit"],
"variable_update_trigger_channel":"Homebridge_Trigger",
"enable_hmip" : true
},

**Comment by royalflashii** [comment]
Nein leider nicht. Momentan funktioniert der bewegungsmelder nur sporadisch und sendet nicht zuverlàssig das Signal Bewegung erkannt. Ich werde das mal im log wenn ich die homebridge starte überprûfen ob ein Eintrag vorhanden ist wenn der Bewegungsmeldern eine Bewegung registriert. Funktionieren tut er aber auf jeden Fall weil die direktverknûpfung in der ccu einwandfrei funktioniert, nur in der home kit app wird das falsch angezeigt. Ich melde mich die Tage noch mal wenn das Problem noch vorhanden ist. Und vielen Dank Thomas an dich das du so ein spitzen Tool entwickelt hast. Wird Teil meiner bachelorarbeit :P

**Comment by Stefan774** [comment]
Mal eine Frage dazu hast du ggf. einen Raspberry / CCU 3 mit FW 3.41x im Einsatz? Ich hatte nämlich ähnliche Probleme z.B. wurden keine Statusmeldungen mehr von HmIP-BSM (Licht) emfangen und die SPI Präsenzmelder waren immer auf ausgelöst. Probel lag an der Umstellung von EQ3 und das Tema mit der Schnittstelle (XMLRPC). Also falls du es noch nicht versucht hast, tausch doch mal einfach die HomeMaticRPC.js bei deiner 0.0.109 Installation durch die hier im Develop bereich aus. Danach sollte es wieder laufen. Geh nicht auf die 0.0.110 dort funktionieren die SPI‘s nicht da es anscheinend noch einen Bug gibt. Beim Starten der 0.0.110 wird angegeben dass falegato.js nicht vorhanden ist usw..
