### ISSUE TITLE
CCU3 mit FW 3.41.x - Zugriffprobleme mit dem homematic-Plugin

### ISSUE THREAD

**Issue by drtp** [thkl/homebridge-homematic#354]
Hallo,

ich muss leider noch mal ein Issue aufmachen, da [dieses hier](https://github.com/thkl/homebridge-homematic/issues/351) so schnell als gelöst geschlossen wurde, ohne explizit einen Lösungsweg anzugeben. 

Was muss man jetzt genau machen, um über die Homebridge mit dem homematic-Plugin wieder einen Zugriff auf die CCU3 mit FW 3.41.x und deren Geräte zu haben? Ich habe da etwas vom Austausch der HomeMaticRPC.js aus dem Develop Branch gelesen. Aber das hat bei mir leider nicht direkt zum gewünschten Erfolg geführt. Vielleicht habe ich auch etwas beim Ersetzen falsch gemacht. Aber es wäre zumindest hilfreich, einen entsprechenden Hinweis zu erhalten. 

Leider gab es im [HomeMatic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=41&t=27465&p=468034&hilit=Homebridge#p468034) zu meinen Anfragen bisher keinerlei Reaktion. Und ich bin nicht der Einzige mit diesem Problem.

Würde mich über eine schnelle Hilfe freuen, da ich die Homebridge in Verbindung mit meiner Watch sehr gerne zur Sprachsteuerung meiner HomeMatic per Siri benutze.

Gruß,

Thorsten

**Comment by fighterzg6** [comment]
Könnte man das als Update anbieten, denke da sind mehrere betroffen

**Comment by hypertom** [comment]
Ich fände dafür eine neue Version auch sehr hilfreich. Dann bleibt man im normalen Update Pfad.

**Comment by drtp** [comment]
Evtl. muss thkl noch die Abwärtskompatibilität prüfen. Aber auf eine homebridge-homematic 0.0.110., die an die FW 3.41.x der CCU3 angepasst ist, hoffe ich auch.

**Comment by fighterzg6** [comment]
Hatte die 0.0.110 Beta schon installiert, doch da sind alle Tür Fenster Kontakte verkehrt! Anstatt geschlossen wird offen angezeigt! Aber es wird etwas aus der Ccu3 ausgelesen

**Comment by jp112sdl** [comment]
@fighterzg6 das hatte ich bei der 0.0.109 auch schon... #293 
Bin derzeit immer noch bei der 0.0.97 :/

**Comment by jp112sdl** [comment]
Ich bin der Sache etwas näher gekommen.
Den Zustand des Kontakts habe ich in den Geräteeinstellungen der WebUI umgekehrt.
Also 
Meldung offen: geschlossen
Meldung geschlossen: offen

Das wurde auch so bis zur 0.0.97 korrekt umgesetzt, findet aber in der 0.0.109 keine Beachtung mehr.

**Comment by jp112sdl** [comment]
Hab den Fehler für den falschen DOOR-Status gefunden und einen PR #355 eingestellt.

**Comment by fighterzg6** [comment]
Ich finde immernoch das genau sowas als update kommen sollte. das rumgebastelt is ja schön und gut, aber zum Schluss gibt das wieder ein totales durcheinander.

**Comment by jp112sdl** [comment]
@fighterzg6 Da stimme ich dir zu. 👍 
Jedoch liegt es wohl in erster Linie bei Thomas, dies zu tun. 
Um ihn ist es irgendwie sehr ruhig geworden hier. Ist hoffentlich nur eine Auszeit... oder weiß jemand mehr?
Dieser [Kommentar](
https://github.com/thkl/homebridge-homematic/issues/335#issuecomment-433151355):
> Ich hoffe, dass Thomas irgendwann zurückkehrt.

macht mich irgendwie stutzig...

**Comment by DSchumacher2104** [comment]
Versucht doch ggf. mal die aktuelle Beta von NPM zu installieren, die ist relativ neu (v0.1.1 - 4 Monate alt):
(sudo) npm i -g homebridge-homematic@beta

**Comment by jp112sdl** [comment]
Ich bin nun wieder zurück zur 0.0.97 👎 

Nachdem ich den Türstatus zwar fixen konnte, wurden nun die Rollläden (HM RF) nicht mehr aktualisiert.
Auch nicht, wenn ich die Home-App neu gestartet habe und ein Refresh erzwungen wurde.
Nur beim Neustart der homebridge (und noch ein paar Minuten danach) stimmte der Zustand.
Wenn morgens per HM-Programm die Rollläden hochfuhren, war trotzdem den ganzen Tag der Status auf 0%.

So lange die 0.0.97 jetzt mit XMLRPC stabil läuft, dann ist es ok für mich. Sie ist für meine Zwecke ausreichend.

**Comment by AdlerCentauri** [comment]
Hallo, ich habe aus dem bev-brach den Inhalt der HomeMaticRPC.js ausgetauscht, meine Geräte sind trotzdem nicht erreichbar. Muss ich noch etwas anderes machen?

**Comment by drtp** [comment]
Ich würde empfehlen, hier nicht per C&P zu arbeiten, sondern die entsprechenden Zeilen direkt mit nano zu editieren. Ansonsten kann es passieren, dass ungültige Line Feeds und Carriage Returns kopiert werden, so dass das Skript nicht mehr ausführbar ist.

**Comment by AdlerCentauri** [comment]
Hallo, ich habe die Zeilen mit Nano eingefügt. Aber ich habe jetzt die komplette Datei hier geladen und mit der vorhandenen ersetzt, jetzt funktioniert es. Danke.

**Comment by rudelm** [comment]
Das Problem tritt jetzt auch auf der Raspmatic mit dem Update 3.41.11.20181126 auf. Ich konnte allerdings auch die Änderungen von [hier](https://github.com/thkl/homebridge-homematic/commit/04b9e25318e9ff93f8ea8e88fbf1e8b54da24076) machen und die HomeMatic Geräte werden wieder aufgelistet.

Ich sehe im Log aber trotzdem noch jede Menge Fehlermeldungen dieser Art:
`Nov 27 22:34:42 pi3plus homebridge[9438]: [2018-11-27 22:34:42] [Config] Unauthorised WebSocket Connection Closed
Nov 27 22:34:46 pi3plus homebridge[9438]: [2018-11-27 22:34:46] [Config] Unauthorised WebSocket Connection Closed
Nov 27 22:34:53 pi3plus homebridge[9438]: [2018-11-27 22:34:53] [Config] Unauthorised WebSocket Connection Closed
Nov 27 22:34:57 pi3plus homebridge[9438]: [2018-11-27 22:34:57] [Config] Unauthorised WebSocket Connection Closed`

**Comment by Vegas2806** [comment]
Hallo ich habe auch von der Version 3.41.11.20181126

Wieder eine ältere Version aufgespielt

**Comment by rudelm** [comment]
Ich habe jetzt übrigens in den Release Notes gesehen, dass bereits in der [Version 3.41.11.20181124](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.41.11.20181124) sich etwas für alle externen Apps geändert hat:

> all remote API XMLRPC ports (8181, 1999, 2010, 9292, 2001, 2000) for external applications to access HomeMatic services (e.g. ReGaHss, HMIPServer, etc.) on the CCU are now proxied through the lighttpd web server implying the following security related changes in accessing these remote APIs:

Das ist eigentlich eine gute Änderung. Man muss jetzt nur noch herausfinden, wie man das dauerhaft und für alle Versionen passend in homebridge-homematic integrieren könnte.

**Comment by drtp** [comment]
Also ich habe bisher keinerlei Probleme mit dem homematic-Plugin für die Homebridge. 

Bei mir laufen aktuell die folgenden Plugins:
![2018-12-02_12h00_32](https://user-images.githubusercontent.com/17758445/49338942-e4f2a780-f629-11e8-80f3-4d2d3f20c968.png)

**Comment by Larson-Sei180LX** [comment]
Die Datei scheint wohl im Pfad usr/local/lib/node_modules/homebridge-homematic zu finden sein. Aber, wenn ich dann den Container neu starte, überscrrheibt er mir ja meine Änderungen auch wieder....

**Comment by drtp** [comment]
Warum sollte die Änderung nach einem Neustart überschrieben werden? Das passiert höchstens nach dem Einspielen einer neuen Version des homematic-Plugins.

**Comment by drtp** [comment]
>     1. Thermostattemperatur via Home-App ändern (auf Thermostat verifizieren).
> 
>     2. Thermostattemperatur ein weiteres Mal ändern (wieder verifizieren).
> 
> Stimmt beim zweiten Mal die Temperatur am Thermostst wirklich mit der Home-App überein?
> 
> Wichtig: die Home-App darf zwischenzeitlich nicht beendet werden!

Funktioniert bei mir einwandfrei. Auch, wenn ich das Prozedere mehrmals hintereinander wiederhole. Die per Home App geänderten Soll-Temperturen werden unverzüglich übernommen und umgesetzt.

**Comment by dehsgr** [comment]
Strange. Bei mir läufts seit der Umstellung mehr schlecht als recht, d.h. zwischendurch hängt sich die Homebridge alle 1-3 Tage auch mal auf. Hast Du nur besagte Datei geändert, oder bist Du evtl. schon auf einem neueren Branch?

**Comment by xerabo** [comment]
Ich habe die Datei nur editiert. Seither läuft aber alles wieder tadellos.

**Comment by Larson-Sei180LX** [comment]
Weil beim dockercontainer nach beenden jedesmal alles neuinstalliert wird. In der install.json sind alle Plugins vorgegeben, die er dann installiert - folglich überschreibt

**Comment by Larson-Sei180LX** [comment]
Ich hoffe dass Thomas sich bald meldet und mal Vl einen kleinen Ausblick auf ein mögliches Update geben kann. Leider ist sonst bis dahin meine Siri in den Urlaub geschickt worden....

**Comment by thkl** [comment]
@Larson-Sei180LX gibt doch ein npm Paket dafür : npm install homebridge-homematic@0.1.2

**Comment by thkl** [comment]
Nein das muss ich noch umbauen. 
Ebenso geht noch keine TLS Verbindung.

**Comment by AdlerCentauri** [comment]
Hallo,

wenn ich das ganze wie hier beschrieben: https://homematic-forum.de/forum/viewtopic.php?f=41&t=27465&sid=22e96badbb69d9a9e22f5be0289fafb4

installiere, wird dann auch die aktuelle Version installiert die mit der CCU3 FW 3.41 funktioniert?

**Comment by drtp** [comment]
> idge-homematic@0.1.2

Hab's mal drüber installiert.
![2018-12-13_09h51_36](https://user-images.githubusercontent.com/17758445/49926913-ff940e80-febc-11e8-8ebc-0a446410457e.png)

Mir wird aber immer noch die Versin 0.0.109 angezeigt.

**Comment by 2000one** [comment]
> @drtp bei mir funktioniert die geänderte Version von HomeMaticRPC.js soweit auch und stellt die Funktionalität wieder her.
> 
> Allerdings kann ich einen Thermostat nur noch exakt 1x in seinen Einstellungen verändern (z.B. Temperatur). Anschließend muss ich die Home App schließen und neu öffnen, damit es wieder geht. Das war über BinRPC zuverlässiger. Ist der Fehler eher hier, oder auf der RaspberryMatic zu suchen?

Ich habe das gleiche Problem mit piVCCU...

**Comment by dehsgr** [comment]
@thkl das kann ich bestätigen. Dafür werden jetzt alle Türstatus inkl. Garagentor als offen angezeigt, obwohl geschlossen. :-(

**Comment by jp112sdl** [comment]
@dehsgr Ich hatte das Problem auch. Bei mir [hat das](https://github.com/thkl/homebridge-homematic/pull/355/files) geholfen.

**Comment by dehsgr** [comment]
@jp112sdl auch das kann ich bestätigen. Jetzt wird mir aber das Garagentor nach wie vor offen obwohl geschlossen angezeigt. :-(

@thkl wäre schön, wenn Du es schaffen würdest, dass für diese ganzen Dinge mal wieder ein regulärer NPM-Release käme. Durch die ganzen Änderungen in RaspberryMatic erachte ich das als absolut sinnvoll. Ich weiß von mindestens zwei weiteren Leuten in meinem Umkreis, dass diese aktuell RM deswegen nicht updaten können. Mir ist aber ebenso bewusst, dass Du hier viel Freizeit investiert. Insofern kann und will ich keine bestimmten Release-Zyklen von Dir erwarten, sondern bedanke mich lieber für die tolle Arbeit die in dieses Projekt gesteckt wird. ;-)

**Comment by dehsgr** [comment]
...das mit dem Garagentorstatus muss ich (teilweise) revidieren. Nachdem ich es geöffnet und wieder geschlossen habe stimmt hier der Status nun auch wieder...

**Comment by dehsgr** [comment]
Hmmm. Neeee. Da ist noch beim Garatentor irgendwo der Wurm drin.... Steht plötzlich immer auf „wird geschlossen“...

**Comment by dehsgr** [comment]
...gerade gesehen, dass das in Issue #357 bereits dokumentiert ist. :‘(

**Comment by AdlerCentauri** [comment]
Bei mir sind manchmal einfach Dimmer auf 100% obwohl sie ausgeschaltet sind. Wenn ich drauf tippe, gehen sie auf 0% und 2-3 Sekunden später sind sie wieder auf 100% das nicht ist aber aus.

**Comment by dehsgr** [comment]
Also ich bin jetzt erst einmal wieder auf die (RPC-gepatchte) 0.0.109 zurück, da mit der Version (mit Einschränkung meines Thermostat-Problems) wenigstens alles so läuft, wie es soll. Die Beta klappt bei mir hinten und vorne nicht wirklich.

@drtp mit dem Thermostat-Problem konnte ich übrigens feststellen, dass das ausschließlich auf dem iPhone aufzutreten scheint. In hb-config-ui-x kann ich es in der Tat auch nicht reproduzieren. Mit der Beta lief das wiederum einwandfrei...

**Comment by CM-UH** [comment]
Ich habe hier auch homebridge und piVCCU3 auf einem Raspi 3 am laufen.
Leider bekomme ich auch nach vielen Probieren die beiden System nicht dazu zu kommunizieren.
Jedes System läuft für sich gut.
Ich habe folgende Stände: Homebridge 0.4.46 (Installation laut https://smartapfel.de/homebridge/homebridge-installieren/)
Config:
            "platform": "HomeMatic",
            "name": "HomeMatic CCU3",
            "ccu_ip": "192.168.2.19",
            "enable_hmip": true,
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "windows": [
                "Fenster_1:1"
            ],
            "programs": [],
            "subsection": "Homekit"
  
Homematic PiVCCU3  (Installation laut https://technikkram.net/2018/01/pivccu-homematic-ccu2-auf-asus-tinkerboard-oder-raspberry-pi-auslagern)

im Homebridge logfile steht:
[2019-2-16 11:57:36] [HomeMatic CCU3] RPC server for interface BidCos-RF. is listening on port 9090.
[2019-2-16 11:57:36] [HomeMatic CCU3] Creating Local HTTP Client for CCU RPC Events
[2019-2-16 11:57:36] [HomeMatic CCU3] RPC server for interface HmIP-RF. is listening on port 9092.
[2019-2-16 11:57:36] [HomeMatic CCU3] Creating Local HTTP Client for CCU RPC Events
[2019-2-16 11:57:36] [Diskstation] do poll...
[2019-2-16 11:57:36] [HomeMatic CCU3] Error Error: connect ECONNREFUSED 192.168.2.19:8181while executing rega script Write('PONG')
[2019-2-16 11:57:36] [HomeMatic CCU3] if undefined is PONG CCU is alive
[2019-2-16 11:57:36] [HomeMatic CCU3] Error Error: connect ECONNREFUSED 192.168.2.19:8181while executing rega script string sDeviceId;string sChannelId;boolean df = true;Write('{"devices":[');foreach(sDeviceId, root.Devices().EnumIDs()){object oDevice = dom.GetObject(sDeviceId);if(oDevice){var oInterface = dom.GetObject(oDevice.Interface());if(df) {df = false;} else { Write(',');}Write('{');Write('"id": "' # sDeviceId # '",');Write('"name": "' # oDevice.Name() # '",');Write('"address": "' # oDevice.Address() # '",');Write('"type": "' # oDevice.HssType() # '",');Write('"channels": [');boolean bcf = true;foreach(sChannelId, oDevice.Channels().EnumIDs()){object oChannel = dom.GetObject(sChannelId);if(bcf) {bcf = false;} else {Write(',');}Write('{');Write('"cId": ' # sChannelId # ',');Write('"name": "' # oChannel.Name() # '",');if(oInterface){Write('"intf": "' # oInterface.Name()  # '",');Write('"address": "' # oInterface.Name() #'.' # oChannel.Address() # '",');}Write('"type": "' # oChannel.HssType() # '",');Write('"access": "' # oChannel.UserAccessRights(iulOtherThanAdmin)# '"');Write('}');}Write(']}');}}Write(']');var s = dom.GetObject("Homekit");string cid;boolean sdf = true;if (s) {Write(',"subsection":[');foreach(cid, s.EnumUsedIDs()){  if(sdf) {sdf = false;} else { Write(',');}Write(cid);}Write(']');}Write('}');
[2019-2-16 11:57:36] [HomeMatic CCU3] ok local cache is set to /var/homebridge/ccu.json
[2019-2-16 11:57:36] [HomeMatic CCU3] Unable to load cached ccu data. giving up
[2019-2-16 11:57:36] [HomeMatic CCU3] Programs :

die HomeMaticRPC.js  habe ich angepasst
und auch das Update auf Plugin 0.1.2 ist gelaufen.

Hat jemand einen Tip für mich, wie man das zum Laufen bekommt??

**Comment by superpower10** [comment]
> So, hab's hinbekommen mit [diesem Verweis hier](https://github.com/thkl/homebridge-homematic/issues/348#issuecomment-435574023). Einfach die ensprechenden Zeilen in der Datei HomeMaticRPC.js im Verzeichnis "/usr/lib/node_modules/homebridge-homematic" editieren und die Homebridge neu starten. That's it. Problem solved. ;)

### So läuft bei mir alles einwandfrei:
- CCU3 auf FW 3.43.15
- CCU3 -> Authentifizierung aus
- CCU3 -> Firewall-Richtlinie: Ports blockieren, die anderen drei Vollzugriff
- homebridge auf 0.0.109
- HomeMaticRPC.js gemäß Anleitung den Beta Source-Code (siehe oben) einfügen

**Comment by superpower10** [comment]
So, jetzt ist passiert. 

Habe auf 3.43.16 und es geht nicht mehr.

Hat jemand noch die alte Firmware 3.43.15 für mich?

**Comment by xerabo** [comment]
https://www.eq-3.de/Downloads/Software/CCU3-Firmware/CCU3-3.43.15/ccu3-3.43.15.tgz

Vielleicht geht der link noch...

**Comment by mikrozensus** [comment]
> > idge-homematic@0.1.2
> 
> Hab's mal drüber installiert.
> ![2018-12-13_09h51_36](https://user-images.githubusercontent.com/17758445/49926913-ff940e80-febc-11e8-8ebc-0a446410457e.png)
> 
> Mir wird aber immer noch die Versin 0.0.109 angezeigt.

Hallo, ich habe eine piVCCU3 Installation neben der Homebridge mit homebridge-homematic plugin.

Ich möchte auch gerne das Plugin auf die letzte Version aktualisieren, bekomme aber genau die gleichen Fehlermeldungen:

pi@raspberrypi:/etc $ sudo npm install homebridge-homematic@0.1.2
npm WARN saveError ENOENT: no such file or directory, open ‚/etc/package.json‘
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open ‚/etc/package.json‘
npm WARN etc No description
npm WARN etc No repository field.
npm WARN etc No README data
npm WARN etc No license field.

+ homebridge-homematic@0.1.2
added 106 packages in 45.133s

Wo liegt der Fehler? sind die Standardverzeichnisse durch den piVCCU Container irgendwie anders?

meine Version bleibt auch bei 0.0.109 “hängen”....

Danke für Hilfe!

Gruss

**Comment by superpower10** [comment]
> https://www.eq-3.de/Downloads/Software/CCU3-Firmware/CCU3-3.43.15/ccu3-3.43.15.tgz
> 
> Vielleicht geht der link noch...

Nein. Leider nicht.

Bin jetzt auf Raspberrymatic umgestiegen. Dort gibt es ja die 15er Version noch.

**Comment by superpower10** [comment]
> > So, hab's hinbekommen mit [diesem Verweis hier](https://github.com/thkl/homebridge-homematic/issues/348#issuecomment-435574023). Einfach die ensprechenden Zeilen in der Datei HomeMaticRPC.js im Verzeichnis "/usr/lib/node_modules/homebridge-homematic" editieren und die Homebridge neu starten. That's it. Problem solved. ;)
> 
> ### So läuft bei mir alles einwandfrei:
> * CCU3 auf FW 3.43.15
> * CCU3 -> Authentifizierung aus
> * CCU3 -> Firewall-Richtlinie: Ports blockieren, die anderen drei Vollzugriff
> * homebridge auf 0.0.109
> * HomeMaticRPC.js gemäß Anleitung den Beta Source-Code (siehe oben) einfügen

Damit habe ich es zwar zum laufen gebracht, aber leider geht der Remote-Zugriff (also außerhalb meines Heimnetzwerkes) nicht.

Selbst, wenn ich mich über VPN nach Hause verbinde. Es geht nur Zuhause.

Hat jemand vielleicht Ideen?

**Comment by jp112sdl** [comment]
> Selbst, wenn ich mich über VPN nach Hause verbinde. Es geht nur Zuhause.

Wenn du keinen Apple TV oder iPad daheim zu laufen hast, dann gehts nur wenn du daheim eigenen LAN bist.
Nein - Auch nicht über VPN!

**Comment by drtp** [comment]
Also bei mir läuft das homematic-Plugin v.0.0.109 auf nem Raspi 3B+ mit den obigen Modifikationen nach wie vor einwandfrei mit der Firmware 3.43.16 der CCU3. 

![2019-03-24_13h06_08](https://user-images.githubusercontent.com/17758445/54879107-9a45a700-4e35-11e9-8945-8a5a882bc15d.png)
![2019-03-24_13h07_14](https://user-images.githubusercontent.com/17758445/54879122-c19c7400-4e35-11e9-810f-abe945e9a99a.png)

**Comment by superpower10** [comment]
> > Selbst, wenn ich mich über VPN nach Hause verbinde. Es geht nur Zuhause.
> 
> Wenn du keinen Apple TV oder iPad daheim zu laufen hast, dann gehts nur wenn du daheim im eigenen LAN bist.
> Nein - Auch nicht über VPN!

Bitte genau lesen. Ich einen Apple TV. Es ging nach der Umstellung auf die CCU3 nicht mehr. Neu gestartet habe ich diese (ja ich habe mehrere) auch schon.

Das ist also nicht der Grund.

**Comment by superpower10** [comment]
@drtp 
- Hast Du das HomeMaticRPC.js geändert?
- Warum hast Du Port 8701 in der Firewall der CCU3 offen? Für den externen Zugriff?

- Bis jetzt (bis zur CCU2) hatte ich in der Config nicht so viel stehen und alles hat funktioniert. Bei mir steht nur:
```
"platforms": [
        {
            "platform": "HomeMatic",
            "name": "HomeMatic CCU2",
            "ccu_ip": "192.168.0.60",
	    "enable_hmip": "true",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "programs": [],
            "accessories": [],
            "subsection": "HomeKit"
        }
   ]
```

**Comment by jp112sdl** [comment]
@superpower10  Ach so... Sorry... 
Ich bin vor einiger Zeit zu Redmatic gewechselt und seither alle Sorgen los, die letztlich mit homebridge-homematic hatte. 
Ich muss mal das Watching hier beenden.
Viel Erfolg noch!

**Comment by drtp** [comment]
@superpower10 
Ja, ich habe meine HomeMaticRPC.js geändert. Hatte ich ja ganz oben im zweiten Posting geschrieben. ;)

Port 8701 ist lediglich notwendig für CUxD, um vom ioBroker aus darauf zugreifen zu können. Der hat für die Homebridge keine Bedeutung.

Hast du mal versucht, das persist-Verzeichnis zu löschen

`sudo /etc/init.d/homebridge stop
rm /home/pi/.homebridge/persist -R
sudo reboot`

und den username der Homebridge in der config.json zu ändern? Manchmal ist das erforderlich, damit überhaupt wieder was geht. Leider müssen dann auch alle Einstellungen in der Home App wieder neu vorgenommen werden.

**Comment by tragnar** [comment]
Kleine Ergänzung: man muss in der ccu unter Systemsteuerung/Sicherheit die Authentifizierung abschalten, sonst klappt der Zugriff des homebridge-homematik Plugin auf die ccu nicht. Allerdings sollte man sich den Sicherheitsrisiko natürlich bewusst sein. Also ccu nicht von außerhalb erreichbar machen...

Hoffe das hilft, bei mir war es der Grund warum es nicht lief (ccu3 Firmware 3.43.16)

**Comment by drtp** [comment]
Ein Sicherheitsrisiko ohne aktivierte Authentifizierung besteht nicht, wenn man den externen Zugriff auf die CCU3 per VPN einrichtet. Eine Portfreischaltung wird jedoch generell nicht empfohlen.
