### ISSUE TITLE
Initialisierungsfehler HM-WDS30-T-O

### ISSUE THREAD

**Issue by asman-hm** [thkl/homebridge-homematic#356]
Bei Aufnahme des Aussentemperatursensors HM-WDS30-T-O startet Homebridge nicht mehr. Verhalten ist reproduzierbar.

Viele Grüße
Alexander

Auszug aus dem Logfile:

Nov 21 07:53:09 raspberrypi homebridge[12897]: /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:47
Nov 21 07:53:09 raspberrypi homebridge[12897]: }
Nov 21 07:53:09 raspberrypi homebridge[12897]: ^
Nov 21 07:53:09 raspberrypi homebridge[12897]: SyntaxError: missing ) after argument list
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at new Script (vm.js:83:7)
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at createScript (vm.js:267:10)
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at Object.runInThisContext (vm.js:319:10)
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at Module._compile (internal/modules/cjs/loader.js:685:28)
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at Module.load (internal/modules/cjs/loader.js:620:32)
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at Module.require (internal/modules/cjs/loader.js:658:17)
Nov 21 07:53:09 raspberrypi homebridge[12897]:     at require (internal/modules/cjs/helpers.js:22:18)
Nov 21 07:53:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 07:53:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Nov 21 07:53:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by BarisKorn** [comment]
Same problem. Any ideas?

Thx Martin

**Comment by LG451** [comment]
Same problem, got as well "SyntaxError: missing ) after argument list"

After I unlearned the temp sensor from Homematic WebUI Homebridge started again.
