### ISSUE TITLE
Garagentor

### ISSUE THREAD

**Issue by muelli1967** [thkl/homebridge-homematic#357]
Hallo,

ich hab nach dem Wechsel auf die Develop ein Problem mit dem Garagentor. Wenn ich nach dem Start von homebridge in die HomeKit app gehe, steht der Status des Garagentor´s auf "geöffnet" obwohl der Sensor geschlossen ist. Betätige ich den Button, geht der Status auf "Schließen" und das Tor öffnet sich. Betätige ich den Button wieder, schließt das Tor und nach einer Zeit zeigen Button und Sensor  parallel "geschlossen" wie gewünscht. Damit könnte ich beim Start der homebridge noch leben, jedoch wenn ich die App neu öffne oder ein anderes Iphone / ipad die HomeKit app startet, beginnt das Spiel erneut und der Button zeigt endlos schließend an, ohne den Status nochmal zu verändern. 

Hier die config:

special": [ {
		"name" : "Garage-Door",
		"type" : "HM-THKL-GARAGEDOOR",
		"parameter" : {
        "address_sensor_close": "BidCos-RF.NEQ1651631:1.STATE",
        "address_actor_open": "BidCos-RF.BidCoS-RF:2.PRESS_SHORT",
		"state_sensor_close":false,
        "message_actor_open": {"on":true}
		} }, 

![garagedoor](https://user-images.githubusercontent.com/37692544/48834518-50ad5880-ed7e-11e8-8b1c-510ef50a4dd7.jpg)

Was läuft hier verkehrt?

**Comment by thoduh** [comment]
Möchte mich der frage anschließen, das selbe hab ich hier nämlich auch :-(

**Comment by DSchumacher2104** [comment]
Hier leider auch.

**Comment by DSchumacher2104** [comment]
Das betrifft auch irgendwie die Rolladenaktoren, die übermitteln auch einen falschen Status nach HomeKit. Irgendetwas stimmt da insgesamt nicht mit den Statusabfragen in der aktuellen Beta-Version.

**Comment by thoduh** [comment]
> Das betrifft auch irgendwie die Rolladenaktoren, die übermitteln auch einen falschen Status nach HomeKit. Irgendetwas stimmt da insgesamt nicht mit den Statusabfragen in der aktuellen Beta-Version.

Die Rolladenaktoren stimmen bei mir, offen/geschlossen wird immer richtig angezeigt...

**Comment by jp112sdl** [comment]
> Das betrifft auch irgendwie die Rolladenaktoren, die übermitteln auch einen falschen Status nach HomeKit. 

@DSchumacher2104 Bei mir stimmt der Zustand nur zu Anfang. Spätestens am nächsten Morgen, wenn die Rollläden nach Zeitprogramm gefahren sind, stimmts nicht mehr.

Bin dann wieder zur 0.0.97 gewechselt. Die läuft einfach mega rund bei mir.

**Comment by DSchumacher2104** [comment]
Ja, nur leider unterstützt die 0.0.97 noch keine Fakegato. Ich habe schon stundenlang versucht den Programmcode des Plugins zu verstehen und die Ursache zu finden. Leider ohne Erfolg, ich bin halt kein Programmierer. Ich hoffe, dass Thomas uns weiterhilft!

**Comment by jp112sdl** [comment]
Ich hab eher das Gefühl _(wirklich rein subjektiv)_, dass der Trödel mit den unzuverlässigen Stati erst mit der Implementierung von Fakegato kam.

Was macht Fakegato überhaupt? Ist das nicht nur irgendwas für Eve?

**Comment by royalflashii** [comment]
zu dem Thema mit den Rollladenaktoren, habe 3 HMIP unterputz Rollladenaktoren die ohne Probleme funktionieren, lediglich der eine hm Rollladenaktor zeigt in der Home App immer den Status öffnen an. tippt man ihn einmal an, wird der Status aktualisiert und der richtige Status wird angezeigt ohne das der Rollladen was macht. Anschließend kann man ganz normal den Aktor bedienen und auch Automationen funktionieren. Jetzt habe ich festgestellt das wenn ich die Home App schließe, also die App richtig schließe und nicht nur auf den Homescreen gehe, das beim erneuten öffnen der Status wieder auf öffnen steht und das Rädchen sich dreht. Tippt man wieder einmal drauf, stimmt der Status wieder. Bin etwas verzweifelt, dachte das es vl an der einstellung der CCU liegt für die Zeit fürs hoch und runter fahren. aber ist leider auch nicht der Fall. Version von nodejs ist 8.11 und vom Plugin 0.109 ( kann leider nicht auf eine Version runter gehen weil dann das videodoorbell Plugin nicht mehr funktioniert)

**Comment by muelli1967** [comment]
gibt es hier ein update zu dem Problem?

**Comment by royalflashii** [comment]
Ich habe mittlerweile die home ridge neu aufgesetzt und die Developer Version installierst also 1.1 und es funktioniert alles einwandfrei ohne Probleme.

**Comment by DSchumacher2104** [comment]
Aktuelle beta ist doch die v0.1.2! Bist du dir sicher, dass du auf v0.1.1 bist?!?

Hast du auch alle Geräte in HomeKit neu anlegen lassen oder die persist und accessories Ordner aus der alten Installation übernommen? Es wäre schon wirklich ärgerlich, wenn es nur nach neuem Anlegen aller Geräte wieder "normal" funktionieren würde.

**Comment by royalflashii** [comment]
Habe alle Geräte neu angelernt war echt nen Akt aber ich schreibe über das Thema meine bachelorarbeit und wollte das alles funktioniert. Ich schaue daheim nochmal welche Version ich installiert habe aber ich meine es war die 1.1. Habe pivccu3 am laufen und nebenher halt die homebridge bis jzz läuft noch alles einwandfrei. Hatte auch bei der 0.109 das Problem das der Bewegungsmelder nicht funktioniert hat bzw den Status nicht geändert hat. Habe halt nicht so die Ahnung von programmieren, habe mir alles aus Anleitungen angelesen, besonders hilfreich war da die Seite Technikkram.net

**Comment by DSchumacher2104** [comment]
Erstmal Danke für die Rückmeldung. Mit "alle Geräte neu angelernt" meinst du auch das Anlernen deiner Geräte an pivccu3 oder nur in HomeKit?

Soweit ich das verstehe, entstehen die Endlosschleifen dadurch, dass in HomeKit ein Event ausgelöst wird, anschließend aber keine Status-Rückmeldung an HomeKit erfolgt, dass das Event auch ausgeführt wurde. Dann "wartet" HomeKit quasi ewig auf die Bestätigung und es entsteht diese Endlosschleife. Dies ist vermutlich das Problem in den letzten Versionen, dass nach dem Auslösen eines Events oder sonstigen Statusabfragen wohl keine Statusrückmeldungen in HomeKit ankommen.

**Comment by royalflashii** [comment]
Genau seh ich auch so wie du. Jedoch kam noch dazu das auch der Status der rollàden teilweiße falsch angezeigt wurde. Und ja ich hab komplett alles neu aufgesetzt. Also sowohl ccu als auch HomeKit. Habe komplett von neuem angefangen.

**Comment by habeck76** [comment]
Ich hatte die gleichen Probleme mit dem Garagentor.

Der Fehler liegt in der Verwendung der Tür bzw. Fensterkontakte. Der im Beispiel verwendete HmIP-Kontakt sendet im State 0 (Geschlossen) und 1 (Offen), so wie benötigt.

Der herkömmliche Fensterkontakt oder wie in meinem Fall der Neigungssensor sendet allerdings False oder True. Daher kommen die Probleme mit dem Status der Garage. Also HmIP-Kontakt verwenden oder THKL bitten das Skript anzupassen.

**Comment by nicoh88** [comment]
Zur Info, die Version 0.1.1, von dem @royalflashii spricht, bei dem das Garagentor angeblich korrekt funktioniert, ist der den GitHub Develop Branch, welcher aktueller ist, als die NPM-Beta 0.1.2.

Er kann mit ...

`npm install -g thkl/homebridge-homematic#develop`

... installiert werden.

**Comment by DSchumacher2104** [comment]
Bei mir hilft das alles nichts, es bleibt bei den Fehlern. Alle von der CCU2 an das Plugin übermittelten Geräte-Stati werden vom Plugin irgendwie zentral falsch ausgewertet. Dies betrifft ja z. B. auch Rollos, Schalter etc.. Ich habe Schalter, die ich nie betätige und nach einer gewissen Zeit stehen die im Plugin immer wieder auf "Aus", obwohl sie "An" sind und nicht geändert wurden. Nach einem Neustart des Plugins stehen sie dann zunächst wieder auf "An", irgendwann springen sie aber wieder aus "Aus", ohne dass irgendetwas aktiv betätigt wurde. Dies kann m. E. nur daran liegen, dass die CCU2 ja turnusmäßig Geräte-Status-Meldungen an das Plugin sendet und das Plugin diese Meldungen falsch auswertet. Ich ärgere mich so, dass ich zu blöd zum Programmieren bin. Das Problem kann gar nicht so schwer zu lösen sein, da es so grundlegend und zentral ist!

**Comment by DSchumacher2104** [comment]
Abgesehen von der falschen Meldung "wird geöffnet..." bei einem Neustart der Homebridge konnte ich das Problem bei mir lösen, indem die den Sensorstate in Anführungszeichen gesetzt habe.

`"state_sensor_close": "false",` 

Vielleicht hilft dies anderen ja auch!
