### ISSUE TITLE
Nach dem update auf 0.0.41

### ISSUE THREAD

**Issue by bprskalo** [thkl/homebridge-homematic#36]
werden keine Geräte mehr angezeigt und die Bridge lässt sich auch nicht mehr neu konfigurieren.

Bis jetzt Leif alles wunderbar .. auf IOS10 .. eine Idee ?

**Comment by thkl** [comment]
Werden die Geräte beim Start im Log angezeigt ?
Ggf in /var/log/homebridge.log nachschauen.

**Comment by bprskalo** [comment]
ja das werden sie

**Comment by thkl** [comment]
Dann hängt HomeKit irgendwie in einer Endlosschleife.  
Entweder warten oder in der HomeApp die Bridge löschen und neu aufnehmen.   Wenn er die auch nicht mehr findet hilft nur noch Haus löschen und von vorn anfangen.  


Das ist ein HomeKit Problem.

**Comment by thkl** [comment]
Ach oder hier die Tips bei Common Issues mal probieren. 

https://github.com/nfarina/homebridge/blob/master/README.md

**Comment by bprskalo** [comment]
danke für den tip, habe ich natürlich alles schon gemacht .. nichts genützt, selbst nach einem komplett neuen setup immer noch das gleiche problem .. ergo .. weitersuchen

**Comment by bprskalo** [comment]
mit 0.0.42 immer noch das gleiche problem ...

**Comment by thkl** [comment]
Ändere mal in der config.json den username der Bridge.  (Sieht aus wie eine Mac Adresse)

**Comment by bprskalo** [comment]
habe ich gemacht, persist Ordner gelöscht .. neu gestartet .. und wieder das gleiche ..  ich kann die hombridge nicht als Zubehör hinzufügen .. 

alle anderen option auch schon ausprobiert und geprüft .. in bonjour ist ja auch alles sichtbar..

will dich ja nicht ärgern :-) .. ist aber wirklich erst seit dem update auf die 0.0.41 .. ich weiss ja auch, dass es 100 Sachen gibt die einen Eifluss haben können :-) .. ist halt einfach .. sch.. dass das ding nicht mehr läuft ...

**Comment by thkl** [comment]
Könnte sein das ein Gerät hinter der Bridge nicht von HK akzeptiert wird.  Einzige Abhilfe: ale Geräte aus dem HomeKit Gewerk entfernen und nacheinander aufnehmen um zu schauen, welches fehlerhaft ist.  Du kannst das nach Typen gruppieren. Also alle Geräte gleichen Types können zusammen wieder eingesetzt werden.

**Comment by bprskalo** [comment]
ich habe kein homekit Gewerk .. ich ziehe alle geräte an .. das hat bis gestern Abend perfekt funktioniert .. 

also du meinst ich sollte ein Gewerk machen .. ?

**Comment by thkl** [comment]
Auf jeden Fall denn mehr als 100 Geräte akzeptiert HomeKit hinter einer Bridge nicht.  Und die CCU alleine bringt schon 50virtuelle Tasten mit, wenn die nicht übers Gewerk gefiltert werden.

**Comment by bprskalo** [comment]
das stimmt schon .. aber hat sich den in den letzten versionen dazu etwas verändert .. ) ich frage um zu verstehen :-)

**Comment by bprskalo** [comment]
zack .. FEHLER gefunden .. mit den Gewerken gehts .. !! man war das jetzt eine Zangengeburt .. !!


Danke für Deine Hilfe Thomas ... 

aber meine Frage würde mich schon noch interessieren .. :-) .. wegen den Änderungen ...

**Comment by thkl** [comment]
Ah ok , mit 41 habe ich die interne Verarbeitung umgestellt. Früher wurden die KEY und VIRTUAL_KEY Channels rausgefiltert, wenn kein Gewerk angegeben wurde. 

Ich hatte den Fall, kein Gewerk, gar nicht mehr auf dem Schirm.

**Comment by bprskalo** [comment]
sann haben wir ja beide etwas gelernt :-) .. mit anderen worten .. Gewerke zwingend notwendig :-) ..

**Comment by thkl** [comment]
ja in der nächsten Version werfe ich dann einen Error wenn kein Gewerk angegeben ist.
Mittlerweile ist die Anzahl der Geräte so groß, das schnell das 100er Limit erreicht wird.
Das ist auch einfacher, als über die config.json zu filtern.

**Comment by bprskalo** [comment]
perfekt , danke nochmals !!

**Comment by bprskalo** [comment]
noch kurz .. die ios10 Einstellung ist nur in Zusammenhang mit Programmen wichtig .. ?

**Comment by thkl** [comment]
Bisher habe ich die Programme (kann man ja im config switch programs angeben) als eigenen Service implementiert. Die iOS 10 Home App weigert sich aber diese zu erkennen bzw legt sie als nicht unterstütztes Gerät an. Damit kann man Programme nicht mehr in Szene aufnehmen, um sie zu starten.

Wenn der ios10 switch gesetzt ist, wird das Programm als HomeKit-Steckdose erzeugt und man kann es in eine Szene aufnehmen. Wird die HomeKit-Steckdose eingeschaltet, wird das Programm auf der CCU gestartet und gleichzeitig wird die HomeKit-Steckdose wieder ausgeschalten. 

Is dreckig, ich weiss aber funktioniert ;)

**Comment by bprskalo** [comment]
ja, ziemlich "dirty", aber cleverer Zug :-) .. danke für die Ausführung :-)
