### ISSUE TITLE
HM-TC-IT-WM-W-EU .... nur ein/aus .... kein Auto ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#361]
Heute ist mir in Homekit aufgefallen, dass ich die Thermostate nur ein/aus schalten kann.
Sollte da nicht auch der Punkt AUTO sein ?

lg Richard

**Comment by roe1974** [comment]
Jaaaaaaaaaaaaa :-)
lg aus Wien

**Comment by thkl** [comment]
ich sehe gerade nur der taget state hat ein AUTO .. das heisst man könnte es maximal auf Auto setzen.
Aber wenn das Thermostat auf Auto steht kann das nicht in Homekit zurück.

Ich denke mal das soll dafür benutzt werden, das das Thermostat automatisch zwischen heating und cooling wechseln kann ...

**Comment by roe1974** [comment]
okeeeeeeee :-(

**Comment by benno666** [comment]
Hallo zusammen,

danke schon mal für deine tolle Arbeit! Das mit der Heizungssteuerung für Homematic interessiert mich auch brennend. Ich habe hier zuhause noch ein paar Thermostate von Tado und diese via selbstgeschriebenem Programm in Homebridge an mein System angebunden, weil ich unbedingt den Auto-Modus integriert haben wollte. Das sollte daher mit Homematic auch funktionieren. Am besten lässt sich die Verhaltensweise des Thermostats im HomeKit Accessory Simulator nachvollziehen.

Der Target Heating Cooling State lässt sich auf OFF/HEAT/COOL/AUTO setzen. Ist das Thermostat in Homematic/Tado auf AUTO mit Wunschtemperatur 21°C gestellt, dann entspricht das in HomeKit ebenfalls AUTO und es wird "21° eingestellt" angezeigt. Ist das Thermostat in Homematic/Tado auf manuellem Modus und 21° gestellt, dann entspricht das in HomeKit HEAT und die Anzeige lautet "Auf 21°C heizen". Ähnliches gilt für AUS bzw. OFF. Da Thermostate von Homematic und Tado nicht kühlen können, ist der Status COOL irrelevant und kann in HomeKit ausgeblendet werden.

Das Ganze ist unabhängig vom Current Heating Cooling State, der kein AUTO kennt (und gar nicht kennen braucht, denn der CHCS zeigt im Prinzip nämlich nur den Ventilöffnungszustand an)! Das bedeutet Folgendes:
Ist die gewünschte Solltemperatur noch nicht erreicht (und zwar unabhängig ob im manuellen oder AUTO-Modus), dann ist das Ventil geöffnet und der CHCS steht auf HEAT. In HomeKit erhält das Thermostat ein orangenes Symbol.
Ist die Solltemperatur erreicht und das Ventil geschlossen, steht der Status des CHCS jetzt auf OFF. Das Symbol ist jetzt grün gefärbt.
Wenn die Heizung komplett ausgeschaltet ist (unabhängig vom Ventilstatus!), dann zeigt das Symbol eine graue Farbe an.

Da der Ventilöffnungszustand in Homematic (ebenso wie in Tado) ausgelesen werden kann, sollte eine Implementierung des AUTO-Modus ebenfalls möglich sein.

Gruß,
benno666
