### ISSUE TITLE
local ip used : 192.168.178.36. you may change that with local_ip parameter in config

### ISSUE THREAD

**Issue by blebbens** [thkl/homebridge-homematic#365]
Hallo,

Der Fehler "local ip used : 192.168.178.36. you may change that with local_ip parameter in config" wird mir bei jedem Start des Services "homebridge"-homematic angezeigt.

Homebridge läuft auf dem Host-System des Raspberry 3B+ (IP 192.168.178.36) und die piVCCU3 (IP 192.168.178.38) im Container auf demselben Raspberry. 

In der config.json ist die korrekte IP zur CCU eingestellt. Die Daten erhält die Homebridge auch. Doch scheint die homebridge derzeit gecachte Config-Daten zu nutzen.

Wie kann man den Fehler beheben ?

**Comment by thkl** [comment]
Das ist kein Fehler. Das ist nur eine Statusmeldung. Fehler würden rot, Warnungen gelb angezeigt.
