### ISSUE TITLE
Plugin doppelt installiert ?!

### ISSUE THREAD

**Issue by blebbens** [thkl/homebridge-homematic#366]
Hallo,

Beim Start der Homebridge wird folgende Meldung ausgegeben...

> Dez 28 16:28:54 piVCCU homebridge[4251]: [28.12.2018, 16:28:54] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-homematic' since we already loaded the same plugin from `'/usr/local/lib/node_modules/homebridge-homematic'.

Scheinbar ist das Plugin doppelt installiert. Nehmen an, eines wurde mit "-g" installiert, das andere nicht. 

Welches sollte auf welche Weise gelöscht werden, um Problemen aus dem Weg zu gehen ?
Per "npm uninstall" oder "rm" ?

**Comment by thkl** [comment]
da die Pfade ja aufgelistet sind kann das ganze Verzeichnis mit rm -R weg
