### ISSUE TITLE
Support for HM-IP Taster WRC6

### ISSUE THREAD

**Issue by MAK-CS** [thkl/homebridge-homematic#368]
Ich habe einen Homematic IP Taster HmIP-WRC6 hinzugefügt und bekomme folgende Fehlermeldung: "[HomeMatic CCU3] There is no service for HmIP-WRC6:KEY_TRANSCEIVER"

Ich würde mich sehr über eine entsprechende Anpassung / Update / Support freuen. Ist das möglich?

Liebe Grüße
MAK-CS

**Comment by devcccc** [comment]
Würde mich auch brennend interessieren

**Comment by googie0815** [comment]
gibt es schon eine Lösung?
