### ISSUE TITLE
WinMatic Integration

### ISSUE THREAD

**Issue by thkl** [thkl/homebridge-homematic#37]
...

**Comment by gernot1972** [comment]
Startet leider nicht ...

Hier die Fehlermeldung:

`
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitWinMaticService.js:46
    }.bind(this));
                ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at HomeMaticChannelLoader.loadChannelService (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:34:21)
    at /usr/local/lib/node_modules/homebridge-homematic/index.js:244:33
    at Array.map (native)
`

**Comment by thkl** [comment]
oopsi ... sollte jetzt gehen

**Comment by gernot1972** [comment]
Startet jetzt und läuft, aber weder die Home App noch Eve lässt sich starten.
Die Home App bleibt dunkel, und Eve bleibt stehen bei "HomeKit initialisieren..."

**Comment by thkl** [comment]
hmm ich muss mal sehen, ob ich eine WinMatic simmuliert bekomme .. das führt ja so zu nichts

**Comment by thkl** [comment]
so, also ich habe noch was geändert und jetzt testweise mal eine simmulierte WM hinzugefügt sie wird in Homekit angezeigt und wenn ich das Fenster öffnen lasse wird Level auf 1 und beim Schließen auf 0 gesetzt. Laut Doku sind das die Level Werte die die WM erwartet

**Comment by gernot1972** [comment]
Ok, geht wieder - die beiden sind abgestürzt, als ich versucht habe das Fenster zu bedienen...
Ist nur mit komplettem Reset wieder lauffähig geworden.
Übrigens sind meine Türkontakte jetzt auch verschwunden und haben eine Position bekommen.Das Motorfenster wäre mir nicht so wichtig wie die Fensterkontakte...

**Comment by thkl** [comment]
Ja die Türen werden als Automatictüren abgebildet, sonst funktioniert die Frage an Siri sind die Türen in .. zu nicht. Analog den Fenstern ... das kann aber über den doors bzw windows Parameter in der config.json eingestellt werden. Wenn die Kanäle da nicht enthalten sind werden sie als Kontaktsensor abgebildet.

Und ja den Crash beim Bedienen habe ich behoben

**Comment by gernot1972** [comment]
Da muss man denke ich recht aufpassen, denn die Winmatic kennt auch verriegelt und offen sowie geschlossen und geöffnet.
Sie hat zwei Motoren einer zum drehen des Griffes (Verriegeln und öffnen) und einer zum Öffnen und Schließen des Fensters in Prozent Schritten!
lg, Gernot

**Comment by thkl** [comment]
Ich weiss, ich kann aber den verriegelt zustand nicht abbilden. das kennt HK nicht. so mit geht nur auf und zu

**Comment by gernot1972** [comment]
Auf und zu geht jetzt - gerade ausprobiert.
Auch aus dem Verriegelt Zustand heraus.
Jetzt fehlt nur noch dass nach dem schließen Befehl die Winmatic das Fenster auch zusätzlich wieder verriegelt. Beim Öffnen passiert das wie geschrieben anscheinend automatisch.

Bzgl. Doors Parameter: Meine Homematik FK auf den Türen waren vorher in HomeKit  in der Type Türen mit offen und geschlossen (da im Parameter "Doors" eingetragen) - wie es sein soll - jetzt haben sie nur noch einen Positionsstatus und außerdem den Hinweis auf eine Blockade!?

**Comment by thkl** [comment]
Ja die WM Verriegelt wenn man den Level Datenpunkt auf < 0 setzt .. das könnte ich jetzt natürlich auch automatisch machen das die WM immer verriegelt ...

Ja das mit den Türen bau ich glaub ich wieder zurück

**Comment by gernot1972** [comment]
Ist sicher nicht einfach es jedem Anwender recht zu machen.
Nur zu schließen ohne Verriegeln hat auch Vorteile, zumal man das Verriegeln auch über ein HM Programm Zeit, oder Wetterabhängig zusätzlich reinprogrammieren könnte.

Sent from a mobile device. I appologize for the brevity and typos.

**Comment by thkl** [comment]
so ich hab jetzt das alte verhalten der Türen zurückgebaut und die WM verriegelt beim Schließen ...
Fenster zu ist also Fenster ganz zu ;)

**Comment by gernot1972** [comment]
DANKE, aber jetzt hab ich das Problem:

/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitWinMaticService.js:61
       hcvalue = value;
               ^
ReferenceError: hcvalue is not defined
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitWinMaticService.js:61:16
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:86:32
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:195:9
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:163:9
    at callback (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:42:7)
    at Deserializer.onDone (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
    at SAXStream.emit (events.js:104:17)
    at Object.SAXStream._parser.onend (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:325:33)
    at end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:363:3)
    at Object.SAXParser.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:209:16)

**Comment by thkl** [comment]
Fcking tippfehler.

Sekunde ich update das gleich .

**Comment by gernot1972** [comment]
PASST!
Funktioniert - Kann ich noch ein paar Sachen anregen??

z.B. die Type „in Verwendung“ bezieht sich momentan auf alle Steckdosen oder „Outlets“ oder?

Die haben aber keinen Messwiderstand, deshalb macht diese Type dort keinen Sinn.
Im Gegensatz zu den Aktoren HM-ES-PMSw1-Pl 
Bei denen könnte man die Type doch zuordnen, oder?

vG
Gernot

**Comment by thkl** [comment]
ja könnte man machen, aber die Messwerte kommen aus einem anderen Kanal als der Switch ... daher ist das arg kompliziert, ich splitte ja die Geräte alle in Kanäle auf damit zb doppelte Schaltaktoren funktionieren

**Comment by thkl** [comment]
so, die WinMatic ist in 0.0.42 eingeflossen.
