### ISSUE TITLE
Subsection wirkt nicht

### ISSUE THREAD

**Issue by QualityAgileFlow** [thkl/homebridge-homematic#370]
Hi,
ich nutze die CCU (2.31.25) auf deinem Mediola-Gateway (V5+). Ich kann die Gewerke-Liste dort anscheinend nicht editieren und muss die vom System vorgegebenen verwenden, z.B. "Umwelt".
Wenn ich diesen als subsection eintrage werden dennoch alle Kanäle übernommen.
Die Filter-Parameter funktionieren.

**Comment by udochrist** [comment]
Als subsection trägt man normalerweise einen "Favoriten" und kein Gewerk ein. Der Favorit kann frei angelegt werden und nur die Kanäle die auf die Homebridge sollen sollten dort rein.

**Comment by QualityAgileFlow** [comment]
Oh, danke. Das hatte ich anders verstanden. Die CCU auf dem Mediola Gateway ist leider recht beschnitten, Favoritenverwaltung habe ich dort auch nicht. Danke für Hilfe.
