### ISSUE TITLE
HM-Sec-SCo Fensterkontakt aktualisiert nicht mehr

### ISSUE THREAD

**Issue by MikeDeltaHH** [thkl/homebridge-homematic#371]
Nabend!
Ich habe diverse Homematic & Homematic IP Geräte im Einsatz die ich per HB an mein HomeKit Setup weiterreiche und bis vor einiger Zeit funktioniert auch alles problemlos, nur ist mir mehr so zufällig aufgefallen dass die HM-Sec-SCo Kontakte bei mir keine Statusänderungen mehr anzeigen, sie werden immr mit dem Status "JA", also geschlossen angezeigt auch wenn die Fenster geöffnet sind - ich habe drei davon im Wohnzimmer und wunderte mich immer warum eine Regel die mit einem der Kontakte verknüpft ist nicht mehr läuft in der HomeMatic WebUi werden die Stati richtig angezeigt... ich kann nun nicht genau sagen seit wann das der Fall ist, alle anderen Kontakte (HMIP-SWDO) funktionieren noch, sonstige HM & HMIP Geräte ebenfalls. Habe jetzt mal die Homebridge Installation auf einem anderen Pi neu gemacht und gleiches Ergebnis...

piVCCU3 mit FW 3.41
HomeBridge: 0.4.45
Node: 10.15.0
npm: 6.4.1
homebridge-homematic v0.0.109

Ich hoffe Du kannst helfen.

Gruß!
Mike

**Comment by MikeDeltaHH** [comment]
ZUr Info... ich habe die Versionen 0.0.108 & 0.0.107 getestet, gleiches Problem...

**Comment by ChristianFFB** [comment]
Bei mir dasselbe Problem mit sämtlichen Plugin Versionen. Seit Raspberrymatic 3.41.11.20181126

**Comment by MikeDeltaHH** [comment]
Hallo!
Wird das plugin noch gepflegt? Ansonsten überlege ich die Kontakte gegen IP Versionen auszutauschen a mir die Regeln in HK sehr wichtig sind...

**Comment by thkl** [comment]
Ja wird es. 
Es gibt eine Änderung in der Security der CCU seit 3.41 ggf liegt das Problem mit den Kontakten da dran.  Fix liegt im Dev Branch.

**Comment by MikeDeltaHH** [comment]
Moin!
Wie muss ih diesen Fix anwenden... ist das nur die Datei "ChannelServices/HomeMaticHomeKitContactService.js" die auszutauschen ist? Die finde ich nirgends in meiner HomeBridge VM...

**Comment by MikeDeltaHH** [comment]
Moin!
Wie muss ich diesen Fix anwenden? Ich habe es damit versucht den Inhalt der korrigierten HomeMaticHomeKitContactService.js in die Originaldatei zu schreiben, aber das hat meine HB beim Neustart zum Absturz gebracht... in der gefixten Datei fehlen auch diverse ; Einträge also vermute ich mal dass ich da anders vorgehen muss...

**Comment by MikeDeltaHH** [comment]
Kann mir hier jemand helfen wie ich diesen Fix anwenden muss?

**Comment by MikeDeltaHH** [comment]
Wird der Fix mal in ein Release übernommen? Ich bekomme es nicht hin den Fix in meine Config einzubauen...
