### ISSUE TITLE
HM-CC-RT-DN zeigt keine aktuelle temperatur und Zieltemperatur falsch

### ISSUE THREAD

**Issue by rkrug** [thkl/homebridge-homematic#373]
Hallo

erstmal vielen Dank für diese plugin - es funktioniert wirklich gut.

Ich versuche meine CCU3 mit Heizungsventilen über HomeBridge in HomeKit zu bekommen.

Ich habe das Gewerk HomeKit so definiert:

![screenshot 2019-01-06 at 16 58 39](https://user-images.githubusercontent.com/487172/50738500-ed17a700-11d4-11e9-9747-dad0dcba218a.png)

Die HmIP-eTRV-B funktioniert und zeigt auch die aktuelle und die Zieltemperatur, aber die zwei HM-CC-RT-DN nicht (weder ziel nock aktuelle Temperatur).

Mache ich etwas falsch, oder ist da ein bug irgendwo?

Vielen Dank,

Rainer

Meine Homebridge config (erstellt mit der iOS app) sieht wie folgt aus:

```
{
  "accessories" : [
    {
      "ip" : "xxx.xxx.xxx.xxx",
      "accessory" : "NetworkDevice",
      "pingInterval" : "15",
      "mac" : "xxxxxxx",
      "wakeGraceTime" : "20",
      "name" : "Example PC",
      "shutdownGraceTime" : "45"
    },
    {
      "name" : "Pi Temp",
      "accessory" : "RaspberryPiTemperature"
    }
  ],
  "bridge" : {
    "username" : "irgendwas",
    "name" : "Homebridge",
    "pin" : "dolle pin",
    "port" : 51826
  },
  "platforms" : [
    {
      "ccu_ip" : "192.168.1.xxx",
      "name" : "HomeMatic",
      "doors" : [

      ],
      "enable_hmip" : true,
      "platform" : "HomeMatic",
      "windows" : [

      ],
      "filter_device" : [

      ],
      "filter_channel" : [

      ],
      "outlets" : [

      ],
      "subsection" : "Homekit",
      "programs" : [

      ]
    }
  ]
}
```

**Comment by fuerst** [comment]
Bei mir ist es genauso: die aktuellen Werte der HM-CC-RT-DN werden nicht angezeigt. Eine Steuerung scheint jedoch möglich zu sein.

Die CCU ist ein RaspberryMatic 3.47.18.20190918. 
Homebridge läuft unter NodeJS 12 auf einem Ubuntu 18.04

**Comment by Hofei90** [comment]
Hallo,
ich hatte am Wochenende genau das selbe Problem.
siehe hier: https://forum.smartapfel.de/forum/thread/4087-homematic-heizk%C3%B6rperthermostat-zeigt-0-c-in-homekit-und-homebridge-an/?postID=68607#post68607
Beitrag 2 führt zur Lösung. Es muss eine Datei "HomeMaticRPC.js" angepasst werden. Jetzt funktioniert es bei mir einwandfrei

**Comment by fuerst** [comment]
Danke, @Hofei90. Mit den Änderungen an _HomeMaticRPC.js_ funktioniert es.
Ich habe einen dazu passenden PR erstellt, der das BINRPC als Kommunikationsprotokoll entfernt. Laut Jens Maus (RaspberryMatic) soll nur noch XMLRPC genutzt werden.
