### ISSUE TITLE
service Schalter, Licht

### ISSUE THREAD

**Issue by Halver01** [thkl/homebridge-homematic#374]
Hallo erst einmal und ein großes Lob an die Entwickler.

Seit ein Halben Jahr läuft Homebridge-homematic bei mir ohne Fehler.
Es kommen immer mehr Autoren da zu.
Eine Frage habe ich nun doch. Ich weiß das Nehmer wurde oft behandelt aber ich komme nicht weiter.

Habe mehrere Schaltsteckdosen HMIP-PSM die ich als Schalter definiert möchte. Unter outlets habe ich diese eingetragen.
Aber ich bekomme es nich hin diese als Schalter darzustellen. Nur Licht, Ventilator oder Steckdose.

An bei ein Auszug aus meiner config. 
Hoffe es gibt eine Lösung. 
{
    "bridge": {
        "name": "Homebridge",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            }
        },
        {
            "platform": "HomeMatic",
            "name": "ccu3-webui",
            "ccu_ip": "xxx.xxx.xxx.xxx",
            "enable_hmip": " true",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [
                "HmIP-RF.0001D8A98EFEE8:3",
                "HmIP-RF.000458A9961505:3",
                "HmIP-RF.0001D8A98EFF2A:3"
            ],
            "doors": [],
            "windows": [],
            "programs": [],
            "accessories": [],
            "subsection": "Homekit",
            "variables": [
                "Anwesenheit",
            ]
        },

**Comment by Halver01** [comment]
Danke für die Info. Aber das Icon kann ich in Home nicht änder.
![bildschirmfoto](https://user-images.githubusercontent.com/46458565/50792406-2af3f880-12c5-11e9-88e0-d2222b48026e.jpg)

**Comment by bprskalo** [comment]
Das Symbol kann nur in der Einstellung “Licht” angepasst werden

Die Steckdose kurz antippen .. oder wenn Du etwas länger auf dem Symbol bleibst erhältst Du ja dieses Bild :

![b34c06c5-2db0-474b-aadb-5bb1a59c1e9a](https://user-images.githubusercontent.com/17832335/50792867-b1f5a080-12c6-11e9-8bb3-ea59c5fd0258.png)

**Comment by Halver01** [comment]
Ja da hast du recht, aber ich kann nur Licht Symbole auswählen seh ich das richtig?
![bildschirmfoto 2019-01-07 um 21 59 27](https://user-images.githubusercontent.com/46458565/50793234-c9815900-12c7-11e9-8bee-2540ea3ecf18.png)

**Comment by bprskalo** [comment]
ja genau, bei Licht kannst du die Art der Lampe etwas anpassen .. Steckdose ist Steckdose ..

wenn Du mehr Optionen möchtest .. kannst Du die Eve App verwenden ... die kann mehr ;-)

**Comment by Halver01** [comment]
OK Danke.
