### ISSUE TITLE
Schaltaktor HM-LC-Sw1-Ba-PCB für Türöffner wird fälschlicherweise als Licht erkannt

### ISSUE THREAD

**Issue by glowfishDE** [thkl/homebridge-homematic#379]
Hi, 

vielen Dank für dieses wunderbare Homebridge welches mein Leben so viel leichter macht 👍 

Ich habe die Platine HM-LC-Sw1-Ba-PCB welche mittels 12 Volt ein kleines Relais im Sicherungskasten schaltet, welches dann potentialfrei den Kontakt meines Türöffners bedient. Soweit so gut.

Leider wird der Aktor immer als Licht erkannt:

Hersteller: EQ-3
Seriennummer: BidCos-RF.OEQXXXXXXX:1
Modell: SWITCH
Firmware: 1.0

Wenn ich jetzt mein Licht schalte geht kann unten die Haustür geöffnet werden bis ich mein Licht wieder aus mache - eigentlich witzig aber sicher nicht als Homecoming Function gedacht :)

Damit das nicht mehr passiert habe ich das ganze jetzt in der config.json in "outlets" gepackt:

"outlets": ["BidCos-RF.OEQ0285402:1"],

ABER - das ist ja eigentlich auch keine Steckdose und das Steckdosensymbol im Apple Home finde ich auch nicht so schön.

Am liebsten würde ich es unter "doors" laufen lassen (macht nach meinem Denken am meisten Sinn?) 
Aber wenn ich´s da reinpacke wird es trotzdem einfach wieder als Licht erkannt. Nur als outlet gehts - doors, windows, rotary_handles, etc.. hab ich alles probiert - das nimmt er nicht.

Frage: Kann man per Device einen Typ zuordnen? Also per Seriennummer ? Das wäre wohl das schönste. Bsp: 

"Types": [
	{ "device": "BidCos-RF.OEQXXXXX:1",
          "type": "door"
	}],

Oder ist das ein Denkfehler von mir ? Würde es ja nicht brauchen wenn man einfach was in die "doors" reinwerfen kann was auch keine Tür ist.

Oder vielleicht braucht es einfach eine Türöffnerunterstützung. Nicht jeder will mit diesem "HM-LC-Sw1-Ba-PCB" Switch ein Licht schalten.

Bin für Vorschläge und Hilfe dankbar.

VG
Stoney

**Comment by matthesdr** [comment]
Please reopen this issue or give any hint to add the device HM-LC-Sw1-Ba-PCB in a useful way. 

I have the same problem and it would be good to know, if it can work in the mentioned  or better way.

**Comment by thkl** [comment]
Ok, das ist etwas älter. Das Problem ist nicht beim homematic Plugin zu suchen, sondern eher bei der Tatsache, das Siri beim Kommando "Schalte das Licht an" einfach alle Lampen einschaltet.

Ein Mapping auf Door wird auch nicht helfen, denn Door ist eine elektrische Tür. Die hat einen Current und Target Öffnungsgrad. 

Es wird aber in der nächsten Version eine Lösung dafür geben. Dann können Switch Kanäle flexibler gestaltet werden:

![image](https://user-images.githubusercontent.com/884355/75560050-cd7cb700-5a44-11ea-810c-83dadafb1fce.png)

Grundsätzlich: Es können nicht beliebige Services an jeden Kanaltype gebunden werden. Aber das wird die kommende WebOberfläche verhindern. Die lässt nur kompatible Services einstellen.
