### ISSUE TITLE
Homematic IP Dimmersteckdose HMIP PDT Support

### ISSUE THREAD

**Issue by muenchnerdanny** [thkl/homebridge-homematic#382]
Hallo,
Wäre es möglich die Dimmersteckdose Homematic IP PDT zu unterstützen? Dann wäre das meine 100% Lösung:)

Vielen Dank schon mal!

**Comment by thkl** [comment]
Müsste gehen indem der Channel 3 des Gerätes zu Homekit hinzugefügt wird und das hier zu ChannelServices/channel_config.json hinzugefügt wird:

> ,{
> 	   "type": "DIMMER_VIRTUAL_RECEIVER",
> 	   "service": "HomeMaticHomeKitDimmerService"
> 	}

Bitte drauf achten, das das File am Ende ein valides JSON ist. Kann bei jsonlint.com getestet werden.
