### ISSUE TITLE
CUxD System.Multi-Dim-Exec mit RGB

### ISSUE THREAD

**Issue by martinzuern** [thkl/homebridge-homematic#385]
Ich habe mehrere RGB-Lampen an einem virtuellen 16-Kanal-Dimmer mit CUxD. Dabei sind je 3 Kanäle pro Lampe für die drei Farben in Verwendung. 
Gibt es eine Möglichkeit, dies in homebridge-homematic einzubinden? Ich habe mir schon die Serviceklassen angesehen, aber keine passt so richtig - RGBW erwartet z.B. einen “Color”-Channel.

Falls es aktuell keine Möglichkeit dafür gibt, wo könnte man am besten ansetzen um es zu implementieren?

**Comment by thkl** [comment]
Dafür müsste man eine eigene Serviceklasse scheiben, die die 3 Kanäle zu einem RGB Gerät zusammenfasst. Problem dabei ist, das ich keine Events von CuxD abonniere, das heisst, sollte sich auf dem Gerät aus Seiten der CCU etwas ändern, dann kommt das nicht bei HomeKit an
