### ISSUE TITLE
Rollade (blind) wird als Lichtschalter angegeben

### ISSUE THREAD

**Issue by martindex23** [thkl/homebridge-homematic#386]
Hallo, habe folgendes Problem. Mein Rolladenaktor wird immer als Lichtschalter angegeben und ich kann es nicht runter oder hochfahren. Woran könnte das liegen?
Vielen Dank im Voraus.

**Comment by martindex23** [comment]
Update: Meine config sieht wie folgt aus:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:xxxxxxxxxxxx",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            }
        },
        {
            "platform": "HomeMatic",
            "name": "HomeMatic CCU",
            "ccu_ip": "19xxxxxxxxxx",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "programs": [],
            "subsection": "Homekit",
            "variables": [
                "Leinwand"
            ]
        }
    ],

Ich verwende den Roladenaktor HM-LC-BL1-FM

Angezeigt wird mir aber nur ein Lichtschalter, womit ich die Jalousie (Leinwand) nicht steuern kann

**Comment by martindex23** [comment]
![img_2969](https://user-images.githubusercontent.com/47195862/52056112-a150e700-2561-11e9-9909-d92d47967bfe.PNG)
![img_2971](https://user-images.githubusercontent.com/47195862/52056113-a150e700-2561-11e9-8e58-c76d6a042b6a.PNG)

**Comment by thkl** [comment]
Bitte mal homebridge im Debug Mode starten (homebridge -D) ..
Und dann im Log suchen nach:


> [2019-2-23 10:52:19] [HomeMatic] Load BuildIn Service Class ......
> [2019-2-23 10:52:19] [HomeMatic] service for HM-LC-BL1-FM.....  is ......
> [2019-2-23 10:52:19] [HomeMatic] Check config for HM-LC-BL1-FM:.....
> 

Den Teil brauch ich mal hier als Info

**Comment by martindex23** [comment]
Habe folgendes im Log gefunden, mehr ist da leider nicht im Bezug auf HomeMatic. Das Gerät HM-LC-BL1-FM taucht im Log auch nirgendswo auf.

Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] Loading 2 platforms...
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [Config] Initializing config platform...
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [Config] Spawning homebridge-config-ui-x with PID 8034
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] Initializing HomeMatic platform...
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] Homematic Plugin Version 0.1.1
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] running in production mode
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] will connect to your ccu at 192.168.0.213
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] using xmprpc for communication with BidCos-RF
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] init RPC for BidCos-RF.
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] local ip used : 192.168.0.67. you may change that with local_ip parameter in config
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] init RPC for VirtualDevices.
Feb 24 11:04:00 raspberrypi homebridge[8006]: [2/24/2019, 11:04:00 AM] [HomeMatic CCU] local ip used : 192.168.0.67. you may change that with local_ip parameter in config

**Comment by martindex23** [comment]
ich finde log folgende info. Leider gibt es keinen weiteren Teil in Bezug auf Homematic oder HM-LC-BL1-FM

Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] Loading 2 platforms...
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [Config] Initializing config platform...
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [Config] Spawning homebridge-config-ui-x with PID 8694
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] Initializing HomeMatic platform...
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] Homematic Plugin Version 0.1.1
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] running in production mode
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] will connect to your ccu at 192.168.0.213
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] using xmprpc for communication with BidCos-RF
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] init RPC for BidCos-RF.
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] local ip used : 192.168.0.67. you may change that with local_ip parameter in config
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] init RPC for VirtualDevices.
Feb 24 11:08:17 raspberrypi homebridge[8674]: [2/24/2019, 11:08:17 AM] [HomeMatic CCU] local ip used : 192.168.0.67. you may change that with local_ip parameter in config

**Comment by martindex23** [comment]
und in /var/log/syslog komme ivh nicht rein trotz Root rechte und Benutzer in adm Gruppe
pi@raspberrypi:~ $ groups
pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi
pi@raspberrypi:~ $ ls -l /var/log/syslog
-rw-r----- 1 root adm 905004 Feb 24 11:32 /var/log/syslog

**Comment by martindex23** [comment]
hallo, ich habe die homebrdige nochmal neu aufgesetzt und die homebridge im Begug mode (homebridge -D) neu gestartet. Die "Blind" wird nach wie vor als Schalter wie oben in den Bildern angezeigt. Einzig folgende Meldung kam bezüglich Homematic:

[2/27/2019, 2:39:58 PM] Loaded plugin: homebridge-homematic
[2/27/2019, 2:39:58 PM] Registering platform 'homebridge-homematic.HomeMatic'
[2/27/2019, 2:39:58 PM] ---
