### ISSUE TITLE
CUxD CUX2801001 - wird nicht aktualisiert

### ISSUE THREAD

**Issue by krobipd** [thkl/homebridge-homematic#389]
hey

hab ein CUxD gerät installiert - eine quasi Fake Fernbedienung (wie ich sie nenne).

Ich möchte damit Aktionen bzw Programme in Homematic auslösen - der Homematic Teil funktioniert auch einwandfrei.

Ich schalte also via Homekit den Schalter auf EIN und dieser löst dann das Homematic Programm aus. In diesem Programm wird der Schalter dann wieder auf AUS geschaltet - dies könnte ich ja dann via Homekit weiterverarbeiten.

Nun auf der CCU wird dies auch gemacht - also Schalter EIN, Programm wird ausgeführt, via Programm Schalter wieder auf AUS. ABER Homekit bekommt diese Aktualisierung nicht mit.

Alle normalen Aktoren usw funktionieren aber einwandfrei und sehr flott. Die CCU 3 Firewall hab ich auch Testweise auf offen gestellt.

Es handelt sich um das CUxD Gerät - CUX2801001 bzw HM-RC-19.

**Comment by thkl** [comment]
Ja CuxD Events abonniere ich nicht. Daher werden keine Änderungen übertragen.

**Comment by krobipd** [comment]
Ok 😔sehr schade
Finde die CUxD „Fake-fb“ eine tolle Sachen vor allem da man sie meist früher oder später für system exec besucht und dann 15 Fernbedienungstasten hat. Diese man ja problemlos nutzen kann.

Finde ich persönlich auch die elegantere Lösung als die variablenlösung.
In diesem Falle siehe das bitte als Feature Request. Da ja das Auslösen funktioniert und die Taster ja jetzt schon aktualisiert werden nur nicht in Echtzeit sondern nur wenn ein voller refresh (Aktualisierung aller Geräte) stattfindet.

Danke

**Comment by krobipd** [comment]
Kommentarlos geschlossen? Cuxd wird ja Unterstützt aber nicht aktualisiert.

**Comment by thkl** [comment]
Ja, aber ohne Events macht das keinen Sinn.

**Comment by krobipd** [comment]
gibt es keine events seitens der ccu? oder, so wies dus geschrieben hast, abonnierst du sie nicht?
wenn du sie nicht abonnierst ist dann nicht möglich dies zu implementieren?
ich denke mir halt nur da ja grundsätzlich cuxd Kompatibilität vorhanden ist ist es ja schade das sie dann nicht voll nutzbar ist. abgesehen von den punkten die ich oben geschrieben habe.

du hast ja einen irren aufwand betrieben um variablen Aktualisierung rein zu bekommen.

**Comment by KoMa1978** [comment]
Würde mich hier mal einklinken wollen ...

Ich habe einige Enocean Fenstergriff Sensoren eingebunden und die werden auch nicht aktualisiert.

Eine Aktualisierung an sich sollte aber möglich sein, denn andere Apps (iobroker oder @home) bekommen ja eine Aktualisierung.

**Comment by Tonitom** [comment]
Maybe there is a workaround to get the status of the CUxD devices updated?

My garage tilt sensor has a dropout every few weeks, so I installed a second door contact. A CUxD sensor (type FS20-03) is now triggered when one of these devices has a status change and takes over its status. I used this CUxD device in the Homebridge garage configuration, but unfortunately the garage door status is not updated.


Tonitom
