### ISSUE TITLE
Hänger

### ISSUE THREAD

**Issue by thoduh** [thkl/homebridge-homematic#39]
Seit kurzem immer wieder "hänger":
[2016-10-09 16:23:23] [HomeMatic CCU] Watchdog Trigger - Reinit Connection for BidCos-RF. after idle time of 679 seconds

Was hat es damit auf sich?

**Comment by thkl** [comment]
das wird ausgelöst wenn 10 Minuten lang kein Event über eine Geräteänderung rein kommt. Damit wollte ich sicherstellen, das die RPC Verbindung nicht unbemerkt abbricht.  Ich werde das mal optional machen. Funktioniert recht gut wenn man Thermostate hat, aber wenn nicht kann es vorkommen, das 10 Minuten keine Werteänderung durch die CCU reportet wird.

**Comment by thoduh** [comment]
Danke für die schnelle Antwort.
Thermostate habe ich mehrere, dann sollte das nicht auftreten?

**Comment by thkl** [comment]
eigentlich schicken die, wie ich experimentell ermittelt habe mindestens aller 2-3 Minuten eine Werteänderung. Ich mach das optional .... und fertig ...

**Comment by thoduh** [comment]
Hab 80 Geräte an der CCU2 hängen...

**Comment by thkl** [comment]
Es gibt jetzt einen Config Parameter (watchdog) . Wenn der 0 ist (also nicht gesetzt) wird der WD weggelassen. Ansonsten kann man da die Sekunden angeben die auf einen Event gewartet wird.
