### ISSUE TITLE
Rolladenaktor (HM-LC-BI1PBU-FM) not supported?

### ISSUE THREAD

**Issue by Dany4you** [thkl/homebridge-homematic#390]
Nutze den oben genannten Rolladenaktor. 

https://www.eq-3.de/produkte/homematic/rolllaeden-und-markisen/hm-lc-bi1pbu-fm.html#download

Leider scheint dieser nicht unterstützt zu werden. Gibt es da irgendeinen Workarround?

**Comment by thkl** [comment]
Es gibt leider noch (?) keine Doku zu dem Ding bei eq3 auf der Webseite ...
Das Log sollte für den Aktor eine Fehlermeldung rauswerfen ... die bräuchte ich mal

**Comment by spionwanze** [comment]
Wichtige Info: 
Die HM-LC-Bl1PBU-FM wurden im der NPM Version 0.0.98 sowie der von mir letzen verwendeten Development 0.1.1 direkt unterstützt. Erst nach dem Update auf aktuelle Development Version 0.1.2 sind diese bei mir nicht mehr vorhanden. 

Lässt sich das irgendwie reaktivieren?

**Comment by drtp** [comment]
Ich habe neun HM-LC-Bl1PBU-FM im Haus im Einsatz. Diese lassen sich problemlos über die Homebridge per Home App und Siri ansteuern. Verwende das homematic-Plugin Version 0.0.109.
