### ISSUE TITLE
Geräte nicht erreichbar beim ersten aufruf im LAN

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#393]
Hallo Thomas
Ich habe jetzt festgestellt, dass das nicht erreichen der geräte beim ersten öffnen der Home App im LAN mit zunehmender anzahl an geräten (derzeit 85) nur beim homematic plugin auftritt. ich habe jetzt mehrere instanzen für die anderen plugins ... also für jedes eine ... bei den anderen instanzen sind die geräte sofort da.
kann das daran liegen, da du ja den status immer von den geräten „live“ holst und nicht aus der ccu ? ... was genau wird in der ccu.json gespeichert ?
lg richard

**Comment by thkl** [comment]
Die Geräteinfos werden von der CCU geholt wenn Homekit explizit danach fragt. Also im Falle das die HomeKit App geöffnet wird. Ansonsten liefert die CCU ja die Geräte Änderungen per Event. Dieser wird auch zu HomeKit durchgereicht. Daher "bewegen" sich die Icons in der HomeApp wenn das Gerät seinen Zustand ändert.

In der ccu.json wird der Gerätebaum gespeichert. Wenn Homebridge startet und keine Geräte von der CCU kommen (warum auch immer) wird dieses Cache benutzt um Geräte nach Homekit zu exportieren. Ansonsten wären nämlich alle Geräte weg.

**Comment by smarti2019** [comment]
hier genauso so, hatte bislang nur homebridge-hue plugin in der Homebridge integriert.
Jetzt zusätzlich das homematic plugin. Hier sind 5 Thermostate sonst nix von der CCU.
Seit der integration kommen keine Daten für die homematich komponenten, bwz immer erst nach einiger zeit. Im Einsatz das aktuellste 0.109 plugin sowie homebridge aktuell auf raspberry pi
