### ISSUE TITLE
Rollos werden nicht gefunden

### ISSUE THREAD

**Issue by DSchumacher2104** [thkl/homebridge-homematic#395]
Hallo Thomas!

Ich habe auf das Problem, dass meine Rollos (blinds) nicht mehr gefunden werden. Im log steht:

[2019-2-24 12:38:50] [HomeMatic CCU] There is no service for HMW-LC-Bl1-DR:BLIND
[2019-2-24 12:38:50] [HomeMatic CCU] There is no service for HMW-LC-Bl1-DR:BLIND
[2019-2-24 12:38:50] [HomeMatic CCU] There is no service for HMW-LC-Bl1-DR:BLIND
[2019-2-24 12:38:50] [HomeMatic CCU] There is no service for HMW-LC-Bl1-DR:BLIND
[2019-2-24 12:38:50] [HomeMatic CCU] There is no service for HMW-LC-Bl1-DR:BLIND

Ich habe die aktuelle developer version installiert. Was kann ich tun???

**Comment by thkl** [comment]
mal das zur ChannelServices/channel_config.json hinzufügen

> ,{
> "type":"HMW-LC-Bl1-DR:BLIND", 
> "service": "HomeMaticHomeKitBlindService"
> }

Drauf achten das es weiterhin ein valides json ist -> auf jsonlint.com kann man das testen

**Comment by DSchumacher2104** [comment]
Super! Sind wieder da!

Danke :-)

**Comment by thkl** [comment]
Perfekt ;o)

**Comment by DSchumacher2104** [comment]
Aber leider werden die Stati nicht richtig dargestellt, also obwohl geöffnet, werden sie als geschlossen angezeigt. sobald sie 100% geöffnet erreichen. Alle Stati <100% werden korrekt angezeigt! Komisch

**Comment by DSchumacher2104** [comment]
Muss ich wegen der 100%-geöffnet-Zustands einen Eintrag in die config.json machen?

Obwohl als Datenpunkt 100% angegeben ist, zeigt HomeKit geschlossen an, bei 99% wird in HomeKit noch alles richtig angezeigt.

Datenpunkte CCU2:
`<channel name="Arbeitszimmer Rollo" ise_id="2185" index="3" visible="true" operate="true">
<datapoint name="BidCos-Wired.HEQ0103282:3.LEVEL" type="LEVEL" ise_id="2188" value="1.000000" valuetype="4" valueunit="100%" timestamp="1551010883" operations="7"/>
<datapoint name="BidCos-Wired.HEQ0103282:3.STOP" type="STOP" ise_id="2189" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/>
</channel>`

Kannst du da mal eventuell nachschauen, Thomas? Die falschen Werte machen mich echt wahnsinnig. Ich habe mir schon die Datei `HomeMaticHomeKitBlindService.js` angesehen, ich erkenne da leider nichts  :-(

Danke!
