### ISSUE TITLE
Falsche Werte in der EVE fakegato history

### ISSUE THREAD

**Issue by udochrist** [thkl/homebridge-homematic#397]
Bei Den HM-IP BWTH funktioniert das Datensammeln nicht gut. Die Werte fallen hier extrem oft auf 0 grad anstelle des korrekten Wertes. (Siehe Bild)

![fe5ed688-f428-466b-baa1-106062844a0b](https://user-images.githubusercontent.com/869637/53696268-976f0d80-3dc5-11e9-8d17-1523e568653b.jpeg)

Für die non-HMIP Wandthermostate funktioniert das dagegen bestens.
![65c6f275-f502-45da-9d30-94eb2e8d7c11](https://user-images.githubusercontent.com/869637/53696267-976f0d80-3dc5-11e9-9569-c67dbaefe84d.jpeg)

Ich habe von jeder der beiden Arten mehrere Geräte und das Problem ist konsistent.

**Comment by udochrist** [comment]
nachdem eine homebridge jetzt mit den aktuellsten node, npm, ... version am start ist habe ich nochmal getestet...

im store der die werte protokolliert stehen die 0 werte so nicht drin für die temperatur.

```
/homebridge # cat six_HmIP-RF.<ID>:1_persist.json | python -m json.tool| grep -i temp
            "currentTemp": 21.3,
            "setTemp": 21,
            "currentTemp": 21.4,
            "currentTemp": 21.6,
            "currentTemp": 21.6,
            "setTemp": 21,
            "currentTemp": 21.4,
            "setTemp": 21,
            "currentTemp": 21.4,
            "currentTemp": 21.4,
            "setTemp": 21,
            "currentTemp": 21.4,
            "currentTemp": 21.4,
            "currentTemp": 21.4,
            "setTemp": 21,
            "currentTemp": 21.4,
            "setTemp": 21,
            "currentTemp": 21.4,
            "currentTemp": 21.4,
            "currentTemp": 21.4,
            "setTemp": 21,
            "currentTemp": 21.4,
``` 
es ist auch so, dass die werte zum zeitpunkt immer alle da zu sein scheinen.
```
        {
            "humidity": 38,
            "time": 1552931629
        },
        {
            "currentTemp": 22.4,
            "time": 1552932229
        },
        {
            "humidity": 38,
            "time": 1552932229
        },
        {
            "currentTemp": 22.4,
            "time": 1552932829
        },
        {
            "humidity": 38,
            "time": 1552932829
        } 
```

**Comment by udochrist** [comment]
nicht mehr relevant

**Comment by emcepe** [comment]
Warum ist das nicht mehr relevant?

Ich habe das gleiche Problem mit den aktuellsten Software Versionen :-( und bisher 0 Lösung dafür gefunden.

**Comment by emcepe** [comment]
gibt es hier eigentlich mal irgendwas neuess? :)
