### ISSUE TITLE
HM Rollos (UP und Schalter) zeigen falschen Zustand an

### ISSUE THREAD

**Issue by udochrist** [thkl/homebridge-homematic#400]
In der aktuellsten Version funktionieren HM Rollos nicht korrekt. Die Home.app zeigt die Rollos andauernd als "Wird geöffnet" oder "Wird geschlossen" an. Geöffnet und geschlossen werden die Rollos dabei sicher nicht. es scheint als ob events nicht korrekt ankommen. Das hatte in alten Versionen alles perfekt funktioniert. 
Logs/Tests o.ä gerne, aktuell wüsste ich nicht was ich konkret tun kann. Der Rollo aus dem Foto wurde beim Sonnenaufgang durch die CCU geöffnet. in der app ist er noch aktiv.

![Bildschirmfoto 2019-03-16 um 16 31 30](https://user-images.githubusercontent.com/869637/54477521-f8a4d100-4808-11e9-8205-6aa88808e4aa.png)

**Comment by udochrist** [comment]
Kann es sein, dass die ChannelKonfig nicht passt. 
```
[3/18/2019, 11:25:37 AM] [HomeMatic CCU] There is no service for HM-LC-Bl1-FM:BLIND
[3/18/2019, 11:25:37 AM] [HomeMatic CCU] There is no service for HM-LC-Bl1-FM:BLIND
[3/18/2019, 11:25:37 AM] [HomeMatic CCU] There is no service for HM-LC-Bl1PBU-FM:BLIND
[3/18/2019, 11:25:37 AM] [HomeMatic CCU] There is no service for HM-LC-Bl1-FM:BLIND
[3/18/2019, 11:25:37 AM] [HomeMatic CCU] There is no service for HM-LC-Bl1PBU-FM:BLIND
[3/18/2019, 11:25:37 AM] [HomeMatic CCU] There is no service for HM-LC-Bl1PBU-FM:BLIND
[3/18/2019, 11:25:37 AM] [HomeMatic CCU] There is no service for HM-LC-Bl1-FM:BLIND
```
Die channel_config.json (in der development version hat den ```HM-LC-Bl1-SM:BLIND```. das sieht nach Tippfehler aus...

**Comment by DSchumacher2104** [comment]
Ich habe das gleiche Problem mit den falschen Zuständen und glaube, dass die Statusmeldungen der CCU2 vom Plugin irgendwie falsch ausgewertet oder überschrieben werden und zwar immer dann, wenn die CCU2 eine Statusaktualisierung an das Plugin sendet. Öffne ich ein Rollo über die HomeApp, zählt die Visualisierung in der HomeApp während des Öffnens die Prozente ordentlich bis auf 100% hoch. Ich vermute, dass die CCU2 dann als Abschluss den Status "Rollo geöffnet" an das Plugin sendet und genau in dem Moment zeigt die HomeApp dann wieder "geschlossen" an. Ich habe z. B. auch Schalter, die immer auf "Ein" stehen. Wenn ich das Plugin starte, wird der Status richtig angezeigt, aber irgendwann springen die Schalter dann auf "Aus", obwohl sie gar nicht geschaltet wurden. Die CCU2 sendet vermutlich periodisch den Status an das Plugin und dabei kommt es dann zu einem Fehler. Mit älteren Plugin-Versionen funktionierte das einwandfrei.

**Comment by udochrist** [comment]
Ich hab die channel_config.json editiert, den typo ausgebessert und die pbu mit dazugenommen. Beide Typen Rollos werden danach wieder gefunden.

**Comment by DSchumacher2104** [comment]
Und der Status wird auch korrekt angezeigt?

**Comment by udochrist** [comment]
Zumindest stimmen die Status nachdem die Rollos heute von der ccu runtergefahren wurden. Während des Laufs war allerdings kein kreiseln zu sehen.

**Comment by DSchumacher2104** [comment]
Geschlossen ist nach meiner Erfahrung nicht das Problem, sondern geöffnet

**Comment by udochrist** [comment]
Stimmt. das Problem ist geöffnet. funktioniert nicht mit dem plugin.
bin nach node-red/redmatic gewechselt. die homekit anbindung funktioniert bei mir.

**Comment by DSchumacher2104** [comment]
Die Auswertung der von der CCU2 übermittelten Geräte-Stati ist irgendwo grundlegend fehlerhaft!

Wirklich schade, dass Thomas dieses für eine vernünftige Benutzung des Plugins absolut grundlegende Problem, das ja auch nicht nur die Rollos, sondern auch andere Geräte (z. B. Schalter, Garagentor etc.) betrifft, nicht fixen kann :-(( 

Redmatic sieht mir viel zu kompliziert aus!
