### ISSUE TITLE
Unterstützung von Wired IP

### ISSUE THREAD

**Issue by padman74** [thkl/homebridge-homematic#404]

**Comment by padman74** [comment]
Um meine Jalousinen smart zu steuern, wären die neuen Wired IP-Devices perfekt. Werden diese bereits unterstützt oder müsste ich dazu eigene Skripte schreiben?

**Comment by thkl** [comment]
Dazu müsste man sicher eigene Serviceklassen bauen

**Comment by padman74** [comment]
Gibt es deinerseits Ambitionen dies in einer der folgenden Release hinzuzufügen? Wie schwierig siehst du den Aufwand analog zum HmIP-BROLL Serviceklassen für den  HmIPW-DRBL4 bereitzustellen? Trotz It-Kenntnissen wäre der Aufwand für mich allein bestimmt hoch.

**Comment by stefanfejfar** [comment]
DRS8, DRS4 und DRD3 funktionieren problemlos.
Zur Einbindung des DRD3 muss man die Serviceklasse in der Config manuell zuweisen:
`"services": [
                {
                    "type": "HmIPW-DRD3:DIMMER_VIRTUAL_RECEIVER",
                    "service": "HomeMaticHomeKitDimmerService"
                }
            ]`
