### ISSUE TITLE
Türöffner - HM-Sec-Key

### ISSUE THREAD

**Issue by TRehfeldt** [thkl/homebridge-homematic#406]
Hallo, 
vielen Dank für die Entwicklung dieses super Tools! Endlich reagiert HomeKit und Siri schnell und zuverlässig. ;-)
Wäre es möglich den Türöffner HM-Sec-Key zu integrieren. Das Gerät zeigt den Status der Tür an und man kann die Tür öffnen bzw. schließen. Gerne kann ich weitere Infos über das Gerät liefern.
Viele Grüße, Tilmann

**Comment by xxxchris** [comment]
Ist doch bereits integriert.

**Comment by TRehfeldt** [comment]
das wäre ja noch besser. Ich check nochmal meine Config.

**Comment by xxxchris** [comment]
Einfach die Keymatic mit in das Gewerk stecken was du in der Config angegeben und in der CCU angelegt hast.

**Comment by TRehfeldt** [comment]
Ich habe den Fehler gefunden. Da es sich um einen virtuellen HM-Sec-Key welcher über CUxD bereitgestellt wird, handelt musste ich in der CCU Config das CUxD Interface aktivieren. Nun ist das Gerät sichtbar. 
Danke für die schnelle Hilfe.
