### ISSUE TITLE
WTH2 und die Elgato History

### ISSUE THREAD

**Issue by ctschach** [thkl/homebridge-homematic#407]
Nutze mehrere WTH2's und BWTH.

Leider klappt das mit der Elgato History noch nicht so ganz. Zwischendurch wird immer wieder "0.00 °C" in die History geschrieben. So gesehen sieht die Grafik etwas merkwürdig aus.

Gibt es weiterhin die Möglichkeit, die aktuelle Temperatur "groß" darzustellen und nicht als kleine Zahl unter dem "Sollwert"?

![IMG_4970](https://user-images.githubusercontent.com/8994357/55541395-3d63af80-56c5-11e9-9c78-3bcb4a2ffac6.PNG)
![IMG_4971](https://user-images.githubusercontent.com/8994357/55541406-418fcd00-56c5-11e9-98a3-4a6264e49795.PNG)

**Comment by tkoenig** [comment]
@thkl Ich hab das selbe Problem und würde mir das gerne anschauen, bin mir nur nicht sicher ob ich vom `master` oder `develop` branch ausgehen soll. 
Kannst du mir kurz die Unterschiede erklären? 
Sollten beide Branches soweit stabil sein?

**Comment by thkl** [comment]
Ich würde den dev Branch nehmen. Der Master ist viel zu alt.
