### ISSUE TITLE
HMIP-BROLL hängt in Schleife bei Änderung in Home App

### ISSUE THREAD

**Issue by tiirex9** [thkl/homebridge-homematic#409]
Ich hab seit geraumer Zeit das folgende kuriose Problem:

Wenn ich in der Home App (egal ob unter iOS 12.2 oder unter macOS 10.14.4) die Position des Rollladens z. B. von 100% auf 50% ändere und den Finger loslasse, sendet die Homeapp einen Befehl zur Änderung auf 50% (soweit richtig). Sobald sich der Rollladen bewegt und einen Zustand *dazwischen* erreicht, bekommt die Homeapp eine Aktualisierung über die Position und zeigt nicht mehr die von mir angestrebten 50% an, sondern die bisher erreichten (beispielsweise) 90%. Dies wiederum sieht die Homeapp als Anweisung dem Rollladen eben diese 90% als neues Ziel mitzuteilen, der daraufhin (aufgrund der Verzögerung) kurz innehält und wieder nach oben fährt mit 90% als neues Ziel. Das ganze kann dann ne Weile hin und her gehen und manchmal sogar zu einer Endlosschleife führen.

Lediglich, wenn ich den Regler in der Home-App FEST halte bis der Rollladen wieder zum Stillstand gekommen ist, funktinoiert alles wie gehabt. Irgendwie scheint sich hier entweder das Verhalten der Home-App geändert zu haben, oder aber das der Homematic CCU oder sogar des homebridge Plugins. Da beides für sich genommen funktioniert, vermute ich, dass die Schnittstelle das abfangen könnte?

Hat das Problem noch jemand?

**Comment by Stefan774** [comment]
Schließe mich an, bei mir das selbe Problem. Ich denke es liegt an der aktuellen FW von RaspberryMatic /CCU3, da ich zuvor noch nie solche Problemchen gehabt habe.
Wäre mal interessant welche ob es bei jeder HomeMatic Plattform auftritt.
Bei mir ist es RaspberryMatic: 

Aktuelle Firmwareversion: | 3.45.5.20190330
-- | --

**Comment by tiirex9** [comment]
Ich habe [piVCCU](https://github.com/alexreinert/piVCCU/) im Einsatz in der Version 2.41.5-42

**Comment by Stefan774** [comment]
Hi also ich habs mal bei meiner Version gefixt. Ich bin auf der 0.0.109 NPM Version hier sieht die entsprechende Datei noch so aus https://github.com/thkl/homebridge-homematic/blob/f76730bdd87ad3d81e479036d5a2298335e39f38/ChannelServices/HomeMaticHomeKitBlindServiceIP.js

Hier einfach die Zeile 114 auskommentieren und dann den Service neu starten.

 ` if (dp == "3:LEVEL") {
    that.currentPos.updateValue(newValue,null);
    /*that.targetPos.updateValue(newValue,null);*/
  }`

bei der aktuellen Version im Repo wurde das ganze updaten der Values in eine Funktion ausgelagert hier müsste mann dann etwas anders vorgehen. Wenn ich mich nicht recht irre war es in früheren Versionen nicht möglich über den Datenpunkt 3 die TargetPos zu setzen bzw. wurde das von der CCU ignoriert. Das hat sich anscheinend jetzt geändert.

**Comment by tiirex9** [comment]
I tried editing the file in /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js according to your hint, but it does not work for me.
![image](https://user-images.githubusercontent.com/1958744/56854122-008c8080-6932-11e9-9aa5-9a21f76d13a3.png)

**Comment by tiirex9** [comment]
Ahhh, I got it.

I had to comment out both 3:LEVEL **and** 4:LEVEL:

![image](https://user-images.githubusercontent.com/1958744/56854229-79400c80-6933-11e9-88b4-56d3718e7f61.png)

**Comment by rhammeran** [comment]
Ich habe das selbe Verhalten bei HM-LC-Bl1PBU-FM

**Comment by tiirex9** [comment]
@tkoenig Would you mind explaining your changes?

**Comment by tkoenig** [comment]
@tiirex9 in der derzeitigen Implementierung wird die targetPosition gleichzeitig mit der currentPosition gesetzt. 
Dies hat zu dem Sprunghaften verhalten der Rollos (zumindest bei den RF Jalousien die ich habe) in den neuesten iOS Versionen geführt.

In meiner Version (die sich auf den `develop` branch bezieht) setze ich die TargetPosition nur wenn ich sie weiss (bei der Steuerung über HomeKit), ansonsten wird sie auf (0% bzw. 100%, je nach der überlieferten Richtung) gesetzt und nach beendigen auf die currentPosition.

Bei mir funktionieren jetzt damit die Jalousien, es wird jetzt auch der richtige status (Öffnen/Schließen) angezeigt. 
Allerdings habe ich keine HMIP RolloAktoren, daher habe ich die Änderungen dort nicht gemacht.

Im develop branch gibt es (für mich zumindest) jedoch noch andere issues, z.b. gehen bei mir (nur im HomeKit) die Lichter immer an...

**Comment by tiirex9** [comment]
Also mit den eingangs beschriebenen HMIP-BROLL kann ich mich als Tester zur Verfügung stellen. Ich hab nur aktuell keine Zeit mich in den Code reinzufuchsen um selbst Änderungen zu machen.

**Comment by tiirex9** [comment]
Mit iOS 13.1 hab ich keine Probleme mehr mit der aktuellen Version ohne manuelle Anpassung.
