### ISSUE TITLE
Support for HM-ES-PMSw1-Pl ?

### ISSUE THREAD

**Issue by fugazzy** [thkl/homebridge-homematic#418]
Is it possible to use / support HM-ES-PMSw1-Pl ?
It is a powermeter and switch.

**Comment by s0n1c** [comment]
Please reopen!

**Comment by thkl** [comment]
This device should work when you add the Powermeter Channel to HomeKit. The Switch Channel will be mapped automatically...

**Comment by fugazzy** [comment]
OK, thanks, it works. One needs to add channel 2 of the device. The Switch is visible in Home the Powermeter only in other App as eg. Eve
