### ISSUE TITLE
Bitte um Hilfe: Geräte stehen immer auf "Aktualisieren"

### ISSUE THREAD

**Issue by CharlyFive** [thkl/homebridge-homematic#426]
Hallo, ich habe auch alles erfolgreich installiert. Ich habe die Homebridge in der Home App hinzugefügt und alle Geräte wurden gefunden und ich habe alle hinzugefügt. Allerdings steht bei den Geräten zu Anfang immer "Aktualisieren" und dann irgendwann "Keine Antwort"

In der homebridge.log sieht alles gut aus und in der homebridge.err steht nichts drin.

Meine CCU Firewall ist komplett offen und Authentifizierung habe ich auch nicht eingeschaltet. Ich habe die CCU und die Homebridge (Pi) schon rebootet, aber hat nicht geholfen.

Was kann ich noch tun?

**Comment by dkrizic** [comment]
Wie viele Geräte hast Du denn so? Ich habe ca. 80 und es dauert auch mal ein paar Sekunden, bis sich die Geräte aktualisieren. Zeig doch mal das Log von Homebridge, wenn es startet, evtl. kann er eine der Verbindungen nicht aufbauen.

**Comment by jnbt** [comment]
@CharlyFive Ich hatte das gleiche Problem mit der letzten offiziell auf NPM veröffentlichten Version. In #348 wurde das Problem auch schon behandelt.

Es scheint zu Helfen einfach die noch nicht veröffentlichte Version von `HomeMaticRPC.js` zu verwenden: https://github.com/thkl/homebridge-homematic/blob/04b9e25318e9ff93f8ea8e88fbf1e8b54da24076/HomeMaticRPC.js

Kann man z.B. mittels Terminal installieren:

```
$ curl https://raw.githubusercontent.com/thkl/homebridge-homematic/04b9e25318e9ff93f8ea8e88fbf1e8b54da24076/HomeMaticRPC.js > node_modules/homebridge-homematic/HomeMaticRPC.js
```
