### ISSUE TITLE
immer umgekehrt.... -- hat jemand das Plugin "from scratch" installiert ? (see post from 2019-06-07)

### ISSUE THREAD

**Issue by luissimoes** [thkl/homebridge-homematic#427]
Als Anmerkung, schon vorher: ich habe schon das Plug-in de-installiert und re-installiert, alle Plug-Ins de-installiert, HomeBridge de-installiert und re-installiert... alle Packages sind upToDate...

Symptoms: 
Jalousien in HomeKit erscheinen als "Open" und sie sind "Closed" ---> die Status Closed ist auch als Closed in die Homematic App und Web UI korrekt repräsentiert
und
Jalousien in HomeKit erscheinen als "Closed" und sie sind "Open" ---> die Status Open ist auch als Open in die Homematic App und Web UI korrekt repräsentiert

Also "inverted"
ich habe keine Ahnung wo dies liegt.... 

Vielen vielen Dank fuer die Hilfe
Luis

**Comment by luissimoes** [comment]
Eine Bitte....
da sich keiner gemeldet hat - bin ich dann der einziger der das Problem hat? ich hatte aber ähnlich Fragen gesehen (nicht gleich... ) und/aber keine Lösung...  

Die Bitte,
kann jemand bitte hier eine Config zeigen? ich habe die einfache...
		"platform": "HomeMatic",
           	"name": "HomeMatic CCU",
           	"ccu_ip": "<ccu ip address>,
           	"filter_device":[],
           	"filter_channel":[],
           	"outlets":[],
           	"doors":[],
           	"programs":[],
           	"subsection":"Homekit"

**Comment by roe1974** [comment]
Ich verwende ebenfals HM Jalousie Aktoren ... habe dieses Problem nicht ......
Habe für die Jalousien folegnde sin der config.json:

"services" : [{"type" : "HM-LC-Ja1PBU-FM:JALOUSIE","service" : "HomeMaticHomeKitBlindService"}],

hoffe das hilf
lg Richard

**Comment by luissimoes** [comment]
Hallo Richard,
danke!
was muss mann dann in Homematic definieren? eg in die "Blinds" Gewerke den Aktor einfügen?... 

Danke!

**Comment by roe1974** [comment]
Ich habe ein Gewerk ("Homekit") .. da kommt alles rein was in Homekit angezeigt werden soll
die entsprechende zeile dazu in der config ist:

"subsection" : "Homekit",

**Comment by roe1974** [comment]
welchen aktor hast du genau ?

**Comment by luissimoes** [comment]
ok - sorry fuer die Fragen (und nochmal vielen vielen dank fuer deine Hilfe!) - aber wie genau dann geht dies?
eg ich muss dann HomeMaticHomeKitDummyService.js kopieren und dann anpassen??... mein Aktor Typ ist (laut Homematic) HM-LC-Bl1PBU-FM... ist dies was ich in die Config kopieren soll?

Ich habe ein Aktor (nicht IP) - unterputz.

**Comment by roe1974** [comment]
Den HM-LC-Bl1PBU-FM müsste er automatisch erkennen ...... nur mein Jalousie aktor ist ein Sonderfall....Da Bausatz von ELV

**Comment by luissimoes** [comment]
yep... das wird erkannt... aber das Status im HomeKit ist umgekehrt

Die Jalousie ist offen (das Homematic zeigt auch offen, genau so wie die OS App) aber HomeKit zeigt *CLOSED* und dann umgehkehrt
Also deutlich ein Problem im Homebridge Plugin.. (aus meiner Sicht...)

**Comment by roe1974** [comment]
ich verwende noch eine alte "HomeMaticHomeKitBlindService.js"

Versuch mal diese:

'use strict';

var HomeKitGenericService = require('./HomeKitGenericService.js').HomeKitGenericService;
var util = require("util");


function HomeMaticHomeKitBlindService(log,platform, id ,name, type ,adress,special, cfg, Service, Characteristic) {
    HomeMaticHomeKitBlindService.super_.apply(this, arguments);
}

util.inherits(HomeMaticHomeKitBlindService, HomeKitGenericService);


HomeMaticHomeKitBlindService.prototype.createDeviceService = function(Service, Characteristic) {

    var that = this;
    var blind = new Service["WindowCovering"](this.name);
    this.services.push(blind);

    var cpos = blind.getCharacteristic(Characteristic.CurrentPosition)

    .on('get', function(callback) {
      that.query("LEVEL",function(value){
       if (callback) callback(null,value);
      });
    }.bind(this));

    this.currentStateCharacteristic["LEVEL"] = cpos;
    cpos.eventEnabled = true;


    var tpos = blind.getCharacteristic(Characteristic.TargetPosition)

    .on('get', function(callback) {
        if (that.state["LEVEL"] != undefined ) {
                callback(null,that.state["LEVEL"]);
        } else {
                that.query("LEVEL",function(value){
                        if (callback) {
                                callback(null,value);
                        }
                });
        }
    }.bind(this))

    .on('set', function(value, callback) {
      that.delayed("set", "LEVEL", value, 750);
      callback();
    }.bind(this));

    var pstate = blind.getCharacteristic(Characteristic.PositionState)

        .on('get', function(callback) {
      that.query("DIRECTION",function(value){
       if (callback) {
          if (value!=undefined) {
            callback(null,value);
          } else {
            callback(null,"0");
          }

       }
      });
    }.bind(this));

    this.currentStateCharacteristic["DIRECTION"] = pstate;
    pstate.eventEnabled = true;

    this.addValueMapping("DIRECTION",0,2);
    this.addValueMapping("DIRECTION",1,1);
    this.addValueMapping("DIRECTION",2,0);
    this.addValueMapping("DIRECTION",3,2);

    this.remoteGetValue("LEVEL");
    this.remoteGetValue("DIRECTION");



}

HomeMaticHomeKitBlindService.prototype.endWorking=function()  {
 this.remoteGetValue("LEVEL");
}


module.exports = HomeMaticHomeKitBlindService;

**Comment by luissimoes** [comment]
ok!!! 
dh dies .js soll ich dann wohin in mein Raspberry kopieren?.... sorry für die Frage.... aber kenne mich nicht genug damit um

**Comment by roe1974** [comment]
es exisitiert bereits ein HomeMaticHomeKitBlindService.js ........
diese kannst am besten direkt am raspi editieren ... 
sollte liegen im verzeichnis:

/usr/lib/node_modules/homebridge-homematic/ChannelServices

**Comment by luissimoes** [comment]
Vielen Dank! ich bin gerade unterwegs und mache dann wenn ich zu Hause bin... 

VIELEN DANK!

**Comment by luissimoes** [comment]
Hi, habe probiert.... hier ist das Status (für andere auch.... ich weiss dass dieses Problem nicht nur bei mir ist....)

Mit der JS oben hat leider nicht funcktioniert... immer noch status umgekehrt (zeigt closed wann open, und anders rum)

Habe dann die .js file genommen die im **Branch MASTER** ist.... 

dann scheint besser aus i.e. es zeigt schon open... aber immer im Status "Opening....".....

Also... dies hat definitiv mit der .JS file zu tun.... 

hat jemand eine Idee wo im File das Problem ist?

Cheers

**Comment by luissimoes** [comment]
Here an Update - vielleicht zeigt dies wo das Prob ist?
In Homekit wie gesagt zeigt immer auf "Opening"...
in EVE APP ist das Status sehr komisch....: Die Position ist 0%.... (also ZU) aber der Zahl zwischen den Pfeilen zeigt 100%.... also "Open"....

**Comment by roe1974** [comment]
welche nodejs version ?

**Comment by luissimoes** [comment]
v10.15.3

**Comment by roe1974** [comment]
ok ....  nur um sicher zu sein .... wenn die rollo oben ist (also offen) zeigt er in HM in der WebUI 100% ... richtig ?

**Comment by luissimoes** [comment]
korrekt

**Comment by luissimoes** [comment]
and now as update... the Homebridge-Homekit shows ALWAYS.. ALWAYS "Opening"./// egal ob die Jalousie zu oder auf ist////

**Comment by roe1974** [comment]
seltsam .......

**Comment by luissimoes** [comment]
Ich habe jetzt: Homematic uminstalliert, alles gelöscht und neu installiert... und immer noch das Ergebnis ist falsch.... obwohl die APP und das WebUI korrekt anzeigen... also das Problem ist definitiv in dem Plugin...

Hat jemand dies alles vom "Scratch" installiert? eg um sicher zu sein dass alle Files in dem Build sind tatsächlich die die angesprochen sind?

Ich verstehe nicht wie ich der einzige bin der dieses Problem hat... :-(... die Config ist simple, und ich habe jetzt ALLES rausgeschmissen ausser Homematic und Rademacher... 

Vielen Dank!!!!

**Comment by luissimoes** [comment]
Ich habe jetzt ein 2. PI und Homebridge installiert... 
als Plugins habe nur Homematic, Rademacher und Homebridge UI
Ergebnis: Status is IMMER „CLOSED“ .... 

Ich habe gesehen dass eine Lösung gibt? Thread „Fix status for blinds #415“.... 

Welche files soll ich kopieren um die Lösung zu haben?
