### ISSUE TITLE
Faucet - Problem 

### ISSUE THREAD

**Issue by pat4020** [thkl/homebridge-homematic#428]
Hallo.

Ich schaffe es einfach nicht, dass ein HM-LC-Sw2-FM Kanal als "faucet" ausgegeben wird.
Wäre eventuell jemand bereit eine gesamte config.json zu posten ... ich habe den Eintrag aus [#268](https://github.com/thkl/homebridge-homematic/issues/268 ) schon an diversten Stellen in der config versucht, jedoch wird das Gerät immer als Sprinkler ausgegeben.

Vielen Dank!

**Comment by roe1974** [comment]
Schliesse mich der Frage an:

Kann das so stimmen ?

"valves":["BidCos-RF.OEQ0123456:1"],
"HM-LC-Sw2-FM:SWITCH":{"types":{"BidCos-RF.OEQ0123456:1":0}},

und wir beim "generic_Valve" auch ein timer angezeigt ?

DANKE !

lg RIchard

**Comment by iuliusmaximilian** [comment]
Vielleicht helfen Euch zwei Beispiele aus meiner Config:

["valves": ["BidCos-RF.OEQ0123456:4","BidCos-Wired.OEQ0123456:4"],

"services": [
                "HMW-IO-12-Sw14-DR:DIGITAL_OUTPUT": {
                        "types": { "BidCos-Wired.OEQ0123456:4": 3 }
                },
                "HM-LC-Sw4-DR-2:SWITCH": {
                        "types": { "BidCos-RF.OEQ0123456:4": 3 }
                }
],](url)

**Comment by roe1974** [comment]
ok DANKE !!! :-) ..... und wird beim generic valve ein timer angezeigt ?

lg Richard

**Comment by pat4020** [comment]
@iuliusmaximilian vielen Dank für dein Beispiel. Leider bekomme ich bereits bei der Validierung einen Fehler in der Zeile ""HMW-IO-12-Sw14-DR:DIGITAL_OUTPUT": {" ....

**Comment by pat4020** [comment]
@roe1974, hast du das Problem schon lösen können?

**Comment by roe1974** [comment]
nein leider ....

**Comment by thkl** [comment]
in obigem Fall muss in der config.json in die homematic section folgender Eintrag nach der generellen Valve Section : 

```
{"HM-LC-Sw2-FM:SWITCH": 
                        {"types": [
                                        { "BidCos-RF.SERIENNUMMER:KANAL": 3 },
                                        { "BidCos-RF.SERIENNUMMER2:KANAL": 3 }
                                     ]
 }             
}
```

Die Valve Klasse sucht bei der Erstellung des HomeKit Gerätes nach der Definition für das übergebene Homematic Gerät daher zuerst

HM-LC-Sw2-FM:SWITCH


und dann werden die HK Gerätetypen für die jeweiligen Homematic Geräte festgelegt:

  // Characteristic.ValveType.GENERIC_VALVE = 0;
  // Characteristic.ValveType.IRRIGATION = 1;
  // Characteristic.ValveType.SHOWER_HEAD = 2;
  // Characteristic.ValveType.WATER_FAUCET = 3;

**Comment by thkl** [comment]
Nachtrag: Vielleicht sollte ich das irgendwie bissel einfacher machen, ich hab nur noch keine rechte Idee

**Comment by roe1974** [comment]
@thkl 
Ich habs immer noch nicht wir die config.json aussehen muss .....
Kannst Du bite hier mal ein komplettes Beispiel posten ?

lg Richard

**Comment by thkl** [comment]
Btw: die nächste Version wird ein WebUi für die Konfig haben. Damit sollten die wilden Settingsfiles der Vergangenheit angehören

**Comment by roe1974** [comment]
sehr cool !!!!

**Comment by thkl** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/884355/75180688-03682580-573d-11ea-9e7d-0fccf4549f72.png">
Ja, es fehlen noch die Konfigurationsmöglichkeiten für die "zusammengesetzten" Dienste Wie VideoDoorBell und Garagentoor .. und dann kann ich mal eine Beta Version rauslassen
