### ISSUE TITLE
Schaltaktor als switch darstellen und nicht als outlet...?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#429]
Kann man irgendwie HM Schaltaktoren statt als "outlet" auch als "schalter" darstellen lassen ?
Also das icon analog wie es bei variablen angezeigt wird ?

lg Richard

**Comment by iuliusmaximilian** [comment]
Worksround ist auf jeden Fall eine Hilfsvariable mit einem Mini-Programm.

**Comment by roe1974** [comment]
auch eine idee ;-)

Andere Frage:

Du hast in #220 gepostet deine config für faucet/valve:
wie sieht die genau aus ? 

Kann das so stimmen ?

"valves":["BidCos-RF.OEQ0123456:1"],
"HM-LC-Sw2-FM:SWITCH":{"types":{"BidCos-RF.OEQ0123456:1":0}},

und wir beim "generic_Valve" auch ein timer angezeigt ?

DANKE !

lg RIchard

**Comment by pat4020** [comment]
Hallo!

Der Frage schließe ich mich an, habe bereits ein eigenes Thema diesbezüglich erstellt. 

Danke!

**Comment by iuliusmaximilian** [comment]
Mit den Hilfsvariablen geht das ganz gut, schöner Nebeneffekt, man kann selbst im Programm bestimmen wann der Schalter wieder zurück gesetzt wird. Bspw. Nutze ich das für Raffstore Programmen mit Kippstellungen die auch gut mal ne Minute laufen können, in der Zeit ist der Schalter dann an und wenn fertig aus.

**Comment by thkl** [comment]
siehe https://github.com/thkl/homebridge-homematic/issues/450#issuecomment-522340425 ... da ist etwas Arbeit an der Switchklasse nötig ... ich schau mal wie ich das anständig implementiert bekomme ...

**Comment by roe1974** [comment]
ich hätte das aber gerne direkt für Hm Geräte zb. HM-LC-Sw2-FM
;-) 
lg Richard

**Comment by thkl** [comment]
Am liebsten wäre mir natürlich, wenn ich das irgendwie aus der CCU lesen könnte. Das sind dann weniger Einstellungen in irgendwelchen configs ...

**Comment by roe1974** [comment]
am besten über gewerke .... 
valve_0, valve_1, valve_2, valve_3, outlet, switch, etc.
würde das nicht gehen ?

**Comment by thkl** [comment]
also quasi:

CCU Gewerk : 
Homekit_Valve_1 .... alle HM-LC-SwXXXX für Valve Typ 1 drin 
Homekit_Switch .... alle HM-LC-SwXXXX für Switch drin
Homekit_Outlet .....
Homekit_Light ....

**Comment by roe1974** [comment]
ja zB .....
oder per namen der geräte ... das wird aber nicht jedem gefallen wenn geräte nach einer struktur in der CCU benannt sind ....

**Comment by thkl** [comment]
naja ich muss ja irgendwas festes auf der Seite der homebridge haben

**Comment by roe1974** [comment]
dann gewerke .....
sollte aber parallel zur konfiguration in der config.json sein ... also dass beides möglich ist ...
config.json für erfahrene und der weg über gewerke für einsteiger .... der käme dann mit einer minimal config.json aus ... und die restlichen parameter wie ios10=true und ähnliches könnte man über systemvariablen auslesen ?

**Comment by thkl** [comment]
Hmm ne doppelt ist Mist. Wenn ich dann zwei verschiedene Sachen bekomme (Gewerk != Config) was zählt dann ?    Ich glaub ich bleib bei der Config.json

**Comment by roe1974** [comment]
@thkl  .... ja den issue gibt es schon :-)
lg Richard

**Comment by thkl** [comment]
Ok , ich hab mal nachgeschaut es gibt folgende HK Geräte wo ein SwitchAktor Sinn macht: Lightbulb , Outlet , Switch , Fan ... 

Das wird dann wieder in der config einstellbar sein:

```
{
  "name" : "TestSwitch",
  "type" : "HM-SPECIAL-SWITCH",
     "parameter" : {
     "channel":"BidCos-RF.THKL000001:1",
     "switchtype":"Fan"
  }
}
```

**Comment by roe1974** [comment]
klingt perfekt :)
hinweis : habe zwei aktoren derzeit als „outlet“ ... werden aber korrekterweise , warum auch immer , als Fan angezeigt ... vielleicht weil sie „Ventilator“ in HK benannt sind ?

**Comment by thkl** [comment]
so siehe : https://github.com/thkl/homebridge-homematic/wiki/Flexiblere-Switch-Aktor-Darstellung

**Comment by roe1974** [comment]
TOP! funktioniert !!!!

**Comment by ballchemist** [comment]
Noch mal kurz geöffnet um hier auch abzugreifen wo mein Fehler liegt, bzw. Was genau wird beim CHANNEL Konfiguriert @roe1974 @thkl ?

Mein JSON Snipped sieht wie folgt aus, integriert die Taste auch - aber funktionieren tut es nicht... 

`  "special": [
        {
            "name": "Lüfter Wohnzimmer",
            "type": "HM-SPECIAL-SWITCH",
            "parameter": {
                "channel": "BidCos-RF.THKL000001:1",
                "switchtype": "Fan"
            }
        }
    ]`
