### ISSUE TITLE
Flickering lights when set a dimmer value via "Apple Home"

### ISSUE THREAD

**Issue by dennydeutscher** [thkl/homebridge-homematic#43]
When I set a dimmer with the build in iOS 10 Home-App other than 100% or 0% the corresponding light starts to jump to maximum (100 %) until its reach the desired value.

**Comment by thkl** [comment]
this will also be fixed in 0.0.44

**Comment by dennydeutscher** [comment]
Both works great now! THX!

**Comment by thoduh** [comment]
Wenn ich Siri sage, sie soll das Licht einschalten, schaltet sie es nicht ein, sagt aber "Licht ist eingeschaltet".
Wenn ich sage stell das Licht auf 100% funktioniert es?

**Comment by dennydeutscher** [comment]
Stimmt, hab es eben probiert…

- „Schalte das Licht auf $Wert%“ funktioniert zum einschalten
- „Schalte das Licht aus“ ebenfalls
- „Schalte das Licht ein“ nicht, jedoch mit positiver Bestätigung

Wäre mir gar nicht aufgefallen, weil ich bei mir immer nur Programme 
der Homematic trigger.

Sinnvoll wäre ja dann eigentlich „EIN = Letzter Dimmwert“ 

Viele Grüße, Denny



 

Von: thoduh [mailto:notifications@github.com] 
Gesendet: Donnerstag, 13. Oktober 2016 17:37
An: thkl/homebridge-homematic
Cc: dennydeutscher; State change
Betreff: Re: [thkl/homebridge-homematic] Flickering lights when set a dimmer value via "Apple Home" (#43)

 

Wenn ich Siri sage, sie soll das Licht einschalten, schaltet sie es nicht ein, sagt aber "Licht ist eingeschaltet".
Wenn ich sage stell das Licht auf 100% funktioniert es?

**Comment by thkl** [comment]
Ist ab nächster Version so. Da merkt sich die Bridge den letzten Wert. Wenn der unbekannt ist dann halt 100%
