### ISSUE TITLE
HmIP-SWDO als MOTIONDETECTOR

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#431]
Gib es eine Möglichkeit einen HmIP-SWDO Fensterkontakt in HomeKit als MOTIONDETECTOR zu Mappen. Hintergrund ist, dass ich bei einer Erkennung eine Push mit Screenshot einer Kamera bekommen möchte, was bei den PIRs super funktioniert.

**Comment by thkl** [comment]
out of the box und ohne einen eigenen Service dafür zu bauen geht das nicht

**Comment by iuliusmaximilian** [comment]
.
