### ISSUE TITLE
iOS 13

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#433]
Hat schon Jemand die Kompatibilität zu  iOS 13 getestet ? Frage mich, ob dies funktioniert und welchen Effekt die neue Gruppierung von Devices in Home hat...

**Comment by thkl** [comment]
Es sollte eigentlich keine großen Probleme geben, da die meisten Geräte (Bis auf die Elgato History Funktion) auf offiziellen Homekit Geräten basieren.

**Comment by backfisch88** [comment]
Klappt. Hab es bei den Homematic Geräten nur bei der Video Klingel festgestellt 

<a href="https://ibb.co/6ZwwKVb"><img src="https://i.ibb.co/6ZwwKVb/082-DF9-CA-0749-4816-9836-11-C3737-FF14-D.png" alt="082-DF9-CA-0749-4816-9836-11-C3737-FF14-D" border="0"></a> <a href="https://ibb.co/fpfMbH1"><img src="https://i.ibb.co/fpfMbH1/4204-AF24-88-CC-4537-8-E5-A-E43505-F24781.png" alt="4204-AF24-88-CC-4537-8-E5-A-E43505-F24781" border="0"></a>

**Comment by iuliusmaximilian** [comment]
Fine das eher unpraktisch, den Türöffner der  VideoDoorBell habe ich mir jetzt zusätzlich nochmal als KeyMatic rein geholt um ihn wieder in Home direkt zu haben. Die neue Gruppierung ist ggf. nett, aber warum man sie in Home nicht jeweils deaktivieren kann mach sich mir nicht klar.

**Comment by backfisch88** [comment]
Ne das ist ok. Was ich bescheuert finde, dass man nicht selber gruppieren kann was man will und was nicht. Habe jetzt in meiner Haustür (seit neuestem Update) da irgendwelche Lampen und Schalter mit drin, die weder ähnlich heißen, noch irgendwie anders mit verknüpft sein könnten

**Comment by iuliusmaximilian** [comment]
Weiter musste ich feststellen, dass die HomeKit Logik, dass wenn ein Bewegungssensor im gleichen Raum ist wie eine Kamera, nicht mehr wie in iOS 12 Rich Notifications mit Snapshot der Kamera versendet werden. Das ist zwar keine Homematic-Homebridge Sache, aber ich will es hier trotzdem der Vollständigkeit halber mal erwähnen.

https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/332

**Comment by iuliusmaximilian** [comment]
Funktioniert!
