### ISSUE TITLE
HM-LC-Sw2PBU-FM - falscher Status

### ISSUE THREAD

**Issue by rhammeran** [thkl/homebridge-homematic#436]
Der HM-LC-Sw2PBU-FM ist ein Lichtschalter mit zwei Kanälen. Wenn man den Raum in der HomeApp beobachtet und dabei direkt am Schalter eine Aktion durchführt, wird das in der App korrekt angezeigt. Verlässt man dann die App kurz und geht wieder rain, wird der Status aktualisiert und es wird für BEIDE (!) Kanäle der Status der letzten Schaltaktion angezeigt. Also beide AN oder beide AUS – obwohl in Realität ein Kanal AN, der andere AUS ist.

**Comment by neges** [comment]
Ich bekomme den Lichtschalter garnicht über homebridge in der home App angezeigt. Gibt es da noch was zu beachten? Meine rolladenaktoren sind alle da.

**Comment by rhammeran** [comment]
Keine Ahnung mit welchem Update das gefixed wurde, aber inzwischen funktioniert es korrekt.

@neges: ich habe nicht besonderes gemacht - nur die beiden Kanäle des Schaltersn dem Gewerk "Homekit" zugewiesen.
