### ISSUE TITLE
HmIP FROLL kein % einstellbar

### ISSUE THREAD

**Issue by mainkowitsch** [thkl/homebridge-homematic#441]
Ich habe eine pivccu3 mit der Firmware 3.45.7, Bidcos-RF Geräte (u.a. Blinds) UND Hm-IP Froll’s im Einsatz.
Mit der Änderung in der HomeMaticRPC.js sehe ich wenigstens geschlossen oder geöffnet bei allen Geräten.
Bei % änderungen fahren die bidcos-rf auf, zu, auf, zu und das immer nur ein paar %... die HmIP aktoren fahren die gewünschte stelle an und fahren dann direkt wieder zu bzw auf...

Mal ein Auszug aus dem Debug... die ganzen Errors finde ich merkwürdig...
Jul 03 00:00:57 raspberrypi homebridge[1991]: [2019-7-3 12:00:57 AM] [HomeMatic CCU3] RPC getValue (hexazeugs:4 LEVEL) Response undefined Errors: Error: XML-RPC fault: Unknown Parameter value for value key: LEVEL
Jul 03 00:00:57 raspberrypi homebridge[1991]: [2019-7-3 12:00:57 AM] [HomeMatic CCU3] RPC getValue (hexazeugs:4 LEVEL) Response undefined Errors: Error: XML-RPC fault: Unknown Parameter value for value key: LEVEL
Jul 03 00:00:57 raspberrypi homebridge[1991]: [2019-7-3 12:00:57 AM] [HomeMatic CCU3] RPC getValue (hexazeugs:4 LEVEL) Response undefined Errors: Error: XML-RPC fault: Unknown Parameter value for value key: LEVEL

die beta (0.1.2) zu installieren bringt auch nichts... schon versucht.

Muss ich evtl. doch auch die Ports auf die gleichen wie in der Interfaces cfg umändern. Hab da mal reingeguckt und die stehen bei Bidcos-rf auf 32001, Virtual devices auf 32929 und bei HmIP auf 32010... also IN der piVCCU3. XML-Rpc steht auf vollzugriff

**Comment by gsiscotty** [comment]
hat sich hier was getan?

**Comment by mainkowitsch** [comment]
ja % sind einstellbar. Aber hab nen anderes problem. ^^
