### ISSUE TITLE
Best practise update CCU3 3.37.8 auf 3.4.x mit von 1.0.9

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#446]
Wie ist denn das Vorgehen für ein Update der CCU3 auf 3.37.8 auf neuste 3.4.x. ausgehend von der  1.0.9 master / NPM ?

**Comment by iuliusmaximilian** [comment]
zur Info, ich bin jetzt wieder zurück auf der NPM 1.0.9 und alles funktioniert wieder korrekt

**Comment by thkl** [comment]
/o\ ... ich hab ewig kein npm neu gebaut ... den dev branch hier runterladen und die Files überschreiben sollte die beste Lösung sein ...

**Comment by iuliusmaximilian** [comment]
@thkl Die 1.0.9 NPM läuft bei mir sehr sehr stabil mit 8 Bridges und mehr als 140 Geräten, von IP bis Wired über virtuelle Devices. Habe die Dev. hier die letzten Tage probiert, allerdings lief danach vieles überhaupt nicht mehr rund, u.a. siehe:

https://github.com/thkl/homebridge-homematic/issues/445
https://github.com/thkl/homebridge-homematic/issues/444
