### ISSUE TITLE
HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe !

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#447]
@thkl 
Ich verwende noch eine ältere Version der "HomeMaticHomeKitSecuritySystem.js" da die besser funktioniert und "ruhig" ist ... dh. es kommen nicht permanent meldung "Alarm aktiviert" obwohl er schon seit Stunden aktiviert ist und sich nichts verändert hat. Die aktuelle Version zeigt beim aktivieren von "abwesend" zwischendurch "Nacht wird aktiviert" ... dann gleich "Abwesend wird aktiviert" ... also irgendwas stimmt mit der auch nicht ...... 
Die Alte Version hat nur das Problem, dass "Nacht/Abwesend" vertauscht ist mit der Alarmsirene in der HM. Habe es versucht zu ändern, aber dann kommen auch diese permanenten Meldungen zwischendurch "Alarm aktiviert" .... 
Kannst Du mir diese altre Version, NATÜRLICH GEGEN BEZAHLUNG, anpassen ?

lg Richard

[HomeMaticHomeKitSecuritySystem.zip](https://github.com/thkl/homebridge-homematic/files/3511779/HomeMaticHomeKitSecuritySystem.zip)

**Comment by thkl** [comment]
Bitte mal das hier probieren
[HomeMaticHomeKitSecuritySystem.js.zip](https://github.com/thkl/homebridge-homematic/files/3512121/HomeMaticHomeKitSecuritySystem.js.zip)

**Comment by roe1974** [comment]
also Nacht/Abwesend schaltet mal richtig ... ob es zwischendurch aufpoppt muss ich testen
ABER: jetzt ist Zuhause/Aus vertauscht ?!?!?!
Also:
Zuhasue in Homekit ist jetzt "Alarm blockiert" in HM .... statt "Alarm Aus"
Aus in Homekit ist jetzt "Alarm Aus" in HM ... statt "Alarm blockiert"

Kannst Du das noch ändern ?

lg Richard

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 16:55
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


Bitte mal das hier probieren
HomeMaticHomeKitSecuritySystem.js.zip<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthkl%2Fhomebridge-homematic%2Ffiles%2F3512121%2FHomeMaticHomeKitSecuritySystem.js.zip&data=02%7C01%7C%7C951693704a274ecf99ac08d72322f3cd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637016505326044827&sdata=XJAuIlBCxG3SU07d9XnSa4pFxXt52zGCqneWg6Mv9oI%3D&reserved=0>

**Comment by thkl** [comment]
Aber zu Hause soll doch kein Alarm kommen ?

**Comment by roe1974** [comment]
doch ... zuhause heisst in hm "Alarm aus" ... damit kann zB ein verknüpfter schalter mit dem Panik Kanal noch auslösen.
Aus ... bedeutet blockiert, dann lässt sich die sirene nicht mehr auslösen .....

DH.
"Aus" in Homekit muss "Alarm blockiert" in HM sein
"Zuhause" in Homekit muss "Alarm aus" in HM sein

lg Richard


________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 17:12
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


Aber zu Hause soll doch kein Alarm kommen ?

**Comment by roe1974** [comment]
PS: Kann ich ein neues .js file von dir irgendwie anders initialisieren ausser homebridge jedesmal neu starten ?

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 17:12
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


Aber zu Hause soll doch kein Alarm kommen ?

**Comment by roe1974** [comment]
also STAY_ARM und DISARMED gehört vertauscht ... so wie es in der ursprünglichen version war ... ;_)

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 17:12
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


Aber zu Hause soll doch kein Alarm kommen ?

**Comment by thkl** [comment]
Alles klar 
[HomeMaticHomeKitSecuritySystem.js.zip](https://github.com/thkl/homebridge-homematic/files/3512154/HomeMaticHomeKitSecuritySystem.js.zip)


PS Nein man kann das nicht on the fly reloaden ..

**Comment by roe1974** [comment]
sieht gut aus !!!!!!
teste noch ob es nachdem es aktiviert wurde "unmotiviert" meldungen abgibt in Homekit 😉

Spende kommt .... wohin ? sagst mir bitte nochmal deinen PayPal account ?

PS: wieso treibt jeder restart der Hombridge (habe eigen instanz nur mit deinem plugin) den DC um 20% in die höhe ?
bei 2 restarts plötlizh bei 35% .... sonst bei 3 %

lg Richard

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 17:27
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


Alles klar
HomeMaticHomeKitSecuritySystem.js.zip<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthkl%2Fhomebridge-homematic%2Ffiles%2F3512154%2FHomeMaticHomeKitSecuritySystem.js.zip&data=02%7C01%7C%7C7829bdaf54ac4e1b779a08d723276d32%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637016524542407510&sdata=o4VNLT%2FQCFPPM%2BhtbX7JNYzajpgpY0VIM9bDKF1%2BmxQ%3D&reserved=0>

PS Nein man kann das nicht on the fly reloaden ..

**Comment by thkl** [comment]
PP klebt auf der Startseite oben ..

Beim Restart fragt Homekit halt alle Zustände neu ab ... und ich muss die ja von der CCU holen ... 
Könnte man mal von der Abfrage des Interfaces auf Rega umstellen.....

**Comment by roe1974** [comment]
PP kommt ....
ja umstelung auf Rega wär geil .... machst du noch weiter an dem projekt ??

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 17:36
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


PP klebt auf der Startseite oben ..

Beim Restart fragt Homekit halt alle Zustände neu ab ... und ich muss die ja von der CCU holen ...
Könnte man mal von der Abfrage des Interfaces auf Rega umstellen.....

**Comment by thkl** [comment]
> machst du noch weiter an dem projekt ??

sporadisch ....

**Comment by roe1974** [comment]
spende ist raus

wäre schade !!!! ... möchte nicht auf redmatic wechslen müssen 🙁

lg Richard

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 17:40
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


machst du noch weiter an dem projekt ??

sporadisch ....

**Comment by thkl** [comment]
> spende ist raus wäre schade !!!! 

vielen Dank

> ... möchte nicht auf redmatic wechslen müssen 🙁 

:o) ... man müsste mal die wichtigsten ToDos zusammenstellen ...

**Comment by roe1974** [comment]
also ganz ehrlich für mich funktioniert es perfekt !!!
Habe aber nur HM classic ....

Das einzige wäre die Umstellung auf Rega 😉

lg Richard

**Comment by thkl** [comment]
wirf mal bitte deine index.js aus dem homematic ordner hier rein. ich glaub, ich hab in meine schon zu viel rumgebaut ;o)

**Comment by roe1974** [comment]
et voila
lg Richard

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 17:58
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


wirf mal bitte deine index.js aus dem homematic ordner hier rein. ich glaub, ich hab in meine schon zu viel rumgebaut ;o)

**Comment by roe1974** [comment]
als zip 😉

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 17:58
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


wirf mal bitte deine index.js aus dem homematic ordner hier rein. ich glaub, ich hab in meine schon zu viel rumgebaut ;o)

**Comment by thkl** [comment]
ähm ? hier is nix

**Comment by roe1974** [comment]
hat er blockiert
kommt als zip 😉

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 18:08
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


ähm ? hier is nix

**Comment by thkl** [comment]
weder noch ..

**Comment by roe1974** [comment]
nochmal als 7zip


________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 18:13
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


weder noch ..

**Comment by thkl** [comment]
nope ... ggf mal per Web anhängen

**Comment by roe1974** [comment]
https://github.com/thkl/homebridge-homematic/issues/448

________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 18:15
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


nope ... ggf mal per Web anhängen

**Comment by roe1974** [comment]
noch eine frage

ich habe an einem HM-LC-Sw2-FM eine Pumpe und ein elektrisches Ventil hängen

Das Ventil würde ich gerne vom Symbol her als "Valve" darstellen im homekit. Brauche aber den Timer nicht....

Könnte man da eine eigene "HomeMaticHomeKitSwitchService.js" die das so darstellt, und ich weise den 2. Kanal dem zu ?

Gegen Spende natürlich 😉

lg Richard


________________________________
Von: Thomas Kluge <notifications@github.com>
Gesendet: Samstag, 17. August 2019 18:13
An: thkl/homebridge-homematic <homebridge-homematic@noreply.github.com>
Cc: Richard <roe@live.at>; Author <author@noreply.github.com>
Betreff: Re: [thkl/homebridge-homematic] HomeMaticHomeKitSecuritySystem.js ..... Status Nacht/Abwesend ... Bitte Hilfe ! (#447)


weder noch ..

**Comment by thkl** [comment]
muss ich ein Servicefile für bauen ...

**Comment by thkl** [comment]
> noch eine frage ich habe an einem HM-LC-Sw2-FM eine Pumpe und ein elektrisches Ventil hängen Das Ventil würde ich gerne vom Symbol her als "Valve" darstellen im homekit. 

--> https://github.com/thkl/homebridge-homematic/issues/450

**Comment by roe1974** [comment]
@thkl ... diese version funktioniert perfekt .... richtiger Status .. bis jetzt keine Zwischenmeldungen von Homekit ;-)

**Comment by thkl** [comment]
Ok meine Testversion hat einmal rumgetrötet, laut Log hat die CCU aber da den Status gesendet. Warum auch immer. Ich werde mal noch was einbauen, was HK bei Events nur Bescheid sagt, wenn der Status wirklich neu ist.

**Comment by roe1974** [comment]
@thkl .... habe seitdem ich die sirene in HK aktviere das problem, dass bei abwesend/Nacht der status zwar schaltet, schliesse ich aber die Home App und öffne sie erneut steht dort "aktivieren...." ... kannst Du mir hier helfen .. gegen eine Spende natürlich ;-)

**Comment by roe1974** [comment]
PS: Aktiviere ich dden Status über homematic, dann steht der richtig in HK ohne "aktivieren......"
