### ISSUE TITLE
index.js ..... zur Ansicht

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#448]
lg Richard
[index.zip](https://github.com/thkl/homebridge-homematic/files/3512187/index.zip)

**Comment by thkl** [comment]
die alte index.js mal nicht wegwerfen ;)

[index.js.zip](https://github.com/thkl/homebridge-homematic/files/3512194/index.js.zip)

**Comment by roe1974** [comment]
sieht gut aus ..... was ist jetzt genau anders ....
kommt mir schneller vor ? kann das sein ?
DC steigt trotzdem beim reboot der homebridge....

**Comment by thkl** [comment]
Alle getValue und setValue werden über Rega geroutet. Allerdings rufe ich da object.State() auf ... müsste auf object.Value() geändert werden:

HomeMaticRegaRequest.js

Zeile 62:

`  getValue: function (channel, datapoint, callback) {
    var script = 'var d = dom.GetObject("' + channel + '.' + datapoint + '");if (d){Write(d.State());}'
    this.script(script, function (data) {
      if (data !== undefined) {
        callback(data)
      }
    })
  },
`

muss zu 

`
  getValue: function (channel, datapoint, callback) {
    var script = 'var d = dom.GetObject("' + channel + '.' + datapoint + '");if (d){Write(d.Value());}'
    this.script(script, function (data) {
      if (data !== undefined) {
        callback(data)
      }
    })
  },
`

**Comment by roe1974** [comment]
ok das soll ich ändern ????
es geht aber alles ??!!

**Comment by roe1974** [comment]
Aber Value() schreibt ja dann im gegensatz zu State() in die REGA ohne das sie es mitbekommt ... so gewollt ?

**Comment by thkl** [comment]
Value nimmt den letzten Zustand den Rega kennt, fragt also nicht das Interface ab.
State fragt den Wert direkt vom Interface ab. Dabei wird halt das Gerät angefragt und der DC steigt.

**Comment by roe1974** [comment]
ok habe ich geändert....

**Comment by roe1974** [comment]
läuft :-) ..... hast du noch das letzt post im #447 gelesen ?

**Comment by roe1974** [comment]
warum bist nicht von anfang an über die rega gegangen ?

**Comment by roe1974** [comment]
habe jetzt das im log ... durch die änderung ?

omematic-raspi user.info kernel: [1944280.433101] TCP: request_sock_TCP: Possible SYN flooding on port 8183. Sending cookies.  Check SNMP counters.

**Comment by thkl** [comment]
tja das ist halt das Problem wenn die Homebridge startet dann holt er alle Werte auf einmal ab.
Dann schlagen halt bei vielen Geräten ne Menge http Requests auf einmal auf Rega ein.

**Comment by roe1974** [comment]
ok ... ist aber nur beim start ... und sonst kein problem .... oder ?

**Comment by thkl** [comment]
ich weiss nicht ob HomeKit selber irgendwann noch mal solche Rundrufe macht .. :)

**Comment by roe1974** [comment]
aber ist das ein problem für die rega ?

**Comment by thkl** [comment]
wird man merken ;) ich weiss es nicht

**Comment by roe1974** [comment]
ok :-P
