### ISSUE TITLE
valve only service

### ISSUE THREAD

**Issue by thkl** [thkl/homebridge-homematic#450]

**Comment by thkl** [comment]
HomeMaticHomeKitValveService.js

add in config.json:

in services
`
{
		    "type" : "HM-SPECIAL-VALVE",
		    "service":"HomeMaticHomeKitValveService"
}
`

in special
`
{
		"name" : "_ValveName_",
		"type" : "HM-SPECIAL-VALVE",
		"parameter" : {
		    "channel":"BidCos-RF.SERIALNUMBER:CHANNEL"
		}
	    }
`

**Comment by roe1974** [comment]
teste ich am abend ....
in special .... verstehe ich nicht ....
kannst du eine beispiel config.json posten ? 
lg richard

**Comment by thkl** [comment]
```
{"bridge": {"name": "Homebridge_develop", "username": "CC:22:3D:E3:FF:AA","port": 51826,"pin": "123-45-678"},
"description": "This is an autogenerated config. only the homematic platform is enabled. see the sample for more",
"platforms": [
{
	    "ios10":"true",
            "platform": "HomeMatic",
            "name": "HomeMatic CCU",
            "ccu_ip": "testccu.fritz.box",
	    "subsection":"Homekit",
            "filter_device":[],
            "filter_channel":[],
	    "enable_hmip":true,
            "outlets":[""],
            "doors":[""],
	    "valves":[""],
	    "windows":[""],
            "programs":[""],
	    "variables":[""],
	    "special":[
	    {
		"name" : "ValveDummyTest",
		"type" : "HM-SPECIAL-VALVE",
		"parameter" : {
		    "channel":"BidCos-RF.SERIAL:1"
		}
	    }
	    ],
	    "services": [
		{
		    "type" : "HM-SPECIAL-VALVE",
		    "service":"HomeMaticHomeKitValveService"
		}
	    ]
}
],"accessories": []}
```

**Comment by roe1974** [comment]
alles klar ... teste ich am abend :) ... der „name“ in special hat eine Bedeutung oder ist egal ?

**Comment by thkl** [comment]
So heisst das Ding dann hin HomeKit ..

**Comment by iuliusmaximilian** [comment]
@roe1974 Wenn Du testet schau mal bitte ob du das gleiche hast wie ich inhttps://github.com/thkl/homebridge-homematic/issues/449 der Status passt manchmal nicht, konnte noch nicht heraus finden wann genau aber wenn ich das parallel als Sprinkler einbinde  habe ich manchmal unterschiedliche Status

**Comment by roe1974** [comment]
@thkl ... komme erst später heim, werde aber testen. :-)
Thomas eine Frage noch, kannst du noch wenn Du Zeit hast #429 ansehen.... ob man das einfach lösen könnte ?

lg Richard

**Comment by thkl** [comment]
> @roe1974 Wenn Du testet schau mal bitte ob du das gleiche hast wie ich in #449 der Status passt manchmal nicht, konnte noch nicht heraus finden wann genau aber wenn ich das parallel als Sprinkler einbinde habe ich manchmal unterschiedliche Status


Wenn die Valve Special Klasse gut funktioniert, würde ich diese so umbauen, das man in der Config festlegen kann, ob man einen Timer haben möchte, und welcher Valve Type es sein soll.
Dann kann ich die Switchklasse wieder vom Valve befreien. Diese ist sehr unübersichtlich geworden.

**Comment by thkl** [comment]
> @thkl ... komme erst später heim, werde aber testen. :-)
> Thomas eine Frage noch, kannst du noch wenn Du Zeit hast #429 ansehen.... ob man das einfach lösen könnte ?

Siehe ein Posting davor, ich würde gern generell die Valves wieder aus der Switch Klasse entfernen.  #429 müsste man dann in die Switchklasse implementieren .. oder generell eine neue Klasse dafür bauen ..

**Comment by roe1974** [comment]
ok, ein schritt nach dem andern ;-)

**Comment by roe1974** [comment]
@thkl .... habe es gestern nicht mehr geschafft ... kann ich es von unterwegs (vpn) ändern auf die neue class .... oder muss ich damit die änderung wirksam wird am iphone daheim sein ? (ATV als Hub vorhanden) ?
lg RIchard

**Comment by thkl** [comment]
Funktioniert das ?

**Comment by roe1974** [comment]
@thkl .... sorry der post mit meinem handy hat nicht funktioniert ...
NEIN ... geht nicht ... ist jetzt ein normaler "swith" .. also lampe, stehlampe etc ...?!?!??!

**Comment by roe1974** [comment]
config sieht so aus:

`    "platforms": [
        {
            "ccu_ip": "192.168.xxx.xxx",
            "outlets": [
                "BidCos-RF.NEQ16450xx:1",
                "BidCos-RF.OEQ00302xx:1",
                "BidCos-RF.OEQ02492xx:1",
                "BidCos-RF.OEQ02124xx:2",
                "BidCos-RF.OEQ19983xx:1",
                "BidCos-RF.OEQ19983xx:2",
                "BidCos-RF.OEQ22641xx:2",
                "BidCos-RF.OEQ06551xx:1"
            ],
            "name": "Raspberrymatic",
            "doors": [],
            "platform": "HomeMatic",
            "filter_device": [],
            "special": [
                {
                    "name" : "Ventil",
                    "type" : "HM-SPECIAL-VALVE",
                    "parameter" : {"channel":"BidCos-RF.OEQ02124xx:1"}
                }
            ],
            "services": [
                {
                    "type": "HM-SPECIAL-VALVE",
                    "service": "HomeMaticHomeKitValveService"
                },
                {
                    "type": "HM-LC-Ja1PBU-FM:JALOUSIE",
                    "service": "HomeMaticHomeKitBlindService"
                },
                {
                    "type": "HM-WDS30-OT2-SM-2:WEATHER",
                    "service": "HomeMaticHomeKitThermometerService"
                },
                {
                    "type": "HM-WDS40-TH-I-2:WEATHER",
                    "service": "HomeMaticHomeKitThermostatWeatherService"
                }
            ],
            "filter_channel": [],
            "subsection": "Homekit",
            "variables": [
                "Alarmanlage Tag",
                "Alarmanlage Nacht",
                "Anwesenheit",
                "Urlaub",
                "Klima Schlafzimmer Steuerung",
                "Klima Wohnzimmer Steuerung",
                "Lueften Steuerung",
                "Klima Wohnzimmer manuell",
                "Klima Schlafzimmer manuell", 
                "Balkon Waesche"
            ],`

**Comment by roe1974** [comment]
muss 

"ios10":true

rein ... oder nur für das starten von programmen ?

lg Richard

**Comment by roe1974** [comment]
ahhhhhhhhhhhhhhhhh das ventil ist da......
das gerät ist aber jetzt doppelt drinnen .... und das symbol ist ein "wasserhahn" ... ist das das "generic_valve" symbol ??

**Comment by thkl** [comment]
Ja, Generic ist ein Wasserhahn. Und ja, da das Gerät ja jetzt explizit über die Config eingebunden wird, kann es aus dem HomeKit Gewerk raus ... (alles was dort drin ist wird über seine Standardzuweisung hinzugefügt)

**Comment by roe1974** [comment]
was ist dann "faucet" .. wenn "generic_Valve" wie ein wasserhahn aussieht ?

**Comment by thkl** [comment]
Sieht als Symbol genau so aus.  Auch wenn das Ventil als Shower definiert ist m, wird es als Wasserhahn dargestellt.  Es gibt noch so nen Rasendprinkler als Symbol. Das war’s dann aber auch.

**Comment by roe1974** [comment]
alles klar, dann geht die class :-)
wie sieht es mit der switch class aus (symbol als schalter wie bei den variabken) ... geht das ? ;-)

**Comment by thkl** [comment]
Im Prinzip geht das.  Problem ist nur das die original Switch Class jetzt schon total überfrachtet ist.  Ich könne, analog zur Valve Class hier, eine eigene dafür bauen, wo man wieder in der Config einstellen kann, wie das Symbol aussehen soll.

**Comment by roe1974** [comment]
ok, das wär super, die müssen dann wieder raus aus dem gewerk ... oder ?

**Comment by thkl** [comment]
So sieht’s aus.  Gibts dafür schon nen issue ? Wenn nicht mach mal einen auf. Ich mach den hier zu, sonst komm ich durcheinander.

**Comment by roe1974** [comment]
ja, #429 lg Richard
