### ISSUE TITLE
Kein Remote Access mehr seit iOS 13.1

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#457]
Seit iOS 13.1 PB 1 und letzten tvOS 13 Versionen habe ich keinen Remote Zufgriff mehr auf Homebridge-Homematic Geräte. Die Geräte stehen alle auf Keine Antwort. Push Nachrichten kommen aber weiterhin an. Auch funktioniert alles im lokalen WIFI wie gewohnt. Homebridge wie FFMPEG für Kamera sind voll erreichbar. Es betrifft nur die Homematic. Ich habe vom gleichen iPhone auch Zugriff auf ein zweites Home welches noch auf tvOS 12 läuft und dort ist auch alles Remote korrekt. Es muss also an Änderungen der Steuerzentrale liegen. Mit gestriger 13.1 PB 2 hat sich leider nichts verändert. Hat noch Jemand diese Erfahrung ?

**Comment by iuliusmaximilian** [comment]
Konnte das Problem auf eines meiner drei Apple TVs einschränken. Alle drei laufen auf der gleichen  tvOS 13 PB Version aber eines macht Probleme. Werde das erstmal neu installieren. Wenn ich dieses vom Netz nehme geht der Remote Zugriff.

**Comment by lumi74** [comment]
Hallo,
ich habe genau das gleiche Problem - auch bei mir sind alle über die Homebridge angebundenen Homematic-IP-Geräte nicht mehr von extern erreichbar. Andere HomeKit-Geräte wie z.B. Eve-Geräte lassen sich weiterhin problemlos von extern steuern.
Konntest Du das Problem lösen?
Ich habe jeweils ein ATV 4 und ein ATV 4k, beide auf TvOS 13.0 - eine neuere Version ist noch nicht verfügbar.
Gruß
Lumi

**Comment by iuliusmaximilian** [comment]
Das Problem war wirklich eines der beiden ATV, nimm die mal nach und nach vom Netz so dass du es eh schränkst. Ich bin auf den PB tvOS 13 und iOS 13.1 die laufen allerdings langsamer wahrscheinlich weil Apple Debug an hat.

**Comment by lumi74** [comment]
Das Ausloggen der ATVs aus der iCloud und das anschließende erneute Einloggen und Einrichten von AirPlay und HomeKit hat bei mir geholfen. Jetzt klappt auch der Zugriff von extern wieder.
