### ISSUE TITLE
Thermostat without Humidity commit breaks CUxD-Thermostat Wrapper devices

### ISSUE THREAD

**Issue by Apollon77** [thkl/homebridge-homematic#46]
I use CUxD-Wrapper devices in "Thermostat" mode to have some external sensors deliver data like a Temperature+Humidtity sensor. For those CUxD-Devices you can configure if Humidity is used or not.
They are handled by CCU as "HM-WDS30-T-O" and so the commit https://github.com/thkl/homebridge-homematic/commit/1f04e93bfa866f554569cb7cb63166cd9614502d removed the Humidity value from all of them :-(

The number of these devices all start with "CUX90".

Do you see any point to fix that? Maybe a option to override this?

Because of the fact that it is possible to hide certain channels in the Homekit apps I do not really see the point to remove such a channel in general ...
Ingo F

**Comment by thkl** [comment]
The fix of this is not a big deal because of the new service structure. All services are located in the ChannelService folder.  There is an configuration file which describes which Channeltype or Device:ChannelType is using which Service Class. 

I need to know the type of the device, the type of the channel and the datapoints you want to map into HomeKit to fix your problem

**Comment by Apollon77** [comment]
Wo krieg ich das her?
Ich hab mal in ioBroker geschaut und dort finde ich z.B.:

  "native": {
    "ADDRESS": "CUX1200001",
    "AES_ACTIVE": 0,
    "FLAGS": 1,
    "VERSION": 1,
    "TYPE": "HM-WDS30-T-O",
    "PARENT": "",
    "FIRMWARE": "1.0",
    "CHILDREN": [
      "CUX1200001:0",
      "CUX1200001:1"
    ],
    "PARAMSETS": [
      "MASTER"
    ]

und bei den Children:
  "native": {
    "ADDRESS": "CUX1200001:1",
    "AES_ACTIVE": 0,
    "FLAGS": 1,
    "VERSION": 1,
    "TYPE": "WEATHER",
    "PARENT": "CUX1200001",
    "PARENT_TYPE": "HM-WDS30-T-O",
    "DIRECTION": 0,
    "INDEX": 1,
    "LINK_SOURCE_ROLES": "",
    "LINK_TARGET_ROLES": "",
    "PARAMSETS": [
      "MASTER",
      "VALUES"
    ]

und in "1" gibt es dann TEMPERATURE und HUMIDITY wie sonst auch ... sogar noch HUMIDITYF mit dem Float wert :-)

**Comment by thkl** [comment]
OK , also Kopier Dir von der Github Version hier das File ChannelServices/HomeMaticHomeKitCuxDThermostatService.js nach /usr/local/lib/node_modules/homebridge-homematic/ChannelServices ...

Dort liegt auch eine channel_config.json da muss jetzt noch ein Eintrag in die channelconfig Liste:

{ 
	   "type": "HM-WDS30-T-O:WEATHER",
	   "service": "HomeMaticHomeKitCuxDThermostatService"
}

(Die EInträge sind Komma getrennt also einfach hinter den letzten  noch ein , machen und das rein.

Dann sollte es gehen .. Ich hab ein Netatmo auf einen CuxD HM-WDS10-TH-O gemappt das funktoniert gut.

Dabei ist mir aufgefallen, das ich die ChannelConfig Liste aufteilen muss, denn mit dem nächsten Update überschreibt es die ja wieder ... aber dazu später

**Comment by thkl** [comment]
OK ich hab das noch mal geändert .. ab dem nächsten Release kann man eigene Zuordnungen in der config.json definieren. Diese werden dann nicht beim Update überschrieben

**Comment by Apollon77** [comment]
cool
