### ISSUE TITLE
Garagentor: Ansteuerung HmIP-MOD-HO für Hörmann

### ISSUE THREAD

**Issue by lumi74** [thkl/homebridge-homematic#461]
Hallo,
zunächst einmal vielen Dank für das tolle Homematic-Modul für die Homebridge!
Ich habe gerade das neue HmIP-Modul für Hörmann Garagentore HmIP-MOD-HO erhalten und an meine CCU3 angebunden.
Mit folgender Konfiguration konnte ich dieses auch weitestgehend erfolgreich als Garagentor in Homebridge-homematic einbinden:

            "special": [
                {
                    "name": "Garagentor",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "address_sensor_close": "HmIP-RF.00241A499DDFEA:1.DOOR_STATE",
                        "state_sensor_close": 0,
                        "address_actor_open": "HmIP-RF.00241A499DDFEA:1.DOOR_COMMAND"
                    }
                }
            ],
            "services": [
                {
                    "type": "HM-THKL-GARAGEDOOR",
                    "service": "HomeMaticHomeKitGarageDoorService"
                }
            ]

Der Status des Garagentores wird durch den Status-Kanal einwandfrei angezeigt.
Öffnen kann ich das Garagentor über den DOOR_COMMAND Kanal auch.
Mein einziges Problem ist, dass ich das Tor nicht schließen kann. Ich weiß leider nicht, welcher Wert an den Kanal DOOR_COMMAND zum Schließen des Tores übergeben werden muss.
Ebenfalls ist es mir nicht gelungen, das Schließen des Tores über eine virtuelle Taste auszulösen, die das Tor jedoch einwandfrei schließt, wenn ich diese an der CCU3 auslöse. Ich vermute, dass virtuelle Tasten nach wie vor nicht unterstützt werden, oder?
Kann mir jemand sagen, wie ich den Wert herausfinde, mit dem ich das Schließen des Tores über den Kanal DOOR_COMMAND des HmIP-MOD-HO herausfinden kann? 
Danke!

Gruß
Lumi

**Comment by lumi74** [comment]
Hallo,
ich konnte das Problem jetzt selbst lösen, musste dazu allerdings einen leicht modifizierten HomeMaticHomeKitGarageDoorServiceHM.js erstellen, da das HmIP-MOD-HO nur einen Aktor bereitstellt, der über unterschiedliche Kommandos (1 = Öffnen, 3 = Schließen) das Tor öffnet und schließt. Diese Funktion war im HomeMaticHomeKitGarageDoorService.js bisher nicht vorgesehen.
Daher habe ich einen leicht modifizierten HomeMaticHomeKitGarageDoorService.js erstellt, der es ermöglicht,  das Garagentor über einen Aktor ("address_actor_open": "HmIP-RF.00xxxxxxxxxxxx:1.DOOR_COMMAND") zu öffnen und zu schließen. Klappt einwandfrei!
Auf Wunsch stelle ich den angepassten ChannelService gerne zur Verfügung.
Die Konfiguration sieht dann wie folgt aus:
            "special": [
                {
                    "name": "Garage",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "address_sensor_close": "HmIP-RF.00241A499DDFEA:1.DOOR_STATE",
                        "state_sensor_close": 0,
                        "address_actor_open": "HmIP-RF.00241A499DDFEA:1.DOOR_COMMAND",
                        "message_actor_open": {
                            "on": 1,
                            "off": 3
                        }
                    }
                }
            ],
            "services": [
                {
                    "type": "HM-THKL-GARAGEDOOR",
                    "service": "HomeMaticHomeKitGarageDoorServiceHM"
                }

Gruß
Lumi

**Comment by meistermolli** [comment]
Hallo,
an welcher stelle der config.json muss ich das ganze denn einfügen?
Irgendwie klappt das ganze bei mir nicht.

Danke und gruß

**Comment by lumi74** [comment]
Hi,

Du benötigst eine angepasste HomeMaticHomeKitGarageDoorService.js - ich habe diese HomeMaticHomeKitGarageDoorServiceHM.js genannt.
Ich habe für die Datei gerade einen Pull-Request gemacht, um diese ins Projekt hinzuzufügen. Vorab habe ich Dir die Datei an diese Mail angefügt - ich hoffe, das klappt.
Die Datei muss manuell in das Verzeichnis /usr/lib/node_modules/homebridge-homematic/ChannelServices/ gelegt werden.

In der config.json müssen die Einträge „special“ und „services" innerhalb „platforms“ eingefügt werden:

    "platforms": [
        {
            "platform": "HomeMatic",
            "name": "HomeMatic CCU3",
            "ccu_ip": "ccu3-webui",
            "enable_hmip": "true",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "windows": [],
            "programs": [],
            "accessories": [],
            "subsection": "Homekit",
            "variables": [],
            "special": [
                {
                    "name": "Garagentor",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "address_sensor_close": "HmIP-RF.xxxxxxxxxxxxxx:1.DOOR_STATE",
                        "state_sensor_close": 0,
                        "address_actor_open": "HmIP-RF.xxxxxxxxxxxxxx:1.DOOR_COMMAND"
                    }
                }
            ],
            "services": [
                {
                    "type": "HM-THKL-GARAGEDOOR",
                    "service": "HomeMaticHomeKitGarageDoorService"
                }
            ]
        },

Das xxxxxxxxxxxxxx muss durch die Seriennummer des HmIP-MOD-HO-Moduls ersetzt werden, die man aus der Geräteliste im WebUI ermitteln kann.

Gruß
Lumi


Am 26.09.2019 um 12:48 schrieb meistermolli <notifications@github.com<mailto:notifications@github.com>>:


Hallo,
an welcher stelle der config.json muss ich das ganze denn einfügen?
Irgendwie klappt das ganze bei mir nicht.

Danke und gruß

**Comment by meistermolli** [comment]
Hallo...
vielen vielen Dank .. mit der Anleitung konnte ich das ganze hinzufügen.
Der Versand mit dem Anhang hat leider nicht funktioniert, aber ich konnte mir das ganze ja hie rraus kopieren.

Ich bekomme nun das Garagentor im Homekit angezeigt und den Status korrekt.
Jedoch funktioniert der Schließen befehl leider nicht.
Besteht zusätzlich die möglichkeit über die Homebridge auf die Lüftungsstellung zu zu greifen?
Hier wird ja nur öffnen und Schließen angeboten.

Ich Danke dir aber schon vielmals für die Hilfe ...

Gruß meistermolli

**Comment by lumi74** [comment]
Hallo,
damit auch das Schließen funktioniert, benötigst Du die angepasste HomeMaticHomeKitGarageDoorServiceHM.js. Ich habe darin ein paar kleine Anpassungen vorgenommen, da der "originale" GarageDoorService davon ausgeht, dass entweder ein Taster vorhanden ist, der das Tor abwechselnd öffnet und schließt, oder zwei separate Autoren zum Öffnen und Schließen. Das HmIP-MOD-HO hat jedoch einen Autor, der mit unterschiedlichen Kommandos entweder öffnet oder schließt. Dies habe ich am HomeMaticHomeKitGarageDoorServiceHM.js angepasst. 
Ich versuche einmal, Dir die angepasste Datei per PM zu schicken.
Die Ansteuerung der Lüftungsposition ist mit HomeKit meines Erachtens nicht möglich.
Gruß
Lumi

**Comment by meistermolli** [comment]
Also ich hatte ja deine HomeMaticHomeKitGarageDoorServiceHM.js  aus dem pullrequest genommen. Diese muss ich dann löschen? Der stand im Pull request ist 2 Tage alt. Da hattest du noch nichts überschrieben? In deinem Config Eintrag steht  "service": "HomeMaticHomeKitGarageDoorService" das bleibt auch so oder muss hinten das HM noch dahinter?

Merci

**Comment by lumi74** [comment]
Hallo,
das Versenden der Datei war leider nicht möglich. Im Pull-Request steht die funktionierende Version, die als HomeMaticHomeKitGarageDoorServiceHM.js im Ordner ChannelServices auf dem Raspberry abgelegt werden muss.
Anschließend muss der Service in der config.json dann in HomeMaticHomeKitGarageDoorServiceHM umbenannt werden. Dann sollte es klappen!
Viel Erfolg!
Gruß
Lumi

**Comment by meistermolli** [comment]
Hallo,

ich habe im Verzeichnis:
/usr/lib/node_modules/homebridge-homematic/ChannelServices/

beide Dateien liegen:
sowohl:   HomeMaticHomeKitGarageDoorService.js
als auch:  HomeMaticHomeKitGarageDoorServiceHM.js

Meine Config sah wie folgt aus:

unter platforms: 

            "special": [
                {
                    "name": "Garagentor",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "address_sensor_close": "HmIP-RF.12345678901234:1.DOOR_STATE",
                        "state_sensor_close": 0,
                        "address_actor_open": "HmIP-RF.12345678901234:1.DOOR_COMMAND"
                    }
                }
            ],
            "services": [
                {
                    "type": "HM-THKL-GARAGEDOOR",
                    "service": "HomeMaticHomeKitGarageDoorService"
                }
            ]
        },

ändere ich diese Config nun ab auf den HomeMaticHomeKitGarageDoorServiceHM, startet die Homebridge nicht mehr!!!

unter platforms: 


"special": [
                {
                    "name": "Garagentor",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "address_sensor_close": "HmIP-RF.12345678901234:1.DOOR_STATE",
                        "state_sensor_close": 0,
                        "address_actor_open": "HmIP-RF.12345678901234:1.DOOR_COMMAND"
                    }
                }
            ],
            "services": [
                {
                    "type": "HM-THKL-GARAGEDOOR",
                    "service": "HomeMaticHomeKitGarageDoorServiceHM"
                }
            ]
        },








oder muss der 
"type": "HM-THKL-GARAGEDOOR"
auch noch abgeändert werden?

Danke und Gruß

**Comment by lumi74** [comment]
Hallo,

die Einträge unter Services sind soweit korrekt. 
Allerdings musst Du unter Special den Eintrag "message_actor_open" ergänzen:

{
"name": "Garage",
"type": "HM-THKL-GARAGEDOOR",
"parameter": {
"address_sensor_close": "HmIP-RF. 12345678901234:1.DOOR_STATE",
"state_sensor_close": 0,
"address_actor_open": "HmIP-RF. 12345678901234:1.DOOR_COMMAND",
**"message_actor_open": {
"on": 1,
"off": 3**
}

Diesen hatte ich in meiner Antwort vom 29.09. leider vergessen - habe ich jetzt ergänzt. 
Sorry!

Gruß
Lumi

**Comment by flohei** [comment]
Hey Lumi,

ich hab dein Modul vorige Tage bei mir auch mal installiert. Das klappt alles ziemlich gut. Vielen Dank dafür!

Zwei Sachen, die mir aufgefallen sind, und von denen ich gerne wüsste, ob das bei euch auch so ist:

1. Wenn jemand das Tor mit einem normalen Handsender öffnet sehe ich diese Änderung in Home nicht. Push Nachrichten kommen dementsprechend auch nicht.
1. Wenn ich das Tor von Siri öffnen lasse, sagt sie mir nach der Bestätigung meistens, dass etwas nicht stimmt oder schiefgelaufen ist. Allerdings macht sie das Tor ordnungsgemäß auf und zu.

Ist das bei euch auch so?

**Comment by lumi74** [comment]
Hi flohei,
sorry für die späte Antwort. Mir war das bisher gar nicht aufgefallen, aber das ist korrekt.
Dies hat die gleiche Ursache hat, wie bei nicht aktualisierten Variablen in Homebridge, nämlich dass die CCU3 bei einer Statusänderung kein Event sendet (siehe https://github.com/thkl/homebridge-homematic/wiki/Variablen).
Das Problem lässt sich somit auf die gleiche Weise lösen:
1) Auswahl einer virtuellen Taste auf der CCU3. Ich habe diese umbenannt in "Hombridge-Trigger:1".
2) Virtuelle Taste in Homebridge-Konfiguration eintrage;
""variable_update_trigger_channel": "Hombridge-Trigger:1",
3) Programm auf der CCU3 anlegen und die virtuelle Taste bei Veränderung des Garagentor-Status auslösen:

![image](https://user-images.githubusercontent.com/51851625/70373402-7ef9c980-18e8-11ea-8f93-17fa80a51b34.png)

Ich habe das soeben bei mir implementiert. Nun kommt direkt eine Pushnachricht, wenn das Garagentor geöffnet oder geschlossen wurde.

Gruß
Lumi

**Comment by allesistmoeglichoderauchnicht** [comment]
Mal ne Frage. ich hab über Hoobs ein Homekit laufen und versuche verzweifelt den HmIP-MOD-HO richtig zum laufen zu bekommen. Vielleicht habt ihr mir ja zufällig nen Tipp. Also ohne in Homematic den letzten Step eingetragen zu haben (also mit dem Trigger) und sogar ohne, dass ich die .js Datei eingefügt habe, läuft es ein bisschen. Aktuell habe ich die Datei runtergeladen und in das Verzeichnis kopiert, aber keinen Unterschied zu vorher bemerkt (nach dem Neustart von Hoobs). Mein Problem ist, wenn das Garagentor zu ist und ich Siri sage sie soll das Garagentor öffnen, beginnt sie direkt, bleibt aber nach ein paar Sekunden stehen (mehr als in der Lüftungsposition). Wenn ich dann das gleiche nochmal sage, macht sie wieder genau gleich lang weiter (und das Tor ist nicht zu 100% offen sondern ca. 90%). Wenn ich nun sage "Schließe das Garagentor", fährt das Tor kurz ganz auf, bleibt hier stehen und fährt dann ganz zu. KEINE Ahnung wie ich das ändern muss...

**Comment by smarthome43372** [comment]
Hallo, ich habe den HmIP-MOD-HO über den HmIP Access Point laufen und über ioBroker eingebunden. Leider wird der HmIP-MOD-HO im ioBroker nicht richtig angesprochen und es werden keine Stati angezeigt. Hat jemand eine Idee wie das gelöst werden kann. Letztendlich möchte ich das Garagentor über den AP in der Homebridge haben.

**Comment by abc150781** [comment]
Guten Morgen,

mein Problem ist das die HomeMaticHomeKitGarageDoorService,js vorhanden ist, aber die HomeMaticHomeKitGarageDoorServiceHM.js nicht. Der Versuch die Datei HomeMaticHomeKitGarageDoorService in HomeMaticHomeKitGarageDoorServiceHM zu kopieren funktioniert leider nur bedingt. Das Tor kann geöffnet werden, fährt aber nicht ganz hoch und bleibt zwischendurch stehen, sodass ich nochmal in der HomeAPP klicken muss. Was mache ich falsch oder liegt es an der fehlenden HomeMaticHomeKitGarageDoorServiceHM.js Datei? Und falls das der Fall ist, kann mir jemand diese Datei zukommen lassen. Würde ungern meine gesamte Homebridge neu aufsetzten.

```
manager@homebridge-srv:~$ sudo find / -name "HomeMaticHomeKitGarageDoorService.js"
/var/lib/homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitGarageDoorService.js
/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitGarageDoorService.js
manager@homebridge-srv:~$ sudo find / -name "HomeMaticHomeKitGarageDoorServiceHM.js"
manager@homebridge-srv:~$

```

Und so sieht meine config.json aus:



"platforms": [
        {
            "platform": "HomeMatic",
            "name": "HomeMatic",
            "ccu_ip": "x.x.x.x",
            "enable_hmip": "true",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "windows": [],
            "programs": [],
            "accessories": [],
            "subsection": "Homekit",
            "variables": [],
            "special": [
                {
                    "name": "Garagentor",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "address_sensor_close": "HmIP-RF.00xxxxxxxxxxxx:1.DOOR_STATE",
                        "state_sensor_close": 0,
                        "address_actor_open": "HmIP-RF.00xxxxxxxxxxxx:1.DOOR_COMMAND",
                        "message_actor_open": {
                            "on": 1,
                            "off": 3
                        }
                    }
                }
            ],
            "services": [
                {
                    "type": "HM-THKL-GARAGEDOOR",
                    "service": "HomeMaticHomeKitGarageDoorServiceHM"
                }
            ]
        },
