### ISSUE TITLE
CCU3 unbenutzbar durch homebridge

### ISSUE THREAD

**Issue by doppelpunkt89** [thkl/homebridge-homematic#462]
Hallo,

in meiner Verzweiflung ist mir nichts anderes mehr eingefallen als hier ein Issue zu eröffnen. Ich komme einfach dem Problem selbst nicht auf die Schliche. Mittlerweile habe ich wochenlange Fehlersuche hinter mir und das einzige was bisher sicher ist: Meine CCU3 kommuniziert nicht mehr sobald die Homebridge im Netzwerk läuft und mittels dieses Plugins zugreift. Ich habe auch mittlerweile verschiedene Versionen des Plugins durch, npm, beta, developer etc.. Das Problem bleibt das gleiche. Alle Komponenten laufen wunderbar bis die Homebridge hochfährt. Dann geht die CCU3 sofort in den Modus "Gerätekommunikation gestört" sobald ein Gerät geschaltet wird oder ich Einstellungen übertragen will. Dabei ist es dann unerheblich ob über HomeKit oder direkt über die CCU. Es sieht extrem nach Duty Cycle 100% aus, obwohl laut CCU dieser immer im grünen Bereich (unter 10%) ist. Lässt man die CCU dann eine Stunde in Ruhe, funktioniert auch die Steuerung durch Siri/Homekit eine Zeit lang, bis hier auch wieder zu viel passiert ist und die CCU wieder dicht macht. Neustart etc. bringt dann bei der CCU nichts, nur Warten hilft.

Hier die Details zu meinem Setup:
- CCU3, Firmware 3.47.15 (hatte auch schon mal ein Update auf .18 gemacht, das aber wieder rückgängig gemacht. Macht aber sowieso keinen Unterschied beim Problem). Einstellungen:
XML RPC API Authentifizierung "aus",
![image](https://user-images.githubusercontent.com/46716395/65754007-6e6eeb00-e110-11e9-9d97-5468bb69ed4a.png)

- HmIP-SWSD 10 Stück, Firmware 1.0.12
- HmIP-BROLL 13 Stück, Firmware 1.6.2
- HmIP-BWTH 9 Stück, Firmware 1.2.4
- HmIP-PCBS 1 Stück, Firmware 2.4.0 (Update steht an)
- HMIP-PS 1 Stück, Firmware 2.6.2

- Raspberry Pi 3, Raspbian mit Homebridge 0.4.5 und homematic plugin (developer branch)

Auszug aus config.json:
"platform":"HomeMatic",
         "name":"HomeMatic CCU3",
         "ccu_ip":"XXX.XXX.XXX.XXX",
         "enable_hmip":"true",
         "filter_device"::["BidCoS-RF"],
         "filter_channel":[],
         "outlets":[],
         "doors":[],
         "programs":["Rauchmelder Alarm aus"],
         "ios10":true,
         "accessories":[],
         "subsection":"Homekit"

Ich liefere gerne weitere Infos falls erforderlich/gewünscht. Ich hoffe wirklich jemand kann mir weiterhelfen. Die ganze Homematic Sache macht für mich ohne HomeKit leider nicht mal halb so viel Spaß :(

EDIT/BTW: Gestern habe ich Homeassistant mal auf dem Pi installiert und dort die Verbindung zur CCU hergestellt (was ja auch via XML RPC API geht) und siehe da: alleine die CCU dort zu konfigurieren führte zum gleichen Verhalten. Ist diese Schnittstelle so extrem anfällig?

Danke vorab und Grüße

**Comment by Frank-Friemel** [comment]
Welche Geräte hast du denn im Gewerk „Homekit“ exportiert? Etwa alle deine Geräte?. Vielleicht wäre es sinnvoll testweise erstmal mit einem Gerät anzufangen. Irgendwas simples - Licht oder so.

**Comment by doppelpunkt89** [comment]
Ja ich habe alle meine Geräte da drin, so soll es ja auch sein. 36 Geräte sollten ja jetzt eigentlich auch nicht ungewöhnlich viele sein, oder?

Werde dennoch testweise mal nur ein Gerät ins Gewerk aufnehmen.

**Comment by Frank-Friemel** [comment]
Nicht wegen der Menge. Ich kenne jetzt die Kurzbezeichnungen nicht alle auswendig, aber vielleicht ist was exotisches dabei? Wenn xml rpc generell Probleme bereiten würde, dann sollten sich doch die Stimmen im Netz mehren

**Comment by doppelpunkt89** [comment]
Hier mal mein Gewerk:

**Comment by doppelpunkt89** [comment]
Sorry, aus Versehen am Handy das issue auf closed gesetzt. Grundsätzlich heißen meine Aktoren alle: Rollade <Zimmername>, Thermostat <Zimmername>, Rauchmelder <Zimmername>. Die beinhalten keine Sonderzeichen, aber z.B. Umlaute.
