### ISSUE TITLE
Homekit Gerät mit Homematic Schalter steuern

### ISSUE THREAD

**Issue by tiirex9** [thkl/homebridge-homematic#463]
Ich brauch hier ein bisschen Denkhilfe, weil ich es bisher nicht hinbekommen habe.

Ich habe einen Schaltaktor, der ein konkretes Licht ein- und ausschalten kann. Ich habe den entsprechenden Channel im Homekit Gewerk drin, sodass ich das Licht auch via Homekit steuern kann.

Ich würde jetzt gerne einstellen, wenn man an dem Schalter auf "Aus" drückt, soll auch das Licht einer Philips Hue Lampe ausgehen, die in Homekit konfiguriert ist.

Ich habe es bereits mit einer Automation in der Home-App a la "Wenn Homematic Licht ausgeschaltet wird, schalte Hue Lampe aus" probiert, aber das funktioniert nur, wenn das Homematic Licht auch tatsächlich an war. Was es nicht immer ist. Ich möchte, dass der Schalter trotzdem die Hue Lampen ausschalten kann.

Den An/Aus Schalter ins Homekit Gewerk packen, hat leider keinen Schalter in Homekit verfügbar gemacht, mit dem ich das hätte konfigurieren können. Aber evtl. habe ich hier auch was vergessen.

Jemand Ideen, ob und wie ich das bewerkstelligen kann?

**Comment by pbksol** [comment]
Die Konfiguration der Schaltfunktionen erfolgt innerhalb des Schalter-Gerätes in HomeKit, dafür wird keine Automation erstellt sondern erfolgt in den Einstellungen des Schalters. Beachte aber, dass nur der einfache Tastendruck korrekt ausgewertet wird wenn der Schalter von Homematic kommt. Doppelte und lange Drücke funktionieren nicht oder so unzuverlässig, dass es sinnvoll ist sie gar nicht erst zu belegen.

**Comment by tiirex9** [comment]
Genau, dafür muss ich den Schalter in Homematic aber erstmal in Homekit angezeigt bekommen.
Wie mach ich das? Ich bekomme nur das dahinterstehende Gerät in Homekit (in dem Fall die angeschlossene Badezimmer Spiegel Beleuchtung).

**Comment by pbksol** [comment]
Gib mir mal bitte die Typenbezeichnung des HomeMatic-Gerätes, das als Schalter fungiert.

**Comment by tiirex9** [comment]
HmIP-BSM

**Comment by tiirex9** [comment]
Verstehe. Danke für die Hilfe. Ich probier das demnächst mal aus. :)

**Comment by tiirex9** [comment]
Habe in Homematic eine Variable erstellt und sie in Homebridge unter "variables" angegeben.
Dann in Homematic ein Programm das jetzt erstmal so aussieht:
![image](https://user-images.githubusercontent.com/1958744/66415804-b806e200-e9fc-11e9-92fe-e360fe259209.png)

Änderungen am Schalter, haben korrekte Auswirkung auf die Systemvariable in Homematic, aber der Status in Homekit scheint sich nicht zu ändern. Anders rum geht es hingegen schon. (Also wenn ich den Zustand in Homekit ändere, ändert sich der Zustand der Variable in Homematic.)

Meintest du mit der Verknüpfung tatsächlich ein Programm? Oder gibt es noch einen direkteren/besseren Weg?

**Comment by pbksol** [comment]
Nimm mal den Auto-Reset zum Test raus. Die Variable muss auch in HomeKit ihren Status ändern. Ich habe aber ein paarmal schon den Fall gehabt, dass erst nach dem zweiten Neustart der Homebridge der Status zuverlässig in beide Richtungen übernommen wurde.

**Comment by pbksol** [comment]
Ich trage noch was nach… Seit iOS 13 braucht das Update des Schalters über die Variable erschreckend lange, wie ich gerade feststellen muss. Das könnte schon der Grund sein, warum das so aussieht als käme nix an…

**Comment by tiirex9** [comment]
Ja, ich merke auch gerade, dass es teilweise > 30 Sekunden dauert.
Das ist dann leider nicht so gut geeignet für den Anwendungszweck. Leider.

**Comment by pbksol** [comment]
Du, mir fällt da gerade ein, dass ich was wichtiges vergessen hatte zu erwähnen… Guck mal https://github.com/thkl/homebridge-homematic/wiki/Variablen – da ist beschrieben, wie sich mit einem Trick die Aktualisierung der Variablen erzwingen lässt.

**Comment by tiirex9** [comment]
Ich hab das mal ausprobiert. Klappt nur leider nicht. Der Trigger wird ausgelöst, aber er kommt nicht in Homebridge an. Auch wenn ich den Trigger manuell auslöse, funktioniert das nicht. :(

config.json sieht so aus
```       "variables":["Badezimmer Trigger Aus"],
       "variable_update_trigger_channel": "Homebridge Trigger",```

Variable und Schalter sind konfiguriert:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1958744/68056640-f342bb00-fcf3-11e9-8777-eba124b116d0.png">
Ich hab den Schalter ins Homekit Gewerk, weil es auf dem Screenshot in dem Wiki Artikel der Fall ist - auch wenn es in der Anleitung nicht beschrieben ist.

---

Mir ist beim Debugger (Homebridge in DEBUG Mode gestartet) auch aufgefallen, dass der Knopfdruck an dem HmIP-BSM Gerät sehr wohl in Homebridge ankommt...
Siehe:
```Nov 01 21:03:39 pismart homebridge[9489]: [2019-11-1 21:03:39] [HomeMatic] rpc <- system.multicall on HmIP-RF.
Nov 01 21:03:39 pismart homebridge[9489]: [2019-11-1 21:03:39] [HomeMatic] RPC event for HmIP-RF.000858A9919548:0 CONFIG_PENDING with value false
Nov 01 21:03:39 pismart homebridge[9489]: [2019-11-1 21:03:39] [HomeMatic] RPC event for HmIP-RF.000858A9919548:0 UNREACH with value false
Nov 01 21:03:39 pismart homebridge[9489]: [2019-11-1 21:03:39] [HomeMatic] RPC event for HmIP-RF.000858A9919548:0 RSSI_DEVICE with value -68
Nov 01 21:03:39 pismart homebridge[9489]: [2019-11-1 21:03:39] [HomeMatic] rpc <- event  on undefined
Nov 01 21:03:39 pismart homebridge[9489]: [2019-11-1 21:03:39] [HomeMatic] Ok here is the Event["homebridge_HmIP-RF.","000858A9919548:1","PRESS_SHORT",true]
Nov 01 21:03:39 pismart homebridge[9489]: [2019-11-1 21:03:39] [HomeMatic] RPC single event for HmIP-RF.000858A9919548:1 PRESS_SHORT with value true```

**Comment by pbksol** [comment]
Hast Du, nachdem in dem Programm, das die Variable setzt nach dem setzen der Variable eingefügt, dass der Taster einmal gedrückt werden soll?

<img width="810" alt="Bildschirmfoto 2019-11-01 um 22 46 52" src="https://user-images.githubusercontent.com/8238713/68058477-82060680-fcf9-11e9-81da-39dc54b76953.png">

So in der Art, quasi. Denn nur wenn die Taste auch gedrückt wird erfolgt die Aktualisierung. Die Sekunde Verzögerung muss nicht sein.

**Comment by tiirex9** [comment]
Ich hatte es mit "sofort" drin. Aber sonst identisch.

Getestet habe ich die Übernahme der Variablen in HomeKit aber durch manuelles Auslösen des Triggers über das Frontend... Das hat nicht funktioniert.

Ja, neugestartet habe ich. :)
