### ISSUE TITLE
Status am Aktor HMW-LC-Sw2-DR

### ISSUE THREAD

**Issue by zivi78** [thkl/homebridge-homematic#465]
ich habe erfolgreich nach der Anleitung auf technikkram.net die Einrichtung eines PI 3B+ und dem oben beschriebenen Aktor mal angefangen mein SmartHome auf Siri/Apple zu bringen. Das ganze mit EINEM Raspberry pivCCU3 und der Homebridge.

meine installieren Module auf dem Raspberry:
pi@raspberrypi:~ $ sudo npm list -g --depth=0
/usr/local/lib
├── homebridge@0.4.50
├── homebridge-homematic@0.0.109
└── npm@6.9.0

Beim steuern über die Homekit-App habe ich allerdings folgendes Problem festgestellt;

Ich habe drei Geräte von Apple (Watch, Phone, PAD) + Apple TV 4. Generation. Wenn ich auf allen drei Geräten die Homekit-App geöffnet habe und auf einem Gerät einen Aktor schalte, dann bekomme ich sofort auch den jeweiligen anderen den Status des Aktors korrekt gezeigt. Schalte ich den Aktor auf einem anderen Gerät wieder aus (solange die Homekit-App auf allen drei Geräten geöffnet ist), dann bekomme ich den Status sofort auch wieder bei allen Geräten richtig angezeigt.

NUN ABER DAS PROBLEM:
Schalte ich den Aktor z.B. am Phone ein (zu der Zeit sind aber die anderen beiden Geräte bzw. die Homekit-App nicht gestartet), gehe dann aufs PAD und öffne die Homekit-App, dann wird der am Phone geschaltene Aktor mit AUS gezeigt, bzw. springt am Phone dann auch sofort auf AUS.

Das selbe passiert, wenn ich am Phone z.B. den Aktor EIN schalte, dann die App ins Dock schließe und die Homekit-App wieder öffne.

Ich hoffe Sie haben mir einen Tipp, bzw. können mir weiterhelfen, dass ich an allen Geräten immer den aktuellen Status auch nach einem erneuten Aufruf der HomeKit App sehen kann.

mfg
zivi78

**Comment by maxisven** [comment]
Hallo :)
Leider habe ich dasselbe Problem gibt es da schon ne Hilfestellung ? oder hast du es mitlerweile selbst raus gefunden ?

**Comment by zivi78** [comment]
Nein. Leider habe ich es noch nicht herausbekommen. Bin für jeden Hinweis extrem dankbar!

**Comment by iuliusmaximilian** [comment]
Habt ihr das nur beim HMW-LC-Sw2-DR oder generell? Ich habe den auch bei mir und kann das gerne mal testen.

**Comment by maxisven** [comment]
HM-LC-Sw4-DR also ich hätte den Autor denke die unterscheiden sich einfach nur von den geschalteten Kanälen ?

**Comment by iuliusmaximilian** [comment]
Welche Node.js Version verwendet ihr ?

**Comment by maxisven** [comment]
Also ich verwende die node.js v10.16.3

**Comment by zivi78** [comment]
Ich habe das grundsätzlich mit allen Aktoren z.B HMW-IO-12-Sw7-DR, HM-LC-Sw1PBU-FM, HM-LC-Sw2-FM, HMW-LC-Sw2-DR

Node.Js bei mir auch v10.16.3

**Comment by maxisven** [comment]
also ich habe von Homematic noch den Türschalter HMIP-SWDO und die Rolladensteuerung HmIP BROLL damit funktioniert seltsamerweise alles...
Liegt es daran das es HMIP gerate sind ?

**Comment by maxisven** [comment]
So mittlerweile habe ich das Plugin SpecialSwitchService funktionsfähig gemacht. :-D und es funktioniert wesentlich besser und die Schaltung der Schalter ist schneller wo ich vorher ca. 10-15 Sekunden warten musste bis es aktiviert wurde.
Nun kommt der Hacken es hat sich im wesentlichen nichts verändert am Status außer ich starte die homebridge neu und bekomme echte Status angezeigt wird was verändert und wird auf dem iPad oder macbook home geöffnet wird der status geändert. starte ich homebridge neu ist alles ok.
Wird der Schalter manuell betätigt ändert sich nichts im status und bleibt einfach so stehen ob an oder aus.
das ganze ist iwie verrückt

**Comment by iuliusmaximilian** [comment]
@maxisven Habe das für den HMW-LC-Sw2-DR mit ein Mac 10.15 > Home UND iOS 13.1.3 > Home und iPadOS 13.1.3 > Home getestet, alle aktualisieren korrekt unter einer Sekunde. Ich nutze einen Raspberry 3B+ "Buster" auf letztem Update und Upgrade mit "latest" homebridge und homebridge-homematic (109) und ausgetauschter HomeMaticRPC.js #466 sowie node.js 12.13.0. CCU3 mit 3.47.22.
