### ISSUE TITLE
Hardware change

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#467]
Hallo zusammen, ich würde gerne die Hardware meines Raspberry 3B+ tauschen. Wenn ich die SD eins-zu-eins in einen anderen Raspberry verwende, wird dann Home weiter laufen oder werden die Bridges dann nicht mehr erkannt so dass das gesamte Home neu eingerichtet werde muss ? Hat Jemand diesen Fall schon mal in der Praxis gehabt ?

**Comment by dkrizic** [comment]
Sollte eigentlich gehen. De neue Raspi kann auch eine andere IP haben, dass sich die Geräte über Bonjour finden.
