### ISSUE TITLE
Hmip-FBL wird nicht unterstützt

### ISSUE THREAD

**Issue by maxrad-nobrain** [thkl/homebridge-homematic#469]
Als absoluter Anfänger bekomme ich leider keine hmip-fbl zu meiner Homebridge hinzugefügt. Mag mich jemand unterstützen?
Im Endeffekt bin ich nur an den Funktionen auf/ab und dem Status interessiert, die Winkelverstellung benötige ich nicht. 
Nach meinem schmalen Verständnis exisitiert schon ein customclassservice im dev branch. Was genau muss ich damit machen?
Sorry blutiger Anfänger hier!

**Comment by rolfsg** [comment]
Habe das gleiche Problem, habe nur einen HMIP-FBL im Einsatz, dieser wird aber von Homebridge nicht ausgelesen.

**Comment by gsiscotty** [comment]
Auch ich würde gerne die HMIP-FBL hinzufügen.
Woran liegt es, dass diese nicht unterstützt werden?

**Comment by rolfsg** [comment]
Habe es heute geschafft meinen HMIP-FBL in Homebridge zu integrieren. Da der HmIP-BBL bereits integriert ist kann der FBL sehr einfach hinzugefügt werden:

1. in der Datei channel_config.json ganz unten den Eintrag des HmIP-BBL duplizieren und für den FBL abändern:
	{
	   "type" : "HmIP-BBL:BLIND_TRANSMITTER",
	   "service": "HomeMaticHomeKitBlindSlatServiceIP"
	},
	**{
	   "type" : "HmIP-FBL:BLIND_TRANSMITTER",
	   "service": "HomeMaticHomeKitBlindSlatServiceIP"
	},**

2. in der Datei config.json folgende Zeilen hinzufügen, z.B. ganz am Ende (aber vor dem letzten } )
**"services": [
        {
            "type": "HmIP-FBL:BLIND_TRANSMITTER",
            "service": "HomeMaticHomeKitBlindSlatServiceIP"
        }
    ]**
3. in Geräteeinstellung der CCU muss beim HMIP-FBL jeweils der Kanal :3 für HomeKit markiert werden. Die anderen Kanäle nicht markieren, sie produzieren nur Fehlermeldung.
