### ISSUE TITLE
Dimmer + Siri

### ISSUE THREAD

**Issue by thoduh** [thkl/homebridge-homematic#47]
Hallo,

erst einmal vielen Dank für die ganzen Bemühungen, wirklich eine super Arbeit von dir !!

Beim Dimmer ist mir folgendes aufgefallen:

Bei "Siri, schalt das List ein", schaltet Siri das Licht auf 0% und sagt dann "Licht ist eingeschaltet", was ja nicht stimmt.
Bei "Siri, stell das Licht auf 10%", schaltet Siri das Licht auf 10%, funktioniert als.

Ich meine, dass diese Problem mit einer Version von 0.0.44 noch nicht vorhanden war, kann das sein?

**Comment by thkl** [comment]
Ja ;) ... das Problem habe ich auch schon festgestellt.
Also es ist ja so, Dimmer haben 2 Services. Einen Ein/Aus und einen für die Helligkeit.
Siri / die HomeApp setzt bei Schalte ein / Aus nur den Service für Ein / Aus ... das ist sicher so, das beim Einschalten der alte Helligkeitswert verwendet wird. Das heisst wenn ich eine Lampe mit 50% ausschalte dann geht die bei nächsten Einschalten wieder auf 50%.

Soweit so gut. Der Homematic Dimmer hat natürlich sowas nicht, sodas ich den alten Helligkeitswert zwischenspeichern muss.  Beim ersten Launch der Bridge ist der natürlich noch nicht gesetzt und deswegen funktioniert Schalte Licht ein nicht. Weil es ja auf die unbekannten 0% geht. 

Wenn das Licht einmal mit einem Dimmwert versehen wurde , funktioniert natürlich auch ein / ausschalten.


Aber jetzt wo ich das hier tippe fällt mir ein Lösungsansatz ein.

**Comment by thoduh** [comment]
Ich bekomme die 0.0.45 nicht installiert? Es wird immer die 0.0.44 installiert?
Versteh ich nicht...

**Comment by thkl** [comment]
0.0.45 ist auch noch nicht raus ;) ... du könntest es hier manuell aus dem Github installieren.
Ich schau mal ob ich das morgen fertig bekomme

**Comment by thoduh** [comment]
Ach soooo.
Hatte in einem File aber die 0.0.45 gelesen :)
Danke für die Info 😁

**Comment by hoermiller** [comment]
Hallo Zusammen. 
Erst einmal möchte ich Danke sagen für so ein geniales Plugin für HomeBase. Hatte mich eigentlich schon damit abgefunden das HomeMatic nicht HomeKit kompatibel ist und dann kam die Rettung 👍 

Ich habe folgendes Problem mit dem Dimmer. Ich hab eine dimmbare und schaltbare Steckdose die ich innerhalb von HomeBase als Licht erkennen lasse um die Dimm-Funktion nutzen zu können. Wenn ich Siri sage: "Dimme das Licht auf X%" wird immer der Wert 1% gesetzt. Wenn ich aber den Befehl anders formuliere: "Stell Licht auf 20" zum Beispiel, funktioniert alles einwandfrei.

**Comment by thkl** [comment]
Das ist aber ein HomeKit Problem. Ich kann nicht unterscheiden, ob die Änderung von Siri oder einer HomeKit App kommt.

**Comment by thkl** [comment]
so 0.0.45 ist raus, das mit den Dimmern kann mal probiert werden. Sollte jetzt besser funktionieren.

**Comment by thoduh** [comment]
Also bei mir funktioniert es erst, nachdem ich das Licht einmal eingeschaltet und ausgeschaltet habe.
Bei "Siri, schalt das Licht ein", sagt Sie ist eigeschaltet, was aber nicht stimmt.
Ist aber OK so, vielen Dank...
