### ISSUE TITLE
iOS13.2 ... HM Alarmsirene (HM-Sec-Sir-WM) ... keine Notifications mehr ?!?!??!

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#471]
@thkl 

Hi Thomas
Seit iOS 13.2 bekomme ich von der Sirene keine Notifications mehr bei Änderung (aktiviert, deaktiviert, zuhause, etc.) ..... liegt das an iOS oder am Plug-In ? Hast du zufällig so eine Sirene ?

lg Richard

**Comment by timwegenerDE** [comment]
Hallo Richard,

benutzt du ein Apple TV als Steuerzentrale? Es gab bei tvOS 13.2 einige Probleme. Es steht aber ein Beta Update auf 13.2.1 zur Verfügung. Das könntest du mal versuchen.

**Comment by roe1974** [comment]
Ja ATV ist Steuerzentrale .... verwende tvos 13.3
ist aber nur die sirene ... alle anderen notifications kommen ....
