### ISSUE TITLE
Wechsel von CCU2 auf CCU3 - funktioniert nur mit Beta v0.1.2

### ISSUE THREAD

**Issue by Tonitom** [thkl/homebridge-homematic#473]
Hallo, 
nach upgrade von CCU2 auf CCU3 hat bei mir das Homematic Plugin nicht mehr funktioniert. Inzwischen habe ich die Beta v0.1.2 installiert und das Plugin läuft wieder, bekomme aber folgende Meldungen.

Homebridge läuft auf Docker von oznu.

Die Fehlermeldung hat anscheinend  keine Auswirkungen, wäre aber trotzdem schön wenn ich sie irgendwie weg bekommen könnte.

    [11/16/2019, 11:58:34 AM] [ccu3-webui] { Error: Command failed: npm view homebridge-        homematic version
    npm ERR! cb() never called!

    npm ERR! This is an error with npm itself. Please report this error at:
    npm ERR!     <https://npm.community>

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    killed: false,
    code: 1,
    signal: null,
    cmd: 'npm view homebridge-homematic version' }

Gruß
Tonitom

**Comment by CameronVIE** [comment]
Hallo Tonitom,
hab mir auch die CCU3 besorgt - aktuell läuft auf 3.51.6.
Leider finde ich die BETA, wie von dir erwähnt, nicht. 
Kannst du mir bitte nen Tip geben, woher ich die bekomme und wie sind Deine Erfahrungen beim Steuern deiner HomeMatic Umgebung mittels Apple Home?
Vielen Dank, liebe Grüsse and STAY HEALTHY
Mario

**Comment by Tonitom** [comment]
Hallo Mario,
in der Zwischenzeit hat sich einiges getan und in der Nummerierung gab es einen Sprung. Ich hab heute die aktuelle Version v0.0.219 installiert. 

Ich bin immer noch begeistert, wobei ich häufiger den Google Sprachassistent (über Homebridge) benutze als das Homekit, es funktioniert aber beides gut und sehr zuverlässig.

Ich hab mir aber einen AppleTV gegönnt als Homekit Zentrale, das iPad war nicht so zuverlässig.

Was ist das Problem, vielleicht kann ich helfen.

Gruß
Tonitom
