### ISSUE TITLE
Homematic IP

### ISSUE THREAD

**Issue by Huberhorn** [thkl/homebridge-homematic#475]
Hallo, vielleicht erscheint einigen von euch die Frage als äußerst blöd, aber ich bin ziemlich neu in dem Skripting/Homebridge Bereich. Demnach sorry für die vielleicht blöde Frage:
Wir haben einen Homematic IP Access Point. Wie kriege ich den über das Plugin zu der Homebridge? 
Über das Plugin, welches ich schon installiert habe, ja. So weit so gut. Dann in der config.jasn die Plattform ergänzen und die Werte austauschen. Aber woher bekomme ich die Channel-Werte des Accesspoints?
Vielen Dank für eure Hilfe im Voraus!
Hans

**Comment by dkrizic** [comment]
Ich glaube das funktioniert nur mit einer CCU, nicht mit dem Access Point

**Comment by thkl** [comment]
Korrekt
