### ISSUE TITLE
Keymatic Status teilweise  falsch

### ISSUE THREAD

**Issue by Apollon77** [thkl/homebridge-homematic#48]
Meine Keymatic wird teilweise als "ungesichert" angezeigt obwohl abgeschlossen und anders herum. Manchmal stimmt es aber auch. Irgendeine Idee? Gibt es was wie ich den Grund rausfinden kann?

Ansonsten hat meine Homekit-App noch einen Türstatus mit bei der Keymatic der immer falsch ist. Wie kann man denn da nen Sensor zuordnen?

**Comment by thoduh** [comment]
Benutze auch die Keymatic, wird bei mir aber immer richtig angezeigt.
Evtl. eine neue Referenzfahrt machen?

Den zweiten Satz versteh ich nicht :)

**Comment by Apollon77** [comment]
Status: ich beobachte es mal weiter

zweiter Satz: Ich nutze die Eve-App und da hat das Keymatic Gerät in der ANzeige quasi zwei zeilen. Einmal "Schloss" und direkt darunter mit weissem Hintergrund (so wie bei Temperatursensoren immer der zweite Wert)noch "Tür". Da steht immer "Geschlossen" ... die Keymatic kann das ja auch nicht wissen ...
Jetzt besser verständlich?

**Comment by thkl** [comment]
zum zweiten Satz. Ja das ist so. Hintergrund ist folgender. Das Keymatic Gerät setzt sich aus 2 Services zusammen. Einmal das elektrische Schloss. Dieses kennt in Homekit den Zustand offen und geschlossen.  Die Funktion der KM, die Tür zu öffnen kennt Homekit nicht. Deswegen habe ich da etwas getrickst. Dieser Button (Homekit TargetDoorState) sendet den Öffnen Befehl zur KM. Aber der kennt ja keine Rückmeldung. Deswegen ist der immer auf "geschlossen"

**Comment by Apollon77** [comment]
Aaaahhhhh ... vllt könnte man ja per Konfig einen Türsensor noch mit dran hängen, dann könntest DU da einen Statut "geöffnet" herbekommen? :-)

**Comment by thkl** [comment]
Könnte man dann über einen Custom ServiceClass abwickeln.

**Comment by bpohvoodoo** [comment]
Kann man nicht irgendwie die beiden channels über eine config kombinieren und so ein gerät draus zaubern?

**Comment by bpohvoodoo** [comment]
> Kombinieren geht nur über einen eigenen Service. Also quasi ein eigenes js File was das beides abwickelt. ZB der RGB Controller hat sowas. 

Ja aber man muss ja die entsprechenden Seriennummern der Aktoren verknüpfen, beim RGW ist das ja dieselbe.

**Comment by bpohvoodoo** [comment]
@thkl 
Hast du eventuell eine andere Idee, wie man die so verknüpfen könnte?

**Comment by dkrizic** [comment]
Ich arbeite an der gleichen Lösung, allerdings klappt es nicht ganz:

https://github.com/thkl/homebridge-homematic/issues/167
