### ISSUE TITLE
Service for HmIP-SWD unavailable

### ISSUE THREAD

**Issue by psdl** [thkl/homebridge-homematic#480]
Hallo,

ich erhalte in meinem LOG folgende Fehlermeldung. Vernutlich gibt es das Homematic Device "Wassersensor" HmIP-SWD noch nicht.

There is no service for HmIP-SWD:WATER_DETECTION_TRANSMITTER

---------

Danke noch einmal für die tolle Software... :)

**Comment by Soilman82** [comment]
Steht auf jeden Fall inzwischen in der channel_config.json drin.

**Comment by psdl** [comment]
Heisst das, ich muss ein "SPECIAL-SWITCH" dafür anlegen, dass ich ihn in Homekit sehe ?
