### ISSUE TITLE
HM-Sec-Sir-WM (HomeMaticHomeKitSecuritySystem.js) ..... wieder mal ;-)

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#481]
@thkl 
Hi Thomas !

Ich komme wieder mal mit der HomeMaticHomeKitSecuritySystem.js zu Dir.
Meine letzte Version von Dir (Siehe Anhang) funktioniert perfekt wenn die Sirene von der CCU gesetzt wird.
Ich habe aber jetzt einiges umgestellt und aktiviere die Sirene in HK.
Da habe ich das Problem, dass bei "Nacht" und "Abwesend" in HK sobald ich das aktiviere als Status immer "aktivieren....." bleibt .... egal ob ich den Raum wechsle oder die Home App abschiesse und neu starte. Wie gesagt, über die CCU aktiviert ist alles OK

Kannst Du die das nochmal ansehen ? .... wäre mir eine ordentliche Spende wert !

lg Richard
[HomeMaticHomeKitSecuritySystem.zip](https://github.com/thkl/homebridge-homematic/files/4014193/HomeMaticHomeKitSecuritySystem.zip)

**Comment by thkl** [comment]
Ich kann das Problem nicht so ganz nachstellen.
Ich habe eine HM-Sec-Sir-WM an einer TestCCU. Kanal 4 wird über das Homekit Gewerk an Homebridge geleitet. Dort taucht es als AlarmSystem auf.

Folgendes Verhalten auf dem Testsystem:

CCU Bedienung:
Alarm Aus -> Gerät in der HomeApp geht auf Off
Alarm ext -> Away
Alarm int -> Night

Ios HomeApp : 
Home -> CCU: Alarm Blockiert
Away -> CCU: ext. scharf
Night-> CCU: intern scharf
Off -> CCU: Alarm aus

Die Schaltzustände bleiben nicht in Target!=Current (also wird aktiviert) hängen sondern werden so geschalten.

Das Service File (HomeMaticHomeKitSecuritySystem.js ) welches benutzt wird ist dieses https://github.com/thkl/homebridge-homematic/blob/develop/ChannelServices/HomeMaticHomeKitSecuritySystem.js

**Comment by roe1974** [comment]
auch wenn du den zustand in HK änderst auf zB "Nacht".... dann die app abschiesst ... wieder öffnest ... dann bleibt der Status richtig und es kommt nicht "aktivieren ..." ?

Probiere gleich die version von oben ... wenn die geht kommt trotzdem spende :-)

**Comment by roe1974** [comment]
@thkl:
Die sieht gut aus bis auf das dein Mapping nicht stimmt:
es sollte sein:

Ios HomeApp :
Home -> CCU: Alarm **aus**
Away -> CCU: ext. scharf
Night-> CCU: intern scharf
Off -> CCU: Alarm **blockiert**

CCU Bedienung:
Alarm Aus -> Gerät in der HomeApp geht auf **Zuhause**
Alarm ext -> Away
Alarm int -> Night

Hintergund: bei blockiert reagiert die Sirene zu Hause auch nicht mehr auf den Panik Taster .... deswegen kann der modus auch nihct in der CCU geschaltet werden....

geht das zum umdrehen ?

**Comment by roe1974** [comment]
@thkl 
ist der spenden knopf noch aktuell ?
nicht dass die kohle wo falsch hingeht ;)
lg richard

**Comment by thkl** [comment]
> @thkl:
> Die sieht gut aus bis auf das dein Mapping nicht stimmt:
> es sollte sein:
> 
> Ios HomeApp :
> Home -> CCU: Alarm **aus**
> Away -> CCU: ext. scharf
> Night-> CCU: intern scharf
> Off -> CCU: Alarm **blockiert**
> 
> CCU Bedienung:
> Alarm Aus -> Gerät in der HomeApp geht auf **Zuhause**
> Alarm ext -> Away
> Alarm int -> Night
> 
> Hintergund: bei blockiert reagiert die Sirene zu Hause auch nicht mehr auf den Panik Taster .... deswegen kann der modus auch nihct in der CCU geschaltet werden....
> 
> geht das zum umdrehen ?

ja siehe https://github.com/thkl/homebridge-homematic/commit/551c03c0f6c66b1a0dcb70b996e6ee3cb2767aaa

**Comment by thkl** [comment]
> @thkl
> ist der spenden knopf noch aktuell ?
> nicht dass die kohle wo falsch hingeht ;)
> lg richard

ja

**Comment by roe1974** [comment]
passt kommt gleich :)
wie komme ich zum richtigen file ? kenne mich mit patchen nicht aus ?

**Comment by roe1974** [comment]
ah habs :-)

**Comment by thkl** [comment]
> passt kommt gleich :)

BTW: Leitest Du Deine Spende bitte an eine Hilfsorganisation Deiner Wahl um ..

> wie komme ich zum richtigen file ? kenne mich mit patchen nicht aus ?
Das File einfach als ganzes noch mal laden.

**Comment by roe1974** [comment]
zu spät ... spende ist raus .... ich überlasse es Dir wohin du es weiterleitest ;-)
DANKE !!! ich teste gleich

**Comment by thkl** [comment]
> zu spät ... spende ist raus .... ich überlasse es Dir wohin du es weiterleitest ;-)

Vielen Dank 1:1 weitergeleitet an https://www.aerzte-ohne-grenzen.de

**Comment by roe1974** [comment]
super ... finde ich toll !!!!

**Comment by roe1974** [comment]
@thkl 
Thomas eine Frage noch ... seit iOS 13 kommen bei der Sirene keine notifications mehr ... oder nur sporadisch ... ist das bei dir auch so ?
lg Richard

**Comment by thkl** [comment]
Also beim Test vorhin wegen des Umbaus der Funktion kam jedes Mal eine Notification von der HomeApp.  Was mit ziemlich auf den Nerv ging 😁

**Comment by roe1974** [comment]
ok ... werde das beobachten ... alle anderen notis kommen ... nur die sirene zickt :-p

**Comment by roe1974** [comment]
funktioniert perfekt !!!
auch die notis kommen wieder mit dieser version :)
vielen dank !!! ich mach das mal zu hier
