### ISSUE TITLE
Homematic Thermostat unter iOS 13.3 ... nur mehr Anzeige der eingestellten Temperatur ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#482]
@thkl 

Hallo Thomas
Seit iOS 13.x sehe ich im Thermostat nurmehr die eingestellt temperatur und "heizen auf..." .. in der Mitte sollte ein Schalter sein für "aus", "automatisch" und "heizen"
Muss hier etwas angepasst werden ?

lg Richard

**Comment by thkl** [comment]
Es gibt nur 2 Zustände für den Controlmode Aus und Heizen .. diese werden auch nur an Homekit übertragen. Deshalb gibt es dort nicht das Auswahlmenü für Off / Head / Cold / Auto .. sondern nur den orangenen Punkt. Das ist dann ein einfacher Toggle Switch

**Comment by krmkrx** [comment]
Vorschlag: Modus Heizen nutzen für manuelle Werte/Steuerung, Modus Automatisch in HomeKit nutzen für Zeitplanaktivierung. Aktuell habe ich das über die Programme gelöst was wenig elegant ist, zumal hier die „Nicht-Unterstützt“-Kacheln die Home-App etwas unordentlich machen. So könnte man etwas „nativer“ Automationen lösen wie: Fenster auf -> Heizung auf manuell und auf 10 Grad einstellen. Fenster zu -> Heizung auf Automatik stellen (hier soll dann der HomeMatic Zeitplan greifen.) Es wird entsprechen die Temperatur eingestellt die zur Uhrzeit vorgegeben ist. Die Ventilstellung sollte maßgeblich für den orangefarbenen Temperatur-Kreis der Kachel sein. Ventil geöffnet = orange, Ventil geschlossen = grün. So ist es bei allen nativen HomeKit Heizkörperthermostaten gelöst. Das würde die Heizungsintegration dieses Plugins wundervoll abrunden. Eine ähnliche Richtung geht das homebridge-Tado-Platform Plugin. Es bietet die o.g. Funktionalitäten. Der Ventilzustand wird hier zusätzlich sogar als custom HomeKit Service eingebunden und ist nur im Eve/Home+ sichtbar...

**Comment by thkl** [comment]
Head / Auto / Off könne man sicher lösen. Das Thema mit der Ventilanzeige ist nicht so einfach, da diese nur bei Heizungsventilen verfügbar ist. Normale Thermostate, die über den gleichen Service abgefrühstückt werden, haben diese Info nicht.

**Comment by roe1974** [comment]
Danke Thomas !!! .. kannst du dir das mit der Sirene nochmal ansehen #481 ... wäre mir eine ordentliche Spende wert :-)

**Comment by krmkrx** [comment]
Insofern ich irgendwie zur Implementierung von Heat/Auto/Off beitragen kann, mache ich das sehr gerne. Muss nur wissen wie.

**Comment by roe1974** [comment]
ja, heat/on/off wär geil ;-) ... kann lieder nichts dazu beitragen ausser zu testen ;-)
