### ISSUE TITLE
Jalousie wird in HK als "öffnen" angezeigt und nicht als "geöffnet" ... seit iOS 13.3

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#486]
@thkl 
Hallo Thomas

Seit iOS 13.3 werden meine Jalousien wenn Sie offen sind als "öffnen" angezeigt und nicht als "geöffnet" ,,, ist das ein iOS Problem oder muss etwas am channelservice geändert werden ?
Den verwende ich aktuell (Siehe Anhang)

lg Richard
[HomeMaticHomeKitBlindService.zip](https://github.com/thkl/homebridge-homematic/files/4049885/HomeMaticHomeKitBlindService.zip)

**Comment by thkl** [comment]
Was für ein Aktor Typ (HM-....) hängt dahinter ?

**Comment by roe1974** [comment]
Ein HM-LC-Ja1PBU-FM eingebunden in der config.json über:

                    "type": "HM-LC-Ja1PBU-FM:JALOUSIE",
                    "service": "HomeMaticHomeKitBlindService"

lg Richard

**Comment by roe1974** [comment]
![243F66FB-177E-4F2D-88B5-4A96C1C86A3B](https://user-images.githubusercontent.com/30420568/72220928-2e643480-3556-11ea-9a57-32c0cd381659.png)

bei 2% offen steht noch „geöffnet“ ... wenn ganz offen steht „öffnen“

**Comment by thkl** [comment]
ich habe mal im Dev Branch den HomeMaticHomeKitBlindService.js so angepasst, das beim Working=False Event das Level des Blinds noch mal abgefragt und in HK aktualisiert wird.
In Homekit sind die Geräte so lange auf opening closing etc wie target != current ist ...

**Comment by roe1974** [comment]
teste ich am abend und melde mich...

**Comment by JensBonse** [comment]
Hallo Thomas, könntest du dir ggf. auch mal den HomeMaticHomeKitWinMaticService.js service anschauen. Der hängt bei mir auch oft auf öffnen oder schließen fest, obwohl der Fenster entsprechend schon offen oder geschlossen ist.

**Comment by roe1974** [comment]
@thkl ..... keine Änderung ... ist glaube ich ein iOS 13 problem ... der Status erscheint ja final als "öffnen" ... es ist kein öffnen wie wenn er noch dabei wäre.....
@JensBonse .... probiere mal diese Version:
[HomeMaticHomeKitWinMaticService.zip](https://github.com/thkl/homebridge-homematic/files/4053775/HomeMaticHomeKitWinMaticService.zip)

**Comment by thkl** [comment]
Ich kann das leider nicht testen da ich Ikea Tradfri Blinds zwar an der CCU verwende aber diese nicht nach HomeKit gehen, da sie über ein extra Interface laufen.

**Comment by roe1974** [comment]
Aber die Ikea Tradfri gehen doch in HK ... nicht ?

**Comment by thkl** [comment]
Jo aber ich will die ja aus der CCU bzw HVL Script steuern

**Comment by roe1974** [comment]
ok wollte nur wissen ob die auch "falsch" dargestellt werden ... also "öffnen" statt "geöffnet" ... damit meine Vermutung bestätigt wird (iOS Übersetzungs Problem)

lg Richard

**Comment by thkl** [comment]
Jo geht leider nicht, denn das Gateway crasht wenn ich es in HomeKit einbinden möchte.

**Comment by roe1974** [comment]
ikea rocks 😜😜

**Comment by JensBonse** [comment]
@roe1974 Danke! Hab es eingespielt und sieht gut aus. Mal bis morgen warten. Lag es nur an den .bind(this) die fehlten? Hab es nur grob verglichen.

**Comment by roe1974** [comment]
ist eine version von thomas die er mal für mich umgebaut hat ...

**Comment by thkl** [comment]
Müsste so auch im dev branch liegen

**Comment by JensBonse** [comment]
@thkl Im dev scheint es nicht zu sein... und im master auch nicht. Wurde ggf. beim merge übersehen?

**Comment by thkl** [comment]
Hmm schau ich mir an

**Comment by Soilman82** [comment]
Bei mir werden zu 100% geöffnete Rollladen ebenfalls mit dem Status „öffnen“ in HomeKit angezeigt. Ist inzwischen bekannt ob es ein iOS Übersetzungsfehler ist oder am Plugin liegt?

**Comment by roe1974** [comment]
zu 99,99% ein Übersetzungsfehler von Apple ... habe ich in anderen Foren auch schon gelesen :(

**Comment by JensBonse** [comment]
@thkl  Kannst du bitte noch den Fix für die WinMatic einbauen? Hier oben im Thread hat @roe1974 die entsprechende Datei gepostet. Ist in der 0.212 noch nicht enthalten :(

**Comment by thkl** [comment]
What echt ? Ok ich schau nach.

**Comment by thkl** [comment]
Hmm wenn ich die Files vergleiche, matchen die aber ?

**Comment by thkl** [comment]
https://github.com/thkl/homebridge-homematic/commit/e97c9d9187aa3d85d7b050e0d5d6220db6603b5b sollte das fixen. 
Ich bin über das Cache gestolpert

**Comment by roe1974** [comment]
machst noch eine 213er ? ... bevor ich loslege ... oder manuell ändern ? ;-)

**Comment by thkl** [comment]
so, das sollte jetzt sowohl beim Dimmer, Blinds und Winmatic funktioniere.
Haben wir noch Geräte die ihren Zustand über längere Zeit ändern ?

**Comment by roe1974** [comment]
Fallen mir jetzt keine mehr ein .....;-)

**Comment by Soilman82** [comment]
Wie sieht es mit der KeyMatic aus? Habe keine aber da öffnet oder schließt doch das Schloss auch ne Weile.

**Comment by roe1974** [comment]
@Soilman82 .... stimmt ... habe ich vergessen da ich nuki verwende ;-)

**Comment by thkl** [comment]
Ja, aber die hat nur einen STATE Datenpunkt und kein LEVEL was sich langsam ändert.
Der State wechselt von einem auf den anderen

**Comment by roe1974** [comment]
ok :) ... machst du eine 213er ? ;)
lg richard

**Comment by thkl** [comment]
214 done :)

**Comment by roe1974** [comment]
cool ... upgrade mache ich morgen ... wenn heute abend was schief geht dann habe ich probleme mit der Chefin 😜😜😜

**Comment by thkl** [comment]
Es ist überall das Gleiche 👻

**Comment by JensBonse** [comment]
Habe 214 drauf, doch leider hängt mein Fenster laut HomeKit im 'Schließen...' oder im 'Wird geöffnet...' Modus.
Wenn ich im 'Schließen' Modus drauf klicke, wird es geöffnet, so wie es sein sollte. Bleibt dann aber im Modus 'Wird geöffnet'.
Wenn ich im 'Wird geöffnet' Modus drauf klicke, wird es zwar geschlossen, aber nicht verriegelt.

@roe1974 Kannst du das bestätigen?

**Comment by roe1974** [comment]
@JensBonse 
kann ich nicht bestätigen ... die winmatic funktioniert 1a !

**Comment by thkl** [comment]
kann das dann hier zu gemacht werden ?

**Comment by roe1974** [comment]
yes :)

**Comment by roe1974** [comment]
heute steht die winmatic plötzlich auf „schließen ......“ .... obwohl geschlossen ... komisch hat die ganze zeit funktioniert ....  hmmmmm

**Comment by roe1974** [comment]
.... das ganze kam nachdem ich alle jalousien geöffnet habe ... da kam plötzlich auch „Antrieb Drehtür wurde geöffnet“ ... und seitdem steht es auf „schließen“ ?????

**Comment by roe1974** [comment]
.... das ganze kam nachdem ich alle jalousien geöffnet habe ... da kam plötzlich auch „Antrieb Drehtür wurde geöffnet“ ... und seitdem steht es auf „schließen“ .... noch einen neustart der homebridge passt alles ... und es kam die meldung „antrieb geschlossen“ ....

**Comment by thkl** [comment]
Welcher Aktortyp ist das denn. Ich vermute mal das gleiche wie auch auf den anderen Geräten das der mehrere Kanäle hat und dann die durcheinanderkommen ...  ?

**Comment by roe1974** [comment]
@thkl ... das ist eine winmatic ... denke nicht dass die mehr kanäle hat ... muss ich dann zu hause schauen ....

**Comment by roe1974** [comment]
@thkl  ... die winmatic hat nur einen Daten Kanal (WINMATIC) und einen Kanal (AKKU)

**Comment by roe1974** [comment]
Weiter in #547
