### ISSUE TITLE
Typ HM-ES-TX-WM Type meldet "Service is not a constructor"

### ISSUE THREAD

**Issue by CM-UH** [thkl/homebridge-homematic#488]
Ich habe einen Stromzähler HM-ES-TX-WM, wenn ich nun die "neue" Klasse aus Issue #175  integriere bekomme ich den Fehler "Service.PowerMeterService is not a constructor"

> [2020-1-9 19:25:47] [HomeMatic CCU3] if PONG is PONG CCU is alive
> [2020-1-9 19:25:49] TypeError: Service.PowerMeterService is not a constructor
> at HomeMaticHomeKitEnergyCounterService.createDeviceService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitEnergy CounterService.js:23:16)
> at HomeMaticHomeKitEnergyCounterService.HomeKitGenericService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericServic e.js:69:8)
> at new HomeMaticHomeKitEnergyCounterService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitEnergyCounterService.j s:8:47)
> at HomeMaticChannelLoader.loadChannelService (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:95:19)
> at /usr/local/lib/node_modules/homebridge-homematic/index.js:340:22
> at Array.map ()
> at /usr/local/lib/node_modules/homebridge-homematic/index.js:300:21
> at Array.map ()
> at HomeMaticPlatform.buildaccesories (/usr/local/lib/node_modules/homebridge-homematic/index.js:288:16)
> at /usr/local/lib/node_modules/homebridge-homematic/index.js:234:9
> at IncomingMessage. (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:43:9)
> at IncomingMessage.emit (events.js:208:15)
> at endReadableNT (_stream_readable.js:1161:12)
> at processTicksAndRejections (internal/process/task_queues.js:77:11)

Kannst du mir da bitte helfen, ich finde den Fehler einfach nicht :-(

**Comment by thkl** [comment]
immer noch in npm version 0.0.200 ?

**Comment by CM-UH** [comment]
Hi,
läuft!!
Ich hatte wohl doch nicht alle Dateien auf den Raspi kopiert. War scheinbar halb 109 und halb aktuell.
Habe heute den kompletten Master nochmal neu übertragen.
Jetzt läuft das!
Vielen Dank für das tolle Plugin!
