### ISSUE TITLE
Heizkörperthermostat ... Boost Mode ?!

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#489]
@thkl 
Hi Thomas

Eine kurze Frage..... da ich bei einem Heizkörperthermostat immer nur den Boost Modus verwende für 20min (1x am Tag) .... Wenn der aktiv ist bleibt es in HK trotzdem auf "aus" ... 
Könntest Du, habe das bei redmatic gesehen, einen "Boost-Switch" pro Thermostat einbauen ?
Idealerweise noch in der config.json pro gerät aktivierbar ? ;-)

lg RIchard

**Comment by pbksol** [comment]
HomeKit sieht das als Status/Steuerung nicht vor. Daher wird das wohl eher nichts, solange es keine entsprechende Erweiterung von Apple dafür gibt.

**Comment by Soilman82** [comment]
Ich denke @roe1974 meint einen separaten Schalter für den Boost in HomeKit. Also zusätzlich zur eigentlichen Temperatursteuerung.

**Comment by superbraz** [comment]
könnte man evtl. als variable erstellen und diese dann triggern, um den status abzufragen!?
habe ich zB. mit einer variable so, wo ich das Licht für 5min einschalte, wogegen der eigentliche Schalter das Licht für 3h schaltet.

**Comment by pbksol** [comment]
> Ich denke @roe1974 meint einen separaten Schalter für den Boost in HomeKit. Also zusätzlich zur eigentlichen Temperatursteuerung.

Das kann man doch einfach über eine Variable, einen Schalter in HomeKit und dann einem Reset der Variable bei Ende des Boost realisieren.

**Comment by thkl** [comment]
![Image](https://i.imgur.com/MNZrdvR.jpg)

Bin dran 😁

**Comment by roe1974** [comment]
ahhhhhhh .... coooool

**Comment by xxxchris** [comment]
Hi,
hab eben aktualisiert auf der "Rollback" Version. War vorher glücklicherweise noch nicht auf der problematischen Version. 
Ist die Implementierung des Boost Modes noch enthalten in der 1.231 und wenn ja, wie bekomme ich den Boost-Schalter an die Thermostate?
Beste Grüße und Danke für die ganze Arbeit hier.

**Comment by thkl** [comment]
Nein, aber die kommt wieder 🤓

**Comment by xxxchris** [comment]
i.O., gut jetzt startet eh langsam der Sommer. Merci
