### ISSUE TITLE
Rotary Sensors (Griff-Status Sensoren) besser anzeigen

### ISSUE THREAD

**Issue by Apollon77** [thkl/homebridge-homematic#49]
Ich habe Griffsensoren an einigen Fenstern und wenn ich die nochmal einsetzte steht da nur "JA" und "NEIN".
Wenn ich die als "doors" bzw "windows" konfiguriere sieht es plötzlich so aus als ob es eine WInmatic wäre oder so ... Ist das Absicht?
Ist eine Anzeige mit "Offen", Gekippt", "geschlossen" nicht möglich?

**Comment by Baenker** [comment]
Apple kennt leider nur motorisierte Fenster. Deshalb ist es Absicht.

Du solltest die Sensoren deshalb als door oder windows in der config.json einbinden

**Comment by Apollon77** [comment]
Ok, dann lass ichs so und muss mal schauen wie ich die Ansicht besser hinbekomme ...
