### ISSUE TITLE
Update Package on npmjs.com

### ISSUE THREAD

**Issue by Soilman82** [thkl/homebridge-homematic#490]
Hallo Thorsten, 

an dieser Stelle erst mal Danke für dein Plugin! Ich hoffe ich stelle meine Frage/Bitte hier an der richtigen Stelle. 

Ich nutze für Homebridge zur Konfiguration das Homebridge Config UI X (https://www.npmjs.com/package/homebridge-config-ui-x). Damit ist es recht einfach die Homebridge zu aktualisieren und zu konfigurieren. Deshalb würde ich mich sehr freuen, wenn du die Version auf npmjs.com einmal aktualisieren könntest, damit ich darüber die aktuelle Version ziehen kann. 

Vielen Dank und viele Grüße
Michael

**Comment by thkl** [comment]
done

**Comment by Soilman82** [comment]
Und mir ist jetzt erst aufgefallen, dass ich Thorsten statt Thomas geschrieben habe. 🤭🙈
