### ISSUE TITLE
Hoobs Crashs when Homematic plugin is installed

### ISSUE THREAD

**Issue by xunreal75** [thkl/homebridge-homematic#492]
Hoobs crashs very often after install plugin and variables from Homematic are very slow or not transmitted.
In Home-App is appliance not answering shown.

**Comment by thkl** [comment]
i dont know "hoobs", so i am not able to comment on this issue.
Variables are generating no event on the ccu logic layer. There is a workaround:https://github.com/thkl/homebridge-homematic/wiki/Variablen

**Comment by MikeDeltaHH** [comment]
I have the same problem after migrating from homebridge to hoobs but think the problem is hoobs and not the plugin - running an homebridge virtual machine for these plugins doens´t work with hoobs and my config runs without problems on homebridge!

**Comment by xunreal75** [comment]
Hi

Hops is from https://hoobs.org <https://hoobs.org/>
And your plugin is available for hoobs.
It looks great.
I’ll try tu debug ist, but I hadn’t time to Create a debugable Instance. I tried Ellipse .
Whats your favourite developenttool.

Thanks

**Comment by thkl** [comment]
Hmm are there any logs you can provide ? Otherwise I am not able to look into that issue.
