### ISSUE TITLE
Steckdosen HMIP-PS zeigen falschen Status (per Home-App anders als per Wandtaster)

### ISSUE THREAD

**Issue by j-p-l** [thkl/homebridge-homematic#495]
Meine IP-Steckdosen HMIP-PS zeigen nicht immer den richtigen Status an. 
1. Wenn ich die Steckdosen über den direktverknüpften Wandtaster schalte (oder per script), sehe ich die Statusänderung in der Home-App sofort. Schließe ich die Home-App und öffne sie wieder, ist der Status auf "OFF", obwohl die Steckdose noch an ist. 
2. Schlte ich die Steckdose aber über die Home-App direk an, wird der Status länger richtig angezeigt (auch bei schließen der Home-App), stellt sich aber nach einer Zeit ebenflls auf "OFF".

Das Ganze ist also fast wie in diesem Ticket: https://github.com/thkl/homebridge-homematic/issues/376 
Ich habe es aber auch schon ohne den Cache versucht, was leider nichts ändert. 

Hat einer von euch eine Idee?

**Comment by superbraz** [comment]
hier ebenso...
denke irgendwas haut mit der übermittlung der status nicht - ist ja beim Ticket [#496](https://github.com/thkl/homebridge-homematic/issues/496) auch so, dass der Status nicht stimmt.

**Comment by thkl** [comment]
Klingt nach einem fehlerhaften .get .. ich schau mal

**Comment by j-p-l** [comment]
Funktioniert, vielen Dank!

**Comment by gecko74** [comment]
Hallo. 
Bin auf 205 und meine Hm-IP-PSM Steckdosen zeigen leider immer noch nicht den richtigen Status an.

**Comment by superbraz** [comment]
> 
> 
> Hallo.
> Bin auf 205 und meine Hm-IP-PSM Steckdosen zeigen leider immer noch nicht den richtigen Status an.

wollte gerade wieder von der 109 auf 205....da hast du mir aber in letzter sekunde den Mut genommen ^^
