### ISSUE TITLE
Garagedoor opener zeigt immer geöffnet an

### ISSUE THREAD

**Issue by fighterzg6** [thkl/homebridge-homematic#496]
Wie schon gesagt,nach dem Update zeigt er meine Garagentore als offen an. Downgrade zur Version 0.0.109 und es funktioniert wieder!

**Comment by superbraz** [comment]
hier genau das gleiche...
Hoftor und Garagentor stehen auf "geöffnet"...
beide Sensoren sind HmIP Geräte (SCI sowie SWDO)

**Comment by ChrWi** [comment]
Same here nach dem Update auf die 201. Ich nutze das Garagentor mit HM-LC-Sw1-Pl-CT-R1 als Aktor und HMIP-SWDO als Sensor. Homematic meldet beim Sensor "Closed", aber Homebridge meldet "Open".

**Comment by fighterzg6** [comment]
das gleiche auch bei version 0.0.201

**Comment by allesistmoeglichoderauchnicht** [comment]
das selbe Problem habe ich auch beim "HmIP-MOD-HO". Wenn ich hier dann "Siri öffne Tor" sage, dann öffnet SIRI die Garage und schließt sie dann wieder...

**Comment by thkl** [comment]
Kurze Frage: bei dem falschen Status, werden da HMIP Kontakte oder HM (ohne IP) Kontakte genutzt? .. Ich habe beim Fix für  #495 ein komisches Verhalten bei der Eventrückmeldung vom HMIP Interface.

**Comment by ChrWi** [comment]
HmIP-SWDO

[iOS]

**Comment by thkl** [comment]
Kann das mal bitte jemand mit dem geänderten File testen ?

**Comment by Sheldor81** [comment]
Bei mir das gleiche Problem mit dem Garagentor und dem HMIP Öffnungsmelder.

**Comment by ChrWi** [comment]
@thkl ich bemerke mit dem geänderten File keinen Unterschied. 
Habe allerdings im journal folgende Zeilen gefunden (mit original 202 und dem geänderten):

`Jan 23 22:45:32 raspberrypi4 homebridge[6423]: [1/23/2020, 22:45:32] [CCU3] Address not given undefined,HomeMaticHomeKitGarageDoorService {
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   name: 'Garagentor',
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   displayName: 'Garagentor',
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   type: 'HM-THKL-GARAGEDOOR',
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   deviceType: 'HM-THKL-GARAGEDOOR',
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   adress: '',
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   deviceAdress: undefined,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   log: [Function],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   platform: [HomeMaticPlatform],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   state: [],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   eventupdate: false,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   special: '',
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   currentStateCharacteristic: [],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   datapointMappings: [],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   timer: [],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   services: [Array],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   usecache: false,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   cadress: undefined,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   cfg: [Object],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   isWorking: false,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   ignoreWorking: false,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   myDataPointName: undefined,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   i_characteristic: {},
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   intf: undefined,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   datapointvaluefactors: {},
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   readOnly: false,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   lowBat: false,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   lowBatCharacteristic: undefined,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   accessoryName: 'Garagentor',
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   tampered: false,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   tamperedCharacteristic: undefined,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   delayOnSet: 0,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   runsInTestMode: false,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   persistentStates: {},
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   characteristic: [Function],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   address_sensor_close: 'HmIP-RF.0000DA498D137D:1.STATE',
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   address_sensor_open: undefined,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   state_sensor_close: 0,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   state_sensor_open: true,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   address_actor_open: 'BidCos-RF.OEQ1014747:1.STATE',
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   address_actor_close: undefined,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   delay_actor_open: 5,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   delay_actor_close: 5,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   message_actor_open: [Object],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   message_actor_close: [Object],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   sensor_requery_time: 20,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   targetCommand: false,
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   obstacle: [Characteristic],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   currentDoorState: [Characteristic],
Jan 23 22:45:32 raspberrypi4 homebridge[6423]:   targetDoorState: [Characteristic]
Jan 23 22:45:32 raspberrypi4 homebridge[6423]: },undefined`

Bin noch Beginner in diesem Thema - aber da ist im Vergleich zur 109 sehr viel "undefined" gelistet.

**Comment by Sheldor81** [comment]
kann man einfach auf die 109 downgraden?

**Comment by fighterzg6** [comment]
Ja kann man.
Ich benutze Homematic ohne ip

**Comment by Sheldor81** [comment]
Mit der 109 konnte ich kein Gerät mehr steuern, mit den nachfolgenden Versionen hat ein Schaltprozess mehrere Sekunden gedauert. Jetzt bin ich wieder bei der 202 da läuft alles bis auf den falschen Garagentor Status.

**Comment by fighterzg6** [comment]
Wenn du auf 109 zurück gehst Must du noch die HomeMaticRPC.js bearbeiten, hatte ich vergessen zu erwähnen

**Comment by Sheldor81** [comment]
Stimmt da war doch mal was, hatte ich total vergessen. Vielen Dank jetzt läuft wieder alles mit der 109

**Comment by thkl** [comment]
Das bringt ja nun für den Bugfix der aktuellen Version nichts.

**Comment by ChrWi** [comment]
Ich werde mich heute abend mit den Themen beschäftigen. Habe bemerkt, dass die HM Variable „Garagedoor_State“ wie festgeklebt auf Open bleibt - nur beim Neustart der CCU kurz auf „Opening“.
Zum Zeitpunkt CCU2 und 109 war alles ok. Dann bin ich auf die CCU3 und Homekit machte alles wie gewünscht. Habe aber die HM Variable nicht mehr geprüft, bevor ich auf die 202 bin => zumindest bei mir gibt es offensichtlich mehrere Punkte zu klären. 

[iOS]

**Comment by thkl** [comment]
Es gibt ne Variable für den Zustand ?

**Comment by superbraz** [comment]
> Es gibt ne Variable für den Zustand ?

Mir auch nicht bekannt...
Ein state vom Sensor
In der CCU stimmt der Status

**Comment by thkl** [comment]
Ja ich werde, analog der Schaltaktor Sache die Daten nicht aus dem EventCache nehmen sondern neu abfragen.

**Comment by fighterzg6** [comment]
also bei version 0.0.202 zeigt er erst offen an, dann kurz geschlossen und dann wieder offen.

**Comment by thkl** [comment]
ok ich bin dem Fehler auf der Spur. Ich habe mal einen Workaround eingebaut, der im Test funktioniert. Der eigentliche Fix ist ein bissel aufwändiger. Aber dafür dann generisch.

**Comment by ChrWi** [comment]
> Es gibt ne Variable für den Zustand ?

Ja. Habe in HM eine Variable (Boolean) für Target (Open/Closed) und eine für State (Open, Opening, Closed, Closing, Stopped). Dann über ein Programm definiert, wie der Status sich abhängig vom Target ergibt:
-> Wenn Target = Open dann Status sofort Opening, nach 16s Open (analog andere Richtung)

Im homebridge json steht dann nur das drin wie im Wiki von Dir als Beispiel beschrieben. 
Hat bisher prima funktionert.

Hatte diese Lösung von ca. 1 Jahr im HM Forum gefunden. Oder geht das alles ohne HM Variablen / Logik?

**Comment by thkl** [comment]
Ähm, ok .. aber der Garagenöffner kann doch direkt die Aktoren steuern ?

**Comment by ChrWi** [comment]
Hallo Thomas,
Homematic habe ich aufgeräumt - war noch ein Relikt aus der Zeit vor Homebridge.
Habe gerade die 203 installiert - ohne sichtbare Änderung. Das heißt, das Verhalten ist:

- In Homematic meldet der Sensor HmIP-SWDO korrekt „geschlossen“, wenn Tor zu. 
- In Homebridge sehe ich mit der 203 jetzt „geschlossen“ wenn zu bzw „Offen“ wenn offen.
- In Eve steht sowohl für den geschlossenen als auch offenen Zustand des Tors „Auf“. Betätigung in beiden Richtungen liefert „schließend“.
- In Homekit ist das Verhalten analog zu Eve - fast, da anstatt „Geöffnet“ nach einiger Zeit automatisch „wird geöffnet“ gemeldet wird. Bei Öffnen und Schließen des Tors kommt „schließen“, kurz vor dem Endpunkt ein „Wird geöffnet“, dann „Geöffnet“.

Hoffe das hilft. Oder sollmich noch irgendwelche Caches testweise löschen?

**Comment by thkl** [comment]
Ok ich gehe davon aus, der Garagentor Service läuft im "One Sensor Mode"
mit einem HmIP-SWDO (der liefert 0 wenn bedeckt[geschlossen] und 1 wenn offen) der so angebracht ist das er bedeckt ist wenn das Tor zu ist muss die config so aussehen:

```
{
  "name": "GarageOrWhatever",
  "type": "HM-THKL-GARAGEDOOR",
  "parameter": {
	"address_sensor_close": "HmIP-RF.12345456:1.STATE",
	"address_actor_open": "BidCos-RF.OEQ0015193:1.STATE",
	"message_actor_open": {
	  "on": true
        },
	"state_sensor_close": 0
   }
}
```

Adressen variieren natürlich ...

**Comment by ChrWi** [comment]
`{
                    "name": "Garagentor",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "address_sensor_close": "HmIP-RF.0000DA498D137D:1.STATE",
                        "state_sensor_close": 0,
                        "address_actor_open": "BidCos-RF.OEQ1014747:1.STATE",
                        "message_actor_open": {
                            "on": true,
                            "off": false
                        },
                        "sensor_requery_time": 20
                    } `

**Comment by thkl** [comment]
ok ich hab das jetzt noch mal als Testaufbau zusammengeklöppelt.
Stellt sich raus, ja der initiale Check läuft falsch. Ich hab es repariert.
204 kommt gleich

**Comment by thkl** [comment]
btw nach dem Start der homebridge dauert es 30sek bis das Garagentor zum ersten Mal abgefragt wird.

**Comment by ChrWi** [comment]
Hm, der initiale Status ist nun „Geschlossen“, der Status bei Bewegung passt auch. Nach Öffnen und Schließen des Tores ist das Verhalten von 204 und 203 zunächst identisch, sprich Geöffnet, obwohl das Tor bereits geschlossen ist. Nach einiger Zeit springt der Status dann korrekt auf „Geschlossen“. Sieht also insgesamt gut aus - herzlichen Dank!

**Comment by ChrWi** [comment]
Add-on: die sensor requery time von 20s hat offensichtlich keinen Bezug zum Statuswechsel. Lohnt sich hier ein anderer Wert?

**Comment by thkl** [comment]
Die sensor_requery_time dient zum Rücksetzen des Kommando Status. Sonst würde das Tor immer auf Öffnen oder Schließen anstatt Offen/Geschlossen stehen.
Normal steht der auf 30 Sekunden wenn nicht anders angegeben.

**Comment by thkl** [comment]
ich würde das dann hier mal zu machen wenn es wieder funktioniert

**Comment by Sheldor81** [comment]
bei mir läuft es jetzt auch wieder wie gewohnt. Vielen Dank!!!!

**Comment by fighterzg6** [comment]
Sorry aber bei mir ist alles unverändert! Zeigt immer offen an

**Comment by dkrizic** [comment]
Bei mir sieht es so aus:

Geschlossen

![image](https://user-images.githubusercontent.com/1181349/73125792-33d86a80-3fab-11ea-930d-e8ee14a27f34.png)

Beim Aufmachen:

![image](https://user-images.githubusercontent.com/1181349/73125797-46eb3a80-3fab-11ea-947c-32bc4b566d93.png)

Offen

![image](https://user-images.githubusercontent.com/1181349/73125801-54082980-3fab-11ea-81cf-6c02dab4fcd6.png)

Bei Schliessen

![image](https://user-images.githubusercontent.com/1181349/73125809-608c8200-3fab-11ea-8748-74ff6bec8836.png)

Nach einer Minute:

![image](https://user-images.githubusercontent.com/1181349/73125825-93367a80-3fab-11ea-9d17-38246461fda7.png)

Meine Konfiguration:

```
            "special": [
                {
                    "name" : "Garagentor 2",
                    "type" : "HM-THKL-GARAGEDOOR",
                    "parameter" : {
                        "address_sensor_close": "BidCos-RF.KEQ0803845:1.STATE",
                        "address_sensor_open": "BidCos-RF.KEQ0803845:1.STATE",
                        "state_sensor_close": false,
                        "state_sensor_open": true,
                        "address_actor_open": "BidCos-RF.LEQ0281557:4.STATE",
                        "message_actor_open": {"off":false,"on":true}
                    }
                }
            ],
```

Der Neigungssensor (KEQ0803845:1.STATE) liefert offenbar die richtigen Werte

**Comment by thkl** [comment]
Dafür gibts Messages im Debug Mode (homebridge mit -D starten)
Nach 30sek wird der initiale Query gemacht. Das schaut dann so aus:

```
[2020-1-25 16:06:38] [HomeMatic CCU] [GDS] One sensor mode. Fetching value for Close Sensor HmIP-RF.00109709AAA606:1.STATE
[2020-1-25 16:06:38] [HomeMatic CCU] platform getValue (HmIP-RF) HmIP-RF.00109709AAA606:1.STATE
[2020-1-25 16:06:38] [HomeMatic CCU] [GDS] get close value result is 0
[2020-1-25 16:06:38] [HomeMatic CCU] [GDS] values match close state
[2020-1-25 16:06:38] [HomeMatic CCU] [GDS] garage event HmIP-RF.00109709AAA606:1,STATE,0 Target Command State false
[2020-1-25 16:06:38] [HomeMatic CCU] [GDS] One Sensor Mode Close is 0
[2020-1-25 16:06:38] [HomeMatic CCU] [GDS] Close sensor is 0 set targetDoorState 1
```
get close value result is 0 -> der close sensor lieferte ein 0 an homebridge
das wäre dann der Wert der bei "state_sensor_close" in der config stehen müsste

**Comment by thkl** [comment]
@dkrizic in Deinem Falle existiert ja auch nur ein Sensor ... daher einfach address_sensor_open und state_sensor_open weg lassen ..

**Comment by dkrizic** [comment]
Im Log steht jetzt: 

```
[1/25/2020, 8:12:47 PM] [HomeMatic CCU] routing via rf xmlrpc
[1/25/2020, 8:12:47 PM] [HomeMatic CCU] XMLRpc setValue LEQ0281557:4 STATE true
[1/25/2020, 8:12:47 PM] [HomeMatic CCU] RPC setValue Call for LEQ0281557:4 STATE Value true Type boolean
[1/25/2020, 8:12:48 PM] [HomeMatic CCU] rpc <- system.multicall on BidCos-RF. (null)
[1/25/2020, 8:12:48 PM] [HomeMatic CCU] RPC event for BidCos-RF.LEQ0281557:4.STATE with value true
[1/25/2020, 8:12:48 PM] [HomeMatic CCU] RPC setValue (LEQ0281557:4 STATE) Response "" Errors: null
[1/25/2020, 8:12:48 PM] [HomeMatic CCU] fallback routing via rega
[1/25/2020, 8:12:48 PM] [HomeMatic CCU] rega.setvalue BidCos-RF.LEQ0281557:4.STATE true
[1/25/2020, 8:12:48 PM] [HomeMatic CCU] Rega SetValue true of BidCos-RF.LEQ0281557:4.STATE
[1/25/2020, 8:12:48 PM] [HomeMatic CCU] rpc <- system.multicall on BidCos-RF. (null)
[1/25/2020, 8:12:48 PM] [HomeMatic CCU] RPC event for BidCos-RF.LEQ0281557:4.WORKING with value false
[1/25/2020, 8:12:52 PM] [HomeMatic CCU] routing via rf xmlrpc
[1/25/2020, 8:12:52 PM] [HomeMatic CCU] XMLRpc setValue LEQ0281557:4 STATE false
[1/25/2020, 8:12:52 PM] [HomeMatic CCU] RPC setValue Call for LEQ0281557:4 STATE Value false Type boolean
[1/25/2020, 8:12:53 PM] [HomeMatic CCU] rpc <- system.multicall on BidCos-RF. (null)
[1/25/2020, 8:12:53 PM] [HomeMatic CCU] RPC event for BidCos-RF.LEQ0281557:4.STATE with value false
[1/25/2020, 8:12:53 PM] [HomeMatic CCU] RPC setValue (LEQ0281557:4 STATE) Response "" Errors: null
[1/25/2020, 8:12:53 PM] [HomeMatic CCU] fallback routing via rega
[1/25/2020, 8:12:53 PM] [HomeMatic CCU] rega.setvalue BidCos-RF.LEQ0281557:4.STATE false
[1/25/2020, 8:12:53 PM] [HomeMatic CCU] Rega SetValue false of BidCos-RF.LEQ0281557:4.STATE
[1/25/2020, 8:12:53 PM] [HomeMatic CCU] rpc <- system.multicall on BidCos-RF. (null)
[1/25/2020, 8:12:53 PM] [HomeMatic CCU] RPC event for BidCos-RF.LEQ0281557:4.WORKING with value false
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] rpc <- system.multicall on BidCos-RF. (null)
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] RPC event for BidCos-RF.KEQ0803845:1.STATE with value false
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] Accessory (Garage Neigungssensor) found -> Send Event with value false
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] Saving log data for Garage Neigungssensor: {"status":0,"time":1579979582}
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] **Fakegato-timer: addData  Garage Neigungssensor { status: 0, time: 1579979582 }  immediate:  true
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] **Fakegato-timer: executeImmediateCallback**
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] **Fakegato-timer callbackDoor:  Garage Neigungssensor , immediate:  true , entry:  { time: 1579979582, status: 0 }
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] First entry Garage Neigungssensor: 0
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] Last entry Garage Neigungssensor: c
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] Used memory Garage Neigungssensor: c
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] 116 Garage Neigungssensor: 781f00000000000046abdc2301 06010d00c00f00000000000000000101
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] ** Fakegato-storage write FS file: /homebridge/kube13_BidCos-RF.KEQ0803845:1_persist.json "firstEntry":0,"lastEntry":12,"usedMemory":12,"refTime":601664326,"initialTime":
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] [GDS] garage event BidCos-RF.KEQ0803845:1,STATE,false Target Command State true
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] [GDS] One Sensor Mode Close is false
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] rpc <- system.multicall on BidCos-RF. (null)
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] RPC event for BidCos-RF.KEQ0803845:1.LOWBAT with value false
[1/25/2020, 8:13:02 PM] [HomeMatic CCU] Accessory (Garage Neigungssensor) found -> Send Event with value false
[1/25/2020, 8:13:03 PM] [HomeMatic CCU] [GDS] timer fired close sensor is 1 set new current state 1
[1/25/2020, 8:13:16 PM] [HomeMatic CCU] rpc <- system.multicall on BidCos-RF. (null)
[1/25/2020, 8:13:16 PM] [HomeMatic CCU] RPC event for BidCos-RF.MEQ1651454:1.TEMPERATURE with value 21.7
[1/25/2020, 8:13:16 PM] [HomeMatic CCU] rpc <- system.multicall on BidCos-RF. (null)
[1/25/2020, 8:13:16 PM] [HomeMatic CCU] RPC event for BidCos-RF.MEQ1651454:1.HUMIDITY with value 29
```

und die Config ist

```
            "special": [ 
				{
					"name" : "Garagentor 2",
					"type" : "HM-THKL-GARAGEDOOR",
					"parameter" : {
						"address_sensor_close": "BidCos-RF.KEQ0803845:1.STATE",
						"state_sensor_close": false,
						"address_actor_open": "BidCos-RF.LEQ0281557:4.STATE",
						"message_actor_open": {"off":false,"on":true}
            		} 
				} 
			],
```

**Comment by thkl** [comment]
im log steht kein STATE Event .. nur irgendwas mit LowBat .. hab noch einen kleinen Bug drin. Der Init Timer wird dummerweise auch beim LowBat Event gekillt. Aber spätestens wenn das Tor einmal bewegt wird, sollte es stimmen

**Comment by thkl** [comment]
hab das mit dem Timer in 205 gefixt und es wird noch mehr Log ins Debug geschrieben ..

**Comment by fighterzg6** [comment]
auch bei version 0.0.205 zeigt es bei mir rgarage und einfahrt geöffnet an.

hier mal meine config.
 "special": [
                {
                    "name": "Garagentor",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "message_actor_open": {
                            "off": false,
                            "on": true
                        },
                        "state_sensor_close": 0,
                        "address_actor_open": "BidCos-RF.OEQ0182237:1.STATE",
                        "address_sensor_close": "BidCos-RF.OEQ2139339:1.STATE"
                    }
                },
                {
                    "name": "Einfahrt",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "state_sensor_close": 0,
                        "address_actor_open": "BidCos-RF.NEQ1631511:1.STATE",
                        "address_sensor_close": "BidCos-RF.MEQ0813289:1.STATE",
                        "delay_actor_close": 15,
                        "message_actor_open": {
                            "on": true
                        },
                        "sensor_requery_time": 15
                    }
                }
            ],

**Comment by Luftloch80** [comment]
Servus. Habe auch ein Update gemacht und nix an der config verändert. Bei mir ist auch das Tor immer offen. 


1/29/2020, 2:11:48 PM] [HomeMatic CCU] [GDS] garage door inital query ...
[1/29/2020, 2:11:48 PM] [HomeMatic CCU] platform getValue (BidCos-RF) BidCos-RF.LEQ0211035:1.STATE
[1/29/2020, 2:11:48 PM] [HomeMatic CCU] [GDS] result for close sensor false
[1/29/2020, 2:11:48 PM] [HomeMatic CCU] [GDS] garage event BidCos-RF.LEQ0211035:1,STATE,NaN Target Command State false
[1/29/2020, 2:11:48 PM] [HomeMatic CCU] [GDS] One Sensor Mode Close is 0
[1/29/2020, 2:11:48 PM] [HomeMatic CCU] [GDS] Close sensor hm value is NaN set targetDoorState 0
[1/29/2020, 2:11:49 PM] [HomeMatic CCU] [GDS] timer fired close sensor hm value is NaN set new current state 0

**Comment by thkl** [comment]
Problem ist das die HM Kontakte true/false und die HMIP Kontakte 1/0 liefern .. ich muss das noch anpassen.

**Comment by dkrizic** [comment]
Version 0.0.208 (rc/beta) feedback:

Mit diesen Einstellungen

```
        "special": [
          {
            "name" : "Garagentor",
            "type" : "HM-THKL-GARAGEDOOR",
            "parameter" : {
              "address_sensor_close": "BidCos-RF.KEQ0803845:1.STATE",
              "address_actor_open": "BidCos-RF.LEQ0281557:4.STATE",
              "state_sensor_close": false,
              "state_sensor_open": true 
            }
          }
        ],
 ```

funktioniert das Garagentor zuverlässig.

**Comment by thkl** [comment]
Danke für die Info.

**Comment by hillinator** [comment]
Ich konnte es auch erfolgreich testen!

**Comment by thkl** [comment]
Danke.  

Ich würde den RC dann heute noch releasen.

**Comment by ChrWi** [comment]
Hab mir gerade mal die letzte beta 210 installiert - das Garagentor lief noch nie besser auf Anhieb. besten dank!

**Comment by GrmpfNarf** [comment]
Moin zusammen,
bei mir läuft das leider noch nicht. 

````
{              
 "name": "Garage",
 "type": "HM-THKL-GARAGEDOOR",                    
 "parameter": {                       
    "address_actor_open": "BidCoS-RF.BidCoS-RF:3.PRESS_SHORT",                   
    "message_actor_open": {                            
        "on": true                       
     },                       
    "address_sensor_close": "CUxD.CUX4000002:1.STATE",                        
    "state_sensor_close": true                   
  }               
}
````
Der CuxD simuliert einen HM-LC-Sw1PBU-FM der über ein Programm getoggelt wird. Das Programm funktioniert auch. 
Ich hab das Problem das das Tor  initial immer „geschlossen“ anzeigt dann auf „öffnen“ geht und nach 30 Sekunden wieder zurück. 
Auch mit „state_sensor_open“: false selbes verhalten. 
Ich bin auf der 0.0.210. 
wenn jemand eine Idee hat schonmal vielen Dank.

**Comment by thkl** [comment]
Bitte einmal das debug log hier rein kippen.

**Comment by fighterzg6** [comment]
ich kann Seiler nicht auf 0.0.210 aktualisieren.
kommt immer Fehler
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ homebridge-homematic@0.0.210
updated 1 package and audited 3988 packages in 11.006s

2 packages are looking for funding
  run `npm fund` for details

found 15 vulnerabilities (11 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

hatte ich ja noch nie!

**Comment by thkl** [comment]
https://github.com/thkl/homebridge-homematic/issues/510#issuecomment-583102759

**Comment by fighterzg6** [comment]
alles klar, läuft jetzt. 
habe die werte der Sensoren von close 0 auf close false geändert und jetzt gehts
dankeschön

**Comment by GrmpfNarf** [comment]
> Bitte einmal das debug log hier rein kippen.

````
2020-2-8 14:18:52] [Homematic CCU] [GDS] garage door requery sensors ...
[2020-2-8 14:18:52] [Homematic CCU] [Generic] transformDatapoint CUxD.CUX4000002:1.STATE
[2020-2-8 14:18:52] [Homematic CCU] [Cache] remove :CUxD.CUX4000002:1.STATE
[2020-2-8 14:18:52] [Homematic CCU] [Core] getValue (CUxD) CUxD.CUX4000002:1.STATE
[2020-2-8 14:18:52] [Homematic CCU] [Core] check cache CUxD.CUX4000002:1.STATE
[2020-2-8 14:18:52] [Homematic CCU] [Cache] hit on CUxD.CUX4000002:1.STATE true
[2020-2-8 14:18:52] [Homematic CCU] [GDS] result for close sensor true
[2020-2-8 14:18:52] [Homematic CCU] [Generic] transformDatapoint STATE
[2020-2-8 14:18:52] [Homematic CCU] [Generic] cache .STATE (true)
[2020-2-8 14:18:52] [Homematic CCU] [GDS] garage event CH:CUxD.CUX4000002:1|DP:STATE|NV:true|TCS:false
[2020-2-8 14:18:52] [Homematic CCU] [GDS] One Sensor Mode Close is true
[2020-2-8 14:18:52] [Homematic CCU] [GDS] is sensor Close Event
[2020-2-8 14:18:52] [Homematic CCU] Check true (string) will match StateSensorClose true (boolean) - true
[2020-2-8 14:18:52] [Homematic CCU] [GDS] Close sensor hm value is true set targetDoorState 1
[2020-2-8 14:18:53] [Homematic CCU] [GDS] timer fired close sensor hm value is true set new current state 1

**Comment by in60-code** [comment]
Mit Version 0.0.212 und der folgenden Config funktioniert wieder alles einwandfrei!

`"special": [
          {
            "name" : "Garagentor",
            "type" : "HM-THKL-GARAGEDOOR",
            "parameter" : {
              "address_sensor_close": "BidCos-RF.KEQ0803845:1.STATE",
              "address_actor_open": "BidCos-RF.LEQ0281557:4.STATE",
              "state_sensor_close": false,
              "state_sensor_open": true 
            }
          }
        ],`

Vielen Dank!

**Comment by fighterzg6** [comment]
Auch die 0.0.212 funktioniert tadellos.
Mal ne blöde Frage, gibt es das auch für Gartentore?

**Comment by thkl** [comment]
HomeKit hat keine generischen Tore nur Garagen.  Aber wenn dich das nicht stört kannst du sicher das Gartentor als Garage einbinden.

**Comment by ChrWi** [comment]
Hallo Thomas, mit der finalen 212 habe ich nun das Problem, dass der sowohl der geschlossene als auch der geöffnete Zustand des Tors "geschlossen" anzeigt. Verrückt! Kann ich auf eine Beta Version zurückgehen?

**Comment by fighterzg6** [comment]
Garagentore funktionieren, aber meine Jalousien zeigen jetzt immer öffnen an?!?!?

**Comment by thkl** [comment]
Das ist hier im Github schon beseitigt.

**Comment by fighterzg6** [comment]
Bei Version 0.0.219 zeigt er mir jetzt bei geöffneten Tor geschlossen an?!

**Comment by ChrWi** [comment]
Ist bei mir leider auch so. Der Sensor im HM zeigt offen an, der Status in Homebridge aber geschlossen.

[iOS]

**Comment by thkl** [comment]
Debug log ?

**Comment by ChrWi** [comment]
Hat sich bei mir geklärt: mir ist aufgefallen, dass der cronjob, der die homebridge einmal täglich neu startet die homebridge offenbar nicht sauber hochfährt: errors im rega und damit keine erfolgreiche Rückmeldung der Status an die Homebridge. Nach manuellem Start keine Probleme, Homebridge und die aktuelle 219 laufen 1a bei mir!

**Comment by thkl** [comment]
Da trifft es sich ja, das ich gerade das ganze Plugin auseinander reiße und an ein moderneres homebridge API anpasse. 

Vorteil u.A.: Geräte können hinzugefügt werden, ohne das man homebridge neu starten muss.
Nachteil: Neue Bugs und Fehler ... ;o)

**Comment by ChrWi** [comment]
Was auch immer "modernes homebridge API" heißt - Respekt für Deine Arbeit & Motivation!
