### ISSUE TITLE
npm version 0.0.200 .... was ist neu ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#497]
@thkl 

Hi Thomas ... kannst Du sagen was die Änderungen in 0.0.200 sind ?
lg Richard

**Comment by roe1974** [comment]
@thkl 
Ich verwende ja noch ein index.js von Die die direkt mit der REGA "spricht" und nicht jedesmal alle Geräte abfragt ... ist das hier in der 0.0.200 auch so ?
lg Richard

**Comment by thkl** [comment]
200 entspricht dem Stand des Develop Trees

**Comment by roe1974** [comment]
ok, dh bezüglich der index.js was genau ? ;-)

**Comment by thkl** [comment]
Die Version fragt REGA und nicht die Schnittstelle

**Comment by roe1974** [comment]
super, DANKE !

**Comment by roe1974** [comment]
@thkl 

Thomas, zwei Fragen noch:
1. das funktioniert auch noch mit der neuen Version ?
https://github.com/thkl/homebridge-homematic/wiki/Flexiblere-Switch-Aktor-Darstellung

2. "type": "HM-LC-Ja1PBU-FM:JALOUSIE" ist jetzt in der channel_config.json enthalten ... dh kann ich rausnehmen aus meiner config.json ?

lg Richard

**Comment by thkl** [comment]
Ja

**Comment by roe1974** [comment]
thx ! :-)
