### ISSUE TITLE
There is no service for HM-LC-Bl1PBU-FM:BLIND

### ISSUE THREAD

**Issue by sohnkarlsruhe** [thkl/homebridge-homematic#498]
Die Meldung bekomme ich seit Update auf die 0.0.200. Mit 98 funktioniert es noch. 
Die Einträge mit Services habe ich noch hinzugefügt, da in einem anderen Issue dies geholfen hat. 
    {
            "platform": "HomeMatic",
            "name": "HomeMatic CCU",
            "enable_hmip":"true",
            "lcache": true,
            "ccu_ip": "192.168.0.107",
            "filter_device": [],

  "services": [
    { "type": "HmIP-BBL:BLIND_VIRTUAL_RECEIVER",
     "service": "HomeMaticHomeKitBlindSlatServiceIP"
     },
     { "type": "HmIP-FBL:BLIND_VIRTUAL_RECEIVER",
     "service": "HomeMaticHomeKitBlindSlatServiceIP"
     }],

            "filter_channel": [
                "BidCos-RF.KEQXXXXXXX:4",
                "BidCos-RF.LEQXXXXXXX:2"
 ],
            "outlets": [
                "BidCos-RF.KEQXXXXXXX:4",
                "BidCos-RF.IEQXXXXXXX:1"
            ],
            "doors": [],
            "programs": [],
            "subsection": "Homekit"
        }

**Comment by thkl** [comment]
Ich füge das Gerät noch in die cannelconfig dann sollte es gehen.

**Comment by sohnkarlsruhe** [comment]
danke für die schnell antwort, welchen Eintrag muss ich da hinzufügen?

**Comment by Soilman82** [comment]
Das dürfte eigentlich mit meinem Pull Request von gestern schon erledigt sein. Die Meldung hatte ich ebenfalls.

@thkl Das ist wahrscheinlich nur noch nicht in der npm Version gelandet oder?

**Comment by thkl** [comment]
Ja könnte sein, da der wegen eines fehlenden , im Travis auf den Poller gelaufen ist.

**Comment by kleinenbroicher** [comment]
Bitte verzeiht meine Anfänger-Frage ...
Bedeutet das, dass ich demnächst ein Update via Homebridge Config UI X einspielen kann, oder muss ich manuell etwas anstoßen? Danke!!!

**Comment by sohnkarlsruhe** [comment]
Habe dies eingefügt... jetzt gehts erst mal wieder 

 "services": [
  {
   "type": "HM-LC-Bl1PBU-FM:BLIND",
   "service": "HomeMaticHomeKitBlindService"
  },

**Comment by thkl** [comment]
👍
