### ISSUE TITLE
Request: Fenstergriffsensor HMIP-SRH - Ansicht in Homekit

### ISSUE THREAD

**Issue by MikeDeltaHH** [thkl/homebridge-homematic#499]
Nabend!

Erstmal ganz herzlichen Dank dass Du ein größeres Update gebracht hast, bei den HMIP-SWDO optischen Fensterkontakten sieht der neue Status jetzt mit der Historie richtig klasse aus - wäre es möglich dass mit den HMIP-SRH Fenstergriffsensoren auch so abzubilden? Da wird nur Kontakt Ja oder Nein angezeigt...

Viele Grüße!

**Comment by thkl** [comment]
ist der mit dem "alten" HM-Sec-RHS vergleichbar ?

**Comment by MikeDeltaHH** [comment]
Sollte, sieht fast genauso aus, nur etwas höher... den alten habe ich nicht eingesetzt, deshalb kann ich das nur anhand der Bilder sagen, aber das Funktionsprinzip ist glaub ich identisch - ich tausche grad nach und nach bei mir die optischen Kontakte gegen die Fenstergriffkontakte aus weil die einfach besser an den Fenstern aussehen und nicht so auffallen...

**Comment by thkl** [comment]
hmm laut doku hat der nen Kanal vom Typ ROTARY_HANDLE_TRANSCEIVER und den unterstütze ich schon ...

**Comment by MikeDeltaHH** [comment]
Hie rmal wie das aktuell aussieht in Eve... die ersten beiden sind Fenstergriffkontakte , der untere ist ein optischer Fensterkontakt...

![IMG_8240](https://user-images.githubusercontent.com/34737987/72753787-23e51300-3bc6-11ea-8808-9a52201fdf3b.PNG)

![IMG_8241](https://user-images.githubusercontent.com/34737987/72753840-4d9e3a00-3bc6-11ea-9e70-ab01a1328698.PNG)

![IMG_8242](https://user-images.githubusercontent.com/34737987/72753843-51ca5780-3bc6-11ea-9097-bc15df508fd2.PNG)

**Comment by thkl** [comment]
achsooooo

**Comment by MikeDeltaHH** [comment]
Lässt sich da was machen? :)

**Comment by thkl** [comment]
Ja, aber : Da der Griff ja 2 "öffnen" Stufen durchlaufen kann habe ich bissel Bedenken mit dem TimesOpen Zähler. Offen für Homekit ist ja Offen und gekippt ...der Zähler würde dann immer doppelt zählen wenn man von Zu auf gekippt geht .. weil ja "offen"dazwischen kommt.

**Comment by MikeDeltaHH** [comment]
Hm... das stimmt... mich persönlich würde das null stören weil ich die generelle Ansicht einfach schick finde und das wesentlich mehr hermacht als nur offen & zu... aber wenn Du da Bauchschmerzen hast weil das die Ergebnisse verfälscht dann ist das wohl eher keine gute Idee...

**Comment by thkl** [comment]
Ich habe keine Bauchschmerzen, man müsste nur einen eindeutigen Entschluss fassen. Entweder Doppelt, oder zb gekippt ignorieren ... (da ist ja im Prinzip Offen durchlaufen)

**Comment by MikeDeltaHH** [comment]
Ich denke gekippt ignorieren wäre hier wohl die beste Option um die Ergebnisse nicht zu verfälschen!?

**Comment by thkl** [comment]
![Image](https://i.imgur.com/SuRMNTW.jpg)

**Comment by thkl** [comment]
Muss noch bissel aufräumen und testen dann geht das in Kürze

**Comment by MikeDeltaHH** [comment]
Super, vielen Dank! :)

**Comment by thkl** [comment]
implementiert mit https://github.com/thkl/homebridge-homematic/commit/f59426d99569c0a48602561e463c3993c6859ff2

**Comment by MikeDeltaHH** [comment]
Nabend!
Ich hab eben das Update auf die 0.202 gemacht und nun sind die beiden Fenstergriffkontakte zwar noch in Homebrdige zu sehen, aber nicht mehr in Homekit, da sind sie durch das Update rausgeflogen...
