### ISSUE TITLE
Change Device Type (Switch/Bulb)

### ISSUE THREAD

**Issue by drschnalli** [thkl/homebridge-homematic#50]
Hello,

im very thankful for your homematic plugin! I got all things working. I have some (non light devices) controlled with homematic wall socket devices (like a Reviecer or a Monitor). I cannot figure out how to exclude devices from being turned off when i say "turn off light in living room". When i say "turn off the lights in the living room" all devices turn off also the things plugged into the homematic wallsocket. 

Is there a way to change the device type or tell homekit that its not a light?

**Comment by Baenker** [comment]
You must edit the config.json. With the paramter "outlets" you can exsclue device.

For more Information see http://homematic-forum.de/forum/viewtopic.php?f=19&t=27465 the first post

**Comment by drschnalli** [comment]
Aaaah perfekt! Great - i think i misunderstood the outlets section, i thought its for filtering out a device :D....

awesome function! Thanks
