### ISSUE TITLE
Probleme mit falscher Anzeige

### ISSUE THREAD

**Issue by Daniel167** [thkl/homebridge-homematic#502]
Hallo, ich habe ein Problem mit 0.0.200 und 0.0.201. mit der 0.0.109 funktioniert alles. Es geht um ein HM-MOD-RE-8
Wenn einer der acht Aktoren geschalten wird, zeigen alle 8 in der Home App „Ein“ an. Sobald ich wieder auf aus gehe, gehen alle laut Anzeige aus. Geschalten wird aber richtig, also nur der wirklich „Ein“ ist Schalter auch. Dieses Phänomen ist unter 0.0.109 nicht. Vielen Dank

**Comment by superbraz** [comment]
ist vermutlich das gleiche Problem wie im Issue #496 und #495 ... Statusfehler, irgend ein fehlerhaftes "get" vermutet Thomas...denke er ist dran

**Comment by thkl** [comment]
Wenn die Kontakte als Switch gemappt sind, könnte das mit dem Fix  https://github.com/thkl/homebridge-homematic/commit/a3dfce3726b023461d9dbc1a6a9e21bdba9ba9dc gelöst sein.

Bitte mal testen.

**Comment by Tom-Bruzze** [comment]
Habe das gleiche Problem ich bin BEKLOPPT geworden... alle iPads aus iCloud rausgenommen reaktiviert etc. 10-12 Std. nach dem Fehler gesucht und dann finde ich per "Zufall" diesen Chat... Alle meine Mehrfachaktoren zeigen auf allen Kanälen "Ein" an, wenn ein Channel an ist. 
 ... und da ich einige Scripts mit Emails daran hängen habe bekam ich haufenweise Warnmails - ohne Grund ----- hoffe auf Lösung.... 
Danke Euch
Gruß
T.

**Comment by thkl** [comment]
ist das immer noch so (in der Version 204)

**Comment by Daniel167** [comment]
Hallo, bis jetzt schaut es mit der 204 bei mir sehr gut aus. Vielen Dank schon mal

**Comment by Tom-Bruzze** [comment]
Habe jetzt die 205 laufen... und alles ist OK. Mega-Herzlichen-Dank... und schönen Sonntagnachmittag...
T.
