### ISSUE TITLE
npm ERR! nach Update.

### ISSUE THREAD

**Issue by enricomueller** [thkl/homebridge-homematic#503]
Hallo zusammen,
ich bekomme leider seit dem letzten Update folgende Fehlermeldung. Homebridge läuft in einem Docker auf einer Synology. Vorab Vielen Dank für eure Hilfe!

Viele Grüße
Enrico

`[HomeMatic CCU2] Error: Command failed: npm view homebridge-homematic version
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /root/.npm/_cacache/tmp/5bf2df7d
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1028:100 "/root/.npm"
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code ERR_STREAM_DESTROYED
npm ERR! Cannot call write after a stream was destroyed
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /root/.npm/_cacache/tmp/5bf2df7d
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1028:100 "/root/.npm"

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm view homebridge-homematic version'
}`

**Comment by superbraz** [comment]
Ganz unten im Code steht

To permanently fix this problem, please run:
npm ERR! sudo chown -R 1028:100 "/root/.npm"


Das hat bei mir geholfen... hatte danach aber die Statusprobleme mit Tor und Steckdosen und bin auf 0.0.109 zurück

**Comment by enricomueller** [comment]
Danke dir! Mit sudo hatte es nicht funktioniert, ohne ging es. Die Fehlermeldungen sind weg. Ich halte die Augen offen wegen der Statusprobleme.

**Comment by superbraz** [comment]
ja stimmt...bei mir wars auch ohne sudo (homebridge im docker auf synology ds218+)

**Comment by enricomueller** [comment]
Nach dem Update auf v0.0.202 bekomme ich jetzt [HomeMatic CCU2] Switch Get hm is false will return false Fehler. Ich werde wohl auch zurück gehen auf die letzte funktionierende Version.

**Comment by thkl** [comment]
Das ist keine Fehlermeldung. Ist nur eine Debug Meldung die ich ausversehen im Info Anzeige. 

Fehler sind rot .. Warnungen Gelb
