### ISSUE TITLE
Fehler nach Neustart nach update auf 00.202

### ISSUE THREAD

**Issue by allesistmoeglichoderauchnicht** [thkl/homebridge-homematic#504]
Hab gerade auf Hoobs in Docker (auf meiner Synology) das update von 201 auf 202 durchgeführt. jetzt hab ich folgendes Log und der Homebridge Dienst läuft nicht mehr an: 
Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] timeout while executing rega script
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] Error Error: socket hang upwhile executing rega script string sDeviceId;string sChannelId;boolean df = true;Write('{"devices":[');foreach(sDeviceId, root.Devices().EnumIDs()){object oDevice = dom.GetObject(sDeviceId);if(oDevice){var oInterface = dom.GetObject(oDevice.Interface());if(df) {df = false;} else { Write(',');}Write('{');Write('"id": "' # sDeviceId # '",');Write('"name": "' # oDevice.Name() # '",');Write('"address": "' # oDevice.Address() # '",');Write('"type": "' # oDevice.HssType() # '",');Write('"channels": [');boolean bcf = true;foreach(sChannelId, oDevice.Channels().EnumIDs()){object oChannel = dom.GetObject(sChannelId);if(bcf) {bcf = false;} else {Write(',');}Write('{');Write('"cId": ' # sChannelId # ',');Write('"name": "' # oChannel.Name() # '",');if(oInterface){Write('"intf": "' # oInterface.Name() # '",');Write('"address": "' # oInterface.Name() #'.' # oChannel.Address() # '",');}Write('"type": "' # oChannel.HssType() # '",');Write('"access": "' # oChannel.UserAccessRights(iulOtherThanAdmin)# '"');Write('}');}Write(']}');}}Write(']');var s = dom.GetObject("Homekit");string cid;boolean sdf = true;if (s) {Write(',"subsection":[');foreach(cid, s.EnumUsedIDs()){  if(sdf) {sdf = false;} else { Write(',');}Write(cid);}Write(']');}Write('}');
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] ok local cache is set to /hoobs/etc/ccu.json
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] loaded ccu data from local cache ... WARNING: your mileage may vary
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] null is not a valid datapoint
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] cannot initialize garage device adress for close sensor is invalid
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] Address not given undefined,[object Object],undefined
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] Initializing platform accessory "Arbeitszimmer Jalousie 1".
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] Initializing platform accessory "Hombridge Trigger 1".
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] Initializing platform accessory "Terrassenfenster Jalousie 1".
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] Initializing platform accessory "Terrassentuere Jalousie 1".
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] Initializing platform accessory "Wohnzimmer Jalousie 1".
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] Initializing platform accessory "Garagentor".
[Homebridge] [1/23/2020, 6:37:56 PM] Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at EventedHTTPServer.listen (/hoobs/node_modules/@hoobs/hap/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/hoobs/node_modules/@hoobs/hap/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/hoobs/node_modules/@hoobs/hap/lib/Accessory.js:616:16)
    at Server._publish (/hoobs/node_modules/@hoobs/homebridge/lib/server.js:127:18)
    at Server.<anonymous> (/hoobs/node_modules/@hoobs/homebridge/lib/server.js:384:18)
    at /hoobs/node_modules/@hoobs/hap/lib/util/once.js:16:19
    at HomeMaticPlatform.buildaccesories (/hoobs/node_modules/homebridge-homematic/index.js:429:3)
[Homebridge] [1/23/2020, 6:37:56 PM] Got SIGTERM, shutting down service...
[Homebridge] [1/23/2020, 6:37:56 PM] [HomeMatic CCU3] Removing Event Server for Interface BidCos-RF.
[Homebridge] [1/23/2020, 6:37:56 PM] TypeError: Cannot read property 'methodCall' of undefined
    at HomeMaticRPC.stop (/hoobs/node_modules/homebridge-homematic/HomeMaticRPC.js:322:15)
    at process.HomeMaticPlatform.process.on (/hoobs/node_modules/homebridge-homematic/index.js:145:19)
    at process.emit (events.js:203:15)
[Homebridge] [1/23/2020, 6:37:57 PM] Got SIGINT, shutting down service...
[Homebridge] [1/23/2020, 6:37:57 PM] [HomeMatic CCU3] Removing Event Server for Interface BidCos-RF.
[Homebridge] [1/23/2020, 6:37:57 PM] TypeError: Cannot read property 'methodCall' of undefined
    at HomeMaticRPC.stop (/hoobs/node_modules/homebridge-homematic/HomeMaticRPC.js:322:15)
    at process.HomeMaticPlatform.process.on (/hoobs/node_modules/homebridge-homematic/index.js:125:19)
    at process.emit (events.js:203:15)
[Homebridge] [1/23/2020, 6:39:52 PM] [HomeMatic CCU3] timeout while executing rega script
[Homebridge] [1/23/2020, 6:39:52 PM] [HomeMatic CCU3] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("HmIP-RF.00241A49A76AA0:1.DOOR_STATE");if (d){Write(d.State());}
[Homebridge] [1/23/2020, 6:41:38 PM] [HomeMatic CCU3] timeout while executing rega script
[Homebridge] [1/23/2020, 6:41:38 PM] [HomeMatic CCU3] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("HmIP-RF.00241A49A76AA0:1.DOOR_STATE");if (d){Write(d.State());}

**Comment by thkl** [comment]
timeout while executing rega script -> ccu antwortet nicht auf das rega anfragen
[Homebridge] [1/23/2020, 6:37:56 PM] Error: listen EADDRINUSE: address already in use :::51826
--> eine andere Homebridge Instanz läuft schon

**Comment by MikeDeltaHH** [comment]
@thkl 
Ich hab Dir grad in dem closed ticket 499 wegen der Fenstergriffkontakte nochmal geantwortet, weiss nicht ob Du das durch das close sehen kannst - durch das Update auf die 202 sind die Fenstergriffkontakte nun leider in Homekit komplett verschwunden...

**Comment by Sheldor81** [comment]
bei der 109 lässt sich bei mir jetzt nichts mehr steuern  und auf den nachfolge Version dauern die Schaltprozesse mehrere Sekunden. Bin jetzt wieder bei der 202 da läuft alles bis auf den Falschen Garagentor status.

**Comment by allesistmoeglichoderauchnicht** [comment]
wahrscheinlich liegt's daran, dass ich 2 Dockercontainer laufen habe und einer für Alexa und einer für Siri. Wenn ich den Alexa stoppe (läuft iobroker nur drauf) dann kommt die meldung nicht. Trotzdem habe ich jetzt folgendes log:
[GDS] Garage Door Config: one sensor mode
[Homebridge] [1/26/2020, 10:11:55 AM] [HomeMatic CCU3] [GDS] Sensor close  is undefined
[Homebridge] [1/26/2020, 10:11:55 AM] [HomeMatic CCU3] [GDS] Sensor close value is true
[Homebridge] [1/26/2020, 10:11:55 AM] [HomeMatic CCU3] null is not a valid datapoint
[Homebridge] [1/26/2020, 10:11:55 AM] [HomeMatic CCU3] [GDS] cannot initialize garage device adress for close sensor is invalid
[Homebridge] [1/26/2020, 10:11:55 AM] [HomeMatic CCU3] [GDS] Garage Door Config: one sensor mode
[Homebridge] [1/26/2020, 10:11:55 AM] [HomeMatic CCU3] [GDS] Sensor close  is HmIP-RF.00241A49A76AA0:1.DOOR_STATE
[Homebridge] [1/26/2020, 10:11:55 AM] [HomeMatic CCU3] [GDS] Sensor close value is 0
[Homebridge] [1/26/2020, 10:11:55 AM] [HomeMatic CCU3] Address not given undefined,[object Object],undefined

Dabei habe ich nun auf die 205 geupdatet und wenn ich die Garage öffnen will, dann fährt sie kurz hoch, stoppt und fährt dann wieder runter (also schließt). Ne Idee wie ich das nun ändern kann???

**Comment by allesistmoeglichoderauchnicht** [comment]
war mein Fehler. hatte ausversehen die Adresse falsch gesetzt gehabt.
