### ISSUE TITLE
Fakegato history verschwunden

### ISSUE THREAD

**Issue by Samfox2** [thkl/homebridge-homematic#505]
Nach dem neuesten Update ist die fakegato-history für die Kontakte/Türen/Fenster verschwunden :-(

**Comment by thkl** [comment]
![Image](https://i.imgur.com/INWA4Zf.jpg)

Also die Historyfunktion selber ist da. 
Zusätzlich zu den Kontakten, haben die Drehgriffe eine History bekommen.

**Comment by Samfox2** [comment]
Grad nochmal geschaut, nun taucht sie auch bei mir wieder auf - sorry!

**Comment by thkl** [comment]
macht nix ;)
