### ISSUE TITLE
[Edit] Anzeige der Fenstergriffsensoren  in 0.0.205

### ISSUE THREAD

**Issue by MikeDeltaHH** [thkl/homebridge-homematic#506]
Moin!
Nachdem ich das Update gemacht habe sid die  HMIP-SRH Fenstergriffsensoren nur noch in Homebridge zu sehen, in Homekit fehlen diese komplett - ich bin erstmal wieder auf die 0.0.201 zurückgegangen! Kannst Du das noch fixen?

Viele Grüße!

**Comment by thkl** [comment]
ok wenn eve die History nutzt wollen die ein anderes return value .. ich hab es ausgebesser

**Comment by MikeDeltaHH** [comment]
Kann ich auf die offizielle Version 202 dann updaten oder kommt der Fix in einem neuen Build?

**Comment by thkl** [comment]
es gibt jetzt 203

**Comment by MikeDeltaHH** [comment]
Hab ich eingespielt und leider keine Änderung... in Homebridge werden die beiden Fenstergriffsensoren  zwar angezeigt aber nicht mit dem richtigen Status (offenes Fenster wird als zu angezeigt, Änderung des Status wird nicht angezeigt) und in Homekit sind sie garnicht mehr zu sehen!

**Comment by thkl** [comment]
ggf mal unter .homebridge /persist/ das IdentifierCache löschen ... 

Was heisst denn in Homebridge und in Homekit ??
ich habe die Dinger in der HomeApp und in Eve .. für Eve jetzt auch mit History

**Comment by MikeDeltaHH** [comment]
Das IdentifierCache zu löschen war leider keine gute Idee, danach sind mir alle Geräte die in der homebrdige Installation laufen in den Standardraum verschoben worden und alle Automationen die mit den Geräten verknüpft waren sind weg! Zum Glück konnte ich das mittels Snapshot rückgängig machen...

Mit Homebrdige meine ich dass ich die Fenstergriffsensoren noch in der WebUi von homebrdige-config-x-ui sehen kann aber in keiner Homekit App mehr, also weder in Apple Hom noch in Eve - nach Update existieren die Fenstergriffsensoren dort nicht mehr und lassen sich auch nicht mehr wiederfinden!

**Comment by MikeDeltaHH** [comment]
Shit... das rücksetzen des Snapshots hat nichts gebracht, urch das löschen des IdentifierCache sind alle Geräte im Standardraum gelandet und die Automationen & Regeln weg...

**Comment by thkl** [comment]
Ich teste das immer auf einer zurückgesetzten leeren HomeKit Instanz.  Die RHS haben History bekommen. Daher haben die sich geändert. Ich mach die History man optional.

**Comment by MikeDeltaHH** [comment]
Ich hab auf der Installation zum Glück nur drei Plugins laufen, da hält sich der Schaden in Grenzen, die anderen laufen auf einer hoobs Installation! Dein Plugin war übrigens vom löschen des Identifer nicht betrogen, da sind alle Geräte noch in den Räumen, nur die der beiden anderen Plugins muss ich neu einsortieren und die Automationen nochmal erstellen!

**Comment by MikeDeltaHH** [comment]
@thkl Ich habe jetzt mal nachdem ich eh alles neu einsortieren musste nochmal das Update auf die 0.0.203 gemacht und in den Logs und allen Homekit Apps geschaut und muss mich korrigieren... in Homebrdige werden die Fenstergriffsensoren mit Statusänderung korrekt angezeigt und auch in der Apple Home App, nur in Eve tauchen sie nicht mehr auf - habe Eve mal auf meinen beiden Apple Geräten neu installiert, ohne Erfolg - das Problem ist also nicht dass die Fenstergriffsensoren nicht in Homekit erscheinen sondern in Eve nicht mehr vorhanden sind! Das ist ja sehr kurios...

**Comment by MikeDeltaHH** [comment]
@thkl Gerade das Update auf die 0.0.204 gemacht, die Fenstergriffsensoren sind in Eve wieder sichtbar - allerdings mit dem alten Stand, also "Kontakt ja/nein" anstatt "auf/zu" und ohne History... muss ich das in der config.json dafür noch irgendwie anpassen von wegen dass die History optiional ist wie Du oben geschrieben hast?!

**Comment by MikeDeltaHH** [comment]
Ich hab mal den Betreff geändert, die Sensoren sind ja wieder sichtbar, nur noch nicht mit History und nicht mit gleichem Stauts wie die optischen Sensoren.

**Comment by thkl** [comment]
Hm. Ok nächstes mal bitte einen neuen Issue, da mittlerweile aus den geschlossenen Issues automatisch die Release Notes erzeugt werden.

**Comment by MikeDeltaHH** [comment]
Ich kann daraus eines machen wenn Du möchtest und das hier dann schliessen... ist ja im Prinzip auch noch mal der Request dass die Fenstergriffsensoren genauso angezeigt werden wie die optischen Fenstersensoren in Eve (da habe ich das geschlossene Case nicht wiedergefunden) - mit der Version 202 - 204 waren die Fenstergriffsensoren plötzlich komplett verschwunden in Eve und sind mit der 205 wieder drin aber eben mit den Stati "Kontakt ja/nein" anstatt "auf/zu" und ohne History.

**Comment by thkl** [comment]
in der config.json muss für die homematic platform ein Eintrag hizugefügt werden damit Fenstergriffe loggen:

```
"HM-Sec-RHS:ROTARY_HANDLE_SENSOR": {
  "enable_history": true
}

```


Beispiel:

```
{
  "platform": "HomeMatic",
  "name": "HomeMatic CCU",
  "ccu_ip": "192.168.0.1",
  "HM-Sec-RHS:ROTARY_HANDLE_SENSOR": {
    "enable_history": true
  }
 .....
}
```

**Comment by MikeDeltaHH** [comment]
Hab ich mal versucht, leider ohne Erfolg.. das sit meine config:

{
            "platform": "HomeMatic",
            "name": "HomeMatic CCU3",
            "ccu_ip": "192.168.2.76",
            "HM-Sec-RHS:ROTARY_HANDLE_SENSOR": {
                "enable_history": true
            },
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "programs": [],
            "accessories": [],
            "enable_hmip": "true",
            "subsection": "Homebridge"
        }

Sieht dann immer noch so aus:

![IMG_8262](https://user-images.githubusercontent.com/34737987/73201311-04efff00-4139-11ea-9597-7a450a38bc07.PNG)

**Comment by MikeDeltaHH** [comment]
@thkl Hast Du da noch eine Idee oder ist das einfach nicht möglich?

**Comment by thkl** [comment]
Bei mir ist die da.  Aber wie gesagt ich teste das immer mit einer leeren neuen Installation um sicher zu gehen, das ich keinen alten Mist mitschleppe.

**Comment by MikeDeltaHH** [comment]
Hm, ok... strange! Aber dann verzichte ich lieber auf die Anzeige denn das Plugin neu zu installieren und in Homekit alles neu einzubinden wäre hier eine tagesfüllende Aufgabe...
