### ISSUE TITLE
HomeMaticHomeKitBlindSlatServiceIP.js .... auch für HM Classic ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#508]
@thkl 
Hallo Thomas
habe heute in den ChannelServices "HomeMaticHomeKitBlindSlatServiceIP.js" entdeckt ... gibt es den Service auch für HM classic ? Was ist der Unterschied zum normalen "Blind" Service ?
Verwende nämlich den HM Jalousien Aktor ;-)

lg RIchard

**Comment by thkl** [comment]
Es gibt einen IP Aktor, der auch irgendwie noch die Lamellen drehen kann. Das wird über LEVEL_2 als Datenpunkt gemacht.

**Comment by roe1974** [comment]
ahhhhhhh ok .... den gibts beim HM Classic nicht ;-)
