### ISSUE TITLE
Release Notes für npm

### ISSUE THREAD

**Issue by Soilman82** [thkl/homebridge-homematic#509]
Hallo Thomas, 

mir ist aufgefallen, dass in den Release Notes bei npm beim Update eine Uralte Version angezeigt wird. Siehe Screenshot vom homebridge-config-ui-x

Vielleicht kannst du ja im einfachsten Fall einfach die Release Notes rausnehmen oder wenn du ganz viel Lust und Zeit hast, welche schreiben. ;-) 

<img width="790" alt="Bildschirmfoto 2020-01-26 um 21 18 42" src="https://user-images.githubusercontent.com/9981568/73141222-e975ed00-4081-11ea-9200-c1e50d6036ad.png">

Viele Grüße
Michael

**Comment by thkl** [comment]
Die Release Notes kommen von GitHub https://github.com/thkl/homebridge-homematic/releases .
Bis Version 0.0.98 gab es kein NPM Archiv sondern das ganze wurde über die GitHub Releases abgefackelt. Ich schaue mal, ob ich das irgendwie automatisieren kann, das es bei jedem NPM Publish ein GitHub Release mit passenden Infos gibt.

**Comment by thkl** [comment]
ab der nächsten Version gibt es release notes aus den Issues hier
