### ISSUE TITLE
Donation / Spenden?

### ISSUE THREAD

**Issue by daNick73** [thkl/homebridge-homematic#51]
Is there a way to donate a small amount for the great support and development?

**Comment by Samfox2** [comment]
Yes, this is really an "issue". Could you add an paypal badge or sth.? Good work should be rewarded...

**Comment by thkl** [comment]
done ;)

**Comment by mach1009** [comment]
Please open this issue again ;-)

**Comment by thkl** [comment]
i've upated the readme ;o)
