### ISSUE TITLE
HmIP-PSM, Trigger Update

### ISSUE THREAD

**Issue by ChrWi** [thkl/homebridge-homematic#510]
Hallo Thomas,

ich habe einen HmIP-PSM (schaltbare Steckdose) am laufen
- das Gerät hat über Kanal 8 eine Zeitsteuerung (morgens an, abends aus).
- Kanal 3 (Aktor) und 6 (Messwerte) sind beide im Homekit Gewerk
- Kanal 3 filtere ich in der Homebridge config raus, da ich über den Service "ENERGIE_METER_TRANSMITTER" bereits das Device in die Geräteliste bekomme
- im Apple Home sehe den Switch, in der Eve den Switch sowie die Messwerte 
Soweit alles ok.

Mein Problem: ich bekomme den neuen Zustand (an/aus) nicht ins Homekit und Eve aktualisiert.
Meine bisherigen Versuche:
1. Über ein Progamm in HM wird eine Variable zeitgesteuert gesetzt. => bringt nichts
2. Aus Deinem Wiki das Trigger Update innerhalb der "Special" Sektion eingebaut 
             `{
                    "variable_update_trigger_channel": "BidCos-RF.BidCoS-RF:10.PRESS_LONG"
                }`
 => kein Unterschied

Stimmt die Verwendung des Trigger Updates? Oder muss das mit dem Gerät (wie?) in Beziehung bringen. Das erkenne ich aus dem Wiki so nicht.
Verwende ich den ENERGIE_METER_TRANSMITTER korrekt?

Danke & Grüße,
Chris

**Comment by thkl** [comment]
Der Ein/Aus Zustand wird nicht aktualisiert ? Lässt sich die Steckdose via HomeKit schalten ?

**Comment by ChrWi** [comment]
Ja, schalten via Homekit geht.

**Comment by superbraz** [comment]
https://github.com/thkl/homebridge-homematic/issues/495

Ist bei der PS wie bei der PSM so...

**Comment by ChrWi** [comment]
Hm, bin mir nicht, ob das mit 495 zusammenhängt oder ‚nur‘ etwas zwischen Zeitschaltung, Variablenaktualisierung und Trigger zurück klemmt: Wenn meine PSM um 19:40 ausgeht, sollte das in Homekit zum Status „Off“ führen. Das tut es aktuell nicht. Der Status wird nur durch Betätigung im Homekit oder durch Neustart der CCU geändert.

**Comment by Tom-Bruzze** [comment]
Moin Zusammen, 
Hatte schon in einem anderen Thread „positive“ Lösung gemeldet. Es ging darum, dass Mehrfachaktoren nicht den korrekten Status anzeigen (wenn einer an werden alle an gezeigt und umgekehrt). 
DAS wurde mit der 205 behoben. 
Aber, es dauert jetzt ewig bis die Geräte in der Home App sich aktualisieren. Habe 69 Geräte und nach ca 30 SEK bricht die Aktualisierung ab. Gehe ich in die einzelnen „Räume“ werden nach und nach die Geräte aktualisiert und auch in der Übersicht korrekt angezeigt. Jedes Mal, wenn ich die Home App öffne, muss man jetzt das Prozedere durchlaufen, um einen aktuellen Stand zu bekommen... is nicht so ganz schön. 
Ach ja, alles mehrfach neu gestartet, WLAN oder Mobile spielt keine Rolle.
Schalten geht immer, Siri läuft auch...
Schöne Grüße 
T.

**Comment by thkl** [comment]
Normalerweise holt sich HomeKit den Stand aus dem Cache. Den habe ich für die HMIP pS in 205 abgeschalten. Das heißt es wird die ccu gefragt.  
Der Wert im Cache ist aber halt noch nicht aktuell wenn Homebridge gestartet ist.  

Ich schaue mal wie sich das optimieren lässt.

**Comment by thkl** [comment]
Das mit dem Zeitschaltaktor muss ich mal testen.  Wenn da kein Event von der ccu kommt wenn dieser per Timer sich ändert dann weiß Homebridge nix davon.

**Comment by Tom-Bruzze** [comment]
Wenn ich irgendwie „Supporten“ kann... lass es mich wissen...
Danke & Gruss
T.

**Comment by thkl** [comment]
Tritt dieser lädt ewig Fehler nur bei hmip ps Gerätrn auf oder sind da alle möglichen Geräte in den HomeKit Räumen ?

**Comment by Tom-Bruzze** [comment]
Habe keine HMIP nur HM und ein einziges anderes Gerät eingebunden - ne Lifx Lampe.

**Comment by ChrWi** [comment]
Bedenke dabei, dass ich die Zeitänderung in einer Variable erfasse, die sich sauber ändert. Ggf habe ich deinen Wiki Eintrag nicht korrekt interpretiert?

**Comment by gecko74** [comment]
Hallo
Bei mir ist der Status seit den letzten Updates auch falsch. Bin auf 205 und alle HmIP-PSM lassen sich schalten, aber eben Status ist falsch, sobald man die Home App schliesst und wieder öffnet.

**Comment by thkl** [comment]
PSM habe ich nicht angefasst sondern nur die PS Geräte ohne Energieerfassung. Ich schalte einstweilen auch bei den PSM den Cache aus. Dann sollte das auch da gehen.

**Comment by thkl** [comment]
die Github Version hier sollte jetzt HMIP PSMs richtig anzeigen ... es sind allerdings eine Menge Core / Servicefile Änderungen im Zuge des Cache Umbaus dabei sodas es nicht reicht, nur das Servicefile für hmip psm zu tauschen.

**Comment by gecko74** [comment]
> die Github Version hier sollte jetzt HMIP PSMs richtig anzeigen ... es sind allerdings eine Menge Core / Servicefile Änderungen im Zuge des Cache Umbaus dabei sodas es nicht reicht, nur das Servicefile für hmip psm zu tauschen.

Vielen Dank.
Frage, wie kann ich die GitHub Version installieren ohne npm? Kenn mich da nicht so aus, vielen Dank.

**Comment by thkl** [comment]
Ich würde uns Wochenende rum ein npm prelease bauen.

**Comment by gecko74** [comment]
Unterdessen habe ich es ohne npm installiert bekommen und der Status der PSM stimmen wieder. Vielen Dank für deinen Einsatz.

**Comment by thkl** [comment]
👍

**Comment by thkl** [comment]
Dann steht einem npm Release ja nichts mehr im Wege. Ggf schaffe ich das heute noch.

**Comment by thkl** [comment]
der RC  ist da 

```
npm install homebridge-homematic@beta
```

installiert die 208

**Comment by ChrWi** [comment]
Vielleicht blöde Frage, da erste Beta bei mir: muss ich irgendwas noch bei der Installation beachten? Bekomme folgende Meldungen und habe danach immer noch die 205:

pi@raspberrypi4:~ $ npm install homebridge-homematic@beta
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ homebridge-homematic@0.0.208
added 95 packages from 110 contributors and audited 400 packages in 12.589s

1 package is looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by thkl** [comment]
Kommt drauf an wie die vorherige Version installiert wurde .. wenn die alte version als Folder unter homebridge-homematic unter /home/pi/node_modules liegt dann ist es obiges kommando ... wenn unter /usr/lib/node_modules dann 

```
sudo npm install -g homebridge-homematic@beta
```

homebridge selber versucht die Plugins erst aus /usr/lib/node_modules und dann aus /home/pi/node_modules zu laden

**Comment by ChrWi** [comment]
Ah, klar. Jetzt hat's geklappt. Ich monitore mal das Verhalten des HmIP-PSM.

**Comment by thkl** [comment]
Der sollte funktionieren den Aktor hab ich zum Test da gehabt. Die Aktoren aus #485 musste ich simulieren.

**Comment by hillinator** [comment]
Ich installiere auch immer mit:
sudo npm install homebridge-homematic@beta -g --unsafe-perm
OR
sudo npm install homebridge-homematic@latest -g --unsafe-perm

Nach dem Update auf die beta ist mir aufgefallen, dass im Log das Garagentor nicht mehr aufgelistet wird!?!? Wurde da was verändert?

**Comment by ChrWi** [comment]
Hallo Thomas, mit der 210 beta und gleichzeitigem Update auf die CCU 3.51 werden die Energiewerte nicht mehr in die Eve App zurückgeben. Zum Stand 208 beta und 3.47 war alles ok. => hast du zwischen 208 und 210 etwas geändert?

**Comment by thkl** [comment]
Nein, aber kann ich prüfen, so ein Ding hab ich da.

**Comment by thkl** [comment]
![Image](https://i.imgur.com/xLE6xdQ.jpg)

Das funktioniert schon nur mit einem kleinen Haken. Dadurch das alles gecacht wird, aktualisiert sich der Wert erst wenn das Gerät einen neuen Messwert an die CCU und damit auch an HomeKit liefert. 

Ich mach das Cache optional abschaltbar.

**Comment by ChrWi** [comment]
Mir ist aufgefallen, dass auch der Status nach all den Updates nicht mehr zurückgemeldet wurde. Habe jetzt den Cache gelöscht und jetzt sowohl Status als auch Messwerte wieder sichtbar!
