### ISSUE TITLE
Garagentor öffnet kurz und schließt sofort wieder

### ISSUE THREAD

**Issue by allesistmoeglichoderauchnicht** [thkl/homebridge-homematic#516]
Ich bin auf der 205 und kriege mein Garagentor nicht zum laufen. Wenn ich öffnen sage, beginnt er das Garagentor zu öffnen (ca. 40cm nach oben), sagt dann sofort er sei geöffnet und schließt es dann gleich wieder und gibt mir auch die Info, dass das Garagentor geschlossen sei.
Mich wundert auch die Infos im Log:

[Homebridge] [1/28/2020, 8:56:55 AM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [1/28/2020, 8:56:56 AM] Loaded plugin: "homebridge-homematic"
[Homebridge] [1/28/2020, 8:56:56 AM] Registering platform "homebridge-homematic.HomeMatic"
[Homebridge] [1/28/2020, 8:56:56 AM] Loading 1 platforms...
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] Initializing HomeMatic platform...
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] Homematic Plugin Version 0.0.205
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] Plugin by thkl  https://github.com/thkl
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] Homematic is a registered trademark of the EQ-3 AG
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] running in production mode
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] will connect to your ccu at 192.168.178.76
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] using xmprpc for communication with BidCos-RF
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] init RPC for BidCos-RF.
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] local ip used : 192.168.178.55. you may change that with local_ip parameter in config
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] init RPC for VirtualDevices.
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] local ip used : 192.168.178.55. you may change that with local_ip parameter in config
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] init RPC for HmIP-RF.
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] local ip used : 192.168.178.55. you may change that with local_ip parameter in config
[Homebridge] [1/28/2020, 8:56:56 AM] Loading 0 accessories...
[Homebridge] [1/28/2020, 8:56:56 AM] API launched
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] RPC server for interface BidCos-RF. is listening on port 9090.
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] Creating Local HTTP Client for CCU RPC Events
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] RPC server for interface VirtualDevices. is listening on port 9093.
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] Creating Local HTTP Client for CCU RPC Events
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] RPC server for interface HmIP-RF. is listening on port 9092.
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] Creating Local HTTP Client for CCU RPC Events
[Homebridge] [1/28/2020, 8:56:56 AM] [HomeMatic CCU3] if PONG is PONG CCU is alive
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] [GDS] Garage Door Config: one sensor mode
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] [GDS] Sensor close  is undefined
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] [GDS] Sensor close value is true
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] null is not a valid datapoint
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] [GDS] cannot initialize garage device adress for close sensor is invalid
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] [GDS] Garage Door Config: one sensor mode
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] [GDS] Sensor close  is HmIP-RF.00241A49A76AA0:1.DOOR_STATE
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] [GDS] Sensor close value is 0
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] Address not given undefined,[object Object],undefined
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] Initializing platform accessory "Garagentor".
[Homebridge] [1/28/2020, 8:57:06 AM] Service is running on port 51826.
[Homebridge] [1/28/2020, 8:57:06 AM] [HomeMatic CCU3] will cache ccu response to /hoobs/etc/ccu.json
[Homebridge] [1/28/2020, 8:57:08 AM] [HomeMatic CCU3] NPM 0.0.205 vs Local 0.0.205

Die Konfig sieht folgendermaßen aus: 
{
    "platform": "HomeMatic",
    "name": "HomeMatic CCU3",
    "ccu_ip": "192.168.178.76",
    "subsection": "Homekit",
    "enable_hmip": "true",
    "special": [
        {
            "name": "Garagentor",
            "type": "HmIP-MOD-HO",
            "parameter": {
                "address_sensor_close": "HmIP-RF.00241A49A76AA0:1.DOOR_STATE",
                "state_sensor_close": 0,
                "address_actor_open": "HmIP-RF.00241A49A76AA0:1.DOOR_COMMAND",
                "message_actor_open": {
                    "on": 1,
                    "off": 3
                }
            }
        }
    ],
    "services": [
        {
            "type": "HmIP-MOD-HO",
            "service": "HomeMaticHomeKitGarageDoorService"
        }
    ]
}

Bin für jeden Tipp dankbar, komm einfach nicht weiter...

**Comment by thkl** [comment]
HmIP-MOD-HO ist der Hörmann Antrieb der braucht nicht HomeMaticHomeKitGarageDoorService sondern HomeMaticHomeKitGarageDoorOpenerService

**Comment by allesistmoeglichoderauchnicht** [comment]
Hm, hab ich gelöscht und jetzt wird das Garagentor nicht mehr angezeigt. Folgendes steht jetzt in dem Log: 

[Homebridge] [1/28/2020, 3:30:50 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [1/28/2020, 3:30:50 PM] Loaded plugin: "homebridge-homematic"
[Homebridge] [1/28/2020, 3:30:50 PM] Registering platform "homebridge-homematic.HomeMatic"
[Homebridge] [1/28/2020, 3:30:50 PM] Loading 1 platforms...
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] Initializing HomeMatic platform...
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] Homematic Plugin Version 0.0.205
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] Plugin by thkl  https://github.com/thkl
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] Homematic is a registered trademark of the EQ-3 AG
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] running in production mode
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] will connect to your ccu at 192.168.178.76
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] using xmprpc for communication with BidCos-RF
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] init RPC for BidCos-RF.
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] local ip used : 192.168.178.55. you may change that with local_ip parameter in config
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] init RPC for VirtualDevices.
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] local ip used : 192.168.178.55. you may change that with local_ip parameter in config
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] init RPC for HmIP-RF.
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] local ip used : 192.168.178.55. you may change that with local_ip parameter in config
[Homebridge] [1/28/2020, 3:30:50 PM] Loading 0 accessories...
[Homebridge] [1/28/2020, 3:30:50 PM] API launched
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] RPC server for interface BidCos-RF. is listening on port 9090.
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] Creating Local HTTP Client for CCU RPC Events
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] RPC server for interface VirtualDevices. is listening on port 9093.
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] Creating Local HTTP Client for CCU RPC Events
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] RPC server for interface HmIP-RF. is listening on port 9092.
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] Creating Local HTTP Client for CCU RPC Events
[Homebridge] [1/28/2020, 3:30:50 PM] [HomeMatic CCU3] if PONG is PONG CCU is alive
[Homebridge] [1/28/2020, 3:31:01 PM] [HomeMatic CCU3] There is no service for HmIP-MOD-HO:DOOR_RECEIVER
[Homebridge] [1/28/2020, 3:31:01 PM] [HomeMatic CCU3] Initializing platform accessory "Arbeitszimmer Jalousie 1".
[Homebridge] [1/28/2020, 3:31:01 PM] [HomeMatic CCU3] Initializing platform accessory "Terrassenfenster Jalousie 1".
[Homebridge] [1/28/2020, 3:31:01 PM] [HomeMatic CCU3] Initializing platform accessory "Terrassentuere Jalousie 1".
[Homebridge] [1/28/2020, 3:31:01 PM] [HomeMatic CCU3] Initializing platform accessory "Wohnzimmer Jalousie 1".
[Homebridge] [1/28/2020, 3:31:01 PM] Service is running on port 51826.
[Homebridge] [1/28/2020, 3:31:01 PM] [HomeMatic CCU3] will cache ccu response to /hoobs/etc/ccu.json
[Homebridge] [1/28/2020, 3:31:03 PM] [HomeMatic CCU3] NPM 0.0.205 vs Local 0.0.205

In der Konfig habe ich stehen: 
{
    "platform": "HomeMatic",
    "name": "HomeMatic CCU3",
    "ccu_ip": "192.168.178.76",
    "subsection": "Homekit",
    "enable_hmip": "true"
}

Hab ich jetzt was falsch gemacht? Hab einfach nur die Inhalte aus der Konfig gelöscht.

**Comment by thkl** [comment]
Theoretisch ist der Opener in der config drin .. die liegt in node_modules/homebridge_homematic/Channelservices/channel_config.json ... letzte Zeile ist

```
{
			"type": "HmIP-MOD-TM:DOOR_RECEIVER",
			"service": "HomeMaticHomeKitGarageDoorOpenerService"
		}
```

**Comment by Soilman82** [comment]
Schau mal, im Log steht "There is no service for HmIP-MOD-**HO**:DOOR_RECEIVER", ggf. müsste also noch folgendes in der channel_config.json ergänzt werden:

`{
			"type": "HmIP-MOD-HO:DOOR_RECEIVER",
			"service": "HomeMaticHomeKitGarageDoorOpenerService"
		}`

Dann sollte das Gerät wieder gefunden werden.

**Comment by allesistmoeglichoderauchnicht** [comment]
Ok das war der Grund warum es nicht angezeigt wurde. Ich kann das Garagentor wieder sehen. Leider erhalte ich nun durchgehen "keine Antwort", folglich kann ich nicht darauf zugreifen. Hast du eine Idee wie ich das lösen kann?

Am Rand kurz: Du bist ziemlich responsive! Respekt für deiner Arbeit!!

**Comment by allesistmoeglichoderauchnicht** [comment]
ok komischerweise habe ich gerade eine Meldung erhalten, dass mein Garagentor geschlossen ist. Jetzt geht es! MEGA
Komisch ist nur, dass Siri mir die Info gibt: Ich habe versucht, aber das Gerät "Aussen" Garagentor reagiert nicht. Siri macht's aber trotzdem :-)

Danke dir für deine super Arbeit!!

**Comment by thkl** [comment]
Die Meldung über das Garagentor kommt kurz nach dem homebridge Start, da das Tor dort aktiv nach seinem Zustand gefragt wird und HK entsprechend aktualisiert wird. 

Ich mach dann mal hier zu
