### ISSUE TITLE
[homematic] contact value false und Duty Cycle Problem

### ISSUE THREAD

**Issue by pat4020** [thkl/homebridge-homematic#517]
Halllo,

habe gestern Version 0.0.205 des HM plugins installiert.
Nachdem ich dann die homebridge Instanz gestartet habe, und alle Plugins geladen wurden, erscheint in regelmäßigen Abständen die Meldung "[Homematic] contact value false" - immer 5 Zeilen, gefolgt von einer 10-sekündigen Pause nach der wieder 5 Zeilen mit dieser Ausgabe erscheinen.
Nach etwa 2 Minuten Laufzeit der homebridge ist der Duty Cycle der CCU bei 100% und es kann keine Kommunikation mit den Geräten mehr stattfinden.
Ist dieses Problem bekannt und gibt es dafür eine Lösung?

Bin mittlerweile zur Version 0.0.109 des HM plugins zurückgekehrt - hier besteht dieses Problem nicht,

Vielen Dank,
LG

**Comment by bpohvoodoo** [comment]
Bei mir läuft auch der Duty Cycle voll, auch bei der Version aus dem Master Branch.

**Comment by thkl** [comment]
Die Meldung kann man ignorieren. Das ist eigentlich eine Debug Meldung. Die hab ich ins falsche Loglevel geschrieben. Das DC Problem ist in dem Commit oben gelöst

**Comment by hillinator** [comment]
Ich habe gerade das Fix gerade eingespielt. Debugmeldung scheint wieder weg zu sein. DutyCycle prüfe ich noch

**Comment by bpohvoodoo** [comment]
Duty Cycle sieht gut aus.

**Comment by thkl** [comment]
Prima 👏

**Comment by Daniel167** [comment]
Servus, kann man die 0.0.205 einfach nochmal installieren und ist der fix dann drin, oder händisch in der Datei ändern? Gruß Daniel

**Comment by thkl** [comment]
Manuell das File tauschen oder auf die 206 warten. Die sollte heute fertig werden.

**Comment by pat4020** [comment]
Hallo.

Vielen Dank, hat funktioniert. 
Allerdings wird bei mir der Status der Geräte in 0.0.205 „langsam“ geladen, ca. 1-2 Sekunden ab Öffnen der Home App. In Version 0.0.109 ist das deutlich schneller... fast ohne Verzögerung. 

LG
