### ISSUE TITLE
Keine Antwort in der HomeAPP

### ISSUE THREAD

**Issue by patrick150781** [thkl/homebridge-homematic#519]
Hallo zusammen,

ich habe ab und zu das Problem, dass bei öffnen der Apple Home APP die Homematic Geräte nicht antworten. Teilweise dauert die Aktualisierung auch recht lange. 
Erst dachte ich, dass es an einem anderen Bonjour Dienst bei mir im Haus lag, denn habe ich jedoch in der Zwischenzeit ausgeschaltet. 

Habe die aktuelle 0.4.50 Homebridge und das 0.205 Homematic Plugin auf einem virtuellen Server mit Ubuntu Server 19.10.

Hat jemand von Euch eine Idee?

Gruß
Patrick

**Comment by dkrizic** [comment]
Hi Patrick,

eine Sache, die ich mal gesehen habe ist: Deaktiviere mal im Avahi-Service auf dem Debian-Server das IPv6.

Gruß,

Darko

**Comment by patrick150781** [comment]
Sorry kannst Du mir da etwas helfen, bin jetzt nicht so Linux affin :)

**Comment by MikeDeltaHH** [comment]
Native Homebridge oder Hoobs?

**Comment by dkrizic** [comment]
In der Datei /etc/avahi/avahi-daemon.conf diesen Eintrag ändern

```
use-ipv6=no
```

und dann Avahi neu starten mit

```
systemctl restart avahi
```

**Comment by thkl** [comment]
ist das erledigt ?
