### ISSUE TITLE
homebridge-homematic scheint kontinuierlich die CCU abzufragen

### ISSUE THREAD

**Issue by bpohvoodoo** [thkl/homebridge-homematic#520]
Alle Aktoren werden sekündlich? abgefragt bis homekit crascht.
Version: master branch von heute morgen

![image](https://user-images.githubusercontent.com/4918785/73590448-c9f81d80-44e2-11ea-9f6d-39b282db8f27.png)

**Comment by thkl** [comment]
Was ist TV Leuchte für ein Aktor ? Ich wüsste nicht, das ich so ein Log produziere ...

**Comment by bpohvoodoo** [comment]
Nein, tust du nicht.
Das ist ein Better Http RGB Gerät.
Das aktualisiert gleich mit. Ich kann es aber auch rausnehmen zum Test.
Es scheint so als würde der cash gefüllt, gelöscht gefüllt gelöscht .....
im Homkit gehen die Stati der Schalter im an/aus/an/aus obwohl sie an sind,

**Comment by thkl** [comment]
Aber dann ist das ja eher ein homebridge/HomeKit Problem ? Normalerweise kommt der Request für das aktualisieren von HomeKit und wird zum jeweiligen Plugin geschickt.

**Comment by bpohvoodoo** [comment]
Mag sein, aber das tritt erst seit der korrektur gestern auf, vor leif nur der Duty Cycle voll ;-)

**Comment by thkl** [comment]
Die Korrektur gestern war, das ich das Rega Kommando zum Lesen eines Zustandes von .State() auf .Value() geändert habe. 
.State() frage das Interface -> DutyCycle  .Value() nimmt den Wert aus dem CCU Cache.

**Comment by bpohvoodoo** [comment]
Ist mir alles klar. So sieht es übrigens nach dem crash aus:
![image](https://user-images.githubusercontent.com/4918785/73590931-b780e280-44e8-11ea-972e-d503c4a249e1.png)

**Comment by thkl** [comment]
Hm ich sehe noch nicht das Problem beim Homematic Plugin

**Comment by MikeDeltaHH** [comment]
Das Plugin hat glaub ich generelle Probleme unter Hoobs... bei mir wird sofort nach dem speichern der config.json Hoobs extrem träge und alle Geräte sind in Homekit offline - bin ich wohl auch nicht der einzige... deshalb habe ich für das Plugin und ein paar andere die mit Hoobs Probleme machen auch eine eigene Homebrdige Installation... das liegt aber eher auf der Hoobs Seite, die haben ja einige Änderungen in der Funktionsweise gegenüber Homebrdige eingebracht...

**Comment by thkl** [comment]
Ok ... aber darum möchte ich mich eigentlich nicht kümmern müssen 😀

**Comment by MikeDeltaHH** [comment]
> 
> 
> Ok ... aber darum möchte ich mich eigentlich nicht kümmern müssen 😀

Deshalb ja mein Post... ich hatte im hoobs github schon einen dazu aufgemacht, aber die haben im Moment soviele offene Baustellen, das dauert noch bis sich da was tut...

**Comment by bpohvoodoo** [comment]
Das erklär einiges ;-)

**Comment by thkl** [comment]
Ich hab aktuell 3 Testsysteme für den ganzen Kram hier laufen.  In ein weiteres möchte ich nicht investieren 🧐

**Comment by MikeDeltaHH** [comment]
Will damit auch sagen dass das meiner Meinung nach auch nicht Deine Baustelle ist... Hoobs ist schon echt genial aber die haben aktuell mit diversen Plugins zu kämpfen die noch nicht sauber laufen dass ich froh bin dass die restlichen Plugins fehlerfrei auf meiner Homebrdige laufen... :)

**Comment by bpohvoodoo** [comment]
Seh ich ein. Kicke gerade hoobs

**Comment by thkl** [comment]
Ich verstehe auch das Hoobs Ding nicht ... 

Das ganze Projekt Homebridge benötigt ein bissel technisches Wissen und funktioniert eben nicht einfach „out of the Box“ ... wer das möchte muss in certified HomeKit Geräte investieren.

**Comment by bpohvoodoo** [comment]
Hoobs ist insovern gut, dass du die Konfigs via http editieren kannst, sofort die logs siehts, etc.
Ist schon nicht ganz schlecht. Ich kanns aber auch ohne ;-)

**Comment by bpohvoodoo** [comment]
So. Läuft! - ohne HOOBS

**Comment by dkrizic** [comment]
Homebridge im Docker (ozne/homebridge) mit der Homebridge-confiug-ui-x ist auch sehr nett 
![image](https://user-images.githubusercontent.com/1181349/73594065-e9a33c00-450a-11ea-8052-a7ab2a69db62.png)
