### ISSUE TITLE
HM-Sen-LI-O: Das Gerät hat eine ungültige Antwort zurückgegeben.

### ISSUE THREAD

**Issue by bpohvoodoo** [thkl/homebridge-homematic#521]
Der Helligkeitssensor HM-Sen-LI-O meldet immer
Das Gerät hat eine ungültige Antwort zurückgegeben.

**Comment by thkl** [comment]
Welcher Wert steht denn in der CCU für die Helligkeit ... 
Das Homekit Gerät darf einen Lux Wert zwischen 0.1 und 100000 haben

**Comment by bpohvoodoo** [comment]
zu der Zeit 1755,25

**Comment by thkl** [comment]
ok muss ich mir mal was zusammensimmulieren ich hab so einen Sensor nicht

**Comment by bpohvoodoo** [comment]
Nur eine Bemerkung am Rande. Habe gestern noch die EVE App ausprobiert. Die zeigt zwar den Wert an, aber ein "!" bei dem Gerät. Möglicherweise ist das kein Werte Problem
