### ISSUE TITLE
HmIP-SWO-PR: Regenerkennung ist als MotionDetector ausgeführt

### ISSUE THREAD

**Issue by bpohvoodoo** [thkl/homebridge-homematic#522]
Hallo,

beim HmIP-SWO-PR ist die Regenerkennung in der HomeMaticHomeKitWeatherStationServiceIP.js  als MotionDetected ausgeführt
und nicht wie beim Regensensor HM-Sen-RD-O in der HomeMaticHomeKitRaindetectorService.js als IsRainingCharacteristic
ist das so gewollt?

**Comment by bpohvoodoo** [comment]
Ich hab mal folgendes probiert
[HomeMaticHomeKitWeatherStationServiceIP.js.txt](https://github.com/thkl/homebridge-homematic/files/4143737/HomeMaticHomeKitWeatherStationServiceIP.js.txt)

**Comment by roe1974** [comment]
Hi, 
wie wird "IsRainingCharacteristic" in der Home App dargestellt ? (icon)
@thkl 
Kann ich einen bestimmten HM-SCI-3-FM (verwende einen davon als regensensor) diesem Service (HomeMaticHomeKitRaindetectorService.js) zuwesien ?

lg Richard

**Comment by thkl** [comment]
ist das erledigt ?

**Comment by bpohvoodoo** [comment]
Also für mich schon.
