### ISSUE TITLE
HM-SCI-3-FM als Wasser(Leck)sensor ..... möglich ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#524]
@thkl 

Hallo Thomas

Ich habe mehrere HM-SCI-3-FM in HK die korrekt als SHUTTER_CONTACT dargstellt werden.
Einen davon nutze ich aber als Regensensor. Hier würde mir die Darstellung als WATERDETECTIONSENSOR besser in HK gefallen......
Kann ich einen einzelnen HM-SCI-3-FM einem anderen Channelservice (Lecksensor) zuweisen ?

lg Richard

**Comment by thkl** [comment]
Müsste gehen, da beide Sensoren den STATE Datenpunkt als Zustandsanzeige haben.

**Comment by thkl** [comment]
Achso, der aktuelle ChannelLoader kann aber keine unterschiedlichen Serviceklassen für ein und den selchen Channeltype erzeugen. Dazu müsste ich den umbauen, das er auch Geräteadressen unterscheidet.

**Comment by roe1974** [comment]
das wäre super :)))👍

**Comment by thkl** [comment]
So, ich habe den ClassLoader angepasst. Es war noch eine Änderung im Leakservice nötig, da der Kontakt True/False liefert der Wassermelder aber 0,1,2

Bei der Gelegenheit habe ich den Classloader von Channelloader umbenannt.

Es müssen also alle in den Commits hier geänderten Files getauscht werden.

**Comment by thkl** [comment]
Zur Funktion: 
Die services Rubrik der config.json versteht jetzt nicht nur Channeltype oder Device:Channeltype sondern auch KanalAdresse als Type Beispiel:

```
{
  "type":"JEQ012345678:1",
  "service":"HomeMaticHomeKitLeakSensorService"
}
```

**Comment by roe1974** [comment]
@thkl 
Hi Thomas
heeeeee ... super ! Spende ist raus !!!
Ich kann erst morgen testen ... aber habe ein paar Fragen:
ich bin noch auf 109 .... die rennt perfekt ... geht das dort auch ?
ist die 205 save für upgrade ? ... lese hier ein paar themen mit duty cycle & co ... und files die noch manuell getauscht werden müssen ... oder kommt eine 206er ?
lg Richard

**Comment by thkl** [comment]
Nein auf 109 geht das nicht weil sehr viele Änderungen gerade im Caching erfolgt sind. Und da auch der Classloader geändert wurde geht das nicht zusammen. 

Du kannst ja ggf homebridge zum Test auf einem extra System laufen lassen wenn du von 109 nicht weg willst. 😁

**Comment by thkl** [comment]
Zum Wochenende hin wird es eine 206 mit dem aktuellen Stand des Masters hier geben.

**Comment by roe1974** [comment]
alles klar ... ich warte ;)
lg richard

**Comment by roe1974** [comment]
nicht schließen ... muss noch testen mit der 206er ;)

**Comment by thkl** [comment]
212 ist da ;)

**Comment by roe1974** [comment]
😳😳😳.... ok dann mit der ;) ... ich mach das heute nachmittag/abend ;)

**Comment by roe1974** [comment]
das funktioniert :)
