### ISSUE TITLE
upgrade 109 -> 212 ...... passt config.json noch ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#527]
@thkl 
Hallo Thomas, bevor ich mit der 212 "drüber bügel" kannst Du bitte die config.json checken ob das noch passt für die 212er ? DANKE ! lg Richard

    "platforms": [
        {
            "ccu_ip": "192.xxx.xxx.xxx",
            "outlets": [
                "BidCos-RF.NEQ1xxxxxx:1",
                "BidCos-RF.OEQ0xxxxxx:1",
                "BidCos-RF.OEQ1xxxxxx:2",
                "BidCos-RF.OEQ2xxxxxx:2"
            ],
            "name": "Raspberrymatic",
            "doors": [],
            "platform": "HomeMatic",
            "filter_device": [],
            "special": [
                {
                    "name" : "Zentrale Lüftung",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQ0xxxxxx:1","switchtype":"Switch"}
                },
				{
                    "name" : "Heizung Ventil",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQ0xxxxxx:1","switchtype":"Switch"}
                },
				{
                    "name" : "Heizung Pumpe",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQ0xxxxxx:2","switchtype":"Switch"}
                },
				{
                    "name" : "Heizpatrone",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQ0xxxxxx:1","switchtype":"Switch"}
                },
				{
                    "name" : "Steckdose Ladegerät",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQ1xxxxxx:1","switchtype":"Switch"}
                }						
            ],
            "services": [
                {
                    "type": "HM-SPECIAL-SWITCH",
                    "service": "HomeMaticHomeKitSpecialSwitchService"
                },
                {
                    "type": "HM-LC-Ja1PBU-FM:JALOUSIE",
                    "service": "HomeMaticHomeKitBlindService"
                },
                {
                    "type": "HM-WDS30-OT2-SM-2:WEATHER",
                    "service": "HomeMaticHomeKitThermometerService"
                },
                {
                    "type": "HM-WDS40-TH-I-2:WEATHER",
                    "service": "HomeMaticHomeKitThermostatWeatherService"
                }
            ],
            "filter_channel": [],
            "variables": [
                "Anwesenheit",
                "Urlaub",
                "Klima Schlafzimmer Steuerung",
                "Klima Wohnzimmer Steuerung",
                "Lueften Steuerung",
                "Klima Wohnzimmer manuell",
                "Klima Schlafzimmer manuell", 
                "Balkon Waesche",
                "Jalousien Steuerung"
            ],
            "programs": [],
            "subsection": "Homekit"
        },

**Comment by thkl** [comment]
An den alten Settings hat sich nichts geändert.

**Comment by roe1974** [comment]
alles klar ... hast du das mit der Winmatic gesehen ? (verwende ich auch ) ....
