### ISSUE TITLE
Feedback 214 .....

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#528]
@thkl 
Hallo Tomas ... 212er ist drauf ... sieht seeehr gut aus :-)

ein paar Fragen zum cache:
derzeit stimmt die anzeige von einer jalousie + neigungssensor nicht.
Nach hoch/runterfahren dieser jalousie stimmt die anzeige.
Der Neigungssensor Status ist aber falsch .... hat sich aber schon lange nicht mehr geändert gegenüber der CCU ... muss ich den einmal bewegen ? Ebenso der Switch war anfangs falsch (beide hängen auf einem Lan-Gateway)....
Kann es sein dass es probleme mit dem cache gibt, wenn ein gerät schon lang im seben status ist ? und durch einen CCU reboot damit kein zeit stempel in der ccu ist ?

Noch ein probelm: Der Status des Security Systems (wenn ich es in der CCU schalte) aktualisiert sich nur wenn ich die Home App Abschiesse und neue starte ... war vorher nicht so :(

lg Richard

**Comment by roe1974** [comment]
ok, neigungssensor bewegt ... jetzt stimmt die anzeige .......
Bleibt nur das Securtiy System das nicht aktualisiert wenn ich es über die CCU schalte .....
Kannst Du Dir das bitte ansehen ? ..... Spende folgt ;-)
lg Richard

**Comment by roe1974** [comment]
@thkl 
Noch ein problem...ich habe 2 Stk. HM-WDS30-OT2-SM-2 im einsatz und jeweils die ersten drei kanäle im Homekit gewerk (Temp1, Temp2, Diff Temp1/Temp2) ..... 
in der config.json habe ich:

"type": "HM-WDS30-OT2-SM-2:WEATHER",
"service": "HomeMaticHomeKitThermometerService"

damit nur temperaturen angezeigt werden....

ich sehe aber jetzt überall nur die Diff Temp1/Temp2 Temperatur .... ?!?!?!? Das hat mit 109 funktioniert :(

kann es sein da beide kanäle WEATHER heissen (der für 1-4) und der für 5 ? Siehe Bild
<img width="340" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/74102525-65713a00-4b44-11ea-81ac-203c7795d842.PNG">

**Comment by roe1974** [comment]
PS: ab und zu taufen die richtigen Temperaturen auf ....

**Comment by Soilman82** [comment]
Ich kann zu den eigentlichen Issues leider nichts sagen. 🙁 Wollte aber anmerken, dass es für Thomas unter anderem wegen der Release Notes hilfreich ist, wenn die einzelnen Themen in separaten Issues erläutert werden. Dann können diese auch einzeln bearbeitet und mit entsprechendem Status versehen und released werden. 

Ansonsten gibt Thomas ja derzeit richtig Gas. Es gibt ja schon wieder ein neues Release 0.214. 😃 Ändert das etwas?

**Comment by roe1974** [comment]
sorry ... betrifft die 214er .... werde das trennen
