### ISSUE TITLE
Version 214 .... Security System aktualisiert nicht

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#529]
@thkl 
Hi Thomas
ich habe festgestellt, dass das Security System nicht aktualisiert wenn ich den Status auf der CCU ändere.  Es aktualisiert nur wenn ich die Home abschiesse und neu aufrufe. Kannst Du dir das bitte asehen ? ;-) Umgekehrt geht es.
lg Richard

**Comment by roe1974** [comment]
@thkl 
Hi Thomas
Hier der Unterschied zwischen dem Security Channel Service der 109er (links) und dem aktuellen aus der 214er (rechts) .. Unterschied sind **"."** und **":"** ... ?!?!
![Unbenannt](https://user-images.githubusercontent.com/30420568/74143409-0d493f00-4bfb-11ea-8c18-18cf5f8ee0bd.JPG)

**Comment by thkl** [comment]
Ja ich habe irgendwann mal den Syntax auf den der CCU Datenpunkte umgestellt. 
Ich hab so ein Gerät zum Testen da.

**Comment by roe1974** [comment]
ok super, wiegesagt in der 109er hat das mit dieser version (anhang) perfekt funktioniert ......
und momentan werden Änderungen auf der CCU nicht aktualisiert (nur durch abschiessen der app) ...
Auch klingt die aktuelle Version (akustische Rückmeldung) wie wenn er irgendwas doppelt schalten würde ....
[HomeMaticHomeKitSecuritySystem.zip](https://github.com/thkl/homebridge-homematic/files/4180360/HomeMaticHomeKitSecuritySystem.zip)

**Comment by roe1974** [comment]
funktioniert !!! danke !!!!
