### ISSUE TITLE
Dimmer Status wird nicht aktualisiert

### ISSUE THREAD

**Issue by bprskalo** [thkl/homebridge-homematic#53]
Wenn ich den Dimmer manuel einschalte sehe ich den status "eingeschaltet"  im HOME nicht, Schalter werden richtig angezeigt (ist auch wieder seit dem letzten update) :-)

**Comment by thkl** [comment]
ok kann ich nachvollziehen, schau ich mir an

**Comment by bprskalo** [comment]
DANKE !!

**Comment by thkl** [comment]
so in 0.0.46 geht das wieder

**Comment by bprskalo** [comment]
kann ich so leider noch nicht bestätigen .. bin auf der 0.0.46  und es ist noch der selbe Effekt

**Comment by bprskalo** [comment]
über npm kommt noch die 0.0.46 :-( ...

**Comment by thkl** [comment]
Ja das mach ich morgen oder so.

**Comment by bprskalo** [comment]
also hier mein feedback , 

die 0.0.47 manuel installiert, jetzt stimmen die Anzeigen auch mit manuell geschalteten Dimmern :-) DANKE schon mal für das, ich kann jetzt wieder manuell einschalten und mit HOME ausschalten oder umgekehrt

aaaber .. die Aktualisierung ist nicht mehr so dynamisch  wie sie mal war, will heissen, das der dimmer z.b. mit 0% angezeigt wird und als eingeschaltet bis ich die Anwendung schließe und erneut öffne .. dann stimmen der status auch. "früher" war das  immer sehr schnell richtig Umgesetz dargestellt

**Comment by thkl** [comment]
Die Dimmer werden aktualisiert, wenn das Working Flag auf False geht.  Dann hole ich noch mal den Level Datenpunkt ab.

**Comment by bprskalo** [comment]
ok, verstehe ich. nur bin ich der Meinung, dass es bisher so war :

Dimmer manuell an :
Symbol ist auf "eingeschaltet" und die richtigen Prozentwerte werden angezeigt (das ist auch jetzt wieder so)

Dimmer manuell aus :
Symbol geht auf ausgeschaltet (jetzt wird in der anzeige 0% angezeigt und bleibt auf "eingeschaltet" bis die app manuell aktualisiert wird wie z.b. mit schlissen und wieder öffnen

**Comment by thkl** [comment]
Oh das mit dem Aus würde ich noch mal anschauen.  Das hab ich gestern nicht getestet.

**Comment by bprskalo** [comment]
danke Thomas, echt geile Arbeit die DU hier leistest !!!

**Comment by thoduh** [comment]
Obwohl das Licht aus ist, zeigt HomeKit 40% an?

**Comment by thkl** [comment]
Das ist schwer zu diagnostizieren. Da müsstest du mal länger die Homebridge im Debug Modus laufen lassen.  Nur erzeugt das ganze eine riesige Masse an Log

**Comment by TheRoolBool** [comment]
Hallo, schalten von Dimmern funktioniert leider immer noch nicht, trotz Version 0.0.46

Wie kann man denn die 0.0.47 manuell installieren?

**Comment by thkl** [comment]
via npm update .. ich hab es eben ins npmjs gepackt ...

**Comment by bprskalo** [comment]
für mich funktioniert im moment :-) .. !! DANKE
