### ISSUE TITLE
Version 214 ... HM-WDS30-OT2-SM-2 zeigt falsche Werte

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#530]
@thkl 
Hallo Thomas

Noch ein problem...ich habe 2 Stk. HM-WDS30-OT2-SM-2 im einsatz und jeweils die ersten drei kanäle im Homekit gewerk (Temp1, Temp2, Diff Temp1/Temp2) .....
in der config.json habe ich:

"type": "HM-WDS30-OT2-SM-2:WEATHER",
"service": "HomeMaticHomeKitThermometerService"

damit nur temperaturen angezeigt werden....

ich sehe aber jetzt überall nur die Diff Temp1/Temp2 Temperatur .... ?!?!?!? Das hat mit 109 funktioniert :(

kann es sein da beide kanäle WEATHER heissen (der für 1-4) und der für 5 ? Siehe Bild
<img width="340" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/74104241-02d36a80-4b53-11ea-8f18-46cfd749c461.PNG">

**Comment by roe1974** [comment]
PS ... die kanäle :1 :2 :3 werden in den geräten richtig angezeigt ... nur die werte stimmen nicht

**Comment by roe1974** [comment]
PSS: in der dazugehörigen json Datei (historie) sehe ich abwechselnd den falschen / richtigen Wert pro Kanal ?!?!?!?

**Comment by thkl** [comment]
Wenn Du 3 Kanäle des Gerätes eingetragen hast, müsste er doch 3 Geräte angelegt haben oder ?

**Comment by roe1974** [comment]
habe die geräte nicht einzeln eingetragen (müsste ich dann pro gerät 3x machen mit der "neuen" methode wie hier beschrieben https://github.com/thkl/homebridge-homematic/wiki/Abweichend-Services)
habe nur

"type": "HM-WDS30-OT2-SM-2:WEATHER",
"service": "HomeMaticHomeKitThermometerService"

in der config.json eingetragen ...
muss ich das ändern ?

lg Richard

**Comment by thkl** [comment]
das sollte weiterhin funktionieren. Aber für jeden Temperatur Kanal wurde ein Gerät in HomeKit angelegt oder ?

Schau mal im Log laufen ja alle erkannten Geräte beim Start durch:

`
[2/10/2020, 5:57:17 PM] [HomeMatic CCU] Initializing platform accessory 'Testsirene'...
`

Da müssten entweder die Adressen stehen oder die Kanalnamen

**Comment by roe1974** [comment]
ja klar ... gerät sind da ... nur mit falschen werten ... hier ein screenshot mit 109:
![IMG_6058](https://user-images.githubusercontent.com/30420568/74172002-c590da80-4c2f-11ea-8fea-08fd91ec7f3d.PNG)

**Comment by roe1974** [comment]
mit 214 sehe ich :
0°    0°    0°
-0.5°   -0.5°    -0.5°

:(

**Comment by thkl** [comment]
ok strange .. ich muss mir mal so ein Ding zusammenlöten ...

**Comment by roe1974** [comment]
ich lasse dir eines zukommen ... schick mir deinen koordinaten auf roe@live.at
OK ?
lg Richard

**Comment by thkl** [comment]
ne kein Problem ich kann sowas aus einem Arduino bauen ;)

**Comment by roe1974** [comment]
okeeee .... wollte es dir erleichtern ;-) .. die Werte sind nämlich wichtig für mich ;)
btw: Tilt Sensor schon getestet ?

**Comment by thkl** [comment]
Ne passt schon. Darf ich vorstellen HM-WDS30-OT2-SM:

![Image](https://i.imgur.com/6aSH58n.jpg)

**Comment by roe1974** [comment]
hä ? ... dann bestelle ich bei dir und nicht bei ELV 😜😜😜😉

**Comment by roe1974** [comment]
für den creativen job hab ich dir eine spende geschickt :-)

**Comment by thkl** [comment]
> für den creativen job hab ich dir eine spende geschickt :-)

vielen Dank ... die Selbstbau Komponenten gibt es iÜ hier zum Nachbauen : https://asksinpp.de

**Comment by thkl** [comment]
![Image](https://i.imgur.com/JFfQvcy.jpg)

Da das Modul nur einen funktionierenden Temperatur hat, habe ich ihm in der Firmware kurzerhand mitgeteilt, Temp2=Temp1+1,5

**Comment by roe1974** [comment]
sehr geil !!!!! .... fehlt nur mehr der TILT Sensor ;-)

**Comment by roe1974** [comment]
machst du dann eine neue NPM version zum schluss ... habe derzeit wieder 109 am laufen und würde dann ein "neues" upgrade machen ;-)

**Comment by thkl** [comment]
ich würde das noch etwas beobachten ....

**Comment by roe1974** [comment]
okkeeeee .... no stress ;-)
geduld ist mein zweiter vorname :-P

**Comment by CM-UH** [comment]
Hallo Thomas,
ich hatte hier auch etwas komische wackelnde Werte. Ich habe die neuen Scripte installiert mal sehen.
Leider schaut das immer aus wie vorher V210
![image](https://user-images.githubusercontent.com/47689333/74265261-88494d00-4d02-11ea-8636-fc9da6ffca1f.png)
Die Werte werden regelmässig auf minus angezeigt
![image](https://user-images.githubusercontent.com/47689333/74265319-a7e07580-4d02-11ea-85d7-16f489b80a03.png)

**Comment by thkl** [comment]
's ist aber frostig bei Dir :) Also ich rechne an keinen Werten rum. Das sind Numbers die werden 1:1 weiter gereicht ...

**Comment by CM-UH** [comment]
Ich glaube ich weis was neues, irgendwie werden vom  HM-WDS30-OT2 verschiedene Kanäle genommen.
![image](https://user-images.githubusercontent.com/47689333/74268891-eb3de280-4d08-11ea-85e6-7d2038d44b0e.png)
Soll heisen manchmal Kanal 1 ok
Ab und an nimmt die Homebridge den Kanal 4 die negative Differenz.
Ist das ein Fehler oder fehlt mir da eine Konfiguration??

**Comment by thkl** [comment]
Nutzt Du schon die hier im Github aktualisierte Version ? Oder noch die originale npm Version.
Da ist noch ein Fehler, das die Kanäle vermischt werden.

**Comment by CM-UH** [comment]
Habe vorhin nochmal den letzten master rüber kopiert

**Comment by CM-UH** [comment]
Leider keine Besserung 😞

**Comment by thkl** [comment]
Ok .. ich sehe das Problem bei mir auch ... (das ging doch gestern :o( )

**Comment by thkl** [comment]
Ich glaub ich habs gefunden ... ChannelServices/HomeMaticHomeKitThermometerService.js tauschen dann sollte es aber gehen

**Comment by thkl** [comment]
jetzt aber

**Comment by thkl** [comment]
So die letzten 12h hat das bei mir mit den aktuellen Änderungen im Repository funktioniert. 

Ich würde meinen, ist durch.

**Comment by roe1974** [comment]
machst du eine npm ;) ?

**Comment by thkl** [comment]
218 done

**Comment by roe1974** [comment]
passt, der Sensor geht !
DANKE !

**Comment by CM-UH** [comment]
Jetzt passen die Werte wieder! 
Vielen Dank für die tolle Arbeit!
