### ISSUE TITLE
Versoin 214 .... nach jedem Neustart (Homebridge) stimmen einige Zustände nicht ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#531]
Bei jedem Neustart der Hombridge (aus Testgründen) stimmen einige Zustände nicht ?!??!
Betrifft Schaltaktoren und den Neigungssensor.
Schaltaktor kann durch 1x betätigen syncron gebracht werden ... Neigungssensor ist etwas Mühsam (jedesmal Garage hoch/runter)
Irgendwas stimmt da mit dem Cache nicht ... die Werte stimmen alle in der CCU ?!?!?

**Comment by thkl** [comment]
Hmm eigentlich sollte das nicht so sein. Denn beim Start ist der Cache leer und es wird auf jeden Fall die CCU gefragt. Ich werde das aber mal unter die Lupe nehmen.

**Comment by roe1974** [comment]
habe jetzt ca 5 restarts ... jedesmal stimmen irgendwelche geräte vom status nicht ... der neigungssensor ist aber zB immer falsch.... „do hot‘s wos „ 😉😉😉

**Comment by thkl** [comment]
Auf welchen Service  ist der Neigungssensor gemappt ?

Achja sind die Zustände auch falsch, wenn die Home(oder Eve) App geschlossen und wieder geöffnet wird ? (Muss nicht gekillt werden HomeScreen reicht). 

Denn beim Öffnen der App fragt HomeKit alle Geräte der aktuellen Ansicht ab und da die alle noch keinen Cache Eintrag haben frage ich die CCU. 

Achja Nach dem Neustart muss man etwas warten bi Homebridge komplett hochgelaufen ist, da wird vorher einmal die CCU ausgelesen das dauert bei vielen Geräten ggf 10-20sek. Wenn der Qr Code kommt ist das Ding hochgelaufen.

**Comment by roe1974** [comment]
Ich habe den Neigungssensor nicht speziell gemappt .... ist ein HM-Sec-TiS
In der Home App steht unter Geräteeigenschaften (109er) TILT_SENSOR

Verwende nur die HomeApp ..... und ja Zustand bleibt falsch auch nach 15min .. öffnen/schliessen .... mit/ohne abschiessen ... erst eine Bewegung bringt ihn "syncron"

Das mit dem Hochlaufen weiss ich ... denke aber nicht dass er alle durchläuft .... Sonst wäre der Neigungssensor richtig .... Wobei Probleme hatte ich mit geräten die zum Zeitpunkt des Updfates auf 214 keinen Zeitstempel in der CCU hatten, weil ewig nicht geschalten/Zustand verändert ....
Höngt es damit zusammen ? ... Wie nach einem Neustart, wo der Status der Geräte zwar da ist, aber keine Zeitstempel in der CCU zu sehen sind ...

**Comment by thkl** [comment]
Der Timestamp in der ccu ist mit Wurst.  Ich schaue, ob ich einen eigenen Wert im Cache habe und wenn nicht wird der bei der CCU erfragt. 
In einigen Fällen wird der Cache aber explizit gelöscht damit ich einen Wert der CCU bekomme. 

Ich probiere das mal aus, ich hab irgendwo so einen Sensor rumfliegen.

**Comment by roe1974** [comment]
naja, wie ich 214 installiert habe war ja noch kein cache da ... da hätte er alle aus der CCU holen müssen ... oder ?

**Comment by thkl** [comment]
Ne das Homematic Cache ist nicht persistent, lebt also nur im RAM und ist bei einem Neustart der Homebridge leer.

**Comment by roe1974** [comment]
er legt ja außer den json files (historie) auch noch andere pro aktor an ... was ist das ?
aja habe node 12.1.15 auf aktuellem buster

**Comment by thkl** [comment]
Das ist die History der Werte für die eve History. 
Wenn Du nur die HomeApp und nicht Elgato Eve als App benutzt, hat das keinen Einfluss.

**Comment by roe1974** [comment]
ok

**Comment by roe1974** [comment]
BItte #529 und #530 auch ansehen ;-)

**Comment by thkl** [comment]
closed cause of #536
