### ISSUE TITLE
[ServiceClassLoader] There is no service for HmIP-MOD-HO:DOOR_RECEIVER

### ISSUE THREAD

**Issue by allesistmoeglichoderauchnicht** [thkl/homebridge-homematic#532]
Mit der aktuellen Version 0.0.214 kann ich leider nicht mehr auf mein Garagentor zugreifen. 
Habe nichts geändert nur das update eingespielt: Jetzt kommt immer: 
[Homebridge] [2/9/2020, 6:23:46 PM] [HomeMatic CCU3] [ServiceClassLoader] There is no service for HmIP-MOD-HO:DOOR_RECEIVER
[Homebridge] [2/9/2020, 6:23:46 PM] [HomeMatic CCU3] [ServiceClassLoader] There is no service for HmIP-MOD-HO:DOOR_RECEIVER

**Comment by Soilman82** [comment]
Um "There is no service for..." Probleme zu beheben, kannst du den entsprechenden Service entweder in der channel_config.json (nicht Update-sicher) oder in deiner persönlichen config.json (Update-sicher) eintragen.

In deinem Fall konkret:

`
		{
			"type": "HmIP-MOD-HO:DOOR_RECEIVER",
			"service": "HomeMaticHomeKitGarageDoorOpenerService"
		}
`

**Comment by thkl** [comment]
Ich weiß jetzt nicht, warum der rausgefallen ist aber ich nehme ihn wieder auf.

**Comment by allesistmoeglichoderauchnicht** [comment]
Soll ich ihn selber eintragen oder machst du ein update, sodass ich über das update das einspielen kann?

**Comment by Soilman82** [comment]
@thkl Bin nicht sicher ob er rausgefallen ist oder noch nicht drin war, denn es steht ein fast identischer drin. Der HmIP-MOD-TM:DOOR_RECEIVER.

**Comment by thkl** [comment]
Ah TM gab’s noch nicht nur HO für Hörmann Antriebe. Ok dann ist der neu

**Comment by allesistmoeglichoderauchnicht** [comment]
ok es ist irgendwie mein Fehler. Ich wusste nicht, dass ich den wieder eintragen muss, wenn ich ein update einspiele. Du hattest mir das schon geschrieben, dass dieser Wert eingetragen werden muss... Ist halt jetzt rausgeflogen. Wenn du ihn mit aufnehmen könntest, wäre das super, dann muss ich den nicht wieder einpflegen beim update...

**Comment by allesistmoeglichoderauchnicht** [comment]
Bytheway: Auch wenn ich die alten Einstellungen einspiele, ich erhalte kein Feedback mehr von den Toren. Irgendwas scheint nicht mehr zu stimmen. Leider zeigt mir das Log nichts an...

**Comment by allesistmoeglichoderauchnicht** [comment]
Ich hab jetzt auf 219 geupdatet, alles neu gestartet (Docker, Server, Hoobs, Services, Iphone, AppleTV, Router,...) aber ich bekomme keine Antwort mehr von den Geräten über Homekit. Komischerweise erhalte ich nach dem Neustart der Services nach ungefähr 30min-1h bei den Toren die Nachricht (über das Iphone), dass sie geschlossen sind. Wenn ich dann jedoch in Homekit gehe, erhalte ich immer "keine antwort" von den Geräten und sie lassen sich nicht steuern. Ich habe sonst nichts geändert (keine Ports, Firewall oder sonstiges). Das Problem tritt im gleichen Wlan auf, brauche es natürlich nicht im Handynetz probieren, da isses aber logischerweise genauso... Alles ist beim alten, nur die Softwareversion NPM und homebridge-homematic ist auf 219. Ach und ich habe feste IP's für alle Geräte. Hier mal das logfile, was mir leider nichts hilfreiches mitgibt: 

[Homebridge] [2/13/2020, 7:15:49 AM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [2/13/2020, 7:15:49 AM] Loaded plugin: "homebridge-homematic"
[Homebridge] [2/13/2020, 7:15:49 AM] Registering platform "homebridge-homematic.HomeMatic"
[Homebridge] [2/13/2020, 7:15:49 AM] Loading 1 platforms...
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] Initializing HomeMatic platform...
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] [Core] merging configurations
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] Homematic Plugin Version 0.0.219
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] Plugin by thkl  https://github.com/thkl
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] Homematic is a registered trademark of the EQ-3 AG
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] running in production mode
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] will connect to your ccu at 192.168.178.76
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] IMPORTANT !! Starting this version, your homematic custom configuration is located in /hoobs/etc/homematic_config.json
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] [RPC] using xmprpc for communication with BidCos-RF
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] init RPC for BidCos-RF.
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] init RPC for VirtualDevices.
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] init RPC for HmIP-RF.
[Homebridge] [2/13/2020, 7:15:49 AM] Loading 0 accessories...
[Homebridge] [2/13/2020, 7:15:49 AM] API launched
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] [RPC] server for interface BidCos-RF. is listening on port 9090.
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] [RPC] Creating Local HTTP Client for CCU RPC Events
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] [RPC] server for interface VirtualDevices. is listening on port 9093.
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] [RPC] Creating Local HTTP Client for CCU RPC Events
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] [RPC] server for interface HmIP-RF. is listening on port 9092.
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] [RPC] Creating Local HTTP Client for CCU RPC Events
[Homebridge] [2/13/2020, 7:15:49 AM] [HomeMatic CCU3] if PONG is PONG CCU is alive
[Homebridge] [2/13/2020, 7:16:00 AM] [HomeMatic CCU3] Initializing platform accessory "Arbeitszimmer Jalousie 1".
[Homebridge] [2/13/2020, 7:16:00 AM] [HomeMatic CCU3] Initializing platform accessory "Garagentor 1".
[Homebridge] [2/13/2020, 7:16:00 AM] [HomeMatic CCU3] Initializing platform accessory "Hoftor 1".
[Homebridge] [2/13/2020, 7:16:00 AM] [HomeMatic CCU3] Initializing platform accessory "Terrassenfenster Jalousie 1".
[Homebridge] [2/13/2020, 7:16:00 AM] [HomeMatic CCU3] Initializing platform accessory "Terrassentuere Jalousie 1".
[Homebridge] [2/13/2020, 7:16:00 AM] [HomeMatic CCU3] Initializing platform accessory "Wohnzimmer Jalousie 1".
[Homebridge] [2/13/2020, 7:16:00 AM] Service is running on port 51826.
[Homebridge] [2/13/2020, 7:16:00 AM] [HomeMatic CCU3] [Core] will cache ccu response to /hoobs/etc/ccu.json
[Homebridge] [2/13/2020, 7:16:02 AM] [HomeMatic CCU3] [Core] NPM 0.0.219 vs Local 0.0.219

**Comment by Soilman82** [comment]
@allesistmoeglichoderauchnicht Hat es jetzt doch funktioniert oder warum ist es geschlossen?

**Comment by allesistmoeglichoderauchnicht** [comment]
Das Problem besteht noch aber nicht das in der Headline. Deshalb gab ich das hier geschlossen und ein neues aufgemacht
