### ISSUE TITLE
create a web config

### ISSUE THREAD

**Issue by thkl** [thkl/homebridge-homematic#533]
create a web page service for all the configuration items.  

Maybe ...

**Comment by Soilman82** [comment]
Was genau meinst du damit? Die Config.json von homebridge kann man ja schon ganz gut, z.B. über homebridge-config-ui-x im Web bearbeiten oder meinst du eine eigene Config speziell für dein Plugin? 🤔

**Comment by thkl** [comment]
Ja die nächste Version hat eine Unterstützung dafür. Aber damit kann ich nur einfache Parameter setzen. 

Zb Config Items für bestimmte Services lassen sich da nicht bearbeiten.

**Comment by thkl** [comment]
homebridge-config-ui-x Settings werden sich noch etwas verzögern:

Diese Funktion schreibt nur Daten in die config.json für welche sie eine Konfiguration im Schema hat. Da aber leider, aufgrund der umfangreichen Konfigurationsmöglichkeiten, die Settings in der config.json nicht vorhersehbar sind kann ich diese Funktion aktuell nicht nutzen, da sonst einfach Settings weggeworfen werden.

Lösung ist: Nur die unbedingt nötigen Settings in die config.json schreiben. Der Rest wird in ein eigenes config File ausgelagert.

Aber das dauert noch.

**Comment by Soilman82** [comment]
Verstehe, danke für die Info.

**Comment by thkl** [comment]
ich splitte jetzt die config auf https://github.com/thkl/homebridge-homematic/commit/c6c768036d6b6101a27ffbe0218c82f6149d4a20  einmalig werden jetzt beim Start die Einstellungen des homematic Plugins aus der config.json in eine homematic_config.json kopiert.  Und wenn beim Plugin Start die homematic_config.json gefunden wurde, werden diese Daten in die aus der config.json gemergt ... Damit sollte das Problem beseitigt sein und homebridge-config-ui-x für die Initiale Konfiguration des Plugins funktionieren.


Man kann natürlich weiter alles in der config.json pflegen, darf aber dann nicht den Einstellungsdialog von homebridge-config-ui-x nutzen.

**Comment by Soilman82** [comment]
Bei "das dauert noch" hätte ich jetzt mit mehr Zeit als nur 1 Stunde gerechnet. 😄 

Kannst du den aktuellen Stand von GitHub mal in eine npm beta packen? Dann würde ich es testen oder wolltest du eh ein offizielles Release machen?

**Comment by thkl** [comment]
> Kannst du den aktuellen Stand von GitHub mal in eine npm beta packen?

bitte 215@beta

**Comment by Soilman82** [comment]
Danke! Für mich sieht es erst mal gut aus. Die config.json sieht nun schmal aus und eine homematic_config.json wurde erstellt. Da steht alles drin, was vorher auch bei mir drin stand. 

Im Log sehe ich auch die Meldung: _IMPORTANT !! Starting this version, your homematic custom configuration is located in /var/lib/homebridge/homematic_config.json_

Wobei es im UI selbst nicht gemeldet wurde. Daher wäre es vermutlich sinnvoll, dass in den Release-Notes zu erwähnen, damit sich niemand wundert. Die werden beim Update angezeigt. Alle die mit der Konsole arbeiten, sehen es dann ja im Log. 

Könntest du denn nicht Dinge wie Filter, Outlets, Services, etc. über Arrays abbilden? Ich habe nur die Doku kurz überflogen, aber es las sich so, als könnte man damit die anderen Settings abbilden. Ist es "nur" aufwändig, dass alles in ein Schema zu packen oder ist es nicht möglich? Bei ersterem könne ich durchaus helfen. 😃

**Comment by thkl** [comment]
Naja das müssten dann Arrays mit frei definierbaren Texten und Größe sein .. und spätestens zb bei der Garagentor Konfig scheitert es dann .. da das ganze ja aber auch optional ist sehe ich da schwarz. Da mach ich mir lieber die Mühe einer eigenen Oberfläche

**Comment by roe1974** [comment]
> Die config.json sieht nun schmal aus und eine homematic_config.json wurde erstellt. Da steht alles drin, was vorher auch bei mir drin stand.

Also bei mir ist die config.json nach Erstellung der homematic_config.json unverändert ... also nix "schmal" ??
lg RIchard

**Comment by thkl** [comment]
Ich lösch da auch nix raus. Nur das Homebridge Ui würde alles raus werfen, wofür es kein UiSettting gibt. Deswegen kopiere ich das raus und merge beide Settings beim Start zusammen.

**Comment by thkl** [comment]
<img width="1535" alt="preview" src="https://user-images.githubusercontent.com/884355/74591006-4bd46480-5014-11ea-9c0b-63966f769774.png">

**Comment by thkl** [comment]
<img width="243" alt="Bildschirmfoto 2020-02-17 um 20 57 29" src="https://user-images.githubusercontent.com/884355/74683608-d14d4580-51c9-11ea-8729-2bf5a9b31e70.png">
<img width="487" alt="Bildschirmfoto 2020-02-17 um 20 57 34" src="https://user-images.githubusercontent.com/884355/74683612-d27e7280-51c9-11ea-8b19-1663b319f4a3.png">

**Comment by Soilman82** [comment]
Da b(r)aut sich was zusammen. 😃

Sieht gut aus.

**Comment by s0n1c** [comment]
Könnte jemand bitte die Readme/Howto/etc. aktualisieren, wie man mehrere CCU Instanzen ordentlich einpflegt? Das Plugin differenziert nämlich nicht mehr welcher CCU welche Konfiguration gehört und aus der Beschreibung wird auch nicht ersichtlich... homematic_config.json

**Comment by thkl** [comment]
ja dem ist so ... ich wusste bisher nicht, das jemand mehrere Instanzen auf einer Homebridge nutzt .. wie unterscheiden diese sich ? Dann benenne ich die homematic_config.json entsprechend

**Comment by thkl** [comment]
Ok ich habe nicht beachtet, das jemand mehrere Instanzen des gleichen Plugins in einer Homebridge nutzt ... Unterscheidung ist "name" in der config .. ich erweitere den config file namen entsprechen ..  Der ganze Zauber ist nur nötig, weil (ob das immer noch so ist, weiss ich nicht) Homebridge UI  Keys aus der Config löscht, die nicht im Schema stehen.

**Comment by thkl** [comment]
So, da sich gezeigt hat, das ein Switch auf das dynamische Accessories Konzept der homebridge nicht möglich ist, ohne das alle Geräte ihren Raum verlieren werde dich das mit der WebConfig etc wieder einstampfen und weiter Bugfixes für die 219++ machen.
