### ISSUE TITLE
Caching optional?

### ISSUE THREAD

**Issue by SebastianHarnau** [thkl/homebridge-homematic#534]
Ich nutze Homebridge mit dem Homematic-Plugin, um die umfangreiche Homematic-Installation "Siri-fähig" zu bekommen. Das funktioniert auch recht gut und zuverlässig, aber leider weichen die gecachten Zustände der Geräte oftmals im HomeKit ab, wenn wir die Haustechnik über Homematic-Apps (Pocket-Control, @Home 2.0) bedienen...

Es wäre toll, wenn man per Config das Caching der Zustände optional deaktivieren/aktivieren könnte, dann würde bei einer entsprechend leistungsfähigen CCU-Installation (RaspberryMatic auf RPi4/x86) der Status jedesmal live abgefragt werden können und so auch der Wirklichkeit entsprechen. :-)

**Comment by thkl** [comment]
Das sollte eigentlich nicht so sein, denn beim Schalten eines Aktors sendet dieser einen Event an Homebridge.  Dieser änder auch den Wert im Cache. Bitte mal prüfen, ob die Firewall Zugriffe von Homebridge  auf die XmlRpC Schnittstelle zulässt.  

Ansonsten kann das im DebugMode getestet werden. Da sollte im Moment der Änderung eines Aktorzustandes ein Event bei Homebridge eintreffen, der den neuen Zustand angibt.  Das führt dazu, das in der HomeKit App der Zustand auch sofort geändert wird.

**Comment by SebastianHarnau** [comment]
Oh, ich habe glaube ich den Fehler gefunden:
In der Konfig fehlte ein "enable_wired", da bin ich erst dank des neuen Konfigurationsdialoges drauf gekommen... ;-)

Danke trotzdem vielmals für deine Mühe und grundlegend für das tolle Plugin!!!
