### ISSUE TITLE
Version 214 .... Tilt Sensor HM-Sec-TiS wird  nicht richtig dargestellt

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#536]
@thkl 
Hi Thomas
Zum nachvollziehen mache ich noch einen Bug für den HM-Sec-TiS auf .....
Wie gesagt, wird der Status initial nicht richitg dargestellt....
lg Richard

**Comment by thkl** [comment]
ja ich bau mir den HM-Sec-TiS auch mal nach ...

**Comment by roe1974** [comment]
dachte den hast du ;-) ?

**Comment by thkl** [comment]
ne war der HmIP-SAM .. der liefert aber einen MOTION Datenpunkt .. dafür hab ich den MotionDetectorServiceIP schon angepasst.

der HM-Sec-TiS liefert nur STATE

**Comment by roe1974** [comment]
ah, OK !

**Comment by roe1974** [comment]
funktioniert mit 218
DANK !
