### ISSUE TITLE
Settings-Option für homebridge-config-ui-x implementieren

### ISSUE THREAD

**Issue by Soilman82** [thkl/homebridge-homematic#538]
Hi @thkl, 

da ich für Homebridge zur Konfiguration und Verwaltung das Plugin homebridge-config-ui-x nutze, würde es mich freuen, wenn du für dein Plugin das [hier](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI) aktivieren könntest. Dann kann man alternativ zum direkten Editieren der config.json, die nötigen Parameter auch über die Einstellungen im Config-UI vornehmen. Gerade für Anfänger vielleicht etwas einfacher. 

Danke und viele Grüße
Michael

**Comment by thkl** [comment]
Wird es im nächsten npm geben. 
Aber nur für die Settings: CCU Ip ; Gewerk ; HMIP ja/nein Wired Ja/Nein

Der Rest bekommt irgendwann mal eine eigene Weboberfläche.
