### ISSUE TITLE
Version 218 .... testing....WARN bei update

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#540]
@thkl 
Hi Thomas
Gerade auf 218 gegangen .....
Beim install kommt dieses WARN:

npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142

OK ?

lg RIchard

**Comment by thkl** [comment]
Jo ich hab da schon einen GreenKeeper Request, bin nur noch nicht dazu gekommen die Versionen zu aktualisieren.

**Comment by roe1974** [comment]
OK Dock ;-)
