### ISSUE TITLE
Version 218 ... HM-LC-Sw1-FM initial State

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#541]
@thkl 

Also 218 sieht seeeeeeeeeeeeehr gut aus.
Alleine der HM-LC-Sw1-FM liefert initial den falschen Wert (d.h. ist IMMER aus ... auch wenn in der CCU eingeschaltet ist.) Wird aber durch 1x betätigen in Home syncron ;-)
Vielleich tkannst da mal drüber sehen ;-)

lg Richard

**Comment by roe1974** [comment]
@thkl 
noch einmal getestet .. habe alle HM-LC-Sw1-FM auf "on" gestellt ... dann homebridge neu gestartet ... in HK waren alle "off" ... obwohl in CCU "on" .... einmaliges schalten bringt den Status syncron.
lg Richard
PS: Sonst ist die 218er perfekt ... weitere Spende folgt ;-)

**Comment by thkl** [comment]
Ich schau mir das mit dem Switch Aktor an, ich kann mir schon denken, wo das Problem ist.

**Comment by thkl** [comment]
Hmm ich kann das so nicht nachvollziehen. Sowohl als Lampe als auch als Outlet definiert machen die Dinger einen Initialen Query und der richtige Zustand wird angezeigt.

Bonusfrage: Wird beim öffnen der Home App (muss nicht gekillt werden HomeScreen reicht) der Status richtig gelesen und angezeigt ?

**Comment by roe1974** [comment]
nein ... nach einem Homebridge start bleiben diese Geräte falsch ...

**Comment by roe1974** [comment]
STOP !!!!!
bei beiden dieser Aktoren verwende ich das SPECIAL SWITCH SERVICE ... damit sie als Schalter dargstellt werden
liegt es daran ?
lgr icard

**Comment by roe1974** [comment]
es betrifft genau diese:

            "special": [
                {
                    "name" : "Zentrale Lüftung",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQxxxxx:1","switchtype":"Switch"}
                },
				{
                    "name" : "Heizung Ventil",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQxxxxx:1","switchtype":"Switch"}
                },
				{
                    "name" : "Heizung Pumpe",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQxxxxx:2","switchtype":"Switch"}
                },
				{
                    "name" : "Heizpatrone",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQxxxxx0:1","switchtype":"Switch"}
                },
				{
                    "name" : "Steckdose Ladegerät",
                    "type" : "HM-SPECIAL-SWITCH",
                    "parameter" : {"channel":"BidCos-RF.OEQxxxxx:1","switchtype":"Switch"}

**Comment by thkl** [comment]
Schau ich auch drauf. Der normale Switch hat aber das gleiche Problem .. (Datentypen) aber dafür hab ich inzwischen eine Lösung

**Comment by roe1974** [comment]
Bist der Beste 👍 👍 👍 
Spende ist raus !

**Comment by thkl** [comment]
und schon sind wir bei 219

**Comment by roe1974** [comment]
passt !!! funktioniert jetzt auf anhieb
DANKE !!! ... perfect work !
lg Richard
