### ISSUE TITLE
Version 218 .... was ist "homematic_config.json" ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#542]
Hi Thomas

Wie der Titel schon sagt wurde mit 218 diese json angelegt ..... 
Aktualisiert sich das automatisch wenn die config.json geändert wird ?

lg Richard

**Comment by thkl** [comment]
Bitte lesen Sie dazu auch die Bedienungsanleitung https://github.com/thkl/homebridge-homematic#configuration-changes-version--214

**Comment by roe1974** [comment]
alles klar .... danke ;)
man sollte ab und zu readme lesen :)

**Comment by thkl** [comment]
auch in Vorbereitung für #533
