### ISSUE TITLE
Version 218 .... HM-SCI-3-FM initial State Kanal 2 nicht korrekt...

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#543]
@thkl , Hi Thomas

Hab grad kurz einen Schock bekommen .... der HM-SCI-3-FM der den Überlauf der Klimapumpe anzeigt steht auf "geöffnet" .... obwohl in der CCU auf geschlossen (puhhhh) :-P
Ich Habe 4 Stk. von den Dingern ... Der eine der die Klima überwacht ist der einzige der falsch angezeigt wird ... Einziger Unterschied ist, dass ich bei diesem Kanal 2 verwende ... bei allen anderen Kanal 1 ... kann es daran liegen ?

lg Richard

**Comment by thkl** [comment]
Kann das Gleiche sein, wie bei den diff TempFühlern. Eigentlich ist das nur ein Property was falsch ist.

**Comment by roe1974** [comment]
passt funktioniert, teste am abend noch am aktor ob er öffnen richtig anzeigt ;-) ... dann schliesse ich hier .....

**Comment by roe1974** [comment]
funktioniert perfekt, danke !
