### ISSUE TITLE
HomeMaticHomeKitBlindSlatServiceIP .. auch für HM umsetzbar ?

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#544]
@thkl Hi thomas
Habe heute erst gesehen, daß Du irgendwann mal eine spezielle "HomeMaticHomeKitBlindSlatServiceIP" für den IP Jalousieaktor gebaut hast ... dort kann man ja die Lamellen extra einstellen.... (Siehe #197)
Das gleich habe ich für HM in Betrieb ..... den HM-LC-Ja1PBU-FM ... Könntest Du das für HM auch realisieren ? ... Datenpunkte & WebUI Screenshot anbei .....
lg Richard
[HM-LC-Ja1PBU-FM.pdf](https://github.com/thkl/homebridge-homematic/files/4198997/HM-LC-Ja1PBU-FM.pdf)
![Unbenannt](https://user-images.githubusercontent.com/30420568/74447359-85249d00-4e79-11ea-91a1-f0b582a5d810.JPG)

**Comment by roe1974** [comment]
@thkl  ... geht das hier auch ? ;)

**Comment by thkl** [comment]
Ich denke schon.  Muss ich mir mal die Doku zu dem Ding anschauen.

**Comment by roe1974** [comment]
@thkl  .... das wäre sehr geil ;-)

**Comment by wasoon1974** [comment]
Hallo zusammen, bin auf der Suche nach einer Lösung für meine Lamellen-Steuerung auf dieses Issue gestossen. Habe genau dasselbe Setup. Gab es hier bereits News dazu für HM-LC-Ja1PBU-FM. Danke Euch
