### ISSUE TITLE
Feature request: fake-Temperatur-Service [für Variablen aus PV Anlage]

### ISSUE THREAD

**Issue by ChrWi** [thkl/homebridge-homematic#548]
Ich schreibe Momentanwerte aus meiner PV Anlage bzw. dem dazugehören Solarlog Datenlogger per Homematic Skript in einige Systemvariablen. Jetzt würde ich die Werte gerne in Homekit sehen. Mit Blick auf das Wiki gibt es aktuell nur Möglichkeiten für True/False sowie die Services für Alarm und Batterie. Dies passt für meinen Fall nicht. Mit Blick auf z.B. max. 9000W Momentanertrag und einer denkbaren Umrechnung auf kW wäre für mich ein fake-Temperatur-Service naheliegend (unter Vernachlässigung der Einheiten). Vielleicht geht technisch auch etwas anderes. Die Systemvariablen sind als Zahl definiert.
Im Homebridge/Homematic-Umfeld gibt es leider keine direkte Verarbeitung von Solar-Energiedaten. Im iobroker gibt es ein [Plugin](https://github.com/iobroker-community-adapters/ioBroker.solarlog), die Überführung dessen Werte in Homekit ist für mich nicht praktikabel.

**Comment by thkl** [comment]
Die Homematic Leistungsmesser haben auch eine History. Daher müsste man sicher nicht auf die Temperatur ausweichen.

Änderungen an Variablen werden prinzipiell nicht von der CCU nicht nach draussen gemeldet.
Man müsste also dem Service eine virtuelle Taste als Trigger mitgeben. Das Script in der CCU müsste dann die Variablen schreiben und anschließend die virtuelle Taste auslösen, um einen Homebridge Event zu triggern.

Zusammengefasst:

Key wird getriggert
Homebridge liest den zugehörigen Variablenwert aus und schreibt den in das Gerät + die History

Das lässt sich machen

**Comment by ChrWi** [comment]
Hallo Thomas,
ich kämpfe noch mit dem Einstieg, wie ich meine Systemvariable mit dem passenden Typ und Service verknüpfe, bekomme ich nicht hin. Aktueller Versuch:

`"special":[
     {
          "name" : "Solar Ertrag (W)",
          "type" : "ENERGIE_METER_TRANSMITTER",
          "parameter" : {
              "trigger" : "BidCos-RF.BidCoS-RF:10.PRESS_LONG",
              "variable" : „Solarertrag"
          }
      },`

Wo liegt mein Fehler? Oder ist der Typ einfach falsch?

Danke und Grüße

**Comment by thkl** [comment]
Das funktioniert so nicht, da der Energy Transmitter Typ eine Messteckdose und die entsprechenden Datenpunkte erwartet. Dazu muss ich eine eigene Serviceclass schreiben.

**Comment by thkl** [comment]
@ChrWi Frage dazu: Was liefert denn die PV Anlage an Daten, welche zu HK sollen ? 
aktuelle Leistung ? Kumulierte kWh ?

ich frage für den passenden Service

**Comment by ChrWi** [comment]
Hallo Thomas,

in Summe liefert die Anlage bzw. der Datenlogger eine Reihe von Daten (siehe Anlage).
Persönlich interessiert mich nur die Werte Pdc (Momentante Gesamtleistung aller Wechselrichter, Watt - Index 102) und consPac (Momentanverbrauch, Watt - Index 110), welche ich jeweils als Systemvariable abbilde.

**Comment by ChrWi** [comment]
[daten.pdf](https://github.com/thkl/homebridge-homematic/files/4272166/daten.pdf)

**Comment by thkl** [comment]
Ok. Also würde ein normaler Energiezähler der Watts ausgiebt ausreichen. Man kann den ja dann verdoppeln für unterschiedliche Variablen

**Comment by ChrWi** [comment]
Ja, das deckt sich mit meinem Verständnis.
Danke!

[iOS]
