### ISSUE TITLE
HMIP BSM Automation triggert auf beiden Kanälen

### ISSUE THREAD

**Issue by Horizon0156** [thkl/homebridge-homematic#549]
Hallo,

Erstmal vielen Dank für das tolle Projekt. Ich habe jedoch aktuell Schwierigkeiten bei den Automationen eines Schalter Events des HMIP BSM Wandaktors. 

Auf Grund der letzten Aktivitäten verfasse ich das Ticket erstmal auf deutsch. In case of any language / communication problems, please let me know... I will translate it to English if preverred 😉  

Jedenfalls versuche ich via Automation die Kanäle 1 und 2 auf Zustände meiner Hue Birnen zu Mappen (50% oder aus). Allerdings feuern beim drücken des Tasters für Kanal 1 beide Kanäle in Homebridge, wodurch die Lampe direkt wieder ausgeht. 

**Which Homematic Device or Service the bug is about**
HMIP BSM

**To Reproduce**
1. Automation anlegen: 
Kanal 1 kurz-> Hue 50%
Kanals 2 kurz -> Hue aus

**Actual behaviour **
Beide Kanäle feuern beim schalten des ersten Kanals wodurch die Lampe nur kurz aufflackert

**Expected behavior**
Nur Kanal 1 feuert und die Lampe schaltet sich ein. Respektive aus wenn Kanal 2 gedrückt wird

Vorab besten Dank für die Unterstützung

**Comment by thkl** [comment]
Das müsste der KeyService sein, der verwendet wird ?

Der läuft bei diesem Taster in die gleichen Probleme, wie bei anderen Issues mit Geräten, wo es mehrere gleiche Kanäle gibt. 

Lösung:
Im File HomeMaticHomeKitKeyService.js (liegt unter ChannelServices)

als erste Zeile bei createDeviceService

this.isMultiChannel = false

einfügen.

**Comment by Horizon0156** [comment]
Ja, das mag sein. Probiere ich morgen direkt aus und gebe dann Feedback.

Danke für die schnelle Rückmeldung 👍🏻

**Comment by molkemolko** [comment]
Hallo zusammen,

ich bin über diesen Thread gestolpert, der wahrscheinlich die Lösung meines Problems beinhaltet, nur leider verstehe ich diese (noch). :-)

Ich habe ebenfalls einen HMIP-BSM und zudem einen HM-PBI-4-FM in HomeKit via Homebridge integriert. Wenn ich eine Taste drücke, erkennt HomeKit einen Tastendruck auf allen Tasten des jeweiligen Tasters. Ich habe bisher keine Services o.ä. angelegt. Muss ich das tun oder wie bekomme ich das getrennt?

Im Prinzip möchte ich das gleiche bewirken wir @Horizon0156 . Taste 1 soll nichts am Aktor selbst bewirken, sondern via HomeKit Automation eine Szene triggern. Taste 2 soll eine andere Szene triggern.

Könnt ihr mir verraten, wir ihr das geschafft habt?

Danke! :-)

**Comment by molkemolko** [comment]
Hab mich noch mal reingefuchst und das Problem nun doch schon selbst gelöst! :-)

Ich habe den ChannelServices Ordner auf dem Raspberry gefunden und die entsprechende Zeile in der entsprechenden Datei geändert.

Vielen Dank!

**Comment by fugazzy** [comment]
Bin auch über diesen Fehler gestolpert und konnte ihn mit dieser Änderung beheben. Vielen Dank!
Kommt die Lösung auch in eine freigegebene Version?
