### ISSUE TITLE
Räume nach einem Neustart der CCU

### ISSUE THREAD

**Issue by offle** [thkl/homebridge-homematic#55]
Hallo,

Vorgestern gab es bei uns einen Stromausfall. Durch den Neustart waren in HomeKit die Räume der Homematic Geräte wieder auf Standardraum zurückgefallen. Hast Du eine Möglichkeit, die Raumkonfiguration zu speichern oder ggf. an Homekit mitzugeben, oder liegt das Problem bei Homekit?

Viele Grüße 
Ole

**Comment by Apollon77** [comment]
Ich hab solche Effekte regelmässig und wird gerade auch bei Homebridge diskutiert:
https://github.com/nfarina/homebridge/issues/874

**Comment by thkl** [comment]
Nein die Raumkonfig wird in HomeKit gemacht

**Comment by offle** [comment]
OK, danke. Dann mache ich hier mal zu :)
