### ISSUE TITLE
Wired aktualisiert den Status nicht bei mehreren Homebridge Instanzen mit aktiviertem Wired

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#553]
Seit dem Update von 109 auf 219 wird der Status bei Änderungen meiner Wired HMW-Sen-SC-12-DR und HMW-IO-12-Sw14-DR nicht mehr aktualisiert. Ein an/aus kommt von Home > CCU3 an, von der CCU3 > Home aber kein an/offen als auch für aus/geschlossen. Beim Neustart der Homebridge werden die korrekten Status geladen, sowohl für an/offen als auch für aus/geschlossen.

**Comment by iuliusmaximilian** [comment]
@thkl Kannst du dir das wohl mal anschauen ?

**Comment by thkl** [comment]
Werden die Stati aktualisiert wenn Home nach einer Aktualisierung fragt (also Raum Wechsel zum Beispiel, oder beim öffnen der Home App) ?

**Comment by iuliusmaximilian** [comment]
@thkl Danke für die schnelle Rückmeldung, ich konnte das Problem soweit eingrenzen, dass dies nur auftritt wenn mehrere Homebridge Instanzen mit "wired=true" laufen. Wenn ich nur eine Instanz mit "wired=true" starte oder von allen Instanzen nur eine mit "wired=true" konfiguriere und alle starte tritt das Problem nicht auf. D.h., dann werden in beide Richtungen die Events richtig verarbeitet.

Da ich jetzt einen Workaround habe ist es nicht mehr so dringend. Interessant wäre es trotzdem heraus zu finden ob das an meiner Konfiguration liegt oder ob es ein Bug ist der gefixt werden kann: Gleiches habe ich schon lange mit "hmip=true" bemerkt, warum ich alle HMIP Komponenten in einer Instanz laufen lasse, was langsam an seine Grenzen stösst.

**Comment by thkl** [comment]
Momentchen .. also es laufen mehrere Instanzen von Homebridge auf einem System ? Also an der Stelle würde ich mal das ganze im Debug Mode laufen lassen und schauen, ob die Events überhaupt von der CCU bei Homebridge ankommen

**Comment by iuliusmaximilian** [comment]
Events kommen nicht an, hatte das mal vor einiger Zeit gemeldet https://github.com/thkl/homebridge-homematic/issues/261

**Comment by thkl** [comment]
Hmm das alte Ticket sagt das das schief geht wenn alle Instanzen gleichzeitig auf die CCU Connected. Ich könnte mal eine optionale random Verzögerung in den Init der Schnittstellen bauen. 
Um welche Zeitspanne handelt es sich da ungefähr ?

**Comment by iuliusmaximilian** [comment]
@thkl Ich habe mal alle Instanzen runter gefahren und nur zwei Instanzen die wired = true haben parallel mit etwas Abstand im Debug gestartet: 

Bei der "Homebridge4" kommen die Wired-Events korrekt an, bei der "Homebridge3" kommen parallel die Events nicht an.

Ausgelöst habe ich mehrmals den "BidCos-Wired.OEQ0129171:13" an/aus über die WebUI der CCU3:

[homebridge4.log.zip](https://github.com/thkl/homebridge-homematic/files/4276242/homebridge4.log.zip)

[homebridge3.log.zip](https://github.com/thkl/homebridge-homematic/files/4276241/homebridge3.log.zip)

**Comment by thkl** [comment]
Ich kann mir vorstellen woran es liegen könnte. Der RPC Init auf die Schnittstellen erfolgt immer mit dem Namen homebridge_[InterfaceName] .. kommt also von allen Instanzen mit der gleichen ID .. ggf liegt das daran. Ich werde mal die letzen 2 Stellen der Mac mit dazu packen.

**Comment by iuliusmaximilian** [comment]
Die Instanzen laufen alle auf dem gleichen Rasp. Ist die Mac nicht Netzwerkkarten abhängig, so dass diese immer noch bei allen Instanzen gleich wäre ?

**Comment by thkl** [comment]
Och nööööö 🤣... ok dann nen Parameter in der Config

**Comment by iuliusmaximilian** [comment]
Kann ich das einfach rein patchen?

**Comment by iuliusmaximilian** [comment]
@thkl Kann ich das einfach rein patchen?

**Comment by thkl** [comment]
Muss ich mal nachschauen wo, ich hab in der GitHub Version schon alles umgeworfen.

**Comment by iuliusmaximilian** [comment]
@thkl Kannst du bitte mal schauen ob ich das einfach rein patschen kann
