### ISSUE TITLE
CUxD Update Trigger (same as with variables)

### ISSUE THREAD

**Issue by JensBonse** [thkl/homebridge-homematic#554]
Hallo Thomas,

wäre es möglich, wie bei den Variablen einen Update Trigger für CUxD Geräte zu implementieren?

**Comment by thkl** [comment]
Was soll der machen ?

**Comment by JensBonse** [comment]
Wenn variablen geupdated werden, dann löst das ja keinen Event aus, den du mit HomeBridge abfangen kannst um die Werte zu aktualisieren.
Das Gleich ist es ja auch bei CUxD. Das schickt ja auch keinen Event. Durch den trigger könnte man dann zumindest auf der HM den Trigger setzen, damit HomeBridge den neuen Wert einließt.

**Comment by CameronVIE** [comment]
Same here!
Ich hab mir den trigger button auch in HK eingebunden und sehe, dass er kurz bumpt, wenn ich eine Systemvar ändere. Aber eingelesen wird nicht neu! Muss immer HK slidend schliessen und wieder öffnen. Das löst dann das Neueinlesen aus.
