### ISSUE TITLE
Status CUXd devices 

### ISSUE THREAD

**Issue by shinzan111** [thkl/homebridge-homematic#558]
Hello Thomas, 

since 2 updates I am facing that my CUXd-switches which I use for scenes, do not show the correct current state.  Can you please help here?

Before it worked perfect.

**Comment by thkl** [comment]
Did they show the correct state after closing and reopening the home app ?

**Comment by r2ixuz** [comment]
Can confirm that behaviour. Had to reinstall Homebridge yesterday from backup, so it changed automatically my Homematic plugin version from 0.1.2 (I know, it was beta) to 0.0.219.

I use it to control my FHT thermostats. With the latetst stable version I can set a temperature successfully but Homebridge does not "known" afterwards the changed target temperature. Even if I force close and reopen the Homekit app.

Back to 0.1.2 everything works normally as expected again.

**Comment by thkl** [comment]
All these devices are CuxD devices ?

If you want, you can try the github version. There all the used interfaces will automatically connect. Maybe this will work better

**Comment by r2ixuz** [comment]
Yes, I use Homematic mainly for FHT CUXd devices (4 units).  There is only one other HM-IP outdoor temp sensor, which works in both versions as expected.

**Comment by r2ixuz** [comment]
This problem persists with version 0.1.231 on Homebridge version 1.0.3 .
---

Leider ist das gravierend, da man so die Temperatur nicht mehr setzen kann. Eine Änderung von z.B. 19 Grad auf 22 Grad funktioniert. Aber sobald man wieder zu 19 Grad zurück will, für das Homekit nicht aus, da es ja keine Änderung ist (Homekit sieht noch den alten Soll-Zustand).

Installiere ich die Beta 0.1.2 mit HB 1.0.3 läuft das Ändern der Temperaturen problemlos wie gewohnt. Wäre echt super, wenn du das auf deine todo aufnehmen könntest, da ich fürchte, dass die alte homebridge-homematic Version 0.1.2 Beta mit einer der kommenden Homebridge Versionen gar nicht mehr laufen wird... ;( Danke!

**Comment by r2ixuz** [comment]
Is this project dead? :(
