### ISSUE TITLE
Minimal-Werte für Jalousien funktionieren nicht

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#559]
Hi, bei mir greifen die Einstellungen aus https://github.com/thkl/homebridge-homematic/wiki/Rolladen-minimale---maximale-Werte nicht. Die Jalousie zeigt "1% geöffnet" an, trotz der folgenden Einstellung:

```
                "special": [{
                        "HM-LC-Bl1PBU-FM:LEVEL": {
                                "minValueForClose": 3
                                }
                }],
                "services": [
```

**Comment by thkl** [comment]
es muss heissen HM-LC-Bl1PBU-FM:BLIND ...

**Comment by iuliusmaximilian** [comment]
Die Jalousie zeigt "1% geöffnet" an, trotz der folgenden Einstellung:
```
          "special": [{
                        "HM-LC-Bl1PBU-FM:BLIND": {
                                "minValueForClose": 3
                                }
                }],
                "services": [
```

**Comment by thkl** [comment]
kann das noch bis zum Update auf die WebUI Version warten ? Da ändern sich auch die internen Settings. Inkl UI für den ganzen Kram:

<img width="821" alt="Bildschirmfoto 2020-03-02 um 20 59 23" src="https://user-images.githubusercontent.com/884355/75712758-c06ffa00-5cc8-11ea-9763-dcc835c581e8.png">

**Comment by iuliusmaximilian** [comment]
Klaro, Thx!

**Comment by thkl** [comment]
Wird in der nächsten Version funktionieren. Da ich jetzt auch die Anbindung an HVL fertig habe, konnte ich das anhand meiner Tradfri Rollos testen. ;)
