### ISSUE TITLE
Gerätenamen: Sonderzeichen aussortieren ... 

### ISSUE THREAD

**Issue by Apollon77** [thkl/homebridge-homematic#56]
Mir ist aufgefallen das wohl dem Homekit "nicht Buchstaben" (ich habe z.B. "-" drin und es wird immer noch ":1" drangehängt) nicht gefallen und er das editieren der Namen nur erlaubt wenn ich den Namen lösche.
Macht es Sinn die Namen gleich von vorn Herein aufzuräumen?

**Comment by thkl** [comment]
Ja.   Das schon.  Müsste ich nur wissen, was dem HomeKit nicht gefällt.  Also quasi eine Blacklist an Zeichen.

**Comment by Apollon77** [comment]
laut Eve alles was nicht Bustaben und Leerzeichen sind. Zittat "muss aussprechbar sein".

Also ich weiss das mind "-" und ":" böse sind

Was "internationale Sonderzeichen" angeht ist das natürlich so eine Sache :-(

**Comment by thkl** [comment]
gefixt in aktueller github version .. 
ich ersetze .:#_()-  gegen ein space 
Dadurch ändern sich aber ggf die Namen , und Szenen könnten nicht mehr funktionieren, da die Geräte nicht mehr da sind ... (bzw jetzt einen anderen Namen haben)
