### ISSUE TITLE
Neue Variablen werden nicht mehr registriert

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#560]
Ich bin auf einem Rasp 3 auf der 219 mit einer CCU3 3.51.6. Jetzt habe ich eine neue boolean Variable in der CCU angelegt und für eine meiner Homebridge Instanzen in der Config eingetragen. Allerdings wird diese nicht erkannt. Auch im Debug taucht die Variable gar nicht im Log auf. Hier mal meine Config, Variablen habe ich allerdings umbenannt. Gibt es ein Limit für Variablen ?

```
...
"programs": ["Pro1"],
"variables": [
"NEW",
"Var1",
"Var2",
"Var3",
"Var4",
"Var5",
"Var6",
"Var7",
"Var8",
"Var9",
"Var10",
"Var11",
"Var12",
"Var13",
"Var14",
"Var15",
"Var16",
"Var17",
"Var18",
"Var19"],
"variable_update_trigger_channel": "Hombridge_Trigger",
...
```

**Comment by thkl** [comment]
ich kann das jetzt nicht mehr nachvollziehen, da ich schon zu viel im Code für die nächste Version geändert habe. Aber dort kann man dann die Variablen via WebUI hinzufügen. Diese werden dann ohne Neustart der Homebridge hinzugefügt /gelöscht

**Comment by iuliusmaximilian** [comment]
Habe die Änderung "Configuration Changes Version > 214" nicht gesehen, wenn man es richtig macht, funktioniert es auch.
