### ISSUE TITLE
Wandthermostat HM-CC-TC

### ISSUE THREAD

**Issue by WeltenbummlerKA** [thkl/homebridge-homematic#563]
Ich habe mehrere Wandthermostate von Homematic. Diese werden auch alle in der Homebridge angezeigt. Allerdings brauche ich nur die aktuelle Temperatur und die Luftfeuchte. Genau diese beiden Werte kann ich nicht getrennt abrufen. Die Temperatur zeigt er mir an, aber in 0,5°C Schritten und die Feuchte nur mit Rechtsklick.

Gibt es irgendeine Möglichkeit die Feuchte und die Temperatur einzeln auszulesen?

Die Regelung brauche ich nicht, da leider alle Heizkörperventile nach 5 Jahre kaputt gingen.
<img width="789" alt="Bildschirmfoto 2020-03-02 um 14 15 49" src="https://user-images.githubusercontent.com/61679394/75679826-a31f3980-5c90-11ea-8b96-fcc45d37f32d.png">

**Comment by thkl** [comment]
Wie die Daten angezeigt werden hängt immer von der HomeKit App ab. Der Screenshot zeigt zumindest, das die da sind.
