### ISSUE TITLE
HmIP-PSM wird nur als Licht angezeigt

### ISSUE THREAD

**Issue by glowfishDE** [thkl/homebridge-homematic#567]
Hallo,

wenn ich die Schalt/Mess/Steckdose HmIP-PSM versuche ins Homekit zu bringen (was auch gelingt), wird dieser immer nur als Licht angezeigt.

Obwohl ich ihn in der config.json mit der "outlets" Sektion wie folgt eingetragen habe:

"platforms": [
        {
            "platform": "HomeMatic",
            "name": "HomeMatic CCU2",
            "ccu_ip": "x.x.x.x",
            "enable_hmip": "true",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [
                "BidCos-RF.OEQ0212345:1",
                "HmIP-RF.0001D3C9912345:3",
                ],
            "doors": [
                "BidCos-RF.OEQ1312345:4"

Der BidCos-RF funktioniert einwandfrei - aber der HmIP-RF.Seriennummer:Kanal3 funktioniert leider nicht.

Was mache ich falsch? Wie kriege ich den HmIP-PSM auch als Steckdose und nicht als Licht in die Home App ?

Danke

**Comment by thkl** [comment]
Nur den Messkanal ins HomeKit Gewerk aufnehmen .... Rest kommt alleine dazu

**Comment by thkl** [comment]
Sieht dann in eve so aus :
 ![Image](https://i.imgur.com/FBp9zbY.jpg)

**Comment by glowfishDE** [comment]
Ach wie krass :)

Danke! das wars :)
