### ISSUE TITLE
Homebridge verursacht "Gerätekommunikation ist gestört"

### ISSUE THREAD

**Issue by TheRoolBool** [thkl/homebridge-homematic#57]
Hallo, seit dem 48er Update bekomme ich in der CCU bei den Servicemeldungen von den Dimmern jetzt sehr oft eine "Gerätekommunikation ist gestört" Meldung. Wenn ich die Homebridge stoppe, kommen die Meldungen nicht. Starte ich die Homebridge wieder, dann kommen die Meldungen nach kurzer Zeit wieder.

Und:
Das Gerät "HM-LC-RGBW-WM" lässt sich mit der 48er Version nicht schalten.

**Comment by thkl** [comment]
Schau mal bitte ob die 0.0.49 das immer noch macht. In meinen Tests ist das nicht mehr so

**Comment by TheRoolBool** [comment]
Jetzt passt es. 

Jetzt nur noch den RGBW Dimmer mit rein und dann ist wieder alles top 👍🏻

**Comment by thkl** [comment]
Ja ich muss den Dimmerfoo dann nur noch mit auf den RGBW kopieren. Aber super wenn das Problem gelöst ist ...

**Comment by TheRoolBool** [comment]
Jepp, scheint gelöst. Klasse Arbeit, Danke.
