### ISSUE TITLE
Frage: Welche Funktion haben die Dateien <hostname>_BidCos-RF.KEQXXX:1_persist.json

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#572]
In meinem Homebridge-Verzeichnis finde ich viele Dateien, die den Aufbau

```
<hostname>_BidCos-RF.KEQXXX:1_persist.json
```

Welche Funktion haben die Dateien? Sind das Caches?

Hintergrund der Frage: Ich betreibe Homebridge mit Homebridge-Homematic und jedes mal läuft die Instanz auf einer von fünf verschiedenen Maschinen, d.h. ich finde Dateien, die in meinem Fall "kube10" oder "kube13" haben.

**Comment by thkl** [comment]
da werden die Eve History Daten gespeichert
