### ISSUE TITLE
Homematicschalter eine Taste trigget alle in Homekit

### ISSUE THREAD

**Issue by BrianCathill** [thkl/homebridge-homematic#574]
Hallo zusammen,

ich hoffe ihr könnt mir helfen. Ich habe homebridge in der aktuellen Version laufen und alles funktioniert. Nun habe ich Homematic Taster (HM-DIS-WM55 und HM-PB6-Wm55) in homebridge eingebunden. Diese erscheinen auf dem Iphone und sollen hier so eingestellt werden, dass sie Lampen schalten. 
Beim drücken von einer Taste auf dem HM Schalter werden aber nun alle Taster auf dem Iphone geschaltet. Dabei ist egal welche HM Taste ich drücke. Das selbe gilt für virtuelle HM Taster.

Könnt Ihr diesen FEhler reproduzieren und habe eine Lösung für mich? Das wäre wirklich super.
Viele Dank schonmal

**Comment by molkemolko** [comment]
Hi zusammen,

ich habe leider das gleiche Problem. Ich habe den HM-PBI-4-FM und den HMIP-BSM in Home via Homebridge integriert. Wenn ich eine Taste drücke, erkennt Home einen Tastendruck auf allen Tasten des jeweiligen Tasters.

Hat jemand einen Tipp? :-)

Liebe Grüße!

**Comment by molkemolko** [comment]
Hi zusammen,

ich habe die Lösung gefunden, dieser Thread hat mir geholfen: https://github.com/thkl/homebridge-homematic/issues/549

LG!

**Comment by fugazzy** [comment]
Bin auch über diesen Fehler gestolpert und konnte ihn mit Änderung aus #549 beheben. Vielen Dank!
Kommt die Lösung auch in eine freigegebene Version?
