### ISSUE TITLE
Sprinkler (Gartenbewässerung)

### ISSUE THREAD

**Issue by v0r73x** [thkl/homebridge-homematic#576]
Hi thkl :)

ich versuche ein Aktor als Sprinkler einzurichten, jedoch funktioniert das nicht so trivial wie ich es mir dachte. 
Verwenden wollte ich meine Sonoff (die ich schon per CuxD  in Homebridge eingebunden habe) als sprinkler in der Home App anzeigen lassen.  

ich habe also gleich in der /var/lib/homebridge/homematic_config.json den Eintrag:

"valves":["CUxD.CUX2801001:4"]

gesetzt, Jedoch hat das nicht funktioniert. Wenn ich den Aktor einfach als Homekit Gewerk "parsen" lasse, erkennt er Ihn als Schalte und funktioniert einwandfrei. 

Ich hätte halt gern die Sprinkler Services auf den Aktoren ... ;(

Frage:
das es nicht ganz verständlich ist - muss ich den Aktor auch dem Gewerk Homekit zuweisen damit er erkannt wird und erst dann erkennt dein plugin in der .config das er es als Sprinkler modifizieren muss? 

was mir noch aufgefallen ist: wenn ich die HomeApp auf dem iphone öffne und nach leeren den caches erstmals aufgerufen wird sehe ich kurz den Sprinkler und innerhalb 1 sekunde verschwindet es wieder ... 

ich verwende 
 Debian GNU/Linux Stretch (9) auf einem 4GB rock64
Node.js Version | v12.16.1
Npm Version | v6.13.4
homebridge Version 0.4.53 konfiguriert als service über hb-service mit user homebridge

**Which Homematic Device or Service the bug is about**
[eg. HM-.... , HmiP-...]

**To Reproduce**
1.  configured as above described
2.  clear cached accessories
3.  restart service 
4.  several times with no change - tried with other BidCos device same result 

es wäre super wenn du hier helfen könntest, ich weiss nicht wie ich es debuggen könnte.

besten dank aus der Hauptstadt 
- v0r73x -

**Comment by dkrizic** [comment]
Hi,

ich verwende einen HM-LC-Sw4-DR von denen ich drei Kanäle in das Gewerk Homebridge gelegt habe:

![image](https://user-images.githubusercontent.com/1181349/77886820-d215d480-7269-11ea-870f-16d568ada7c0.png)

In der homebridge.config habe diese drei Kanäle als valves definiert:

```
  "valves": [
    "BidCos-RF.LEQ0281557:1",
    "BidCos-RF.LEQ0281557:2",
    "BidCos-RF.LEQ0281557:3"
  ],
```

und bei mir sieht es so aus: 

![image](https://user-images.githubusercontent.com/1181349/77886985-16a17000-726a-11ea-939c-6a195525bad3.png)

Der einzige Unterschied ist wohl, dass es bei mir HomeMatic-direkt ist und bei Dir CUxD... Aber warum es nicht geht, sehe ich auch nicht. Hier würde @thkl helfen.

**Comment by thkl** [comment]
An CuxD binde ich keinen Event Listener daher könnte das das Problem sein, wenn keine Updates kommen.

**Comment by v0r73x** [comment]
super :) Danke für euer schnelles Feedback.
müssen die Aktoren, die ich als Sprinkler nutzen möchte, in der subsection/Gewerk Gruppe sein? Und wenn ja, werden Sie dann nicht durch die initiale Erkennung überschrieben als switch? Ich habe meine Sprinkler in der /var/lib/homebridge/homematic_config.json konfiguriert, oder muss ich es in die  /var/lib/homebridge/config.json schreiben? 

Ich habe auch ein anderen Aktor verwendet  HM-LC-Sw4-Ba-PCB - Kanal 3 jedoch auch nichts zu sehen. Bzw. nur wenn ich den cach der accessories lösche, dann ist es kurz in der home app - aber verschwindet gleich wieder (symbol einfach weg) ?

**Comment by dkrizic** [comment]
Alle Geräte müssen in der Gruppe/Gewerk sein, sonst werden sie nicht gefunden. Sie müssen in die homebridge_config.json rein, bzw. wenn sie in config.json sind, werden sie in die homebridge_config.json geschrieben, wenn sie nicht schon existiert.

**Comment by v0r73x** [comment]
super - ich stelle es nochmal nach - diesmal aber zielgerichtet mit einem BidCos.RF Aktor. 
Nochmal zu der Frage - musstet ihr bei jeder änderung in der config die caches löschen?

**Comment by v0r73x** [comment]
Wenn ich das ganze nochmal nachstelle indem ich mein Haus aus der Home app lösche und dann mit einer zurückgesetzten Homebridge beginne, sehe ich den sprinkler jetzt so, wie er sein soll. Jedoch nach fertigen aufnehmen aller Geräte verschwinden nach einigen Sekunden ca. 80% aller Homebridge Geräte - und die Geräte sortieren sich neu in der home App. Kann ich irgendwie debuggen was da vorgeht? 

Diesmal habe ich ein BidCos Aktor genommen:
![image](https://user-images.githubusercontent.com/48632087/77899859-78b7a080-727d-11ea-8e1d-082f8025a8bb.png)

den habe ich dann in der config gesetzt:
![image](https://user-images.githubusercontent.com/48632087/77899977-a6044e80-727d-11ea-9ebc-9ac767d41a35.png)

im log sehe ich auch kein problem - nur im homeapp verschwinden einfach die Geräte und nicht nur der BidCosRF aktor sondern auch andere - konnte nicht direkt nachstellen ob es immer dieselben sind. 
Habt ihr eine idee ? debug oder ähnliches Verhalten? 
danke und gruß,
Robert

**Comment by v0r73x** [comment]
moment -jetzt scheint es zu laufen :) es dauerte ca 5 min. dann habe ich ein neustart der CCU (pivccu) durch mein lautsprecher vernommen und in home sind alle aktoren wieder erschienen ;) Ich monitore es mal und gebe rückmeldung ob es jetzt stabil läuft

**Comment by v0r73x** [comment]
folgende infos konnte ich aus dem log fischen 👍 
![image](https://user-images.githubusercontent.com/48632087/77941417-690a7d00-72ba-11ea-822c-bc6b954764a8.png)

![image](https://user-images.githubusercontent.com/48632087/77941532-99eab200-72ba-11ea-9cbe-1279c89fd225.png)

**Comment by v0r73x** [comment]
ok ich konnte es nachstellen: ich habe ab 3:06 die homebridge komplett neu gestertet (ohne die ccu mit zu starten) und man kan sehen das es ein paar sekunden mit dem sprinkler funktioniert - auch running aus und an und ich sehe auch in der homebridge das der aktor ausgelöst wurde (timestamp aktor) das plötzliche verschwinden ist für mich völlig unklar

![sprinkler_issue](https://user-images.githubusercontent.com/48632087/77948438-b17b6800-72c5-11ea-8024-78e1d89148b6.gif)

**Comment by v0r73x** [comment]
Ich habe leider keine weitere idee mehr :(
ich habe mir einen workaround mit den httpSprinkler plugin gebastelt.
Über die XML Api kann ich die SonOff (oder jegliche andere Homematic Aktoren) per ise_id direkt als weburl schalten  und der status wird auch in der homematic zentrale aktualisiert. Leider gibt es keinen timer den ich über die Homeapp modifizieren kann. 

Daher wäre es schön, wenn mir einer hilft das Problem zu lösen.

**Comment by thkl** [comment]
Ich hab das Problem hier immer noch nicht richtig kapiert ? 
Es wurde ein Switch als Ventil angelegt ? Und der ist dann da und kurze Zeit später nicht mehr ? 
Oben in dem Screencast ist doch der Sprinkler da ? 


Prinzipiell gilt : (zumindest noch bis zur nächsten Version, die dann ein WebUI hat): Jedes Gerät, welches nach HomeKit soll, muss in dem Gewerk vorhanden sein, welches in der Homebridge Config angegeben wurde. Eigentlich muss der Kanal drin sein, Geräte kann man ja keinem Gewerk zuordnen. Und damit der Switch Kanal dann als Sprinkler - und nicht als Lampe oder Steckdose - nach Homekit geht muss die Adresse in die valve Liste ....

**Comment by v0r73x** [comment]
Hi Thomas,

das problem ist eigentlich ganz einfach: der sprinkler ist für einen kurzen moment sichtbar und dann verschwindet er wieder - und merkwürdigerweise auch noch viele andere Homematic Geräte verschwinden auch plötzlich . Ich habe es auf 3 verschiedenen hombridge instanzen (rock64, rpi2 und rpi4) überall das gleiche spiel. 

Sprinkler da - kurzes probieren in der HomeApp freuen und dann ohne warnung im log  ... buff... sprinkler weg, einige hm geräte fliegen auch raus. 

wenn ich die homebridge wieder neu starte - gleiches spiel - sprinkler da..blub und wieder weg ...

hatte ich in den letzten 3 jahren rumbastelei noch nie gesehen.

**Comment by thkl** [comment]
Strange !

Aber wenn Du eh am basteln bist:


https://github.com/thkl/hap-homematic

Das ist ein Plugin für die Raspberrymatic/CCu3 das macht HomeKit direkt auf der CCU. Da unterstütze ich auch schon die Switche als Sprinkler ...

**Comment by v0r73x** [comment]
Hi Thomas,

werde ich mir gleich mal ansehen - leider habe ich noch gedöhns wie magichome, neopixels, die ich nich direkt in homematic reinbekomme - daher brauche ich dann trotzdem die Homebridge. 
BTW: die verwendeten ports sollten sich nicht mit homebridge überschneiden oder? es ist natürlich klar das ich dann das hoebridge-homematic plugin vorher aus der homebridge entferne ;)

**Comment by thkl** [comment]
Homebridge kann problemlos weiter benutzt werden. Mache ich auch zb für Roborock oder Netatmo. Und kann auch das Homematic Plugin aktiv sein. Man kann ja mehrere Bridges in ein Home aufnehmen.

**Comment by v0r73x** [comment]
Hmmm... habe Addonn mal in die Homematic geladen ... ich nutze jedoch pivccu. Installation erfolgreich - jedoch wenn ich ins menü " CCU-zusatzsoftware gehe und dann auf Einstellungen klicke 
![image](https://user-images.githubusercontent.com/48632087/78159448-e103af00-7442-11ea-8f50-da302042687d.png)

bekomme ich eine neue seite geöffnet die anzeigt das  die Sete nicht erreichbar ist. Kann es sein das pivccu nicht unterstützt ist ?

**Comment by thkl** [comment]
Ich setze node.js auf der ccu voraus. Das ist bei der RM bzw CCU3 der Fall. Ob bei piVCCU Node installiert ist weiß ich nicht.  Wenn in der Systemsteuerung kein HomeKit Button ist dann fehlt da Node. Ich muss mir mal pivccu organisieren.

**Comment by v0r73x** [comment]
ich habe mal netstat konsultiert - da sind nur die folgenden port in listen mode
![image](https://user-images.githubusercontent.com/48632087/78160317-0cd36480-7444-11ea-93df-8843b1d7317d.png)

**Comment by v0r73x** [comment]
auf pivccu ist nodejs druaf aber die 8ter version 
![image](https://user-images.githubusercontent.com/48632087/78160433-38564f00-7444-11ea-9346-5f7a765b7480.png)

**Comment by thkl** [comment]
Nein ich setze 8.11.0 als mindest Version voraus. 

Und keiner der Ports ist meiner :)

Ich schau mal warum das nicht installiert/startet

**Comment by v0r73x** [comment]
das wäre klasse :) ich unterstütze gern wo ich kann - einfach Bescheid geben.

p.s. - wie ... ? ... einfach so eine pivcc im netz ? mächtig mysteriös :)

**Comment by thkl** [comment]
so der installer ist neu  0.0.2 .. pivccu verhält sich ein wenig anders.
Der Installer macht jetzt einen CCU Reboot und erst dann wird das npm install ausgeführt ...
Hab 3 Tests gemacht hat jedes mal geklappt ;o)

**Comment by v0r73x** [comment]
Hi Thomas,

supi - installation läft durch und es ist auch der Homekit Button in der Systemsteuerung zu sehen:
![image](https://user-images.githubusercontent.com/48632087/78245395-b1f34900-74e7-11ea-888b-99ff16b9757e.png)

leider ist die sich öffnende Seite irgendwie inhaltlos - versucht mit 2 versch. Browsern FF und Chrome
![image](https://user-images.githubusercontent.com/48632087/78245335-98520180-74e7-11ea-9491-1342664979bb.png)

**Comment by thkl** [comment]
Mal bitte in der Browserconsole schauen was es da für Errors gibt.

**Comment by thkl** [comment]
Ach und bitte in den anderen Repo tracken das kommt hier sonst durcheinander.

**Comment by v0r73x** [comment]
ok mache ich - wollte ich sowieso fragen ob das mehr sinn macht :)

**Comment by v0r73x** [comment]
Hi Thomas,

ich habe nun endlich analysieren können warum die Gartensprinkler nie funktioniert hatten (in der Vergangenheit). ich konnte es jetzt nachstellen - - es lag an .....*trommelwirbel* an einem IPAD3 welches max IOS 9.3.5 verwenden kann! - ich hatte es nach der kompletten neuinstallation damals (mit hap-homebridge) ausgeschaltet. jetzt habe ich das alte pad gern als sprachinterface zu siri nutzen per "hey Siri" aber sobald das alte ipad sich mit dem wlan verbinden verschwinden die Sprenger auf allen homkit apps - also Fehler gefunden - hast du eventuelle eine idee wie ich das alte ipad (32bit) doch noch nutzen kann? irgendein hack im ios 9.3.5 auf andere ios fw spoofen ? ich werf ungern funktionierende hw in den müll X(

ich kann erfreulich verkünden dass wir diesen issue damit schliessen können
