### ISSUE TITLE
Automatisches Entfernen von Gerät aus Gewerk entfernt Gerät nicht in Home

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#578]
Ich bin auf 0.0.219 und habe für mehrere Homebridge Instanzen jeweils ein Gewerk, die alle in einer Home sind. Jetzt habe ich einen HM-Sec-SD-2 aus Gewerk B entfernt und in Gewerk A hinzugefügt und danach neu gestartet. Ergebnis war, dass der HM-Sec-SD-2 nun in Home doppelt auftaucht.

Entferne ich ihn den HM-Sec-SD-2 auch aus Gewerk A und starte neu, wird er korrekt aus Home raus genommen bleibt aber für Gewerk B immer noch bestehen, obwohl nicht mehr dem Gewerk B zugewiesen. Füge ich ihn nochmal zu Gewerk B hinzu und entferne ihn danach wieder jeweils mit Neustart dazwischen bleibt er dennoch immer noch in Home bestehen.

Kann man ein Gerät manuell aus der Homebridge-Homematic entfernen?

**Comment by Matzushub** [comment]
Schau mal ob eventuell noch ein Channel des Gerätes dem Gewerk zugeordnet ist. Bei der Initialisierung des Homematic modules müsstest du sehen welche Geräte von der CCU übergeben worden sind.
