### ISSUE TITLE
Videodoorbell merkt sich Einstellung für Bewegungsmitteilungen nicht

### ISSUE THREAD

**Issue by maxu359** [thkl/homebridge-homematic#579]
Hallo,
ich weiss leider nicht ob es an meiner Konfiguration liegt, deswegen wollte ich, bevor ich alles neu einrichte, erstmal fragen, ob jemand das Problem reproduzieren kann.
Ich habe vor kurzen zwei Videodoorbells mit Klingel und PIR eingerichtet.
Diese funktionieren bis auf eine Kleinigkeit auch sehr gut.
Leider merkt sich Homebridge nach einen Neustart nicht, dass die Bewegungsmitteilungen aktiviert sind. (Die Klingel jedoch schon)
Nach jeden Neustart sind diese wieder deaktiviert.
Kann jemand bestätigen dass es an meiner Konfiguration liegt?

Was ich schon wieder probiert habe:
- gelöscht und neu hinzugefügt in Home
- jegliche Kombi aus Einstellungen in der Home App
- gelöscht in Home, die entsprechenden AccessoryInfo.XXXX.json und IdentifierCache.XXXX.json aus persist gelöscht und dann neu hinzugefügt

Homebridge Version: homebridge@0.4.53
Homebridge-Homematic Version: homebridge-homematic@0.0.219

Anbei Auszug aus der homematic-config.json
`{
                    "name": "Wohnungseingang",
                    "type": "HM-THKL-VIDEODOORBELL",
                    "parameter": {
                        "camera": {
                            "name": "Wohnungseingang",
                            "videoConfig": {
                                "source": "-rtsp_transport tcp -re -i rtsp://bla:bla@192.168.2.6/Streaming/Channels/1",
                                "stillImageSource": "-i http:/bla:bla@192.168.2.6/Streaming/channels/1/picture/",
                                "maxStreams": 1,
                                "maxWidth": 1280,
                                "maxHeight": 960,
                                "maxFPS": 10,
                                "maxBitrate": 300,
                                "vcodec": "h264_omx",
                                "packetSize": 1316,
                                "audio": false,
                                "debug": false
                                }
                            },
                            "address_key_event": "HmIP-RF.0016D8A9A4B648:3.STATE",
                            "state_key_event": false,
                            "address_unlock_actor": "BidCos-RF.NEQ1581736:1.STATE",
                            "message_actor_open": {
                                "on": true,
                                "off": false
                           	 },
							"pir" :{
								"address" : "BidCos-RF.OEQ0165564:1.STATE",
								"key_event" : true,
								"upload":false
	    							}
                        }
                    
                },`

**Comment by thkl** [comment]
ich versteh das Problem nicht ganz. Werden die Daten in der Config überschrieben ? Oder wie muss ich "merkt sich die Einstellung nicht" verstehen ?

**Comment by maxu359** [comment]
Servus, in der Home App klicke ich in den Einstellungen der Kamera auf Mitteilungen.
Dann gibt es hier 3 Schalter:
Mitteilungen auf diesen iPhone, Bewegungsmitteilungen  und Mitteilungen bei Türklingeln.
Ich habe alle 3 eingeschaltet. Wenn ich jetzt allerdings meine Homebridge neu starte, ist der Schalter für Bewegungsmitteilungen wieder auf aus. Er merkt sich bei mir also die Mitteilungseinstellung für Bewegungsmitteilungen nicht. Die "Mitteilung bei Türklingeln" jedoch schon. 
[Bild vor Neustart](https://imgur.com/a/OE4NYG9#8NhvClL)
[Bild nach Neustart](https://imgur.com/a/2NLoWnw)

**Comment by thkl** [comment]
achsoooo ok das liegt aber nicht an homebridge bzw dem plugin. Denn diese Settings leben alleine in HomeKit und werden von HK nicht zurück zur bridge/homematic geschickt.

**Comment by maxu359** [comment]
Ah Ok, das wusste ich nicht. Vielen Dank für die Info! Dann komme ich wohl nicht darum, HomeKit neu aufzusetzen:)
