### ISSUE TITLE
HmIP SWSD Rauchmeldergruppen

### ISSUE THREAD

**Issue by superbraz** [thkl/homebridge-homematic#582]
Gruss,
hab seit gestern die Homematic Rauchmelder HmIP SWSD im Einsatz und bin auf den Hinweis in der Wiki zu den Rauchmeldergruppen gestoßen (https://github.com/thkl/homebridge-homematic/wiki/Rauchmeldergruppen) - aber an welcher Stelle muss ich den Parameter denn in der Config einfügen?

Vielen Dank für die Hilfe!

Edit: 
HIer mal meine Config

{
    "bridge": {
        "name": "Homebridge",
        "username": "XXX",
        "port": XXX,
        "pin": "XXXXX"
    },
    "platforms": [
        {
            "platform": "HomeMatic",
            "name": "HomeMatic CCU3",
            "ccu_ip": "192.XXXXXXXX",
            "enable_hmip": "true",
            "ios10": true,
            "filter_device": [],
            "filter_channel": [],
            "outlets": [
                "HmIP-RF.XXXXX:3",
                "HmIP-RF.XXXXX:3",
                "HmIP-RF.XXXXX:3",
                "HmIP-RF.XXXXX:3",
                "HmIP-RF.XXXXX:3",
                "HmIP-RF.XXXXX:3",
                "HmIP-RF.XXXXX:3",
                "HmIP-RF.XXXXX:3"
            ],
            "doors": [],
            "programs": [],
            "accessories": [],
            "subsection": "Homekit",
            "variables": [
                "Hoflicht_kurz"
            ],
            "variable_update_trigger_channel": "Variablen_Trigger",
            "special": [
                {
                    "name": "Garagentor",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "address_sensor_close": "HmIP-RF.XXXXX:1.STATE",
                        "state_sensor_close": 0,
                        "sensor_requery_time": 35,
                        "address_actor_open": "HmIP-RF.XXXXX.STATE",
                        "delay_actor_open": 1,
                        "delay_actor_close": 1,
                        "message_actor_open": {
                            "on": true,
                            "off": false
                        }
                    }
                },
                {
                    "name": "Hoftor",
                    "type": "HM-THKL-GARAGEDOOR",
                    "parameter": {
                        "address_sensor_close": "HmIP-RF.XXXXX:1.STATE",
                        "state_sensor_close": false,
                        "sensor_requery_time": 25,
                        "address_actor_open": "HmIP-RF.XXXXX:3.STATE",
                        "delay_actor_open": 1,
                        "delay_actor_close": 1,
                        "message_actor_open": {
                            "on": true,
                            "off": false
                        }
                    }
                }
            ],
            "services": [
                {
                    "type": "HM-THKL-GARAGEDOOR",
                    "service": "HomeMaticHomeKitGarageDoorService"
                }
            ]
        },
        {
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Garage",
                    "videoConfig": {
                        "source": "-re -i rtsp://XXXXX/axis-media/media.amp?resolution=1280x720",
                        "stillImageSource": "-i http://XXXXX/axis-cgi/jpg/image.cgi",
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 200,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Terrasse",
                    "videoConfig": {
                        "source": "-re -i rtsp://XXXXX/axis-media/media.amp?resolution=1280x720",
                        "stillImageSource": "-i http://XXXXX/axis-cgi/jpg/image.cgi",
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 200,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Hof",
                    "videoConfig": {
                        "source": "-re -i rtsp://XXXXX/axis-media/media.amp?resolution=1280x720",
                        "stillImageSource": "-i http://XXXXX/axis-cgi/jpg/image.cgi",
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 200,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "name": "Alexa",
            "username": "XXXXX",
            "password": "XXXXX",
            "pin": "XXXXX",
            "platform": "Alexa"
        },
        {
            "name": "Config",
            "port": XXXXX,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "de",
            "platform": "config"
        }
    ],
    "accessories": [
        {
            "accessory": "DummySwitch",
            "name": "Briefkasten",
            "stateful": true
        },
        {
            "accessory": "DummySwitch",
            "name": "Fake Schalter",
            "stateful": true
        },
        {
            "accessory": "DummySwitch",
            "name": "Fake Taster"
        }
    ]
}

**Comment by superbraz** [comment]
ich habe es jetzt an folgender Stelle eingefügt und bekam zumindest keinen Syntax Fehler im ConfigUiX

...
"accessories": [],
"subsection": "Homekit",
"variables": ["Hoflicht_kurz"],
"HmIP-SWSD:SMOKE_DETECTOR": {"single_alarm": true},
"variable_update_trigger_channel": "Variablen_Trigger",
"special": [...

werd es dann die nächsten Tage mal mit Testrauch probieren, ob es fkt. wie gewünscht.

**Comment by thkl** [comment]
müsste richtig sein, wie schon hier #583 angesprochen habe ich in der aktuellen GitHub Version ne Menge umgeworfen und neu gebaut.

**Comment by superbraz** [comment]
Gestern getestet mit Rauchmelder Testgas, funktioniert einwandfrei!
Kann man dir irgendwie was gutes tun?
Gibts nen Spendenkonto oder rückst du deine Adresse raus für ein kleines Dankeschön? Du hast mir jetzt schon so oft geholfen!

**Comment by thkl** [comment]
Die ReadMe hat einen PayPal Button ;) aber ist nicht nötig ...
