### ISSUE TITLE
Bewässerung/Irrigation: Geht in der 219 nicht

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#583]
Ich habe die aktuelle Version 0.0.219 und ich habe in der homematic_config.json drei Einträge für alles valves definiert:

```
  "valves": [
    "BidCos-RF.LEQ0281557:1",
    "BidCos-RF.LEQ0281557:2",
    "BidCos-RF.LEQ0281557:3"
  ],
```

Diese tauchen in der Home app auch als solche auf:

![image](https://user-images.githubusercontent.com/1181349/78462839-5509b580-76d6-11ea-82de-d7f5a8905b6c.png)

**Das Problem**

* Wenn ich drauftippe, funktioniert es nicht
* Ich kann die Zone nicht enabled, wenn ich speichern will springt er auf off zurück

**Frage**

Was ist das aktuelle Vorgehen, um Sprinkler zu konfigurieren? Die "alte" Einstellung scheint so nicht mehr zu funktionieren.

**Comment by thkl** [comment]
hmm ich habe in der aktuellen GitHub Version hier mal wieder alles umgeworfen und viele Klassen neu geschrieben. Daher kann ich das nicht wirklich nachprüfen.

Ich werde mal ein beta npm bauen zum Ausprobieren.
Da aber das Laden der Accessories jetzt dynamisch erfolgt (homebridge braucht dann keinen Neustart mehr wenn was geändert wurde) weiss ich nicht, ob ggf die Geräte alle als NEU in HomeKit auftauchen.

**Comment by dkrizic** [comment]
Ich habe hap-homekit mal auf der CCU3 installiert und ich bin sehr beeindruckt. Ich habe die Sprinkler jetzt dahin gezogen. Da funktionieren sie einwandfrei. 

Was ist denn jetzt die Strategie? homebridge-homematic oder hap-homekit? Du redest ja davon, dass Du einen Rewrite von homebridge-homematic machst. Teilen die beiden die codebase? Was ist die Strategie, die Du verfolgst?

**Comment by thkl** [comment]
Die ursprüngliche Idee von hap-homematic war, rauszufinden ob HomeKit ohne Homebridge direkt auf der CCU funktioniert. Das ist dann ein wenig eskaliert. 

Die beiden Systeme teilen nicht die selbe Codebase. Der Rewrite des homebridge Plugins basiert auf einigen neuen homebridge APIs (dynamisches Laden von Accessories).

Der Rewrite des homebridge Plugins ist hier im GitHub schon soweit abgeschossen das auf dem Testsystem eigentlich alles läuft. Ich habe natürlich auch nicht alle Komponenten die unterstützt werden, daher kann ich nur von den UnitTests ausgehen. Ein NPM gibt es noch nicht.

Ich bin mir noch nicht ganz sicher ob ich das homebridge Plugin zugunsten von hap-homematic aufgeben werde, da es ja immer noch CCU2s gibt wo das Ganze nicht funktioniert.

Aktuell wird beides weiter geführt, was nicht unbedingt wenig Arbeit ist ;o)

**Comment by dkrizic** [comment]
Cool wäre es, wenn die Codebase die gleiche wäre (Services) und nur die Runtime sich unterscheidet.

**Comment by thkl** [comment]
die Services sind ähnlich aufgebaut. Der Aufwand einen Service von einer auf die andere RunTime umzuziehen/anzupassen ist nicht sehr hoch.

**Comment by arndtk** [comment]
Guten Tag,

ich hoffe ihr könnt mir (kurz) helfen. :-)

Genau diesen Wunsch habe ich auch, drei Ventile in Home angezeigt zu bekommen.  Hier meine aktuelle Config:


{
    "bridge": {
        "name": "Homebridge 3E22",
        "username": "0E:1D:BA:AA:3E:22",
        "port": 51041,
        "pin": "972-63-984"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}



Ich denke folgender Abschnitt ist nötig, ich weiß jedoch nicht an welche Stelle ich den Code einfügen muss, sorry.

"valves": [
    "BidCos-RF.QEQ0659843:1"
    "BidCos-RF.QEQ0659843:2"
    "BidCos-RF.QEQ0659843:3"
    "BidCos-RF.QEQ0659843:4"
  ],

DANKE!!!!!

Viele Grüße aus dem Rheinland,
Arndt

**Comment by arndtk** [comment]
Liest hier zufällig jemand mit? ;-)

**Comment by dkrizic** [comment]
Ja, ich. @thkl ist in letzter Zeit sehr aktiv im Projekt https://github.com/thkl/hap-homematic. Dort funktioniert die Irrigation. Ich habe das auf meiner CCU3 installiert einige der Autoren umgezogen.

**Comment by arndtk** [comment]
Hi, und danke für deine Antwort. Ich habe bereits eine CCU3 hier liegen und möchte auch auf Hap umsteigen, gerade für mich als Laie eine super Lösung.

Bedeutet, die Lösung mit den Ventilen ist dort bereits umgesetzt? Funktioniert auch der Garagentoröffner weiterhin damit oder müsste ich den Codeschnipsel mit umziehen? Kennst du eine Lösung, um den Füllstand meiner Zisterne (läuft über den HM Füllstandssensor) angezeigt zu bekommen? 

Viele Grüße
Arndt

**Comment by dkrizic** [comment]
Ventile: Implementiert, geht
Garage: Implementiert, vermutlich einfacher als hier, nutze ich aber noch nicht, da es bei mir auch so funktioniert.
Zisterne: Keine Ahnung, hier fehlt ja die entsprechende Komponente in HomeKit, oder?

So wird die Garage konfiguriert:

![image](https://user-images.githubusercontent.com/1181349/81467994-d1634d00-91dc-11ea-86b1-fd4fec402e7d.png)

**Comment by arndtk** [comment]
Sehr nett, vielen Dank! Ich werde mein Glück versuchen! :-)
