### ISSUE TITLE
Response:  Unable to fetch new versions

### ISSUE THREAD

**Issue by shinzan111** [thkl/homebridge-homematic#586]
Hallo, 

Ich erhalte nach dem Start von Homebridge diese Fehlermeldung:

"Unable to fetch new version". 

Ist das mitunter der Grund warum der Status der Präsenzmelder, Jalousien u.a.
nicht mehr mit dem aktuellen Status angezeigt werden?

Danke und Gruss

![Bildschirmfoto 2020-04-10 um 09 37 14](https://user-images.githubusercontent.com/10072661/78973222-bafba000-7b0f-11ea-94ca-bc540c969188.png)

**Comment by thkl** [comment]
nö das ist nur eine Meldung das ein ggf Update nicht ermittelt werden kann ....

**Comment by Matzushub** [comment]
Würde da gern noch mal nachfragen. Ich verstehe die Meldung "Unable to fetch new versions" so, dass nicht ermittelt werden kann ob eine neue Version des homebridge-homematic plugins existiert. Denn wenn es ermittelt werden könnte aber kein neue Version existiert würde ich eher sowas wie "no updates available" erwarten.

Darum die Frage - was läuft nicht, dass auch bei mir ein Update nicht ermittelt werden kann? Liegt es an unserem System oder am Server?

**Comment by WirthmU** [comment]
Ich habe dieselbe Fehlermeldung - gibt es hierzu eine Lösung?
