### ISSUE TITLE
homebridge-homematic und CCU3 korrekt einrichten

### ISSUE THREAD

**Issue by Polodriver** [thkl/homebridge-homematic#587]
Benötige Hilfe beim korrekten Einrichten der CCU3 der richtigen Eintragungen in der Konfiguration von homebridge. Leider werden mir keine Aktoren in der Homebridge angezeigt.
Habe in der CCU3 ein Gewerk mit dem Namen Homekit erstellt und alle meine Aktoren diesem Gewerk hinzugefügt.
Anschließend habe ich in die Konfiguration folgendes eingetragen:
"platform": "HomeMatic",
            "name": "HomeMatic CCU",
            "ccu_ip": "192.168.178.35",
            "subsection": "HomeKit",
            "enable_hmip": true,
            "enable_wired": false,
            "local_port": 9090,
            "ios10": true`

Die IP habe ich fest zugewiesen und der Port wird auch noch nicht genutzt.
Was könnte ich falsch gemacht haben?
Bin um jeden Tipp sehr froh! Herzlichen dan schon mal im Voraus!

**Comment by CameronVIE** [comment]
Meine HomeMatic Config in der "json"
{
            "name": "HomeMatic CCU3",
            "ccu_ip": "172.16.172.130",
            "filter_device": [
                "BidCoS-Wir"
            ],
            "filter_channel": [],
            "outlets": [],
            "doors": [],
            "programs": [],
            "accessories": [],
            "variables": [],
            "variable_update_trigger_channel": "",
            "subsection": "Homekit",
            "enable_hmip": true,
            "enable_wired": false,
            "ios10": true,
            "platform": "HomeMatic"
        },
