### ISSUE TITLE
HMIP-BSM messwerte

### ISSUE THREAD

**Issue by teewurstbrot84** [thkl/homebridge-homematic#588]
Selbes Problem. Leider keine korrekten Messwerte in der Eve App. 

https://github.com/thkl/homebridge-homematic/issues/86#issue-199355763

**Comment by thkl** [comment]
Das sollte aber funktionieren, wenn der Channel 7 (ENERGIE_METER_TRANSMITTER) aufgenommen wird. Der Switch Channel wird automatisch mit hinzugefügt.

**Comment by teewurstbrot84** [comment]
Nein leider nicht. Hab auch mal den Schaltkanal mit rausgenommen und nur den Messwertkanal 7 rein. Gleiches Spiel. Alles auf null.  Funktioniert nicht

**Comment by teewurstbrot84** [comment]
![3357ACDF-7227-4A53-B487-456F32EA4F9E](https://user-images.githubusercontent.com/45150721/79044499-bfa28000-7c05-11ea-9866-fed877dc5798.png)

**Comment by thkl** [comment]
Ah ich sehe es gerade, er nimmt an das Channel 6 der Messkanal und Channel 3 der Schaltkanal ist. Kann man aber in der config.json (homematic_config.json ab Version 214) einstellen:


"HmIP-BSM:ENERGIE_METER_TRANSMITTER": {
		"meterChannel" : 7,
		"switchChannel" : 4
}

**Comment by teewurstbrot84** [comment]
Super danke. Hat geklappt
