### ISSUE TITLE
Seltsame Staus-Aktualisierung bei HMW-IO-12-Sw14-DR mit HomeMaticHomeKitKeymaticService

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#589]
Seit ich vor einigen Wochen von der 109 auf 219 aktualisiert und die CCU3 Anbindung umgestellt habe, habe ich beim Wired HMW-IO-12-Sw14-DR einen komischen Effekt:

Beim Neustart der Homebridge wird der Status vom bspw. BidCos-Wired.OEQ0129171:1 korrekt gelesen. Wenn ich Home hart schliesse und wieder öffne ist der Status immer noch korrekt (auch mehrmals nacheinander). Wenn ich dann den bspw. BidCos-Wired.OEQ0129171:1 über Home schalte, wird auch der Status korrekt gesetzt und angezeigt. Dies auch mehrmals. Wenn den bspw. BidCos-Wired.OEQ0129171:1 über ein CCU3 Programm schalte, ebenfalls korrekt in Home. 

Nach einiger Zeit irgendwann, mehrere Minuten, wenn ich die Home wieder öffne wird auf einmal der Status in Home aktualisiert obwohl keine Status-Änderung am bspw. BidCos-Wired.OEQ0129171:1 erfolgt ist. Der Status in der CCU3 bleibt richtig, aber der in Home wird er falsch angezeigt.

Dies passiert dann immer zeitgleich zusammen für alle drei Kanäle des BidCos-Wired.OEQ0129171.1, BidCos-Wired.OEQ0129171.13, BidCos-Wired.OEQ0129171.14 die unter "services" als

```
{"type": "HMW-IO-12-Sw14-DR:DIGITAL_OUTPUT",
"service": "HomeMaticHomeKitKeymaticService"}
```
auf Homebridge Instanz #4 konfiguriert sind. Das Log für Homebridge Instanz #4 dass das Verhalten um 12:22 rum für BidCos-Wired.OEQ0129171:1 protokolliert habe ich mit angehängt.

Interessanter Weise passiert dies dann aber nicht für

`"valves": ["BidCos-Wired.OEQ0129171:2","BidCos-Wired.OEQ0129171:3","BidCos-Wired.OEQ0129171:4"]`

die auf Homebridge Instanz #3 konfiguriert sind.

Natürlich haben beiden Homebridge Instanzen `"enable_wired": true`

@thkl Kannst du dir das mal anschauen

<img width="1426" alt="HMW-IO-12-Sw14-DR" src="https://user-images.githubusercontent.com/28545473/79219316-55324f80-7e52-11ea-9937-6ced062d4f2a.png">

[Homebridge4.log](https://github.com/thkl/homebridge-homematic/files/4474947/Homebridge4.log)

**Comment by iuliusmaximilian** [comment]
Nachtrag: ich habe die BidCos-Wired.OEQ0129171.1, BidCos-Wired.OEQ0129171.13 und BidCos-Wired.OEQ0129171.14 mal testhalber zusätzlich in die Homebridge Instanz #3 rein gehangen, ohne weitere Konfiguration werden diese dann in Home als "Licht" angezeigt. Bei oben beschriebenem Verhalten sind diese in Home dann zeitgleich korrekt.

**Comment by thkl** [comment]
Hmm Keymatic reagiert auf STATE und hat aber keine Channeltrennung. Das heisst wenn irgend ein Kanal des Gerätes seinen Zustand wechselt wird das in der KeyMatic als Wechsel im exportierten Kanal interpretiert.  Daher bitte mal prüfen, ob in dem Falle ein anderer Kanal des Gerätes zwischenzeitlich seinen Zustand geändert hat. Dieses Konstrukt ist so eigentlich nicht vorgesehen, auch wenn es halb funktioniert.

**Comment by iuliusmaximilian** [comment]
@thkl Danke für das Feedback! Könntest du alternativ einen neuen Service erstellen, der einfach anstelle des Standards Licht ein Türschloss anzeigt/steuerbar macht ?

**Comment by iuliusmaximilian** [comment]
@thkl ich habe einen Feature Request dazu erstellt #593
