### ISSUE TITLE
Alte Rolladenaktoren nicht sichtbar

### ISSUE THREAD

**Issue by Commi007** [thkl/homebridge-homematic#590]
Hallo,

ich bin neu und wirklich nur ein kleiner dummer User.
Ich finde dieses Projekt wirklich großartig und habe auch geschafft alles zum laufen zu bekommen.

Ein „Gewerk“ ist in meiner Raspimatic angelegt und weniger als 100 Aktoren / Sensoren sind hinzugefügt. Es erscheinen (fast) alle Aktoren / Sensoren in HomeKit.

Aber eben nur fast !
Ich benutze sowohl welche von den „neuen“ Typen Rolladenaktoren - ich meine die aus grauem Kunststoff hergestellten vom Typ HM-LC-Bl1PUB-FM,
Als auch welche von den „alten“ aus grünem Kunststoff hergestellten vom Typ HM-LC-Bl1-PB-FM.

So, es werden in der Homebridge NUR die Rolladenaktoren des „neuen“ Typs angezeigt. Die des „alten“ Typs sind nicht in der Liste. Ich versuche mal einen Screenshot anzuhängen.... es zeigt „There is No Service for .....“ (Typnummer „alte“ Aktoren) .
![IMG_0175](https://user-images.githubusercontent.com/63652662/79232970-80279e00-7e68-11ea-811c-8910bdcb2e30.jpeg)

Werden die nicht mehr supportet, oder fehlen die aus Versehen und kommen vielleicht in einem Update wieder dazu ? Oder mache ich etwas falsch ?
Ich habe nun nicht die Lust, mal eben 8 Rolladenaktoren neuen Typs zu kaufen !

Gibt es BITTE eine Lösung ?
Viele Grüße und bitte weitermachen mit diesem Projekt !
Frank

**Comment by thkl** [comment]
Ich trage die in die nächste Version mit ein.
Einstweilen kann das selber gemacht werden.

Die große Frage ist jetzt in welchem Verzeichnis liegt die Config.
Das sieht man aber im LogFile:

[4/14/2020, 14:58:19] [HomeMatic] IMPORTANT !! Starting this version, your homematic custom configuration is located in /var/lib/homebridge/homematic_config.json

in dem Falle /var/lib/homebridge/homematic_config.json

Und diese Datei gilt es zu editieren.
Das ist ein JSON File.
Da steht erst mal nicht viel drin es muss ein Eintrag für die Serviceerweiterung hinein:

```
{ 
....
....
"services":[{ 
			"type": "HM-LC-Bl1-PB-FM:BLIND",
			"service": "HomeMaticHomeKitBlindService"
		}]
}
```


Das ist ein json Format, bitte vor dem Speichern zb auf jsonlint.com checken ob der neue Inhalt des Files das richtige Format hat

**Comment by Commi007** [comment]
Sehr geehrter Herr Kluge,

DANKE GEIL !

Ich hab’s geschafft, das hat geklappt !

Mit freundlichen Grüßen

Frank

> Am 14.04.2020 um 17:03 schrieb Thomas Kluge <notifications@github.com>:
> 
> { 
> ....
> ....
> "services":[{ 
> 			"type": "HM-LC-Bl1-PB-FM:BLIND",
> 			"service": "HomeMaticHomeKitBlindService"
> 		}]
> }

**Comment by thkl** [comment]
Na grossartig
