### ISSUE TITLE
version 0.1.222

### ISSUE THREAD

**Issue by fighterzg6** [thkl/homebridge-homematic#592]
bei mir wird in der config ui x angezeigt das es ein update gibt. 0.1.222
also ich, zack installiert.
und nun geht es los.

1. Es startet nur eine Homebridge Instanz.
2. es werden keine Garagentore und variablen erkannt.
3. diese Einstellungsseite für evtl services geht nicht im safari auf dem mac nur bunte Streifen , aber hab sie dann im Crome angezeigt bekommen. wie kann man das port ändern.???

also nach der 0.0.219 (beste version bis jetzt) ist die 0.1.222 Katastrophe !

lief bis jetzt alles so gut!

**Comment by thkl** [comment]
Siehe dem anderen issue dazu

**Comment by shinzan111** [comment]
Dieses Update hat meine ganze Homebridge-Konfig ruiniert, obwohl ich zuvor es auf einen Test-Server installiert hatte und keine Fehler angezeigt wurden.

Das ist jetzt schon recht nervig…

![Bildschirmfoto 2020-04-20 um 13 50 14](https://user-images.githubusercontent.com/10072661/79748739-32021700-830e-11ea-9574-4bb82041ba68.png)

**Comment by thkl** [comment]
Die Meldung kommt vom Config Server wenn der Hauptprozess nicht da ist. Ich schau mal das ich das abfange

**Comment by thkl** [comment]
So die 0.1.222 hat einen entsprechenden Eintrag im Release und die 0.1.231 ist ein Rollback auf die 219 .. mehr hier https://github.com/thkl/homebridge-homematic/issues/591#issuecomment-616537301

**Comment by ChrWi** [comment]
Habe glücklicherweise die 222 verpasst und laufe nun problemlos nach der 219 mit der 231 weiter.
