### ISSUE TITLE
HM Füllstandssensor wird nicht angezeigt

### ISSUE THREAD

**Issue by arndtk** [thkl/homebridge-homematic#594]
Hallo,

ich habe den HM Füllstandssensor HM-Sen-Wa-Od in Betrieb genommen und der Füllstand wir in HM korrekt angezeigt.

Besteht eine Chance oder Möglichkeit, den Füllstand auch über Homebridge integriert werden können? Oder klappt das grundsätzlich schon und ich muss noch irgendwoe etwas eintragen?

Sorry, aber ich bin auf diesem gebiet eher ein Laie. ;-)

Viele Grüße
Arndt

**Comment by thkl** [comment]
Es gibt kein HomeKit Gerät was diese Funktion abbildet.

**Comment by iuliusmaximilian** [comment]
siehe 267 bzw. https://github.com/thkl/homebridge-homematic/wiki/Variablen-basierende-Batterie-Anzeige funktioniert bei mir gut,
