### ISSUE TITLE
Wo ist die WebUI hin?

### ISSUE THREAD

**Issue by mghussi** [thkl/homebridge-homematic#596]
Moin
Vor ein paar Versionen gab es doch eine WebUI (heisst das überhaupt so?) für doe homebridge-homematic. 

Ich finde nach einer neuinstallation des Pi´s mit dem Plugin diese aber nicht wieder. War sie nur kurz in einer Version und ist nun wieder weg oder mache ich etwas falsch?

**Comment by thkl** [comment]
Die ist wieder rausgeflogen, mit dem Rollback auf Version 219 ....
