### ISSUE TITLE
Homebridge Update 1.0.2

### ISSUE THREAD

**Issue by maxu359** [thkl/homebridge-homematic#597]
Hallo,
beim Update auf Homebridge 1.0.2 bekomme ich von allen devices ein "nicht erreichbar". 
Kameras, welche über Homebridge-camera-ffmpeg angebunden sind, funktionieren weiterhin.
Auch nach einer Neuinstallation hat es nicht funktioniert.
Was ich herausgefunden habe:
Im meiner Homematic_config.json steht:

` 
...
 "services": [
    {
      "type": "HmIPW-DRD3:DIMMER_VIRTUAL_RECEIVER",
      "service": "HomeMaticHomeKitDimmerService"
    },
    {
      "type": "HM-THKL-GARAGEDOOR",
      "service": "HomeMaticHomeKitGarageDoorService"
    }
  ],
  "special": [
    {
      "name": "Garage",
      "type": "HM-THKL-GARAGEDOOR",
      "parameter": {
        "address_sensor_close": "BidCos-RF.NEQ1681532:1.STATE",
        "state_sensor_close": false,
        "address_actor_open": "BidCos-RF.OEQ0286571:1.STATE",
        "message_actor_open": {
          "on": true,
          "off": false
        },
        "delay_actor_open": 1
      }
    }
  ]
...
` 

Wenn ich dies herausnehme, funktioniert alles wie gehabt.
Besteht hier ein Problem mit den Services in Verbindung mit Homebridge 1.0.2?
Eine Fehlermeldung habe ich auch im Debug-Log nicht gefunden.

Grüße Max

**Comment by thkl** [comment]
Hmm wenn ich mir den Issue Tracker bei homebridge anschaue : https://github.com/homebridge/homebridge/issues dann ist das Problem wohl eher dort zu suchen.

**Comment by maxu359** [comment]
Oh super, war heute schon mal in den issue. Den Zusammenhang habe ich aber nicht ganz realisiert.
Die homebridge@1.0.3-beta.4 fixt es. 
Danke🙏
