### ISSUE TITLE
Neue Systemvariablen werden nicht erkannt

### ISSUE THREAD

**Issue by Kerschten** [thkl/homebridge-homematic#599]
**Describe the bug**
Nach dem Update auf Homebridge-Homematic Version 219 und homebridge Version 1.0.4 werden keine neuen Systemvariablen in der Home App hinzugefügt. Auch Änderungen wie das Löschen bestehender Systemvariablen werden nicht erkannt / übertragen. Ansonsten läuft das System einwandfrei und stabil. 

219

**Which Homematic Device or Service the bug is about**
[eg. HM-.... , HmiP-...]
SysVar

**To Reproduce**
1.  Add new sysvar or delete existing one in config.json
2.  Open Home App
3. Try to find new sysvar

**Actual behaviour**

New sysvar will not be shown or removed sysvar will still be shown respectively

**Expected behavior**
New sysvar should be shown / removed sysvar should not be shown AnyMote

**Screenshots**

**Additional context**

**Comment by thkl** [comment]
1a restart the homebridge ?

**Comment by Kerschten** [comment]
Yes, several times. No effect.

**Comment by thkl** [comment]
ok das Config File wurde ab 214 ausgelagert. Und einmalig migriert:

https://github.com/thkl/homebridge-homematic#configuration-changes-version--214

Ich tippe mal es liegt daran ...

**Comment by Kerschten** [comment]
Alles klar, das war der entscheidende Tipp. Vielen Dank für die schnelle Hilfe!

D.h. aber auch, dass man die Config UI X derzeit nicht zum Editieren der Systemvariablen und Programme nutzen kann, sondern noch manuell die homematic_config.json anpassen muss?

**Comment by thkl** [comment]
Richtig, da ConfigUI ein Schema benötigt um zu wissen was es wo setzen darf. Das kann ich aber so nicht bereitstellen, weil die Configuration nicht feststehend ist.
