### ISSUE TITLE
Rollladen und Siri Befehle

### ISSUE THREAD

**Issue by morpheus12** [thkl/homebridge-homematic#60]
Hallo Thomas!

Erstmal danke für das tolle Plugin! Ähnlich genial wie HomeControl! Jetzt hoffe ich das der Support hier genauso gut ist ... :)

Ich habe gemäß ELV Anleitung Homebridge vergangene Woche auf dem Pi installiert zusammen mit dem genialen Installationsskript aus dem homematic forum.

Soweit funktioniert auch alles. Eve/HomeKit erkennt korrekt Lichtschalter, Dimmer, Thermostate (sofern man nur Kanal 2 nimmt) und auch Rollladen Aktoren.
Problem ist nur, dass Siri irgendwie nur zumachen will.

Beispiel: "Siri schließe den Rollladen im Schlafzimmer" ===> Funktioniert, Rollladen schließt sich, Siri quittiert

Beispiel: "Siri öffne den Rollladen im Schlafzimmer" => Fehlermeldung "Das kann ich leider nicht", "Das geht nicht", "Die Funktion wird nicht unterstützt".

Jedwede umformilierung wie "Fahre hoch"und Co geht auch nicht. Einzig der Befehl "Sire stelle den Rollladen im Schlafzimmer auf 100%" funktioniert. Ebenso alle anderen Prozentwerte.

Kann es sein, dass hier noch eine Funktion fehlt?
Es handelt sich um die HM-LC-Sw1PBU-FM

An sich herrscht die gleiche Problematik bei HM-LC-Bl1-FM und HM-LC-Bl1-SM auch...

Danke schon mal für eine Antwort...

vg

morpheus (du kennst mich ja schon :) )

**Comment by thkl** [comment]
Mahlzeit, 

ich habe leider keinerlei Einfluß auf die Siri Erkennung. Homebridge bzw das Plugin liefert nur eine Übersetzung der Homematic Geräte nach iOS Homekit. Was Siri dann aus den HomeKit Geräten macht und ob / wie Siri die Kommandos erkennt, liegt nicht an mir sondern an der Firma mit dem Apfellogo
