### ISSUE TITLE
Status Description | Translation 

### ISSUE THREAD

**Issue by CameronVIE** [thkl/homebridge-homematic#600]
I have some Shutters with Shelly and from Homematic some Sensors. 
The NAME of the Device can be changed in Homekit, but is there a chance to change the STATUSnaming of the Device.

For Example in english:  Shutter -> open -> closed                     is ok in english
For Example in german: Shutter -> öffnen -> geschlossen          sollte **GEÖFFNET** oder **OFFEN** heissen

WHO is responsible/can change the translation/naming?

Thanx for a hint how this works.

**Comment by Soilman82** [comment]
Das ist ein iOS Übersetzungsfehler und wohl seit iOS 13.3 so. 
Siehe auch https://github.com/thkl/homebridge-homematic/issues/486

**Comment by CameronVIE** [comment]
Danke Thomas!
Hoffentlich zieht apple das mal nach!
LG
--can be closed--

**Comment by Soilman82** [comment]
Bin zwar nicht Thomas, aber trotzdem gerne. 😄 Unser Profilbild hat allerdings eine gewisse Ähnlichkeit. 🤷🏻‍♂️

**Comment by CameronVIE** [comment]
Sorry Michael und Danke Michael! Ja, der schnelle Blick war nicht ausreichend :)

**Comment by thkl** [comment]
What ? 😂

**Comment by Soilman82** [comment]
War auf das schwarz-weiße bezogen, nicht aufs Aussehen an sich. 😂
