### ISSUE TITLE
Initiale Meldung „Standardraum Garage wurde geschlossen“ unterdrücken

### ISSUE THREAD

**Issue by Philipp1978** [thkl/homebridge-homematic#606]
Hallo zusammen,

ich habe leider erst beim Überarbeiten meine Umgangsformen wiederentdeckt. Bitte entschuldigt, das soll nicht wieder vorkommen. Folgende Thematik beschäftigt mich gerade im Kontext meiner Homematic Garagen-Lösung, die ich nach Anleitung umgesetzt habe. Ich bin noch immer sehr stolz, es hinbekommen zu haben. Nun wäre eine Nuance zu optimieren:

**Situationsbeschreibung**
Der Homebridge Service auf meinem Raspberry hängt sich leider ca. einmal am Tag auf. Es hilft dann ein Neustart des Services (oder auch des Raspberry). Das könnte ich über einen Cronjob lösen, der stündlich (oder alle x Stunden) den Homebridge Service neu startet. Nun bekomme ich bei einem Neustart des Services allerdings die Push-Benachrichtigung „Standardraum Garage wurde geschlossen“. Diese Meldung würde ich gerne zum Start des Services „unterdrücken“. 

**Lösungsvorschlag**
Eine Option, um die Initiale Meldung zu unterdrücken, wäre großartig.

Für Vorschläge und Rückfragen bin ich dankbar.

Gruß
Philipp

**Comment by robbyHuelsi** [comment]
Hallo,
ich bin in einer sehr ähnlichen Situation, wie @Philipp1978 beschreiben hat. Ich lasse die Homebridge jede Nacht einmal neustarten. Daher würde mich eine solche Option auch sehr interessieren!

Viele Grüße
Robert

**Comment by Philipp1978** [comment]
Hallo Robert,

hast Du das Problem noch? Ich konnte es letztlich umgehen, indem ich die Homebridge direkt auf die CCU3 installiert habe. Das erfordert nun keine Neustarts mehr.

Viele Grüße
Philipp

**Comment by robbyHuelsi** [comment]
Hallo Philipp,

danke für den Tipp! Ich habe inzwischen bei mir zu Hause auch [hap-homematic](https://github.com/thkl/hap-homematic) im Einsatz. Das Garagen-Problem besteht aber bei meinen Schwiegereltern. Wenn ich das nächste mal bei Ihnen bin, werde ich das testen.

Viele Grüße
Robert

**Comment by Philipp1978** [comment]
Hallo Robert,

ich drücke die Daumen, dass das klappt.

Falls Du bei Deinen Schwiegereltern mal in die Konfiguration reinschauen könntest, wäre das wirklich interessant. Ich habe an einer anderen Stelle ein Problem, das sich leider hartnäckig hält: siehe https://github.com/thkl/homebridge-homematic/issues/672#issue-830906951

Wenn Du mir einen Tipp geben könntest, wie das bei Dir aussieht, wäre ich sehr dankbar.

Viele Grüße
Philipp
