### ISSUE TITLE
Homematic_config.json mit 2 Homematic Instanzen 

### ISSUE THREAD

**Issue by peterg01** [thkl/homebridge-homematic#609]
**Describe the bug**
ich habe eine Homebridge mit 2 Homematic Instanzen auf meinem System. Nach dem UPDATE auf 231 werden die Variablen ( aus der 2. Instanz nicht mehr angezeigt). in der Homematic_config.json werden ausschliesslich die Eintrage der 1.Instanz angezeigt.

Version 
0.1.231

Ich habe auf der suche nach einer Lösung 'irgendwo' einen Kommentar von @tkhl gelesen das der Homematic Name eingetragen wird... 

Wie und Wo kann ich nun das Problem lösen

**Comment by franzel61** [comment]
keinen Stress.... habe auf HAP-Homematic gewechselt
