### ISSUE TITLE
Korrekte Definition von Outlets

### ISSUE THREAD

**Issue by morpheus12** [thkl/homebridge-homematic#61]
Hi,

da HomeKit auch global funktioniert z.B. "schalte alle Lichter ein" ist es ja doof wenn Schalter keine Lichter sind. Bei mir ist das z.B. bei zwei Deckenventilatoren der Fall.

Hierfür gibt es ja die "Outlets" in der Config.json

Wie sieht hier die korrekte Syntax aus? Ich nehme schwer an, dass hier die BidCosSN genutzt wird. Geht das so wie bei doors? Also...

"outlets":["BidCos-RF.KEQXXXXXXX:1","BidCos-RF.IEQXXXXXXX:1"]

...so?

**Comment by morpheus12** [comment]
Siehe readme.md stimmt so wie oben beschrieben

**Comment by thkl** [comment]
ja ;)
