### ISSUE TITLE
Zisterne/Füllstand

### ISSUE THREAD

**Issue by dinneatgithub** [thkl/homebridge-homematic#612]
**Is your feature request related to a problem? Please describe.**
Ich würde gerne den Füllstand der Zisterne anzeigen lassen. Werte sind 0-100%. 

**Describe the solution you'd like**
Falls Homekit nichts passendes hat, könnte man ja einen Rolladen simulieren und die Behanghöhe als Füllstand nehmen.

**Describe alternatives you've considered**

**Additional context**

Der Homematic Sensor heißt "HM-Sen-Wa-Od" 
https://de.elv.com/elv-homematic-komplettbausatz-kapazitiver-fuellstandsmesser-hm-sen-wa-od-fuer-smart-home-hausautomation-104945

So sieht er aus in /addons/xmlapi/statelist.cgi
Der Füllstandslevel ist in 
`<datapoint name="BidCos-RF.QEQ1647374:1.FILLING_LEVEL" type="FILLING_LEVEL" ise_id="31195" value="100"....>   `
 Hier also 100%

`
<device name="Zisterne" ise_id="31165" unreach="false" sticky_unreach="false" config_pending="false">
<channel name="Zisterne:0" ise_id="31166" index="0" visible="" operate="">
<datapoint name="BidCos-RF.QEQ1647374:0.UNREACH" type="UNREACH" ise_id="31186" value="false" valuetype="2" valueunit="" timestamp="1592055646" operations="5"/>
<datapoint name="BidCos-RF.QEQ1647374:0.STICKY_UNREACH" type="STICKY_UNREACH" ise_id="31182" value="false" valuetype="2" valueunit="" timestamp="1592055646" operations="7"/>
<datapoint name="BidCos-RF.QEQ1647374:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="31168" value="false" valuetype="2" valueunit="" timestamp="1592050440" operations="5"/>
<datapoint name="BidCos-RF.QEQ1647374:0.LOWBAT" type="LOWBAT" ise_id="31176" value="false" valuetype="2" valueunit="" timestamp="1592111513" operations="5"/>
<datapoint name="BidCos-RF.QEQ1647374:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="31180" value="1" valuetype="8" valueunit="" timestamp="1592055646" operations="5"/>
<datapoint name="BidCos-RF.QEQ1647374:0.RSSI_PEER" type="RSSI_PEER" ise_id="31181" value="166" valuetype="8" valueunit="" timestamp="1592055646" operations="5"/>
<datapoint name="BidCos-RF.QEQ1647374:0.DEVICE_IN_BOOTLOADER" type="DEVICE_IN_BOOTLOADER" ise_id="31172" value="false" valuetype="2" valueunit="" timestamp="1592055646" operations="5"/>
<datapoint name="BidCos-RF.QEQ1647374:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="31190" value="false" valuetype="2" valueunit="" timestamp="1592055646" operations="5"/>
</channel>
<channel name="Zisterne" ise_id="31194" index="1" visible="true" operate="true">
<datapoint name="BidCos-RF.QEQ1647374:1.FILLING_LEVEL" type="FILLING_LEVEL" ise_id="31195" value="100" valuetype="16" valueunit="%" timestamp="1592112851" operations="5"/>
</channel>
</device>
`

**Comment by iuliusmaximilian** [comment]
https://github.com/thkl/homebridge-homematic/wiki/Variablen-basierende-Batterie-Anzeige
