### ISSUE TITLE
Support for Wireless Doorbell Sensor

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#62]
Hi,

what do I need to do to add support for

- HM-Sen-DB-PCB Wireless Doorbell Sensor

as contact? I tried this

`            "services" : [
                {
                   "type": "HM-Sen-DB-PCB:PRESS_SHORT",
                   "service": "HomeMaticHomeKitContactService"
                }
            ]
`

but I now have a device "Not Supported"

**Comment by thkl** [comment]
ok i will check that ....

**Comment by dkrizic** [comment]
I haven seen that HomeKit has a device type for Doorbell (including Camera Doorbell), maybe it would make sense to expose it as this device.

BTW: Lieber deutsch? HomeMatic ist wohl nur in D verbreitet, oder?

**Comment by thkl** [comment]
<img width="623" alt="bildschirmfoto 2016-11-18 um 15 40 58" src="https://cloud.githubusercontent.com/assets/884355/20433780/7a67ef48-ada5-11e6-9be0-7779bf64618a.png">

Ähm, es gibt keinen DoorBell Sensor ?

**Comment by dkrizic** [comment]
Ich muss mal selbst forschen, es könnte eine Characteristics von Lock oder von Door sein

**Comment by thkl** [comment]
Nope, die Homebridge selbst bringt einen DoorBelll Service als Custom Service mit. Allerdings erkennt natürlich die  HomeApp diesen nicht. ..

**Comment by Samfox2** [comment]
Sie erkennt den Doorbell service zwar noch nicht ganz, die Benachrichtigungen "Türklingel klingelte" inkl. Snapshot funktionieren aber.

**Comment by thkl** [comment]
Ich hab das mal eingebaut. Es gibt einen HMServiceTypeDoorbell den benutze ich und setze beim Press_Short Event die dran hängende characteristic ProgrammableSwitchEvent kurz auf wahr.

Allerdings behauptet die Home App sie kennt das Gerät nicht und ich kann auch keine Mitteilungen dafür aktivieren .. hmm

**Comment by Samfox2** [comment]
Ja, das sagt die home app auch bei mir. Ich trigger das Event von extern mit nem curl befehl in einem bash script, das funktioniert dann trotzdem. Sollte analog auch bei dir funktionieren

**Comment by dkrizic** [comment]
Wie kann ich das testen? Muss ich auf den aktuellen master wechseln? Wie geht das?

**Comment by thkl** [comment]
Die Github Version hier hat das Doorbell File schon.

**Comment by Samfox2** [comment]
Das ging aber schnell. Braucht man da zum testen diesen Homematic-Sensor oder kann man das auch per Software emulieren/auslösen?

**Comment by thkl** [comment]
Ja kann man simmulieren. Es muss ein beliebiger Tastenaktor ins HomeKit Gewerk, und eine kleine Änderung an der channel_config.json gemacht werden. Letzter aktueller Eintrag ist:

`
{
	   "type": "HM-Sen-DB-PCB:KEY",
	   "service": "HomeMaticHomeKitDoorBellSensorService"
	}
`

der muss geändert werden in 

`{
	   "type": "KEY",
	   "service": "HomeMaticHomeKitDoorBellSensorService"
	}`


Damit werden alle Tasten als Türklingel betrachtet. Dann kann man das testen.
Eve kennt den DoorBell Sensor auch richtig.

**Comment by dkrizic** [comment]
Ich kann bestätigen: "Home" erkennt es nicht "Not Supported", aber Eve zeigt es als einen Kontakt an! Dann warten wir mal iOS 10.2

**Comment by Samfox2** [comment]
Aber funtioniert es denn? Also bei Auslösung Nachricht+Pic aufs iOS-Gerät?

**Comment by dkrizic** [comment]
Duty Cycle.. Aktuell geht garnichts 👎

**Comment by Samfox2** [comment]
Ich hab leider keinen Tastaktor...

**Comment by thkl** [comment]
Virtuelle Tasten sollten auch gehen.  Dann nur VIRTUAL_KEY statt KEY in der chanel_config

**Comment by Samfox2** [comment]
Ok, gerade mal als VIRTUAL_KEY definiert, löst aber zumindest bei mir keine Benachrichtigung aus. Die Umsetzung im Code schaut aber ok aus. In der App selbst wird der Status auch umgeschaltet. Wenn ich mich richtig erinnere, dann hatte das damals bei mir auch etwas gedauert, bis die 1. Benachrichtigung aufs Handy kam. Wir hatten das damals auf die icloud Aktualisierung geschoben. Funktionierte zunächst ebenfalls nicht, nach ein paar Stunden mit unverändertem Code aber schon. Also einfach mal abwarten...

**Comment by Samfox2** [comment]
Nochwas am Rande: Die Benachrichtigung kommt dann jeweils bei der Statusänderung also 1x von 0 auf 1 und dann nochmal von 1 auf 0 -> in deinem Fall also vermutlich 2x. Da wäre es besser, wenn du nur "togglest".

**Comment by dkrizic** [comment]
Bei mir passiert garnichts... Testet ihr schon alle mit iOS 10.2 beta?

**Comment by Samfox2** [comment]
Nö, ich bin auf 10.1.1

**Comment by Samfox2** [comment]
Erfolg! Funktioniert bei mir (wie erwartet 2x Benachrichtigung). Hab In der channel_config.json folg. Eintrag angepasst:

`    {
	   "type": "VIRTUAL_KEY",
	   "service": "HomeMaticHomeKitDoorBellSensorService"
	}`

Wenn man dann in der WebUI auf "Kurzer Tastendruck" klickt, erhällt man wie erwartet 2x eine Nachricht auf die verbundenen iOS Geräte (sofern sich eine Kamera im gleichen Raum befindet, auch mit Snapshot).

**Comment by Samfox2** [comment]
Jetzt noch ne Frage am Rande: Gibt es eine Möglichkeit, diesen VIRTUAL_KEY von aussen per Script zu schalten und so das Event auszulösen?

**Comment by thkl** [comment]
Ja über RegaHss http://ccuip:8181/foobar.exe?dom.GetObject("namedeskey").State(1)

**Comment by Samfox2** [comment]
Cool, danke sehr. Könntest du den Zustand des Doorbell-Sensors noch "togglen" anstatt kurz an/aus? Dann würde man nur eine Mitteilung bekommen.

**Comment by thkl** [comment]
du meinst beim ersten PRESS_SHORT den DP auf an und beim nächsten erst auf aus ?

**Comment by Samfox2** [comment]
Ja genau, immer umschalten.

**Comment by dkrizic** [comment]
Ich habe die aktuelle Version von HBHM drauf

    {
       "type": "HM-Sen-DB-PCB:KEY",
       "service": "HomeMaticHomeKitDoorBellSensorService"
    },

und die aktuelle Version von HomeMaticHomeKitDoorBellSensorService.js, aber bei mir taucht das Gerät immer noch als "Not Supported" auf (auch iOS 8.2 beta 4). Was mache ich falsch?

Kann ich caches löschen ohne alles neu pairen zu müssen?

**Comment by Samfox2** [comment]
Das ist schon richtig, da steht zwar "Not Supported", das Ereignis wird aber erkannt und löst auch eine "Home"-Benachrichtigung "Türklingel xlingelte" aus.

**Comment by dkrizic** [comment]
Kann ich bestätigen 

![screen shot 2016-11-30 at 17 45 50](https://cloud.githubusercontent.com/assets/1181349/20761953/f8d0af18-b724-11e6-850f-8a51776aa67f.png)

**Comment by Samfox2** [comment]
Pack mal ne Kamera in den gleichen Raum wie die Doorbell, dann kommt die Nachricht mit Pic.

**Comment by thkl** [comment]
Ich mach das mal zu

**Comment by dkrizic** [comment]
Komisch, bei mir hat das alles funktioniert und nach ein paar Umkonfigurationen haben die Benachrichtigungen aufgehört. Was muss ich jetzt genau konfigurieren, damit die Benachrichtigung kommen? Das Gerät ist im Gewerk "Homebridge" (so heisst es bei mir) und taucht in der Home-App auch als unsupported auf. Aber es löst keine Benachrichtigungen mehr.

Ich habe HBHM in der Version 0.6.6, beim Starten sehe ich:

`Apr  1 21:10:02 supermicro homebridge[31122]: [4/1/2017, 9:10:02 PM] [HomeMatic CCU] Initializing platform accessory 'Diele Türklingel'...
`

in der channel_config.json habe ich das hier:

```
        {
           "type": "HM-Sen-DB-PCB:KEY",
           "service": "HomeMaticHomeKitDoorBellSensorService"
        }
```

und nichts besonderes in der config.json. Was fehlt?

**Comment by Samfox2** [comment]
Der Doorbell-Service funktioniert nicht mehr, am besten auf Motionsensor umstellen, dann sollten die Benachrichtigungen wieder kommen.
