### ISSUE TITLE
Wettersensor HmIP-SWO-PL

### ISSUE THREAD

**Issue by FSTNDonald** [thkl/homebridge-homematic#624]
Angezeigt in Homebridge Accessories (sorry englische Oberfläche) werden nur (A) Temperatur, relative Luftfeuchte und Helligkeit, weitere Sensorwerte fehlen.

PS: in der CCU werden zusätzlich angezeigt aktuelle Werte für (B) Windstärke, Regen/Trocken und Regenmenge.
PPS: in der "@home" App auf IOS (Frontend zur CCU) werden darüber hinaus die gestrigen, heutigen und seit Reset aufgelaufenen Werte angzeigt (Regenmenge, Sonnenscheinstunden). Homebridge ist DEBMATIC auf Pi.

ZIEL: Ich möchte abhängig von der gestrigen Regenmenge einen Schalter (Bewässerung) auslösen. Der Schalter ist Apple Homekit nativ, also nicht Homematic. Idee ist, diese Logik als Automation in Homekit anzulegen, aber dazu benötige ich die Regenmenge von gestern.

In der CCU ist allen betreffenden Kanälen der Wetterstation (A+B) ein Raum (Garten) und ein Gewerk (Homekit) zugeordnet. Im Log der Homebridge sind auch CCU Meldungen zu Windstärke und Regen, aber die Sensoren (B) erscheinen nicht im Accessories Fenster der Homebridge und damit auch nicht in Homekit.
Dazu passt evtl. folgende Meldung im Log:
[9/5/2020, 10:09:17 AM] [HomeMatic CCU] [ServiceClassLoader] There is no service for HmIP-SWO-PL:COND_SWITCH_TRANSMITTER_WIND_SPEED
[9/5/2020, 10:09:17 AM] [HomeMatic CCU] [ServiceClassLoader] There is no service for HmIP-SWO-PL:COND_SWITCH_TRANSMITTER_RAIN_QUANTITY

Ich hoffe, dass Issue ist nicht schon vorher gemeldet / diskutiert / gelöst(?) worden. Trotz Recherche habe ich nichts gefunden ausser einem Eintrag von 2018, der darauf so konkret nicht einzugehen scheint.

Welches ist der richtige Weg, um die Regenmenge von gestern in Homekit zu bekommen?

Vielen Dank im voraus, VG Donald

**Comment by iuliusmaximilian** [comment]
@FSTNDonald Vielleicht einfach eine Hilfsvariable in der CCU und diesen "Schalter" aus der CCU auslösen und auf Äderung des Gerätes im Home mit einer Automation reagieren ? Zusätzliche Werte kannst du als Workaround auch über den BatteryService anzeigen.

**Comment by donald-debmatic** [comment]
Hi Julius,
vielen Dank für den Tipp, auf soetwas wird es wohl dann hinauslaufen. Mein Ziel war eigentlich, die 'Edge' Devices dumm zu halten und die Logik in der Spitze der Pyramide abzuwickeln. Ich lerne allerdings jeden Tag dazu, dass Homekit struntzdoof ist, grrr. Selbst Automationen, die in der App angelegt werden können (.... Schalter x zum Zeitpunkt y für z Minuten einschalten) kann SIRI nicht abbilden: "Schalte x jetzt für z Minuten ein" wird quittiert mit "ich habe x eingeschaltet" (... und der läuft dann ohne Ende).
Ich hoffe, dass die Konstruktion über Hilfsvariable und Auswertung eines in der CCU festgelegten Triggers auch in der CCU Emulation (Debmatic) wie in einer echten CCU funktioniert (... und über Updates Bestand hat). Werde Programmierung und Ergebnis hier berichten.

PS: es bleibt trotzdem die Frage, warum ein simples iOS Frontend auf diese CCU Daten Zugriff hat ohne Probleme und die Daten nicht in der Homebridge erscheinen ... ???

Merci und VG - Donald

**Comment by FSTNDonald** [comment]
Kann geschlossen werden, habe den Pi mit debmatic/homebridge/homematic-plugin durch eine echte CCU3 ersetzt, auf der Node-Red läuft.
