### ISSUE TITLE
Notification for doors

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#63]
Hi,

when I open a window, I receive a notification. This does NOT happen with doors. Is it possible to configure this?

Regards,

DK

**Comment by thkl** [comment]
i am not sure , but you can try to setup a notification for that door in the iOS home app.
got to the details of that door and there is a setting for status and notification ....

**Comment by dkrizic** [comment]
Negative, Doors don't offer any notification, opposite to Windows which do. Is it something that can be controlled by homegridge-homematic?

**Comment by thkl** [comment]
not at the moment.
