### ISSUE TITLE
Cool feature: Motion sensor triggers sending camera pictures

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#64]
Hi,

this is no issue, I just wanted to report a very nice feature of HomeKit. When a motion sensor detects a motion, then I receive notifications of all cameras in the same room. This notification contains a snapshot of the camera image.

This is very cool.

Regards,

DK

**Comment by thkl** [comment]
oh cool, didn't notice that....

**Comment by thkl** [comment]
hmm did not work for me .. i receive the notification for the motion but there is no image from the camera. ¯\_(ツ)_/¯

**Comment by Samfox2** [comment]
The cam has to be in the same room.

**Comment by thkl** [comment]
the cam is in the same room as mentioned in the first post ;o)

**Comment by dkrizic** [comment]
Do you an AppleTV or iPad?

**Comment by thkl** [comment]
ATV4 and the Status is "connected" in the HomeApp

**Comment by dkrizic** [comment]
Which plugin do you use for Camera? I have homebridge-camera-ffpeg and image depends on the power of the machine, try to reduce the resolution to 640x480 or so, this improved responsibility much and also allows LIVE views.

**Comment by thkl** [comment]
hmm ok .. i use  homebridge-camera-ffpeg on a Raspberry PI3 ... LiveView works (ok, there is a 5sec Gap)

**Comment by dkrizic** [comment]
Maybe to long for HomeKit

**Comment by thkl** [comment]
¯\_(ツ)_/¯ anyway ...

**Comment by Samfox2** [comment]
I use the same plugin. The latest version has an option for a snapshot location. If you use that the snapshot is directly used and not generated with ffmpeg which gives a good speedup. Use that and you are fine.
