### ISSUE TITLE
Filter unwirksam -   Error: Cannot Bridge more than 149 Accessories

### ISSUE THREAD

**Issue by Elisedd-Bradan** [thkl/homebridge-homematic#644]
**Fehlerbeschreibung:**
Nach dem Setup meldet das Logfile: Error: Cannot Bridge more than 149 Accessories

die Konfiguration sieht wie folgt aus:

 "bridge": {
        "name": "Homebridge CC57",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51038,
        "pin": "111-11-111"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "HomeMatic CCU",
            "ccu_ip": "xxx.xxx.xxx.xxx",
            "subsection": "HomeKit",
            "enable_hmip": true,
            "enable_wired": false,
            "ios10": true,
            "platform": "HomeMatic"
        }
    ]
}

Es sind ungefär 20 Devices in der CCU3 mit HomeKit getagt. Auch wenn man das Tagging ganz entfernt versucht das Plugin trotzdem alles zu importieren, was dann zu der Fehlermeldung der Bridge führt.

**Erwartetes Verhalten:** Es werde nur die Geräte importiert die auch das Gewerk "HomeKit" besitzen   

**Fehlermeldung:**

Error: Cannot Bridge more than 149 Accessories
    at Bridge.Accessory._this.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:421:13)
    at /usr/lib/node_modules/homebridge/src/server.ts:430:25
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge/src/server.ts:417:21
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at HomeMaticPlatform.buildaccesories (/usr/lib/node_modules/homebridge-homematic/index.js:463:3)
    at /usr/lib/node_modules/homebridge-homematic/index.js:278:12
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:42:9)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)

**Version**  v0.1.231

**Comment by Elisedd-Bradan** [comment]
Aus nicht wirklich nachvollziehbaren Gründen ging es irgendwann. Könnte es möglich sein, das wenn in der CCU kein Gewerk zugewiesen ist alles importiert wird?

**Comment by thorstendorn** [comment]
I am having the exact same issue, but it does not "auto-resolve" itself.
I have a "blank" CCU3 that I want to connect to HomeKit via Homebridge. It is running firmware version 3.55.5 with no (!) accessories connected to it, except the virtual standard accessories "HM-RCV-50 BidCoS-RF" and "HmIP-RCV-50 HmIP-RCV-1". The Homematic plugin is reporting the error as quoted above ("Error: Cannot Bridge more than 149 Accessories [...]").
Any hint, how I could solve that?

**Comment by FSTNDonald** [comment]
my learning:
I 'gave up' troubleshooting the homematic plugin.
Installed the "redmatic Zusatzsoftware" on CCU3.
No more problems ... and a free raspi ;-))
