### ISSUE TITLE
Request: Expose HM-Sec-WDS-2 as Leak Sensor

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#65]
Hi,

I would like to expose my Leak Sensor HM-Sec-WDS-2 as HomeKit Leak Sensor. I configured it as Contact, seems to work, but there is no notification. I presume a Leak Sensor DOES notifications.

Regards,

DK

**Comment by thkl** [comment]
ok i implemented such a sensor , but i can not test ...

Instructions : 

Get the file https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitLeakSensorService.js  put it to  homebridge-homematic/ChannelServices  and put the following to your config.json to activate the new device:


"services": [
    { "type": "WATERDETECTIONSENSOR",
          "service": "HomeMaticHomeKitLeakSensorService"
    }]

**Comment by dkrizic** [comment]
Sieht auf den ersten Blick gut aus, das Ding erscheint bei mir als "Leak Sensor" mit "Leak Detected" = "No". Notifications werden hier nicht angeboten. Ich teste es mal, wenn ich zuhause bin.

**Comment by dkrizic** [comment]
DANKE! Ihr seid echt cool

**Comment by thkl** [comment]
Ok , danke. Ich würde das dann in die normale ChannelConfig einbauen, wenn es funktioniert.

**Comment by dkrizic** [comment]
Also, der Sonsor reagiert NICHT! Wie kann ich das besser debugged?

**Comment by thkl** [comment]
die Bridge im Debug Modus starten : DEBUG=* homebridge -D

Dann läuft da ziemlich viel Log durch den Screen.
Wenn der Melder von HM Seiten auslöst sollte sowas hier erscheinen 

> HomeMaticRPC RPC event for BidCos-RF.MELDERADRESSE:1 STATE with value true +1ms

Das bedeutet die Bidge hat von der CCU die Statusänderung bekommen.

darauf sollten dann als nächste Einträge sowas wie hier kommen

>  EventedHTTPServer [::ffff:XXX.XXX.XXX.XXX] Sending HTTP event '17.9' with data: {"characteristics":[{"aid":17,"iid":9,"value":true}]} +10s

Die XXX sind die IP eines Deiner angemeldeten HomeKit Geräte. die aid und iid können abweichen, das sind die internen IDs der Geräte und Charakteristiken.

**Comment by dkrizic** [comment]
Ich habe mal den Wassermelder ins Wasser gelegt (nass) bzw. nur die äusseren Beinchen (feucht), dann sehe ich das hier im Log:

`Nov 19 20:11:43 supermicro homebridge[3935]: Sat, 19 Nov 2016 19:11:43 GMT HomeMaticRPC RPC event for BidCos-RF.LEQ0100873:1 STATE with value 0
Nov 19 20:11:43 supermicro homebridge[3935]: Sat, 19 Nov 2016 19:11:43 GMT HomeMaticRPC RPC event for BidCos-RF.LEQ0100873:1 LOWBAT with value false
Nov 19 20:11:51 supermicro homebridge[3935]: Sat, 19 Nov 2016 19:11:51 GMT HomeMaticRPC RPC event for BidCos-RF.LEQ0100873:1 STATE with value 1
Nov 19 20:11:51 supermicro homebridge[3935]: Sat, 19 Nov 2016 19:11:51 GMT HomeMaticRPC RPC event for BidCos-RF.LEQ0100873:1 LOWBAT with value false
Nov 19 20:12:02 supermicro homebridge[3935]: Sat, 19 Nov 2016 19:12:02 GMT HomeMaticRPC RPC event for BidCos-RF.LEQ0100873:1 STATE with value 2
Nov 19 20:12:02 supermicro homebridge[3935]: Sat, 19 Nov 2016 19:12:02 GMT HomeMaticRPC RPC event for BidCos-RF.LEQ0100873:1 LOWBAT with value false
Nov 19 20:12:07 supermicro homebridge[3935]: Sat, 19 Nov 2016 19:12:07 GMT HomeMaticRPC RPC event for BidCos-RF.LEQ0100873:1 STATE with value 0
Nov 19 20:12:07 supermicro homebridge[3935]: Sat, 19 Nov 2016 19:12:07 GMT HomeMaticRPC RPC event for BidCos-RF.LEQ0100873:1 LOWBAT with value false
`

**Comment by dkrizic** [comment]
Ich habe mal testweise IPv6 auf dem Server deaktiviert, gleiches Verhalten.

**Comment by thkl** [comment]
ah ok ich sehe gerade der HM Sensor liefert auf dem State Parameter 0 / 1 / 2 ich bin von true false ausgegangen ...  Ich ändere das mal.  Der HomeKit Leak Sensor kennt allerdings nur ja/nein .. also werde ich 0 = trocken  und 1 (Wet) & 2 (water) auf Nass mappen.

**Comment by dkrizic** [comment]
Ja, der kann die Unterscheidung, coole Konstruktion eigentlich. Danke, ich werde dann testen.

**Comment by dkrizic** [comment]
Ich habe Deinen commit gesehen und auch Homegear neu gestartet, aber ich hänge durch die ständigen Restart von Homegear voll im Duty Cycle.... Wenn der weg ist, teste ich und sage Bescheid

**Comment by dkrizic** [comment]
so, es funktioniert alles! Trocken (0), Feucht (1, an), Nass (2, an)

**Comment by thkl** [comment]
F*ck yeah 🤙
