### ISSUE TITLE
What is meant with subsection

### ISSUE THREAD

**Issue by zap2021** [thkl/homebridge-homematic#653]
If i connect the Plugin with my Rasperymatic (3.53.30.20201024), nearly every posible device in the CCU ist connected. Even if i select "enable_hmip": false and "enable_wired":false. 
By reading the documentation i found the "subsection", witch is to create in the CCU, but i do not know what you mean with this? A Group? A Room? Has somebody a hint for me?
Thanks a lot!

**Comment by Dada40** [comment]
After setting up the plugin today for the first time, the same question and confusion came up for me.
A "subsection" seems to be called "Function" (or in german: "Gewerke") on the CCU.

New Functions can be added in the Settings menu (choosing "Functions" and pressing "Edit" button at the bottom of the page).

**Comment by zap2021** [comment]
Thank's for the hint.
