### ISSUE TITLE
doors werden nicht erkannt "Not supported"

### ISSUE THREAD

**Issue by dkrizic** [thkl/homebridge-homematic#66]
Ich habe einige HM-Sec-SC (Fenster-Kontakt-Sensoren). Diese werden standardmässig als Kontakt erkannt und ich kann sie als Tür umdefinieren. Wenn ich sie aber als "doors" eintrage, dann hat dieses Device "Not supported".

```
            "doors" : [
                "BidCos-RF.LEQ0034XXX:1",
                "BidCos-RF.LEQ0034XXX:1",
                "BidCos-RF.KEQ0803XXX:1",
                "BidCos-RF.KEQ1031XXX:1"
            ],
```  

Mache ich was falsch?

**Comment by bprskalo** [comment]
hast du die geräte auch in der subsection die geladen wird ? :-)

**Comment by dkrizic** [comment]
Ja, habe ich. Wenn ich sie aus "doors" entferne sind sie ja auch da als "Contacts", sonst würden sie ja garnicht erscheinen.

**Comment by bprskalo** [comment]
stimmt .. war ne idee :-)

kennst du die optionen in der Home APP ?


so solltest du dein problem lösen können.

**Comment by dkrizic** [comment]
Wie gesagt, wenn ich sie aus "doors" herausnehme, dann sind es Contacts und ich kann daraus dann Türen machen. Diese werden auch als Türen angezeigt und funktionieren auch, aber ich der Unterschied zu "richtigen" Türen ist, dass diese eine Notification verschicken (können), was bei den "Contact-Türen" nicht der Fall ist.

Wenn ein Gerät "Not Supported" ist, dann kann ich in der Apple Home-App damit nur den Namen ändern und den Raum zuweisen, sonst nichts. Ansonsten sind sie nur ein totes Haussymbol.

Ich wundere mich halt nur deswegen, weil das bei anderen Leuten scheinbar funktioniert und ich verstehe nicht warum.

**Comment by bprskalo** [comment]
faktisch ist es so, dass ein kontaktsensor nachrichten versenden kann.

was ich mir jetzt nicht sicher bin ob dies erst mit ios 10.2 geht (auf der ich gerade bin)

**Comment by dkrizic** [comment]
Ist das Versenden von Nachrichten bei einem Kontaktsensor bei homebridge-homematic implementiert? 

Ich bin auf der aktuellen iOS 10 (GA), keine Beta.

**Comment by bprskalo** [comment]
das hat nicht mit homebridge-homematic zu tun. es ist Bestandteil von homekit .. und in dem fall ab der Version 10.2 ausgebaut worden um auf der einen seite mehrere typen zuweisen zu können und auf der anderen seite sich bei einer Statusänderung benachrichtigen zu lassen. 

mit anderen worten .. wurde Homekit ausgebaut .. 

homebridge-homematic kann das ja schon :-)

ehm .. ich habe vorher Bilder gepostet .. sehe diese hier aber nicht .. hast du welche bekommen ?

**Comment by offle** [comment]
Bei mir ist auch seit der 10.2 beta möglich, für alle Kontaktsensoren den Typ festzulegen und ob Push Nachrichten versendet werden können. Die 10.2 ist schon recht weit bei Apple, ist wohl nur noch eine Frage von wenigen Tagen/Wochen denke ich.

**Comment by dkrizic** [comment]
@bprskalo Ich habe keine Bilder gesehen
@offle und @bprskalo Ah, schön zu hören, dass Apple HomeKit und Home weiterentwickelt hat, vielleicht lege ich mir die 10.2 aufs Handy

Aber zusammengefasst heisst das: "doors" funktioniert nicht, aber mit 10.2 kann man bei normalen Kontakten definieren, dass es eine Notification gibt; und homebridge-homematic kann es schon, cool.

**Comment by bprskalo** [comment]
![type](https://cloud.githubusercontent.com/assets/17832335/20430375/42900a3a-ad94-11e6-91b2-0878e277929b.png)

hier zum thema typen

**Comment by bprskalo** [comment]
![notification](https://cloud.githubusercontent.com/assets/17832335/20430379/50e8e980-ad94-11e6-9a94-ad9d3400bd66.png)
und das ist der bildschirm zu den benachrichtigungen

**Comment by bprskalo** [comment]
mit anderen worten .. ist die 10.2 die Lösung zu deinem Problem :-)

**Comment by dkrizic** [comment]
Wie sieht das bei einer Tür aus?

**Comment by dkrizic** [comment]
Das würde auch #65 verbessern, der Wassermelder ist aktuell auch ein Contact aber ohne Notification, wobei HomeKit einen Leak Sensor kennt.

**Comment by bprskalo** [comment]
das symbol ändert sich (eine Türe wird angezeigt) der erst bleibt gleich in der Funktionalität .. sprich .. wenn sich die "Türe" oder der Sensor auf geöffnet ändert .. erhältst  du eine Meldung ..

**Comment by dkrizic** [comment]
Ich habe gerade das hier gefunden: https://smartapfel.de/ios-10-2-bringt-benachrichtigungen-fuer-weitere-homekit-geraete/

Jetzt kann ich mich auch wieder über Notifications freuen, wenn der Briefkasten geöffnet wurde.

**Comment by dkrizic** [comment]
Ich habe mal iOS 8.2 beta 4 auf mein iPad gemacht. Dort kann ich bei den Türen dann Notifications einschalten und sie funktionieren auch!

**Comment by udochrist** [comment]
Das gleiche Thema habe ich auch. Wenn die Sensoren als "door" oder "window" eingetragen sind, dann funktioniert das "details" in der Home.app nicht. wenn die sensoren ohne "door" oder "window" geladen werden, dann kann man in der Home.app Türen und Fenster draus machen.

Das könnte 2 Gründe haben die ich jetzt aber nicht einschätzen kann
1) Die Sensoren waren mal ohne "door" und "window" konfiguriert und die Home.app hat sich das gemerkt und kommt jetzt ins straucheln wenn sich der Typ ändert
2) Der Typ der geliefert wird für Doors ist eben kein Shutter vom Typ Door sondern was anderes.

Interessanterweise hatte ich einen Fensterkontakt der als "window" funktioniert hat. Der zeigt dann aber noch "Obstruction detected" als property an. Das lässt vermuten dass das Problem eher #2 ist.

**Comment by thkl** [comment]
So, die aktuelle GitHub Version hat das mit den Doors und Windows jetzt gefixt.
Ebenso das Obstacle Problem

**Comment by udochrist** [comment]
Danke für den schnellen Fix!
Das update hats aber noch nicht bis zum node npm Modul geschafft. das steht noch auf 0.62.

Grüße und guten Rutsch!

**Comment by dkrizic** [comment]
Getestet, funktioniert jetzt

**Comment by udochrist** [comment]
Sorry. Muss da nochmal nachhaken. Irgendwie scheint das bei mir nicht zu passen.
mit der 0.0.63 und einem "optischen Sensor" montiert am Fenster und diesem Sensor eingetragen als "window" unter ios10 mit ios10 als true in der Konfig. wird in der Home.app plötzlich ein Gerät das ich per Schieberegler prozentual öffnen oder schliessen könnte und das auf einfachen druck öffnet oder schliesst, also wie ein Türoffner. Das ist was komplett anderes als ein SHUTTER CONTAT Typ Tür der nur den Status anzeigt. Notifications gehen damit übrigens nicht.

**Comment by thkl** [comment]
Ja, das ist so. Die IOS HomeApp und damit auch Siri erkennt die Floskeln "Fenster" nur wenn das Gerät als sog. motorisiertes Fenster in Homekit erscheint. Damit hat es das oben beschriebene Verhalten. Der Schieberegler bewirkt aber nichts. Notifications beim Öffnen oder Schließen des Fensters sollten aber funktionieren, das hab ich ausprobiert.

Wenn Du die Fensterkontakte nicht mit Siri abfragen möchtest dann lasse die Geräte aus der window Liste raus, dann kommen sie als Kontakte.
