### ISSUE TITLE
Error after Updating HB to 1.3

### ISSUE THREAD

**Issue by docNeptun** [thkl/homebridge-homematic#660]
After updating Homebridge to version 1.3, the plugin threw the following Error messages:

> Error: characteristic value NaN is not contained in valid values array!
>     at PositionState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2028:15)
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
>     at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindSlatServiceIP.js:53:13
>     at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:410:13
>     at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:597:9
>     at /usr/local/lib/node_modules/homebridge-homematic/index.js:654:9
>     at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:66:9
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:42:9)
>     at IncomingMessage.emit (events.js:327:22)
> [21/02/2021, 13:31:11] Got SIGTERM, shutting down Homebridge...

I had to disable the plugin :(

**Comment by thkl** [comment]
please update to the latest version 0.2.224 to fix this

**Comment by thkl** [comment]
oh, i forgot to fix this in the ip blind slat service .. 0.2.225 will do the job ....
