### ISSUE TITLE
Windows report as open although being closed in HomeMatic after updating to 0.2.225

### ISSUE THREAD

**Issue by Tylli** [thkl/homebridge-homematic#661]
**Describe the bug**
After updating and restarting Homebridge all windows report as open. They sometimes toggle between closed/open state but quickly revert back to open and stay that way. Tried a couple of restarts. Homematic reports "closed" state.

Version [0.2.225]

**Which Homematic Device or Service the bug is about**
HMIP-SWDO 

After reverting back to 0.1.231 everything works fine again

**Comment by thkl** [comment]
oh ok, i had to change a return value to make this in homebridge 1.3 work. And i've messed the values up.
This will be fixed in 2.226

**Comment by Tylli** [comment]
Is fixed!
