### ISSUE TITLE
POWERMETER Service für HM-LC-Sw1-Pl-DN-R5

### ISSUE THREAD

**Issue by bprskalo** [thkl/homebridge-homematic#70]
Hat schon jemand einen Service erstellt für die POWERMETER Funktionen des HM-LC-Sw1-Pl-DN-R5 ?

**Comment by thkl** [comment]
ähm laut Doku http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/hm_devices_Endkunden.pdf ist das ein normaler SWITCH ..

**Comment by bprskalo** [comment]
ja, der SWITCH an und für sich  ja, aaaber .. es gibt diverse Werte die so nicht ausgelesen werden wie aktuell verwendete Leistung in Watt.. etc) .. und as wäre ja dann interessant :-)

**Comment by bprskalo** [comment]
oder mit anderen Worten .. alles was der Kanal 2 liefert ...

**Comment by thkl** [comment]
Da ist kein Kanal 2 nach dem was oben in dem PDF steht ... ?

**Comment by thkl** [comment]
Ach und außerdem bin ich gerade mal durch den Homekit Accessory Simulator gesurft .. Es gibt auch keinen Service für Energiemessung ..also weder sowas wie current Voltage oder irgendwas was ich als Power Consumption nehmen könnte.

Kann man zwar alles als Custom machen, aber dann beschwert sich ja wieder der feine Herr Home.app

**Comment by Samfox2** [comment]
Den gibt es nur als custom für die EVE-App.

https://gist.github.com/gomfunkel/b1a046d729757120907c

**Comment by bprskalo** [comment]
kanaltyp POWERMETER Seite 161 :-) 

ok, das heisst, das diese werte nur mit EVE angezeigt werden .. ? kann man denn diese aus dem System lesen damit diese dann auch weiterverwendet werden können ? gleiches auch zum Beispiel für den Batery State bei den Geräten ?

**Comment by bprskalo** [comment]
Die Werte von "gomfunkel" kannte ich schon .. hab mich ja auch versucht etwas einzulesen bevor ich die Frage gestellt habe :-)

**Comment by thkl** [comment]
jaja bei HM-ES-**PM**Sw1-Pl-DN-R5 aber nicht bei HM-LC-Sw1-Pl-DN-R5 ;) ... 

ich kleb da mal nen Service zusammen

**Comment by bprskalo** [comment]
HM-ES-PMSw1-Pl-DN-R5 ... den eine ich natürlich auch  :-) 

boh das wäre natürlich seehehr cool !!

**Comment by thkl** [comment]
.. done

![img_0230](https://cloud.githubusercontent.com/assets/884355/20866330/80395320-ba2b-11e6-9d66-2238832628d8.PNG)

**Comment by bprskalo** [comment]
Wunderbar !! Danke DIR !! 

das "Home" das nicht anzeigen kann .. liegt an "Home" .. richtig .. ?

**Comment by thkl** [comment]
jap .. der feine Herr Home.app aus dem Hause Apple möchte nicht mit fremden Characteristics spielen ... 
Dabei könnten die das locker, denn sie haben das Protokoll extra so designt das man beim Erstellen einer custom characteristics alles Wichtige mitgeben muss (Name, Werte, Einheiten, Modi etc) .. 

Deswegen kann Eve ja auch mit unbekannten Geräten umgehen, die machen das richtig. Sie zeigen vielleicht nicht das richtige Icon an, aber sie können ein unbekanntes Gerät rudimentär unterstützen.

Nuja

**Comment by bprskalo** [comment]
ok, danke für die Ausführung, habe ich so verstanden ! ist das auch der Grund, warum Thermostaten getrennt angezeigt werden (Temperatur und Feuchtigkeit ) ?

**Comment by bprskalo** [comment]
und noch eine frage ..  wie ist das mit den battery state für die Geräte .. kann das schon abgefragt werden oder müssten da die SERIVICES ausgebaut werden ?

**Comment by thkl** [comment]
Thermostate ja die kommen aus 2 Kanälen der CCU und damit werden es 2 HK Geräte isn bissel doof ..  mit bissel "walk the extra mile" könnte man das verbessern

Batteriestatus , ja dazu müssen die Services erweitert werden. Und nicht jedes HM Gerät liefert mit den Batteriestatus im Value Parameterset (meist nur die neueren). Die alten haben nur einen LOWBAT Datenpunkt aber der ist im Masterset ...... und dann wird es richtig fies ... 

Bei den neuen Thermostaten / Ventilen könnte man das einbauen ...

**Comment by bprskalo** [comment]
das mit dem Battery Level oder Status wäre halt super wenn man eine Meldung bekommt .. aber ja, dafür gibt es ja noch die guten "alten" Homematic Apps ..

ein weitere Interessanter Wet wäre auch die VALVE .. aber eben ... es müsste dann halt auch richtig angezeigt werden .. mal sehen was iOS 12 oder 13 bringen wird :-) 


Danke Dir nochmals für den schnellen Service !!
