### ISSUE TITLE
services

### ISSUE THREAD

**Issue by gernot1972** [thkl/homebridge-homematic#73]
Ich hab es leider immer noch nicht richtig verstanden wie ich ein noch nicht unterstütztes Gerät selbst mit den Services einbinden kann.
Ich habe gesehen dass es bereits ein CuxDThermostatService gibt.
Wie sage ich jetzt der Homebridge, dass mein Kanal CUX9002001:2 dieses Service verwenden soll und ein Thermostat ist?
Und was ist der Unterschied zum ThermalControlService?

**Comment by thkl** [comment]
Schieb den Kanal mal mit in das HomeKit Gewerk .. Beim Start siehst Du dann entweder das er ihn zuordnen konnte oder es kommt eine Meldung There is no service for  .... foo bar ... 

Das was bei foo bar steht ist entscheidend.

**Comment by gernot1972** [comment]
werde es heute mal testen!

**Comment by gernot1972** [comment]
Folgendes Verhalten: Keine Fehlermeldung wenn ich die Kanäle 1 und 2 aufnehme, allerdings:
1. für den Kanal 1 wird die Temperatur schön ausgegeben allerdings ist ja nur der Temperaturfühler zugeordnet ohne Luftfeuchte die muss ich da irgendwie wieder rausgeben (sonst wird sie ebenfalls angezeigt aber mit 0%, was zu einer falschen Berechnung der Luftfeuchte führt, wenn ich das Gerät einem Raum zuordne). Der Kanal wird lt. Home App übriges dem Modell WEATHER zugeordnet.

2. Der Kanal 2 vom CUxD sollte das Thermostat sein - da steht aber "keine Antwort".
in der Home App ist das Modell CLIMATECONTROL_R...

**Comment by gernot1972** [comment]
Komme langsam dahinter...
Nachdem ein CUxD Gewrät einem Homematic Gerät von der Type zugeordnet ist, ist das eingestellte Service natürlich der normale Thermostatservice.
Ich müsste also dem Thermostat eine andere Type zuordnen in CUxD und dann den Kanaltyp CLIMATECONTROL_REGULATOR auf den CUxD Service - stimmt das so?
Oder kann ich auch per Seriennummer zuordnen also so: 

`"services": [
    { "type": "CUX9002001:2:CLIMATECONTROL_REGULATOR",
          "service": "HomeMaticHomeKitCuxDThermostatService"
    }]`

**Comment by thkl** [comment]
nein, man kann das nur für den gerätetypen und den kanaltypen festlegen. Seriennummern gehen nicht.

**Comment by gernot1972** [comment]
Ich habe den Typ in Cuxd jetzt geändert auf das alte Thermostat HM-CC-TC.  Das habe ich sonst nicht in Verwendung und dort das Service zugeordnet.
Leider auch noch ohne Erfolg.
In der WebUI geht der Thermostat übrigens.

Aber irgendwie hat diese Type ja auch noch eine Besonderheit - zumindest im Json File steht da noch etwas mit Filter...

Sent from a mobile device. I appologize for the brevity and typos.
