### ISSUE TITLE
Homematic IP

### ISSUE THREAD

**Issue by Telefisch** [thkl/homebridge-homematic#74]
Gibt es eine Chance mit der Homematic IP-Bridge dieses Plugin zu verwenden?

**Comment by thkl** [comment]
Meinst Du mit dem IP Accesspoint ( http://www.eq-3.de/produkte/homematic-ip/heizung-und-klima/home-control-access-point.html )


Nein

**Comment by nilsleiffischer** [comment]
@thkl Ist dies weiterhin der Fall? Kennst du eine Möglichkeit, Geräte über den Homematic IP Access Point mit HomeKit anzusprechen?
