### ISSUE TITLE
There is no service for VARIABLE:undefined

### ISSUE THREAD

**Issue by cschacht** [thkl/homebridge-homematic#75]
Hi,

I'm trying to add a systems variable to homebridge my configuration looks like this:

"platforms": [
    {
      "platform": "HomeMatic",
      "name": "Homatic CCU",
      "ccu_ip": "x.x.x.x",
...
     "variables":["Anwesenheit"]
}]}

When I'm starting homebridge I'm getting a message

[Homatic CCU] There is no service for VARIABLE:undefined

and I can't see the variable in Eve or Home app. (I'm expecting it to show up as switch). Homematic Plugin Version is 0.0.56

Any clues?

Thx
Chris

**Comment by thkl** [comment]
yeah my bad .. will fix this soon

**Comment by thkl** [comment]
should work in .59 now ...

**Comment by cschacht** [comment]
Fantastic! I'm trying to update the version ('sudo npm -g update homebridge-homematic'). The command executes just fine however no new version is installed. I'm running on Rasbian. What am I missing?

**Comment by thkl** [comment]
¯\_(ツ)_/¯ the 0.0.59 is the latest version @ https://www.npmjs.com/package/homebridge-homematic

**Comment by cschacht** [comment]
Hm, a bit strange. I've done a reinstall ('sudo npm install -g homebridge-homematic') which is pulling the latest version.

Now Variable is showing up as switch as expected :)

Great stuff!
