### ISSUE TITLE
Feature Request Integration der Lightify Lampen über CCU 

### ISSUE THREAD

**Issue by Bettarg** [thkl/homebridge-homematic#76]
Hallo,

Erstmal vielen Dank für die ganze Arbeit 👍🏻

Was mir aktuell fehlt ist die Unterstützung der Lightify Lampen über die CCU. Dort werden sie ja als Virtuele Kanäle angelegt , diese bekomme ich aber nicht über die Homebridge ins HomeKit. 

Vielen Danke 😀

**Comment by thkl** [comment]
Ich glaub , es gibt ein Lightify Plugin für Homebridge ..

**Comment by Bettarg** [comment]
Hallo, 

ja gibt es. Das läuft aber nicht wirklich sauber und der Entwickler scheint eine menge anderer dinge um die Ohren zu haben 😊
