### ISSUE TITLE
HMIP-WTH und HMIP-eTRV

### ISSUE THREAD

**Issue by jmeinicke** [thkl/homebridge-homematic#77]
Hi, 

kannst Du bitte HMIP-WTH und HMIP-eTRV mit aufnehmen?

Wäre prima.

Danke.

**Comment by thkl** [comment]
Die Github Version hier kennt das jetzt . Sollte funktionieren.
NPM habe ich noch nicht aktualisiert.

**Comment by jmeinicke** [comment]
hmm bist Du sicher? Der letzte Change stammt von gestern. Habe es auch per git clone heruntergeladen und Dateien ausgetauscht, bekomme aber gleichen Fehler:

`HomeMatic CCU] There is no service for HMIP-eTRV:HEATING_CLIMATECONTROL_TRANSCEIVER
Dec 12 18:38:50 pi homebridge[3275]: [2016-12-12 18:38:50] [HomeMatic CCU] There is no service for HMIP-WTH:HEATING_CLIMATECONTROL_TRANSCEIVER
Dec 12 18:38:50 pi homebridge[3275]: [2016-12-12 18:38:50] [HomeMatic CCU] There is no service for HMIP-eTRV:HEATING_CLIMATECONTROL_TRANSCEIVER
Dec 12 18:38:50 pi homebridge[3275]: [2016-12-12 18:38:50] [HomeMatic CCU] There is no service for HMIP-eTRV:HEATING_CLIMATECONTROL_TRANSCEIVER
Dec 12 18:38:50 pi homebridge[3275]: [2016-12-12 18:38:50] [HomeMatic CCU] There is no service for HMIP-eTRV:HEATING_CLIMATECONTROL_TRANSCEIVER
Dec 12 18:38:50 pi homebridge[3275]: [2016-12-12 18:38:50] [HomeMatic CCU] There is no service for HMIP-eTRV:HEATING_CLIMATECONTROL_TRANSCEIVER`

Oder mache ich was falsch?

Danke

**Comment by thkl** [comment]
Commit ohne Push, ich kann's noch .. :) jetzt aber

**Comment by jmeinicke** [comment]
yeah :-) funktioniert!

vielen lieben Dank!
