### ISSUE TITLE
HMIP-PSM Messkanal

### ISSUE THREAD

**Issue by masetho** [thkl/homebridge-homematic#78]
Hallo,

vielen Dank erstmal für die großartige Arbeit hier.
Ich würde gerne wissen ob der Messkanal des HMIP-PSM unterstützt wird. 

Grüße

**Comment by thkl** [comment]
aktuell nicht, in Kürze ja

**Comment by masetho** [comment]
ah okay, super dann warte ich einfach ab :)

**Comment by thkl** [comment]
sollte in der GitHub version gehen

**Comment by masetho** [comment]
Jep, funktioniert soweit, allerdings nur in der Eve App.
In der "normalen" Home App wird der nur als schaltkontakt angezeigt. Ich nehme aber mal an das liegt an der App?

Ach und ich bekomme demnächst den unterputz aktor von Homematic ip. Der heißt glaub ich Hmip-fsm. Wird der auch schon unterstützt ?

Gruß und danke

**Comment by thkl** [comment]
ja wird

**Comment by ChrWi** [comment]
@thkl nach erfolgreicher Konfiguration der Garagentors (danke) ist nun ein HMIP-PSM dran gewesen. Mit Bezug auf diesen älteren Thread: Messkanal funktioniert - ich bekomme Current, Voltage und Power in der Eve App angezeigt. Zwei Punkte würde ich besser gelöst bekommen:
1) Anzeige des Energy Counters (Wh) (der laut statelist auch im Channel 6 ausgegeben wird)
2) Festlegen, welcher Messwert auf der Statusseite erscheint Voltage scheint fix eingestellt zu sein.
Danke!
