### ISSUE TITLE
Don't get variables, windows and programs imported...

### ISSUE THREAD

**Issue by watercove** [thkl/homebridge-homematic#80]
any idea what I'm doing wrong?

**Comment by thkl** [comment]
can you please post the startup log ....

**Comment by watercove** [comment]
Works. Edited the wrong config file.

Rajko Patz
0173 3561312
Rajko.Patz@pingpoint.de<mailto:Rajko.Patz@pingpoint.de>

On 22 Dec 2016, at 09:53, Thomas Kluge <notifications@github.com<mailto:notifications@github.com>> wrote:


can you please post the startup log ....

-

**Comment by thkl** [comment]
👍
