### ISSUE TITLE
HmIP-WTH-2

### ISSUE THREAD

**Issue by qarell** [thkl/homebridge-homematic#81]
Hallo, eine wahnsinns Arbeit!!
Könntest die HmIP-WTH-2 vielleicht auch noch mit aufnehmen?

Danke.

**Comment by thkl** [comment]
ich schau mir das mal an

**Comment by qarell** [comment]
Super, vielen Dank.

**Comment by thkl** [comment]
die aktuelle GitHub Version sollte das können. Dazu muss der Kanal 1 des HmIP-WTH-2 hinzugefügt werden. Ich bau mal ein neues npm draus

**Comment by qarell** [comment]
Danke Dir für das schnelle Einbinden, werde es testen, sobald ich das mit dem Update der npm hinbekommen habe.

Vielen Dank

**Comment by drtp** [comment]
Im Unterschied zum HM-Wandthermostaten HM-TC-IT-WM-W-EU wird mir beim HmIP-WTH-2 nicht die Luftfeuchtigkeit in der Home App angezeigt, obwohl Kanal 1 die eigentlich überträgt. Könnte man das ggf. noch anpassen, oder mache ich da was falsch?
