### ISSUE TITLE
homebridge crash bei schalten von homematic aktor

### ISSUE THREAD

**Issue by jmeinicke** [thkl/homebridge-homematic#82]
Hi,

NodeJS:  nodejs                               6.9.2-1nodesource1~jessie1
Homebridge:                                    homebridge@0.4.16

ich habe mit der aktuellen git Version das Problem, wenn ich einen Homematic Aktor über Apple Homekit schalte, dass  dann Homebridge crasht und in eine Restartschleife kommt. Ich stope dann homebridge und starte es dann wieder, bis zum nächsten schalten. Bei nicht Homematic Schaltern habe ich das Problem nicht. 

`Dec 22 07:49:01 pi homebridge[1265]: [2016-12-22 07:49:01] [HomeMatic CCU] (Rpc) Send true to Datapoint STATE at BidCos-RF.NEQ0135205:1
Dec 22 07:49:02 pi homebridge[1265]: /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:209
Dec 22 07:49:02 pi homebridge[1265]: this.log.debug("RPC setValue (%s %s) Response %s Errors: %s",channel, datapoint, JSON.stringify(value),error);
Dec 22 07:49:02 pi homebridge[1265]: ^
Dec 22 07:49:02 pi homebridge[1265]: TypeError: Cannot read property 'log' of undefined
Dec 22 07:49:02 pi homebridge[1265]: at /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:209:7
Dec 22 07:49:02 pi homebridge[1265]: at Deserializer.callback (/usr/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:42:7)
Dec 22 07:49:02 pi homebridge[1265]: at Deserializer.onDone (/usr/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
Dec 22 07:49:02 pi homebridge[1265]: at emitNone (events.js:86:13)
Dec 22 07:49:02 pi homebridge[1265]: at SAXStream.emit (events.js:185:7)
Dec 22 07:49:02 pi homebridge[1265]: at Object.SAXStream._parser.onend (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:171:8)
Dec 22 07:49:02 pi homebridge[1265]: at emit (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:325:33)
Dec 22 07:49:02 pi homebridge[1265]: at end (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:363:3)
Dec 22 07:49:02 pi homebridge[1265]: at Object.end (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:137:24)
Dec 22 07:49:02 pi homebridge[1265]: at SAXStream.end (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:209:16)
Dec 22 07:49:02 pi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Dec 22 07:49:02 pi systemd[1]: Unit homebridge.service entered failed state.
`

Kennst Du das Problem?

**Comment by thkl** [comment]
sollte wieder gehen ...

**Comment by jmeinicke** [comment]
jepp. geht wieder. 

Und Danke für die klasse Arbeit!
