### ISSUE TITLE
update auf 0.0.63 hat alle Raumzuordnungen der Home.app entfernt

### ISSUE THREAD

**Issue by udochrist** [thkl/homebridge-homematic#84]
Nach dem Update auf die aktuellste Version sind alle Geräte jetzt wieder im "Default Room" zugeordnet in der Home.app.

**Comment by Apollon77** [comment]
ggf kommt das daher: https://github.com/thkl/homebridge-homematic/issues/56#event-908491310

**Comment by udochrist** [comment]
Ja. Alle raumzuordnungen, Namen, Szenen und notifications oder sonstige Geräteeinstellungen sind damit verloren. 2h Zeit wieder alles einzurichten. Das wäre eine Release Warnung wert gewesen damit man das einplanen kann nach dem Update und nicht blind ins Messer läuft.

**Comment by thkl** [comment]
Hmm ich kann mir nicht erklären warum das passiert ist, denn nur weil sich der ein oder andere Name ändert sollte die Zuordnung der restlichen Geräte nicht kaputt gehen ...

**Comment by udochrist** [comment]
Ich schon. Meine Geräte heißen alle
(Raum).(gerät).(funktion)

Wenn da punkte durch blanks ersetzt werden ist halt alles kaputt

**Comment by thkl** [comment]
ah ok ... sorry dann läuft das auf den Poller ... hat denn Siri was damit anfangen können ?

**Comment by udochrist** [comment]
Nach der kompletten neukonfiguration dann wieder. Ich hatte vorher keine Probleme damit.
