### ISSUE TITLE
unable to update system variables in 0.0.63

### ISSUE THREAD

**Issue by cschacht** [thkl/homebridge-homematic#85]
Hi,

I'm using a boolean system variable to track presence of a person. In Home App I have a Ge-fence trigger to switch the variable state and based on that state other actions are triggered. 

Used to work perfectly in previous version but in 0.0.63 I can't change the variable state any more. not through a scene nor through toggling the state (since variables are exposed as switches).

I'm not 100% sure this is due to homebridge but I switched off everything else I can think of which could possibly modify the variable. At least switching the variabel manually should work so my best guess is that it has come with a recent update.

Cheers
Christian

**Comment by thkl** [comment]
hmm sorry, i am not able to reproduce that issue, because it works for me. i was able to switch a variable with the original apple home app. i also used that "variable-switch" in a scene.. this also works fine in 0.0.63.

**Comment by cschacht** [comment]
I've done a few tests creating a new system variable and checking if I can set through Eve. 

It seems that as long as the name of the variable doesn't contain a hyphen ('-') everything works as expected. I created a variable "Test-A". When I start homebridge it gives a message 

`Initializing platform accessory 'TEST A'`

So the name without the hyphen. If I do the same with variable "TESTA" or even "TEST A" it works as expected.

**Comment by thkl** [comment]
Ah ok you're right. With the latest version, i fixed https://github.com/thkl/homebridge-homematic/issues/56 .

If a name of an actor contains a - or : you are unable to use that actor with Siri.  

This has no effect for normal actors, cause Im using the internal address to access them on the rpc interface . But I forgot to check side effects at variables - and here they are.   

Ok i think, i know how to fix this. 

Thank you for investigating in this issue

**Comment by cschacht** [comment]
Sure :-)

**Comment by cschacht** [comment]
On second thoughts, could the description field be used here? In my scenario I can't change the variable name but the description. Also better for Siri, isn't it? If the description is empty, then variable name could be a fall back.

**Comment by thkl** [comment]
As far as i know, there is no way to set the description field. 
i fixed the issue in the current github version.

**Comment by cschacht** [comment]
I can set the description field in the admin UI for the CCU? Thanks for the quick fix!

**Comment by thkl** [comment]
Yes, but there is no homekit characteristic for the description. This is a client only feature.

**Comment by cschacht** [comment]
I meant to use the ccu description as name for the switch in homekit

**Comment by thkl** [comment]
I think this is not necessary. Currently the system will replace any - or : with a space. So, if the variable is named "Test-A", it will set to homekit as "Test A". I tried the Siri command "switch Test A on", and this works .

**Comment by cschacht** [comment]
In my scenario I can't change the name of the variable in the CCU (because it's being created by another application) but I could change the description. But no matter. I can also change the Siri name in Eve. If there a fix for the issue yet I can pull via npm?

**Comment by thkl** [comment]
no, you do not have to change anything in the ccu yet. It just works like the version before. only the name in homekit has changed a little. is this a big deal ? 
npm update should work.

**Comment by cschacht** [comment]
No issue. Everything works perfectly again :-) Thank you!
