### ISSUE TITLE
HmIP BSM Messfunktion

### ISSUE THREAD

**Issue by masetho** [thkl/homebridge-homematic#86]
Hallo,

Ich habe gerade den Wandschalter HmIP BSM installiert.
Dieser hat auch eine Messfunktion für Spannung, Strom usw. 
In der CCU2 wird die Messfunktion auch korrekt angezeigt. 
Leider wird mir in der EVE App zwar die Messfunktion angezeigt, nur sind die Werte alle bei 0 Obwohl das Licht eingeschaltet.

Grüße

**Comment by thkl** [comment]
Ja, der vorhandene Service für PowerMeter ist für die Steckdose ausgelegt.
Ich müsste den etwas anpassen, da der Schalter andere Kanäle nutzt

**Comment by cschacht** [comment]
Gibt es auch für die nicht-IP Version des Schaltmess-Steckdose die Möglichkeit die aktuelle Leistungsaufnahme zu sehen?

**Comment by thkl** [comment]
Muss ich mal schauen, geht sicher

**Comment by cschacht** [comment]
Ich habe mal den Leistungs-Sensor in das Gewerk Homekit getan. Der Sensor erscheint aber nicht im Homekit. Mache ich was falsch?

**Comment by thkl** [comment]
Welchen Typ ?

**Comment by cschacht** [comment]
Die nicht IP Variante ("HM-ES-PMSw1-Pl") und ich habe den Messwert-Kanal ausgewählt.

**Comment by thkl** [comment]
Sollte eigentlich gehen wenn der POWERMETER Channel (2) genommen wird. Der STATE (1) wird automatisch mit hinzugefügt.

**Comment by cschacht** [comment]
Yup, der Kanal 2 *und* der Kanal 1 sind im Gewerk Homekit. Reicht es, nur den Kanal 2 zu wählen?

**Comment by cschacht** [comment]
OK, kaum macht man es richtig, schon geht es ;-) Ich hab jetzt nur den Kanal 2 ins Homekit Gewerk getan und sowohl der Schalter als auch die Leistung werden angezeigt. Danke!

**Comment by teewurstbrot84** [comment]
Ist zwar schon sehr alt hier, aber eine Anpassung für Hmip-BSM wäre top. Die Auswertung liegt weiterhin bei null. Hmip-PSM funktionieren dagegen hervorragend.
