### ISSUE TITLE
HMIP supported devices?

### ISSUE THREAD

**Issue by cschacht** [thkl/homebridge-homematic#87]
Hi Thomas,

I wonder if there is a list of the HMIP devices currently supported? 

Specifically I'm interested in Homematic IP Floor Heating Actuator and the corresponding Thermostat. 

In general, I understand I need to register the HMIP devices with the CCU2?

Regards
Christian

**Comment by thkl** [comment]
Hi Christian, 

there is currently support for the wall thermostat , the ventdrive and switching actors (also with measurement).

i have to take a look on to the documentation for the floor heating actor to figure out how i can support that device.

**Comment by cschacht** [comment]
I might buy one soon. Once I have one I could do some testing.
