### ISSUE TITLE
Service: Taster einbinden

### ISSUE THREAD

**Issue by Lichterloh** [thkl/homebridge-homematic#88]
Hallo zusammen,
ich würde gerne die 4 Kanal Taster Schnittstelle einbinden (HM-PBI-4-FM). Über Homekit möchte ich gerne eine Aktion auslösen, wenn der Taster lang gedrückt wird.
Gibt es für Taster schon eine vordefinierte Service Klasse? 
Meine Idee ist es über Homekit Automatisierung und den Taster ein Event an ein anderes Homekit Device auszulösen.
Hat damit sonst schon jemand Erfahrungen gemacht?

Gruß,
Fabian

**Comment by thkl** [comment]
Ja, man kann die Key Kanäle zu Homekit hinzufügen. Die gehen dann als Input Device .
Funktioniert mit Eve aber soweit ich das sehe weigert sich die Apple Home App die zu erkennen.
