### ISSUE TITLE
Thermostat liefert keine (aktuelle) Temperatur

### ISSUE THREAD

**Issue by irrwitzer42** [thkl/homebridge-homematic#89]
Hallo THKL,

zu allererst mal vielen Dank für Dein großartiges Werk und den Eifer, mit dem Du es ständig verbesserst!
Ich bin noch super neu in diesem ganzen Homeautomatisierungsthema und stelle jetzt vielleicht zwei super dumme Fragen, wenn das so ist, bitte ich um Nachsicht.

Ich habe zum testen erstmal zwei HM-CC-RT-DN  an einer CCU2, die ich mit homebridge-homematic an HomeKit binden und dann mit myHome, Eve und Apple's Home.app verwalten/steuern möchte.

homebridge-homematic und homebridge habe ich in den jeweils aktuellen NPM Versionen (homematic in 0.0.65) am Laufen. Die HomeKit Apps zeigen die beiden Thermostate auch an und ich kann mit Scenes die Soll-Temperatur wunderbar vorgeben. Homebridge loggt dann auch ein entsprechendes "Send" Event an das Thermostat und das fügt sich dem Befehl.

Nun das Problem: Die aktuelle IST Temperatur der Thermostate wird mir in HomeKit mit konstanten 22.6 Grad angezeigt, obwohl sie sich natürlich ständig ändert. Auch sehe ich im Homebridge Log kein einziges Empfangs-Event einer aktuellen Temperatur.
Ich habe auf der CCU2 eigentlich nur die beiden Devices dem "Gewerk" (das Wort finde ich immer wieder irritierend) hinzugefügt, recht viel mehr habe ich nicht getan.
Muss ich sonst noch etwas tun, um ein regelmäßiges Temperturupdate an HomeKit gesendet zu bekommen?

Eine andere Frage noch: Welche Auswirkung hat der HomeKit Schalter "Heat" (on/off) bei diesen Thermostaten? Diese entscheiden doch selbständig, ob geheizt werden muss, oder nicht - und laut HomeKit stehen sie quasi immer auf "Heating", auch wenn die SOLL-Temperatur weit unter der IST-Temperatur liegt.

Ich glaube nicht, dass es sich hierbei um ein Issue handelt, zumindest nicht eines an Deinem Code... sorry, dass ich es hier trotzdem als solches eröffnen musste.

Danke und Grüße,

   Irrwitzer

**Comment by thkl** [comment]
Nabend, 

zuerst die 2. Frage . Das HomeKit Thermostat hat einen vorgegebenen Datenpunkt für Heizen/Kühlen/Aus .. diesen muss ich irgendwie füllen, da aber das Homematic Gerät nur Heizen kann steht der permanent auf Heating.

zum 1. Problem. Ja ich habe auch schon festgestellt, das einige Events scheinbar nicht verarbeitet werden. Das bin ich aktuell am prüfen.

**Comment by irrwitzer42** [comment]
Hi,

Hast Du zu der nicht aktualisierten Sensorthematik schon was finden können?

Ich hab mir mal mit tcpdump angeschaut, was da überhaupt so zwischen der CCU2 und der Homebridge hin und her geht. Dabei wird schnell klar, dass die CCU2 nicht das Problem ist, sie reported fleissig Daten an die Homebridge.
Würde die Homebridge die empfangenen Werte der CCU2 auch loggen?
Homebridge-hue loggt beispielsweise:

[1/15/2017, 5:17:48 PM] [Hue] Hue temperature sensor 2: set homekit temperature from 22.1˚C to 22.2˚C on Sun Jan 15 2017 17:17:47

prinzipiell "gehts" also noch.

Ich verwende noch ein anderes homebridge addon, das aktuell Probleme macht: homebridge-people.
Das hat seit ich es verwende, aber laut issue reports erst in jüngster Vergangenheit das Problem, dass Trigger nicht mehr verlässlich ausgelöst werden, sondern immer nur dann, wenn man eine homekit App startet:
https://github.com/PeteLawrence/homebridge-people/issues/27
Eventuell hängen diese Probleme elementar zusammen?

Zu 2) Unter den von der CCU2 gesendeten Werten sind ja auch so tolle Werte wie 

CONTROL_MODE
BATTERY_STATE
VALVE_STATE
BOOST_STATE
ACTUAL_TEMPERATURE
PARTY_*

Von den Elgato Eve Thermo, die ich ausprobiert, mich dann aber doch für die Homematic Thermostate entschieden habe, weiss ich, dass zumindest die Eve und die MyHome App Batteriestatus, Heizung an/aus auch sauber anzeigen kann.
Du schreibst, Du musst den Datenpunkt "Heizen/Kühlen/Aus" entsprechend füllen - dann muss man doch an Hand von dem Valve-Status auch recht einfach einen sinnvollen Wert an Homekit exportieren können?
Meine coding skills sind unterirdisch, aber ich werd versuchen an Hand Deines Codes mal zu verstehen, wie die ganzen Komponenten zusammenspielen, vielleicht kann ich das ja selbst noch einbauen - außer Du sagst, das geht aus irgendeinem Grund nicht.

Danke und Grüße,
 Irrwitzer

**Comment by thkl** [comment]
Du kannst das ganze im Debug Modus laufen lassen. Start dann mit : 

DEBUG=* homebridge -D

Dann müsstest Du nach 

`
[1/16/2017, 6:56:08 PM] [HomeMatic CCU] RPC event for BidCos-RF.LEQ0420377:4 ACTUAL_TEMPERATURE with value 20.2
[1/16/2017, 6:56:08 PM] [HomeMatic CCU] RPC event for BidCos-RF.LEQ0420377:4 SET_TEMPERATURE with value 20
`

Das wäre der Event wenn das Thermostat mit der Seriennummer LEQ0420377 seine Temperatur reportet.

Irgendwie sollte das für Deine Geräte auch auftauchen ....
