### ISSUE TITLE
Gerätestatusabfrage ist langsam, wenn ein Gerät nicht erreichbar ist

### ISSUE THREAD

**Issue by jp112sdl** [thkl/homebridge-homematic#91]
Ist ein HM-Gerät nicht erreichbar (CCU2 Servicemeldung "Kommunikation gestört") und Bestandteil des Gewerks Homekit, dauert es mitunter über 1 Minute, bis der Status aller anderen HM-Geräte des Gewerks angezeigt wird.
Währenddessen wird in Elgato Eve der Loading-Circle oder ein rotes Ausrufezeichen an allen Sensoren/Aktoren angezeigt. 

Aktualisiert man den Status der HM-Geräte in der App nach ein paar Minuten, ist alles sofort wieder da.

Rein subjektiv tritt dieses verzögerte Verhalten erst nach einiger Laufzeit des Homebridge-Prozesses auf. 
Startet man ihn neu, geht die HM-Gerätestatusabfrage erstmal eine Weile schnell, trotz der Nicht-Erreichbarkeit eines HM-Gerätes.

**Comment by thkl** [comment]
Könnte daran liegen, das die Rückantwort der CCU so lange braucht. Bei einer Geräteabfrage durch HomeKit wird der der Cache verworfen und der Status aus der CCU abgefragt.  Während der Laufzeit wird der Status über die eintreffenden Events aktualisiert.

**Comment by jp112sdl** [comment]
Gut, danke, das hat mir schon mal weitergeholfen. Scheinbar liegt es auch nicht am -homematic Plugin, sondern evtl. am -http Plugin. 

Daher kurze Frage noch: Werden homebridge-Plugins seriell abgearbeitet? Also bspw. erst wenn das http-Plugin eine Antwortet bekommt (oder ein Timeout), wird anschließend -homematic abgearbeitet. Ist das so?

**Comment by thkl** [comment]
Nein, das läuft weitesgehend parallel. Soweit node dazu in der Lage ist
