### ISSUE TITLE
HomeKit verliert Konfiguration

### ISSUE THREAD

**Issue by Omega236** [thkl/homebridge-homematic#92]
Hallo. 

Wenn ich alles vom Strom nehme und alles gleichzeitig hochfahren lasse (oder vielleicht auch wenn ich iPad während dem hochfahren verwende) verliert HomeKit alle Einstellungen (Räume und Namen ...)
Ich achte zwar darauf dass ich normal ccu2 - fritzbox - raspberry - iPad anschalte. Aber scheinbar seit ich noch einen Apple TV habe funktioniert das auch nicht mehr. 

Hat jemand Tipps um das Problem zu umgehen?

**Comment by sirdir1972** [comment]
Genau, ähnliches Problem: Nach einem Neustart der Homebridge verliert HomeKit manchmal einen Teil seiner Konfiguration (gewisse Änderungen Rückgängig gemacht), ausserdem funktioniert es manchmal gar nicht (Homebridge wird durch Homekit nicht gefunden). Ein Neustart von Homebridge hilft dann manchmal...?

**Comment by JensBonse** [comment]
Damit das HomeBridge-HomeMatic Plug-In die Geräte nciht verliert, falls die HomeBridge vor der CCU gestartet wird etc. gibt es eine Einstellung die man in der config.json machen kann, damit die Daten von der CCU gecached werden.
Fügt folgendes in der config.json ein:
`"lcache":true`
Ggf. noch ein Komma am Ende nach dem true!

Die Kommunikation von HomeBridge mit der CCU wird dann zwar nicht funktionieren, doch man verliert zumindest seine Einstellungen nicht. Was unter umständen einiges an Zeit kosten kann diese erneut zu machen.

Also falls das der Fall gewesen sein sollte, das die HomeBridge vor der CCU online war, dann einfach den HomeBridge Service neustarten.
