### ISSUE TITLE
CCU Channels

### ISSUE THREAD

**Issue by saminowak** [thkl/homebridge-homematic#93]
Hallo,
seit dem letzten Update, erscheinen alle 50 CCU-Channels. Wie kann ich diese ausblenden (z.B. "filter_channel": ["HM-RCV-50 BidCoS-RF:1", usw.) oder CCU Settings "sichtbar"?
Danke schon mal für die Hilfe :-)

**Comment by dkrizic** [comment]
Nimm die CCU bzw. die Virtual Channels aus dem Gewerk für Homebridge raus.

**Comment by saminowak** [comment]
Danke.
filter_channel": ["HM-RCV-50 BidCoS-RF:1", usw.] brachte leider nicht den gewünschten Effekt.
Hast Du evtl. einen Tipp für mich? Danke

**Comment by thkl** [comment]
Nope, Du musst die Virtuellen Tasten in der CCU aus dem Homebridge Gewerk löschen.
Das geht im WebGUI der CCU in der Geräteliste
