### ISSUE TITLE
Make local cache directory configurable

### ISSUE THREAD

**Issue by Apollon77** [thkl/homebridge-homematic#96]
On a new installation I followed https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/ to setup homebridge for systemd and anything ... but this means that the hard coded path to the ccu.json is now no longer working. Can you make the path configurable? Or does homebridge provide a way to get the config or persist directory?

**Comment by thkl** [comment]
see https://github.com/thkl/homebridge-homematic/commit/1e778941dfd578d093ca7bc612bdf9d81488a602

**Comment by Apollon77** [comment]
great, thank you! Then I wait for next release ... should be 0.67 then, or ?!

**Comment by thkl** [comment]
If there are no more things to do, I will publish that soon.
