### ISSUE TITLE
Benachrichtigungen erscheinen unerwartet

### ISSUE THREAD

**Issue by udochrist** [thkl/homebridge-homematic#98]
irgendwie verhält sich das Thema Status Benachrichtigungen sehr komisch bei mir:
- ich nutze nur die apple home.app, kein eve o.ä.
- ios10=true in der config, iOS 10.2.1 auf dem gerät
- Türkontakte sind nicht über die door section konfiguriert, dafür in der app als Kontakt des Typs door angelegt.
- Türkontakte sind in der app auf Benachrichtigung gestellt.
- die Bedienung aller Komponenten funktioniert
- Apple TV mit homekit ist konfiguriert für remote zugriff

was falsch erscheint ist die art/der Zeitpunkt wann die Benachrichtigungen erscheinen.
in über 90% der fälle erscheint die info dass eine Tür geschlossen wurde wenn ich die app öffne (und dann direkt hintereinander für alle Türen) oder wenn ich das homekit Favoriten Feld von unten aus dem handy hochziehe. der fall sieht aus, als ob entweder die homematic-homebridge die status der Türen nur auf anfrage liefert und dann quasi alle verschickt wenn nach dem ersten gefragt wird, oder wenn der interne cache der status verloren geht und wieder neu gefüllt wird wenn eine Tür angefragt wird.

weitere infos/logs/rückfragen gerne
Udo

**Comment by JensBonse** [comment]
Ich kenne dieses Verhalten auch. Da ich jedoch zwei HomeBridges habe, wovon bei einer nur  HomeMatic und die zweite für andere IoT Geräte genutzt wird, wie z.B. netatmo. Da es bei beiden auftritt, vermute ich, dass es nicht homebridge-homematic schuld ist, sondern das es an der homebridge selber liegt.

**Comment by dkrizic** [comment]
Ich habe das gleiche Setup (ios10=true, Home App, Tür- und Fensterkontakte, Apple TV 4) und bei mir kommen die Notifications sofort.

**Comment by JensBonse** [comment]
Ja, es kommt darauf an, wann man das letzte mal die Home oder EVE App offen hatte. Dann funktioniert es eine Zeit lang 1A und dann wieder nicht mehr. Ich vermute, das bei der homebridge im Hintergrund mit der Zeit irgend eine Verbindung geschlossen wird.

**Comment by thkl** [comment]
Ich konnte das mit der HomeApp nachvollziehen. Das ist aber eher ein Homekit Problem. Teilweise kommen die Benachrichtigungen auch Stunden später, der Zustand in HomeKit wurde aber schon längst aktualisiert.
