### ISSUE TITLE
Bewegungsmelder deaktivieren

### ISSUE THREAD

**Issue by tkoenig** [thkl/homebridge-homematic#99]
Hallo, gibt es eine Möglichkeit den Bewegungsmelder nur bei Bedarf zu aktivieren (Abwesenheit)?
Die Idee ist irgendwie die Notifications steuern zu können (Keine Notifications bei Anwesenheit). 
Eventuell über eine Variable am Gerät?

**Comment by JensBonse** [comment]
Die Einstellungen die du in der Home oder EVE App machst bzgl. der Benachrichtigung kann man von der HomeBridge nicht ändern. Du könntest vielleicht irgendwie verhindern, das die HomeBridge getriggert wird, in Abhängigkeit der Anwesenheit.
Kurz: Die HomeBridge selber kann keine Einstellungen in HomeKit bzgl. der Notification etc. ändern.

**Comment by thkl** [comment]
Wie oben schon beschrieben. Direkt in Homekit geht das nicht. Ich könnte zwar jetzt über eine Variable aus der CCU die Events welche von den Geräten kommen ignorieren, aber die Implementierung wäre sehr aufwändig (Zuordnung welches Gerät ignoriert werden soll etc)
